# Syllabus {-}

GIS5122: Applied Spatial Statistics

## Contact information {-}

-   Instructor Name: Professor James B. Elsner
-   Instructor Location: Bellamy Building, Room 314
-   Lesson Hours: TR 8:00-9:15 a.m.
-   Student Hours: 

Email: [jelsner@fsu.edu](mailto:jelsner@fsu.edu){.email}

Links to my professional stuff (if you are curious)

-   [Website](http://myweb.fsu.edu/jelsner/_site/)
-   [GitHub](https://github.com/jelsner/)
-   [Mastodon](https://fediscience.org/@jelsner)

## Course description and expected learning outcomes {-}

This course is for students who want to learn how to analyze, map, and model spatial and geographical data using the R programming language. It assumes you know basic statistics through multiple linear regression. And that you have some prior experience with using R. If you have no knowledge of R you should look at various online tutorials (see below).

All the course content is available on GitHub <https://github.com/jelsner/ASS-2023>

In this course you will get a survey of the methods used to describe, analyze, and model spatial data. Focus will be on applications. Emphasis is on how statistical methods are related through the concept of spatial autocorrelation.

Expected learning outcomes

1.  Learn how and when to apply statistical methods and models to spatial data,
2.  learn various packages in R for analyzing and modeling spatial data, and
3.  learn how to interpret the results of a spatial data model.

The course offers a programming approach to exposing you to spatial statistics. I want to demystify the process and give you confidence that you can analyze and fit spatial models. I believe some investment in honing programming skills will pay dividends for you later on.

But in taking this approach I don't want to give you the false impression that statisticians have the answers. A *working* knowledge of the model fitting process needs to be combined with a good understanding of the context in which you are working.

Materials and class meetings {-}

-   Access to the internet and a computer
-   All course materials are available through GitHub <https://github.com/jelsner/ASS-2023>
-   No textbook is required
-   Many excellent online resources are also available. Here are some of my favorites

    -   Data Science <https://r4ds.had.co.nz/>
    -   Tidyverse <https://dominicroye.github.io/en/2020/a-very-short-introduction-to-tidyverse/>
    -   Statistics <https://tinystats.github.io/teacups-giraffes-and-statistics/index.html>
    -   Census data <https://walker-data.com/census-r/wrangling-census-data-with-tidyverse-tools.html>

Class meetings

During each lesson I will work through and explain the R code and notes contained within an `xx-Lesson.Rmd` file. Lessons will be held in this classroom (BEL 320). The notes in the lesson files are comprehensive, so you can work through them on your own if you are unable to make it to class.

The notes are written using the markdown language. Markdown is a way to write content for the Web. An R markdown file has the suffix `.Rmd` (R markdown file). The file is opened using the RStudio application.

## Grades and ethics {-}

You are responsible for:

1.  Reading and running the code in the lesson R markdown files (`.Rmd`) files. You can do this during the lessons as I talk and run my code or outside of class on your own
2.  Completing and returning the lab assignments on time

Grades are determined by how well you do on the assignments using the following standard:

-   A: Outstanding: few, in any, errors/omissions
-   B: Good: only minor errors/omissions
-   C: Satisfactory: minor omissions, at least one major error/omission
-   D: Poor: several major errors/omissions
-   F: Fail: many major errors/omissions

I'll use the +/- grading system.

Grades will be posted as they are recorded on [FSU Canvas](https://canvas.fsu.edu)

Academic honor code

<https://fda.fsu.edu/academic-resources/academic-integrity-and-grievances/academic-honor-policy>

Americans With Disabilities Act

Students with disabilities needing academic accommodation should: (1) register with and provide documentation to the Student Disability Resource Center; (2) bring a letter indicating the need for accommodation and what type. This should be done during the first week of classes.

Diversity and inclusiveness

It is my intent to present notes and data that are respectful of diversity: gender identity, sexuality, disability, age, socioeconomic status, ethnicity, race, nationality, religion, and culture.

## Outline of topics and schedule {-}

January 10 Syllabus
January 12 Lesson 1
January 17 Lesson 2
January 19 Lesson 3
January 24 Lesson 4
January 26 Lab 1
January 31 Lesson 5
February 2 Lesson 6
February 7 Lesson 7
February 9 Lesson 8
February 14 Lab 2
February 16 Lesson 9
February 21 Lesson 10
February 23 Lesson 11
February 28 Lesson 12
March 2 Lab 3
March 7 Lesson 13
March 9 FREE
March 14 Spring Break
March 16 Spring Break
March 21 Lesson 14
March 23 Lesson 15
March 28 Lesson 16
March 30 Lesson 17
April 4 Lesson 18
April 6 Lesson 19
April 11 Lab 4
April 13 Lesson 20
April 18 Lesson 21
April 20 Lesson 22
April 25 Lab 5
April 27 FREE

1.  Working with data and making graphs (4 lessons)
2.  Working with spatial data and making maps (4 lessons)
3.  Quantifying spatial autocorrelation and spatial regression (4 lessons)
4.  Analyzing and modeling point pattern data (7 lessons)
5.  Estimating variograms and interpolating spatially (3 lessons)

27 dates: 22 lesson days + 5 lab days

| Lab | Date                  | Lessons covered |
|-----|-----------------------|-----------------|
| 1   | Thursday January 26   | 1-4             |
| 2   | Tuesday February 14   | 5-8             |
| 3   | Tuesday March 2       | 9-12            |
| 4   | Tuesday April 11      | 13-19           |
| 5   | Tuesday April 25      | 20-22           |

## Reference materials {-}

1.  Bivand, R. S., E. J. Pebesma, and V. G. Gomez-Rubio, 2013: Applied Spatial Data Analysis with R, 2nd Edition, Springer. A source for much of the material in the lesson notes.
2.  Lovelace, R. Nowosad, J. and Muenchow, J. Geocomputation with R. <https://geocompr.robinlovelace.net/> A source for some of the material in the lesson notes.
3.  Healy, K., 2018: Data Visualization: A practical introduction, <https://socviz.co/>. This book teaches you how to really look at your data. A source for some of the early material in the lesson notes.
4.  Waller, L. A., and C. A. Gotway, 2004: Applied Spatial Statistics for Public Health Data, John Wiley & Sons, Inc. (Available as an e-book in the FSU library). Good overall reference material for analyzing and modeling spatial data.
5.  Analyzing US Census Data: Methods, Maps, and Models in R <https://walker-data.com/census-r/index.html>

-   Cheat Sheets: <https://rstudio.com/resources/cheatsheets/>
-   R Cookbook: How to do specific things: <https://rc2e.com/>
-   R for Geospatial Processing: <https://bakaniko.github.io/FOSS4G2019_Geoprocessing_with_R_workshop/>
-   Spatial Data Science: <https://keen-swartz-3146c4.netlify.com/>

Maps/graphs

-   Inset maps: <https://geocompr.github.io/post/2019/ggplot2-inset-maps/>
-   {cartography} package in R: <https://riatelab.github.io/cartography/docs/articles/cartography.html>
-   geovisualization with {mapdeck}: <https://spatial.blog.ryerson.ca/2019/11/21/geovis-mapdeck-package-in-r/>
-   3D elevation with {rayshader}: <https://www.rayshader.com/>
-   3D elevation to 3D printer: <https://blog.hoxo-m.com/entry/2019/12/19/080000>
-   Accelerate your plots with {ggforce}: <https://rviews.rstudio.com/2019/09/19/intro-to-ggforce/>
-   Summary statistics and ggplot: <https://ggplot2tutor.com/summary_statistics/summary_statistics/>

Space-time statistics

-   Space-time Bayesian modeling package: <https://cran.r-project.org/web/packages/spTimer/spTimer.pdf>
-   Working with space-time rasters: <https://github.com/surfcao/geog5330/blob/master/week12/raster.Rmd>

Bayesian models

-   Bayesian Linear Mixed Models: Random intercepts, slopes and missing data: <https://willhipson.netlify.com/post/bayesian_mlm/bayesian_mlm/>
-   Doing Bayesian Data Analysis in {brms} and the {tidyverse}: <https://bookdown.org/ajkurz/DBDA_recoded/>
-   Spatial models with INLA: <https://becarioprecario.bitbucket.io/inla-gitbook/index.html>
-   Geospatial Health Data: Modeling and Visualization with {RINLA} and {shiny}: <https://paula-moraga.github.io/book-geospatial/>
-   Bayesian workflow: <https://betanalpha.github.io/assets/case_studies/principled_bayesian_workflow.html#1_questioning_authority>

Spatial data

-   Progress in the R ecosystem for representing and handling spatial data <https://link.springer.com/article/10.1007/s10109-020-00336-0>
-   Google earthengine: <https://earthengine.google.com/>
-   Burden of roof: Revisiting housing costs with {tidycensus}: <https://austinwehrwein.com/data-visualization/housing/>
-   The Care and Feeding of Spatial Data: <https://docs.google.com/presentation/d/1BHlrSZWmw9tRWfYFVsRLNhAoX6KzhOhsnezTqL-R0sU/edit#slide=id.g6aeb55b281_0_550>
-   Accessing remotely sensed imagery: <https://twitter.com/mouthofmorrison/status/1212840820019208192/photo/1>
-   Spatial data sets from Brazil: <https://github.com/ipeaGIT/geobr>
-   Getting started with R and R-spatial <https://bakaniko.github.io/foss4g2022-getting-started-rspatial/>

Machine learning

-   Supervised machine learning case studies: <https://supervised-ml-course.netlify.com/>
-   Machine learning for spatial prediction: <https://www.youtube.com/watch?v=2pdRk4cj1P0&feature=youtu.be>
-   Machine learning on spatial data: <https://geocompr.robinlovelace.net/spatial-cv.html>

Spatial networks

-   Spatial Networks in R with {sf} and {tidygraph}: <https://www.r-spatial.org/r/2019/09/26/spatial-networks.html>
<https://github.com/sfnetworks/foss4g-workshop>
-   Travel times/distances: <https://github.com/rCarto/osrm>
-   Making network graphs in R - {ggraph} and {tidygraph} introduction <https://youtu.be/geYZ83Aidq4>

Transport planning/routing

<https://docs.ropensci.org/stplanr/index.html> <https://www.urbandemographics.org/post/r5r-fast-multimodal-transport-routing-in-r/>

Time series forecasting

<https://weecology.github.io/MATSS/>

Movement

<https://besjournals.onlinelibrary.wiley.com/doi/pdf/10.1111/1365-2656.13116>

Bookdown

-   Introduction: <https://bookdown.org/yihui/bookdown/introduction.html>
-   Learning more: <https://ropensci.org/blog/2020/04/07/bookdown-learnings/>

Climate data

<https://waterdata.usgs.gov/blog/dataretrieval/>

Traditional reference books on the theory and application of spatial statistics.

-   Anselin, L., 2005: Spatial Regression Analysis in R, Spatial Analysis Laboratory, Center for Spatially Integrated Social Science.
-   Baddeley, A., and R. Turner, 2005: spatstat: An R Package for Analyzing Spatial Point Patterns, Journal of Statistical Software, v12.
-   Blangiardo, M., and M. Cameletti, 2015: Spatial and Spatio-temporal Bayesian Models with R-INLA, John Wiley & Sons, Inc., New York. An introduction to Bayesian models for spatial data.
-   Cressie, N. A. C., 1993: Statistics for Spatial Data, Wiley Series in Probability and Mathematical Statistics, John Wiley & Sons, Inc., New York. A mathematical treatment of spatial data analysis.
-   Cressie, N. A. C., and C. K. Wikle, 2011: Statistics for Spatio-Temporal Data, Wiley Series in Probability and Mathematical Statistics, John Wiley & Sons, Inc., New York. A mathematical treatment of space-time statistics with an emphasis on Bayesian models.
-   Diggle, P. J., 2003: Statistical Analysis of Spatial Point Patterns, Second Edition, Arnold Publishers. An introduction to the concepts and methods of statistical analysis of spatial point patterns.
-   Fotherhingham, A. S., C. Brunsdon, and M. Charlton, 2000: Quantitative Geography: Perspectives on Spatial Data Analysis, SAGE Publications, London. A survey of spatial data analysis from the perspective of modern geography.
-   Haining, R., 2003: Spatial Data Analysis: Theory and Practice, Cambridge University Press. A confluence of geographic information science and applied spatial statistics.
-   Illian, J., A. Penttinen, H. Stoyan, and D. Stoyan, 2008: Statistical Analysis and Modeling of Spatial Point Patterns, Wiley Series in Statistics in Practice, John Wiley & Sons, Inc., New York. A mathematical treatment of spatial point processes.
-   Ripley, B. D., 1981: Spatial Statistics, Wiley, New York. A reference book on spatial data analysis with emphasis on point pattern analysis.
-   Wickham, H., 2009: ggplot2: Elegant Graphics for Data Analysis, Springer UseR! Series, Springer, New York. An introduction to the ggplot package for graphics.

Recent research examples

-   [More hots](https://eartharxiv.org/q4y8z/)
-   [Stronger tornadoes](https://eartharxiv.org/wpkt9/)

## Reproducible research {-}

A scientific paper has at least two goals: announce a new result and convince readers that the result is correct. Scientific papers should describe the results *and* provide a clear protocol to allow repetition and extension.

Analysis and modeling tools should integrate text with code to make it easier to provide a clear protocol of what was done.

-   Such tools make doing research efficient. Changes are made with little effort.
-   Such tools allow others to build on what you've done. Research achieves more faster.
-   Collaboration is easier.
-   Code sharing leads to greater research impact. Research impact leads to promotion & tenure.

Free and open source software for geospatial data has progressed at an astonishing rate. High performance spatial libraries are now widely available.

However, much of it is still not easy to script. Open source Geographic Information Systems (GIS) like QGIS (see <https://qgis.org>) have greatly reduced the 'barrier to entry' but emphasis on the graphical user interface (GUI) makes reproducible research difficult.

Instead here we will focus on a command line interface (CLI) to help you create reproducible work flows.

You might be interested in this article: [Practical reproducibility in geography and geosciences](https://myweb.fsu.edu/jelsner/NustPebesma2020.pdf)

## Install R and RStudio on your computer {-}

First get R

-   Go to <http://www.r-project.org>
-   Select the CRAN (Comprehensive R Archive Network). Scroll to a mirror site
-   Choose the appropriate file for your computer
-   Follow the instructions to install R

Then get RStudio

-   Go to on <http://rstudio.org>
-   Download RStudio Desktop
-   Install and open RStudio

Finally, learn how to connect to GitHub (optional). See Jennifer Bryan's Happy Git and GitHub for R.

<https://happygitwithr.com/install-git.html>

## Download course materials {-}

-   Navigate to [https://github.com/jelsner/ASS-2023](https://github.com/jelsner/ASS-2023)
-   Click on the bright green Code button
-   Download ZIP
-   Unzip the file on your computer
-   Open the `ASS-2023.Rproj` file

## Read the syllabus {-}

-   Open the `00-Syllabus.Rmd` file under the `Files` tab

