<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Thursday October 27, 2022 | GIS5122: Applied Spatial Statistics</title>
  <meta name="description" content="Thursday October 27, 2022 | GIS5122: Applied Spatial Statistics" />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="Thursday October 27, 2022 | GIS5122: Applied Spatial Statistics" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="jelsner/ASS-2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Thursday October 27, 2022 | GIS5122: Applied Spatial Statistics" />
  
  
  

<meta name="author" content="James B. Elsner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tuesday-october-25-2022.html"/>
<link rel="next" href="tuesday-november-1-2022.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.1.1/leaflet.js"></script>
<script src="libs/leaflet-providers-1.9.0/leaflet-providers_1.9.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.1.1/leaflet-providers-plugin.js"></script>
<script src="libs/Leaflet.Sync-0.0.5/L.Map.Sync.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied Spatial Statistics</a></li>

<li class="divider"></li>
<li><a href="index.html#section"></a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i>Syllabus</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#contact-information"><i class="fa fa-check"></i>Contact information</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#course-description-and-expected-learning-outcomes"><i class="fa fa-check"></i>Course description and expected learning outcomes</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#materials-and-class-meetings"><i class="fa fa-check"></i>Materials and class meetings</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#grades-and-ethics"><i class="fa fa-check"></i>Grades and ethics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#outline-of-topics-and-schedule"><i class="fa fa-check"></i>Outline of topics and schedule</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#reference-materials"><i class="fa fa-check"></i>Reference materials</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#reproducible-research"><i class="fa fa-check"></i>Reproducible research</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html"><i class="fa fa-check"></i>Tuesday, August 23, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#install-r-and-rstudio-on-your-computer"><i class="fa fa-check"></i>Install R and RStudio on your computer</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#download-course-materials"><i class="fa fa-check"></i>Download course materials</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#read-the-syllabus"><i class="fa fa-check"></i>Read the syllabus</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#about-rstudio"><i class="fa fa-check"></i>About RStudio</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#lab-assignments"><i class="fa fa-check"></i>Lab assignments</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#getting-started-with-r"><i class="fa fa-check"></i>Getting started with R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#are-you-completely-new-to-r"><i class="fa fa-check"></i>Are you completely new to R?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html"><i class="fa fa-check"></i>Thursday, August 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#expectations"><i class="fa fa-check"></i>Expectations</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-science-workflow-with-r-markdown"><i class="fa fa-check"></i>Data science workflow with R markdown</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#an-introduction-to-using-r"><i class="fa fa-check"></i>An introduction to using R</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-frames"><i class="fa fa-check"></i>Data frames</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html"><i class="fa fa-check"></i>Tuesday August 30, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#working-with-data-frames"><i class="fa fa-check"></i>Working with data frames</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html"><i class="fa fa-check"></i>Thursday September 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#making-graphs"><i class="fa fa-check"></i>Making graphs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html"><i class="fa fa-check"></i>Thursday September 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#working-with-spatial-data"><i class="fa fa-check"></i>Working with spatial data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#geo-computation-on-simple-features"><i class="fa fa-check"></i>Geo-computation on simple features</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html"><i class="fa fa-check"></i>Tuesday September 13, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#spatial-data-subsets-and-joins"><i class="fa fa-check"></i>Spatial data subsets and joins</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#interpolation-using-areal-weights"><i class="fa fa-check"></i>Interpolation using areal weights</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html"><i class="fa fa-check"></i>Thursday September 15, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#s4-spatial-data-objects"><i class="fa fa-check"></i>S4 spatial data objects</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#working-with-raster-data"><i class="fa fa-check"></i>Working with raster data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html"><i class="fa fa-check"></i>Tuesday September 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#working-with-space-time-data"><i class="fa fa-check"></i>Working with space-time data</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#mapping-using-functions-from-the-ggplot2-package"><i class="fa fa-check"></i>Mapping using functions from the {ggplot2} package</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#mapping-using-functions-from-the-tmap-package"><i class="fa fa-check"></i>Mapping using functions from the {tmap} package</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#creating-an-interactive-map"><i class="fa fa-check"></i>Creating an interactive map</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#adding-an-inset-map"><i class="fa fa-check"></i>Adding an inset map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-27-2022.html"><a href="tuesday-september-27-2022.html"><i class="fa fa-check"></i>Tuesday September 27, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-27-2022.html"><a href="tuesday-september-27-2022.html#defining-spatial-neighborhoods-and-spatial-weights"><i class="fa fa-check"></i>Defining spatial neighborhoods and spatial weights</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-27-2022.html"><a href="tuesday-september-27-2022.html#computing-autocorrelation"><i class="fa fa-check"></i>Computing autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-27-2022.html"><a href="tuesday-september-27-2022.html#spatial-lag-and-its-relation-to-autocorrelation"><i class="fa fa-check"></i>Spatial lag and its relation to autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html"><i class="fa fa-check"></i>Thursday September 29, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#other-neighbor-definitions"><i class="fa fa-check"></i>Other neighbor definitions</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#assessing-the-statistical-significance-of-autocorrelation"><i class="fa fa-check"></i>Assessing the statistical significance of autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#bivariate-spatial-autocorrelation"><i class="fa fa-check"></i>Bivariate spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#local-indicators-of-spatial-autocorrelation"><i class="fa fa-check"></i>Local indicators of spatial autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html"><i class="fa fa-check"></i>Tuesday October 4, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#constraining-group-membership-based-on-spatial-autocorrelation"><i class="fa fa-check"></i>Constraining group membership based on spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#estimating-spatial-autocorrelation-in-model-residuals"><i class="fa fa-check"></i>Estimating spatial autocorrelation in model residuals</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#choosing-a-spatial-regression-model"><i class="fa fa-check"></i>Choosing a spatial regression model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html"><i class="fa fa-check"></i>Thursday October 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#fitting-and-interpreting-a-spatially-lagged-y-model"><i class="fa fa-check"></i>Fitting and interpreting a spatially-lagged Y model</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#fitting-and-interpreting-a-spatially-lagged-x-model"><i class="fa fa-check"></i>Fitting and interpreting a spatially-lagged X model</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#fitting-and-interpreting-spatial-durbin-models"><i class="fa fa-check"></i>Fitting and interpreting spatial Durbin models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html"><i class="fa fa-check"></i>Tuesday October 11, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#fitting-and-interpreting-geographic-regressions"><i class="fa fa-check"></i>Fitting and interpreting geographic regressions</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#mapping-incidence-and-risk-with-spatial-regression-models"><i class="fa fa-check"></i>Mapping incidence and risk with spatial regression models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html"><i class="fa fa-check"></i>Tuesday October 18, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#spatial-data-as-point-patterns"><i class="fa fa-check"></i>Spatial data as point patterns</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#working-with-point-pattern-objects-using-functions-from-the-spatstat-package"><i class="fa fa-check"></i>Working with point pattern objects using functions from the {spatstat} package</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#quantifying-event-intensity"><i class="fa fa-check"></i>Quantifying event intensity</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html"><i class="fa fa-check"></i>Thursday October 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#creating-ppp-and-owin-objects-from-simple-feature-data-frames"><i class="fa fa-check"></i>Creating <code>ppp</code> and <code>owin</code> objects from simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#estimating-spatial-intensity-as-a-function-of-distance"><i class="fa fa-check"></i>Estimating spatial intensity as a function of distance</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#intensity-trend-as-a-possible-confounding-factor"><i class="fa fa-check"></i>Intensity trend as a possible confounding factor</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html"><i class="fa fa-check"></i>Tuesday October 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#estimating-the-relative-risk-of-events"><i class="fa fa-check"></i>Estimating the relative risk of events</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#estimating-second-moment-properties-of-spatial-events"><i class="fa fa-check"></i>Estimating second-moment properties of spatial events</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html"><i class="fa fa-check"></i>Thursday October 27, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#examples-of-spatially-clustered-events"><i class="fa fa-check"></i>Examples of spatially clustered events</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#determining-the-statistical-significance-of-event-clustering"><i class="fa fa-check"></i>Determining the statistical significance of event clustering</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#estimating-event-clustering-in-multi-type-event-locations"><i class="fa fa-check"></i>Estimating event clustering in multi-type event locations</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#more-about-the-ripley-k-function"><i class="fa fa-check"></i>More about the Ripley K function</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html"><i class="fa fa-check"></i>Tuesday November 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#inferring-event-interaction-from-distance-functions"><i class="fa fa-check"></i>Inferring event interaction from distance functions</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#removing-duplicate-event-locations-and-defining-the-domain"><i class="fa fa-check"></i>Removing duplicate event locations and defining the domain</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#modeling-point-pattern-data"><i class="fa fa-check"></i>Modeling point pattern data</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#fitting-and-interpreting-an-inhibition-model"><i class="fa fa-check"></i>Fitting and interpreting an inhibition model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html"><i class="fa fa-check"></i>Thursday November 3, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#fitting-and-interpreting-a-cluster-model"><i class="fa fa-check"></i>Fitting and interpreting a cluster model</a></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#assessing-how-well-the-model-fits"><i class="fa fa-check"></i>Assessing how well the model fits</a></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#spatial-logistic-regression"><i class="fa fa-check"></i>Spatial logistic regression</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html"><i class="fa fa-check"></i>Thursday November 10, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html#spatial-data-interpolation"><i class="fa fa-check"></i>Spatial data interpolation</a></li>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html#computing-the-sample-variogram"><i class="fa fa-check"></i>Computing the sample variogram</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html"><i class="fa fa-check"></i>Tuesday November 15, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#fitting-a-variogram-model-to-the-sample-variogram"><i class="fa fa-check"></i>Fitting a variogram model to the sample variogram</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#creating-an-interpolated-surface-with-the-method-of-kriging"><i class="fa fa-check"></i>Creating an interpolated surface with the method of kriging</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html"><i class="fa fa-check"></i>Thursday November 17, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#comparing-interpolation-methods"><i class="fa fa-check"></i>Comparing interpolation methods</a></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#evaluating-the-accuracy-of-the-interpolation"><i class="fa fa-check"></i>Evaluating the accuracy of the interpolation</a></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#block-cross-validation"><i class="fa fa-check"></i>Block cross validation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html"><i class="fa fa-check"></i>Thursday November 29, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html#interpolating-to-areal-units-block-kriging"><i class="fa fa-check"></i>Interpolating to areal units (block kriging)</a></li>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html#simulating-spatial-fields"><i class="fa fa-check"></i>Simulating spatial fields</a></li>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html#interpolating-multiple-variables"><i class="fa fa-check"></i>Interpolating multiple variables</a></li>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html#machine-learning-for-spatial-interpolation"><i class="fa fa-check"></i>Machine learning for spatial interpolation</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GIS5122: Applied Spatial Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="thursday-october-27-2022" class="section level1 unnumbered hasAnchor">
<h1>Thursday October 27, 2022<a href="thursday-october-27-2022.html#thursday-october-27-2022" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>“Good code is its own best documentation. As you’re about to add a comment, ask yourself, ‘How can I improve the code so that this comment isn’t needed?’ Improve the code and then document it to make it even clearer.”</strong> - Steve McConnell</p>
<p>Today</p>
<ul>
<li>Examples of spatially clustered events</li>
<li>Determining the statistical significance of event clustering</li>
<li>Estimating event clustering in multi-type event locations</li>
<li>More about the Ripley K function</li>
</ul>
<div id="examples-of-spatially-clustered-events" class="section level2 unnumbered hasAnchor">
<h2>Examples of spatially clustered events<a href="thursday-october-27-2022.html#examples-of-spatially-clustered-events" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Bramble canes</p>
<p>The locations of bramble canes are available as a marked <code>ppp</code> object in the {spatstat} package. A bramble is a rough (usually wild) tangled prickly shrub with thorny stems.</p>
<div class="sourceCode" id="cb1215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1215-1"><a href="thursday-october-27-2022.html#cb1215-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(spatstat))</span>
<span id="cb1215-2"><a href="thursday-october-27-2022.html#cb1215-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1215-3"><a href="thursday-october-27-2022.html#cb1215-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(bramblecanes)</span>
<span id="cb1215-4"><a href="thursday-october-27-2022.html#cb1215-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bramblecanes)</span></code></pre></div>
<pre><code>## Marked planar point pattern:  823 points
## Average intensity 823 points per square unit (one unit = 9 metres)
## 
## Coordinates are given to 3 decimal places
## i.e. rounded to the nearest multiple of 0.001 units (one unit = 9 metres)
## 
## Multitype:
##   frequency proportion intensity
## 0       359 0.43620900       359
## 1       385 0.46780070       385
## 2        79 0.09599028        79
## 
## Window: rectangle = [0, 1] x [0, 1] units
## Window area = 1 square unit
## Unit of length: 9 metres</code></pre>
<p>The marks represent three different ages (as an ordered factor) for the bramble canes. The unit of length is 9 meters.</p>
<div class="sourceCode" id="cb1217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1217-1"><a href="thursday-october-27-2022.html#cb1217-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bramblecanes) </span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-544-1.png" width="672" /></p>
<p>Consider the point pattern for all the bramble canes regardless of age and estimate the <span class="math inline">\(K\)</span> function and a corresponding plot. Plot the empirical estimate of <span class="math inline">\(K\)</span> with an ‘isotropic’ correction at the domain borders (<code>iso</code>). Include a line for the theoretical <span class="math inline">\(K\)</span> under the assumption of CSR.</p>
<div class="sourceCode" id="cb1218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1218-1"><a href="thursday-october-27-2022.html#cb1218-1" aria-hidden="true" tabindex="-1"></a>K.df <span class="ot">&lt;-</span> bramblecanes <span class="sc">|&gt;</span></span>
<span id="cb1218-2"><a href="thursday-october-27-2022.html#cb1218-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Kest</span>() <span class="sc">|&gt;</span></span>
<span id="cb1218-3"><a href="thursday-october-27-2022.html#cb1218-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb1218-4"><a href="thursday-october-27-2022.html#cb1218-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">r =</span> r <span class="sc">*</span> <span class="dv">9</span>)</span>
<span id="cb1218-5"><a href="thursday-october-27-2022.html#cb1218-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1218-6"><a href="thursday-october-27-2022.html#cb1218-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1218-7"><a href="thursday-october-27-2022.html#cb1218-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1218-8"><a href="thursday-october-27-2022.html#cb1218-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> K.df, </span>
<span id="cb1218-9"><a href="thursday-october-27-2022.html#cb1218-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> iso)) <span class="sc">+</span></span>
<span id="cb1218-10"><a href="thursday-october-27-2022.html#cb1218-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb1218-11"><a href="thursday-october-27-2022.html#cb1218-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb1218-12"><a href="thursday-october-27-2022.html#cb1218-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (m)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb1218-13"><a href="thursday-october-27-2022.html#cb1218-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-545-1.png" width="672" /></p>
<p>The <span class="math inline">\(K\)</span> estimate from the actual data (black line) lies to the left of the theoretical <span class="math inline">\(K\)</span> under CSR (red line). This means that for any distance from an event (lag distance) there tends to be <em>more</em> events within this distance (larger <span class="math inline">\(K\)</span>) than expected under CSR. You conclude that these bramble canes are more clustered than CRS.</p>
<p>The expected number of additional events is multiplied by the total number of events (823) so a value of .1 indicates that at a distance of 1.6 meters (where .1 value of <span class="math inline">\(K(r)\)</span> intersects the red curve) you should expect to see about 82 additional events.</p>
<p>Kansas tornado reports</p>
<p>Previously you mapped the intensity of tornadoes across Kansas using the start locations as point pattern data. Here we return to these data and consider only tornadoes since 1994.</p>
<div class="sourceCode" id="cb1219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1219-1"><a href="thursday-october-27-2022.html#cb1219-1" aria-hidden="true" tabindex="-1"></a>Torn.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="at">dsn =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;1950-2020-torn-initpoint&quot;</span>)) <span class="sc">|&gt;</span></span>
<span id="cb1219-2"><a href="thursday-october-27-2022.html#cb1219-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3082</span>) <span class="sc">|&gt;</span></span>
<span id="cb1219-3"><a href="thursday-october-27-2022.html#cb1219-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(mag <span class="sc">&gt;=</span> <span class="dv">0</span>, yr <span class="sc">&gt;=</span> <span class="dv">1994</span>) <span class="sc">|&gt;</span></span>
<span id="cb1219-4"><a href="thursday-october-27-2022.html#cb1219-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">EF =</span> <span class="fu">as.factor</span>(mag)) <span class="sc">|&gt;</span></span>
<span id="cb1219-5"><a href="thursday-october-27-2022.html#cb1219-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(EF)</span></code></pre></div>
<pre><code>## Reading layer `1950-2020-torn-initpoint&#39; from data source 
##   `/Users/jelsner/Desktop/ClassNotes/ASS-2022/data/1950-2020-torn-initpoint&#39; 
##   using driver `ESRI Shapefile&#39;
## Simple feature collection with 66244 features and 22 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -163.53 ymin: 17.7212 xmax: -64.7151 ymax: 61.02
## Geodetic CRS:  WGS 84</code></pre>
<div class="sourceCode" id="cb1221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1221-1"><a href="thursday-october-27-2022.html#cb1221-1" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="ot">&lt;-</span> Torn.sf[<span class="st">&quot;EF&quot;</span>] <span class="sc">|&gt;</span></span>
<span id="cb1221-2"><a href="thursday-october-27-2022.html#cb1221-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.ppp</span>()</span>
<span id="cb1221-3"><a href="thursday-october-27-2022.html#cb1221-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1221-4"><a href="thursday-october-27-2022.html#cb1221-4" aria-hidden="true" tabindex="-1"></a>KS.sf <span class="ot">&lt;-</span> USAboundaries<span class="sc">::</span><span class="fu">us_states</span>(<span class="at">states =</span> <span class="st">&quot;Kansas&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb1221-5"><a href="thursday-october-27-2022.html#cb1221-5" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> sf<span class="sc">::</span><span class="fu">st_crs</span>(Torn.sf)<span class="sc">$</span>proj4string)</span>
<span id="cb1221-6"><a href="thursday-october-27-2022.html#cb1221-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1221-7"><a href="thursday-october-27-2022.html#cb1221-7" aria-hidden="true" tabindex="-1"></a>W <span class="ot">&lt;-</span> KS.sf <span class="sc">|&gt;</span></span>
<span id="cb1221-8"><a href="thursday-october-27-2022.html#cb1221-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.owin</span>()</span>
<span id="cb1221-9"><a href="thursday-october-27-2022.html#cb1221-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1221-10"><a href="thursday-october-27-2022.html#cb1221-10" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="ot">&lt;-</span> T.ppp[W] <span class="sc">|&gt;</span></span>
<span id="cb1221-11"><a href="thursday-october-27-2022.html#cb1221-11" aria-hidden="true" tabindex="-1"></a>  spatstat.geom<span class="sc">::</span><span class="fu">rescale</span>(<span class="at">s =</span> <span class="dv">1000</span>, </span>
<span id="cb1221-12"><a href="thursday-october-27-2022.html#cb1221-12" aria-hidden="true" tabindex="-1"></a>                         <span class="at">unitname =</span> <span class="st">&quot;km&quot;</span>)</span>
<span id="cb1221-13"><a href="thursday-october-27-2022.html#cb1221-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1221-14"><a href="thursday-october-27-2022.html#cb1221-14" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="sc">|&gt;</span></span>
<span id="cb1221-15"><a href="thursday-october-27-2022.html#cb1221-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-546-1.png" width="672" /></p>
<div class="sourceCode" id="cb1222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1222-1"><a href="thursday-october-27-2022.html#cb1222-1" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="sc">|&gt;</span></span>
<span id="cb1222-2"><a href="thursday-october-27-2022.html#cb1222-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## Marked planar point pattern:  2241 points
## Average intensity 0.01038475 points per square km
## 
## *Pattern contains duplicated points*
## 
## Coordinates are given to 4 decimal places
## 
## Multitype:
##   frequency   proportion    intensity
## 0      1623 0.7242303000 7.520953e-03
## 1       436 0.1945560000 2.020416e-03
## 2       104 0.0464078500 4.819342e-04
## 3        64 0.0285586800 2.965749e-04
## 4        13 0.0058009820 6.024177e-05
## 5         1 0.0004462294 4.633982e-06
## 
## Window: polygonal boundary
## single connected closed polygon with 169 vertices
## enclosing rectangle: [1317.6759, 1980.2948] x [7114.969, 7458.57] km
##                      (662.6 x 343.6 km)
## Window area = 215797 square km
## Unit of length: 1 km
## Fraction of frame area: 0.948</code></pre>
<p>There are 2241 events with an average intensity of .01 events per square km (1 tornado per 10 square km over the 26-year period 1994–2020).</p>
<p>You compare the <span class="math inline">\(K\)</span> function estimated from the set of tornado reports with a theoretical <span class="math inline">\(K\)</span> function from a model of CSR.</p>
<div class="sourceCode" id="cb1224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1224-1"><a href="thursday-october-27-2022.html#cb1224-1" aria-hidden="true" tabindex="-1"></a>K.df <span class="ot">&lt;-</span> T.ppp <span class="sc">|&gt;</span></span>
<span id="cb1224-2"><a href="thursday-october-27-2022.html#cb1224-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Kest</span>(<span class="at">correction =</span> <span class="st">&quot;iso&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb1224-3"><a href="thursday-october-27-2022.html#cb1224-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb1224-4"><a href="thursday-october-27-2022.html#cb1224-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Kdata =</span> iso <span class="sc">*</span> <span class="fu">sum</span>(<span class="fu">intensity</span>(T.ppp)),</span>
<span id="cb1224-5"><a href="thursday-october-27-2022.html#cb1224-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">Kpois =</span> theo <span class="sc">*</span> <span class="fu">sum</span>(<span class="fu">intensity</span>(T.ppp)))</span>
<span id="cb1224-6"><a href="thursday-october-27-2022.html#cb1224-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1224-7"><a href="thursday-october-27-2022.html#cb1224-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> K.df, </span>
<span id="cb1224-8"><a href="thursday-october-27-2022.html#cb1224-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> Kdata)) <span class="sc">+</span></span>
<span id="cb1224-9"><a href="thursday-october-27-2022.html#cb1224-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb1224-10"><a href="thursday-october-27-2022.html#cb1224-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">y =</span> Kpois), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb1224-11"><a href="thursday-october-27-2022.html#cb1224-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">60</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb1224-12"><a href="thursday-october-27-2022.html#cb1224-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">129</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb1224-13"><a href="thursday-october-27-2022.html#cb1224-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">115</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb1224-14"><a href="thursday-october-27-2022.html#cb1224-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r), Expected number of additional tornadoes</span><span class="sc">\n</span><span class="st"> within a distance r of any tornado&quot;</span>) <span class="sc">+</span></span>
<span id="cb1224-15"><a href="thursday-october-27-2022.html#cb1224-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-547-1.png" width="672" /></p>
<p>Consider the lag distance of 60 km along the horizontal axis. If you draw a vertical line at that distance it intersects the black curve at a height of about 129. This value indicates that at a distance of 60 km from a random tornado report about 129 other tornado reports are in the vicinity (on average).</p>
<p>Imagine placing a disc with radius 60 km centered on each event and then averaging the number of events under the disc over all events.</p>
<p>The red line is the theoretical curve under the assumption that the tornado reports are CSR across the state. If this is the case then you would expect to see about 115 tornadoes within a distance 60 km from any tornado (on average). Since there are MORE tornadoes than expected within a given 60 km radius you conclude that there is evidence for clustering (at this spatial scale).</p>
<p>The black line lies above the red line across distances from 0 to greater than 100 km.</p>
<p>How do you interpret the results of applying the nearest neighbor function to these data? Here you create a data frame from the output of the <code>Gest()</code> function and remove distances exceeding 8 km.</p>
<div class="sourceCode" id="cb1225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1225-1"><a href="thursday-october-27-2022.html#cb1225-1" aria-hidden="true" tabindex="-1"></a>G.df <span class="ot">&lt;-</span> T.ppp <span class="sc">|&gt;</span></span>
<span id="cb1225-2"><a href="thursday-october-27-2022.html#cb1225-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Gest</span>(<span class="at">correction =</span> <span class="st">&quot;km&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb1225-3"><a href="thursday-october-27-2022.html#cb1225-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb1225-4"><a href="thursday-october-27-2022.html#cb1225-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(r <span class="sc">&lt;</span> <span class="dv">8</span>)</span>
<span id="cb1225-5"><a href="thursday-october-27-2022.html#cb1225-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1225-6"><a href="thursday-october-27-2022.html#cb1225-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> G.df, </span>
<span id="cb1225-7"><a href="thursday-october-27-2022.html#cb1225-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> km)) <span class="sc">+</span></span>
<span id="cb1225-8"><a href="thursday-october-27-2022.html#cb1225-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb1225-9"><a href="thursday-october-27-2022.html#cb1225-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb1225-10"><a href="thursday-october-27-2022.html#cb1225-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> .<span class="dv">4</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb1225-11"><a href="thursday-october-27-2022.html#cb1225-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">c</span>(<span class="fl">3.2</span>, <span class="dv">4</span>), <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb1225-12"><a href="thursday-october-27-2022.html#cb1225-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;G(r): Cumulative % of tornadoes</span><span class="sc">\n</span><span class="st"> within a distance r of another tornado&quot;</span>) <span class="sc">+</span></span>
<span id="cb1225-13"><a href="thursday-october-27-2022.html#cb1225-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-548-1.png" width="672" /></p>
<p>The interpretation is that 40% (<span class="math inline">\(G\)</span> = .4) of all tornado reports have another report within a distance of about 3.2 km on average. If the reports where homogeneous Poisson (CSR) then the distance would be 4 km. We conclude they are more clustered.</p>
<p>Note: With a data set containing many events the difference between the raw and border-corrected estimates of the distance functions is typically small.</p>
</div>
<div id="determining-the-statistical-significance-of-event-clustering" class="section level2 unnumbered hasAnchor">
<h2>Determining the statistical significance of event clustering<a href="thursday-october-27-2022.html#determining-the-statistical-significance-of-event-clustering" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The plots show a separation between the black solid line and the red line, but is this separation large relative to sampling variation? Is the above difference between the empirical and theoretical distance functions (e.g., <span class="math inline">\(G\)</span>) large enough to conclude there is significant clustering?</p>
<p>There are two ways to approach statistical inference. 1) Compare the function computed with the observed data against the function computed data generated under the null hypothesis and ask: does the function fall outside the envelope of functions from the null cases? 2) Get estimates of uncertainty on the function and ask: does the uncertainty interval contain the null case?</p>
<p>With the first approach you take a <code>ppp</code> object and then compute the function of interest (e.g., Ripley’s K) for a specified number of samples under the null hypothesis of a homogeneous Poisson process.</p>
<p>To make things run faster you consider a subset of all the tornadoes (those that have an EF rating of 2 or higher). You create a new <code>ppp</code> object that contains only tornadoes rated at least EF2. Since the marks is a factor vector you can’t use <code>&gt;=</code>.</p>
<div class="sourceCode" id="cb1226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1226-1"><a href="thursday-october-27-2022.html#cb1226-1" aria-hidden="true" tabindex="-1"></a>ST.ppp <span class="ot">&lt;-</span> <span class="fu">unmark</span>(T.ppp[T.ppp<span class="sc">$</span>marks <span class="sc">==</span> <span class="dv">2</span> <span class="sc">|</span> </span>
<span id="cb1226-2"><a href="thursday-october-27-2022.html#cb1226-2" aria-hidden="true" tabindex="-1"></a>                       T.ppp<span class="sc">$</span>marks <span class="sc">==</span> <span class="dv">3</span> <span class="sc">|</span> </span>
<span id="cb1226-3"><a href="thursday-october-27-2022.html#cb1226-3" aria-hidden="true" tabindex="-1"></a>                       T.ppp<span class="sc">$</span>marks <span class="sc">==</span> <span class="dv">4</span> <span class="sc">|</span></span>
<span id="cb1226-4"><a href="thursday-october-27-2022.html#cb1226-4" aria-hidden="true" tabindex="-1"></a>                       T.ppp<span class="sc">$</span>marks <span class="sc">==</span> <span class="dv">5</span>])</span>
<span id="cb1226-5"><a href="thursday-october-27-2022.html#cb1226-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ST.ppp)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-549-1.png" width="672" /></p>
<p>The <code>envelope()</code> method from the {spatstat} package is used on this new <code>ST.ppp</code> object. You specify the function with the <code>fun = Kest</code> argument and the number of samples with the <code>nsim =</code> argument. You then convert the output to a data frame. It takes a few seconds to complete the computation of <span class="math inline">\(K\)</span> for all 99 samples.</p>
<div class="sourceCode" id="cb1227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1227-1"><a href="thursday-october-27-2022.html#cb1227-1" aria-hidden="true" tabindex="-1"></a>Kenv.df <span class="ot">&lt;-</span> <span class="fu">envelope</span>(ST.ppp, </span>
<span id="cb1227-2"><a href="thursday-october-27-2022.html#cb1227-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">fun =</span> Kest, </span>
<span id="cb1227-3"><a href="thursday-october-27-2022.html#cb1227-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">nsim =</span> <span class="dv">99</span>) <span class="sc">|&gt;</span></span>
<span id="cb1227-4"><a href="thursday-october-27-2022.html#cb1227-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>## Generating 99 simulations of CSR  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
## 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,  99.
## 
## Done.</code></pre>
<div class="sourceCode" id="cb1229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1229-1"><a href="thursday-october-27-2022.html#cb1229-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Kenv.df)</span></code></pre></div>
<pre><code>##           r      obs       theo lo       hi
## 1 0.0000000  0.00000 0.00000000  0  0.00000
## 2 0.1677738 13.10164 0.08842974  0 11.40878
## 3 0.3355477 13.10164 0.35371897  0 11.40878
## 4 0.5033215 13.10164 0.79586769  0 12.54270
## 5 0.6710954 13.10164 1.41487589  0 13.54574
## 6 0.8388692 13.10164 2.21074358  0 24.29327</code></pre>
<p>The resulting data frame contains estimates of Ripley’s <span class="math inline">\(K\)</span> as a function of lag distance (<code>r</code>) (column labeled <code>obs</code>). It also has the estimates of <span class="math inline">\(K\)</span> under the null hypothesis of CSR (<code>theo</code>) and the lowest (<code>lo</code>) and highest (<code>hi</code>) values of <span class="math inline">\(K\)</span> across the 99 samples.</p>
<p>You plot this information using the <code>geom_ribbon()</code> layer to include a gray ribbon around the model of CSR.</p>
<div class="sourceCode" id="cb1231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1231-1"><a href="thursday-october-27-2022.html#cb1231-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Kenv.df, </span>
<span id="cb1231-2"><a href="thursday-october-27-2022.html#cb1231-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> obs <span class="sc">*</span> <span class="fu">intensity</span>(ST.ppp))) <span class="sc">+</span></span>
<span id="cb1231-3"><a href="thursday-october-27-2022.html#cb1231-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">ymin =</span> lo <span class="sc">*</span> <span class="fu">intensity</span>(ST.ppp), </span>
<span id="cb1231-4"><a href="thursday-october-27-2022.html#cb1231-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">ymax =</span> hi <span class="sc">*</span> <span class="fu">intensity</span>(ST.ppp)), <span class="at">fill =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb1231-5"><a href="thursday-october-27-2022.html#cb1231-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb1231-6"><a href="thursday-october-27-2022.html#cb1231-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo <span class="sc">*</span> <span class="fu">intensity</span>(ST.ppp)), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb1231-7"><a href="thursday-october-27-2022.html#cb1231-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb1231-8"><a href="thursday-october-27-2022.html#cb1231-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-551-1.png" width="672" /></p>
<p>The <span class="math inline">\(K\)</span> function computed on the data is the black line and the <span class="math inline">\(K\)</span> function under CSR is the red line. The uncertainty ribbon (gray band) connects the point-wise minimum and maximum values of <span class="math inline">\(K\)</span> computed from the 99 generated point pattern samples.</p>
<p>Since the black line lies outside the gray band you can confidently conclude that the tornado reports are <em>more</em> clustered than one would expect by chance.</p>
<p>If the specific intention is to test a null hypothesis of CSR, then a single statistic indicating the departure of <span class="math inline">\(K\)</span> computed on the observations from the theoretical <span class="math inline">\(K\)</span> is appropriate.</p>
<p>One such statistic is the maximum absolute deviation (MAD) and is implemented with the <code>mad.test()</code> function from the {spatstat} package. The function performs a hypothesis test for goodness-of-fit of the observations to the theoretical model. The larger the value of the statistic, the less likely it is that the data are CSR.</p>
<div class="sourceCode" id="cb1232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1232-1"><a href="thursday-october-27-2022.html#cb1232-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mad.test</span>(ST.ppp, </span>
<span id="cb1232-2"><a href="thursday-october-27-2022.html#cb1232-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">fun =</span> Kest, </span>
<span id="cb1232-3"><a href="thursday-october-27-2022.html#cb1232-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">nsim =</span> <span class="dv">99</span>)</span></code></pre></div>
<pre><code>## Generating 99 simulations of CSR  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
## 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,  99.
## 
## Done.</code></pre>
<pre><code>## 
##  Maximum absolute deviation test of CSR
##  Monte Carlo test based on 99 simulations
##  Summary function: K(r)
##  Reference function: theoretical
##  Alternative: two.sided
##  Interval of distance values: [0, 85.9002061907829] km
##  Test statistic: Maximum absolute deviation
##  Deviation = observed minus theoretical
## 
## data:  ST.ppp
## mad = 7297.2, rank = 1, p-value = 0.01</code></pre>
<p>The maximum absolute deviation is 7297 which is very large so the <span class="math inline">\(p\)</span>-value is small and you reject the null hypothesis of CSR for these data. This is consistent with the graph. Note: Since there are 99 simulations the lowest <span class="math inline">\(p\)</span>-value is .01.</p>
<p>Another test statistic is related to the sum of the squared deviations between the estimated and theoretical functions. It is implemented with the <code>dclf.test()</code> function.</p>
<div class="sourceCode" id="cb1235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1235-1"><a href="thursday-october-27-2022.html#cb1235-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dclf.test</span>(ST.ppp, </span>
<span id="cb1235-2"><a href="thursday-october-27-2022.html#cb1235-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">fun =</span> Kest, </span>
<span id="cb1235-3"><a href="thursday-october-27-2022.html#cb1235-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">nsim =</span> <span class="dv">99</span>)</span></code></pre></div>
<pre><code>## Generating 99 simulations of CSR  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
## 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,  99.
## 
## Done.</code></pre>
<pre><code>## 
##  Diggle-Cressie-Loosmore-Ford test of CSR
##  Monte Carlo test based on 99 simulations
##  Summary function: K(r)
##  Reference function: theoretical
##  Alternative: two.sided
##  Interval of distance values: [0, 85.9002061907829] km
##  Test statistic: Integral of squared absolute deviation
##  Deviation = observed minus theoretical
## 
## data:  ST.ppp
## u = 1548888704, rank = 1, p-value = 0.01</code></pre>
<p>Again the <span class="math inline">\(p\)</span>-value on the test statistic against the two-sided alternative is less than .01.</p>
<p>Compare these test results on tornado report clustering with test results on pine sapling clustering in the <code>swedishpines</code> data set.</p>
<div class="sourceCode" id="cb1238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1238-1"><a href="thursday-october-27-2022.html#cb1238-1" aria-hidden="true" tabindex="-1"></a>SP <span class="ot">&lt;-</span> swedishpines</span>
<span id="cb1238-2"><a href="thursday-october-27-2022.html#cb1238-2" aria-hidden="true" tabindex="-1"></a>Kenv.df <span class="ot">&lt;-</span> <span class="fu">envelope</span>(SP, </span>
<span id="cb1238-3"><a href="thursday-october-27-2022.html#cb1238-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">fun =</span> Kest, </span>
<span id="cb1238-4"><a href="thursday-october-27-2022.html#cb1238-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">nsim =</span> <span class="dv">99</span>) <span class="sc">|&gt;</span></span>
<span id="cb1238-5"><a href="thursday-october-27-2022.html#cb1238-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>## Generating 99 simulations of CSR  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
## 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,  99.
## 
## Done.</code></pre>
<div class="sourceCode" id="cb1240"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1240-1"><a href="thursday-october-27-2022.html#cb1240-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Kenv.df, </span>
<span id="cb1240-2"><a href="thursday-october-27-2022.html#cb1240-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r <span class="sc">*</span> .<span class="dv">1</span>, <span class="at">y =</span> obs <span class="sc">*</span> <span class="fu">intensity</span>(SP))) <span class="sc">+</span></span>
<span id="cb1240-3"><a href="thursday-october-27-2022.html#cb1240-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lo <span class="sc">*</span> <span class="fu">intensity</span>(SP),</span>
<span id="cb1240-4"><a href="thursday-october-27-2022.html#cb1240-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ymax =</span> hi <span class="sc">*</span> <span class="fu">intensity</span>(SP)), </span>
<span id="cb1240-5"><a href="thursday-october-27-2022.html#cb1240-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb1240-6"><a href="thursday-october-27-2022.html#cb1240-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo <span class="sc">*</span> <span class="fu">intensity</span>(SP)), </span>
<span id="cb1240-7"><a href="thursday-october-27-2022.html#cb1240-7" aria-hidden="true" tabindex="-1"></a>                          <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb1240-8"><a href="thursday-october-27-2022.html#cb1240-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (m)&quot;</span>) <span class="sc">+</span> </span>
<span id="cb1240-9"><a href="thursday-october-27-2022.html#cb1240-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;K(r), Expected number of additional saplings</span><span class="sc">\n</span><span class="st"> within a distance r of a sapling&quot;</span>) <span class="sc">+</span></span>
<span id="cb1240-10"><a href="thursday-october-27-2022.html#cb1240-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-554-1.png" width="672" /></p>
<p>At short distances (closer than about 1 m) the black line is below the red line and outside the gray ribbon which you interpret to mean that there are fewer pine saplings near other pine saplings than would be expected by chance at this scale. This ‘regularity’ might be the result of competition among the saplings.</p>
<p>At larger distances the black line is close to the red line and inside the gray ribbon which you interpret to mean that, at this larger spatial scale, the distribution of pine saplings is indistinguishable from CSR.</p>
<p>Based on the fact that much of the black line is within the gray envelope you might anticipate that a formal test against the null hypothesis of CSR will likely fail to reject.</p>
<div class="sourceCode" id="cb1241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1241-1"><a href="thursday-october-27-2022.html#cb1241-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mad.test</span>(SP, </span>
<span id="cb1241-2"><a href="thursday-october-27-2022.html#cb1241-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">fun =</span> Kest, </span>
<span id="cb1241-3"><a href="thursday-october-27-2022.html#cb1241-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">nsim =</span> <span class="dv">99</span>)</span></code></pre></div>
<pre><code>## Generating 99 simulations of CSR  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
## 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,  99.
## 
## Done.</code></pre>
<pre><code>## 
##  Maximum absolute deviation test of CSR
##  Monte Carlo test based on 99 simulations
##  Summary function: K(r)
##  Reference function: theoretical
##  Alternative: two.sided
##  Interval of distance values: [0, 24] units (one unit = 0.1 metres)
##  Test statistic: Maximum absolute deviation
##  Deviation = observed minus theoretical
## 
## data:  SP
## mad = 150.69, rank = 25, p-value = 0.25</code></pre>
<div class="sourceCode" id="cb1244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1244-1"><a href="thursday-october-27-2022.html#cb1244-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dclf.test</span>(SP, </span>
<span id="cb1244-2"><a href="thursday-october-27-2022.html#cb1244-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">fun =</span> Kest, </span>
<span id="cb1244-3"><a href="thursday-october-27-2022.html#cb1244-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">nsim =</span> <span class="dv">99</span>)</span></code></pre></div>
<pre><code>## Generating 99 simulations of CSR  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
## 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,  99.
## 
## Done.</code></pre>
<pre><code>## 
##  Diggle-Cressie-Loosmore-Ford test of CSR
##  Monte Carlo test based on 99 simulations
##  Summary function: K(r)
##  Reference function: theoretical
##  Alternative: two.sided
##  Interval of distance values: [0, 24] units (one unit = 0.1 metres)
##  Test statistic: Integral of squared absolute deviation
##  Deviation = observed minus theoretical
## 
## data:  SP
## u = 106917, rank = 17, p-value = 0.17</code></pre>
<p>Both return a <span class="math inline">\(p\)</span>-value that is greater than .15 so you fail to reject the null hypothesis of CSR.</p>
<p>In the second approach to inference the procedure of re-sampling is used. Note the distinction: Re-sampling refers to generating samples from the data while sampling, as above, refers to generating samples from some theoretical model.</p>
<p>The bootstrap procedure is a re-sampling strategy whereby new samples are generated from the data by randomly choosing events within the domain. An event that is chosen for the ‘bootstrap’ sample gets the chance to be chosen again (called ‘with replacement’). The number of events in each bootstrap sample must equal the number of events in the data.</p>
<p>Consider 15 numbers from 1 to 15. Then pick randomly from that set of numbers with replacement until the sample size is 15 to create a bootstrap sample.</p>
<div class="sourceCode" id="cb1247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1247-1"><a href="thursday-october-27-2022.html#cb1247-1" aria-hidden="true" tabindex="-1"></a>( x <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">15</span> )</span></code></pre></div>
<pre><code>##  [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15</code></pre>
<div class="sourceCode" id="cb1249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1249-1"><a href="thursday-october-27-2022.html#cb1249-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(x, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##  [1]  7  3  4 11  1 10  9  8  3 11  5 11 12 10 15</code></pre>
<p>Some numbers get picked more than once and some do not get picked at all.</p>
<p>The average of the original 15 <code>x</code> values is 8 but the average over the set of numbers in the bootstrap sample will not necessarily be 8. However, the distribution of the averages over many bootstrap samples will be centered close to this average.</p>
<div class="sourceCode" id="cb1251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1251-1"><a href="thursday-october-27-2022.html#cb1251-1" aria-hidden="true" tabindex="-1"></a>mx <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb1251-2"><a href="thursday-october-27-2022.html#cb1251-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">99</span>){</span>
<span id="cb1251-3"><a href="thursday-october-27-2022.html#cb1251-3" aria-hidden="true" tabindex="-1"></a>  mx[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">sample</span>(x, <span class="at">replace =</span> <span class="cn">TRUE</span>))</span>
<span id="cb1251-4"><a href="thursday-october-27-2022.html#cb1251-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1251-5"><a href="thursday-october-27-2022.html#cb1251-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1251-6"><a href="thursday-october-27-2022.html#cb1251-6" aria-hidden="true" tabindex="-1"></a>mx.df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(mx)</span>
<span id="cb1251-7"><a href="thursday-october-27-2022.html#cb1251-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> mx.df,</span>
<span id="cb1251-8"><a href="thursday-october-27-2022.html#cb1251-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">mapping =</span> <span class="fu">aes</span>(mx)) <span class="sc">+</span></span>
<span id="cb1251-9"><a href="thursday-october-27-2022.html#cb1251-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb1251-10"><a href="thursday-october-27-2022.html#cb1251-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(x),</span>
<span id="cb1251-11"><a href="thursday-october-27-2022.html#cb1251-11" aria-hidden="true" tabindex="-1"></a>               <span class="at">color =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-557-1.png" width="672" /></p>
<p>The important thing is that the bootstrap distribution provides an estimate of the uncertainty on the computed mean through the range of possible average values.</p>
<p>In this way, the <code>lohboot()</code> function estimates the uncertainty on the computed spatial statistic using a bootstrap procedure. It works by computing a local version of the function (e.g., <code>localK()</code>) on the set of re-sampled events.</p>
<div class="sourceCode" id="cb1252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1252-1"><a href="thursday-october-27-2022.html#cb1252-1" aria-hidden="true" tabindex="-1"></a>Kboot.df <span class="ot">&lt;-</span> ST.ppp <span class="sc">|&gt;</span></span>
<span id="cb1252-2"><a href="thursday-october-27-2022.html#cb1252-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lohboot</span>(<span class="at">fun =</span> Kest) <span class="sc">|&gt;</span></span>
<span id="cb1252-3"><a href="thursday-october-27-2022.html#cb1252-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>## 1, 2, 3, 4.6.8.10.12.14.16.18.20.22.24.26.28.30.32.34.36.38.40
## .42.44.46.48.50.52.54.56.58.60.62.64.66.68.70.72.74.76.78.80
## .82.84.86.88.90.92.94.96.98.100.102.104.106.108.110.112.114.116.118.120
## .122.124.126.128.130.132.134.136.138.140.142.144.146.148.150.152.154.156.158.160
## .162.164.166.168.170.172.174.176.178.180. 182.</code></pre>
<div class="sourceCode" id="cb1254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1254-1"><a href="thursday-october-27-2022.html#cb1254-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Kboot.df, </span>
<span id="cb1254-2"><a href="thursday-october-27-2022.html#cb1254-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> iso <span class="sc">*</span> <span class="fu">intensity</span>(ST.ppp))) <span class="sc">+</span></span>
<span id="cb1254-3"><a href="thursday-october-27-2022.html#cb1254-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lo <span class="sc">*</span> <span class="fu">intensity</span>(ST.ppp), </span>
<span id="cb1254-4"><a href="thursday-october-27-2022.html#cb1254-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ymax =</span> hi <span class="sc">*</span> <span class="fu">intensity</span>(ST.ppp)), <span class="at">fill =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb1254-5"><a href="thursday-october-27-2022.html#cb1254-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb1254-6"><a href="thursday-october-27-2022.html#cb1254-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo <span class="sc">*</span> <span class="fu">intensity</span>(ST.ppp)), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb1254-7"><a href="thursday-october-27-2022.html#cb1254-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb1254-8"><a href="thursday-october-27-2022.html#cb1254-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-558-1.png" width="672" /></p>
<p>Now the uncertainty band is plotted about the black line (<span class="math inline">\(K\)</span> function computed on the observations) rather than about the null model (red line). The 95% uncertainty band does to include the CSR model so you confidently conclude that the tornadoes in Kansas are more clustered than chance.</p>
<p>Repeating for the Swedish pine saplings.</p>
<div class="sourceCode" id="cb1255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1255-1"><a href="thursday-october-27-2022.html#cb1255-1" aria-hidden="true" tabindex="-1"></a>Kboot.df <span class="ot">&lt;-</span> SP <span class="sc">|&gt;</span></span>
<span id="cb1255-2"><a href="thursday-october-27-2022.html#cb1255-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lohboot</span>(<span class="at">fun =</span> Kest) <span class="sc">|&gt;</span></span>
<span id="cb1255-3"><a href="thursday-october-27-2022.html#cb1255-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,  71.</code></pre>
<div class="sourceCode" id="cb1257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1257-1"><a href="thursday-october-27-2022.html#cb1257-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Kboot.df, <span class="fu">aes</span>(<span class="at">x =</span> r <span class="sc">*</span> .<span class="dv">1</span>, <span class="at">y =</span> iso <span class="sc">*</span> <span class="fu">intensity</span>(SP))) <span class="sc">+</span></span>
<span id="cb1257-2"><a href="thursday-october-27-2022.html#cb1257-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lo <span class="sc">*</span> <span class="fu">intensity</span>(SP), </span>
<span id="cb1257-3"><a href="thursday-october-27-2022.html#cb1257-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ymax =</span> hi <span class="sc">*</span> <span class="fu">intensity</span>(SP)), <span class="at">fill =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb1257-4"><a href="thursday-october-27-2022.html#cb1257-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb1257-5"><a href="thursday-october-27-2022.html#cb1257-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo <span class="sc">*</span> <span class="fu">intensity</span>(SP)), <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb1257-6"><a href="thursday-october-27-2022.html#cb1257-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (m)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb1257-7"><a href="thursday-october-27-2022.html#cb1257-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-559-1.png" width="672" /></p>
<p>At short distances (closer than about 1.5 m) the gray ribbon is below the blue line which you interpret to mean that there are fewer pine saplings near other pine saplings than would be expected by chance at this scale indicating regularity.</p>
</div>
<div id="estimating-event-clustering-in-multi-type-event-locations" class="section level2 unnumbered hasAnchor">
<h2>Estimating event clustering in multi-type event locations<a href="thursday-october-27-2022.html#estimating-event-clustering-in-multi-type-event-locations" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Often the interest focuses on whether the occurrence of one event type influences (or is influenced by) another event type. For example, does the occurrence of one species of tree influence the occurrence of another species?</p>
<p>Analogues to the <span class="math inline">\(G\)</span> and <span class="math inline">\(K\)</span> functions are available for ‘multi-type’ point patterns where the marks are factors.</p>
<p>A common statistic for examining ‘cross correlation’ of event type occurrences is the cross <span class="math inline">\(K\)</span> function <span class="math inline">\(K_{ij}(r)\)</span>, which estimates the expected number of events of type <span class="math inline">\(j\)</span> within a distance <span class="math inline">\(r\)</span> of type <span class="math inline">\(i\)</span>.</p>
<p>Consider the data called <code>lansing</code> from the {spatstat} package that contains the locations of 2,251 trees of various species in a wooded lot in Lansing, MI as a <code>ppp</code> object.</p>
<div class="sourceCode" id="cb1258"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1258-1"><a href="thursday-october-27-2022.html#cb1258-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(lansing)</span>
<span id="cb1258-2"><a href="thursday-october-27-2022.html#cb1258-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lansing)</span></code></pre></div>
<pre><code>## Marked planar point pattern:  2251 points
## Average intensity 2251 points per square unit (one unit = 924 feet)
## 
## *Pattern contains duplicated points*
## 
## Coordinates are given to 3 decimal places
## i.e. rounded to the nearest multiple of 0.001 units (one unit = 924 feet)
## 
## Multitype:
##          frequency proportion intensity
## blackoak       135 0.05997335       135
## hickory        703 0.31230560       703
## maple          514 0.22834300       514
## misc           105 0.04664594       105
## redoak         346 0.15370950       346
## whiteoak       448 0.19902270       448
## 
## Window: rectangle = [0, 1] x [0, 1] units
## Window area = 1 square unit
## Unit of length: 924 feet</code></pre>
<p>The data are a multi-type planar point pattern with the marks indicating tree species. There are 135 black oaks, 703 hickories, etc. The spatial unit is 924 feet.</p>
<p>Compute and plot the cross <span class="math inline">\(K\)</span> function for Maple and Hickory trees.</p>
<div class="sourceCode" id="cb1260"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1260-1"><a href="thursday-october-27-2022.html#cb1260-1" aria-hidden="true" tabindex="-1"></a>Kc.df <span class="ot">&lt;-</span> lansing <span class="sc">|&gt;</span></span>
<span id="cb1260-2"><a href="thursday-october-27-2022.html#cb1260-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Kcross</span>(<span class="at">i =</span> <span class="st">&quot;maple&quot;</span>,</span>
<span id="cb1260-3"><a href="thursday-october-27-2022.html#cb1260-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">j =</span> <span class="st">&quot;hickory&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb1260-4"><a href="thursday-october-27-2022.html#cb1260-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span>
<span id="cb1260-5"><a href="thursday-october-27-2022.html#cb1260-5" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb1260-6"><a href="thursday-october-27-2022.html#cb1260-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Kc.df, </span>
<span id="cb1260-7"><a href="thursday-october-27-2022.html#cb1260-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> iso)) <span class="sc">+</span></span>
<span id="cb1260-8"><a href="thursday-october-27-2022.html#cb1260-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb1260-9"><a href="thursday-october-27-2022.html#cb1260-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb1260-10"><a href="thursday-october-27-2022.html#cb1260-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> .<span class="dv">2</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb1260-11"><a href="thursday-october-27-2022.html#cb1260-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> .<span class="dv">093</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb1260-12"><a href="thursday-october-27-2022.html#cb1260-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> .<span class="dv">125</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb1260-13"><a href="thursday-october-27-2022.html#cb1260-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Distance&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Kc(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb1260-14"><a href="thursday-october-27-2022.html#cb1260-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-561-1.png" width="672" /></p>
<p>The vertical axis is the number of hickory trees within a radius r of a maple tree divided by the average intensity of the hickories. So at a distance of .2 (.2 x 924 ft = 180 ft) from a random maple there is an average of roughly 65 hickories (.093 x 703 hickories). If hickory and maple trees are CSR you would expect about 88 maples (.125 * 703) within that distance.</p>
<p>The presence of a hickory tree reduces the likelihood that a maple tree will be nearby.</p>
<p>Do the same for the EF1 and EF3 tornadoes in Kansas.</p>
<div class="sourceCode" id="cb1261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1261-1"><a href="thursday-october-27-2022.html#cb1261-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">Kcross</span>(T.ppp, </span>
<span id="cb1261-2"><a href="thursday-october-27-2022.html#cb1261-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">i =</span> <span class="st">&quot;1&quot;</span>, </span>
<span id="cb1261-3"><a href="thursday-october-27-2022.html#cb1261-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">j =</span> <span class="st">&quot;3&quot;</span>))</span>
<span id="cb1261-4"><a href="thursday-october-27-2022.html#cb1261-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">70</span>)</span>
<span id="cb1261-5"><a href="thursday-october-27-2022.html#cb1261-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">18700</span>)</span>
<span id="cb1261-6"><a href="thursday-october-27-2022.html#cb1261-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">15500</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-562-1.png" width="672" /></p>
<div class="sourceCode" id="cb1262"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1262-1"><a href="thursday-october-27-2022.html#cb1262-1" aria-hidden="true" tabindex="-1"></a>Kc.df <span class="ot">&lt;-</span> T.ppp <span class="sc">|&gt;</span></span>
<span id="cb1262-2"><a href="thursday-october-27-2022.html#cb1262-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Kcross</span>(<span class="at">i =</span> <span class="st">&quot;1&quot;</span>, </span>
<span id="cb1262-3"><a href="thursday-october-27-2022.html#cb1262-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">j =</span> <span class="st">&quot;3&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb1262-4"><a href="thursday-october-27-2022.html#cb1262-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span>
<span id="cb1262-5"><a href="thursday-october-27-2022.html#cb1262-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Kc.df, </span>
<span id="cb1262-6"><a href="thursday-october-27-2022.html#cb1262-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> iso)) <span class="sc">+</span></span>
<span id="cb1262-7"><a href="thursday-october-27-2022.html#cb1262-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb1262-8"><a href="thursday-october-27-2022.html#cb1262-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb1262-9"><a href="thursday-october-27-2022.html#cb1262-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">70</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb1262-10"><a href="thursday-october-27-2022.html#cb1262-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">18700</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb1262-11"><a href="thursday-october-27-2022.html#cb1262-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">15500</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb1262-12"><a href="thursday-october-27-2022.html#cb1262-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Distance&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Kc(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb1262-13"><a href="thursday-october-27-2022.html#cb1262-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-562-2.png" width="672" /></p>
<p>The vertical axis is the number of EF3 tornadoes within a radius r of an EF1 tornado divided by the average intensity of the EF3 tornadoes. At a distance of 70 km from a random EF1 tornado there are on average 18500 x .000296 = 5.5 EF3 tornadoes. If EF1 and EF3 tornadoes are CSR then you would expect, on average, somewhat fewer EF3 tornadoes in the vicinity of EF1 tornadoes (15500 x .000296 = 4.6).</p>
<p>You can see this more clearly by using the <code>envelope()</code> function with the <code>fun = Kross</code>. You first use the <code>subset()</code> method with <code>drop = TRUE</code> to make a new <code>ppp</code> object with only those two groups.</p>
<div class="sourceCode" id="cb1263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1263-1"><a href="thursday-october-27-2022.html#cb1263-1" aria-hidden="true" tabindex="-1"></a>T.ppp13 <span class="ot">&lt;-</span> <span class="fu">subset</span>(T.ppp,</span>
<span id="cb1263-2"><a href="thursday-october-27-2022.html#cb1263-2" aria-hidden="true" tabindex="-1"></a>                  marks <span class="sc">==</span> <span class="st">&quot;1&quot;</span> <span class="sc">|</span></span>
<span id="cb1263-3"><a href="thursday-october-27-2022.html#cb1263-3" aria-hidden="true" tabindex="-1"></a>                  marks <span class="sc">==</span> <span class="st">&quot;3&quot;</span>,</span>
<span id="cb1263-4"><a href="thursday-october-27-2022.html#cb1263-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">drop =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1263-5"><a href="thursday-october-27-2022.html#cb1263-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1263-6"><a href="thursday-october-27-2022.html#cb1263-6" aria-hidden="true" tabindex="-1"></a>Kcenv.df <span class="ot">&lt;-</span> T.ppp13 <span class="sc">|&gt;</span></span>
<span id="cb1263-7"><a href="thursday-october-27-2022.html#cb1263-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">envelope</span>(<span class="at">fun =</span> Kcross,</span>
<span id="cb1263-8"><a href="thursday-october-27-2022.html#cb1263-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">nsim =</span> <span class="dv">99</span>) <span class="sc">|&gt;</span></span>
<span id="cb1263-9"><a href="thursday-october-27-2022.html#cb1263-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>## Generating 99 simulations of CSR  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
## 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,  99.
## 
## Done.</code></pre>
<div class="sourceCode" id="cb1265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1265-1"><a href="thursday-october-27-2022.html#cb1265-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Kcenv.df, </span>
<span id="cb1265-2"><a href="thursday-october-27-2022.html#cb1265-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> obs)) <span class="sc">+</span></span>
<span id="cb1265-3"><a href="thursday-october-27-2022.html#cb1265-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lo, <span class="at">ymax =</span> hi), <span class="at">fill =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb1265-4"><a href="thursday-october-27-2022.html#cb1265-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb1265-5"><a href="thursday-october-27-2022.html#cb1265-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb1265-6"><a href="thursday-october-27-2022.html#cb1265-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Kc(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb1265-7"><a href="thursday-october-27-2022.html#cb1265-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-563-1.png" width="672" /></p>
<p>And you can formally test as before using the <code>mad.test()</code> function.</p>
<div class="sourceCode" id="cb1266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1266-1"><a href="thursday-october-27-2022.html#cb1266-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mad.test</span>(T.ppp13, <span class="at">fun =</span> Kcross, <span class="at">nsim =</span> <span class="dv">99</span>)</span></code></pre></div>
<pre><code>## Generating 99 simulations of CSR  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
## 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,  99.
## 
## Done.</code></pre>
<pre><code>## 
##  Maximum absolute deviation test of CSR
##  Monte Carlo test based on 99 simulations
##  Summary function: &quot;K&quot;[&quot;1&quot;, &quot;3&quot;](r)
##  Reference function: theoretical
##  Alternative: two.sided
##  Interval of distance values: [0, 85.9002061907829] km
##  Test statistic: Maximum absolute deviation
##  Deviation = observed minus theoretical
## 
## data:  T.ppp13
## mad = 4234.6, rank = 1, p-value = 0.01</code></pre>
<div class="sourceCode" id="cb1269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1269-1"><a href="thursday-october-27-2022.html#cb1269-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dclf.test</span>(T.ppp13, <span class="at">fun =</span> Kcross, <span class="at">nsim =</span> <span class="dv">99</span>)</span></code></pre></div>
<pre><code>## Generating 99 simulations of CSR  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
## 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,  99.
## 
## Done.</code></pre>
<pre><code>## 
##  Diggle-Cressie-Loosmore-Ford test of CSR
##  Monte Carlo test based on 99 simulations
##  Summary function: &quot;K&quot;[&quot;1&quot;, &quot;3&quot;](r)
##  Reference function: theoretical
##  Alternative: two.sided
##  Interval of distance values: [0, 85.9002061907829] km
##  Test statistic: Integral of squared absolute deviation
##  Deviation = observed minus theoretical
## 
## data:  T.ppp13
## u = 402609991, rank = 1, p-value = 0.01</code></pre>
<p>Both tests lead you to conclude that EF3 tornadoes are more likely near EF1 tornadoes than would be expected if they were independently CSR.</p>
</div>
<div id="more-about-the-ripley-k-function" class="section level2 unnumbered hasAnchor">
<h2>More about the Ripley K function<a href="thursday-october-27-2022.html#more-about-the-ripley-k-function" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Compute Ripley <span class="math inline">\(K\)</span> and look at the classes of the resulting object.</p>
<div class="sourceCode" id="cb1272"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1272-1"><a href="thursday-october-27-2022.html#cb1272-1" aria-hidden="true" tabindex="-1"></a>K <span class="ot">&lt;-</span> <span class="fu">Kest</span>(T.ppp)</span>
<span id="cb1272-2"><a href="thursday-october-27-2022.html#cb1272-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(K)</span></code></pre></div>
<pre><code>## [1] &quot;fv&quot;         &quot;data.frame&quot;</code></pre>
<p>It has two classes <code>fv</code> and <code>data.frame</code>. It is a data frame but with additional attribute information. You focus on the data frame portion.</p>
<div class="sourceCode" id="cb1274"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1274-1"><a href="thursday-october-27-2022.html#cb1274-1" aria-hidden="true" tabindex="-1"></a>K.df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(K)</span>
<span id="cb1274-2"><a href="thursday-october-27-2022.html#cb1274-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(K.df)</span></code></pre></div>
<pre><code>##           r       theo   border    trans      iso
## 1 0.0000000 0.00000000 0.000000 0.000000 0.000000
## 2 0.1677738 0.08842974 5.586056 5.588550 5.588550
## 3 0.3355477 0.35371897 6.118072 6.104416 6.104416
## 4 0.5033215 0.79586769 6.745407 6.792237 6.792237
## 5 0.6710954 1.41487589 7.264284 7.308103 7.308103
## 6 0.8388692 2.21074358 7.963272 7.995925 7.995925</code></pre>
<p>In particular you want the values of <code>r</code> and <code>iso</code>. The value of <code>iso</code> times the average spatial intensity is the number of tornadoes within a distance <code>r</code>.</p>
<p>You add this information to the data frame.</p>
<div class="sourceCode" id="cb1276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1276-1"><a href="thursday-october-27-2022.html#cb1276-1" aria-hidden="true" tabindex="-1"></a>K.df <span class="ot">&lt;-</span> K.df <span class="sc">|&gt;</span></span>
<span id="cb1276-2"><a href="thursday-october-27-2022.html#cb1276-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">nT =</span> <span class="fu">summary</span>(T.ppp)<span class="sc">$</span>intensity <span class="sc">*</span> iso)</span></code></pre></div>
<p>Suppose you are interested in the average number of tornadoes at a distance of exactly 50 km. Use the <code>approx()</code> function to interpolate the value of <code>nT</code> at a distance of 50 km.</p>
<div class="sourceCode" id="cb1277"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1277-1"><a href="thursday-october-27-2022.html#cb1277-1" aria-hidden="true" tabindex="-1"></a><span class="fu">approx</span>(<span class="at">x =</span> K.df<span class="sc">$</span>r, </span>
<span id="cb1277-2"><a href="thursday-october-27-2022.html#cb1277-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> K.df<span class="sc">$</span>nT,</span>
<span id="cb1277-3"><a href="thursday-october-27-2022.html#cb1277-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">xout =</span> <span class="dv">50</span>)<span class="sc">$</span>y</span></code></pre></div>
<pre><code>## [1] 92.39087</code></pre>
<p>Finally, the variance stabilized Ripley <span class="math inline">\(K\)</span> function called the <span class="math inline">\(L\)</span> function is often used instead of <span class="math inline">\(K\)</span>. The sample version of the <span class="math inline">\(L\)</span> function is defined as
<span class="math display">\[
\hat{L}(r) = \Big( \hat{K}(r)/\pi\Big)^{1/2}.
\]</span></p>
<p>For data that is CSR, the <span class="math inline">\(L\)</span> function has expected value <span class="math inline">\(r\)</span> and its variance is approximately constant in <span class="math inline">\(r\)</span>. A common plot is a graph of <span class="math inline">\(r - \hat{L}(r)\)</span> against <span class="math inline">\(r\)</span>, which approximately follows the horizontal zero-axis with constant dispersion if the data follow a homogeneous Poisson process.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tuesday-october-25-2022.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="tuesday-november-1-2022.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
