---
title: "Assignment 2"
author: "Your Name"
date: January 22, 2021
output: 
  html_document:
    keep_md: true
editor_options: 
  chunk_output_type: console
---

Due: January 22, 2021, 3pm

Total Points: 35

Make sure you have the {tidyverse}, {sf}, and {spData} packages available by running the code chunk below.

```{r}
library(tidyverse)
if(!require(sf)) install.packages(pkgs = "sf", repos = "http://cran.us.r-project.org")
library(sf)
if(!require(spData)) install.packages(pkgs = "spData", repos = "http://cran.us.r-project.org")
library(spData)
```

The object `us_states` from the {spData} package is a data frame (simple feature data frame) from the U.S. Census Bureau. The variables include the state `GEOID` and `NAME`, the `REGION` (`South`, `West`, etc), `AREA` (in square km), and total population in 2010 (`total_pop_10`) and in 2015 (`total_pop_15`). Answer the five questions below using the appropriate functions `select()`, `filter()`, `summarize()`, and `group_by()`.

a.  Create a new data frame containing only the population columns. (5)
b.  Create a new data frame containing only states from the South region. (5)
c.  Create a new data frame containing only states from the West region with a 2015 population of more than 6 million people. (5)
d.  What was the total population of the Midwest region in 2010 and 2015? (10)
e.  How many states are in each region and what is the *average* statewide 2015 population in each region? (10) Hint: Use the `group_by()` function.
