---
title: "Assignment 11"
author: "Your Name"
date: April 9, 2021
output: 
  html_document:
    keep_md: true
editor_options: 
  chunk_output_type: console
---

Due: April 16, 2021, 3pm

Total Points: 40

Consider the geodata object `parana` from the {geoR} package containing rainfall values from the state of Paran\`a. The data are average rainfall (mm) during May and June.

(a) First plot the observed values using the `plot()` method. Then plot the residuals after a 2nd-order trend is removed from the observed values. (5)
(b) Compute and plot an empirical variogram on the residuals after removing the 2nd-order trend. Hint: Use the `variog()` function. (5)
(c) Fit a variogram model using the exponential function to the empirical variogram. Assume isotropy. Set the initial nugget to 500, the partial sill to 300 and the range to 100. Hint: Use the `likfit()` function. (5)
(d) Plot the empirical variogram and add the variogram model curve on the same graph. Hint: To add the variogram model curve use the `lines.variomodel()` function with parameters from the model. (10)
(e) Create a kriged surface by interpolating the rainfall values to locations on a regular grid. Use the `pred_grid(parana$borders, by = 2)` function to generate the grid. (10)
(f) Plot the interpolated surface using the `image()` function with the argument `col = rev(terrain.colors(21))`. (5)