<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Thurday September 22, 2022 | GIS5122: Applied Spatial Statistics</title>
  <meta name="description" content="Thurday September 22, 2022 | GIS5122: Applied Spatial Statistics" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Thurday September 22, 2022 | GIS5122: Applied Spatial Statistics" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="jelsner/ASS-2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Thurday September 22, 2022 | GIS5122: Applied Spatial Statistics" />
  
  
  

<meta name="author" content="James B. Elsner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tuesday-september-20-2022.html"/>

<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied Spatial Statistics</a></li>

<li class="divider"></li>
<li><a href="index.html#section"></a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i>Syllabus</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#gis5122-applied-spatial-statistics"><i class="fa fa-check"></i>GIS5122: Applied Spatial Statistics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#contact-information"><i class="fa fa-check"></i>Contact information</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#course-description"><i class="fa fa-check"></i>Course description</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#expected-learning-outcomes"><i class="fa fa-check"></i>Expected learning outcomes</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#materials"><i class="fa fa-check"></i>Materials</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#class-meetings"><i class="fa fa-check"></i>Class meetings</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#grades"><i class="fa fa-check"></i>Grades</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#ethics"><i class="fa fa-check"></i>Ethics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#outline-of-topics"><i class="fa fa-check"></i>Outline of topics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#schedule-subject-to-change-with-notice"><i class="fa fa-check"></i>Schedule (subject to change with notice)</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#reference-materials"><i class="fa fa-check"></i>Reference materials</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#reproducible-research"><i class="fa fa-check"></i>Reproducible research</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html"><i class="fa fa-check"></i>Tuesday, August 23, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#install-r-and-rstudio-on-your-computer"><i class="fa fa-check"></i>Install R and RStudio on your computer</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#download-course-materials"><i class="fa fa-check"></i>Download course materials</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#read-the-syllabus"><i class="fa fa-check"></i>Read the syllabus</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#about-rstudio"><i class="fa fa-check"></i>About RStudio</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#lab-assignments"><i class="fa fa-check"></i>Lab assignments</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#getting-started-with-r"><i class="fa fa-check"></i>Getting started with R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#are-you-completely-new-to-r"><i class="fa fa-check"></i>Are you completely new to R?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html"><i class="fa fa-check"></i>Thursday, August 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#expectations"><i class="fa fa-check"></i>Expectations</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-science-workflow-with-r-markdown"><i class="fa fa-check"></i>Data science workflow with R markdown</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#an-introduction-to-using-r"><i class="fa fa-check"></i>An introduction to using R</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-frames"><i class="fa fa-check"></i>Data frames</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html"><i class="fa fa-check"></i>Tuesday August 30, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#working-with-data-frames"><i class="fa fa-check"></i>Working with data frames</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html"><i class="fa fa-check"></i>Thursday September 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#making-graphs"><i class="fa fa-check"></i>Making graphs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html"><i class="fa fa-check"></i>Tuesday September 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#working-with-spatial-data"><i class="fa fa-check"></i>Working with spatial data</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#geo-computation-on-simple-features"><i class="fa fa-check"></i>Geo-computation on simple features</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html"><i class="fa fa-check"></i>Thursday September 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#spatial-data-subsets-and-joins"><i class="fa fa-check"></i>Spatial data subsets and joins</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#interpolation-using-areal-weights"><i class="fa fa-check"></i>Interpolation using areal weights</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html"><i class="fa fa-check"></i>Tuesday September 13, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#s4-spatial-data-objects"><i class="fa fa-check"></i>S4 spatial data objects</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#working-with-raster-data"><i class="fa fa-check"></i>Working with raster data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html"><i class="fa fa-check"></i>Thursday September 15, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#working-with-space-time-data"><i class="fa fa-check"></i>Working with space-time data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#mapping-using-functions-from-the-ggplot2-package"><i class="fa fa-check"></i>Mapping using functions from the {ggplot2} package</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#mapping-using-functions-from-the-tmap-package"><i class="fa fa-check"></i>Mapping using functions from the {tmap} package</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#creating-an-interactive-map"><i class="fa fa-check"></i>Creating an interactive map</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#adding-an-inset-map"><i class="fa fa-check"></i>Adding an inset map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html"><i class="fa fa-check"></i>Tuesday September 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#defining-spatial-neighborhoods-and-spatial-weights"><i class="fa fa-check"></i>Defining spatial neighborhoods and spatial weights</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#computing-autocorrelation"><i class="fa fa-check"></i>Computing autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#spatial-lag-and-its-relation-to-autocorrelation"><i class="fa fa-check"></i>Spatial lag and its relation to autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thurday-september-22-2022.html"><a href="thurday-september-22-2022.html"><i class="fa fa-check"></i>Thurday September 22, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thurday-september-22-2022.html"><a href="thurday-september-22-2022.html#defining-neighborhoods-differently"><i class="fa fa-check"></i>Defining neighborhoods differently</a></li>
<li class="chapter" data-level="" data-path="thurday-september-22-2022.html"><a href="thurday-september-22-2022.html#assessing-the-statistical-significance-of-autocorrelation"><i class="fa fa-check"></i>Assessing the statistical significance of autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thurday-september-22-2022.html"><a href="thurday-september-22-2022.html#bivariate-spatial-autocorrelation"><i class="fa fa-check"></i>Bivariate spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thurday-september-22-2022.html"><a href="thurday-september-22-2022.html#local-indicators-of-spatial-autocorrelation"><i class="fa fa-check"></i>Local indicators of spatial autocorrelation</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GIS5122: Applied Spatial Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="thurday-september-22-2022" class="section level1 unnumbered">
<h1>Thurday September 22, 2022</h1>
<p><strong>“Be curious. Read widely. Try new things. I think a lot of what people call intelligence boils down to curiosity.”</strong> - Aaron Swartz</p>
<p>Today</p>
<ul>
<li>Defining neighborhoods differently</li>
<li>Assessing the statistical significance of autocorrelation</li>
<li>Bivariate spatial autocorrelation</li>
<li>Local indicators of spatial autocorrelation</li>
</ul>
<div id="defining-neighborhoods-differently" class="section level2 unnumbered">
<h2>Defining neighborhoods differently</h2>
<p>Last time you saw how to compute autocorrelation using areal aggregated data. The procedure involves a weights matrix, which you created using the default neighborhood definition and the weighting scheme with functions from the {spdep} package.</p>
<p>It was noted that the magnitude of autocorrelation depends on the weighting scheme used. Other neighborhood definitions are possible and they will also influence the magnitude of the autocorrelation.</p>
<p>Let’s consider the historical demographic data in Mississippi counties. Import the data as a simple feature data frame and assign the geometry a geographic CRS.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="thurday-september-22-2022.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="st">&quot;police&quot;</span> <span class="sc">%in%</span> <span class="fu">list.files</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>))) {</span>
<span id="cb1-2"><a href="thurday-september-22-2022.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(<span class="at">url =</span> <span class="st">&quot;http://myweb.fsu.edu/jelsner/temp/data/police.zip&quot;</span>,</span>
<span id="cb1-3"><a href="thurday-september-22-2022.html#cb1-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">destfile =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;police.zip&quot;</span>))</span>
<span id="cb1-4"><a href="thurday-september-22-2022.html#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">unzip</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;police.zip&quot;</span>),</span>
<span id="cb1-5"><a href="thurday-september-22-2022.html#cb1-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">exdir =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>))</span>
<span id="cb1-6"><a href="thurday-september-22-2022.html#cb1-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-7"><a href="thurday-september-22-2022.html#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="thurday-september-22-2022.html#cb1-8" aria-hidden="true" tabindex="-1"></a>( PE.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="at">dsn =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;police&quot;</span>), </span>
<span id="cb1-9"><a href="thurday-september-22-2022.html#cb1-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">layer =</span> <span class="st">&quot;police&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-10"><a href="thurday-september-22-2022.html#cb1-10" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_set_crs</span>(<span class="dv">4326</span>) )</span></code></pre></div>
<pre><code>## Reading layer `police&#39; from data source 
##   `/Users/jameselsner/Desktop/ClassNotes/ASS-2022/data/police&#39; 
##   using driver `ESRI Shapefile&#39;
## Simple feature collection with 82 features and 21 fields
## Geometry type: POLYGON
## Dimension:     XY
## Bounding box:  xmin: -91.64356 ymin: 30.19474 xmax: -88.09043 ymax: 35.00496
## CRS:           NA</code></pre>
<pre><code>## Simple feature collection with 82 features and 21 fields
## Geometry type: POLYGON
## Dimension:     XY
## Bounding box:  xmin: -91.64356 ymin: 30.19474 xmax: -88.09043 ymax: 35.00496
## Geodetic CRS:  WGS 84
## First 10 features:
##     AREA PERIMETER CNTY_ CNTY_ID       NAME  STATE_NAME STATE_FIPS CNTY_FIPS
## 1  0.105     1.401  2129    2129     Alcorn Mississippi         28       003
## 2  0.111     1.485  2130    2130 Tishomingo Mississippi         28       141
## 3  0.116     1.519  2131    2131     Tippah Mississippi         28       139
## 4  0.105     1.478  2132    2132     Benton Mississippi         28       009
## 5  0.127     1.774  2133    2133    De Soto Mississippi         28       033
## 6  0.181     1.911  2134    2134   Marshall Mississippi         28       093
## 7  0.119     2.146  2155    2155     Tunica Mississippi         28       143
## 8  0.103     1.571  2171    2171       Tate Mississippi         28       137
## 9  0.106     1.394  2176    2176   Prentiss Mississippi         28       117
## 10 0.109     1.493  2199    2199      Union Mississippi         28       145
##     FIPS FIPSNO POLICE   POP TAX TRANSFER  INC CRIME UNEMP OWN COLLEGE WHITE
## 1  28003  28003    706 32500 122    12428 8206    43     7  70      23    89
## 2  28141  28141    247 19100 112     7278 6666   316     8  73      18    96
## 3  28139  28139    296 18800  93     8606 6865     5     7  71      18    84
## 4  28009  28009    116  8400 100     3494 6083    24    12  75      16    62
## 5  28033  28033   1063 56400 116    18555 8731    36     6  77      26    82
## 6  28093  28093    549 30900  87    10370 5825   316    11  71      22    47
## 7  28143  28143    291  9500 153     5354 6019    42    15  43      18    27
## 8  28137  28137    444 20500 137    13783 7837    20     8  67      29    61
## 9  28117  28117    455 24400 118    14650 6361    41     6  74      20    89
## 10 28145  28145    364 21400 117     8207 7530    46     5  73      22    86
##    COMMUTE                       geometry
## 1        8 POLYGON ((-88.35416 34.7626...
## 2        8 POLYGON ((-88.32171 34.4693...
## 3       15 POLYGON ((-88.72614 34.6048...
## 4       41 POLYGON ((-89.23874 34.5935...
## 5        2 POLYGON ((-90.20186 34.7297...
## 6       12 POLYGON ((-89.66407 34.5659...
## 7        3 POLYGON ((-90.19978 34.5617...
## 8       11 POLYGON ((-89.71541 34.5659...
## 9       23 POLYGON ((-88.32171 34.4693...
## 10      20 POLYGON ((-89.24072 34.5017...</code></pre>
<p>Variables in the simple feature data frame include police expenditures (<code>POLICE</code>), crime (<code>CRIME</code>), income (<code>INC</code>), unemployment (<code>UNEMP</code>) and other socio-economic characteristics across Mississippi at the county level. Police expenditures are per person 1982 (dollars per person). Personal income is per person in 1982 (dollars per person). Crime is the number of serious crimes per 100,000 person in 1981. Unemployment is percent of people looking for work in 1980.</p>
<p>The geometries are polygons that define the county borders.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="thurday-september-22-2022.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb4-2"><a href="thurday-september-22-2022.html#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="thurday-september-22-2022.html#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> PE.sf) <span class="sc">+</span></span>
<span id="cb4-4"><a href="thurday-september-22-2022.html#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>To estimate autocorrelation for any variable in the data frame, you need to first assign the neighbors and weights for each region.</p>
<p>The default options in the <code>spdep::poly2nb()</code> and <code>spdep::nb2listw()</code> result in neighbors defined by ‘queen’ contiguity (polygon intersections can include a single point) and weights defined by row standardization (the sum of the weights equals the number of regions).</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="thurday-september-22-2022.html#cb5-1" aria-hidden="true" tabindex="-1"></a>nbs <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">poly2nb</span>(PE.sf)</span>
<span id="cb5-2"><a href="thurday-september-22-2022.html#cb5-2" aria-hidden="true" tabindex="-1"></a>wts <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">nb2listw</span>(nbs)</span></code></pre></div>
<p>Alternatively you can specify the number of neighbors and then assign neighbors based on proximity (closeness). Here you first extract the coordinates of the polygon centroids as a matrix.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="thurday-september-22-2022.html#cb6-1" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> PE.sf <span class="sc">|&gt;</span></span>
<span id="cb6-2"><a href="thurday-september-22-2022.html#cb6-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_centroid</span>() <span class="sc">|&gt;</span></span>
<span id="cb6-3"><a href="thurday-september-22-2022.html#cb6-3" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_coordinates</span>()</span></code></pre></div>
<pre><code>## Warning in st_centroid.sf(PE.sf): st_centroid assumes attributes are constant
## over geometries of x</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="thurday-september-22-2022.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(coords)</span></code></pre></div>
<pre><code>##           X        Y
## 1 -88.56938 34.88746
## 2 -88.23073 34.74665
## 3 -88.89928 34.77600
## 4 -89.17942 34.82323
## 5 -89.98973 34.88099
## 6 -89.49699 34.76984</code></pre>
<p>Then use the <code>spdep::knearneigh()</code> function on the coordinate matrix and specify the number of neighbors with the <code>k =</code> argument. Here you set it to six. That is, allow each county to have 6 closest neighbors.</p>
<p>Since the CRS is geographic you need to include the <code>longlat = TRUE</code> argument so distances are calculated using great circles.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="thurday-september-22-2022.html#cb10-1" aria-hidden="true" tabindex="-1"></a>knn <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">knearneigh</span>(coords, </span>
<span id="cb10-2"><a href="thurday-september-22-2022.html#cb10-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">k =</span> <span class="dv">6</span>, </span>
<span id="cb10-3"><a href="thurday-september-22-2022.html#cb10-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">longlat =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-4"><a href="thurday-september-22-2022.html#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(knn)</span></code></pre></div>
<pre><code>## [1] &quot;nn&quot;        &quot;np&quot;        &quot;k&quot;         &quot;dimension&quot; &quot;x&quot;</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="thurday-september-22-2022.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(knn<span class="sc">$</span>nn)</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4] [,5] [,6]
## [1,]    9    3    2    4   10   14
## [2,]    9    1   16    3   14   10
## [3,]    4   10    1    9    6   14
## [4,]    3    6   10    1   11    9
## [5,]    8    7    6   12   11    4
## [6,]    4    8   11    5    3   10</code></pre>
<p>The output is a list of five elements with the first element a matrix with the row dimension the number of counties and the column dimension the number of neighbors.</p>
<p>Note that by using distance to define neighbors the matrix is not symmetric. For example, county 3 is a neighbor of county 2, but county 2 is not a neighbor of county 3.</p>
<p>Certain spatial models require the neighbor matrix to be symmetric. That is if region X is a neighbor of region Y then region Y must be a neighbor of region X.</p>
<p>You turn this matrix into a neighbor object (class <code>nb</code>) with the <code>spdep::knn2nb()</code> function.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="thurday-september-22-2022.html#cb14-1" aria-hidden="true" tabindex="-1"></a>nbs2 <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">knn2nb</span>(knn)</span>
<span id="cb14-2"><a href="thurday-september-22-2022.html#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nbs2)</span></code></pre></div>
<pre><code>## Neighbour list object:
## Number of regions: 82 
## Number of nonzero links: 492 
## Percentage nonzero weights: 7.317073 
## Average number of links: 6 
## Non-symmetric neighbours list
## Link number distribution:
## 
##  6 
## 82 
## 82 least connected regions:
## 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 with 6 links
## 82 most connected regions:
## 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 with 6 links</code></pre>
<p>If you include the argument <code>sym = TRUE</code> in the <code>knn2nb()</code> function then it forces the neighbor matrix to be symmetric.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="thurday-september-22-2022.html#cb16-1" aria-hidden="true" tabindex="-1"></a>nbs3 <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">knn2nb</span>(knn,</span>
<span id="cb16-2"><a href="thurday-september-22-2022.html#cb16-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">sym =</span> <span class="cn">TRUE</span>)</span>
<span id="cb16-3"><a href="thurday-september-22-2022.html#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nbs3)</span></code></pre></div>
<pre><code>## Neighbour list object:
## Number of regions: 82 
## Number of nonzero links: 568 
## Percentage nonzero weights: 8.447353 
## Average number of links: 6.926829 
## Link number distribution:
## 
##  6  7  8  9 10 
## 37 25 13  3  4 
## 37 least connected regions:
## 1 2 5 6 7 8 13 16 18 21 22 28 31 33 34 40 42 44 45 46 48 49 50 54 57 59 62 63 65 73 74 76 77 78 80 81 82 with 6 links
## 4 most connected regions:
## 10 19 66 70 with 10 links</code></pre>
<p>The result shows that six is now the minimum number of nearest neighbors with some counties having has many as 10 neighbors to guarantee symmetry.</p>
<p>Compare the default adjacency neighborhoods with the nearest-neighbor neighborhoods.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="thurday-september-22-2022.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sf<span class="sc">::</span><span class="fu">st_geometry</span>(PE.sf), <span class="at">border =</span> <span class="st">&quot;grey&quot;</span>)</span>
<span id="cb18-2"><a href="thurday-september-22-2022.html#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(nbs, coords, <span class="at">add =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="thurday-september-22-2022.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sf<span class="sc">::</span><span class="fu">st_geometry</span>(PE.sf), <span class="at">border =</span> <span class="st">&quot;grey&quot;</span>)</span>
<span id="cb19-2"><a href="thurday-september-22-2022.html#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(nbs2, coords, <span class="at">add =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-8-2.png" width="672" /></p>
<p>Toggle between the plots.</p>
<p>A difference between the two neighborhoods is the number of links on counties along the borders. The nearest-neighbor defined neighborhoods have more links. Note: when neighbors are defined by proximity counties can share a border but they still may not be neighbors.</p>
<p>Your choice of neighbors is based on domain specific knowledge. If the process you are interested in can be described by a dispersal mechanism then proximity definition might be the right choice for defining neighbors. If the process can be described by a border diffusion mechanism then contiguity might be the right choice.</p>
<p>Create weight matrices for these alternative neighborhoods using the same <code>spdep::nb2listw()</code> function.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="thurday-september-22-2022.html#cb20-1" aria-hidden="true" tabindex="-1"></a>wts2 <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">nb2listw</span>(nbs2)</span>
<span id="cb20-2"><a href="thurday-september-22-2022.html#cb20-2" aria-hidden="true" tabindex="-1"></a>wts3 <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">nb2listw</span>(nbs3)</span></code></pre></div>
<p>You compute Moran’s I for the percentage of white people variable (<code>WHITE</code>) with the <code>moran()</code> function separately for the three different weight matrices.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="thurday-september-22-2022.html#cb21-1" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">moran</span>(PE.sf<span class="sc">$</span>WHITE,</span>
<span id="cb21-2"><a href="thurday-september-22-2022.html#cb21-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">listw =</span> wts,</span>
<span id="cb21-3"><a href="thurday-september-22-2022.html#cb21-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">n =</span> <span class="fu">length</span>(nbs),</span>
<span id="cb21-4"><a href="thurday-september-22-2022.html#cb21-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">S0 =</span> spdep<span class="sc">::</span><span class="fu">Szero</span>(wts))</span></code></pre></div>
<pre><code>## $I
## [1] 0.5634778
## 
## $K
## [1] 2.300738</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="thurday-september-22-2022.html#cb23-1" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">moran</span>(PE.sf<span class="sc">$</span>WHITE,</span>
<span id="cb23-2"><a href="thurday-september-22-2022.html#cb23-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">listw =</span> wts2,</span>
<span id="cb23-3"><a href="thurday-september-22-2022.html#cb23-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">n =</span> <span class="fu">length</span>(nbs2),</span>
<span id="cb23-4"><a href="thurday-september-22-2022.html#cb23-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">S0 =</span> spdep<span class="sc">::</span><span class="fu">Szero</span>(wts2))</span></code></pre></div>
<pre><code>## $I
## [1] 0.5506132
## 
## $K
## [1] 2.300738</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="thurday-september-22-2022.html#cb25-1" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">moran</span>(PE.sf<span class="sc">$</span>WHITE,</span>
<span id="cb25-2"><a href="thurday-september-22-2022.html#cb25-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">listw =</span> wts3,</span>
<span id="cb25-3"><a href="thurday-september-22-2022.html#cb25-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">n =</span> <span class="fu">length</span>(nbs3),</span>
<span id="cb25-4"><a href="thurday-september-22-2022.html#cb25-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">S0 =</span> spdep<span class="sc">::</span><span class="fu">Szero</span>(wts3))</span></code></pre></div>
<pre><code>## $I
## [1] 0.5592557
## 
## $K
## [1] 2.300738</code></pre>
<p>Values of Moran’s I are constrained between -1 and +1. In this case the neighborhood definition has little or no impact on inferences made about spatial autocorrelation. The kurtosis is between 2 and 4 consistent with a set of values from a normal distribution.</p>
<p>In a similar way you compute the Geary’s C statistic.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="thurday-september-22-2022.html#cb27-1" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">geary</span>(PE.sf<span class="sc">$</span>WHITE, </span>
<span id="cb27-2"><a href="thurday-september-22-2022.html#cb27-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">listw =</span> wts,</span>
<span id="cb27-3"><a href="thurday-september-22-2022.html#cb27-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">n =</span> <span class="fu">length</span>(nbs), </span>
<span id="cb27-4"><a href="thurday-september-22-2022.html#cb27-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">S0 =</span> spdep<span class="sc">::</span><span class="fu">Szero</span>(wts), </span>
<span id="cb27-5"><a href="thurday-september-22-2022.html#cb27-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">n1 =</span> <span class="fu">length</span>(nbs) <span class="sc">-</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## $C
## [1] 0.4123818
## 
## $K
## [1] 2.300738</code></pre>
<p>Values of Geary’s C range between 0 and 2 with values less than one indicating positive autocorrelation.</p>
<p>If the values of Moran’s I and Geary’s C result in different interpretations about the amount of clustering then it is a good idea to examine <em>local</em> variations in autocorrelation.</p>
</div>
<div id="assessing-the-statistical-significance-of-autocorrelation" class="section level2 unnumbered">
<h2>Assessing the statistical significance of autocorrelation</h2>
<p>Attribute values randomly placed across a spatial domain will result in some autocorrelation. Statistical tests provide a way to guard against being fooled by this randomness. For example, claiming a ‘hot spot’ when none exists. In statistical parlance, is the value of Moran’s I significant with respect to the null hypothesis of no autocorrelation?</p>
<p>One way to answer this question is to draw an uncertainty band on the regression line in a Moran scatter plot. If a horizontal line can be placed entirely within the band then the slope (Moran’s I) is not significant against the null hypothesis of no autocorrelation.</p>
<p>More formally the question is answered by comparing the standard deviate (<span class="math inline">\(z\)</span> value) of the I statistic to the appropriate value from a standard normal distribution. This is done using the <code>spdep::moran.test()</code> function, where the <span class="math inline">\(z\)</span> value is the difference between I and the expected value of I divided by the square root of the variance of I.</p>
<p>The function takes a variable name or numeric vector and a spatial weights list object in that order. The argument <code>randomisation = FALSE</code> means the variance of I is computed under the assumption of normally distributed unemployment (<code>UNEMP</code>) rates.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="thurday-september-22-2022.html#cb29-1" aria-hidden="true" tabindex="-1"></a>( mt <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">moran.test</span>(PE.sf<span class="sc">$</span>UNEMP, </span>
<span id="cb29-2"><a href="thurday-september-22-2022.html#cb29-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">listw =</span> wts,</span>
<span id="cb29-3"><a href="thurday-september-22-2022.html#cb29-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">randomisation =</span> <span class="cn">FALSE</span>) )</span></code></pre></div>
<pre><code>## 
##  Moran I test under normality
## 
## data:  PE.sf$UNEMP  
## weights: wts    
## 
## Moran I statistic standard deviate = 3.4102, p-value = 0.0003246
## alternative hypothesis: greater
## sample estimates:
## Moran I statistic       Expectation          Variance 
##       0.217503452      -0.012345679       0.004542775</code></pre>
<p>Moran’s I is .218 with a variance of .0045. The <span class="math inline">\(z\)</span> value for I is 3.41 giving a <span class="math inline">\(p\)</span>-value of .0003 under the null hypothesis of no autocorrelation. Thus you reject the null hypothesis and conclude there is weak but significant autocorrelation in unemployment rates across Mississippi at the county level.</p>
<p>Outputs from the <code>spdep::moran.test()</code> function are in the form of a list.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="thurday-september-22-2022.html#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mt)</span></code></pre></div>
<pre><code>## List of 6
##  $ statistic  : Named num 3.41
##   ..- attr(*, &quot;names&quot;)= chr &quot;Moran I statistic standard deviate&quot;
##  $ p.value    : num 0.000325
##  $ estimate   : Named num [1:3] 0.2175 -0.01235 0.00454
##   ..- attr(*, &quot;names&quot;)= chr [1:3] &quot;Moran I statistic&quot; &quot;Expectation&quot; &quot;Variance&quot;
##  $ alternative: chr &quot;greater&quot;
##  $ method     : chr &quot;Moran I test under normality&quot;
##  $ data.name  : chr &quot;PE.sf$UNEMP  \nweights: wts    \n&quot;
##  - attr(*, &quot;class&quot;)= chr &quot;htest&quot;</code></pre>
<p>The list element called <code>estimate</code> is a vector of length three containing Moran’s I, the expected value of Moran’s I under the assumption of no autocorrelation, and the variance of Moran’s I.</p>
<p>The <span class="math inline">\(z\)</span> value is the difference between I and it’s expected value divided by the square root of the variance.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="thurday-september-22-2022.html#cb33-1" aria-hidden="true" tabindex="-1"></a>( mt<span class="sc">$</span>estimate[<span class="dv">1</span>] <span class="sc">-</span> mt<span class="sc">$</span>estimate[<span class="dv">2</span>] ) <span class="sc">/</span> <span class="fu">sqrt</span>(mt<span class="sc">$</span>estimate[<span class="dv">3</span>])</span></code></pre></div>
<pre><code>## Moran I statistic 
##          3.410219</code></pre>
<p>The <span class="math inline">\(p\)</span>-value is the area under a standard normal distribution curve to the right (<code>lower.tail = FALSE</code>) of 3.4102 (<code>mt$statistic</code>).</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="thurday-september-22-2022.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(mt<span class="sc">$</span>statistic, </span>
<span id="cb35-2"><a href="thurday-september-22-2022.html#cb35-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Moran I statistic standard deviate 
##                        0.000324554</code></pre>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="thurday-september-22-2022.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x), <span class="at">from =</span> <span class="sc">-</span><span class="dv">4</span>, <span class="at">to =</span> <span class="dv">4</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb37-2"><a href="thurday-september-22-2022.html#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> mt<span class="sc">$</span>statistic, <span class="at">col =</span> <span class="st">&#39;red&#39;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>So about .03% of the area lies to the right of the red line.</p>
<p>Recall the <span class="math inline">\(p\)</span>-value summarizes the evidence in support of the null hypothesis. The smaller the <span class="math inline">\(p\)</span>-value, the less evidence there is in support of the null hypothesis.</p>
<p>In this case it is the probability that the county unemployment rates could have been arranged at random across the state if the null hypothesis is true. The small <span class="math inline">\(p\)</span>-value tells you that the spatial arrangement of the data is unusual with respect to the null hypothesis.</p>
<p>The interpretation of the <span class="math inline">\(p\)</span>-value is stated as evidence AGAINST the null hypothesis. This is because interest lies in the null hypothesis being untenable. A <span class="math inline">\(p\)</span>-value less than .01 is said to provide convincing evidence against the null, a <span class="math inline">\(p\)</span>-value between .01 and .05 is said to provide moderate evidence against the null, and a <span class="math inline">\(p\)</span>-value between .05 and .15 is said to be suggestive, but inconclusive in providing evidence against the null. A <span class="math inline">\(p\)</span>-value greater than .15 is said to provide no evidence against the null.</p>
<p>Note you do not interpret “no evidence” as “no effect (no autocorrelation)”.</p>
<p>Under the assumption of normal distributed and uncorrelated data, the expected value for Moran’s I is -1/(n-1) where n is the number of regions.</p>
<p>A check on the distribution of unemployment rates indicates that normality is somewhat suspect. A good way to check the normality assumption is to use the <code>sm.density()</code> function from the {sm} package.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="thurday-september-22-2022.html#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(sm)) <span class="fu">install.packages</span>(<span class="st">&quot;sm&quot;</span>, <span class="at">repos =</span> <span class="st">&quot;http://cran.us.r-project.org&quot;</span>)</span></code></pre></div>
<pre><code>## Loading required package: sm</code></pre>
<pre><code>## Package &#39;sm&#39;, version 2.2-5.7: type help(sm) for summary information</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="thurday-september-22-2022.html#cb41-1" aria-hidden="true" tabindex="-1"></a>sm<span class="sc">::</span><span class="fu">sm.density</span>(PE.sf<span class="sc">$</span>UNEMP, </span>
<span id="cb41-2"><a href="thurday-september-22-2022.html#cb41-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">model =</span> <span class="st">&quot;Normal&quot;</span>,</span>
<span id="cb41-3"><a href="thurday-september-22-2022.html#cb41-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">xlab =</span> <span class="st">&quot;Unemployment Rates&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>The unemployment rates are less “peaked” (lower kurtosis) than a normal distribution. In this case it is better to use the default <code>randomisation = TRUE</code> argument.</p>
<p>Further, the assumptions underlying Moran’s test are sensitive to the form of the graph of neighbor relationships and other factors so results should be checked against a test that involves permutations.</p>
<p>A random sampling approach to inference is made with the <code>spdep::moran.mc()</code> function. MC stands for Monte Carlo which refers to the city of Monte Carlo in Monaco famous for its gambling casinos.</p>
<p>The name of the data vector and the weights list object (<code>listw</code>) are required as is the number of permutations (<code>nsim</code>). Each permutation is a random rearrangement of the unemployment rates across the counties. This removes the spatial autocorrelation but keeps the non-spatial distribution of the unemployment rates. The neighbor topology and weights remain the same.</p>
<p>For each permutation (random shuffle of the data values), I is computed and saved. The <span class="math inline">\(p\)</span>-value is obtained as the ratio of the number of permuted I values greater or exceeding the observed I over the number of permutation plus one. In the case where there are 5 permuted I values greater or equal to the observed value based on 99 simulations, the <span class="math inline">\(p\)</span>-value is 5/(99 + 1) = .05.</p>
<p>For example, if you want inference on I using 9999 permutations type</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="thurday-september-22-2022.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">40453</span>)</span>
<span id="cb42-2"><a href="thurday-september-22-2022.html#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="thurday-september-22-2022.html#cb42-3" aria-hidden="true" tabindex="-1"></a>( mP <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">moran.mc</span>(PE.sf<span class="sc">$</span>UNEMP, </span>
<span id="cb42-4"><a href="thurday-september-22-2022.html#cb42-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">listw =</span> wts,</span>
<span id="cb42-5"><a href="thurday-september-22-2022.html#cb42-5" aria-hidden="true" tabindex="-1"></a>                        <span class="at">nsim =</span> <span class="dv">9999</span>) )</span></code></pre></div>
<pre><code>## 
##  Monte-Carlo simulation of Moran I
## 
## data:  PE.sf$UNEMP 
## weights: wts  
## number of simulations + 1: 10000 
## 
## statistic = 0.2175, observed rank = 9991, p-value = 9e-04
## alternative hypothesis: greater</code></pre>
<p>Nine of the permutations yield a Moran’s I greater than .218, hence the <span class="math inline">\(p\)</span>-value as evidence in support of the null hypothesis (the true value for Moran’s I is zero) is .0009.</p>
<p>Note: you initiate the random number generator with a seed value (any will do) so that the set of random permutations of the values across the domain will be the same each time you run this code chunk. This is important for reproducibility. The default random number generator seed value is determined from the current time (internal clock) and so no random permutations will be identical. To control the seed use the <code>set.seed()</code> function.</p>
<p>The values of I computed for each permutation are saved in the vector <code>mP$res</code>.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="thurday-september-22-2022.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mP<span class="sc">$</span>res)</span></code></pre></div>
<pre><code>## [1] -0.03052409  0.05019765  0.01346706  0.03189984 -0.07625158 -0.07398726</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="thurday-september-22-2022.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(mP<span class="sc">$</span>res)</span></code></pre></div>
<pre><code>## [1]  0.01973190 -0.01000012 -0.04472215 -0.12488347 -0.01269481  0.21750345</code></pre>
<p>The last value in the vector is I computed using the data in the correct counties. The <span class="math inline">\(p\)</span>-value as evidence in support of the null hypothesis that I is zero is given as</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="thurday-september-22-2022.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(mP<span class="sc">$</span>res <span class="sc">&gt;</span> mP<span class="sc">$</span>res[<span class="dv">10000</span>])<span class="sc">/</span><span class="dv">9999</span></span></code></pre></div>
<pre><code>## [1] 0.00090009</code></pre>
<p>A density graph displays the distribution of permuted I’s.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="thurday-september-22-2022.html#cb50-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">mp =</span> mP<span class="sc">$</span>res[<span class="sc">-</span><span class="dv">10000</span>])</span>
<span id="cb50-2"><a href="thurday-september-22-2022.html#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> df,</span>
<span id="cb50-3"><a href="thurday-september-22-2022.html#cb50-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(mp)) <span class="sc">+</span> </span>
<span id="cb50-4"><a href="thurday-september-22-2022.html#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span> </span>
<span id="cb50-5"><a href="thurday-september-22-2022.html#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_rug</span>() <span class="sc">+</span> </span>
<span id="cb50-6"><a href="thurday-september-22-2022.html#cb50-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mP<span class="sc">$</span>res[<span class="dv">10000</span>], </span>
<span id="cb50-7"><a href="thurday-september-22-2022.html#cb50-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb50-8"><a href="thurday-september-22-2022.html#cb50-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>The density curve is centered just to the left of zero consistent with the theoretical expectation (mean).</p>
<p>What to do with the knowledge that the unemployment rates have significant autocorrelation? By itself, not much, but it can provide notice that something might be going on in certain regions (hot spot analysis).</p>
<p>The knowledge is useful after other factors are considered. In the language of statistics, knowledge of significant autocorrelation in the model residuals can help you build a better model.</p>
</div>
<div id="bivariate-spatial-autocorrelation" class="section level2 unnumbered">
<h2>Bivariate spatial autocorrelation</h2>
<p>The idea of spatial autocorrelation can be extended to two variables. It is motivated by the fact that aspatial bi-variate association measures, like Pearson’s correlation, do not recognize the spatial arrangement of the regions.</p>
<p>Consider the correlation between police expenditure (<code>POLICE</code>) and the amount of crime (<code>CRIME</code>) in the police expenditure data set.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="thurday-september-22-2022.html#cb51-1" aria-hidden="true" tabindex="-1"></a>police <span class="ot">&lt;-</span> PE.sf<span class="sc">$</span>POLICE</span>
<span id="cb51-2"><a href="thurday-september-22-2022.html#cb51-2" aria-hidden="true" tabindex="-1"></a>crime <span class="ot">&lt;-</span> PE.sf<span class="sc">$</span>CRIME</span>
<span id="cb51-3"><a href="thurday-september-22-2022.html#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="thurday-september-22-2022.html#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(police, crime, <span class="at">method =</span> <span class="st">&quot;pearson&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  police and crime
## t = 6.2916, df = 80, p-value = 1.569e-08
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.4094516 0.7043990
## sample estimates:
##       cor 
## 0.5753377</code></pre>
<p>You note a significant (direct) correlation (<span class="math inline">\(p\)</span>-value &lt; .01) exists between these two variables.</p>
<p>But you also note some significant spatial autocorrelation in each of the variables separately.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="thurday-september-22-2022.html#cb53-1" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">moran.test</span>(police, </span>
<span id="cb53-2"><a href="thurday-september-22-2022.html#cb53-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">listw =</span> wts)</span></code></pre></div>
<pre><code>## 
##  Moran I test under randomisation
## 
## data:  police  
## weights: wts    
## 
## Moran I statistic standard deviate = 1.7899, p-value = 0.03674
## alternative hypothesis: greater
## sample estimates:
## Moran I statistic       Expectation          Variance 
##       0.087185424      -0.012345679       0.003092257</code></pre>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="thurday-september-22-2022.html#cb55-1" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">moran.test</span>(crime, </span>
<span id="cb55-2"><a href="thurday-september-22-2022.html#cb55-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">listw =</span> wts)</span></code></pre></div>
<pre><code>## 
##  Moran I test under randomisation
## 
## data:  crime  
## weights: wts    
## 
## Moran I statistic standard deviate = 2.2072, p-value = 0.01365
## alternative hypothesis: greater
## sample estimates:
## Moran I statistic       Expectation          Variance 
##       0.103588680      -0.012345679       0.002758842</code></pre>
<p>The Lee statistic integrates the Pearson correlation as an aspatial bi-variate association metric with Moran’s I as a uni-variate spatial autocorrelation metric. The formula is
<span class="math display">\[
L(x,y) = \frac{n}{\sum_{i=1}^{n}(\sum_{j=1}^{n}w_{ij})^2}
\frac{\sum_{i=1}^{n}(\sum_{j=1}^{n}w_{ij}(x_i-\bar{x})) ((\sum_{j=1}^{n}w_{ij}(y_j-\bar{y}))}{\sqrt{\sum_{i=1}^{n}(x_i - \bar{x})^2} \sqrt{\sum_{i=1}^{n}(y_i - \bar{y})^2}}
\]</span></p>
<p>The formula is implemented in the <code>spdep::lee()</code> function where the first two arguments are the variables of interest and you need to include the weights matrix and the number of regions. The output from this function is a list of two with the first being the value of Lee’s statistic (<code>L</code>).</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="thurday-september-22-2022.html#cb57-1" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">lee</span>(crime, police, </span>
<span id="cb57-2"><a href="thurday-september-22-2022.html#cb57-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">listw =</span> wts, </span>
<span id="cb57-3"><a href="thurday-september-22-2022.html#cb57-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">n =</span> <span class="fu">length</span>(nbs))<span class="sc">$</span>L</span></code></pre></div>
<pre><code>## [1] 0.1306991</code></pre>
<p>Values of L range between -1 and +1 with the value here of .13 indicating relatively weak bi-variate spatial autocorrelation between crime and police expenditures. Statistically you infer that crime in a county has some influence on police expenditure in that county and in the neighboring counties, but not much.</p>
<p>The <code>crime</code> and <code>police</code> variables are not adequately described by a normal distribution.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="thurday-september-22-2022.html#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>))</span>
<span id="cb59-2"><a href="thurday-september-22-2022.html#cb59-2" aria-hidden="true" tabindex="-1"></a>sm<span class="sc">::</span><span class="fu">sm.density</span>(crime, <span class="at">model =</span> <span class="st">&quot;normal&quot;</span>)</span>
<span id="cb59-3"><a href="thurday-september-22-2022.html#cb59-3" aria-hidden="true" tabindex="-1"></a>sm<span class="sc">::</span><span class="fu">sm.density</span>(police, <span class="at">model =</span> <span class="st">&quot;normal&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>Thus you perform a non-parametric test on the bi-variate spatial autocorrelation with the <code>spdep::lee.mc()</code> function. The crime and police expenditure values are randomly permuted and values of <code>L</code> are computed for each permutation.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="thurday-september-22-2022.html#cb60-1" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">lee.mc</span>(crime, police, </span>
<span id="cb60-2"><a href="thurday-september-22-2022.html#cb60-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">listw =</span> wts, </span>
<span id="cb60-3"><a href="thurday-september-22-2022.html#cb60-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">nsim =</span> <span class="dv">999</span>)</span></code></pre></div>
<pre><code>## 
##  Monte-Carlo simulation of Lee&#39;s L
## 
## data:  crime ,  police 
## weights: wts  
## number of simulations + 1: 1000 
## 
## statistic = 0.1307, observed rank = 760, p-value = 0.24
## alternative hypothesis: greater</code></pre>
<p>Based on a <span class="math inline">\(p\)</span>-value that exceeds .05 you conclude that there is no significant bi-variate spatial autocorrelation between crime and police expenditure in these data.</p>
</div>
<div id="local-indicators-of-spatial-autocorrelation" class="section level2 unnumbered">
<h2>Local indicators of spatial autocorrelation</h2>
<p>The Moran’s I statistic was first used in the 1950s. Localization of the statistic was presented by Luc Anselin in 1995 (Anselin, L. 1995. Local indicators of spatial association, Geographical Analysis, 27, 93–115).</p>
<p>Earlier you saw the <code>raster::MoranLocal()</code> function from the {raster} package returns a raster of local Moran’s I values.</p>
<p>Local I is a deconstruction of global I where geographic proximity is used in two ways. (1) to define and weight neighbors and (2) to determine the spatial scale over which I is computed.</p>
<p>Using queen’s contiguity you determine the neighborhood topology and the weights for the police expenditure data from Mississippi. Here you print them in the full matrix form with the <code>spdep::list2mat()</code> function.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="thurday-september-22-2022.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(spdep<span class="sc">::</span><span class="fu">listw2mat</span>(wts)[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>], <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##   [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
## 1 0.00 0.33 0.33 0.00    0 0.00 0.00 0.00 0.33  0.00
## 2 0.33 0.00 0.00 0.00    0 0.00 0.00 0.00 0.33  0.00
## 3 0.25 0.00 0.00 0.25    0 0.00 0.00 0.00 0.25  0.25
## 4 0.00 0.00 0.33 0.00    0 0.33 0.00 0.00 0.00  0.33
## 5 0.00 0.00 0.00 0.00    0 0.33 0.33 0.33 0.00  0.00</code></pre>
<p>The matrix shows that the first county has three neighbors 2, 3, and 9 and each get a weight of 1/3. The third county has four neighbors 1, 4, 9 and 10 and each gets a weight of 1/4.</p>
<p>Compute local Moran’s I on the percentage of white people using the <code>spdep::localmoran()</code> function. Two arguments are needed (1) the attribute variable for which you want to compute local correlation and (2) the weights matrix as a list object.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="thurday-september-22-2022.html#cb64-1" aria-hidden="true" tabindex="-1"></a>Ii_stats <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">localmoran</span>(PE.sf<span class="sc">$</span>WHITE, </span>
<span id="cb64-2"><a href="thurday-september-22-2022.html#cb64-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">listw =</span> wts)</span>
<span id="cb64-3"><a href="thurday-september-22-2022.html#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(Ii_stats)</span></code></pre></div>
<pre><code>##  &#39;localmoran&#39; num [1:82, 1:5] 2.28138 2.97475 1.31244 0.00231 -1.03216 ...
##  - attr(*, &quot;dimnames&quot;)=List of 2
##   ..$ : chr [1:82] &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot; ...
##   ..$ : chr [1:5] &quot;Ii&quot; &quot;E.Ii&quot; &quot;Var.Ii&quot; &quot;Z.Ii&quot; ...
##  - attr(*, &quot;call&quot;)= language spdep::localmoran(x = PE.sf$WHITE, listw = wts)
##  - attr(*, &quot;quadr&quot;)=&#39;data.frame&#39;:    82 obs. of  3 variables:
##   ..$ mean  : Factor w/ 4 levels &quot;Low-Low&quot;,&quot;High-Low&quot;,..: 4 4 4 4 2 3 1 1 4 4 ...
##   ..$ median: Factor w/ 4 levels &quot;Low-Low&quot;,&quot;High-Low&quot;,..: 4 4 4 3 2 3 1 1 4 4 ...
##   ..$ pysal : Factor w/ 4 levels &quot;Low-Low&quot;,&quot;High-Low&quot;,..: 4 4 4 4 2 3 1 1 4 4 ...</code></pre>
<p>The local I is stored in the first column of a matrix where the rows are the counties. The other columns are the expected value for I, the variance of I, the <span class="math inline">\(z\)</span> value and the <span class="math inline">\(p\)</span>-value. For example, the local I statistics from the first county are given by typing</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="thurday-september-22-2022.html#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Ii_stats)</span></code></pre></div>
<pre><code>##             Ii          E.Ii       Var.Ii      Z.Ii Pr(z != E(Ii))
## 1  2.281375143 -2.748824e-02 7.124247e-01  2.735450    0.006229509
## 2  2.974750377 -4.354053e-02 1.109833e+00  2.865051    0.004169423
## 3  1.312440365 -1.827251e-02 3.539514e-01  2.236725    0.025304339
## 4  0.002313108 -2.007906e-07 5.351069e-06  1.000031    0.317295645
## 5 -1.032155817 -1.511126e-02 3.966295e-01 -1.614907    0.106330864
## 6 -0.493034653 -8.356103e-03 1.291002e-01 -1.348933    0.177358557</code></pre>
<p>Because these local values must average to the global value (when using row standardized weights), they can take on values outside the range between -1 and 1. A <code>summary()</code> method on the first column of the <code>Li</code> object gives statistics from the non-spatial distribution of I’s.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="thurday-september-22-2022.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Ii_stats[, <span class="dv">1</span>])</span></code></pre></div>
<pre><code>##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
## -1.03216  0.01733  0.26984  0.56348  1.05945  2.97475</code></pre>
<p>You map the values by first attaching the matrix columns of interest to the simple feature data frame. Here you attach <code>Ii</code>, <code>Var</code>, and <code>Pi</code>.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="thurday-september-22-2022.html#cb70-1" aria-hidden="true" tabindex="-1"></a>PE.sf<span class="sc">$</span>Ii <span class="ot">&lt;-</span> Ii_stats[, <span class="dv">1</span>]</span>
<span id="cb70-2"><a href="thurday-september-22-2022.html#cb70-2" aria-hidden="true" tabindex="-1"></a>PE.sf<span class="sc">$</span>Vi <span class="ot">&lt;-</span> Ii_stats[, <span class="dv">3</span>]</span>
<span id="cb70-3"><a href="thurday-september-22-2022.html#cb70-3" aria-hidden="true" tabindex="-1"></a>PE.sf<span class="sc">$</span>Pi <span class="ot">&lt;-</span> Ii_stats[, <span class="dv">5</span>]</span></code></pre></div>
<p>Then using the {ggplot2} syntax.</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="thurday-september-22-2022.html#cb71-1" aria-hidden="true" tabindex="-1"></a>( g1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> PE.sf) <span class="sc">+</span></span>
<span id="cb71-2"><a href="thurday-september-22-2022.html#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> Ii)) <span class="sc">+</span></span>
<span id="cb71-3"><a href="thurday-september-22-2022.html#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient2</span>(<span class="at">low =</span> <span class="st">&quot;green&quot;</span>,</span>
<span id="cb71-4"><a href="thurday-september-22-2022.html#cb71-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">high =</span> <span class="st">&quot;blue&quot;</span>) )</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<p>You also map out the variances.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="thurday-september-22-2022.html#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> PE.sf) <span class="sc">+</span></span>
<span id="cb72-2"><a href="thurday-september-22-2022.html#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> Vi)) <span class="sc">+</span></span>
<span id="cb72-3"><a href="thurday-september-22-2022.html#cb72-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p>Variances are larger for counties near the boundaries as the sample sizes are smaller.</p>
<p>Compare the map of local autocorrelation with a map of percent white.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="thurday-september-22-2022.html#cb73-1" aria-hidden="true" tabindex="-1"></a>( g2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> PE.sf) <span class="sc">+</span></span>
<span id="cb73-2"><a href="thurday-september-22-2022.html#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> WHITE)) <span class="sc">+</span></span>
<span id="cb73-3"><a href="thurday-september-22-2022.html#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">&quot;black&quot;</span>,</span>
<span id="cb73-4"><a href="thurday-september-22-2022.html#cb73-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">high =</span> <span class="st">&quot;white&quot;</span>) )</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<p>Plot them together.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="thurday-september-22-2022.html#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb74-2"><a href="thurday-september-22-2022.html#cb74-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-3"><a href="thurday-september-22-2022.html#cb74-3" aria-hidden="true" tabindex="-1"></a>g1 <span class="sc">+</span> g2</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<p>Areas where percent white is high over the northeast are areas with the largest spatial correlation. Other areas of high spatial correlation include the Mississippi Valley and in the south. Note the county with the most negative spatial correlation is the county in the northwest with a fairly high percentage of whites neighbored by counties with much lower percentages of whites.</p>
<p>Local values of Lee’s bi-variate spatial autocorrelation are available from the <code>spdep::lee()</code> function.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="thurday-september-22-2022.html#cb75-1" aria-hidden="true" tabindex="-1"></a>lee_stat <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">lee</span>(crime, police, </span>
<span id="cb75-2"><a href="thurday-september-22-2022.html#cb75-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">listw =</span> wts, </span>
<span id="cb75-3"><a href="thurday-september-22-2022.html#cb75-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">n =</span> <span class="fu">length</span>(nbs))</span>
<span id="cb75-4"><a href="thurday-september-22-2022.html#cb75-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-5"><a href="thurday-september-22-2022.html#cb75-5" aria-hidden="true" tabindex="-1"></a>PE.sf<span class="sc">$</span>localL <span class="ot">&lt;-</span> lee_stat<span class="sc">$</span>localL</span>
<span id="cb75-6"><a href="thurday-september-22-2022.html#cb75-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-7"><a href="thurday-september-22-2022.html#cb75-7" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_shape</span>(PE.sf) <span class="sc">+</span></span>
<span id="cb75-8"><a href="thurday-september-22-2022.html#cb75-8" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_fill</span>(<span class="st">&quot;localL&quot;</span>,</span>
<span id="cb75-9"><a href="thurday-september-22-2022.html#cb75-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">title =</span> <span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb75-10"><a href="thurday-september-22-2022.html#cb75-10" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb75-11"><a href="thurday-september-22-2022.html#cb75-11" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_layout</span>(<span class="at">title =</span> <span class="st">&quot;Local bi-variate spatial autocorrelation&quot;</span>,</span>
<span id="cb75-12"><a href="thurday-september-22-2022.html#cb75-12" aria-hidden="true" tabindex="-1"></a>                  <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Variable(s) &quot;localL&quot; contains positive and negative values, so midpoint is set to 0. Set midpoint = NA to show the full spectrum of the color palette.</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<p>Areas in dark green indicate where the correlation between crime and policing is most influenced by neighboring crime and policing.</p>
<p>Population and tornado reports</p>
<p>Is the frequency of tornado reports correlated with the number of people in a region? Might this correlation extend to the number of people in neighboring region?</p>
<p>To answer these questions you quantify the non-spatial correlation and the bi-variate spatial autocorrelation between tornado occurrences and population. To keep this manageable you focus on one state (Iowa).</p>
<p>Start by getting the U.S. Census data with functions from the {tidycensus} package. The <code>get_decennial()</code> function grants access to the 1990, 2000, and 2010 decennial US Census data and the <code>get_acs()</code> function grants access to the 5-year American Community Survey data. For example, here is how you get county-level population for Iowa.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="thurday-september-22-2022.html#cb77-1" aria-hidden="true" tabindex="-1"></a>Counties.sf <span class="ot">&lt;-</span> tidycensus<span class="sc">::</span><span class="fu">get_acs</span>(<span class="at">geography =</span> <span class="st">&quot;county&quot;</span>, </span>
<span id="cb77-2"><a href="thurday-september-22-2022.html#cb77-2" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">variables =</span> <span class="st">&quot;B02001_001E&quot;</span>, </span>
<span id="cb77-3"><a href="thurday-september-22-2022.html#cb77-3" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">state =</span> <span class="st">&quot;IA&quot;</span>,</span>
<span id="cb77-4"><a href="thurday-september-22-2022.html#cb77-4" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">geometry =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Getting data from the 2015-2019 5-year ACS</code></pre>
<pre><code>## Downloading feature geometry from the Census website.  To cache shapefiles for use in future sessions, set `options(tigris_use_cache = TRUE)`.</code></pre>
<pre><code>## 
  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |                                                                      |   1%
  |                                                                            
  |=                                                                     |   1%
  |                                                                            
  |=                                                                     |   2%
  |                                                                            
  |==                                                                    |   2%
  |                                                                            
  |==                                                                    |   3%
  |                                                                            
  |===                                                                   |   5%
  |                                                                            
  |====                                                                  |   5%
  |                                                                            
  |====                                                                  |   6%
  |                                                                            
  |=====                                                                 |   7%
  |                                                                            
  |=====                                                                 |   8%
  |                                                                            
  |======                                                                |   8%
  |                                                                            
  |======                                                                |   9%
  |                                                                            
  |=========                                                             |  13%
  |                                                                            
  |=============                                                         |  19%
  |                                                                            
  |==============                                                        |  21%
  |                                                                            
  |=================                                                     |  24%
  |                                                                            
  |==================                                                    |  25%
  |                                                                            
  |==================                                                    |  26%
  |                                                                            
  |===================                                                   |  27%
  |                                                                            
  |===================                                                   |  28%
  |                                                                            
  |====================                                                  |  28%
  |                                                                            
  |====================                                                  |  29%
  |                                                                            
  |=====================                                                 |  29%
  |                                                                            
  |=====================                                                 |  30%
  |                                                                            
  |=====================                                                 |  31%
  |                                                                            
  |======================                                                |  31%
  |                                                                            
  |======================                                                |  32%
  |                                                                            
  |=======================                                               |  33%
  |                                                                            
  |=======================                                               |  34%
  |                                                                            
  |========================                                              |  34%
  |                                                                            
  |========================                                              |  35%
  |                                                                            
  |=========================                                             |  35%
  |                                                                            
  |=========================                                             |  36%
  |                                                                            
  |==========================                                            |  37%
  |                                                                            
  |==========================                                            |  38%
  |                                                                            
  |===========================                                           |  39%
  |                                                                            
  |=============================                                         |  42%
  |                                                                            
  |==============================                                        |  43%
  |                                                                            
  |================================                                      |  45%
  |                                                                            
  |================================                                      |  46%
  |                                                                            
  |=================================                                     |  47%
  |                                                                            
  |======================================                                |  55%
  |                                                                            
  |=======================================                               |  56%
  |                                                                            
  |============================================                          |  63%
  |                                                                            
  |==============================================                        |  65%
  |                                                                            
  |==============================================                        |  66%
  |                                                                            
  |===============================================                       |  67%
  |                                                                            
  |================================================                      |  68%
  |                                                                            
  |================================================                      |  69%
  |                                                                            
  |==================================================                    |  71%
  |                                                                            
  |==================================================                    |  72%
  |                                                                            
  |===================================================                   |  72%
  |                                                                            
  |====================================================                  |  74%
  |                                                                            
  |=====================================================                 |  75%
  |                                                                            
  |======================================================                |  77%
  |                                                                            
  |=======================================================               |  79%
  |                                                                            
  |========================================================              |  80%
  |                                                                            
  |=========================================================             |  82%
  |                                                                            
  |===========================================================           |  84%
  |                                                                            
  |============================================================          |  86%
  |                                                                            
  |==================================================================    |  94%
  |                                                                            
  |===================================================================   |  96%
  |                                                                            
  |======================================================================| 100%</code></pre>
<p>The code returns a simple feature data frame with county borders as multi-polygons. The variable <code>B02001_001E</code> is the 2015-2019 population estimate in each county within the state.</p>
<p>Next get the tornado data and count the number of tracks by county. A single track can intersect more than one county.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="thurday-september-22-2022.html#cb81-1" aria-hidden="true" tabindex="-1"></a>Torn.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="at">dsn =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;1950-2020-torn-aspath&quot;</span>), </span>
<span id="cb81-2"><a href="thurday-september-22-2022.html#cb81-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">layer =</span> <span class="st">&quot;1950-2020-torn-aspath&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb81-3"><a href="thurday-september-22-2022.html#cb81-3" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> sf<span class="sc">::</span><span class="fu">st_crs</span>(Counties.sf)) <span class="sc">|&gt;</span></span>
<span id="cb81-4"><a href="thurday-september-22-2022.html#cb81-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(yr <span class="sc">&gt;=</span> <span class="dv">2015</span>)</span></code></pre></div>
<pre><code>## Reading layer `1950-2020-torn-aspath&#39; from data source 
##   `/Users/jameselsner/Desktop/ClassNotes/ASS-2022/data/1950-2020-torn-aspath&#39; 
##   using driver `ESRI Shapefile&#39;
## Simple feature collection with 66244 features and 22 fields
## Geometry type: LINESTRING
## Dimension:     XY
## Bounding box:  xmin: -163.53 ymin: 17.7212 xmax: -64.7151 ymax: 61.02
## Geodetic CRS:  WGS 84</code></pre>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="thurday-september-22-2022.html#cb83-1" aria-hidden="true" tabindex="-1"></a>( TorCounts.df <span class="ot">&lt;-</span> Torn.sf <span class="sc">|&gt;</span></span>
<span id="cb83-2"><a href="thurday-september-22-2022.html#cb83-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_intersection</span>(Counties.sf) <span class="sc">|&gt;</span></span>
<span id="cb83-3"><a href="thurday-september-22-2022.html#cb83-3" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span></span>
<span id="cb83-4"><a href="thurday-september-22-2022.html#cb83-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(GEOID) <span class="sc">|&gt;</span></span>
<span id="cb83-5"><a href="thurday-september-22-2022.html#cb83-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">nT =</span> dplyr<span class="sc">::</span><span class="fu">n</span>()) )</span></code></pre></div>
<pre><code>## Warning: attribute variables are assumed to be spatially constant throughout all
## geometries</code></pre>
<pre><code>## # A tibble: 89 × 2
##    GEOID    nT
##    &lt;chr&gt; &lt;int&gt;
##  1 19001     8
##  2 19003     4
##  3 19007     6
##  4 19011     7
##  5 19013     4
##  6 19015     7
##  7 19017     1
##  8 19019     4
##  9 19021     1
## 10 19023     1
## # … with 79 more rows</code></pre>
<p>Next join the counts to the simple feature data frame.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="thurday-september-22-2022.html#cb86-1" aria-hidden="true" tabindex="-1"></a>Counties.sf <span class="ot">&lt;-</span> Counties.sf <span class="sc">|&gt;</span></span>
<span id="cb86-2"><a href="thurday-september-22-2022.html#cb86-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">left_join</span>(TorCounts.df,</span>
<span id="cb86-3"><a href="thurday-september-22-2022.html#cb86-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">by =</span> <span class="st">&quot;GEOID&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb86-4"><a href="thurday-september-22-2022.html#cb86-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">nT =</span> tidyr<span class="sc">::</span><span class="fu">replace_na</span>(nT, <span class="dv">0</span>)) <span class="sc">|&gt;</span></span>
<span id="cb86-5"><a href="thurday-september-22-2022.html#cb86-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Area =</span> sf<span class="sc">::</span><span class="fu">st_area</span>(Counties.sf),</span>
<span id="cb86-6"><a href="thurday-september-22-2022.html#cb86-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">rate =</span> nT<span class="sc">/</span>Area<span class="sc">/</span>(<span class="dv">2020</span> <span class="sc">-</span> <span class="dv">2015</span> <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">10</span>,</span>
<span id="cb86-7"><a href="thurday-september-22-2022.html#cb86-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">lpop =</span> <span class="fu">log10</span>(estimate))</span></code></pre></div>
<p>Note that some counties have no tornadoes and the <code>dplyr::left_join()</code> returns a value of <code>NA</code> for those. You use <code>dplyr::mutate()</code> with <code>tidyr::replace_na()</code> to turn those counts to a value of 0.</p>
<p>Make a two-panel map displaying the log of the population and the tornado rates.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="thurday-september-22-2022.html#cb87-1" aria-hidden="true" tabindex="-1"></a>map1 <span class="ot">&lt;-</span> tmap<span class="sc">::</span><span class="fu">tm_shape</span>(Counties.sf) <span class="sc">+</span></span>
<span id="cb87-2"><a href="thurday-september-22-2022.html#cb87-2" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb87-3"><a href="thurday-september-22-2022.html#cb87-3" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">&quot;lpop&quot;</span>,</span>
<span id="cb87-4"><a href="thurday-september-22-2022.html#cb87-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">title =</span> <span class="st">&quot;Log Population&quot;</span>,</span>
<span id="cb87-5"><a href="thurday-september-22-2022.html#cb87-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">palette =</span> <span class="st">&quot;Blues&quot;</span>) <span class="sc">+</span></span>
<span id="cb87-6"><a href="thurday-september-22-2022.html#cb87-6" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_layout</span>(<span class="at">legend.outside =</span> <span class="st">&quot;TRUE&quot;</span>)</span>
<span id="cb87-7"><a href="thurday-september-22-2022.html#cb87-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-8"><a href="thurday-september-22-2022.html#cb87-8" aria-hidden="true" tabindex="-1"></a>map2 <span class="ot">&lt;-</span> tmap<span class="sc">::</span><span class="fu">tm_shape</span>(Counties.sf) <span class="sc">+</span></span>
<span id="cb87-9"><a href="thurday-september-22-2022.html#cb87-9" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb87-10"><a href="thurday-september-22-2022.html#cb87-10" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">&quot;rate&quot;</span>,</span>
<span id="cb87-11"><a href="thurday-september-22-2022.html#cb87-11" aria-hidden="true" tabindex="-1"></a>                <span class="at">title =</span> <span class="st">&quot;Annual Rate</span><span class="sc">\n</span><span class="st">[/10,000 sq. km]&quot;</span>,</span>
<span id="cb87-12"><a href="thurday-september-22-2022.html#cb87-12" aria-hidden="true" tabindex="-1"></a>                <span class="at">palette =</span> <span class="st">&quot;Greens&quot;</span>) <span class="sc">+</span></span>
<span id="cb87-13"><a href="thurday-september-22-2022.html#cb87-13" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_layout</span>(<span class="at">legend.outside =</span> <span class="st">&quot;TRUE&quot;</span>)</span>
<span id="cb87-14"><a href="thurday-september-22-2022.html#cb87-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-15"><a href="thurday-september-22-2022.html#cb87-15" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tmap_arrange</span>(map1, map2)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
<p>There appears some relationship. The non-spatial correlation between the two variables is obtained with the <code>cor.test()</code> function.</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="thurday-september-22-2022.html#cb88-1" aria-hidden="true" tabindex="-1"></a>lpop <span class="ot">&lt;-</span> Counties.sf<span class="sc">$</span>lpop</span>
<span id="cb88-2"><a href="thurday-september-22-2022.html#cb88-2" aria-hidden="true" tabindex="-1"></a>rate <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(Counties.sf<span class="sc">$</span>rate)</span>
<span id="cb88-3"><a href="thurday-september-22-2022.html#cb88-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-4"><a href="thurday-september-22-2022.html#cb88-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(lpop, rate)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  lpop and rate
## t = 3.8318, df = 97, p-value = 0.0002258
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.1779088 0.5225915
## sample estimates:
##       cor 
## 0.3625861</code></pre>
<p>The bi-variate spatial autocorrelation is assessed using the Lee statistic. A formal non-parametric test under the null hypothesis of no bi-variate spatial autocorrelation is done using a Monte Carlo simulation.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="thurday-september-22-2022.html#cb90-1" aria-hidden="true" tabindex="-1"></a>nbs <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">poly2nb</span>(Counties.sf)</span>
<span id="cb90-2"><a href="thurday-september-22-2022.html#cb90-2" aria-hidden="true" tabindex="-1"></a>wts <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">nb2listw</span>(nbs)</span>
<span id="cb90-3"><a href="thurday-september-22-2022.html#cb90-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-4"><a href="thurday-september-22-2022.html#cb90-4" aria-hidden="true" tabindex="-1"></a>lee_stat <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">lee</span>(lpop, rate, </span>
<span id="cb90-5"><a href="thurday-september-22-2022.html#cb90-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">listw =</span> wts, </span>
<span id="cb90-6"><a href="thurday-september-22-2022.html#cb90-6" aria-hidden="true" tabindex="-1"></a>                       <span class="at">n =</span> <span class="fu">length</span>(nbs))</span>
<span id="cb90-7"><a href="thurday-september-22-2022.html#cb90-7" aria-hidden="true" tabindex="-1"></a>lee_stat<span class="sc">$</span>L</span></code></pre></div>
<pre><code>## [1] 0.2049081</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="thurday-september-22-2022.html#cb92-1" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">lee.mc</span>(lpop, rate, <span class="at">listw =</span> wts, <span class="at">nsim =</span> <span class="dv">9999</span>)</span></code></pre></div>
<pre><code>## 
##  Monte-Carlo simulation of Lee&#39;s L
## 
## data:  lpop ,  rate 
## weights: wts  
## number of simulations + 1: 10000 
## 
## statistic = 0.20491, observed rank = 10000, p-value = 1e-04
## alternative hypothesis: greater</code></pre>
<p>Finally you map out the local variation in the bi-variate spatial autocorrelation.</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="thurday-september-22-2022.html#cb94-1" aria-hidden="true" tabindex="-1"></a>Counties.sf<span class="sc">$</span>localL <span class="ot">&lt;-</span> lee_stat<span class="sc">$</span>localL</span>
<span id="cb94-2"><a href="thurday-september-22-2022.html#cb94-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-3"><a href="thurday-september-22-2022.html#cb94-3" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_shape</span>(Counties.sf) <span class="sc">+</span></span>
<span id="cb94-4"><a href="thurday-september-22-2022.html#cb94-4" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_fill</span>(<span class="st">&quot;localL&quot;</span>,</span>
<span id="cb94-5"><a href="thurday-september-22-2022.html#cb94-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">title =</span> <span class="st">&quot;Local Bivariate</span><span class="sc">\n</span><span class="st">Spatial Autocorrelation&quot;</span>) <span class="sc">+</span></span>
<span id="cb94-6"><a href="thurday-september-22-2022.html#cb94-6" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb94-7"><a href="thurday-september-22-2022.html#cb94-7" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_layout</span>(<span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Variable(s) &quot;localL&quot; contains positive and negative values, so midpoint is set to 0. Set midpoint = NA to show the full spectrum of the color palette.</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>
<p>What might cause this? Compare with Kansas.</p>
<p>Also, compare local Lee with local Moran.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="thurday-september-22-2022.html#cb96-1" aria-hidden="true" tabindex="-1"></a>Ii_stats <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">localmoran</span>(rate, </span>
<span id="cb96-2"><a href="thurday-september-22-2022.html#cb96-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">listw =</span> wts)</span>
<span id="cb96-3"><a href="thurday-september-22-2022.html#cb96-3" aria-hidden="true" tabindex="-1"></a>Counties.sf<span class="sc">$</span>localI <span class="ot">=</span> Ii_stats[, <span class="dv">1</span>]</span>
<span id="cb96-4"><a href="thurday-september-22-2022.html#cb96-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-5"><a href="thurday-september-22-2022.html#cb96-5" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_shape</span>(Counties.sf) <span class="sc">+</span></span>
<span id="cb96-6"><a href="thurday-september-22-2022.html#cb96-6" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb96-7"><a href="thurday-september-22-2022.html#cb96-7" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">&quot;localI&quot;</span>,</span>
<span id="cb96-8"><a href="thurday-september-22-2022.html#cb96-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">title =</span> <span class="st">&quot;Local Autocorrelation&quot;</span>,</span>
<span id="cb96-9"><a href="thurday-september-22-2022.html#cb96-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">palette =</span> <span class="st">&quot;Purples&quot;</span>) <span class="sc">+</span></span>
<span id="cb96-10"><a href="thurday-september-22-2022.html#cb96-10" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_layout</span>(<span class="at">legend.outside =</span> <span class="st">&quot;TRUE&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-43-1.png" width="672" /></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tuesday-september-20-2022.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
