<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Thursday October 20, 2022 | GIS5122: Applied Spatial Statistics</title>
  <meta name="description" content="Thursday October 20, 2022 | GIS5122: Applied Spatial Statistics" />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="Thursday October 20, 2022 | GIS5122: Applied Spatial Statistics" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="jelsner/ASS-2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Thursday October 20, 2022 | GIS5122: Applied Spatial Statistics" />
  
  
  

<meta name="author" content="James B. Elsner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tuesday-october-18-2022.html"/>
<link rel="next" href="tuesday-october-25-2022.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied Spatial Statistics</a></li>

<li class="divider"></li>
<li><a href="index.html#section"></a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i>Syllabus</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#gis5122-applied-spatial-statistics"><i class="fa fa-check"></i>GIS5122: Applied Spatial Statistics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#contact-information"><i class="fa fa-check"></i>Contact information</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#course-description"><i class="fa fa-check"></i>Course description</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#expected-learning-outcomes"><i class="fa fa-check"></i>Expected learning outcomes</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#materials"><i class="fa fa-check"></i>Materials</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#class-meetings"><i class="fa fa-check"></i>Class meetings</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#grades"><i class="fa fa-check"></i>Grades</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#ethics"><i class="fa fa-check"></i>Ethics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#outline-of-topics"><i class="fa fa-check"></i>Outline of topics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#schedule-subject-to-change-with-notice"><i class="fa fa-check"></i>Schedule (subject to change with notice)</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#reference-materials"><i class="fa fa-check"></i>Reference materials</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#reproducible-research"><i class="fa fa-check"></i>Reproducible research</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html"><i class="fa fa-check"></i>Tuesday, August 23, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#install-r-and-rstudio-on-your-computer"><i class="fa fa-check"></i>Install R and RStudio on your computer</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#download-course-materials"><i class="fa fa-check"></i>Download course materials</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#read-the-syllabus"><i class="fa fa-check"></i>Read the syllabus</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#about-rstudio"><i class="fa fa-check"></i>About RStudio</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#lab-assignments"><i class="fa fa-check"></i>Lab assignments</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#getting-started-with-r"><i class="fa fa-check"></i>Getting started with R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#are-you-completely-new-to-r"><i class="fa fa-check"></i>Are you completely new to R?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html"><i class="fa fa-check"></i>Thursday, August 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#expectations"><i class="fa fa-check"></i>Expectations</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-science-workflow-with-r-markdown"><i class="fa fa-check"></i>Data science workflow with R markdown</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#an-introduction-to-using-r"><i class="fa fa-check"></i>An introduction to using R</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-frames"><i class="fa fa-check"></i>Data frames</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html"><i class="fa fa-check"></i>Tuesday August 30, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#working-with-data-frames"><i class="fa fa-check"></i>Working with data frames</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html"><i class="fa fa-check"></i>Thursday September 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#making-graphs"><i class="fa fa-check"></i>Making graphs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html"><i class="fa fa-check"></i>Tuesday September 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#working-with-spatial-data"><i class="fa fa-check"></i>Working with spatial data</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#geo-computation-on-simple-features"><i class="fa fa-check"></i>Geo-computation on simple features</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html"><i class="fa fa-check"></i>Thursday September 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#spatial-data-subsets-and-joins"><i class="fa fa-check"></i>Spatial data subsets and joins</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#interpolation-using-areal-weights"><i class="fa fa-check"></i>Interpolation using areal weights</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html"><i class="fa fa-check"></i>Tuesday September 13, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#s4-spatial-data-objects"><i class="fa fa-check"></i>S4 spatial data objects</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#working-with-raster-data"><i class="fa fa-check"></i>Working with raster data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html"><i class="fa fa-check"></i>Thursday September 15, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#working-with-space-time-data"><i class="fa fa-check"></i>Working with space-time data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#mapping-using-functions-from-the-ggplot2-package"><i class="fa fa-check"></i>Mapping using functions from the {ggplot2} package</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#mapping-using-functions-from-the-tmap-package"><i class="fa fa-check"></i>Mapping using functions from the {tmap} package</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#creating-an-interactive-map"><i class="fa fa-check"></i>Creating an interactive map</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#adding-an-inset-map"><i class="fa fa-check"></i>Adding an inset map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html"><i class="fa fa-check"></i>Tuesday September 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#defining-spatial-neighborhoods-and-spatial-weights"><i class="fa fa-check"></i>Defining spatial neighborhoods and spatial weights</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#computing-autocorrelation"><i class="fa fa-check"></i>Computing autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#spatial-lag-and-its-relation-to-autocorrelation"><i class="fa fa-check"></i>Spatial lag and its relation to autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html"><i class="fa fa-check"></i>Thursday September 22, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#other-neighbor-definitions"><i class="fa fa-check"></i>Other neighbor definitions</a></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#assessing-the-statistical-significance-of-autocorrelation"><i class="fa fa-check"></i>Assessing the statistical significance of autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#bivariate-spatial-autocorrelation"><i class="fa fa-check"></i>Bivariate spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#local-indicators-of-spatial-autocorrelation"><i class="fa fa-check"></i>Local indicators of spatial autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-27-2022.html"><a href="tuesday-september-27-2022.html"><i class="fa fa-check"></i>Tuesday September 27, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-27-2022.html"><a href="tuesday-september-27-2022.html#constraining-group-membership-based-on-spatial-autocorrelation"><i class="fa fa-check"></i>Constraining group membership based on spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-27-2022.html"><a href="tuesday-september-27-2022.html#estimating-spatial-autocorrelation-in-model-residuals"><i class="fa fa-check"></i>Estimating spatial autocorrelation in model residuals</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-27-2022.html"><a href="tuesday-september-27-2022.html#choosing-a-spatial-regression-model"><i class="fa fa-check"></i>Choosing a spatial regression model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html"><i class="fa fa-check"></i>Thursday September 29, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#fitting-and-interpreting-a-spatially-lagged-y-model"><i class="fa fa-check"></i>Fitting and interpreting a spatially-lagged Y model</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#fitting-and-interpreting-a-spatially-lagged-x-model"><i class="fa fa-check"></i>Fitting and interpreting a spatially-lagged X model</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#fitting-and-interpreting-spatial-durbin-models"><i class="fa fa-check"></i>Fitting and interpreting spatial Durbin models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html"><i class="fa fa-check"></i>Tuesday October 4, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#fitting-and-interpreting-geographic-regressions"><i class="fa fa-check"></i>Fitting and interpreting geographic regressions</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#mapping-incidence-and-risk-with-spatial-regression-models"><i class="fa fa-check"></i>Mapping incidence and risk with spatial regression models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html"><i class="fa fa-check"></i>Thursday October 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#spatial-data-as-point-patterns"><i class="fa fa-check"></i>Spatial data as point patterns</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#working-with-point-pattern-objects-using-functions-from-the-spatstat-package"><i class="fa fa-check"></i>Working with point pattern objects using functions from the {spatstat} package</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#quantifying-event-intensity"><i class="fa fa-check"></i>Quantifying event intensity</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html"><i class="fa fa-check"></i>Tuesday October 11, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#creating-ppp-and-owin-objects-from-simple-feature-data-frames"><i class="fa fa-check"></i>Creating <code>ppp</code> and <code>owin</code> objects from simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#estimating-spatial-intensity-as-a-function-of-distance"><i class="fa fa-check"></i>Estimating spatial intensity as a function of distance</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#intensity-trend-as-a-possible-confounding-factor"><i class="fa fa-check"></i>Intensity trend as a possible confounding factor</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html"><i class="fa fa-check"></i>Thursday October 13, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html#estimating-the-relative-risk-of-events"><i class="fa fa-check"></i>Estimating the relative risk of events</a></li>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html#estimating-second-moment-properties-of-spatial-events"><i class="fa fa-check"></i>Estimating second-moment properties of spatial events</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html"><i class="fa fa-check"></i>Tuesday October 18, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#examples-of-spatially-clustered-events"><i class="fa fa-check"></i>Examples of spatially clustered events</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#determining-the-statistical-significance-of-event-clustering"><i class="fa fa-check"></i>Determining the statistical significance of event clustering</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#estimating-event-clustering-in-multi-type-event-locations"><i class="fa fa-check"></i>Estimating event clustering in multi-type event locations</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#more-about-the-ripley-k-function"><i class="fa fa-check"></i>More about the Ripley K function</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html"><i class="fa fa-check"></i>Thursday October 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#inferring-event-interaction-from-distance-functions"><i class="fa fa-check"></i>Inferring event interaction from distance functions</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#removing-duplicate-event-locations-and-defining-the-domain"><i class="fa fa-check"></i>Removing duplicate event locations and defining the domain</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#modeling-point-pattern-data"><i class="fa fa-check"></i>Modeling point pattern data</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#fitting-and-interpreting-an-inhibition-model"><i class="fa fa-check"></i>Fitting and interpreting an inhibition model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html"><i class="fa fa-check"></i>Tuesday October 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#fitting-and-interpreting-a-cluster-model"><i class="fa fa-check"></i>Fitting and interpreting a cluster model</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#workflow-in-fitting-a-model-to-point-pattern-data"><i class="fa fa-check"></i>Workflow in fitting a model to point pattern data</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#assessing-how-well-the-model-fits-the-data"><i class="fa fa-check"></i>Assessing how well the model fits the data</a>
<ul>
<li class="chapter" data-level="0.0.1" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#example-1-tropical-trees"><i class="fa fa-check"></i><b>0.0.1</b> Example 1: Tropical trees</a></li>
<li class="chapter" data-level="0.0.2" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#example-2-violent-tornado-occurrence"><i class="fa fa-check"></i><b>0.0.2</b> Example 2: Violent tornado occurrence</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html"><i class="fa fa-check"></i>Thursday October 27, 2022</a>
<ul>
<li class="chapter" data-level="0.1" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#modeling-the-occurrence-of-violent-tornadoes"><i class="fa fa-check"></i><b>0.1</b> Modeling the occurrence of violent tornadoes</a></li>
<li class="chapter" data-level="0.2" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#terrain-roughness-and-tornado-occurrence-rates"><i class="fa fa-check"></i><b>0.2</b> Terrain roughness and tornado occurrence rates</a></li>
<li class="chapter" data-level="0.3" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#spatial-logistic-regression"><i class="fa fa-check"></i><b>0.3</b> Spatial logistic regression</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GIS5122: Applied Spatial Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="thursday-october-20-2022" class="section level1 unnumbered hasAnchor">
<h1>Thursday October 20, 2022<a href="thursday-october-20-2022.html#thursday-october-20-2022" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>“Weeks of coding can save you hours of planning.”</strong> - Unknown</p>
<p>Today
- Inferring event interaction from distance functions
- Removing duplicate event locations and defining the domain
- Modeling point pattern data
- Fitting and interpreting an inhibition model</p>
<div id="inferring-event-interaction-from-distance-functions" class="section level2 unnumbered hasAnchor">
<h2>Inferring event interaction from distance functions<a href="thursday-october-20-2022.html#inferring-event-interaction-from-distance-functions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The distance functions (<span class="math inline">\(G\)</span>, <span class="math inline">\(K\)</span>, etc) that are used to quantify clustering are defined and estimated under the assumption that the process that produced the events is stationary (homogeneous). If this is true then you can treat any sub-region of the domain as an independent and identically distributed (iid) sample from the entire set of data.</p>
<p>If the spatial distribution of the event locations is influenced by event interaction then the functions will deviate from the theoretical model of CSR. But a deviation from CSR does not imply event interaction.</p>
<p>Moreover, the functions characterize the spatial arrangement of event locations ‘on average’ so variability in an interaction as a function of scale may not be detected.</p>
<p>As an example of the latter case, here you generate event locations at random with clustering on a small scale but with regularity on a larger scale. On average the event locations are CSR as indicated by the <span class="math inline">\(K\)</span> function.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="thursday-october-20-2022.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(spatstat))</span>
<span id="cb1-2"><a href="thursday-october-20-2022.html#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="thursday-october-20-2022.html#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">0112</span>)</span>
<span id="cb1-4"><a href="thursday-october-20-2022.html#cb1-4" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">rcell</span>(<span class="at">nx =</span> <span class="dv">15</span>)</span>
<span id="cb1-5"><a href="thursday-october-20-2022.html#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X, <span class="at">main =</span> <span class="st">&quot;&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>There are two ‘local’ clusters one in the north and one in the south. But overall the events appear to be more regular (inhibition) than CSR.</p>
<p>Interpretation of the process that created the event locations based on Ripley’s <span class="math inline">\(K\)</span> would be that the arrangement of events is CSR.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="thursday-october-20-2022.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-2"><a href="thursday-october-20-2022.html#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="thursday-october-20-2022.html#cb2-3" aria-hidden="true" tabindex="-1"></a>K.df <span class="ot">&lt;-</span> X <span class="sc">|&gt;</span></span>
<span id="cb2-4"><a href="thursday-october-20-2022.html#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Kest</span>() <span class="sc">|&gt;</span></span>
<span id="cb2-5"><a href="thursday-october-20-2022.html#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span>
<span id="cb2-6"><a href="thursday-october-20-2022.html#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="thursday-october-20-2022.html#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(K.df, <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> iso)) <span class="sc">+</span></span>
<span id="cb2-8"><a href="thursday-october-20-2022.html#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb2-9"><a href="thursday-october-20-2022.html#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb2-10"><a href="thursday-october-20-2022.html#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb2-11"><a href="thursday-october-20-2022.html#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>The empirical curve (black line) coincides with the theoretical CSR line (red line) indicating CSR.</p>
<p>And the maximum absolute deviation test under the null hypothesis of CSR returns a large <span class="math inline">\(p\)</span>-value so you fail to reject it.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="thursday-october-20-2022.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mad.test</span>(X, <span class="at">fun =</span> Kest, <span class="at">nsim =</span> <span class="dv">99</span>)</span></code></pre></div>
<pre><code>## Generating 99 simulations of CSR  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
## 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,  99.
## 
## Done.</code></pre>
<pre><code>## 
##  Maximum absolute deviation test of CSR
##  Monte Carlo test based on 99 simulations
##  Summary function: K(r)
##  Reference function: theoretical
##  Alternative: two.sided
##  Interval of distance values: [0, 0.25]
##  Test statistic: Maximum absolute deviation
##  Deviation = observed minus theoretical
## 
## data:  X
## mad = 0.0023931, rank = 87, p-value = 0.87</code></pre>
<p>As an example of the former case, here you generate event locations that have no inter-event interaction but there is a trend in the spatial intensity.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="thursday-october-20-2022.html#cb6-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">rpoispp</span>(<span class="cf">function</span>(x, y){ <span class="dv">300</span> <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="dv">3</span> <span class="sc">*</span> x) })</span>
<span id="cb6-2"><a href="thursday-october-20-2022.html#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X, <span class="at">main =</span> <span class="st">&quot;&quot;</span>) </span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>By design there is a clear trend toward fewer events moving toward the east.</p>
<p>You compute and plot the <span class="math inline">\(K\)</span> function on these event locations.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="thursday-october-20-2022.html#cb7-1" aria-hidden="true" tabindex="-1"></a>K.df <span class="ot">&lt;-</span> X <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="thursday-october-20-2022.html#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Kest</span>() <span class="sc">|&gt;</span></span>
<span id="cb7-3"><a href="thursday-october-20-2022.html#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span>
<span id="cb7-4"><a href="thursday-october-20-2022.html#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="thursday-october-20-2022.html#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(K.df, <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> iso)) <span class="sc">+</span></span>
<span id="cb7-6"><a href="thursday-october-20-2022.html#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb7-7"><a href="thursday-october-20-2022.html#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb7-8"><a href="thursday-october-20-2022.html#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb7-9"><a href="thursday-october-20-2022.html#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>The <span class="math inline">\(K\)</span> function indicates clustering but this is an artifact of the trend in the intensity.</p>
<p>In the case of a known trend in the spatial intensity, you need to use the <code>Kinhom()</code> function. For example, compare the uncertainty envelopes from a homogeneous and inhomogeneous Poisson process.</p>
<p>Start by plotting the output from the <code>envelope()</code> function with <code>fun = Kest</code>. The <code>global = TRUE</code> argument indicates that the envelopes are simultaneous rather than point-wise (<code>global = FALSE</code> which is the default). Point-wise envelopes assume the estimates are independent (usually not a good assumption) across the range of distances so the standard errors will be smaller resulting in narrower bands.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="thursday-october-20-2022.html#cb8-1" aria-hidden="true" tabindex="-1"></a>Kenv <span class="ot">&lt;-</span> <span class="fu">envelope</span>(X, </span>
<span id="cb8-2"><a href="thursday-october-20-2022.html#cb8-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fun =</span> Kest, </span>
<span id="cb8-3"><a href="thursday-october-20-2022.html#cb8-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">nsim =</span> <span class="dv">39</span>, </span>
<span id="cb8-4"><a href="thursday-october-20-2022.html#cb8-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">rank =</span> <span class="dv">1</span>, </span>
<span id="cb8-5"><a href="thursday-october-20-2022.html#cb8-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">global =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Generating 39 simulations of CSR  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,  39.
## 
## Done.</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="thursday-october-20-2022.html#cb10-1" aria-hidden="true" tabindex="-1"></a>Kenv.df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(Kenv)</span>
<span id="cb10-2"><a href="thursday-october-20-2022.html#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="thursday-october-20-2022.html#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Kenv.df, <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> obs)) <span class="sc">+</span></span>
<span id="cb10-4"><a href="thursday-october-20-2022.html#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lo, <span class="at">ymax =</span> hi), <span class="at">fill =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb10-5"><a href="thursday-october-20-2022.html#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb10-6"><a href="thursday-october-20-2022.html#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb10-7"><a href="thursday-october-20-2022.html#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb10-8"><a href="thursday-october-20-2022.html#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>After a distance of about .15 units the empirical curve (black line) is outside the uncertainty band indicating the events are more clustered than CSR.</p>
<p>However when you use the <code>fun = Kinhom</code> the empirical curve is completely inside the uncertainty band.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="thursday-october-20-2022.html#cb11-1" aria-hidden="true" tabindex="-1"></a>Kenv <span class="ot">&lt;-</span> <span class="fu">envelope</span>(X, </span>
<span id="cb11-2"><a href="thursday-october-20-2022.html#cb11-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fun =</span> Kinhom, </span>
<span id="cb11-3"><a href="thursday-october-20-2022.html#cb11-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">nsim =</span> <span class="dv">99</span>, </span>
<span id="cb11-4"><a href="thursday-october-20-2022.html#cb11-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">rank =</span> <span class="dv">1</span>, </span>
<span id="cb11-5"><a href="thursday-october-20-2022.html#cb11-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">global =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Generating 99 simulations of CSR  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
## 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,  99.
## 
## Done.</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="thursday-october-20-2022.html#cb13-1" aria-hidden="true" tabindex="-1"></a>Kenv.df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(Kenv)</span>
<span id="cb13-2"><a href="thursday-october-20-2022.html#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="thursday-october-20-2022.html#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Kenv.df, <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> obs)) <span class="sc">+</span></span>
<span id="cb13-4"><a href="thursday-october-20-2022.html#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lo, <span class="at">ymax =</span> hi), <span class="at">fill =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb13-5"><a href="thursday-october-20-2022.html#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb13-6"><a href="thursday-october-20-2022.html#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb13-7"><a href="thursday-october-20-2022.html#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r), Expected number of additional events</span><span class="sc">\n</span><span class="st"> within a distance r of an event&quot;</span>) <span class="sc">+</span></span>
<span id="cb13-8"><a href="thursday-october-20-2022.html#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>You conclude that the point pattern data are consistent with an inhomogeneous Poisson process without event interaction.</p>
<p>Let’s return to the Kansas tornadoes (EF1+). You import the data and create a point pattern object windowed by the state borders.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="thursday-october-20-2022.html#cb14-1" aria-hidden="true" tabindex="-1"></a>Torn.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="at">dsn =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;1950-2020-torn-initpoint&quot;</span>)) <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="thursday-october-20-2022.html#cb14-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3082</span>) <span class="sc">|&gt;</span></span>
<span id="cb14-3"><a href="thursday-october-20-2022.html#cb14-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(mag <span class="sc">&gt;=</span> <span class="dv">1</span>, yr <span class="sc">&gt;=</span> <span class="dv">1994</span>) <span class="sc">|&gt;</span></span>
<span id="cb14-4"><a href="thursday-october-20-2022.html#cb14-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">EF =</span> <span class="fu">as.factor</span>(mag)) <span class="sc">|&gt;</span></span>
<span id="cb14-5"><a href="thursday-october-20-2022.html#cb14-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(EF)</span></code></pre></div>
<pre><code>## Reading layer `1950-2020-torn-initpoint&#39; from data source 
##   `/Users/jameselsner/Desktop/ClassNotes/ASS-2022/data/1950-2020-torn-initpoint&#39; 
##   using driver `ESRI Shapefile&#39;
## Simple feature collection with 66244 features and 22 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -163.53 ymin: 17.7212 xmax: -64.7151 ymax: 61.02
## Geodetic CRS:  WGS 84</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="thursday-october-20-2022.html#cb16-1" aria-hidden="true" tabindex="-1"></a>ST.ppp <span class="ot">&lt;-</span> Torn.sf[<span class="st">&quot;EF&quot;</span>] <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="thursday-october-20-2022.html#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.ppp</span>()</span>
<span id="cb16-3"><a href="thursday-october-20-2022.html#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="thursday-october-20-2022.html#cb16-4" aria-hidden="true" tabindex="-1"></a>KS.sf <span class="ot">&lt;-</span> USAboundaries<span class="sc">::</span><span class="fu">us_states</span>(<span class="at">states =</span> <span class="st">&quot;Kansas&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb16-5"><a href="thursday-october-20-2022.html#cb16-5" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> sf<span class="sc">::</span><span class="fu">st_crs</span>(Torn.sf)<span class="sc">$</span>proj4string)</span>
<span id="cb16-6"><a href="thursday-october-20-2022.html#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="thursday-october-20-2022.html#cb16-7" aria-hidden="true" tabindex="-1"></a>W <span class="ot">&lt;-</span> KS.sf <span class="sc">|&gt;</span></span>
<span id="cb16-8"><a href="thursday-october-20-2022.html#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.owin</span>()</span>
<span id="cb16-9"><a href="thursday-october-20-2022.html#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="thursday-october-20-2022.html#cb16-10" aria-hidden="true" tabindex="-1"></a>ST.ppp <span class="ot">&lt;-</span> ST.ppp[W] <span class="sc">|&gt;</span></span>
<span id="cb16-11"><a href="thursday-october-20-2022.html#cb16-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rescale</span>(<span class="at">s =</span> <span class="dv">1000</span>, </span>
<span id="cb16-12"><a href="thursday-october-20-2022.html#cb16-12" aria-hidden="true" tabindex="-1"></a>          <span class="at">unitname =</span> <span class="st">&quot;km&quot;</span>)</span>
<span id="cb16-13"><a href="thursday-october-20-2022.html#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ST.ppp)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>There are more tornado reports in the west than in the east, especially across the southern part of the state indicating the process producing the events is not homogeneous. This means there are other factors contributing to local event intensity.</p>
<p>Evidence for clustering must account for this inhomogeneity. Here you do this by computing the envelope around the inhomogeneous Ripley K function using the argument <code>fun = Kinhom</code>.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="thursday-october-20-2022.html#cb17-1" aria-hidden="true" tabindex="-1"></a>Kenv <span class="ot">&lt;-</span> <span class="fu">envelope</span>(ST.ppp,</span>
<span id="cb17-2"><a href="thursday-october-20-2022.html#cb17-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fun =</span> Kinhom,</span>
<span id="cb17-3"><a href="thursday-october-20-2022.html#cb17-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">nsim =</span> <span class="dv">39</span>,</span>
<span id="cb17-4"><a href="thursday-october-20-2022.html#cb17-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">rank =</span> <span class="dv">1</span>,</span>
<span id="cb17-5"><a href="thursday-october-20-2022.html#cb17-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">global =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Generating 39 simulations of CSR  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,  39.
## 
## Done.</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="thursday-october-20-2022.html#cb19-1" aria-hidden="true" tabindex="-1"></a>Kenv.df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(Kenv)</span>
<span id="cb19-2"><a href="thursday-october-20-2022.html#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="thursday-october-20-2022.html#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Kenv.df, <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> obs)) <span class="sc">+</span></span>
<span id="cb19-4"><a href="thursday-october-20-2022.html#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lo, <span class="at">ymax =</span> hi), <span class="at">fill =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb19-5"><a href="thursday-october-20-2022.html#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb19-6"><a href="thursday-october-20-2022.html#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb19-7"><a href="thursday-october-20-2022.html#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb19-8"><a href="thursday-october-20-2022.html#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>The output reveals no evidence of clustering at distances less than about 70 km. At greater distances there is evidence of regularity indicated by the black line significantly below the red line. This is due to the fact that tornado reports are more common near cities and towns and cities and towns tend to be spread out more regular than CSR.</p>
</div>
<div id="removing-duplicate-event-locations-and-defining-the-domain" class="section level2 unnumbered hasAnchor">
<h2>Removing duplicate event locations and defining the domain<a href="thursday-october-20-2022.html#removing-duplicate-event-locations-and-defining-the-domain" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The functions in the {spatstat} package require the event locations (as a <code>ppp</code> object) and a domain over which the spatial statistics are computed (as an <code>owin</code> object).</p>
<p>If no <code>owin</code> object is specified, the statistics are computed over a rectangle (bounding box) defined by the northern most, southern most, eastern most, and western most event locations.</p>
<p>To see this, consider the Florida wildfire data as a simple feature data frame. Extract only fires occurring in Baker County (west of Duval County–Jacksonville). Include only wildfires started by lightning and select the fire size variable.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="thursday-october-20-2022.html#cb20-1" aria-hidden="true" tabindex="-1"></a>FL_Fires.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="at">dsn =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;FL_Fires&quot;</span>)) <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a href="thursday-october-20-2022.html#cb20-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3086</span>)</span></code></pre></div>
<pre><code>## Reading layer `FL_Fires&#39; from data source 
##   `/Users/jameselsner/Desktop/ClassNotes/ASS-2022/data/FL_Fires&#39; 
##   using driver `ESRI Shapefile&#39;
## Simple feature collection with 90261 features and 37 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -9750382 ymin: 2824449 xmax: -8908899 ymax: 3632749
## Projected CRS: Mercator_2SP</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="thursday-october-20-2022.html#cb22-1" aria-hidden="true" tabindex="-1"></a>Baker.sf <span class="ot">&lt;-</span> USAboundaries<span class="sc">::</span><span class="fu">us_counties</span>(<span class="at">states =</span> <span class="st">&quot;FL&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="thursday-october-20-2022.html#cb22-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(name) <span class="sc">|&gt;</span></span>
<span id="cb22-3"><a href="thursday-october-20-2022.html#cb22-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(name <span class="sc">==</span> <span class="st">&quot;Baker&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb22-4"><a href="thursday-october-20-2022.html#cb22-4" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3086</span>)</span>
<span id="cb22-5"><a href="thursday-october-20-2022.html#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="thursday-october-20-2022.html#cb22-6" aria-hidden="true" tabindex="-1"></a>BakerFires.sf <span class="ot">&lt;-</span> FL_Fires.sf <span class="sc">|&gt;</span></span>
<span id="cb22-7"><a href="thursday-october-20-2022.html#cb22-7" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_intersection</span>(Baker.sf) <span class="sc">|&gt;</span></span>
<span id="cb22-8"><a href="thursday-october-20-2022.html#cb22-8" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(STAT_CAU_1 <span class="sc">==</span> <span class="st">&quot;Lightning&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb22-9"><a href="thursday-october-20-2022.html#cb22-9" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(FIRE_SIZE_)</span></code></pre></div>
<pre><code>## Warning: attribute variables are assumed to be spatially constant throughout all
## geometries</code></pre>
<p>Create a <code>ppp</code> object and an unmarked <code>ppp</code> object. Summarize the unmarked object and make a plot.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="thursday-october-20-2022.html#cb24-1" aria-hidden="true" tabindex="-1"></a>BF.ppp <span class="ot">&lt;-</span> BakerFires.sf <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="thursday-october-20-2022.html#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.ppp</span>() </span>
<span id="cb24-3"><a href="thursday-october-20-2022.html#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="thursday-october-20-2022.html#cb24-4" aria-hidden="true" tabindex="-1"></a>BFU.ppp <span class="ot">&lt;-</span> <span class="fu">unmark</span>(BF.ppp)</span>
<span id="cb24-5"><a href="thursday-october-20-2022.html#cb24-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-6"><a href="thursday-october-20-2022.html#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(BFU.ppp)</span></code></pre></div>
<pre><code>## Planar point pattern:  327 points
## Average intensity 1.797954e-07 points per square unit
## 
## *Pattern contains duplicated points*
## 
## Coordinates are given to 2 decimal places
## i.e. rounded to the nearest multiple of 0.01 units
## 
## Window: rectangle = [547988.2, 587567.5] x [682872.2, 728823.8] units
##                     (39580 x 45950 units)
## Window area = 1818730000 square units</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="thursday-october-20-2022.html#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(BFU.ppp)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>The average intensity is 18 wildfires per 10 square km. But the intensity is based on a square domain. The lack of events in the northeast part of the domain is due to the fact that you removed wildfires outside the county border.</p>
<p>Further, two event locations are identical if their x,y coordinates are the same, and their marks are the same (if they carry marks).</p>
<p>Remove duplicate events with the <code>unique()</code> function, set the domain to be the county border, and set the name for the unit of length to meters.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="thursday-october-20-2022.html#cb27-1" aria-hidden="true" tabindex="-1"></a>BFU.ppp <span class="ot">&lt;-</span> <span class="fu">unique</span>(BFU.ppp)</span>
<span id="cb27-2"><a href="thursday-october-20-2022.html#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="thursday-october-20-2022.html#cb27-3" aria-hidden="true" tabindex="-1"></a>W <span class="ot">&lt;-</span> Baker.sf <span class="sc">|&gt;</span></span>
<span id="cb27-4"><a href="thursday-october-20-2022.html#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.owin</span>()</span>
<span id="cb27-5"><a href="thursday-october-20-2022.html#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="thursday-october-20-2022.html#cb27-6" aria-hidden="true" tabindex="-1"></a>BFU.ppp <span class="ot">&lt;-</span> BFU.ppp[W]</span>
<span id="cb27-7"><a href="thursday-october-20-2022.html#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="thursday-october-20-2022.html#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="fu">unitname</span>(BFU.ppp) <span class="ot">&lt;-</span> <span class="st">&quot;meters&quot;</span></span>
<span id="cb27-9"><a href="thursday-october-20-2022.html#cb27-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-10"><a href="thursday-october-20-2022.html#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(BFU.ppp)</span></code></pre></div>
<pre><code>## Planar point pattern:  322 points
## Average intensity 2.096214e-07 points per square meters
## 
## Coordinates are given to 2 decimal places
## i.e. rounded to the nearest multiple of 0.01 meters
## 
## Window: polygonal boundary
## single connected closed polygon with 17 vertices
## enclosing rectangle: [547588.2, 587682.5] x [681954.6, 731650.3] meters
##                      (40090 x 49700 meters)
## Window area = 1536100000 square meters
## Unit of length: 1 meters
## Fraction of frame area: 0.771</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="thursday-october-20-2022.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(BFU.ppp)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>Now the average intensity is 21 wildfires per 10 sq. km.</p>
<p>Apply Ripley’s <span class="math inline">\(K\)</span> function and graph the results.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="thursday-october-20-2022.html#cb30-1" aria-hidden="true" tabindex="-1"></a>K.df <span class="ot">&lt;-</span> BFU.ppp <span class="sc">|&gt;</span></span>
<span id="cb30-2"><a href="thursday-october-20-2022.html#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Kest</span>() <span class="sc">|&gt;</span></span>
<span id="cb30-3"><a href="thursday-october-20-2022.html#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span>
<span id="cb30-4"><a href="thursday-october-20-2022.html#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="thursday-october-20-2022.html#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(K.df, <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> iso <span class="sc">*</span> <span class="fu">intensity</span>(BFU.ppp))) <span class="sc">+</span></span>
<span id="cb30-6"><a href="thursday-october-20-2022.html#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb30-7"><a href="thursday-october-20-2022.html#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo <span class="sc">*</span> <span class="fu">intensity</span>(BFU.ppp)), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb30-8"><a href="thursday-october-20-2022.html#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (m)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r), Expected number of additional wildfires</span><span class="sc">\n</span><span class="st"> within a distance r of any wildfire&quot;</span>) <span class="sc">+</span></span>
<span id="cb30-9"><a href="thursday-october-20-2022.html#cb30-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>We see a difference indicating a cluster of event locations, but is the difference significant against a null hypothesis of a homogeneous Poisson?</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="thursday-october-20-2022.html#cb31-1" aria-hidden="true" tabindex="-1"></a>Kenv.df <span class="ot">&lt;-</span> <span class="fu">envelope</span>(BFU.ppp, </span>
<span id="cb31-2"><a href="thursday-october-20-2022.html#cb31-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">fun =</span> Kest, </span>
<span id="cb31-3"><a href="thursday-october-20-2022.html#cb31-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">nsim =</span> <span class="dv">39</span>, </span>
<span id="cb31-4"><a href="thursday-october-20-2022.html#cb31-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">rank =</span> <span class="dv">1</span>, </span>
<span id="cb31-5"><a href="thursday-october-20-2022.html#cb31-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">global =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb31-6"><a href="thursday-october-20-2022.html#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>## Generating 39 simulations of CSR  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,  39.
## 
## Done.</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="thursday-october-20-2022.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Kenv.df, <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> obs)) <span class="sc">+</span></span>
<span id="cb33-2"><a href="thursday-october-20-2022.html#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lo, <span class="at">ymax =</span> hi), <span class="at">fill =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb33-3"><a href="thursday-october-20-2022.html#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb33-4"><a href="thursday-october-20-2022.html#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb33-5"><a href="thursday-october-20-2022.html#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (m)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb33-6"><a href="thursday-october-20-2022.html#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>Yes it is.</p>
</div>
<div id="modeling-point-pattern-data" class="section level2 unnumbered hasAnchor">
<h2>Modeling point pattern data<a href="thursday-october-20-2022.html#modeling-point-pattern-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Models are helpful for trying to understanding the processes leading to the event locations when event interaction is suspected. Event interaction means that an event at one location changes the probability of an event nearby.</p>
<p>Cluster models can be derived by starting with a Poisson model. For example, you begin with a homogeneous Poisson model <span class="math inline">\(Y\)</span> describing a set of events. A model is homogeneous Poisson when the event locations generated by the model are CSR.</p>
<p>Then consider each individual event <span class="math inline">\(y_i\)</span> in <span class="math inline">\(Y\)</span> to be a ‘parent’ that produces a set of ‘offspring’ events (<span class="math inline">\(x_i\)</span>) according to some mechanism. The resulting set of offspring forms clustered point pattern data <span class="math inline">\(X\)</span>. Said another way, the model is homogeneous Poisson at an unobserved level <span class="math inline">\(Y\)</span> (latent level) but clustered at the level of the observations (<span class="math inline">\(X\)</span>).</p>
<p>One example of this parent-child process is the Matern cluster model. Parent events come from a homogeneous Poisson process with intensity <span class="math inline">\(\kappa\)</span> and then each parent has a Poisson (<span class="math inline">\(\mu\)</span>) number of offspring that are iid within a radius <span class="math inline">\(r\)</span> centered on the parent.</p>
<p>For instance here you use the <code>rMatClust()</code> function from the {spatstat} package to produce a clustered <code>ppp</code> object. We use a disc radius of .1 units and an offspring rate equal to 5 (<code>mu = 5</code>).</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="thursday-october-20-2022.html#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rMatClust</span>(<span class="at">kappa =</span> <span class="dv">10</span>, </span>
<span id="cb34-2"><a href="thursday-october-20-2022.html#cb34-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">r =</span> .<span class="dv">1</span>, </span>
<span id="cb34-3"><a href="thursday-october-20-2022.html#cb34-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">mu =</span> <span class="dv">5</span>) <span class="sc">|&gt;</span></span>
<span id="cb34-4"><a href="thursday-october-20-2022.html#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="at">main =</span> <span class="st">&quot;&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>The result is a set of event locations and the process that produced them is described as <em>doubly Poisson</em>. You can vary <span class="math inline">\(\kappa\)</span>, <span class="math inline">\(r\)</span>, and <span class="math inline">\(\mu\)</span> to generate more or fewer events.</p>
<p>Other clustered Poisson models include:
- Thomas model: each cluster consists of a Poisson number of random events with each event having an isotropic Gaussian displacement from its parent.<br />
- Gauss-Poisson model: each cluster is either a single event or a pair of events.<br />
- Neyman-Scott model: the cluster mechanism is arbitrary.</p>
<p>A Cox model is a homogeneous Poisson model with a random intensity function. Let <span class="math inline">\(\Lambda(s)\)</span> be a function with non-negative values defined at all locations <span class="math inline">\(s\)</span> inside the domain. Then, conditional on <span class="math inline">\(\Lambda\)</span> let <span class="math inline">\(X\)</span> be a Poisson model with an intensity function <span class="math inline">\(\Lambda\)</span>. Then <span class="math inline">\(X\)</span> will be a sample from a Cox model.</p>
<p>An example of a Cox model is the mixed Poisson process in which a random variable <span class="math inline">\(\Lambda\)</span> is generated and then, conditional on <span class="math inline">\(\Lambda\)</span>, a homogeneous Poisson process with intensity <span class="math inline">\(\Lambda\)</span> is generated.</p>
<p>Following are two samples from a Cox point process.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="thursday-october-20-2022.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">3042</span>)</span>
<span id="cb35-2"><a href="thursday-october-20-2022.html#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb35-3"><a href="thursday-october-20-2022.html#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>){</span>
<span id="cb35-4"><a href="thursday-october-20-2022.html#cb35-4" aria-hidden="true" tabindex="-1"></a>  lambda <span class="ot">&lt;-</span> <span class="fu">rexp</span>(<span class="at">n =</span> <span class="dv">1</span>, <span class="at">rate =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">100</span>)</span>
<span id="cb35-5"><a href="thursday-october-20-2022.html#cb35-5" aria-hidden="true" tabindex="-1"></a>  X <span class="ot">&lt;-</span> <span class="fu">rpoispp</span>(lambda)</span>
<span id="cb35-6"><a href="thursday-october-20-2022.html#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(X)</span>
<span id="cb35-7"><a href="thursday-october-20-2022.html#cb35-7" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="thursday-october-20-2022.html#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div>
<p>The statistical moments of Cox models are defined in terms of the moments of <span class="math inline">\(\Lambda\)</span>. For instance, the intensity function of <span class="math inline">\(X\)</span> is <span class="math inline">\(\lambda(s)\)</span> = E[<span class="math inline">\(\Lambda(s)\)</span>], where E[] is the expected value.</p>
<p>Cox models are convenient for describing clustered point pattern data. A Cox model is over-dispersed relative to a Poisson model (i.e. the variance of the number of events falling in any region of size A, is greater than the mean number of events in those regions). The Matern cluster model and the Thomas models are Cox models. Another common type of a Cox model is the log-Gaussian Cox processes (LGCP) model in which logarithm of <span class="math inline">\(\Lambda(s)\)</span> is a Gaussian random function.</p>
<p>If you have a way of generating samples from a random function <span class="math inline">\(\Lambda\)</span> of interest, then you can use the <code>rpoispp()</code> function to generate the Cox process. The intensity argument <code>lambda</code> of <code>rpoispp()</code> can be a function of x or y or a pixel image.</p>
<p>Another way to generate clustered point pattern data is by ‘thinning’. Thinning refers to deleting some of the events. With ‘independent thinning’ the fate of each event is independent of the fate of the other events. When independent thinning is applied to a homogeneous Poisson point pattern, the resulting point pattern consisting of the retained events is also Poisson.
To simulate a inhibition process you can use a ‘thinning’ mechanism.</p>
<p>An example of this is Matern’s Model I model. Here a homogeneous Poisson model first generates a point pattern <span class="math inline">\(Y\)</span>, then any event in <span class="math inline">\(Y\)</span> that lies closer than a distance <span class="math inline">\(r\)</span> from another event is deleted. This results in point pattern data whereby close neighbor events do not exist.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="thursday-october-20-2022.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">rMaternI</span>(<span class="at">kappa =</span> <span class="dv">70</span>, </span>
<span id="cb37-2"><a href="thursday-october-20-2022.html#cb37-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">r =</span> .<span class="dv">05</span>), <span class="at">main =</span> <span class="st">&quot;&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="thursday-october-20-2022.html#cb38-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">rMaternI</span>(<span class="at">kappa =</span> <span class="dv">70</span>, </span>
<span id="cb38-2"><a href="thursday-october-20-2022.html#cb38-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">r =</span> .<span class="dv">05</span>)</span>
<span id="cb38-3"><a href="thursday-october-20-2022.html#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="thursday-october-20-2022.html#cb38-4" aria-hidden="true" tabindex="-1"></a>X <span class="sc">|&gt;</span></span>
<span id="cb38-5"><a href="thursday-october-20-2022.html#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Kest</span>() <span class="sc">|&gt;</span></span>
<span id="cb38-6"><a href="thursday-october-20-2022.html#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-17-2.png" width="672" /></p>
<p>Changing <span class="math inline">\(\kappa\)</span> and <span class="math inline">\(r\)</span> will change the event intensity.</p>
<p>The various spatial models for event locations can be described with math. For instance, expanding on the earlier notation you write that a homogeneous Poisson model with intensity <span class="math inline">\(\lambda &gt; 0\)</span> has intensity <span class="math display">\[\lambda(s, x) = \lambda\]</span> where <span class="math inline">\(s\)</span> is any location in the window W and <span class="math inline">\(x\)</span> is the set of events.</p>
<p>Then the inhomogeneous Poisson model has conditional intensity <span class="math display">\[\lambda(s, x) = \lambda(s)\]</span>. The intensity <span class="math inline">\(\lambda(s)\)</span> depends on a spatial trend or on an explanatory variable.</p>
<p>There is also a class of ‘Markov’ point process models that allow for clustering (or inhibition) due to event interaction. Markov refers to the fact that the interaction is limited to nearest neighbors. Said another way, a Markov point process generalizes a Poisson process in the case where events are pairwise dependent.</p>
<p>A Markov process with parameters <span class="math inline">\(\beta &gt; 0\)</span> and <span class="math inline">\(0 &lt; \gamma &lt; \infty\)</span> with interaction radius <span class="math inline">\(r &gt; 0\)</span> has conditional intensity <span class="math inline">\(\lambda(s, x)\)</span> given by</p>
<p><span class="math display">\[
\lambda(s, x) = \beta \gamma^{t(s, x)}
\]</span></p>
<p>where <span class="math inline">\(t(s, x)\)</span> is the number of events that lie within a distance <span class="math inline">\(r\)</span> of location <span class="math inline">\(s\)</span>.</p>
<p>Three cases:
- If <span class="math inline">\(\gamma = 1\)</span>, then <span class="math inline">\(\lambda(s, x) = \beta\)</span> No interaction between events, <span class="math inline">\(\beta\)</span> can vary with <span class="math inline">\(s\)</span>.
- If <span class="math inline">\(\gamma &lt; 1\)</span>, then <span class="math inline">\(\lambda(s, x) &lt; \beta\)</span>. Events inhibit nearby events.
- If <span class="math inline">\(\gamma &gt; 1\)</span>, then <span class="math inline">\(\lambda(s, x) &gt; \beta\)</span>. Events encourage nearby events.</p>
<p>Note the distinction between the interaction term <span class="math inline">\(\gamma\)</span> and the trend term <span class="math inline">\(\beta\)</span>. Note: A similar distinction exists between autocorrelation <span class="math inline">\(\rho\)</span> and trend <span class="math inline">\(\beta\)</span> in spatial regression models.</p>
<p>More generally, you write the logarithm of the conditional intensity <span class="math inline">\(\log[\lambda(s, x)]\)</span> as linear expression with two components.</p>
<p><span class="math display">\[
\log\big[\lambda(s, x)\big] = \theta_1 B(s) + \theta_2 C(s, x)
\]</span></p>
<p>where the <span class="math inline">\(\theta\)</span>’s are model parameters that need to be estimated.</p>
<p>The term <span class="math inline">\(B(s)\)</span> depends only on location so it represents trend and explanatory variable (covariate) effects. It is the ‘systematic component’ of the model. The term <span class="math inline">\(C(s, x)\)</span> represents stochastic interactions (dependency) between events.</p>
</div>
<div id="fitting-and-interpreting-an-inhibition-model" class="section level2 unnumbered hasAnchor">
<h2>Fitting and interpreting an inhibition model<a href="thursday-october-20-2022.html#fitting-and-interpreting-an-inhibition-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The {spatstat} package contains functions for fitting statistical models to point pattern data. Models can include trend (to account for non-stationarity), explanatory variables (covariates), <em>and</em> event interactions of any order (in other words, interactions are not restricted to pairwise). Models are fit with the method of maximum likelihood and the method of minimum contrasts.</p>
<p>The method of maximum likelihood estimates the probability of the empirical <span class="math inline">\(K\)</span> curve given the theoretical curve for various parameter values. Parameter values are chosen so as to maximize the likelihood of the empirical curve.</p>
<p>The method of minimum contrasts derives a cost function as the difference between the theoretical and empirical <span class="math inline">\(K\)</span> curves. Parameter values for the theoretical curve are those that minimize this cost function.</p>
<p>The <code>ppm()</code> function is used to fit a spatial point pattern model. The syntax has the form <code>ppm(X, formula, interaction, ...)</code> where <code>X</code> is the point pattern object of class <code>ppp</code>, <code>formula</code> describes the systematic (trend and covariate) part of the model, and <code>interaction</code> describes the stochastic dependence between events (e.g., Matern process).</p>
<p>Recall a plot of the Swedish pine saplings. There was no indication of a trend (no systematic variation in the intensity of saplings).</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="thursday-october-20-2022.html#cb39-1" aria-hidden="true" tabindex="-1"></a>SP <span class="ot">&lt;-</span> swedishpines</span>
<span id="cb39-2"><a href="thursday-october-20-2022.html#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(SP)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="thursday-october-20-2022.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">intensity</span>(SP)</span></code></pre></div>
<pre><code>## [1] 0.007395833</code></pre>
<p>There is no obvious spatial trend in the distribution of saplings and the average intensity is .0074 saplings per unit area.</p>
<p>A plot of the Ripley’s <span class="math inline">\(K\)</span> function indicated regularity relative to CSR.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="thursday-october-20-2022.html#cb42-1" aria-hidden="true" tabindex="-1"></a>SP <span class="sc">|&gt;</span></span>
<span id="cb42-2"><a href="thursday-october-20-2022.html#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Kest</span>(<span class="at">correction =</span> <span class="st">&quot;iso&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb42-3"><a href="thursday-october-20-2022.html#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>The red dashed line is the <span class="math inline">\(K\)</span> curve under CSR. The black line is the empirical curve. At lag distances of between 5 and 15 units the empirical curve is below the CSR curve indicating there are fewer events within other events at those scales than would be expected by chance.</p>
<p>This suggests a physical process whereby saplings tend to compete for sunlight, nutrients, etc. A process of between-event inhibition. If you suspect that the spatial distribution of event locations is influenced by inhibition you can model the process statistically.</p>
<p>A simple inhibition model is a Strauss process when the inhibition is constant with a fixed radius (r) around each event. The amount of inhibition ranges between zero (100% chance of a nearby event) to complete (0% chance of a nearby event). In the case of no inhibition the process is equivalent to a homogeneous Poisson process.</p>
<p>If you assume the inhibition process is constant across the domain with a fixed interaction radius (r), then you can fit a Strauss model to the data. You use the <code>ppm()</code> function from the {spatstat} package and include the point pattern data as the first argument. You set the trend term to a constant (implying a stationary process) with the argument <code>trend ~ 1</code> and the interaction radius to 10 units with the argument <code>interaction = Strauss(r = 10)</code>. Finally you use a border correction out to a distance of 10 units from the window with the <code>rbord =</code> argument.</p>
<p>Save the output in the object called <code>model.in</code> (inhibition model).</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="thursday-october-20-2022.html#cb43-1" aria-hidden="true" tabindex="-1"></a>model.in <span class="ot">&lt;-</span> <span class="fu">ppm</span>(SP, </span>
<span id="cb43-2"><a href="thursday-october-20-2022.html#cb43-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">trend =</span> <span class="sc">~</span> <span class="dv">1</span>, </span>
<span id="cb43-3"><a href="thursday-october-20-2022.html#cb43-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">interaction =</span> <span class="fu">Strauss</span>(<span class="at">r =</span> <span class="dv">10</span>), </span>
<span id="cb43-4"><a href="thursday-october-20-2022.html#cb43-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">rbord =</span> <span class="dv">10</span>)</span></code></pre></div>
<p>The value for <code>r</code> in the <code>Strauss()</code> function is based on our visual inspection of the plot of <code>Kest()</code>. A value is chosen that represents the distance at which there is the largest departure from a CSR model.</p>
<p>You inspect the model parameters by typing the object name.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="thursday-october-20-2022.html#cb44-1" aria-hidden="true" tabindex="-1"></a>model.in</span></code></pre></div>
<pre><code>## Stationary Strauss process
## 
## First order term:  beta = 0.07567442
## 
## Interaction distance:    10
## Fitted interaction parameter gamma:  0.2752048
## 
## Relevant coefficients:
## Interaction 
##    -1.29024 
## 
## For standard errors, type coef(summary(x))</code></pre>
<p>The first-order term (<code>beta</code>) has a value of .0757. This is the intensity of the ‘proposal’ events. The value of beta exceeds the average intensity by a factor of ten.</p>
<p>Recall the intensity of the events is obtained as</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="thursday-october-20-2022.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">intensity</span>(SP)</span></code></pre></div>
<pre><code>## [1] 0.007395833</code></pre>
<p>The interaction parameter (<code>gamma</code>) is .275. It is less than one, indicating an inhibition process. The logarithm of gamma, called the interaction coefficient (<code>Interaction</code>), is -1.29. Interaction coefficients less than zero imply inhibition.</p>
<p>A table with the coefficients including the standard errors and uncertainty ranges is obtained with the <code>coef()</code> method.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="thursday-october-20-2022.html#cb48-1" aria-hidden="true" tabindex="-1"></a>model.in <span class="sc">|&gt;</span></span>
<span id="cb48-2"><a href="thursday-october-20-2022.html#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>() <span class="sc">|&gt;</span></span>
<span id="cb48-3"><a href="thursday-october-20-2022.html#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coef</span>()</span></code></pre></div>
<pre><code>##              Estimate      S.E.   CI95.lo    CI95.hi Ztest      Zval
## (Intercept) -2.581315 0.4524077 -3.468018 -1.6946123   *** -5.705728
## Interaction -1.290240 0.2375515 -1.755832 -0.8246475   *** -5.431411</code></pre>
<p>The output includes the <code>Interaction</code> coefficient along with it’s standard error (<code>S.E.</code>) and the associated 95% uncertainty interval. The ratio of the <code>Interaction</code> coefficient to its standard error is the <code>Zval</code>. A large z-value (in absolute magnitude) translates to a low <span class="math inline">\(p\)</span>-value and a rejection of the null hypothesis of no interaction between events.</p>
<p>Output also is the estimated value for the <code>(Intercept)</code> term. It is the logarithm of the beta value, so exp(-2.58) = .0757 is the intensity of the proposal events.</p>
<p>You interpret the model output as follows. The process producing the spatial pattern of pine saplings is such that you should see .0757 saplings per unit area [unobserved (latent) rate].</p>
<p>But because of event inhibition, where saplings nearby other saplings fail to grow, the number of saplings is reduced to .0074 per unit area. Thus the spatial pattern is suggestive of sibling-sibling interaction. Adults have many offspring, but only some survive due to limited resources.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tuesday-october-18-2022.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="tuesday-october-25-2022.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
