<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Thursday September 8, 2022 | GIS5122: Applied Spatial Statistics</title>
  <meta name="description" content="Thursday September 8, 2022 | GIS5122: Applied Spatial Statistics" />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="Thursday September 8, 2022 | GIS5122: Applied Spatial Statistics" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="jelsner/ASS-2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Thursday September 8, 2022 | GIS5122: Applied Spatial Statistics" />
  
  
  

<meta name="author" content="James B. Elsner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tuesday-september-6-2022.html"/>
<link rel="next" href="tuesday-september-13-2022.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.1.1/leaflet.js"></script>
<script src="libs/leaflet-providers-1.9.0/leaflet-providers_1.9.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.1.1/leaflet-providers-plugin.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied Spatial Statistics</a></li>

<li class="divider"></li>
<li><a href="index.html#section"></a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i>Syllabus</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#gis5122-applied-spatial-statistics"><i class="fa fa-check"></i>GIS5122: Applied Spatial Statistics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#contact-information"><i class="fa fa-check"></i>Contact information</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#course-description"><i class="fa fa-check"></i>Course description</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#expected-learning-outcomes"><i class="fa fa-check"></i>Expected learning outcomes</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#materials"><i class="fa fa-check"></i>Materials</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#class-meetings"><i class="fa fa-check"></i>Class meetings</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#grades"><i class="fa fa-check"></i>Grades</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#ethics"><i class="fa fa-check"></i>Ethics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#outline-of-topics"><i class="fa fa-check"></i>Outline of topics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#schedule-subject-to-change-with-notice"><i class="fa fa-check"></i>Schedule (subject to change with notice)</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#reference-materials"><i class="fa fa-check"></i>Reference materials</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#reproducible-research"><i class="fa fa-check"></i>Reproducible research</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html"><i class="fa fa-check"></i>Tuesday, August 23, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#install-r-and-rstudio-on-your-computer"><i class="fa fa-check"></i>Install R and RStudio on your computer</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#download-course-materials"><i class="fa fa-check"></i>Download course materials</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#read-the-syllabus"><i class="fa fa-check"></i>Read the syllabus</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#about-rstudio"><i class="fa fa-check"></i>About RStudio</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#lab-assignments"><i class="fa fa-check"></i>Lab assignments</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#getting-started-with-r"><i class="fa fa-check"></i>Getting started with R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#are-you-completely-new-to-r"><i class="fa fa-check"></i>Are you completely new to R?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html"><i class="fa fa-check"></i>Thursday, August 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#expectations"><i class="fa fa-check"></i>Expectations</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-science-workflow-with-r-markdown"><i class="fa fa-check"></i>Data science workflow with R markdown</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#an-introduction-to-using-r"><i class="fa fa-check"></i>An introduction to using R</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-frames"><i class="fa fa-check"></i>Data frames</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html"><i class="fa fa-check"></i>Tuesday August 30, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#working-with-data-frames"><i class="fa fa-check"></i>Working with data frames</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html"><i class="fa fa-check"></i>Thursday September 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#making-graphs"><i class="fa fa-check"></i>Making graphs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html"><i class="fa fa-check"></i>Tuesday September 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#working-with-spatial-data"><i class="fa fa-check"></i>Working with spatial data</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#geo-computation-on-simple-features"><i class="fa fa-check"></i>Geo-computation on simple features</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html"><i class="fa fa-check"></i>Thursday September 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#spatial-data-subsets-and-joins"><i class="fa fa-check"></i>Spatial data subsets and joins</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#interpolation-using-areal-weights"><i class="fa fa-check"></i>Interpolation using areal weights</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html"><i class="fa fa-check"></i>Tuesday September 13, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#s4-spatial-data-objects"><i class="fa fa-check"></i>S4 spatial data objects</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#working-with-raster-data"><i class="fa fa-check"></i>Working with raster data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html"><i class="fa fa-check"></i>Thursday September 15, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#working-with-space-time-data"><i class="fa fa-check"></i>Working with space-time data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#mapping-using-functions-from-the-ggplot2-package"><i class="fa fa-check"></i>Mapping using functions from the {ggplot2} package</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#mapping-using-functions-from-the-tmap-package"><i class="fa fa-check"></i>Mapping using functions from the {tmap} package</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#creating-an-interactive-map"><i class="fa fa-check"></i>Creating an interactive map</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#adding-an-inset-map"><i class="fa fa-check"></i>Adding an inset map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html"><i class="fa fa-check"></i>Tuesday September 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#defining-spatial-neighborhoods-and-spatial-weights"><i class="fa fa-check"></i>Defining spatial neighborhoods and spatial weights</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#computing-autocorrelation"><i class="fa fa-check"></i>Computing autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#spatial-lag-and-its-relation-to-autocorrelation"><i class="fa fa-check"></i>Spatial lag and its relation to autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html"><i class="fa fa-check"></i>Thursday September 22, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#other-neighbor-definitions"><i class="fa fa-check"></i>Other neighbor definitions</a></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#assessing-the-statistical-significance-of-autocorrelation"><i class="fa fa-check"></i>Assessing the statistical significance of autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#bivariate-spatial-autocorrelation"><i class="fa fa-check"></i>Bivariate spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#local-indicators-of-spatial-autocorrelation"><i class="fa fa-check"></i>Local indicators of spatial autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-27-2022.html"><a href="tuesday-september-27-2022.html"><i class="fa fa-check"></i>Tuesday September 27, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-27-2022.html"><a href="tuesday-september-27-2022.html#constraining-group-membership-based-on-spatial-autocorrelation"><i class="fa fa-check"></i>Constraining group membership based on spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-27-2022.html"><a href="tuesday-september-27-2022.html#estimating-spatial-autocorrelation-in-model-residuals"><i class="fa fa-check"></i>Estimating spatial autocorrelation in model residuals</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-27-2022.html"><a href="tuesday-september-27-2022.html#choosing-a-spatial-regression-model"><i class="fa fa-check"></i>Choosing a spatial regression model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html"><i class="fa fa-check"></i>Thursday September 29, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#fitting-and-interpreting-a-spatially-lagged-y-model"><i class="fa fa-check"></i>Fitting and interpreting a spatially-lagged Y model</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#fitting-and-interpreting-a-spatially-lagged-x-model"><i class="fa fa-check"></i>Fitting and interpreting a spatially-lagged X model</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#fitting-and-interpreting-spatial-durbin-models"><i class="fa fa-check"></i>Fitting and interpreting spatial Durbin models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html"><i class="fa fa-check"></i>Tuesday October 4, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#fitting-and-interpreting-geographic-regressions"><i class="fa fa-check"></i>Fitting and interpreting geographic regressions</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#mapping-incidence-and-risk-with-spatial-regression-models"><i class="fa fa-check"></i>Mapping incidence and risk with spatial regression models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html"><i class="fa fa-check"></i>Thursday October 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#spatial-data-as-point-patterns"><i class="fa fa-check"></i>Spatial data as point patterns</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#working-with-point-pattern-objects-using-functions-from-the-spatstat-package"><i class="fa fa-check"></i>Working with point pattern objects using functions from the {spatstat} package</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#quantifying-event-intensity"><i class="fa fa-check"></i>Quantifying event intensity</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html"><i class="fa fa-check"></i>Tuesday October 11, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#creating-ppp-and-owin-objects-from-simple-feature-data-frames"><i class="fa fa-check"></i>Creating <code>ppp</code> and <code>owin</code> objects from simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#estimating-spatial-intensity-as-a-function-of-distance"><i class="fa fa-check"></i>Estimating spatial intensity as a function of distance</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#intensity-trend-as-a-possible-confounding-factor"><i class="fa fa-check"></i>Intensity trend as a possible confounding factor</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html"><i class="fa fa-check"></i>Thursday October 13, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html#estimating-the-relative-risk-of-events"><i class="fa fa-check"></i>Estimating the relative risk of events</a></li>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html#estimating-second-moment-properties-of-spatial-events"><i class="fa fa-check"></i>Estimating second-moment properties of spatial events</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html"><i class="fa fa-check"></i>Tuesday October 18, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#examples-of-spatially-clustered-events"><i class="fa fa-check"></i>Examples of spatially clustered events</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#determining-the-statistical-significance-of-event-clustering"><i class="fa fa-check"></i>Determining the statistical significance of event clustering</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#estimating-event-clustering-in-multi-type-event-locations"><i class="fa fa-check"></i>Estimating event clustering in multi-type event locations</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#more-about-the-ripley-k-function"><i class="fa fa-check"></i>More about the Ripley K function</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GIS5122: Applied Spatial Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="thursday-september-8-2022" class="section level1 unnumbered hasAnchor">
<h1>Thursday September 8, 2022<a href="thursday-september-8-2022.html#thursday-september-8-2022" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>“Hell isn’t other people’s code. Hell is your own code from 3 years ago.”</strong> – Jeff Atwood</p>
<p>Today</p>
<ul>
<li>Spatial data subsets and joins</li>
<li>Interpolating variables using areal weights</li>
</ul>
<div id="spatial-data-subsets-and-joins" class="section level2 unnumbered hasAnchor">
<h2>Spatial data subsets and joins<a href="thursday-september-8-2022.html#spatial-data-subsets-and-joins" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Variables (stored as columns) in spatial data structures are referred to as ‘attributes’.</p>
<p>With simple feature data frames you can create data subsets using <code>[</code>, <code>subset()</code> and <code>$</code> from the {base} R packages and <code>select()</code> and <code>filter()</code> from the {dplyr} package.</p>
<p>The <code>[</code> operator subsets rows and columns. Indexes specify the elements you wish to extract from an object, e.g. object[i, j], with i and j typically being numbers representing rows and columns. Leaving i or j empty returns all rows or columns, so <code>world[1:5, ]</code> returns the first five rows and all columns of the simple feature data frame <code>world</code> (from the {spData} package). Examples</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="thursday-september-8-2022.html#cb1-1" aria-hidden="true" tabindex="-1"></a>world <span class="ot">&lt;-</span> spData<span class="sc">::</span>world</span>
<span id="cb1-2"><a href="thursday-september-8-2022.html#cb1-2" aria-hidden="true" tabindex="-1"></a>world[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">9</span>), ] <span class="co"># subset rows by row position</span></span></code></pre></div>
<pre><code>##   iso_a2     name_long     continent region_un          subregion
## 1     FJ          Fiji       Oceania   Oceania          Melanesia
## 5     US United States North America  Americas   Northern America
## 9     ID     Indonesia          Asia      Asia South-Eastern Asia
##                type   area_km2       pop  lifeExp gdpPercap
## 1 Sovereign country   19289.97    885806 69.96000  8222.254
## 5           Country 9510743.74 318622525 78.84146 51921.985
## 9 Sovereign country 1819251.33 255131116 68.85600 10003.089
##                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            geom
## 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       -180.00000, -179.91737, -179.79332, -180.00000, -180.00000, -16.55522, -16.50178, -16.02088, -16.06713, -16.55522, 178.12557, 177.67087, 177.28504, 177.38146, 177.93266, 178.55271, 178.71806, 178.37360, 178.12557, -17.50481, -17.38114, -17.72465, -18.16432, -18.28799, -18.15059, -17.62846, -17.33992, -17.50481, 179.99999, 179.99999, 179.41351, 179.09661, 178.59684, 178.72506, 179.36414, 179.99999, -16.55522, -16.06714, -16.37905, -16.43398, -16.63915, -17.01204, -16.80135, -16.55522
## 5 -171.73166, -171.79111, -171.55306, -170.67139, -170.29056, -169.52944, -168.77194, -168.68944, -169.68251, -170.49111, -171.11443, -171.73166, 63.78252, 63.40585, 63.31779, 63.37582, 63.19444, 62.97693, 63.18860, 63.29751, 63.43112, 63.69498, 63.59219, 63.78252, -166.46779, -167.45528, -166.84834, -166.19277, -165.57916, -165.67443, -166.46779, 60.38417, 60.21307, 59.94141, 59.75444, 59.90999, 60.29361, 60.38417, -159.36569, -159.59620, -159.74877, -159.80051, -159.46372, -159.34512, -159.36569, 22.21494, 22.23618, 22.13820, 22.06533, 21.88299, 21.98200, 22.21494, -158.02520, -158.29265, -158.25380, -158.12667, -157.77860, -157.70703, -157.65283, -157.94161, -158.02520, 21.71696, 21.57912, 21.53919, 21.31244, 21.27729, 21.26442, 21.32217, 21.65272, 21.71696, -156.75824, -157.25027, -157.32521, -156.78933, -156.75824, 21.17684, 21.21958, 21.09777, 21.06873, 21.17684, -155.99566, -156.25711, -156.61258, -156.71055, -156.70167, -156.58673, -156.41445, -156.07926, -155.99566, 20.76404, 20.91745, 21.01249, 20.92676, 20.86430, 20.78300, 20.57241, 20.64397, 20.76404, -155.40214, -155.78505, -155.86108, -155.91907, -155.85008, -156.02368, -156.07347, -155.90806, -155.93665, -155.68817, -155.54211, -155.22217, -154.83147, -154.80741, -155.06226, -155.22452, -155.40214, 20.07975, 20.24870, 20.26721, 20.17395, 19.97729, 19.81422, 19.70294, 19.33888, 19.05939, 18.91619, 19.08348, 19.23972, 19.45328, 19.50871, 19.85910, 19.99302, 20.07975, -153.22873, -153.76278, -154.67099, -154.51640, -154.00509, -153.00631, -152.14115, -152.56479, -153.22873, 57.96897, 57.81657, 57.46120, 56.99275, 56.73468, 57.11584, 57.59106, 57.90143, 57.96897, -140.98599, -140.98599, -142.07251, -143.58945, -144.92001, -145.68999, -147.61336, -149.72000, -150.73999, -152.27000, -152.21001, -153.90001, -154.34417, -155.06779, -156.58082, -158.11972, -159.03918, -160.93480, -161.90890, -162.93057, -163.16861, -164.43081, -166.20471, -166.76444, -165.39029, -164.43099, -163.71972, -162.48971, -161.67777, -163.78860, -163.65251, -164.47471, -166.70527, -168.11056, -166.84500, -166.42529, -164.96083, -163.54639, -162.75779, -162.45305, -161.39193, -160.77778, -161.51807, -160.95834, -160.77251, -161.53445, -162.26056, -163.06722, -163.75333, -164.56251, -164.91918, -165.73445, -166.12138, -165.35083, -165.34639, -164.66222, -163.81834, -162.51806, -161.87417, -162.05499, -161.96889, -161.35500, -160.35527, -159.98129, -159.71167, -159.05861, -158.51722, -158.19473, -157.04167, -157.55027, -157.72277, -158.46110, -158.68444, -160.07056, -160.56360, -161.80417, -162.87000, -163.84834, -164.94223, -164.78557, -163.06945, -162.23777, -161.22305, -160.28972, -159.60333, -158.43332, -158.11722, -156.55610, -156.30833, -155.30749, -154.23249, -153.28751, -154.01917, -152.57833, -151.89584, -150.62111, -150.34694, -151.40972, -151.85943, -151.71639, -150.60824, -149.72786, -148.57082, -148.01807, -148.22431, -147.11437, -145.92556, -143.95888, -142.57444, -140.82527, -139.86779, -137.80001, -136.62806, -135.03821, -134.07806, -133.53918, -132.25001, -131.96721, -131.08582, -130.53611, -130.53611, -130.53611, -129.98000, -130.00778, -131.70781, -132.73042, -133.35556, -134.27111, -134.94500, -135.47583, -136.47972, -137.45250, -138.34089, -139.03900, -140.01300, -140.99778, -140.99250, -140.98600, -140.98599, 69.71200, 69.71200, 69.85194, 70.15251, 69.98999, 70.12001, 70.21403, 70.53001, 70.43002, 70.60001, 70.82999, 70.88999, 70.69641, 71.14778, 71.35776, 70.82472, 70.89164, 70.44769, 70.33333, 69.85806, 69.37111, 68.91554, 68.88303, 68.35888, 68.04277, 67.61634, 67.11639, 66.73557, 66.11612, 66.07721, 66.57666, 66.57666, 66.08832, 65.67000, 65.08890, 64.68667, 64.44695, 64.55916, 64.33861, 64.55944, 64.77724, 64.78860, 64.40279, 64.22280, 63.76611, 63.45582, 63.54194, 63.05946, 63.21945, 63.14638, 62.63308, 62.07500, 61.50002, 61.07390, 60.50750, 60.26748, 59.79806, 59.98972, 59.63362, 59.26693, 58.67166, 58.67084, 59.07112, 58.57255, 58.93139, 58.42419, 58.78778, 58.61580, 58.91888, 58.32833, 57.57000, 57.21692, 57.01668, 56.41806, 56.00805, 55.89499, 55.34804, 55.03943, 54.57222, 54.40417, 54.68974, 55.02419, 55.36473, 55.64358, 55.56669, 55.99415, 56.46361, 56.97998, 57.42277, 57.72779, 58.14637, 58.86473, 59.35028, 60.06166, 60.72720, 61.28442, 61.03359, 60.72580, 59.74498, 59.15582, 59.36821, 59.70566, 59.91417, 59.97833, 60.67299, 60.88466, 60.45861, 59.99918, 60.08445, 59.72752, 59.53776, 58.50000, 58.21221, 58.18771, 58.12307, 57.17889, 56.37000, 55.49778, 55.17891, 54.80275, 54.80275, 54.80278, 55.28500, 55.91583, 56.55212, 57.69289, 58.41028, 58.86111, 59.27056, 59.78778, 59.46389, 58.90500, 59.56211, 60.00000, 60.27682, 60.30639, 66.00003, 69.71200, 69.71200, -122.84000, -122.50000, -122.34000, -122.58736, -123.12000, -124.56610, -124.68721, -124.39567, -124.07963, -123.89893, -124.02053, -124.14214, -124.53284, -124.21370, -124.17886, -124.39807, -123.86517, -123.72720, -122.95319, -122.51201, -122.54747, -121.71457, -120.74433, -120.62286, -120.36778, -119.43884, -119.08100, -118.51989, -118.41060, -117.94400, -117.29594, -117.12776, -115.99135, -114.72139, -114.81500, -113.30498, -111.02361, -109.03500, -108.24194, -108.24000, -106.50759, -106.14290, -105.63159, -105.03737, -104.70575, -104.45697, -103.94000, -103.11000, -102.48000, -101.66240, -100.95760, -100.45584, -100.11000, -99.52000, -99.30000, -99.02000, -98.24000, -97.53000, -97.14000, -97.33000, -97.38000, -97.37000, -97.14000, -96.59404, -95.60026, -94.69000, -93.84842, -93.22637, -92.49906, -91.62678, -90.88022, -90.15463, -89.77928, -89.40823, -89.21767, -89.43000, -89.41373, -89.59383, -89.18049, -88.41782, -87.53036, -86.40000, -85.77310, -85.28784, -85.10882, -84.10000, -83.70959, -82.93000, -82.65000, -82.85526, -82.70515, -82.24000, -81.71000, -81.33000, -81.17213, -80.68000, -80.38103, -80.13156, -80.08801, -80.05654, -80.53000, -80.53558, -80.98000, -81.31371, -81.49042, -81.33629, -80.86498, -80.30132, -79.20357, -79.06067, -78.55435, -78.05496, -77.39763, -76.36318, -75.72749, -75.86804, -75.97180, -76.25874, -76.30162, -76.99000, -76.32933, -76.54272, -76.35000, -76.23287, -75.72205, -76.03127, -75.94023, -75.37747, -75.05673, -75.07183, -75.32000, -75.52805, -75.20002, -74.98041, -74.90604, -74.17838, -73.96244, -74.25671, -73.95232, -73.98200, -73.34500, -71.94500, -72.24126, -73.71000, -72.87643, -72.29500, -71.86000, -71.12039, -70.64000, -69.96503, -69.88497, -70.18500, -70.08000, -70.49500, -70.82500, -70.81489, -70.64548, -70.11617, -69.06000, -68.03252, -66.96466, -67.13741, -67.79134, -67.79046, -68.23444, -68.90500, -69.23722, -69.99997, -70.30500, -70.66000, -71.08482, -71.40500, -71.50506, -73.34783, -74.86700, -75.31821, -76.37500, -76.50000, -76.82003, -77.73789, -78.72028, -79.17167, -79.01000, -78.92000, -78.93936, -80.24745, -81.27775, -82.43928, -82.69009, -83.02981, -83.14200, -83.12000, -82.90000, -82.43000, -82.13764, -82.33776, -82.55092, -83.59285, -83.46955, -83.61613, -83.89077, -84.09185, -84.14212, -84.33670, -84.60490, -84.54375, -84.77924, -84.87608, -85.65236, -86.46199, -87.43979, -88.37811, -89.27292, -89.60000, -90.83000, -91.64000, -92.61000, -93.63087, -94.32914, -94.64000, -94.81758, -95.15609, -95.15907, -97.22872, -100.65000, -104.04826, -107.05000, -110.05000, -113.00000, -116.04818, -117.03121, -120.00000, -122.84000, 49.00000, 48.18000, 47.36000, 47.09600, 48.04000, 48.37971, 48.18443, 47.72017, 46.86475, 45.52341, 44.61589, 43.70838, 42.76599, 41.99964, 41.14202, 40.31320, 39.76699, 38.95166, 38.11371, 37.78339, 37.55176, 36.16153, 35.15686, 34.60855, 34.44711, 34.34848, 34.07800, 34.02778, 33.74091, 33.62124, 33.04622, 32.53534, 32.61239, 32.72083, 32.52528, 32.03914, 31.33472, 31.34194, 31.34222, 31.75485, 31.75452, 31.39995, 31.08383, 30.64402, 30.12173, 29.57196, 29.27000, 28.97000, 29.76000, 29.77930, 29.38071, 28.69612, 28.11000, 27.54000, 26.84000, 26.37000, 26.06000, 25.84000, 25.87000, 26.21000, 26.69000, 27.38000, 27.83000, 28.30748, 28.73863, 29.48000, 29.71363, 29.78375, 29.55230, 29.67700, 29.14854, 29.11743, 29.30714, 29.15961, 29.29108, 29.48864, 29.89419, 30.15999, 30.31598, 30.38490, 30.27433, 30.40000, 30.15261, 29.68612, 29.63615, 30.09000, 29.93656, 29.10000, 28.55000, 27.88624, 27.49504, 26.73000, 25.87000, 25.64000, 25.20126, 25.08000, 25.20616, 25.81678, 26.20576, 26.88000, 28.04000, 28.47213, 29.18000, 30.03552, 30.72999, 31.44049, 32.03330, 32.50936, 33.15839, 33.49395, 33.86133, 33.92547, 34.51201, 34.80854, 35.55074, 36.55125, 36.89726, 36.96640, 37.91794, 38.23999, 38.08326, 38.71762, 39.15000, 38.31921, 37.93705, 37.25660, 37.21689, 38.01551, 38.40412, 38.78203, 38.96000, 39.49850, 39.24845, 39.19640, 38.93954, 39.70926, 40.42763, 40.47351, 40.75075, 40.62800, 40.63000, 40.93000, 41.11948, 40.93110, 41.22065, 41.27000, 41.32000, 41.49445, 41.47500, 41.63717, 41.92283, 42.14500, 41.78000, 41.80500, 42.33500, 42.86530, 43.09024, 43.68405, 43.98000, 44.32520, 44.80970, 45.13753, 45.70281, 47.06636, 47.35486, 47.18500, 47.44778, 46.69307, 45.91500, 45.46000, 45.30524, 45.25500, 45.00820, 45.00738, 45.00048, 44.81645, 44.09631, 44.01846, 43.62878, 43.62906, 43.62509, 43.46634, 43.27000, 42.96500, 42.86361, 42.36620, 42.20903, 41.67511, 41.67511, 41.83280, 41.97568, 42.08000, 42.43000, 42.98000, 43.57109, 44.44000, 45.34752, 45.81689, 45.99469, 46.11693, 46.11693, 46.27542, 46.51223, 46.40877, 46.43960, 46.53868, 46.63710, 46.90008, 47.22022, 47.55334, 47.94000, 48.30292, 48.01981, 48.01000, 48.27000, 48.14000, 48.45000, 48.60926, 48.67074, 48.84000, 49.38905, 49.38425, 49.00000, 49.00070, 49.00000, 48.99986, 49.00000, 49.00000, 49.00000, 49.00000, 49.00000, 49.00000, 49.00000
## 9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             104.3699915, 104.0107886, 103.4376453, 103.8383960, 103.0768404, 102.4982711, 101.6580123, 100.6414335, 99.6939978, 99.1425586, 98.3691691, 97.4848820, 95.9368628, 95.2930262, 95.3808761, 96.4240166, 97.1769422, 97.6995976, 98.6013514, 98.9700110, 99.2637399, 100.1419808, 100.9025029, 101.3991134, 102.1561731, 102.5842607, 103.8682133, 104.7103841, 105.8176551, 105.8574459, 106.1085934, 105.6221114, 104.8878927, 104.5394902, 104.3699915, -1.0848430, -1.0592115, -0.7119459, 0.1045417, 0.5613614, 1.3987005, 2.0836974, 2.0993812, 3.1743285, 3.5903496, 4.2683703, 5.2463209, 5.4395133, 5.4798209, 4.9707822, 3.8688598, 3.3087906, 2.4531839, 1.8235066, 1.0428824, 0.1831416, -0.6503476, -2.0502621, -2.7997771, -3.6141460, -4.2202589, -5.0373150, -5.8732846, -5.8523556, -4.3055250, -3.0617766, -2.4288437, -2.3404253, -1.7823715, -1.0848430, 108.4868461, 108.0720911, 107.2650086, 106.0516459, 105.3654863, 106.2806242, 106.4541020, 108.2777633, 108.6936552, 109.4276673, 110.5861495, 111.5220614, 112.5596725, 113.4647335, 114.5645113, 115.7055270, 114.4789352, 112.9787683, 112.6148112, 110.7595756, 110.5392273, 108.6234786, 108.4868461, -6.4219850, -6.3457622, -5.9549850, -5.8959189, -6.8514161, -6.9249000, -7.3548996, -7.7666574, -7.6416004, -7.7406642, -8.1226047, -8.3021286, -8.3761809, -8.3489474, -8.7518169, -8.3708066, -7.7765276, -7.5942131, -6.9460357, -6.4651865, -6.8773577, -6.7776738, -6.4219850, 117.8820349, 117.0152145, 115.8655172, 115.5190784, 115.1340373, 114.6213554, 113.8058496, 112.8598092, 112.3802519, 111.7975485, 111.1591378, 110.5140609, 109.8302267, 109.6632601, 109.0691362, 108.9526575, 109.0918738, 109.5719479, 110.0709355, 110.2238461, 111.0482402, 111.7032906, 112.0681263, 113.2569943, 113.7556718, 114.4686516, 114.8648031, 116.0008578, 116.1480839, 116.5337968, 116.5600485, 117.5216435, 117.4783387, 117.8118584, 118.9967473, 117.8756271, 118.0483297, 117.3132325, 117.8820349, 4.1375514, 4.3060941, 4.3065591, 3.1692384, 2.8214818, 1.4306882, 1.2175487, 1.4977900, 1.4101210, 0.9044412, 0.9764782, 0.7731314, 1.3381357, 2.0064670, 1.3419339, 0.4153755, -0.4595065, -1.3149065, -1.5928740, -2.9340325, -3.0494260, -2.9944422, -3.4783920, -3.1187757, -3.4391696, -3.4957036, -4.1069841, -3.6570374, -4.0127263, -2.4835173, -1.4876608, -0.8037232, 0.1024747, 0.7842418, 0.9022191, 1.8276407, 2.2876901, 3.2344282, 4.1375514, 118.2606165, 117.9000183, 117.6320244, 117.0837374, 116.7401408, 117.2777307, 117.9704016, 119.1265068, 118.8784599, 118.2606165, -8.3623833, -8.0956812, -8.4493031, -8.4571579, -9.0329367, -9.0408949, -8.9066395, -8.7058249, -8.2806829, -8.3623833, 120.2950143, 120.7156088, 120.7755017, 120.4257556, 119.9003097, 118.9678085, 120.2950143, -10.2586500, -10.2395814, -9.9696754, -9.6659213, -9.3613404, -9.5579693, -10.2586500, 121.3416687, 120.7150920, 119.9209286, 119.9243909, 121.2544906, 122.7569829, 122.9035372, 122.0073645, 121.3416687, -8.5367396, -8.2369646, -8.4448589, -8.8104180, -8.9336663, -8.6498076, -8.0942343, -8.4606202, -8.5367396, 122.9275668, 121.6668168, 120.8857793, 120.0357019, 119.8259990, 119.3233940, 119.1809737, 118.7677690, 119.0783444, 119.4988355, 119.6536064, 119.3669056, 119.7965434, 120.4307166, 120.3900472, 120.3054529, 120.9723890, 120.8981816, 121.6191712, 121.4894633, 121.7382337, 122.7195691, 122.2363945, 122.6285153, 123.1623328, 123.1709628, 122.2718962, 122.4545724, 121.5082736, 122.3885299, 122.8227153, 123.2583993, 123.3405648, 121.4758208, 120.9359054, 120.0408696, 120.1830831, 121.0567249, 122.7230831, 123.6855050, 124.4370354, 125.2405005, 125.0659892, 124.0775224, 122.9275668, 0.8751924, 1.0139436, 1.3092227, 0.5664774, 0.1542545, -1.3531471, -2.1471038, -2.8019992, -3.4870220, -3.4944117, -4.4594174, -5.3798780, -5.6734002, -5.5282411, -4.0975790, -2.9316037, -2.6276429, -3.6021054, -4.1884779, -4.5745525, -4.8513315, -4.4641716, -5.2829330, -5.6345912, -5.3406039, -4.6836931, -3.5295000, -3.1860584, -1.9044829, -1.5168580, -0.9309506, -1.0762131, -0.6156727, -0.9559620, -1.4089059, -0.5196579, 0.2372468, 0.3812174, 0.4311368, 0.2355932, 0.4278812, 1.4198361, 1.6432592, 0.9171020, 0.8751924, 124.9686825, 123.9800090, 123.5500094, 123.4599890, 123.5799817, 124.4359501, 125.0885201, 125.0700200, 124.9686825, -8.8927902, -9.2900270, -9.9000156, -10.2399948, -10.3599875, -10.1400009, -9.3931731, -9.0899875, -8.8927902, 126.8749227, 127.2492151, 127.0006515, 125.9890336, 126.1838021, 126.8749227, -3.7909828, -3.4590650, -3.1293177, -3.1772735, -3.6073764, -3.7909828, 127.9323776, 127.6005115, 127.3994902, 127.6964746, 128.1000159, 128.3799988, 127.9680343, 128.1201697, 128.6359522, 128.6882487, 128.5945594, 128.0041561, 127.9323776, 2.1745963, 1.8106908, 1.0117215, -0.2665984, -0.8999964, -0.7800038, -0.2520773, 0.3564127, 0.2584858, 1.1323860, 1.5408107, 1.6285314, 2.1745963, 129.3709978, 128.1358793, 127.8988912, 128.5906836, 129.1552487, 129.9905465, 130.8348361, 130.4713440, 129.3709978, -2.8021542, -2.8436504, -3.3934360, -3.4286793, -3.3626368, -3.4463010, -3.8584722, -3.0937643, -2.8021542, 134.2101339, 134.7246245, 134.7270016, 134.4996253, 134.2903357, 134.1127755, 134.2101339, -6.8952377, -6.2144007, -5.7375823, -5.4450420, -5.7830575, -6.1424671, -6.8952377, 141.0002104, 139.9266842, 139.1849207, 138.3297274, 137.4407377, 136.2933142, 135.4576030, 134.4226274, 134.1433680, 133.9855481, 132.3801164, 131.8675379, 130.5195581, 130.9428398, 131.8362220, 132.2323735, 133.6962118, 133.7800310, 133.0668445, 131.9898043, 132.7537887, 132.7569410, 132.9839555, 133.3677047, 133.6628805, 135.1645976, 135.9892501, 137.9278398, 138.4079139, 138.6686215, 138.0390992, 137.6144739, 138.8814767, 139.1277666, 140.1434152, 141.0338518, 141.0170569, 141.0002104, -2.6001511, -2.4090516, -2.0512957, -1.7026865, -1.7035133, -2.3070423, -3.3677528, -2.7691847, -1.1518674, -0.7802105, -0.3695379, -0.6954611, -0.9377202, -1.4325221, -1.6171620, -2.2125261, -2.2145415, -2.4798483, -2.4604180, -2.8205510, -3.3117872, -3.7462826, -4.1129786, -4.0248186, -3.5388534, -4.4629314, -4.5465439, -5.3933656, -6.2328492, -7.3202247, -7.5978822, -8.4116826, -8.3809352, -8.0960430, -8.2971677, -9.1178928, -5.8590219, -2.6001511</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="thursday-september-8-2022.html#cb3-1" aria-hidden="true" tabindex="-1"></a>world[, <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>] <span class="co"># subset columns by column position</span></span></code></pre></div>
<pre><code>##     iso_a2                           name_long               continent
## 1       FJ                                Fiji                 Oceania
## 2       TZ                            Tanzania                  Africa
## 3       EH                      Western Sahara                  Africa
## 4       CA                              Canada           North America
## 5       US                       United States           North America
## 6       KZ                          Kazakhstan                    Asia
## 7       UZ                          Uzbekistan                    Asia
## 8       PG                    Papua New Guinea                 Oceania
## 9       ID                           Indonesia                    Asia
## 10      AR                           Argentina           South America
## 11      CL                               Chile           South America
## 12      CD    Democratic Republic of the Congo                  Africa
## 13      SO                             Somalia                  Africa
## 14      KE                               Kenya                  Africa
## 15      SD                               Sudan                  Africa
## 16      TD                                Chad                  Africa
## 17      HT                               Haiti           North America
## 18      DO                  Dominican Republic           North America
## 19      RU                  Russian Federation                  Europe
## 20      BS                             Bahamas           North America
## 21      FK                    Falkland Islands           South America
## 22      NO                              Norway                  Europe
## 23      GL                           Greenland           North America
## 24      TF French Southern and Antarctic Lands Seven seas (open ocean)
## 25      TL                         Timor-Leste                    Asia
## 26      ZA                        South Africa                  Africa
## 27      LS                             Lesotho                  Africa
## 28      MX                              Mexico           North America
## 29      UY                             Uruguay           South America
## 30      BR                              Brazil           South America
## 31      BO                             Bolivia           South America
## 32      PE                                Peru           South America
## 33      CO                            Colombia           South America
## 34      PA                              Panama           North America
## 35      CR                          Costa Rica           North America
## 36      NI                           Nicaragua           North America
## 37      HN                            Honduras           North America
## 38      SV                         El Salvador           North America
## 39      GT                           Guatemala           North America
## 40      BZ                              Belize           North America
## 41      VE                           Venezuela           South America
## 42      GY                              Guyana           South America
## 43      SR                            Suriname           South America
## 44      FR                              France                  Europe
## 45      EC                             Ecuador           South America
## 46      PR                         Puerto Rico           North America
## 47      JM                             Jamaica           North America
## 48      CU                                Cuba           North America
## 49      ZW                            Zimbabwe                  Africa
## 50      BW                            Botswana                  Africa
## 51      NA                             Namibia                  Africa
## 52      SN                             Senegal                  Africa
## 53      ML                                Mali                  Africa
## 54      MR                          Mauritania                  Africa
## 55      BJ                               Benin                  Africa
## 56      NE                               Niger                  Africa
## 57      NG                             Nigeria                  Africa
## 58      CM                            Cameroon                  Africa
## 59      TG                                Togo                  Africa
## 60      GH                               Ghana                  Africa
## 61      CI                       Côte d&#39;Ivoire                  Africa
## 62      GN                              Guinea                  Africa
## 63      GW                       Guinea-Bissau                  Africa
## 64      LR                             Liberia                  Africa
## 65      SL                        Sierra Leone                  Africa
## 66      BF                        Burkina Faso                  Africa
## 67      CF            Central African Republic                  Africa
## 68      CG               Republic of the Congo                  Africa
## 69      GA                               Gabon                  Africa
## 70      GQ                   Equatorial Guinea                  Africa
## 71      ZM                              Zambia                  Africa
## 72      MW                              Malawi                  Africa
## 73      MZ                          Mozambique                  Africa
## 74      SZ                            eSwatini                  Africa
## 75      AO                              Angola                  Africa
## 76      BI                             Burundi                  Africa
## 77      IL                              Israel                    Asia
## 78      LB                             Lebanon                    Asia
## 79      MG                          Madagascar                  Africa
## 80      PS                           Palestine                    Asia
## 81      GM                          The Gambia                  Africa
## 82      TN                             Tunisia                  Africa
## 83      DZ                             Algeria                  Africa
## 84      JO                              Jordan                    Asia
## 85      AE                United Arab Emirates                    Asia
## 86      QA                               Qatar                    Asia
## 87      KW                              Kuwait                    Asia
## 88      IQ                                Iraq                    Asia
## 89      OM                                Oman                    Asia
## 90      VU                             Vanuatu                 Oceania
## 91      KH                            Cambodia                    Asia
## 92      TH                            Thailand                    Asia
## 93      LA                             Lao PDR                    Asia
## 94      MM                             Myanmar                    Asia
## 95      VN                             Vietnam                    Asia
## 96      KP                     Dem. Rep. Korea                    Asia
## 97      KR                   Republic of Korea                    Asia
## 98      MN                            Mongolia                    Asia
## 99      IN                               India                    Asia
## 100     BD                          Bangladesh                    Asia
## 101     BT                              Bhutan                    Asia
## 102     NP                               Nepal                    Asia
## 103     PK                            Pakistan                    Asia
## 104     AF                         Afghanistan                    Asia
## 105     TJ                          Tajikistan                    Asia
## 106     KG                          Kyrgyzstan                    Asia
## 107     TM                        Turkmenistan                    Asia
## 108     IR                                Iran                    Asia
## 109     SY                               Syria                    Asia
## 110     AM                             Armenia                    Asia
## 111     SE                              Sweden                  Europe
## 112     BY                             Belarus                  Europe
## 113     UA                             Ukraine                  Europe
## 114     PL                              Poland                  Europe
## 115     AT                             Austria                  Europe
## 116     HU                             Hungary                  Europe
## 117     MD                             Moldova                  Europe
## 118     RO                             Romania                  Europe
## 119     LT                           Lithuania                  Europe
## 120     LV                              Latvia                  Europe
## 121     EE                             Estonia                  Europe
## 122     DE                             Germany                  Europe
## 123     BG                            Bulgaria                  Europe
## 124     GR                              Greece                  Europe
## 125     TR                              Turkey                    Asia
## 126     AL                             Albania                  Europe
## 127     HR                             Croatia                  Europe
## 128     CH                         Switzerland                  Europe
## 129     LU                          Luxembourg                  Europe
## 130     BE                             Belgium                  Europe
## 131     NL                         Netherlands                  Europe
## 132     PT                            Portugal                  Europe
## 133     ES                               Spain                  Europe
## 134     IE                             Ireland                  Europe
## 135     NC                       New Caledonia                 Oceania
## 136     SB                     Solomon Islands                 Oceania
## 137     NZ                         New Zealand                 Oceania
## 138     AU                           Australia                 Oceania
## 139     LK                           Sri Lanka                    Asia
## 140     CN                               China                    Asia
## 141     TW                              Taiwan                    Asia
## 142     IT                               Italy                  Europe
## 143     DK                             Denmark                  Europe
## 144     GB                      United Kingdom                  Europe
## 145     IS                             Iceland                  Europe
## 146     AZ                          Azerbaijan                    Asia
## 147     GE                             Georgia                    Asia
## 148     PH                         Philippines                    Asia
## 149     MY                            Malaysia                    Asia
## 150     BN                   Brunei Darussalam                    Asia
## 151     SI                            Slovenia                  Europe
## 152     FI                             Finland                  Europe
## 153     SK                            Slovakia                  Europe
## 154     CZ                      Czech Republic                  Europe
## 155     ER                             Eritrea                  Africa
## 156     JP                               Japan                    Asia
## 157     PY                            Paraguay           South America
## 158     YE                               Yemen                    Asia
## 159     SA                        Saudi Arabia                    Asia
## 160     AQ                          Antarctica              Antarctica
## 161   &lt;NA&gt;                     Northern Cyprus                    Asia
## 162     CY                              Cyprus                    Asia
## 163     MA                             Morocco                  Africa
## 164     EG                               Egypt                  Africa
## 165     LY                               Libya                  Africa
## 166     ET                            Ethiopia                  Africa
## 167     DJ                            Djibouti                  Africa
## 168   &lt;NA&gt;                          Somaliland                  Africa
## 169     UG                              Uganda                  Africa
## 170     RW                              Rwanda                  Africa
## 171     BA              Bosnia and Herzegovina                  Europe
## 172     MK                           Macedonia                  Europe
## 173     RS                              Serbia                  Europe
## 174     ME                          Montenegro                  Europe
## 175     XK                              Kosovo                  Europe
## 176     TT                 Trinidad and Tobago           North America
## 177     SS                         South Sudan                  Africa</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="thursday-september-8-2022.html#cb5-1" aria-hidden="true" tabindex="-1"></a>world[, <span class="fu">c</span>(<span class="st">&quot;name_long&quot;</span>, <span class="st">&quot;lifeExp&quot;</span>)] <span class="co"># subset columns by name</span></span></code></pre></div>
<pre><code>##                               name_long  lifeExp
## 1                                  Fiji 69.96000
## 2                              Tanzania 64.16300
## 3                        Western Sahara       NA
## 4                                Canada 81.95305
## 5                         United States 78.84146
## 6                            Kazakhstan 71.62000
## 7                            Uzbekistan 71.03900
## 8                      Papua New Guinea 65.23000
## 9                             Indonesia 68.85600
## 10                            Argentina 76.25200
## 11                                Chile 79.11700
## 12     Democratic Republic of the Congo 58.78200
## 13                              Somalia 55.46700
## 14                                Kenya 66.24200
## 15                                Sudan 64.00200
## 16                                 Chad 52.20400
## 17                                Haiti 62.75700
## 18                   Dominican Republic 73.48300
## 19                   Russian Federation 70.74366
## 20                              Bahamas 75.37900
## 21                     Falkland Islands       NA
## 22                               Norway       NA
## 23                            Greenland       NA
## 24  French Southern and Antarctic Lands       NA
## 25                          Timor-Leste 68.28500
## 26                         South Africa 60.99300
## 27                              Lesotho 53.26800
## 28                               Mexico 76.75300
## 29                              Uruguay 77.19000
## 30                               Brazil 75.04200
## 31                              Bolivia 68.35700
## 32                                 Peru 74.51800
## 33                             Colombia 74.02200
## 34                               Panama 77.61000
## 35                           Costa Rica 79.44000
## 36                            Nicaragua 74.88400
## 37                             Honduras 73.18100
## 38                          El Salvador 73.01500
## 39                            Guatemala 72.86900
## 40                               Belize 70.02700
## 41                            Venezuela 74.19600
## 42                               Guyana 66.42500
## 43                             Suriname 71.13800
## 44                               France       NA
## 45                              Ecuador 75.87900
## 46                          Puerto Rico 79.39012
## 47                              Jamaica 75.68900
## 48                                 Cuba 79.41500
## 49                             Zimbabwe 59.36000
## 50                             Botswana 64.78000
## 51                              Namibia 62.98100
## 52                              Senegal 66.37600
## 53                                 Mali 57.00700
## 54                           Mauritania 62.90700
## 55                                Benin 60.37300
## 56                                Niger 59.22800
## 57                              Nigeria 52.54900
## 58                             Cameroon 57.11100
## 59                                 Togo 59.60100
## 60                                Ghana 62.15400
## 61                        Côte d&#39;Ivoire 52.52000
## 62                               Guinea 58.84600
## 63                        Guinea-Bissau 56.59800
## 64                              Liberia 61.52700
## 65                         Sierra Leone 50.95100
## 66                         Burkina Faso 59.45700
## 67             Central African Republic 50.62100
## 68                Republic of the Congo 63.53600
## 69                                Gabon 65.21100
## 70                    Equatorial Guinea 57.18000
## 71                               Zambia 60.77500
## 72                               Malawi 61.93200
## 73                           Mozambique 57.09900
## 74                             eSwatini 56.28700
## 75                               Angola 60.85800
## 76                              Burundi 56.68800
## 77                               Israel 82.15366
## 78                              Lebanon 79.23100
## 79                           Madagascar 65.13300
## 80                            Palestine 73.12600
## 81                           The Gambia 60.70700
## 82                              Tunisia 75.33500
## 83                              Algeria 75.64100
## 84                               Jordan 74.03400
## 85                 United Arab Emirates 76.94800
## 86                                Qatar 77.88800
## 87                               Kuwait 74.45800
## 88                                 Iraq 69.45800
## 89                                 Oman 76.57800
## 90                              Vanuatu 71.70900
## 91                             Cambodia 68.25100
## 92                             Thailand 74.89500
## 93                              Lao PDR 65.97500
## 94                              Myanmar 66.28500
## 95                              Vietnam 75.85500
## 96                      Dem. Rep. Korea 71.17900
## 97                    Republic of Korea 81.72195
## 98                             Mongolia 68.84700
## 99                                India 68.02100
## 100                          Bangladesh 71.80300
## 101                              Bhutan 69.43000
## 102                               Nepal 69.51100
## 103                            Pakistan 66.13900
## 104                         Afghanistan 62.89500
## 105                          Tajikistan 70.69000
## 106                          Kyrgyzstan 70.40244
## 107                        Turkmenistan 67.55200
## 108                                Iran 75.46600
## 109                               Syria 69.81700
## 110                             Armenia 74.25500
## 111                              Sweden 82.25366
## 112                             Belarus 72.97073
## 113                             Ukraine 71.18659
## 114                              Poland 77.60244
## 115                             Austria 81.49024
## 116                             Hungary 75.76341
## 117                             Moldova 71.25800
## 118                             Romania 74.96098
## 119                           Lithuania 74.51707
## 120                              Latvia 74.12439
## 121                             Estonia 77.03415
## 122                             Germany 81.09024
## 123                            Bulgaria 74.46585
## 124                              Greece 81.38537
## 125                              Turkey 75.23900
## 126                             Albania 77.96300
## 127                             Croatia 77.47805
## 128                         Switzerland 83.19756
## 129                          Luxembourg 82.22927
## 130                             Belgium 81.28780
## 131                         Netherlands 81.70732
## 132                            Portugal 81.12195
## 133                               Spain 83.22927
## 134                             Ireland 81.34878
## 135                       New Caledonia 77.25287
## 136                     Solomon Islands 70.11300
## 137                         New Zealand 81.40488
## 138                           Australia 82.30000
## 139                           Sri Lanka 74.90600
## 140                               China 75.93200
## 141                              Taiwan       NA
## 142                               Italy 83.09024
## 143                             Denmark 80.70000
## 144                      United Kingdom 81.30488
## 145                             Iceland 82.86098
## 146                          Azerbaijan 71.80000
## 147                             Georgia 72.95100
## 148                         Philippines 68.81300
## 149                            Malaysia 74.97600
## 150                   Brunei Darussalam 76.91700
## 151                            Slovenia 81.07805
## 152                             Finland 81.18049
## 153                            Slovakia 76.81220
## 154                      Czech Republic 78.82439
## 155                             Eritrea 64.17400
## 156                               Japan 83.58780
## 157                            Paraguay 72.91300
## 158                               Yemen 64.52300
## 159                        Saudi Arabia 74.23400
## 160                          Antarctica       NA
## 161                     Northern Cyprus       NA
## 162                              Cyprus 80.17300
## 163                             Morocco 75.30900
## 164                               Egypt 71.12000
## 165                               Libya 71.65900
## 166                            Ethiopia 64.53500
## 167                            Djibouti 62.00600
## 168                          Somaliland       NA
## 169                              Uganda 59.22400
## 170                              Rwanda 66.18800
## 171              Bosnia and Herzegovina 76.56100
## 172                           Macedonia 75.38400
## 173                              Serbia 75.33659
## 174                          Montenegro 76.71200
## 175                              Kosovo 71.09756
## 176                 Trinidad and Tobago 70.42600
## 177                         South Sudan 55.81700</code></pre>
<p>Here you use logical vectors to create a subset. First create a logical vector <code>sel_area</code>.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="thursday-september-8-2022.html#cb7-1" aria-hidden="true" tabindex="-1"></a>sel_area <span class="ot">&lt;-</span> world<span class="sc">$</span>area_km2 <span class="sc">&lt;</span> <span class="dv">10000</span></span>
<span id="cb7-2"><a href="thursday-september-8-2022.html#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(sel_area)</span></code></pre></div>
<pre><code>## [1] FALSE FALSE FALSE FALSE FALSE FALSE</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="thursday-september-8-2022.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sel_area)</span></code></pre></div>
<pre><code>##    Mode   FALSE    TRUE 
## logical     170       7</code></pre>
<p>Then select only cases from the <code>world</code> simple feature data frame where the elements of the <code>sel_area</code> vector are <code>TRUE</code>.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="thursday-september-8-2022.html#cb11-1" aria-hidden="true" tabindex="-1"></a>small_countries <span class="ot">&lt;-</span> world[sel_area, ]</span></code></pre></div>
<p>This creates a new simple feature data frame, <code>small_countries</code>, containing nations whose surface area is smaller than 10,000 square kilometers.</p>
<p>Note: there is no harm in keeping the geometry column because an operation on a {sf} object only changes the geometry when appropriate (e.g. by dissolving borders between adjacent polygons following aggregation). This means that the speed of operations with attribute data in {sf} objects is the same as with columns in a data frames.</p>
<p>The {base} R function <code>subset()</code> provides another way to get the same result.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="thursday-september-8-2022.html#cb12-1" aria-hidden="true" tabindex="-1"></a>small_countries <span class="ot">&lt;-</span> <span class="fu">subset</span>(world, </span>
<span id="cb12-2"><a href="thursday-september-8-2022.html#cb12-2" aria-hidden="true" tabindex="-1"></a>                          area_km2 <span class="sc">&lt;</span> <span class="dv">10000</span>)</span></code></pre></div>
<p>The {dplyr} verbs work on {sf} spatial data frames. The functions include <code>dplyr::select()</code> and <code>dplyr::filter()</code>.</p>
<p>CAUTION! The {dplyr} and {raster} packages have a <code>select()</code> function. When using both packages in the same session, the function in the most recently attached package will be used, ‘masking’ the other function. This will generate error messages containing text like: unable to find an inherited method for function ‘select’ for signature “sf”. To avoid this error message, and prevent ambiguity, you should always use the long-form function name, prefixed by the package name and two colons <code>dplyr::select()</code>.</p>
<p>The <code>dplyr::select()</code> function picks the columns by name or position. For example, you can select only two columns, <code>name_long</code> and <code>pop</code>, with the following command.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="thursday-september-8-2022.html#cb13-1" aria-hidden="true" tabindex="-1"></a>world1 <span class="ot">&lt;-</span> world <span class="sc">|&gt;</span></span>
<span id="cb13-2"><a href="thursday-september-8-2022.html#cb13-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(name_long, pop)</span>
<span id="cb13-3"><a href="thursday-september-8-2022.html#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(world1)</span></code></pre></div>
<pre><code>## [1] &quot;name_long&quot; &quot;pop&quot;</code></pre>
<p>The result is a simple feature data frame with the geometry column.</p>
<p>With the <code>select()</code> function you can subset and rename columns at the same time. Here you select the columns with names <code>name_long</code> and <code>pop</code> and give the <code>pop</code> column a new name (<code>population</code>).</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="thursday-september-8-2022.html#cb15-1" aria-hidden="true" tabindex="-1"></a>world <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="thursday-september-8-2022.html#cb15-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(name_long, </span>
<span id="cb15-3"><a href="thursday-september-8-2022.html#cb15-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">population =</span> pop)</span></code></pre></div>
<pre><code>## # A tibble: 177 × 2
##    name_long        population
##    &lt;chr&gt;                 &lt;dbl&gt;
##  1 Fiji                 885806
##  2 Tanzania           52234869
##  3 Western Sahara           NA
##  4 Canada             35535348
##  5 United States     318622525
##  6 Kazakhstan         17288285
##  7 Uzbekistan         30757700
##  8 Papua New Guinea    7755785
##  9 Indonesia         255131116
## 10 Argentina          42981515
## # … with 167 more rows</code></pre>
<p>The <code>dplyr::pull()</code> function returns a single vector without the geometry.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="thursday-september-8-2022.html#cb17-1" aria-hidden="true" tabindex="-1"></a>world <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="thursday-september-8-2022.html#cb17-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">pull</span>(pop)</span></code></pre></div>
<pre><code>##   [1]     885806   52234869         NA   35535348  318622525   17288285
##   [7]   30757700    7755785  255131116   42981515   17613798   73722860
##  [13]   13513125   46024250   37737913   13569438   10572466   10405844
##  [19]  143819666     382169         NA         NA      56295         NA
##  [25]    1212814   54539571    2145785  124221600    3419546  204213133
##  [31]   10562159   30973354   47791911    3903986    4757575    6013997
##  [37]    8809216    6281189   15923559     351694   30738378     763393
##  [43]     547928         NA   15903112    3534874    2862087   11439767
##  [49]   15411675    2168573    2370992   14546111   16962846    4063920
##  [55]   10286712   19148219  176460502   22239904    7228915   26962563
##  [61]   22531350   11805509    1725744    4390737    7079162   17585977
##  [67]    4515392    4871101    1875713    1129424   15620974   17068838
##  [73]   27212382    1295097   26920466    9891790    8215700    5603279
##  [79]   23589801    4294682    1917852   11143908   39113313    8809306
##  [85]    9070867    2374419    3782450   35006080    3960925     258850
##  [91]   15270790   68416772    6576397   51924182   92544915   25116363
##  [97]   50746659    2923896 1293859294  159405279     776448   28323241
## [103]  185546257   32758020    8362745    5835500    5466241   78411092
## [109]   19203090    2906220    9696110    9474511   45271947   38011735
## [115]    8546356    9866468    3556397   19908979    2932367    1993782
## [121]    1314545   80982500    7223938   10892413   77030628    2889104
## [127]    4238389    8188649     556319   11209057   16865008   10401062
## [133]   46480882    4657740     268050     575504    4509700   23504138
## [139]   20771000 1364270000         NA   60789140    5643475   64613160
## [145]     327386    9535079    3727000  100102249   30228017     411704
## [151]    2061980    5461512    5418649   10525347         NA  127276000
## [157]    6552584   26246327   30776722         NA         NA    1152309
## [163]   34318082   91812566    6204108   97366774     912164         NA
## [169]   38833338   11345357    3566002    2077495    7130576     621810
## [175]    1821800    1354493   11530971</code></pre>
<p>The <code>filter()</code> function keeps only rows matching given criteria, e.g., only countries with a very high average life expectancy.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="thursday-september-8-2022.html#cb19-1" aria-hidden="true" tabindex="-1"></a>world <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a href="thursday-september-8-2022.html#cb19-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span></span>
<span id="cb19-3"><a href="thursday-september-8-2022.html#cb19-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(lifeExp <span class="sc">&gt;</span> <span class="dv">82</span>)</span></code></pre></div>
<pre><code>## # A tibble: 9 × 10
##   iso_a2 name_long   continent region_un subregion type  area_km2    pop lifeExp
##   &lt;chr&gt;  &lt;chr&gt;       &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt;    &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1 IL     Israel      Asia      Asia      Western … Coun…   22991. 8.22e6    82.2
## 2 SE     Sweden      Europe    Europe    Northern… Sove…  450582. 9.70e6    82.3
## 3 CH     Switzerland Europe    Europe    Western … Sove…   46185. 8.19e6    83.2
## 4 LU     Luxembourg  Europe    Europe    Western … Sove…    2417. 5.56e5    82.2
## 5 ES     Spain       Europe    Europe    Southern… Sove…  502306. 4.65e7    83.2
## 6 AU     Australia   Oceania   Oceania   Australi… Coun… 7687614. 2.35e7    82.3
## 7 IT     Italy       Europe    Europe    Southern… Sove…  315105. 6.08e7    83.1
## 8 IS     Iceland     Europe    Europe    Northern… Sove…  107736. 3.27e5    82.9
## 9 JP     Japan       Asia      Asia      Eastern … Sove…  404620. 1.27e8    83.6
## # … with 1 more variable: gdpPercap &lt;dbl&gt;</code></pre>
<p>Aggregation summarizes a data frame by a grouping variable. An example of aggregation is to calculate the number of people per continent based on country-level data (one row per country).</p>
<p>This is done with the <code>dplyr::group_by()</code> and <code>dplyr::summarize()</code> functions.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="thursday-september-8-2022.html#cb21-1" aria-hidden="true" tabindex="-1"></a>world <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="thursday-september-8-2022.html#cb21-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(continent) <span class="sc">|&gt;</span></span>
<span id="cb21-3"><a href="thursday-september-8-2022.html#cb21-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">Population =</span> <span class="fu">sum</span>(pop, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb21-4"><a href="thursday-september-8-2022.html#cb21-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">nCountries =</span> dplyr<span class="sc">::</span><span class="fu">n</span>())</span></code></pre></div>
<pre><code>## Simple feature collection with 8 features and 3 fields
## Geometry type: GEOMETRY
## Dimension:     XY
## Bounding box:  xmin: -180 ymin: -89.9 xmax: 180 ymax: 83.64513
## Geodetic CRS:  WGS 84
## # A tibble: 8 × 4
##   continent               Population nCountries                             geom
##   &lt;chr&gt;                        &lt;dbl&gt;      &lt;int&gt;                   &lt;GEOMETRY [°]&gt;
## 1 Africa                  1154946633         51 MULTIPOLYGON (((43.1453 11.4620…
## 2 Antarctica                       0          1 MULTIPOLYGON (((-180 -89.9, 180…
## 3 Asia                    4311408059         47 MULTIPOLYGON (((104.37 -1.08484…
## 4 Europe                   669036256         39 MULTIPOLYGON (((-180 64.97971, …
## 5 North America            565028684         18 MULTIPOLYGON (((-132.71 54.0400…
## 6 Oceania                   37757833          7 MULTIPOLYGON (((-180 -16.55522,…
## 7 Seven seas (open ocean)          0          1 POLYGON ((68.935 -48.625, 68.86…
## 8 South America            412060811         13 MULTIPOLYGON (((-66.95992 -54.8…</code></pre>
<p>The two columns in the resulting table are <code>Population</code> and <code>nCountries</code>. The functions <code>sum()</code> and <code>dplyr::n()</code> were the aggregating functions.</p>
<p>The result is a simple feature data frame with a single row representing attributes of the world and the geometry as a single multi-polygon through the geometric <em>union</em> operator.</p>
<p>You can chain together functions to find the world’s three most populous continents and the number of countries they contain.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="thursday-september-8-2022.html#cb23-1" aria-hidden="true" tabindex="-1"></a>world <span class="sc">|&gt;</span> </span>
<span id="cb23-2"><a href="thursday-september-8-2022.html#cb23-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(pop, continent) <span class="sc">|&gt;</span> </span>
<span id="cb23-3"><a href="thursday-september-8-2022.html#cb23-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(continent) <span class="sc">|&gt;</span> </span>
<span id="cb23-4"><a href="thursday-september-8-2022.html#cb23-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">Population =</span> <span class="fu">sum</span>(pop, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb23-5"><a href="thursday-september-8-2022.html#cb23-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">nCountries =</span> dplyr<span class="sc">::</span><span class="fu">n</span>()) <span class="sc">|&gt;</span> </span>
<span id="cb23-6"><a href="thursday-september-8-2022.html#cb23-6" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">top_n</span>(<span class="at">n =</span> <span class="dv">3</span>, <span class="at">wt =</span> Population) </span></code></pre></div>
<pre><code>## Simple feature collection with 3 features and 3 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -180 ymin: -34.81917 xmax: 180 ymax: 81.2504
## Geodetic CRS:  WGS 84
## # A tibble: 3 × 4
##   continent Population nCountries                                           geom
## * &lt;chr&gt;          &lt;dbl&gt;      &lt;int&gt;                             &lt;MULTIPOLYGON [°]&gt;
## 1 Africa    1154946633         51 (((43.1453 11.46204, 42.71587 11.73564, 43.28…
## 2 Asia      4311408059         47 (((104.37 -1.084843, 104.0108 -1.059212, 103.…
## 3 Europe     669036256         39 (((-180 64.97971, -179.4327 65.40411, -179.88…</code></pre>
<p>If you want to create a new column based on existing columns use <code>dplyr::mutate()</code>. For example, if you want to calculate population density for each country divide the population column, here <code>pop</code>, by an area column, here <code>area_km2</code> with unit area in square kilometers.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="thursday-september-8-2022.html#cb25-1" aria-hidden="true" tabindex="-1"></a>world <span class="sc">|&gt;</span> </span>
<span id="cb25-2"><a href="thursday-september-8-2022.html#cb25-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Population_Density =</span> pop <span class="sc">/</span> area_km2)</span></code></pre></div>
<pre><code>## Simple feature collection with 177 features and 11 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -180 ymin: -89.9 xmax: 180 ymax: 83.64513
## Geodetic CRS:  WGS 84
## # A tibble: 177 × 12
##    iso_a2 name_long continent region_un subregion type  area_km2     pop lifeExp
##  * &lt;chr&gt;  &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
##  1 FJ     Fiji      Oceania   Oceania   Melanesia Sove…   1.93e4  8.86e5    70.0
##  2 TZ     Tanzania  Africa    Africa    Eastern … Sove…   9.33e5  5.22e7    64.2
##  3 EH     Western … Africa    Africa    Northern… Inde…   9.63e4 NA         NA  
##  4 CA     Canada    North Am… Americas  Northern… Sove…   1.00e7  3.55e7    82.0
##  5 US     United S… North Am… Americas  Northern… Coun…   9.51e6  3.19e8    78.8
##  6 KZ     Kazakhst… Asia      Asia      Central … Sove…   2.73e6  1.73e7    71.6
##  7 UZ     Uzbekist… Asia      Asia      Central … Sove…   4.61e5  3.08e7    71.0
##  8 PG     Papua Ne… Oceania   Oceania   Melanesia Sove…   4.65e5  7.76e6    65.2
##  9 ID     Indonesia Asia      Asia      South-Ea… Sove…   1.82e6  2.55e8    68.9
## 10 AR     Argentina South Am… Americas  South Am… Sove…   2.78e6  4.30e7    76.3
## # … with 167 more rows, and 3 more variables: gdpPercap &lt;dbl&gt;,
## #   geom &lt;MULTIPOLYGON [°]&gt;, Population_Density &lt;dbl&gt;</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="thursday-september-8-2022.html#cb27-1" aria-hidden="true" tabindex="-1"></a>world <span class="sc">|&gt;</span></span>
<span id="cb27-2"><a href="thursday-september-8-2022.html#cb27-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">transmute</span>(<span class="at">Population_Density =</span> pop <span class="sc">/</span> area_km2)</span></code></pre></div>
<pre><code>## Simple feature collection with 177 features and 1 field
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -180 ymin: -89.9 xmax: 180 ymax: 83.64513
## Geodetic CRS:  WGS 84
## # A tibble: 177 × 2
##    Population_Density                                                       geom
##  *              &lt;dbl&gt;                                         &lt;MULTIPOLYGON [°]&gt;
##  1              45.9  (((-180 -16.55522, -179.9174 -16.50178, -179.7933 -16.020…
##  2              56.0  (((33.90371 -0.95, 31.86617 -1.02736, 30.76986 -1.01455, …
##  3              NA    (((-8.66559 27.65643, -8.817828 27.65643, -8.794884 27.12…
##  4               3.54 (((-132.71 54.04001, -133.18 54.16998, -133.2397 53.85108…
##  5              33.5  (((-171.7317 63.78252, -171.7911 63.40585, -171.5531 63.3…
##  6               6.33 (((87.35997 49.21498, 86.82936 49.82667, 85.54127 49.6928…
##  7              66.7  (((55.96819 41.30864, 57.09639 41.32231, 56.93222 41.8260…
##  8              16.7  (((141.0002 -2.600151, 141.0171 -5.859022, 141.0339 -9.11…
##  9             140.   (((104.37 -1.084843, 104.0108 -1.059212, 103.4376 -0.7119…
## 10              15.4  (((-68.63401 -52.63637, -68.63335 -54.8695, -67.56244 -54…
## # … with 167 more rows</code></pre>
<p>The <code>dplyr::transmute()</code> function performs the same computation but also removes the other columns (except the geometry column).</p>
<p>Subsetting (filtering) your data based on geographic boundaries</p>
<p>The {USAboundaries} package has historical and contemporary boundaries for the United States provided by the U.S. Census Bureau.</p>
<p>Individual states are extracted using the <code>us_states()</code> function. CAUTION: this function has the same name as the object <code>us_states</code> from the {spData} package.</p>
<p>Here you use the argument <code>states =</code> to get only the state of Kansas. You then make a plot of the boundary and check the native coordinate reference system (CRS).</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="thursday-september-8-2022.html#cb29-1" aria-hidden="true" tabindex="-1"></a>KS.sf <span class="ot">&lt;-</span> USAboundaries<span class="sc">::</span><span class="fu">us_states</span>(<span class="at">states =</span> <span class="st">&quot;Kansas&quot;</span>)</span>
<span id="cb29-2"><a href="thursday-september-8-2022.html#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="thursday-september-8-2022.html#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb29-4"><a href="thursday-september-8-2022.html#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="thursday-september-8-2022.html#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> KS.sf) <span class="sc">+</span></span>
<span id="cb29-6"><a href="thursday-september-8-2022.html#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="thursday-september-8-2022.html#cb30-1" aria-hidden="true" tabindex="-1"></a>sf<span class="sc">::</span><span class="fu">st_crs</span>(KS.sf)</span></code></pre></div>
<pre><code>## Coordinate Reference System:
##   User input: EPSG:4326 
##   wkt:
## GEOGCRS[&quot;WGS 84&quot;,
##     DATUM[&quot;World Geodetic System 1984&quot;,
##         ELLIPSOID[&quot;WGS 84&quot;,6378137,298.257223563,
##             LENGTHUNIT[&quot;metre&quot;,1]]],
##     PRIMEM[&quot;Greenwich&quot;,0,
##         ANGLEUNIT[&quot;degree&quot;,0.0174532925199433]],
##     CS[ellipsoidal,2],
##         AXIS[&quot;geodetic latitude (Lat)&quot;,north,
##             ORDER[1],
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433]],
##         AXIS[&quot;geodetic longitude (Lon)&quot;,east,
##             ORDER[2],
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433]],
##     USAGE[
##         SCOPE[&quot;Horizontal component of 3D system.&quot;],
##         AREA[&quot;World.&quot;],
##         BBOX[-90,-180,90,180]],
##     ID[&quot;EPSG&quot;,4326]]</code></pre>
<p>The polygon geometry includes the border and the area inside the border. The CRS is described by the 4326 EPSG code and implemented using well-known text (WKT).</p>
<p>You use a geometric operation to subset spatial data geographically (rather than on some attribute). For example here you subset the tornado tracks as line strings, keeping only those line strings that fall within the Kansas border defined by a polygon geometry.</p>
<p>First import the tornado data. Note here you first ask if the tornado data file is in our list of files with the <code>if()</code> conditional and the <code>list.files()</code> function. You only download the data file if the file is not (<code>!</code>) in the list.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="thursday-september-8-2022.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="st">&quot;1950-2020-torn-aspath&quot;</span> <span class="sc">%in%</span> <span class="fu">list.files</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>))) {</span>
<span id="cb32-2"><a href="thursday-september-8-2022.html#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(<span class="at">url =</span> <span class="st">&quot;http://www.spc.noaa.gov/gis/svrgis/zipped/1950-2020-torn-aspath.zip&quot;</span>,</span>
<span id="cb32-3"><a href="thursday-september-8-2022.html#cb32-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">destfile =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;1950-2020-torn-aspath.zip&quot;</span>))</span>
<span id="cb32-4"><a href="thursday-september-8-2022.html#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="fu">unzip</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;1950-2020-torn-aspath.zip&quot;</span>), </span>
<span id="cb32-5"><a href="thursday-september-8-2022.html#cb32-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">exdir =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>))</span>
<span id="cb32-6"><a href="thursday-september-8-2022.html#cb32-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb32-7"><a href="thursday-september-8-2022.html#cb32-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-8"><a href="thursday-september-8-2022.html#cb32-8" aria-hidden="true" tabindex="-1"></a>Torn.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="at">dsn =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;1950-2020-torn-aspath&quot;</span>), </span>
<span id="cb32-9"><a href="thursday-september-8-2022.html#cb32-9" aria-hidden="true" tabindex="-1"></a>                       <span class="at">layer =</span> <span class="st">&quot;1950-2020-torn-aspath&quot;</span>) </span></code></pre></div>
<pre><code>## Reading layer `1950-2020-torn-aspath&#39; from data source 
##   `/Users/jameselsner/Desktop/ClassNotes/ASS-2022/data/1950-2020-torn-aspath&#39; 
##   using driver `ESRI Shapefile&#39;
## Simple feature collection with 66244 features and 22 fields
## Geometry type: LINESTRING
## Dimension:     XY
## Bounding box:  xmin: -163.53 ymin: 17.7212 xmax: -64.7151 ymax: 61.02
## Geodetic CRS:  WGS 84</code></pre>
<p>The geometries are line strings representing the approximate track of each tornado. The CRS has EPSG code of 4326, same as the Kansas polygon.</p>
<p>To keep only the tornado tracks that fall within the border of Kansas you use the <code>sf::st_intersection()</code> function. The first argument (<code>x =</code>) is the simple feature data frame that you want to subset and the second argument (<code>y =</code>) defines the geometry over which the subset occurs.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="thursday-september-8-2022.html#cb34-1" aria-hidden="true" tabindex="-1"></a>KS_Torn.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_intersection</span>(<span class="at">x =</span> Torn.sf, </span>
<span id="cb34-2"><a href="thursday-september-8-2022.html#cb34-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">y =</span> KS.sf)</span></code></pre></div>
<pre><code>## Warning: attribute variables are assumed to be spatially constant throughout all
## geometries</code></pre>
<p>You can use the pipe operator (<code>|&gt;</code>) to pass the first argument to the function.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="thursday-september-8-2022.html#cb36-1" aria-hidden="true" tabindex="-1"></a>KS_Torn.sf <span class="ot">&lt;-</span> Torn.sf <span class="sc">|&gt;</span></span>
<span id="cb36-2"><a href="thursday-september-8-2022.html#cb36-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_intersection</span>(<span class="at">y =</span> KS.sf)</span></code></pre></div>
<pre><code>## Warning: attribute variables are assumed to be spatially constant throughout all
## geometries</code></pre>
<p>You make a plot to see if things appear as you expect.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="thursday-september-8-2022.html#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb38-2"><a href="thursday-september-8-2022.html#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> KS.sf) <span class="sc">+</span></span>
<span id="cb38-3"><a href="thursday-september-8-2022.html#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> KS_Torn.sf)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>Note that no tornado track lies outside the state border. Line strings that lie outside the border are clipped at the border. However the attribute values represent the entire track.</p>
<p>If you want the entire tornado track for all tornadoes that passed into (or through) the state, then you first use the geometric binary predict function <code>sf::st_intersects()</code>. With <code>sparse = FALSE</code> a matrix with a single column of <code>TRUE</code>s and <code>FALSE</code>s is returned. Here you use the piping operator to implicitly specify the <code>x =</code> argument as the <code>Torn.sf</code> data frame.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="thursday-september-8-2022.html#cb39-1" aria-hidden="true" tabindex="-1"></a>Intersects <span class="ot">&lt;-</span> Torn.sf <span class="sc">|&gt;</span></span>
<span id="cb39-2"><a href="thursday-september-8-2022.html#cb39-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_intersects</span>(<span class="at">y =</span> KS.sf, <span class="at">sparse =</span> <span class="cn">FALSE</span>)</span>
<span id="cb39-3"><a href="thursday-september-8-2022.html#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="thursday-september-8-2022.html#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Intersects)</span></code></pre></div>
<pre><code>##       [,1]
## [1,] FALSE
## [2,] FALSE
## [3,] FALSE
## [4,] FALSE
## [5,] FALSE
## [6,] FALSE</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="thursday-september-8-2022.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(Intersects)</span></code></pre></div>
<pre><code>## [1] 4377</code></pre>
<p>Next you create a new data frame from the original data frame keeping only observations (rows) where <code>Interects</code> is TRUE.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="thursday-september-8-2022.html#cb43-1" aria-hidden="true" tabindex="-1"></a>KS_Torn2.sf <span class="ot">&lt;-</span> Torn.sf[Intersects, ]</span>
<span id="cb43-2"><a href="thursday-september-8-2022.html#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="thursday-september-8-2022.html#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb43-4"><a href="thursday-september-8-2022.html#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> KS.sf) <span class="sc">+</span></span>
<span id="cb43-5"><a href="thursday-september-8-2022.html#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> KS_Torn2.sf)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>Are tornadoes more common in some parts of Kansas than others? One way to answer this question is to see how far away the tornado centroid is from the center of the state.</p>
<p>Start by computing the centers of the state polygon and the combined set of Kansas tornadoes using the <code>sf::st_centroid()</code> function. Note you first use the <code>sf::st_combine()</code> function on the tornadoes.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="thursday-september-8-2022.html#cb44-1" aria-hidden="true" tabindex="-1"></a>geocenterKS <span class="ot">&lt;-</span> KS.sf <span class="sc">|&gt;</span></span>
<span id="cb44-2"><a href="thursday-september-8-2022.html#cb44-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_centroid</span>()</span></code></pre></div>
<pre><code>## Warning in st_centroid.sf(KS.sf): st_centroid assumes attributes are constant
## over geometries of x</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="thursday-september-8-2022.html#cb46-1" aria-hidden="true" tabindex="-1"></a>centerKStornadoes <span class="ot">&lt;-</span> KS_Torn.sf <span class="sc">|&gt;</span></span>
<span id="cb46-2"><a href="thursday-september-8-2022.html#cb46-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_combine</span>() <span class="sc">|&gt;</span></span>
<span id="cb46-3"><a href="thursday-september-8-2022.html#cb46-3" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_centroid</span>()</span></code></pre></div>
<p>Then make a map and compute the distance in meters using the <code>sf::st_distance()</code> function.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="thursday-september-8-2022.html#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb47-2"><a href="thursday-september-8-2022.html#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> KS.sf) <span class="sc">+</span></span>
<span id="cb47-3"><a href="thursday-september-8-2022.html#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> geocenterKS, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb47-4"><a href="thursday-september-8-2022.html#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> centerKStornadoes, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="thursday-september-8-2022.html#cb48-1" aria-hidden="true" tabindex="-1"></a>geocenterKS <span class="sc">|&gt;</span></span>
<span id="cb48-2"><a href="thursday-september-8-2022.html#cb48-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_distance</span>(centerKStornadoes)</span></code></pre></div>
<pre><code>## Units: [m]
##          [,1]
## [1,] 2875.099</code></pre>
<p>Less than 3 km!</p>
<p>More examples: <a href="https://www.jla-data.net/eng/spatial-aggregation/" class="uri">https://www.jla-data.net/eng/spatial-aggregation/</a></p>
<p>Mutating data frames with joins</p>
<p>Combining data from different sources based on a shared variable is a common operation. The {dplyr} package has join functions that follow naming conventions used in database languages (like SQL).</p>
<p>Given two data frames labeled <code>x</code> and <code>y</code>, the join functions add columns <em>from y</em> <em>to x</em>, matching rows based on the function name.</p>
<ul>
<li><code>inner_join()</code>: includes all rows in <code>x</code> <em>and</em> <code>y</code></li>
<li><code>left_join()</code>: includes all rows in <code>x</code></li>
<li><code>full_join()</code>: includes all rows in <code>x</code> <em>or</em> <code>y</code></li>
</ul>
<p>Join functions work the same on data frames and on simple feature data frames. The most common type of attribute join on spatial data takes a simple feature data frame as the first argument and adds columns to it from a data a frame specified as the second argument.</p>
<p>For example, you combine data on coffee production with the <code>spData::world</code> simple feature data frame. Coffee production by country is in the data frame called <code>spData::coffee_data</code>.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="thursday-september-8-2022.html#cb50-1" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">glimpse</span>(spData<span class="sc">::</span>coffee_data)</span></code></pre></div>
<pre><code>## Rows: 47
## Columns: 3
## $ name_long              &lt;chr&gt; &quot;Angola&quot;, &quot;Bolivia&quot;, &quot;Brazil&quot;, &quot;Burundi&quot;, &quot;Came…
## $ coffee_production_2016 &lt;int&gt; NA, 3, 3277, 37, 8, NA, 4, 1330, 28, 114, NA, 1…
## $ coffee_production_2017 &lt;int&gt; NA, 4, 2786, 38, 6, NA, 12, 1169, 32, 130, NA, …</code></pre>
<p>It has 3 columns: <code>name_long</code> names major coffee-producing nations and <code>coffee_production_2016</code> and <code>coffee_production_2017</code> contain estimated values for coffee production in units of 60-kg bags per year.</p>
<p>First select only the name and GDP (per person) from the <code>spData::world</code> simple feature data frame.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="thursday-september-8-2022.html#cb52-1" aria-hidden="true" tabindex="-1"></a>( world.sf <span class="ot">&lt;-</span> spData<span class="sc">::</span>world <span class="sc">|&gt;</span></span>
<span id="cb52-2"><a href="thursday-september-8-2022.html#cb52-2" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(name_long, gdpPercap) )</span></code></pre></div>
<pre><code>## Simple feature collection with 177 features and 2 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -180 ymin: -89.9 xmax: 180 ymax: 83.64513
## Geodetic CRS:  WGS 84
## # A tibble: 177 × 3
##    name_long        gdpPercap                                               geom
##    &lt;chr&gt;                &lt;dbl&gt;                                 &lt;MULTIPOLYGON [°]&gt;
##  1 Fiji                 8222. (((-180 -16.55522, -179.9174 -16.50178, -179.7933…
##  2 Tanzania             2402. (((33.90371 -0.95, 31.86617 -1.02736, 30.76986 -1…
##  3 Western Sahara         NA  (((-8.66559 27.65643, -8.817828 27.65643, -8.7948…
##  4 Canada              43079. (((-132.71 54.04001, -133.18 54.16998, -133.2397 …
##  5 United States       51922. (((-171.7317 63.78252, -171.7911 63.40585, -171.5…
##  6 Kazakhstan          23587. (((87.35997 49.21498, 86.82936 49.82667, 85.54127…
##  7 Uzbekistan           5371. (((55.96819 41.30864, 57.09639 41.32231, 56.93222…
##  8 Papua New Guinea     3709. (((141.0002 -2.600151, 141.0171 -5.859022, 141.03…
##  9 Indonesia           10003. (((104.37 -1.084843, 104.0108 -1.059212, 103.4376…
## 10 Argentina           18798. (((-68.63401 -52.63637, -68.63335 -54.8695, -67.5…
## # … with 167 more rows</code></pre>
<p>The <code>dplyr::left_join()</code> function takes the data frame named by the argument <code>x =</code> and joins it to the data frame named by the argument <code>y =</code>.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="thursday-september-8-2022.html#cb54-1" aria-hidden="true" tabindex="-1"></a>( world_coffee.sf <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">left_join</span>(<span class="at">x =</span> world.sf, </span>
<span id="cb54-2"><a href="thursday-september-8-2022.html#cb54-2" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">y =</span> spData<span class="sc">::</span>coffee_data) )</span></code></pre></div>
<pre><code>## Joining, by = &quot;name_long&quot;</code></pre>
<pre><code>## Simple feature collection with 177 features and 4 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -180 ymin: -89.9 xmax: 180 ymax: 83.64513
## Geodetic CRS:  WGS 84
## # A tibble: 177 × 5
##    name_long        gdpPercap                              geom coffee_producti…
##    &lt;chr&gt;                &lt;dbl&gt;                &lt;MULTIPOLYGON [°]&gt;            &lt;int&gt;
##  1 Fiji                 8222. (((-180 -16.55522, -179.9174 -16…               NA
##  2 Tanzania             2402. (((33.90371 -0.95, 31.86617 -1.0…               81
##  3 Western Sahara         NA  (((-8.66559 27.65643, -8.817828 …               NA
##  4 Canada              43079. (((-132.71 54.04001, -133.18 54.…               NA
##  5 United States       51922. (((-171.7317 63.78252, -171.7911…               NA
##  6 Kazakhstan          23587. (((87.35997 49.21498, 86.82936 4…               NA
##  7 Uzbekistan           5371. (((55.96819 41.30864, 57.09639 4…               NA
##  8 Papua New Guinea     3709. (((141.0002 -2.600151, 141.0171 …              114
##  9 Indonesia           10003. (((104.37 -1.084843, 104.0108 -1…              742
## 10 Argentina           18798. (((-68.63401 -52.63637, -68.6333…               NA
## # … with 167 more rows, and 1 more variable: coffee_production_2017 &lt;int&gt;</code></pre>
<p>Because the two data frames share a common variable name (<code>name_long</code>) the join works without using the <code>by =</code> argument. The result is a simple feature data frame identical to the <code>world.sf</code> object but with two new variables indicating coffee production in 2016 and 2017.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="thursday-september-8-2022.html#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(world_coffee.sf)</span></code></pre></div>
<pre><code>## [1] &quot;name_long&quot;              &quot;gdpPercap&quot;              &quot;geom&quot;                  
## [4] &quot;coffee_production_2016&quot; &quot;coffee_production_2017&quot;</code></pre>
<p>For a join to work there must be at least one variable name in common.</p>
<p>Since the object listed in the <code>x =</code> argument is a simple feature data frame, the join function returns a simple feature data frame with the same number of rows (observations).</p>
<p>Although there are only 47 rows of data in <code>spData::coffee_data</code>, all 177 of the country records in <code>world.sf</code> are kept intact in <code>world_coffee.sf</code>. Rows in the first dataset with no match are assigned <code>NA</code> values for the new coffee production variables.</p>
<p>If you want to keep only countries that have a match in the key variable then use <code>dplyr::inner_join()</code>. Here you use the piping operator to implicitly specify the <code>x =</code> argument as the <code>world.sf</code> data frame.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="thursday-september-8-2022.html#cb59-1" aria-hidden="true" tabindex="-1"></a>world.sf <span class="sc">|&gt;</span></span>
<span id="cb59-2"><a href="thursday-september-8-2022.html#cb59-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">inner_join</span>(spData<span class="sc">::</span>coffee_data)</span></code></pre></div>
<pre><code>## Joining, by = &quot;name_long&quot;</code></pre>
<pre><code>## Simple feature collection with 45 features and 4 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -117.1278 ymin: -33.76838 xmax: 156.02 ymax: 35.49401
## Geodetic CRS:  WGS 84
## # A tibble: 45 × 5
##    name_long          gdpPercap                            geom coffee_producti…
##    &lt;chr&gt;                  &lt;dbl&gt;              &lt;MULTIPOLYGON [°]&gt;            &lt;int&gt;
##  1 Tanzania               2402. (((33.90371 -0.95, 31.86617 -1…               81
##  2 Papua New Guinea       3709. (((141.0002 -2.600151, 141.017…              114
##  3 Indonesia             10003. (((104.37 -1.084843, 104.0108 …              742
##  4 Kenya                  2753. (((39.20222 -4.67677, 39.60489…               60
##  5 Dominican Republic    12663. (((-71.7083 18.045, -71.65766 …                1
##  6 Timor-Leste            6263. (((124.9687 -8.89279, 125.07 -…               14
##  7 Mexico                16623. (((-117.1278 32.53534, -116.72…              151
##  8 Brazil                15374. (((-53.37366 -33.76838, -52.71…             3277
##  9 Bolivia                6325. (((-69.52968 -10.95173, -68.66…                3
## 10 Peru                  11548. (((-69.89364 -4.298187, -70.39…              585
## # … with 35 more rows, and 1 more variable: coffee_production_2017 &lt;int&gt;</code></pre>
<p>You can join in the other direction as well, starting with a regular data frame and adding variables from a simple features object.</p>
<p>More information on attribute data operations such as these is given here: <a href="https://geocompr.robinlovelace.net/attr.html" class="uri">https://geocompr.robinlovelace.net/attr.html</a></p>
</div>
<div id="interpolation-using-areal-weights" class="section level2 unnumbered hasAnchor">
<h2>Interpolation using areal weights<a href="thursday-september-8-2022.html#interpolation-using-areal-weights" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Areal-weighted interpolation estimates the value of some variable from a set of polygons to an overlapping but incongruent set of target polygons. For example, suppose you want demographic information given at the Census tract level to be estimated within the tornado damage path. Damage paths do not align with census tract boundaries so areal weighted interpolation is needed to get demographic estimates at the tornado level.</p>
<p>The function <code>sf::st_interpolate_aw()</code> performs areal-weighted interpolation of polygon data. As an example, consider the number of births by county in North Carolina in over the period 1970 through 1974 (<code>BIR74</code>).</p>
<p>The data are available as a shapefile as part of the {sf} package system file. Use the <code>sf::st_read()</code> function together with the <code>system.file()</code> function to import the data. Then create a map filling by the <code>BIR74</code> variable.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="thursday-september-8-2022.html#cb62-1" aria-hidden="true" tabindex="-1"></a>nc.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="fu">system.file</span>(<span class="st">&quot;shape/nc.shp&quot;</span>, </span>
<span id="cb62-2"><a href="thursday-september-8-2022.html#cb62-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">package =</span> <span class="st">&quot;sf&quot;</span>))</span></code></pre></div>
<pre><code>## Reading layer `nc&#39; from data source 
##   `/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/sf/shape/nc.shp&#39; 
##   using driver `ESRI Shapefile&#39;
## Simple feature collection with 100 features and 14 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
## Geodetic CRS:  NAD27</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="thursday-september-8-2022.html#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> nc.sf) <span class="sc">+</span></span>
<span id="cb64-2"><a href="thursday-september-8-2022.html#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">fill =</span> BIR74))</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>Next construct a 20 by 10 grid of polygons that overlap the state using the <code>sf::st_make_grid()</code> function. The function takes the bounding box from the <code>nc.sf</code> simple feature data frame and constructs a two-dimension grid using the dimensions specified with the <code>n =</code> argument.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="thursday-september-8-2022.html#cb65-1" aria-hidden="true" tabindex="-1"></a>g.sfc <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_make_grid</span>(nc.sf, </span>
<span id="cb65-2"><a href="thursday-september-8-2022.html#cb65-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">n =</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">10</span>))</span>
<span id="cb65-3"><a href="thursday-september-8-2022.html#cb65-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-4"><a href="thursday-september-8-2022.html#cb65-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb65-5"><a href="thursday-september-8-2022.html#cb65-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> g.sfc, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb65-6"><a href="thursday-september-8-2022.html#cb65-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> nc.sf, <span class="at">fill =</span> <span class="st">&quot;transparent&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p>The result is overlapping but incongruent sets of polygons as a <code>sfc</code> (simple feature column).</p>
<p>Then you use the <code>sf::st_interpolate_aw()</code> function with the first argument a simple feature data frame for which you want to aggregate a particular variable and the argument <code>to =</code> to the set of polygons for which you want the variable to be aggregated. The name of the variable must be put in quotes inside the subset operator <code>[]</code>. The argument <code>extensive =</code> if <code>FALSE</code> (default) assumes the variable is spatially intensive (like population density) and the mean is preserved.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="thursday-september-8-2022.html#cb66-1" aria-hidden="true" tabindex="-1"></a>a1.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_interpolate_aw</span>(nc.sf[<span class="st">&quot;BIR74&quot;</span>], </span>
<span id="cb66-2"><a href="thursday-september-8-2022.html#cb66-2" aria-hidden="true" tabindex="-1"></a>                               <span class="at">to =</span> g.sfc,</span>
<span id="cb66-3"><a href="thursday-september-8-2022.html#cb66-3" aria-hidden="true" tabindex="-1"></a>                               <span class="at">extensive =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Warning in st_interpolate_aw.sf(nc.sf[&quot;BIR74&quot;], to = g.sfc, extensive = FALSE):
## st_interpolate_aw assumes attributes are constant or uniform over areas of x</code></pre>
<p>The result is a simple feature data frame with the same polygons geometry as the <code>sfc</code> grid and a single variable called (<code>BIR74</code>).</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="thursday-september-8-2022.html#cb68-1" aria-hidden="true" tabindex="-1"></a>( p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span>  </span>
<span id="cb68-2"><a href="thursday-september-8-2022.html#cb68-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>(<span class="at">data =</span> a1.sf, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">fill =</span> BIR74)) <span class="sc">+</span></span>
<span id="cb68-3"><a href="thursday-september-8-2022.html#cb68-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">18000</span>)) <span class="sc">+</span></span>
<span id="cb68-4"><a href="thursday-september-8-2022.html#cb68-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Intensive&quot;</span>) )</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<p>Note that the average number of births across the state at the county level matches (roughly) the average number of births across the grid of polygons, but the sums do not match.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="thursday-september-8-2022.html#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(a1.sf<span class="sc">$</span>BIR74) <span class="sc">/</span> <span class="fu">mean</span>(nc.sf<span class="sc">$</span>BIR74)</span></code></pre></div>
<pre><code>## [1] 1.040669</code></pre>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="thursday-september-8-2022.html#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(a1.sf<span class="sc">$</span>BIR74) <span class="sc">/</span> <span class="fu">sum</span>(nc.sf<span class="sc">$</span>BIR74)</span></code></pre></div>
<pre><code>## [1] 1.436123</code></pre>
<p>An <em>intensive</em> variable is independent of the spatial units (e.g., population density, percentages); a variable that has been normalized in some fashion. An <em>extensive</em> variable depends on the spatial unit (e.g., population totals). Assuming a uniform population density, the number of people will depend on the size of the spatial area.</p>
<p>Since the number of births in each county is an extensive variable, you change the <code>extensive =</code> argument to <code>TRUE</code>.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="thursday-september-8-2022.html#cb73-1" aria-hidden="true" tabindex="-1"></a>a2.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_interpolate_aw</span>(nc.sf[<span class="st">&quot;BIR74&quot;</span>], </span>
<span id="cb73-2"><a href="thursday-september-8-2022.html#cb73-2" aria-hidden="true" tabindex="-1"></a>                               <span class="at">to =</span> g.sfc, </span>
<span id="cb73-3"><a href="thursday-september-8-2022.html#cb73-3" aria-hidden="true" tabindex="-1"></a>                               <span class="at">extensive =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Warning in st_interpolate_aw.sf(nc.sf[&quot;BIR74&quot;], to = g.sfc, extensive = TRUE):
## st_interpolate_aw assumes attributes are constant or uniform over areas of x</code></pre>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="thursday-september-8-2022.html#cb75-1" aria-hidden="true" tabindex="-1"></a>( p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(a2.sf) <span class="sc">+</span>  </span>
<span id="cb75-2"><a href="thursday-september-8-2022.html#cb75-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">fill =</span> BIR74)) <span class="sc">+</span></span>
<span id="cb75-3"><a href="thursday-september-8-2022.html#cb75-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">18000</span>)) <span class="sc">+</span></span>
<span id="cb75-4"><a href="thursday-september-8-2022.html#cb75-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Extensive&quot;</span>) )</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<p>In this case you preserve the total number of births across the domain. You verify this ‘mass preservation’ property (pycnophylactic property) with a ratio of one.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="thursday-september-8-2022.html#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(a2.sf<span class="sc">$</span>BIR74) <span class="sc">/</span> <span class="fu">sum</span>(nc.sf<span class="sc">$</span>BIR74)</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>Here you create a plot of both interpolations.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="thursday-september-8-2022.html#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb78-2"><a href="thursday-september-8-2022.html#cb78-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-3"><a href="thursday-september-8-2022.html#cb78-3" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">/</span> p2</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<p>Example: tornado paths and housing units</p>
<p>Here you are interested in the number of houses (housing units) affected by tornadoes occurring in Florida 2014-2020. You begin by creating a polygon geometry for each tornado record.</p>
<p>Import the data, transform the native CRS to 3857 (pseudo-Mercator), and filter on <code>yr</code> (year) and <code>st</code> (state).</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="thursday-september-8-2022.html#cb79-1" aria-hidden="true" tabindex="-1"></a>FL_Torn.sf <span class="ot">&lt;-</span> Torn.sf <span class="sc">|&gt;</span></span>
<span id="cb79-2"><a href="thursday-september-8-2022.html#cb79-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3857</span>) <span class="sc">|&gt;</span></span>
<span id="cb79-3"><a href="thursday-september-8-2022.html#cb79-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(yr <span class="sc">&gt;=</span> <span class="dv">2014</span>, </span>
<span id="cb79-4"><a href="thursday-september-8-2022.html#cb79-4" aria-hidden="true" tabindex="-1"></a>                st <span class="sc">==</span> <span class="st">&quot;FL&quot;</span>)</span></code></pre></div>
<p>Next change the geometries from line strings to polygons to represent the tornado path (‘footprint’). The path width is given by the variable labeled <code>wid</code>. First you create new a new variable with the width in units of meters and then use the <code>st_buffer()</code> function with the <code>dist =</code> argument set to 1/2 the width.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="thursday-september-8-2022.html#cb80-1" aria-hidden="true" tabindex="-1"></a>FL_Torn.sf <span class="ot">&lt;-</span> FL_Torn.sf <span class="sc">|&gt;</span></span>
<span id="cb80-2"><a href="thursday-september-8-2022.html#cb80-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Width =</span> wid <span class="sc">*</span> .<span class="dv">9144</span>)</span>
<span id="cb80-3"><a href="thursday-september-8-2022.html#cb80-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-4"><a href="thursday-september-8-2022.html#cb80-4" aria-hidden="true" tabindex="-1"></a>FL_TornPath.sf <span class="ot">&lt;-</span> FL_Torn.sf <span class="sc">|&gt;</span></span>
<span id="cb80-5"><a href="thursday-september-8-2022.html#cb80-5" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_buffer</span>(<span class="at">dist =</span> FL_Torn.sf<span class="sc">$</span>Width <span class="sc">/</span> <span class="dv">2</span>)</span></code></pre></div>
<p>To see the change from line string track to polygon path plot both together for one of the tornadoes.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="thursday-september-8-2022.html#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb81-2"><a href="thursday-september-8-2022.html#cb81-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> FL_TornPath.sf[<span class="dv">10</span>, ]) <span class="sc">+</span></span>
<span id="cb81-3"><a href="thursday-september-8-2022.html#cb81-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> FL_Torn.sf[<span class="dv">10</span>, ], <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<p>Now you want the number of houses within the path. The housing units are from the census data. You can access these data with the <code>tidycensus::get_acs()</code> function. The {tidycensus} package is an interface to the decennial US Census and American Community Survey APIs and the US Census Bureau’s geographic boundary files. Functions return Census and ACS data as simple feature data frames for all Census geographies.</p>
<p>Note: You need to get an API key from U.S. Census. Then</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="thursday-september-8-2022.html#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">file.create</span>(<span class="st">&quot;CensusAPI&quot;</span>) <span class="co"># open then copy/paste your API key</span></span></code></pre></div>
<p>To ensure the file is only readable by you, not by any other user on the system use the function <code>Sys.chmod()</code> then read the key and install it.</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="thursday-september-8-2022.html#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Sys.chmod</span>(<span class="st">&quot;CensusAPI&quot;</span>, <span class="at">mode =</span> <span class="st">&quot;0400&quot;</span>)</span>
<span id="cb83-2"><a href="thursday-september-8-2022.html#cb83-2" aria-hidden="true" tabindex="-1"></a>key <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_file</span>(<span class="st">&quot;CensusAPI&quot;</span>)</span>
<span id="cb83-3"><a href="thursday-september-8-2022.html#cb83-3" aria-hidden="true" tabindex="-1"></a>tidycensus<span class="sc">::</span><span class="fu">census_api_key</span>(key, <span class="at">install =</span> <span class="cn">TRUE</span>, <span class="at">overwrite =</span> <span class="cn">TRUE</span>)</span>
<span id="cb83-4"><a href="thursday-september-8-2022.html#cb83-4" aria-hidden="true" tabindex="-1"></a><span class="fu">readRenviron</span>(<span class="st">&quot;~/.Renviron&quot;</span>)</span></code></pre></div>
<p>Make sure the file is listed in the file <code>.gitignore</code> so it doesn’t get included in your git public repository.</p>
<p>The geometry is the tract level and the variable is the un-weighted sample housing units (B00002_001). Transform the CRS to that of the tornadoes.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="thursday-september-8-2022.html#cb84-1" aria-hidden="true" tabindex="-1"></a>Census.sf <span class="ot">&lt;-</span> tidycensus<span class="sc">::</span><span class="fu">get_acs</span>(<span class="at">geography =</span> <span class="st">&quot;tract&quot;</span>, </span>
<span id="cb84-2"><a href="thursday-september-8-2022.html#cb84-2" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">variables =</span> <span class="st">&quot;B00002_001&quot;</span>,</span>
<span id="cb84-3"><a href="thursday-september-8-2022.html#cb84-3" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">state =</span> <span class="st">&quot;FL&quot;</span>,</span>
<span id="cb84-4"><a href="thursday-september-8-2022.html#cb84-4" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">year =</span> <span class="dv">2015</span>,</span>
<span id="cb84-5"><a href="thursday-september-8-2022.html#cb84-5" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">geometry =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb84-6"><a href="thursday-september-8-2022.html#cb84-6" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> sf<span class="sc">::</span><span class="fu">st_crs</span>(FL_TornPath.sf))</span></code></pre></div>
<pre><code>## Getting data from the 2011-2015 5-year ACS</code></pre>
<pre><code>## Downloading feature geometry from the Census website.  To cache shapefiles for use in future sessions, set `options(tigris_use_cache = TRUE)`.</code></pre>
<pre><code>## 
  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |=                                                                     |   1%
  |                                                                            
  |=                                                                     |   2%
  |                                                                            
  |==                                                                    |   3%
  |                                                                            
  |===                                                                   |   4%
  |                                                                            
  |===                                                                   |   5%
  |                                                                            
  |====                                                                  |   5%
  |                                                                            
  |====                                                                  |   6%
  |                                                                            
  |=====                                                                 |   7%
  |                                                                            
  |======                                                                |   9%
  |                                                                            
  |=======                                                               |  10%
  |                                                                            
  |=======                                                               |  11%
  |                                                                            
  |========                                                              |  11%
  |                                                                            
  |========                                                              |  12%
  |                                                                            
  |=========                                                             |  13%
  |                                                                            
  |==========                                                            |  14%
  |                                                                            
  |===========                                                           |  16%
  |                                                                            
  |============                                                          |  17%
  |                                                                            
  |==============                                                        |  20%
  |                                                                            
  |===============                                                       |  21%
  |                                                                            
  |=================                                                     |  25%
  |                                                                            
  |===================                                                   |  27%
  |                                                                            
  |=====================                                                 |  31%
  |                                                                            
  |=======================                                               |  33%
  |                                                                            
  |========================                                              |  34%
  |                                                                            
  |==========================                                            |  37%
  |                                                                            
  |============================                                          |  40%
  |                                                                            
  |=============================                                         |  42%
  |                                                                            
  |===============================                                       |  44%
  |                                                                            
  |================================                                      |  45%
  |                                                                            
  |=================================                                     |  47%
  |                                                                            
  |===================================                                   |  50%
  |                                                                            
  |====================================                                  |  51%
  |                                                                            
  |====================================                                  |  52%
  |                                                                            
  |=======================================                               |  55%
  |                                                                            
  |==========================================                            |  59%
  |                                                                            
  |===========================================                           |  62%
  |                                                                            
  |============================================================          |  85%
  |                                                                            
  |======================================================================| 100%</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="thursday-september-8-2022.html#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Census.sf)</span></code></pre></div>
<pre><code>## Simple feature collection with 6 features and 4 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -9527976 ymin: 3452498 xmax: -9168692 ymax: 3522281
## Projected CRS: WGS 84 / Pseudo-Mercator
##         GEOID                                        NAME   variable estimate
## 1 12001001201 Census Tract 12.01, Alachua County, Florida B00002_001      112
## 2 12001001519 Census Tract 15.19, Alachua County, Florida B00002_001       99
## 3 12001001520 Census Tract 15.20, Alachua County, Florida B00002_001       85
## 4 12001002207 Census Tract 22.07, Alachua County, Florida B00002_001      137
## 5 12001002218 Census Tract 22.18, Alachua County, Florida B00002_001      111
## 6 12005000805      Census Tract 8.05, Bay County, Florida B00002_001      159
##                         geometry
## 1 MULTIPOLYGON (((-9171497 34...
## 2 MULTIPOLYGON (((-9171172 34...
## 3 MULTIPOLYGON (((-9171771 34...
## 4 MULTIPOLYGON (((-9177078 34...
## 5 MULTIPOLYGON (((-9175225 34...
## 6 MULTIPOLYGON (((-9527976 35...</code></pre>
<p>The column labeled <code>estimate</code> is the estimate of the number of housing units within the census tract.</p>
<p>Finally you use the <code>sf::st_interpolate_aw()</code> function to spatially interpolate the housing units to the tornado path.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="thursday-september-8-2022.html#cb90-1" aria-hidden="true" tabindex="-1"></a>awi.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_interpolate_aw</span>(Census.sf[<span class="st">&quot;estimate&quot;</span>],</span>
<span id="cb90-2"><a href="thursday-september-8-2022.html#cb90-2" aria-hidden="true" tabindex="-1"></a>                                <span class="at">to =</span> FL_TornPath.sf, </span>
<span id="cb90-3"><a href="thursday-september-8-2022.html#cb90-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">extensive =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Warning in st_interpolate_aw.sf(Census.sf[&quot;estimate&quot;], to = FL_TornPath.sf, :
## st_interpolate_aw assumes attributes are constant or uniform over areas of x</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="thursday-september-8-2022.html#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(awi.sf)</span></code></pre></div>
<pre><code>## Simple feature collection with 6 features and 1 field
## Attribute-geometry relationship: 0 constant, 1 aggregate, 0 identity
## Geometry type: POLYGON
## Dimension:     XY
## Bounding box:  xmin: -9502241 ymin: 3489409 xmax: -9452129 ymax: 3606099
## Projected CRS: WGS 84 / Pseudo-Mercator
##       estimate                       geometry
## 1 1.801417e-02 POLYGON ((-9481985 3545304,...
## 2 3.493061e-05 POLYGON ((-9452129 3489418,...
## 3 3.493061e-05 POLYGON ((-9452129 3504835,...
## 4 6.396930e-03 POLYGON ((-9459939 3509978,...
## 5 2.001489e-05 POLYGON ((-9452129 3521558,...
## 6 5.666174e-02 POLYGON ((-9499599 3606097,...</code></pre>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="thursday-september-8-2022.html#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(awi.sf<span class="sc">$</span>estimate, </span>
<span id="cb94-2"><a href="thursday-september-8-2022.html#cb94-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1]   0.0000 175.6654</code></pre>
<p>The tornado that hit the most houses occurred just east of downtown Orlando.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="thursday-september-8-2022.html#cb96-1" aria-hidden="true" tabindex="-1"></a>awi.sf2 <span class="ot">&lt;-</span> awi.sf <span class="sc">|&gt;</span></span>
<span id="cb96-2"><a href="thursday-september-8-2022.html#cb96-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(estimate <span class="sc">&gt;</span> <span class="dv">175</span>)</span>
<span id="cb96-3"><a href="thursday-september-8-2022.html#cb96-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-4"><a href="thursday-september-8-2022.html#cb96-4" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tmap_mode</span>(<span class="st">&quot;view&quot;</span>)</span></code></pre></div>
<pre><code>## tmap mode set to interactive viewing</code></pre>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="thursday-september-8-2022.html#cb98-1" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_shape</span>(awi.sf2) <span class="sc">+</span></span>
<span id="cb98-2"><a href="thursday-september-8-2022.html#cb98-2" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_borders</span>()</span></code></pre></div>
<div id="htmlwidget-ea54ed3f2991b10a0f15" style="width:672px;height:480px;" class="leaflet html-widget"></div>
<script type="application/json" data-for="htmlwidget-ea54ed3f2991b10a0f15">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"createMapPane","args":["tmap401",401]},{"method":"addProviderTiles","args":["Esri.WorldGrayCanvas",null,"Esri.WorldGrayCanvas",{"minZoom":0,"maxZoom":18,"tileSize":256,"subdomains":"abc","errorTileUrl":"","tms":false,"noWrap":false,"zoomOffset":0,"zoomReverse":false,"opacity":1,"zIndex":1,"detectRetina":false,"pane":"tilePane"}]},{"method":"addProviderTiles","args":["OpenStreetMap",null,"OpenStreetMap",{"minZoom":0,"maxZoom":18,"tileSize":256,"subdomains":"abc","errorTileUrl":"","tms":false,"noWrap":false,"zoomOffset":0,"zoomReverse":false,"opacity":1,"zIndex":1,"detectRetina":false,"pane":"tilePane"}]},{"method":"addProviderTiles","args":["Esri.WorldTopoMap",null,"Esri.WorldTopoMap",{"minZoom":0,"maxZoom":18,"tileSize":256,"subdomains":"abc","errorTileUrl":"","tms":false,"noWrap":false,"zoomOffset":0,"zoomReverse":false,"opacity":1,"zIndex":1,"detectRetina":false,"pane":"tilePane"}]},{"method":"addPolygons","args":[[[[{"lng":[-81.3656449713447,-81.3656519815475,-81.3656533674116,-81.3656491251383,-81.3656392663554,-81.3656238180852,-81.3656028226703,-81.3655763376577,-81.3655444356409,-81.3655072040612,-81.3654647449677,-81.3654171747379,-81.3653646237585,-81.365307236068,-81.3652451689621,-81.3651785925624,-81.3651076893502,-81.3650326536663,-81.3649536911783,-81.3648710183169,-81.3647848616826,-81.3646954574248,-81.3646030505944,-81.364507894472,-81.3644102498739,-81.3643103844373,-81.3642085718863,-81.364105091282,-81.3640002262577,-81.363894264241,-81.3637874956665,-81.3636802131794,-81.3635727108336,-81.3634652832854,-81.3633582249864,-81.3632518293759,-81.3631463880769,-81.3630421900966,-81.3629395210346,-81.3628386622994,-81.362739890338,-81.3626434758773,-81.3625496831828,-81.3624587693337,-81.3623709835185,-81.3622865663521,-81.362205749216,-81.3621287536244,-81.3620557906168,-81.3619870601798,-81.3619227506988,-81.3618630384414,-81.361808087075,-81.3617580472174,-81.3617130560243,-81.3616732368135,-81.3616386987267,-81.3616095364303,-81.3615858298562,-81.3615676439825,-81.3615550286553,-81.3538550286553,-81.3538480184525,-81.3538466325884,-81.3538508748617,-81.3538607336446,-81.3538761819148,-81.3538971773297,-81.3539236623423,-81.3539555643591,-81.3539927959388,-81.3540352550323,-81.3540828252621,-81.3541353762415,-81.354192763932,-81.3542548310379,-81.3543214074376,-81.3543923106498,-81.3544673463337,-81.3545463088217,-81.3546289816831,-81.3547151383174,-81.3548045425752,-81.3548969494056,-81.354992105528,-81.3550897501261,-81.3551896155627,-81.3552914281137,-81.355394908718,-81.3554997737423,-81.355605735759,-81.3557125043335,-81.3558197868206,-81.3559272891665,-81.3560347167146,-81.3561417750136,-81.3562481706241,-81.3563536119231,-81.3564578099034,-81.3565604789654,-81.3566613377006,-81.3567601096621,-81.3568565241227,-81.3569503168172,-81.3570412306663,-81.3571290164815,-81.3572134336479,-81.357294250784,-81.3573712463756,-81.3574442093832,-81.3575129398202,-81.3575772493012,-81.3576369615586,-81.357691912925,-81.3577419527826,-81.3577869439757,-81.3578267631865,-81.3578613012733,-81.3578904635697,-81.3579141701438,-81.3579323560175,-81.3579449713447,-81.3656449713447],"lat":[28.5437352940675,28.5438295366082,28.5439239721998,28.5440183420006,28.5441123873502,28.544205850478,28.5442984752098,28.5443900076704,28.5444801969788,28.544568795936,28.544655561703,28.5447402564654,28.5448226480862,28.5449025107413,28.5449796255387,28.5450537811184,28.5451247742315,28.5451924102975,28.5452565039372,28.545316879481,28.5453733714503,28.545425825011,28.5454740963975,28.5455180533071,28.5455575752627,28.5455925539422,28.545622893476,28.5456485107097,28.5456693354318,28.5456853105658,28.5456963923274,28.5457025503437,28.5457037677368,28.5457000411703,28.5456913808578,28.5456778105353,28.5456593673964,28.5456361019899,28.5456080780814,28.5455753724787,28.5455380748214,28.5454962873349,28.5454501245504,28.5453997129915,28.5453451908265,28.5452867074908,28.5452244232766,28.5451585088941,28.5450891450032,28.5450165217192,28.5449408380906,28.5448623015549,28.544781127369,28.5446975380198,28.5446117626145,28.5445240362526,28.5444345993812,28.5443436971366,28.544251578672,28.5441584964749,28.544064705675,28.470264820937,28.4701705126552,28.4700760110189,28.4699815750502,28.4698874635922,28.4697939345989,28.4697012444288,28.4696096471417,28.4695193938026,28.4694307317933,28.4693439041346,28.4692591488198,28.4691766981627,28.4690967781604,28.4690196078741,28.4689453988284,28.4688743544317,28.4688066694181,28.4687425293143,28.4686821099305,28.4686255768785,28.4685730851178,28.4685247785308,28.4684807895284,28.4684412386868,28.4684062344171,28.4683758726681,28.4683502366635,28.4683293966731,28.4683134098207,28.4683023199274,28.4682961573914,28.4682949391047,28.4682986684065,28.4683073350747,28.4683209153533,28.4683393720179,28.4683626544774,28.468390698913,28.4684234284533,28.4684607533844,28.4685025713965,28.4685487678641,28.4685992161603,28.4686537780037,28.4687123038379,28.4687746332412,28.4688405953665,28.4689100094096,28.4689826851047,28.4690584232463,28.4691370162351,28.469218248647,28.4693018978239,28.4693877344836,28.4694755233489,28.4695650237919,28.4696559904941,28.4697481741188,28.4698413219941,28.4699351788059,28.5437352940675]}]]],"X1","awi.sf2",{"interactive":false,"className":"","pane":"tmap401","stroke":true,"color":"#666666","weight":1,"opacity":1,"fill":true,"fillOpacity":0,"dashArray":"none","smoothFactor":1,"noClip":false},null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]},{"method":"addLayersControl","args":[["Esri.WorldGrayCanvas","OpenStreetMap","Esri.WorldTopoMap"],"awi.sf2",{"collapsed":true,"autoZIndex":true,"position":"topleft"}]}],"limits":{"lat":[28.4682949391047,28.5457037677368],"lng":[-81.3656533674116,-81.3538466325884]},"fitBounds":[28.4682949391047,-81.3656533674116,28.5457037677368,-81.3538466325884,[]]},"evals":[],"jsHooks":[]}</script>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tuesday-september-6-2022.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="tuesday-september-13-2022.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
