<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Thursday November 3, 2022 | GIS5122: Applied Spatial Statistics</title>
  <meta name="description" content="Thursday November 3, 2022 | GIS5122: Applied Spatial Statistics" />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="Thursday November 3, 2022 | GIS5122: Applied Spatial Statistics" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="jelsner/ASS-2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Thursday November 3, 2022 | GIS5122: Applied Spatial Statistics" />
  
  
  

<meta name="author" content="James B. Elsner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tuesday-november-1-2022.html"/>
<link rel="next" href="thursday-november-10-2022.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.1.1/leaflet.js"></script>
<script src="libs/leaflet-providers-1.9.0/leaflet-providers_1.9.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.1.1/leaflet-providers-plugin.js"></script>
<script src="libs/Leaflet.Sync-0.0.5/L.Map.Sync.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied Spatial Statistics</a></li>

<li class="divider"></li>
<li><a href="index.html#section"></a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i>Syllabus</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#contact-information"><i class="fa fa-check"></i>Contact information</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#course-description-and-expected-learning-outcomes"><i class="fa fa-check"></i>Course description and expected learning outcomes</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#materials-and-class-meetings"><i class="fa fa-check"></i>Materials and class meetings</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#grades-and-ethics"><i class="fa fa-check"></i>Grades and ethics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#outline-of-topics-and-schedule"><i class="fa fa-check"></i>Outline of topics and schedule</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#reference-materials"><i class="fa fa-check"></i>Reference materials</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#reproducible-research"><i class="fa fa-check"></i>Reproducible research</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html"><i class="fa fa-check"></i>Tuesday, August 23, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#install-r-and-rstudio-on-your-computer"><i class="fa fa-check"></i>Install R and RStudio on your computer</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#download-course-materials"><i class="fa fa-check"></i>Download course materials</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#read-the-syllabus"><i class="fa fa-check"></i>Read the syllabus</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#about-rstudio"><i class="fa fa-check"></i>About RStudio</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#lab-assignments"><i class="fa fa-check"></i>Lab assignments</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#getting-started-with-r"><i class="fa fa-check"></i>Getting started with R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#are-you-completely-new-to-r"><i class="fa fa-check"></i>Are you completely new to R?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html"><i class="fa fa-check"></i>Thursday, August 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#expectations"><i class="fa fa-check"></i>Expectations</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-science-workflow-with-r-markdown"><i class="fa fa-check"></i>Data science workflow with R markdown</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#an-introduction-to-using-r"><i class="fa fa-check"></i>An introduction to using R</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-frames"><i class="fa fa-check"></i>Data frames</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html"><i class="fa fa-check"></i>Tuesday August 30, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#working-with-data-frames"><i class="fa fa-check"></i>Working with data frames</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html"><i class="fa fa-check"></i>Thursday September 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#making-graphs"><i class="fa fa-check"></i>Making graphs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html"><i class="fa fa-check"></i>Thursday September 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#working-with-spatial-data"><i class="fa fa-check"></i>Working with spatial data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#geo-computation-on-simple-features"><i class="fa fa-check"></i>Geo-computation on simple features</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html"><i class="fa fa-check"></i>Tuesday September 13, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#spatial-data-subsets-and-joins"><i class="fa fa-check"></i>Spatial data subsets and joins</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#interpolation-using-areal-weights"><i class="fa fa-check"></i>Interpolation using areal weights</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html"><i class="fa fa-check"></i>Thursday September 15, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#s4-spatial-data-objects"><i class="fa fa-check"></i>S4 spatial data objects</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#working-with-raster-data"><i class="fa fa-check"></i>Working with raster data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html"><i class="fa fa-check"></i>Tuesday September 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#working-with-space-time-data"><i class="fa fa-check"></i>Working with space-time data</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#mapping-using-functions-from-the-ggplot2-package"><i class="fa fa-check"></i>Mapping using functions from the {ggplot2} package</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#mapping-using-functions-from-the-tmap-package"><i class="fa fa-check"></i>Mapping using functions from the {tmap} package</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#creating-an-interactive-map"><i class="fa fa-check"></i>Creating an interactive map</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#adding-an-inset-map"><i class="fa fa-check"></i>Adding an inset map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-27-2022.html"><a href="tuesday-september-27-2022.html"><i class="fa fa-check"></i>Tuesday September 27, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-27-2022.html"><a href="tuesday-september-27-2022.html#defining-spatial-neighborhoods-and-spatial-weights"><i class="fa fa-check"></i>Defining spatial neighborhoods and spatial weights</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-27-2022.html"><a href="tuesday-september-27-2022.html#computing-autocorrelation"><i class="fa fa-check"></i>Computing autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-27-2022.html"><a href="tuesday-september-27-2022.html#spatial-lag-and-its-relation-to-autocorrelation"><i class="fa fa-check"></i>Spatial lag and its relation to autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html"><i class="fa fa-check"></i>Thursday September 29, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#other-neighbor-definitions"><i class="fa fa-check"></i>Other neighbor definitions</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#assessing-the-statistical-significance-of-autocorrelation"><i class="fa fa-check"></i>Assessing the statistical significance of autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#bivariate-spatial-autocorrelation"><i class="fa fa-check"></i>Bivariate spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#local-indicators-of-spatial-autocorrelation"><i class="fa fa-check"></i>Local indicators of spatial autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html"><i class="fa fa-check"></i>Tuesday October 4, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#constraining-group-membership-based-on-spatial-autocorrelation"><i class="fa fa-check"></i>Constraining group membership based on spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#estimating-spatial-autocorrelation-in-model-residuals"><i class="fa fa-check"></i>Estimating spatial autocorrelation in model residuals</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#choosing-a-spatial-regression-model"><i class="fa fa-check"></i>Choosing a spatial regression model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html"><i class="fa fa-check"></i>Thursday October 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#fitting-and-interpreting-a-spatially-lagged-y-model"><i class="fa fa-check"></i>Fitting and interpreting a spatially-lagged Y model</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#fitting-and-interpreting-a-spatially-lagged-x-model"><i class="fa fa-check"></i>Fitting and interpreting a spatially-lagged X model</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#fitting-and-interpreting-spatial-durbin-models"><i class="fa fa-check"></i>Fitting and interpreting spatial Durbin models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html"><i class="fa fa-check"></i>Tuesday October 11, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#fitting-and-interpreting-geographic-regressions"><i class="fa fa-check"></i>Fitting and interpreting geographic regressions</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#mapping-incidence-and-risk-with-spatial-regression-models"><i class="fa fa-check"></i>Mapping incidence and risk with spatial regression models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html"><i class="fa fa-check"></i>Tuesday October 18, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#spatial-data-as-point-patterns"><i class="fa fa-check"></i>Spatial data as point patterns</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#working-with-point-pattern-objects-using-functions-from-the-spatstat-package"><i class="fa fa-check"></i>Working with point pattern objects using functions from the {spatstat} package</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#quantifying-event-intensity"><i class="fa fa-check"></i>Quantifying event intensity</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html"><i class="fa fa-check"></i>Thursday October 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#creating-ppp-and-owin-objects-from-simple-feature-data-frames"><i class="fa fa-check"></i>Creating <code>ppp</code> and <code>owin</code> objects from simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#estimating-spatial-intensity-as-a-function-of-distance"><i class="fa fa-check"></i>Estimating spatial intensity as a function of distance</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#intensity-trend-as-a-possible-confounding-factor"><i class="fa fa-check"></i>Intensity trend as a possible confounding factor</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html"><i class="fa fa-check"></i>Tuesday October 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#estimating-the-relative-risk-of-events"><i class="fa fa-check"></i>Estimating the relative risk of events</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#estimating-second-moment-properties-of-spatial-events"><i class="fa fa-check"></i>Estimating second-moment properties of spatial events</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html"><i class="fa fa-check"></i>Thursday October 27, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#examples-of-spatially-clustered-events"><i class="fa fa-check"></i>Examples of spatially clustered events</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#determining-the-statistical-significance-of-event-clustering"><i class="fa fa-check"></i>Determining the statistical significance of event clustering</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#estimating-event-clustering-in-multi-type-event-locations"><i class="fa fa-check"></i>Estimating event clustering in multi-type event locations</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#more-about-the-ripley-k-function"><i class="fa fa-check"></i>More about the Ripley K function</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html"><i class="fa fa-check"></i>Tuesday November 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#inferring-event-interaction-from-distance-functions"><i class="fa fa-check"></i>Inferring event interaction from distance functions</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#removing-duplicate-event-locations-and-defining-the-domain"><i class="fa fa-check"></i>Removing duplicate event locations and defining the domain</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#modeling-point-pattern-data"><i class="fa fa-check"></i>Modeling point pattern data</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#fitting-and-interpreting-an-inhibition-model"><i class="fa fa-check"></i>Fitting and interpreting an inhibition model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html"><i class="fa fa-check"></i>Thursday November 3, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#fitting-and-interpreting-a-cluster-model"><i class="fa fa-check"></i>Fitting and interpreting a cluster model</a></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#assessing-how-well-the-model-fits"><i class="fa fa-check"></i>Assessing how well the model fits</a></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#spatial-logistic-regression"><i class="fa fa-check"></i>Spatial logistic regression</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html"><i class="fa fa-check"></i>Thursday November 10, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html#spatial-data-interpolation"><i class="fa fa-check"></i>Spatial data interpolation</a></li>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html#computing-the-sample-variogram"><i class="fa fa-check"></i>Computing the sample variogram</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html"><i class="fa fa-check"></i>Tuesday November 15, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#fitting-a-variogram-model-to-the-sample-variogram"><i class="fa fa-check"></i>Fitting a variogram model to the sample variogram</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#creating-an-interpolated-surface-with-the-method-of-kriging"><i class="fa fa-check"></i>Creating an interpolated surface with the method of kriging</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html"><i class="fa fa-check"></i>Thursday November 17, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#comparing-interpolation-methods"><i class="fa fa-check"></i>Comparing interpolation methods</a></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#evaluating-the-accuracy-of-the-interpolation"><i class="fa fa-check"></i>Evaluating the accuracy of the interpolation</a></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#block-cross-validation"><i class="fa fa-check"></i>Block cross validation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html"><i class="fa fa-check"></i>Thursday November 29, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html#interpolating-to-areal-units-block-kriging"><i class="fa fa-check"></i>Interpolating to areal units (block kriging)</a></li>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html#simulating-spatial-fields"><i class="fa fa-check"></i>Simulating spatial fields</a></li>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html#interpolating-multiple-variables"><i class="fa fa-check"></i>Interpolating multiple variables</a></li>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html#machine-learning-for-spatial-interpolation"><i class="fa fa-check"></i>Machine learning for spatial interpolation</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GIS5122: Applied Spatial Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="thursday-november-3-2022" class="section level1 unnumbered hasAnchor">
<h1>Thursday November 3, 2022<a href="thursday-november-3-2022.html#thursday-november-3-2022" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>“Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday’s code.”</strong> - Christopher Thompson</p>
<p>Today</p>
<ul>
<li>Fitting and interpreting a cluster model</li>
<li>Assessing how well the model fits</li>
<li>Spatial logistic regression</li>
</ul>
<div id="fitting-and-interpreting-a-cluster-model" class="section level2 unnumbered hasAnchor">
<h2>Fitting and interpreting a cluster model<a href="thursday-november-3-2022.html#fitting-and-interpreting-a-cluster-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s compare the inhibition model fit previously to describe the Swedish pine saplings data with a cluster model for describing the Lansing Woods maple trees (in the <code>ppp</code> object called <code>lansing</code> from the {spatstat} package).</p>
<p>Start by extracting the events marked as <code>maple</code> and putting them in a separate <code>ppp</code> object called <code>MT</code>.</p>
<div class="sourceCode" id="cb1328"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1328-1"><a href="thursday-november-3-2022.html#cb1328-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(spatstat))</span>
<span id="cb1328-2"><a href="thursday-november-3-2022.html#cb1328-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(lansing)</span>
<span id="cb1328-3"><a href="thursday-november-3-2022.html#cb1328-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lansing)</span></code></pre></div>
<pre><code>## Marked planar point pattern:  2251 points
## Average intensity 2251 points per square unit (one unit = 924 feet)
## 
## *Pattern contains duplicated points*
## 
## Coordinates are given to 3 decimal places
## i.e. rounded to the nearest multiple of 0.001 units (one unit = 924 feet)
## 
## Multitype:
##          frequency proportion intensity
## blackoak       135 0.05997335       135
## hickory        703 0.31230560       703
## maple          514 0.22834300       514
## misc           105 0.04664594       105
## redoak         346 0.15370950       346
## whiteoak       448 0.19902270       448
## 
## Window: rectangle = [0, 1] x [0, 1] units
## Window area = 1 square unit
## Unit of length: 924 feet</code></pre>
<div class="sourceCode" id="cb1330"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1330-1"><a href="thursday-november-3-2022.html#cb1330-1" aria-hidden="true" tabindex="-1"></a>MT <span class="ot">&lt;-</span> lansing <span class="sc">|&gt;</span></span>
<span id="cb1330-2"><a href="thursday-november-3-2022.html#cb1330-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">subset</span>(marks <span class="sc">==</span> <span class="st">&quot;maple&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb1330-3"><a href="thursday-november-3-2022.html#cb1330-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unmark</span>()</span>
<span id="cb1330-4"><a href="thursday-november-3-2022.html#cb1330-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1330-5"><a href="thursday-november-3-2022.html#cb1330-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(MT)</span></code></pre></div>
<pre><code>## Planar point pattern:  514 points
## Average intensity 514 points per square unit (one unit = 924 feet)
## 
## Coordinates are given to 3 decimal places
## i.e. rounded to the nearest multiple of 0.001 units (one unit = 924 feet)
## 
## Window: rectangle = [0, 1] x [0, 1] units
## Window area = 1 square unit
## Unit of length: 924 feet</code></pre>
<p>There are 514 maple trees over this square region (924 x 924 square feet).</p>
<p>Plots of the tree locations and the local intensity function help you understand the first-order property of these data.</p>
<div class="sourceCode" id="cb1332"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1332-1"><a href="thursday-november-3-2022.html#cb1332-1" aria-hidden="true" tabindex="-1"></a>MT <span class="sc">|&gt;</span></span>
<span id="cb1332-2"><a href="thursday-november-3-2022.html#cb1332-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">density</span>() <span class="sc">|&gt;</span></span>
<span id="cb1332-3"><a href="thursday-november-3-2022.html#cb1332-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span>
<span id="cb1332-4"><a href="thursday-november-3-2022.html#cb1332-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1332-5"><a href="thursday-november-3-2022.html#cb1332-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(MT, <span class="at">add =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-593-1.png" width="672" /></p>
<p>There are maple trees across the southern and central parts of the study domain.</p>
<p>A plot of the <span class="math inline">\(G\)</span> function summarizes the second-order properties under the assumption of no trend.</p>
<div class="sourceCode" id="cb1333"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1333-1"><a href="thursday-november-3-2022.html#cb1333-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1333-2"><a href="thursday-november-3-2022.html#cb1333-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1333-3"><a href="thursday-november-3-2022.html#cb1333-3" aria-hidden="true" tabindex="-1"></a>G.df <span class="ot">&lt;-</span> MT <span class="sc">|&gt;</span></span>
<span id="cb1333-4"><a href="thursday-november-3-2022.html#cb1333-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Gest</span>() <span class="sc">|&gt;</span></span>
<span id="cb1333-5"><a href="thursday-november-3-2022.html#cb1333-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb1333-6"><a href="thursday-november-3-2022.html#cb1333-6" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(r <span class="sc">&lt;</span> .<span class="dv">033</span>) <span class="sc">|&gt;</span></span>
<span id="cb1333-7"><a href="thursday-november-3-2022.html#cb1333-7" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">r =</span> r <span class="sc">*</span> <span class="dv">924</span>)</span>
<span id="cb1333-8"><a href="thursday-november-3-2022.html#cb1333-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1333-9"><a href="thursday-november-3-2022.html#cb1333-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(G.df, <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> km)) <span class="sc">+</span></span>
<span id="cb1333-10"><a href="thursday-november-3-2022.html#cb1333-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb1333-11"><a href="thursday-november-3-2022.html#cb1333-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb1333-12"><a href="thursday-november-3-2022.html#cb1333-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">18</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb1333-13"><a href="thursday-november-3-2022.html#cb1333-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (ft)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;G(r): Cumulative % of events within a distance r of another maple&quot;</span>) <span class="sc">+</span></span>
<span id="cb1333-14"><a href="thursday-november-3-2022.html#cb1333-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-594-1.png" width="672" /></p>
<p>The plot provides evidence that the maple trees are clustered. The empirical curve is above the theoretical curve. For example about 74% of the maple trees are within 18 feet of another maple tree (vertical blue line). If the trees were arranged as CSR then only 49% of the trees would be within 18 feet of another maple.</p>
<p>Is the clustering due to interaction or trends (or both)?</p>
<p>You start the modeling process by investigating event interaction using a stationary Strauss model with interaction radius of .019 units (18 ft).</p>
<div class="sourceCode" id="cb1334"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1334-1"><a href="thursday-november-3-2022.html#cb1334-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ppm</span>(MT, </span>
<span id="cb1334-2"><a href="thursday-november-3-2022.html#cb1334-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">trend =</span> <span class="sc">~</span> <span class="dv">1</span>, </span>
<span id="cb1334-3"><a href="thursday-november-3-2022.html#cb1334-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">interaction =</span> <span class="fu">Strauss</span>(<span class="at">r =</span> .<span class="dv">019</span>))</span></code></pre></div>
<pre><code>## Stationary Strauss process
## 
## First order term:  beta = 344.625
## 
## Interaction distance:    0.019
## Fitted interaction parameter gamma:  1.7253743
## 
## Relevant coefficients:
## Interaction 
##    0.545444 
## 
## For standard errors, type coef(summary(x))
## 
## *** Model is not valid ***
## *** Interaction parameters are outside valid range ***</code></pre>
<p>Here the first order term beta is 345. It is the ‘latent’ rate (intensity) of maple trees per unit area. This rate is less than the 514 actual maple trees. The fitted interaction parameter (gamma) is 1.72. It is greater than one since the trees are clustered. The logarithm of gamma is positive at .545.</p>
<p>The model is interpreted as follows. The process producing the maple trees is such that you expect to see about 345 maples. Because of clustering where maple trees are more likely in the vicinity of other maple trees, the number of maples increases to the observed 514 per unit area.</p>
<p>Here the physical explanation could be event interaction. But it also could be explained by inhibition with hickory trees. You can model this using a term for cross event type interaction.</p>
<p>The Strauss process is for inhibition models. So although you use it here for diagnostics, you need to fit a cluster model (thus the <code>*** Model is not valid ***</code> warning).</p>
<p>For a cluster model the spatial intensity <span class="math display">\[\lambda(s) = \kappa \mu(s)\]</span> where <span class="math inline">\(\kappa\)</span> is the average number of clusters and where <span class="math inline">\(\mu(s)\)</span> is the spatial varying cluster size (number events per cluster).</p>
<p>Cluster models are fit using the <code>kppm()</code> function from the {spatstat} package. Here you specify the cluster process with <code>clusters = "Thomas"</code>.</p>
<p>That means each cluster consists of a Poisson number of maple trees and where each tree in the cluster is placed randomly about the ‘parent’ tree with intensity that varies inversely with distance from the parent as a Gaussian function.</p>
<div class="sourceCode" id="cb1336"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1336-1"><a href="thursday-november-3-2022.html#cb1336-1" aria-hidden="true" tabindex="-1"></a>( model.cl <span class="ot">&lt;-</span> <span class="fu">kppm</span>(MT, </span>
<span id="cb1336-2"><a href="thursday-november-3-2022.html#cb1336-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">trend =</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb1336-3"><a href="thursday-november-3-2022.html#cb1336-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">clusters =</span> <span class="st">&quot;Thomas&quot;</span>) )</span></code></pre></div>
<pre><code>## Stationary cluster point process model
## Fitted to point pattern dataset &#39;MT&#39;
## Fitted by minimum contrast
##  Summary statistic: K-function
## 
## Uniform intensity:   514
## 
## Cluster model: Thomas process
## Fitted cluster parameters:
##       kappa       scale 
## 21.74344366  0.06752959 
## Mean cluster size:  23.63931 points</code></pre>
<p>Here <span class="math inline">\(\kappa\)</span> is 21.75 and <span class="math inline">\(\bar \mu(s)\)</span> (mean cluster size) is 23.6 trees. The product of kappa and the mean cluster size is the number of events. The cluster model describes a parent-child process. The number of parents is about 22. The distribution of the parents can be described as CSR. Each parent produces about 24 offspring distributed randomly about the location of the parent within a characteristic distance. Note: The physical process might be different from the statistical process used to describe it.</p>
<p>The cluster scale parameter indicating the characteristic size (area units) of the clusters is <span class="math inline">\(\sigma^2\)</span>.</p>
<p>A <code>plot()</code> method verifies that the cluster process statistically ‘explains’ the spatial correlation.</p>
<div class="sourceCode" id="cb1338"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1338-1"><a href="thursday-november-3-2022.html#cb1338-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model.cl, </span>
<span id="cb1338-2"><a href="thursday-november-3-2022.html#cb1338-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">what =</span> <span class="st">&quot;statistic&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-597-1.png" width="672" /></p>
<p>The model (black line) is very close to the cluster process line (red dashed line). Also note that it is far from the CSR model (green line).</p>
<p>The spatial scale of the clustering is visualized with the <code>what = "cluster"</code> argument.</p>
<div class="sourceCode" id="cb1339"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1339-1"><a href="thursday-november-3-2022.html#cb1339-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model.cl, </span>
<span id="cb1339-2"><a href="thursday-november-3-2022.html#cb1339-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">what =</span> <span class="st">&quot;cluster&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-598-1.png" width="672" /></p>
<p>The color ramp is the spatial intensity (number of events per unit area) about an arbitrary single event revealing the spatial scale and extent of clustering.</p>
</div>
<div id="assessing-how-well-the-model-fits" class="section level2 unnumbered hasAnchor">
<h2>Assessing how well the model fits<a href="thursday-november-3-2022.html#assessing-how-well-the-model-fits" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Workflow in fitting spatial event location models</p>
<ul>
<li>Analyze/plot the intensity and nearest neighbor statistics</li>
<li>Select a model including trend, interaction distance, etc informed by the results of step 1</li>
<li>Choose an inhibition or cluster model</li>
<li>Fit the model to the event pattern</li>
<li>Assess how well the model fits the data by generating samples and comparing statistics from the samples with the statistics from the original data</li>
</ul>
<p>The model should be capable of generating samples of event locations that are statistically indistinguishable from the actual event locations.</p>
<p>Note: The development of spatial point process methods has largely been theory driven (not by actual problems/data). More work needs to be done to apply the theory to environmental data with spatial heterogeneity, properties at the individual level (marks), and with time information.</p>
<p>You produce samples of event locations with the <code>simulate()</code> function applied to the model object.</p>
<p>Let’s return to the Swedish pine sapling data and the inhibition model.</p>
<div class="sourceCode" id="cb1340"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1340-1"><a href="thursday-november-3-2022.html#cb1340-1" aria-hidden="true" tabindex="-1"></a>SP <span class="ot">&lt;-</span> swedishpines</span>
<span id="cb1340-2"><a href="thursday-november-3-2022.html#cb1340-2" aria-hidden="true" tabindex="-1"></a>model.in <span class="ot">&lt;-</span> <span class="fu">ppm</span>(SP, </span>
<span id="cb1340-3"><a href="thursday-november-3-2022.html#cb1340-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">trend =</span> <span class="sc">~</span> <span class="dv">1</span>, </span>
<span id="cb1340-4"><a href="thursday-november-3-2022.html#cb1340-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">interaction =</span> <span class="fu">Strauss</span>(<span class="at">r =</span> <span class="dv">10</span>), </span>
<span id="cb1340-5"><a href="thursday-november-3-2022.html#cb1340-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">rbord =</span> <span class="dv">10</span>)</span></code></pre></div>
<p>Here you generate three samples of the Swedish pine sapling data and plot them alongside the actual data for comparison.</p>
<div class="sourceCode" id="cb1341"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1341-1"><a href="thursday-november-3-2022.html#cb1341-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> model.in <span class="sc">|&gt;</span></span>
<span id="cb1341-2"><a href="thursday-november-3-2022.html#cb1341-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">simulate</span>(<span class="at">nsim =</span> <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## Generating 3 simulated patterns ...1, 2,  3.</code></pre>
<div class="sourceCode" id="cb1343"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1343-1"><a href="thursday-november-3-2022.html#cb1343-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb1343-2"><a href="thursday-november-3-2022.html#cb1343-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(SP) </span>
<span id="cb1343-3"><a href="thursday-november-3-2022.html#cb1343-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X[[<span class="dv">1</span>]])</span>
<span id="cb1343-4"><a href="thursday-november-3-2022.html#cb1343-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X[[<span class="dv">2</span>]])</span>
<span id="cb1343-5"><a href="thursday-november-3-2022.html#cb1343-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X[[<span class="dv">3</span>]])</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-600-1.png" width="672" /></p>
<p>The samples of point pattern data look similar to the actual data providing evidence that the inhibition model is adequate.</p>
<p>To quantitatively assess the similarity use the <code>envelope()</code> function that computes the <span class="math inline">\(K\)</span> function on 99 samples and the actual data. The <span class="math inline">\(K\)</span> function values are averaged over all samples and a mean line represents the best model curve. Uncertainty is assessed with a band that ranges from the minimum to the maximum K at each distance.</p>
<p>Do this with the inhibition model for the pine saplings. This takes a few seconds to complete.</p>
<div class="sourceCode" id="cb1344"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1344-1"><a href="thursday-november-3-2022.html#cb1344-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb1344-2"><a href="thursday-november-3-2022.html#cb1344-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1344-3"><a href="thursday-november-3-2022.html#cb1344-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">envelope</span>(model.in, </span>
<span id="cb1344-4"><a href="thursday-november-3-2022.html#cb1344-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">fun =</span> Kest, </span>
<span id="cb1344-5"><a href="thursday-november-3-2022.html#cb1344-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">nsim =</span> <span class="dv">99</span>, </span>
<span id="cb1344-6"><a href="thursday-november-3-2022.html#cb1344-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">correction =</span> <span class="st">&#39;border&#39;</span>), <span class="at">legend =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Generating 99 simulated realisations of fitted Gibbs model  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
## 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,  99.
## 
## Done.</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-601-1.png" width="672" /></p>
<p>The black line is the empirical (data) curve and the red line is the average over the 99 samples. The two lines are close and the black line falls nearly completely within the gray uncertainty band indicating the model fits the data well. The kink in the red curve is the result of specifying 10 units for the interaction distance.</p>
<p>From this plot you confidently conclude that a homogeneous inhibition model is adequate for describing the pine sapling data.</p>
<p>What about the model for the maple trees? The model is saved as <code>model.cl</code>.</p>
<div class="sourceCode" id="cb1346"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1346-1"><a href="thursday-november-3-2022.html#cb1346-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">envelope</span>(model.cl, </span>
<span id="cb1346-2"><a href="thursday-november-3-2022.html#cb1346-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">fun =</span> Kest, </span>
<span id="cb1346-3"><a href="thursday-november-3-2022.html#cb1346-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">nsim =</span> <span class="dv">99</span>, </span>
<span id="cb1346-4"><a href="thursday-november-3-2022.html#cb1346-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">correction =</span> <span class="st">&#39;border&#39;</span>), <span class="at">legend =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Generating 99 simulated realisations of fitted cluster model  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
## 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,  99.
## 
## Done.</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-602-1.png" width="672" /></p>
<p>In the case of the maple trees, a cluster model is adequate. However, it is not satisfying since you know about the potential for inhibition caused by the presence of hickory trees.</p>
<p>Also you saw that there were more trees in the south than in the north so the stationary assumption is suspect.</p>
<p>You fit a second cluster model where the intensity is a linear function of distance in the north-south direction.</p>
<div class="sourceCode" id="cb1348"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1348-1"><a href="thursday-november-3-2022.html#cb1348-1" aria-hidden="true" tabindex="-1"></a>model.cl2 <span class="ot">&lt;-</span> <span class="fu">kppm</span>(MT, </span>
<span id="cb1348-2"><a href="thursday-november-3-2022.html#cb1348-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">trend =</span> <span class="sc">~</span> y,</span>
<span id="cb1348-3"><a href="thursday-november-3-2022.html#cb1348-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">clusters =</span> <span class="st">&quot;Thomas&quot;</span>)</span>
<span id="cb1348-4"><a href="thursday-november-3-2022.html#cb1348-4" aria-hidden="true" tabindex="-1"></a>model.cl2</span></code></pre></div>
<pre><code>## Inhomogeneous cluster point process model
## Fitted to point pattern dataset &#39;MT&#39;
## Fitted by minimum contrast
##  Summary statistic: inhomogeneous K-function
## 
## Log intensity:  ~y
## 
## Fitted trend coefficients:
## (Intercept)           y 
##    6.894933   -1.486252 
## 
## Cluster model: Thomas process
## Fitted cluster parameters:
##     kappa     scale 
## 26.955877  0.053585 
## Mean cluster size:  [pixel image]</code></pre>
<p>This is an inhomogeneous cluster point process model. The logarithm of the intensity depends on y (<code>Log intensity:  ~y</code>). The fitted trend coefficient is negative as expected, since there are fewer trees as you move north (increasing y direction). There is one spatial unit in the north-south direction so you interpret this coefficient to mean there are 77% fewer trees in the north than in the south. The 77% comes from the formula 1 - exp(-1.486) = .77.</p>
<p>The average number of clusters (<code>kappa</code>) is higher at about 27 (it was 22 for stationary model). The cluster scale parameter (<code>sigma</code>), indicating the characteristic size of the cluster (in distance units) is lower at .0536. That makes sense since some of the event-to-event distance is accounted for by the trend term.</p>
<p>Simulate data using the new model and compare the inhomogenous <span class="math inline">\(K\)</span> function between the simulations and the observed data.</p>
<div class="sourceCode" id="cb1350"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1350-1"><a href="thursday-november-3-2022.html#cb1350-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">envelope</span>(model.cl2, </span>
<span id="cb1350-2"><a href="thursday-november-3-2022.html#cb1350-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">fun =</span> Kinhom, </span>
<span id="cb1350-3"><a href="thursday-november-3-2022.html#cb1350-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">nsim =</span> <span class="dv">99</span>,</span>
<span id="cb1350-4"><a href="thursday-november-3-2022.html#cb1350-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">correction =</span> <span class="st">&#39;border&#39;</span>), <span class="at">legend =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Generating 99 simulated realisations of fitted cluster model  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
## 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,  99.
## 
## Done.</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-604-1.png" width="672" /></p>
<p>The black line falls within the gray band and the gray band is narrower than the simulations using the homogeneous cluster model.</p>
<p>Tropical trees</p>
<p>If the intensity of events depends on spatial location as it does with the maple trees you can include a trend and covariate term in the model.</p>
<p>For a trend term, the <code>formula ~ x</code> corresponds to a spatial trend of the form <span class="math inline">\(\lambda(x) = \exp(a + bx)\)</span>, while <code>~ x + y</code> corresponds to <span class="math inline">\(\lambda(x, y) = \exp(a + bx + cy)\)</span> where <code>x</code>, <code>y</code> are the spatial coordinates. For a covariates, the formula is <code>~ covariate1 + covariate2</code>.</p>
<p>Consider the <code>bei</code> data from the {spatstat} package containing the locations of 3605 trees in a tropical rain forest.</p>
<div class="sourceCode" id="cb1352"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1352-1"><a href="thursday-november-3-2022.html#cb1352-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bei)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-605-1.png" width="672" /></p>
<p>Accompanied by covariate data giving the elevation (altitude) and slope of elevation in the study region. The data <code>bei.extra</code> is a list containing two pixel images, <code>elev</code> (elevation in meters) and <code>grad</code> (norm of elevation gradient). These pixel images are objects of class <code>im</code>, see <code>im.object</code>.</p>
<div class="sourceCode" id="cb1353"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1353-1"><a href="thursday-november-3-2022.html#cb1353-1" aria-hidden="true" tabindex="-1"></a><span class="fu">image</span>(bei.extra)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-606-1.png" width="672" /></p>
<p>Compute and plot the <span class="math inline">\(K\)</span> function on the <code>ppp</code> object <code>bei</code>.</p>
<div class="sourceCode" id="cb1354"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1354-1"><a href="thursday-november-3-2022.html#cb1354-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">envelope</span>(bei, </span>
<span id="cb1354-2"><a href="thursday-november-3-2022.html#cb1354-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">fun =</span> Kest, </span>
<span id="cb1354-3"><a href="thursday-november-3-2022.html#cb1354-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">nsim =</span> <span class="dv">39</span>, </span>
<span id="cb1354-4"><a href="thursday-november-3-2022.html#cb1354-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">global =</span> <span class="cn">TRUE</span>, </span>
<span id="cb1354-5"><a href="thursday-november-3-2022.html#cb1354-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">correction =</span> <span class="st">&quot;border&quot;</span>), </span>
<span id="cb1354-6"><a href="thursday-november-3-2022.html#cb1354-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">legend =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Generating 39 simulations of CSR  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,  39.
## 
## Done.</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-607-1.png" width="672" /></p>
<p>There is significant clustering indicated by the black line sitting far above the CSR line. There are more trees in the vicinity of other trees than expected by chance.</p>
<p>But how much of the clustering is due to variations in terrain?</p>
<p>You start by fitting a model that includes elevation and gradient as covariates without clustering. This is done with the <code>trend =</code> argument naming the image variables and including the argument <code>covariates =</code> indicating a data frame or, in this case, a list whose entries are image functions.</p>
<div class="sourceCode" id="cb1356"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1356-1"><a href="thursday-november-3-2022.html#cb1356-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">ppm</span>(bei, </span>
<span id="cb1356-2"><a href="thursday-november-3-2022.html#cb1356-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">trend =</span> <span class="sc">~</span> elev <span class="sc">+</span> grad, </span>
<span id="cb1356-3"><a href="thursday-november-3-2022.html#cb1356-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">covariates =</span> bei.extra)</span></code></pre></div>
<p>Check to see if elevation and gradient as explanatory variables are significant in the model.</p>
<div class="sourceCode" id="cb1357"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1357-1"><a href="thursday-november-3-2022.html#cb1357-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div>
<pre><code>## Point process model
## Fitting method: maximum likelihood (Berman-Turner approximation)
## Model was fitted using glm()
## Algorithm converged
## Call:
## ppm.ppp(Q = bei, trend = ~elev + grad, covariates = bei.extra)
## Edge correction: &quot;border&quot;
##  [border correction distance r = 0 ]
## --------------------------------------------------------------------------------
## Quadrature scheme (Berman-Turner) = data + dummy + weights
## 
## Data pattern:
## Planar point pattern:  3604 points
## Average intensity 0.00721 points per square metre
## Window: rectangle = [0, 1000] x [0, 500] metres
## Window area = 5e+05 square metres
## Unit of length: 1 metre
## 
## Dummy quadrature points:
##      130 x 130 grid of dummy points, plus 4 corner points
##      dummy spacing: 7.692308 x 3.846154 metres
## 
## Original dummy parameters: =
## Planar point pattern:  16904 points
## Average intensity 0.0338 points per square metre
## Window: rectangle = [0, 1000] x [0, 500] metres
## Window area = 5e+05 square metres
## Unit of length: 1 metre
## Quadrature weights:
##      (counting weights based on 130 x 130 array of rectangular tiles)
## All weights:
##  range: [1.64, 29.6] total: 5e+05
## Weights on data points:
##  range: [1.64, 14.8] total: 41000
## Weights on dummy points:
##  range: [1.64, 29.6] total: 459000
## --------------------------------------------------------------------------------
## FITTED MODEL:
## 
## Nonstationary Poisson process
## 
## ---- Intensity: ----
## 
## Log intensity: ~elev + grad
## Model depends on external covariates &#39;elev&#39; and &#39;grad&#39;
## Covariates provided:
##  elev: im
##  grad: im
## 
## Fitted trend coefficients:
## (Intercept)        elev        grad 
## -8.56355220  0.02143995  5.84646680 
## 
##                Estimate        S.E.     CI95.lo     CI95.hi Ztest       Zval
## (Intercept) -8.56355220 0.341113849 -9.23212306 -7.89498134   *** -25.104675
## elev         0.02143995 0.002287866  0.01695581  0.02592408   ***   9.371155
## grad         5.84646680 0.255781018  5.34514522  6.34778838   ***  22.857313
## 
## ----------- gory details -----
## 
## Fitted regular parameters (theta):
## (Intercept)        elev        grad 
## -8.56355220  0.02143995  5.84646680 
## 
## Fitted exp(theta):
##  (Intercept)         elev         grad 
## 1.909398e-04 1.021671e+00 3.460097e+02</code></pre>
<p>The output shows that both elevation and elevation gradient are significant in explaining the spatial varying intensity of the trees.</p>
<p>Since the conditional intensity is on a log scale you interpret the elevation coefficient as follows: For a one meter increase in elevation the local spatial intensity increases by a amount equal to exp(.021) or 2%.</p>
<p>Check how well the model fits the data. Again this is done with the <code>envelope()</code> function using the model object as the first argument.</p>
<div class="sourceCode" id="cb1359"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1359-1"><a href="thursday-november-3-2022.html#cb1359-1" aria-hidden="true" tabindex="-1"></a>E <span class="ot">&lt;-</span> <span class="fu">envelope</span>(model1, </span>
<span id="cb1359-2"><a href="thursday-november-3-2022.html#cb1359-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">fun =</span> Kest, </span>
<span id="cb1359-3"><a href="thursday-november-3-2022.html#cb1359-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">nsim =</span> <span class="dv">39</span>,</span>
<span id="cb1359-4"><a href="thursday-november-3-2022.html#cb1359-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">correction =</span> <span class="st">&quot;border&quot;</span>,</span>
<span id="cb1359-5"><a href="thursday-november-3-2022.html#cb1359-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">global =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Generating 78 simulated realisations of fitted Poisson model (39 to estimate 
## the mean and 39 to calculate envelopes) ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,  78.
## 
## Done.</code></pre>
<div class="sourceCode" id="cb1361"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1361-1"><a href="thursday-november-3-2022.html#cb1361-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(E, <span class="at">main =</span> <span class="st">&quot;Inhomogeneous Poisson Model&quot;</span>, </span>
<span id="cb1361-2"><a href="thursday-november-3-2022.html#cb1361-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">legend =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-610-1.png" width="672" /></p>
<p>You conclude that although elevation and elevation slope are significant in explaining the spatial distribution of trees, they do not explain all the clustering.</p>
<p>An improvement is made by adding a cluster process to the model. This is done with the function <code>kppm()</code>.</p>
<div class="sourceCode" id="cb1362"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1362-1"><a href="thursday-november-3-2022.html#cb1362-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">kppm</span>(bei, </span>
<span id="cb1362-2"><a href="thursday-november-3-2022.html#cb1362-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">trend =</span> <span class="sc">~</span> elev <span class="sc">+</span> grad, </span>
<span id="cb1362-3"><a href="thursday-november-3-2022.html#cb1362-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">covariates =</span> bei.extra, </span>
<span id="cb1362-4"><a href="thursday-november-3-2022.html#cb1362-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">clusters =</span> <span class="st">&quot;Thomas&quot;</span>)</span>
<span id="cb1362-5"><a href="thursday-november-3-2022.html#cb1362-5" aria-hidden="true" tabindex="-1"></a>E <span class="ot">&lt;-</span> <span class="fu">envelope</span>(model2, Lest, <span class="at">nsim =</span> <span class="dv">39</span>, </span>
<span id="cb1362-6"><a href="thursday-november-3-2022.html#cb1362-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">global =</span> <span class="cn">TRUE</span>, </span>
<span id="cb1362-7"><a href="thursday-november-3-2022.html#cb1362-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">correction =</span> <span class="st">&quot;border&quot;</span>)</span></code></pre></div>
<pre><code>## Generating 78 simulated realisations of fitted cluster model (39 to estimate 
## the mean and 39 to calculate envelopes) ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,  78.
## 
## Done.</code></pre>
<div class="sourceCode" id="cb1364"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1364-1"><a href="thursday-november-3-2022.html#cb1364-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(E, <span class="at">main =</span> <span class="st">&quot;Clustered Inhomogeneous Model&quot;</span>, <span class="at">legend =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-611-1.png" width="672" /></p>
<p>The uncertainty band is much wider. The empirical curve fits completely inside the band so you conclude that an inhomogeneous cluster process appears to be an adequate description of the point pattern data.</p>
<p>Violent tornadoes</p>
<p>The vast majority of tornadoes have winds of less than 60 m/s (120 mph). A violent tornado, with winds exceeding 90 m/s, is rare. Most of these potentially destructive and deadly tornadoes occur from rotating thunderstorms called supercells, with formation contingent on local (storm-scale) meteorological conditions.</p>
<p>The long-term risk of a tornado at a given location is assessed using historical records, however, the rarity of the most violent tornadoes make these rate estimates unstable. Here you use the more stable rate estimates from the larger set of less violent tornadoes to create more reliable estimates of violent tornado frequency.</p>
<p>For this exercise attention is restricted to tornadoes occurring in Kansas over the period 1954–2020.</p>
<div class="sourceCode" id="cb1365"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1365-1"><a href="thursday-november-3-2022.html#cb1365-1" aria-hidden="true" tabindex="-1"></a>Torn.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="at">dsn =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;1950-2020-torn-initpoint&quot;</span>)) <span class="sc">|&gt;</span></span>
<span id="cb1365-2"><a href="thursday-november-3-2022.html#cb1365-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3082</span>) <span class="sc">|&gt;</span></span>
<span id="cb1365-3"><a href="thursday-november-3-2022.html#cb1365-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(mag <span class="sc">&gt;=</span> <span class="dv">0</span>, yr <span class="sc">&gt;=</span> <span class="dv">1954</span>) <span class="sc">|&gt;</span></span>
<span id="cb1365-4"><a href="thursday-november-3-2022.html#cb1365-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">EF =</span> mag,</span>
<span id="cb1365-5"><a href="thursday-november-3-2022.html#cb1365-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">EFf =</span> <span class="fu">as.factor</span>(EF)) <span class="sc">|&gt;</span></span>
<span id="cb1365-6"><a href="thursday-november-3-2022.html#cb1365-6" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(yr, EF, EFf)</span></code></pre></div>
<pre><code>## Reading layer `1950-2020-torn-initpoint&#39; from data source 
##   `/Users/jelsner/Desktop/ClassNotes/ASS-2022/data/1950-2020-torn-initpoint&#39; 
##   using driver `ESRI Shapefile&#39;
## Simple feature collection with 66244 features and 22 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -163.53 ymin: 17.7212 xmax: -64.7151 ymax: 61.02
## Geodetic CRS:  WGS 84</code></pre>
<div class="sourceCode" id="cb1367"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1367-1"><a href="thursday-november-3-2022.html#cb1367-1" aria-hidden="true" tabindex="-1"></a>W.sfc <span class="ot">&lt;-</span> USAboundaries<span class="sc">::</span><span class="fu">us_states</span>(<span class="at">states =</span> <span class="st">&quot;Kansas&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb1367-2"><a href="thursday-november-3-2022.html#cb1367-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> sf<span class="sc">::</span><span class="fu">st_crs</span>(Torn.sf)) <span class="sc">|&gt;</span></span>
<span id="cb1367-3"><a href="thursday-november-3-2022.html#cb1367-3" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_geometry</span>()</span>
<span id="cb1367-4"><a href="thursday-november-3-2022.html#cb1367-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1367-5"><a href="thursday-november-3-2022.html#cb1367-5" aria-hidden="true" tabindex="-1"></a>Torn.sf <span class="ot">&lt;-</span> Torn.sf[W.sfc, ]</span></code></pre></div>
<p>Create a <code>owin</code> and <code>ppp</code> objects. Note that although you already subset by Kansas tornadoes above you need to subset on the <code>ppp</code> object to assign the KS boundary as the analysis window.</p>
<div class="sourceCode" id="cb1368"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1368-1"><a href="thursday-november-3-2022.html#cb1368-1" aria-hidden="true" tabindex="-1"></a>KS.win <span class="ot">&lt;-</span> W.sfc <span class="sc">|&gt;</span></span>
<span id="cb1368-2"><a href="thursday-november-3-2022.html#cb1368-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.owin</span>()</span>
<span id="cb1368-3"><a href="thursday-november-3-2022.html#cb1368-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1368-4"><a href="thursday-november-3-2022.html#cb1368-4" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="ot">&lt;-</span> Torn.sf[<span class="st">&quot;EF&quot;</span>] <span class="sc">|&gt;</span></span>
<span id="cb1368-5"><a href="thursday-november-3-2022.html#cb1368-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.ppp</span>()</span>
<span id="cb1368-6"><a href="thursday-november-3-2022.html#cb1368-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1368-7"><a href="thursday-november-3-2022.html#cb1368-7" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="ot">&lt;-</span> T.ppp[KS.win]</span>
<span id="cb1368-8"><a href="thursday-november-3-2022.html#cb1368-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1368-9"><a href="thursday-november-3-2022.html#cb1368-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(T.ppp)</span></code></pre></div>
<pre><code>## Marked planar point pattern:  4139 points
## Average intensity 1.918005e-08 points per square unit
## 
## *Pattern contains duplicated points*
## 
## Coordinates are given to 1 decimal place
## i.e. rounded to the nearest multiple of 0.1 units
## 
## marks are numeric, of type &#39;double&#39;
## Summary:
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0000  0.0000  0.0000  0.6139  1.0000  5.0000 
## 
## Window: polygonal boundary
## single connected closed polygon with 169 vertices
## enclosing rectangle: [1317675.9, 1980294.8] x [7114969, 7458570] units
##                      (662600 x 343600 units)
## Window area = 2.15797e+11 square units
## Fraction of frame area: 0.948</code></pre>
<p>There are 4139 tornadoes over the period with an average intensity of 192 per 100 square kilometer (multiply the average intensity in square meters by 10^10).</p>
<p>Separate the point pattern data into non-violent tornadoes and violent tornadoes. The non-violent tornadoes include those with an EF rating of 0, 1, 2 or 3. The violent tornadoes include those with an EF rating of 4 or 5.</p>
<div class="sourceCode" id="cb1370"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1370-1"><a href="thursday-november-3-2022.html#cb1370-1" aria-hidden="true" tabindex="-1"></a>NV.ppp <span class="ot">&lt;-</span> T.ppp <span class="sc">|&gt;</span></span>
<span id="cb1370-2"><a href="thursday-november-3-2022.html#cb1370-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">subset</span>(marks <span class="sc">&lt;=</span> <span class="dv">3</span> <span class="sc">&amp;</span> marks <span class="sc">&gt;=</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb1370-3"><a href="thursday-november-3-2022.html#cb1370-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unmark</span>()</span>
<span id="cb1370-4"><a href="thursday-november-3-2022.html#cb1370-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1370-5"><a href="thursday-november-3-2022.html#cb1370-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(NV.ppp)</span></code></pre></div>
<pre><code>## Planar point pattern:  4098 points
## Average intensity 1.899006e-08 points per square unit
## 
## *Pattern contains duplicated points*
## 
## Coordinates are given to 1 decimal place
## i.e. rounded to the nearest multiple of 0.1 units
## 
## Window: polygonal boundary
## single connected closed polygon with 169 vertices
## enclosing rectangle: [1317675.9, 1980294.8] x [7114969, 7458570] units
##                      (662600 x 343600 units)
## Window area = 2.15797e+11 square units
## Fraction of frame area: 0.948</code></pre>
<div class="sourceCode" id="cb1372"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1372-1"><a href="thursday-november-3-2022.html#cb1372-1" aria-hidden="true" tabindex="-1"></a>V.ppp <span class="ot">&lt;-</span> T.ppp <span class="sc">|&gt;</span></span>
<span id="cb1372-2"><a href="thursday-november-3-2022.html#cb1372-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">subset</span>(marks <span class="sc">&gt;=</span> <span class="dv">4</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1372-3"><a href="thursday-november-3-2022.html#cb1372-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unmark</span>()</span>
<span id="cb1372-4"><a href="thursday-november-3-2022.html#cb1372-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1372-5"><a href="thursday-november-3-2022.html#cb1372-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(V.ppp)</span></code></pre></div>
<pre><code>## Planar point pattern:  41 points
## Average intensity 1.899933e-10 points per square unit
## 
## Coordinates are given to 1 decimal place
## i.e. rounded to the nearest multiple of 0.1 units
## 
## Window: polygonal boundary
## single connected closed polygon with 169 vertices
## enclosing rectangle: [1317675.9, 1980294.8] x [7114969, 7458570] units
##                      (662600 x 343600 units)
## Window area = 2.15797e+11 square units
## Fraction of frame area: 0.948</code></pre>
<p>The spatial intensity of the non-violent tornadoes is 190 per 100 sq km. The spatial intensity of the violent tornadoes is 1.9 per 100 square kilometer.</p>
<p>Plot the locations of the violent tornado events.</p>
<div class="sourceCode" id="cb1374"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1374-1"><a href="thursday-november-3-2022.html#cb1374-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(V.ppp)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-615-1.png" width="672" /></p>
<p>Early we found that the spatial intensity of tornado reports was a function of distance to nearest city.</p>
<p>So here you include this as an explanatory variable. Import the data, set the CRS, and transform the CRS to match that of the tornadoes. Exclude cities with fewer than 1000 people.</p>
<div class="sourceCode" id="cb1375"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1375-1"><a href="thursday-november-3-2022.html#cb1375-1" aria-hidden="true" tabindex="-1"></a>C.sf <span class="ot">&lt;-</span> USAboundaries<span class="sc">::</span><span class="fu">us_cities</span>() <span class="sc">|&gt;</span></span>
<span id="cb1375-2"><a href="thursday-november-3-2022.html#cb1375-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(population <span class="sc">&gt;=</span> <span class="dv">1000</span>) <span class="sc">|&gt;</span></span>
<span id="cb1375-3"><a href="thursday-november-3-2022.html#cb1375-3" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> sf<span class="sc">::</span><span class="fu">st_crs</span>(Torn.sf))</span></code></pre></div>
<pre><code>## City populations for contemporary data come from the 2010 census.</code></pre>
<p>Then convert the simple feature data frame to a <code>ppp</code> object. Then subset the events by the analysis window (Kansas border).</p>
<div class="sourceCode" id="cb1377"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1377-1"><a href="thursday-november-3-2022.html#cb1377-1" aria-hidden="true" tabindex="-1"></a>C.ppp <span class="ot">&lt;-</span> C.sf <span class="sc">|&gt;</span></span>
<span id="cb1377-2"><a href="thursday-november-3-2022.html#cb1377-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.ppp</span>()</span></code></pre></div>
<pre><code>## Warning in as.ppp.sf(C.sf): only first attribute column is used for marks</code></pre>
<div class="sourceCode" id="cb1379"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1379-1"><a href="thursday-november-3-2022.html#cb1379-1" aria-hidden="true" tabindex="-1"></a>C.ppp <span class="ot">&lt;-</span> C.ppp[KS.win] <span class="sc">|&gt;</span></span>
<span id="cb1379-2"><a href="thursday-november-3-2022.html#cb1379-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unmark</span>()</span>
<span id="cb1379-3"><a href="thursday-november-3-2022.html#cb1379-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1379-4"><a href="thursday-november-3-2022.html#cb1379-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(C.ppp)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-617-1.png" width="672" /></p>
<p>Next create a distance map of the city locations using the <code>distmap()</code> function.</p>
<div class="sourceCode" id="cb1380"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1380-1"><a href="thursday-november-3-2022.html#cb1380-1" aria-hidden="true" tabindex="-1"></a>Zc <span class="ot">&lt;-</span> <span class="fu">distmap</span>(C.ppp)</span>
<span id="cb1380-2"><a href="thursday-november-3-2022.html#cb1380-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Zc)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-618-1.png" width="672" /></p>
<p>The pixel values of the <code>im</code> object are distances is meters. Blue indicates locations that are less than 20 km from a city.</p>
<p>Interest lies with the distance to nearest non-violent tornado. You check to see if this might be a useful variable in a model so you make a distance map for the non-violent events and then use the <code>rhohat()</code> function.</p>
<div class="sourceCode" id="cb1381"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1381-1"><a href="thursday-november-3-2022.html#cb1381-1" aria-hidden="true" tabindex="-1"></a>Znv <span class="ot">&lt;-</span> <span class="fu">distmap</span>(NV.ppp)</span>
<span id="cb1381-2"><a href="thursday-november-3-2022.html#cb1381-2" aria-hidden="true" tabindex="-1"></a>rhat <span class="ot">&lt;-</span> <span class="fu">rhohat</span>(V.ppp, Znv, </span>
<span id="cb1381-3"><a href="thursday-november-3-2022.html#cb1381-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">adjust =</span> <span class="fl">1.5</span>, </span>
<span id="cb1381-4"><a href="thursday-november-3-2022.html#cb1381-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">smoother =</span> <span class="st">&quot;kernel&quot;</span>, </span>
<span id="cb1381-5"><a href="thursday-november-3-2022.html#cb1381-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">method =</span> <span class="st">&quot;transform&quot;</span>)</span>
<span id="cb1381-6"><a href="thursday-november-3-2022.html#cb1381-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1381-7"><a href="thursday-november-3-2022.html#cb1381-7" aria-hidden="true" tabindex="-1"></a>dist <span class="ot">&lt;-</span> rhat<span class="sc">$</span>Znv</span>
<span id="cb1381-8"><a href="thursday-november-3-2022.html#cb1381-8" aria-hidden="true" tabindex="-1"></a>rho <span class="ot">&lt;-</span> rhat<span class="sc">$</span>rho</span>
<span id="cb1381-9"><a href="thursday-november-3-2022.html#cb1381-9" aria-hidden="true" tabindex="-1"></a>hi <span class="ot">&lt;-</span> rhat<span class="sc">$</span>hi</span>
<span id="cb1381-10"><a href="thursday-november-3-2022.html#cb1381-10" aria-hidden="true" tabindex="-1"></a>lo <span class="ot">&lt;-</span> rhat<span class="sc">$</span>lo</span>
<span id="cb1381-11"><a href="thursday-november-3-2022.html#cb1381-11" aria-hidden="true" tabindex="-1"></a>Rho.df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">dist =</span> dist, <span class="at">rho =</span> rho, <span class="at">hi =</span> hi, <span class="at">lo =</span> lo)</span>
<span id="cb1381-12"><a href="thursday-november-3-2022.html#cb1381-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1381-13"><a href="thursday-november-3-2022.html#cb1381-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Rho.df) <span class="sc">+</span> </span>
<span id="cb1381-14"><a href="thursday-november-3-2022.html#cb1381-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">x =</span> dist, <span class="at">ymin =</span> lo, <span class="at">ymax =</span> hi), <span class="at">alpha =</span> .<span class="dv">3</span>) <span class="sc">+</span> </span>
<span id="cb1381-15"><a href="thursday-november-3-2022.html#cb1381-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> dist, <span class="at">y =</span> rho), <span class="at">col =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span> </span>
<span id="cb1381-16"><a href="thursday-november-3-2022.html#cb1381-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Spatial intensity of violent tornadoes&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Distance from nearest non-violent tornado (m)&quot;</span>) <span class="sc">+</span> </span>
<span id="cb1381-17"><a href="thursday-november-3-2022.html#cb1381-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-619-1.png" width="672" /></p>
<p>This shows that regions that get non-violent tornadoes also see higher rates of violent tornadoes.</p>
<p>So the model should include two covariates (trend terms), distance to nearest city and distance to nearest non-violent tornado.</p>
<div class="sourceCode" id="cb1382"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1382-1"><a href="thursday-november-3-2022.html#cb1382-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">ppm</span>(V.ppp, </span>
<span id="cb1382-2"><a href="thursday-november-3-2022.html#cb1382-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">trend =</span> <span class="sc">~</span> Zc <span class="sc">+</span> Znv, </span>
<span id="cb1382-3"><a href="thursday-november-3-2022.html#cb1382-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">covariates =</span> <span class="fu">list</span>(<span class="at">Zc =</span> Zc, <span class="at">Znv =</span> Znv))</span>
<span id="cb1382-4"><a href="thursday-november-3-2022.html#cb1382-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1382-5"><a href="thursday-november-3-2022.html#cb1382-5" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(model1))</span></code></pre></div>
<pre><code>##                  Estimate         S.E.       CI95.lo       CI95.hi Ztest
## (Intercept) -2.079665e+01 3.689920e-01 -2.151986e+01 -2.007344e+01   ***
## Zc          -3.213231e-05 1.118327e-05 -5.405111e-05 -1.021350e-05    **
## Znv         -2.235788e-04 8.585891e-05 -3.918592e-04 -5.529845e-05    **
##                   Zval
## (Intercept) -56.360705
## Zc           -2.873248
## Znv          -2.604026</code></pre>
<p>As expected the model shows fewer violent tornadoes with increasing distance from the nearest city (negative coefficient on <code>Zc</code>) and fewer violent tornadoes with increasing distance from a non-violent tornado (negative coefficient on <code>Znv</code>).</p>
<p>Since the spatial unit is meters the coefficient of -3.06e-05 is interpreted as a [1 - exp(-.0306)] * 100% or 3% decrease in violent tornado reports per kilometer of distance from a city. Similarly the coefficient on distance from nearest non-violent tornado is interpreted as a 23% decrease in violent tornado reports per kilometer of distance from nearest non-violent tornado.</p>
<p>Check if there is any residual nearest neighbor correlation.</p>
<div class="sourceCode" id="cb1384"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1384-1"><a href="thursday-november-3-2022.html#cb1384-1" aria-hidden="true" tabindex="-1"></a>E <span class="ot">&lt;-</span> <span class="fu">envelope</span>(model1, </span>
<span id="cb1384-2"><a href="thursday-november-3-2022.html#cb1384-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">fun =</span> Kest, </span>
<span id="cb1384-3"><a href="thursday-november-3-2022.html#cb1384-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">nsim =</span> <span class="dv">39</span>,</span>
<span id="cb1384-4"><a href="thursday-november-3-2022.html#cb1384-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">global =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Generating 78 simulated realisations of fitted Poisson model (39 to estimate 
## the mean and 39 to calculate envelopes) ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,  78.
## 
## Done.</code></pre>
<div class="sourceCode" id="cb1386"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1386-1"><a href="thursday-november-3-2022.html#cb1386-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(E, <span class="at">main =</span> <span class="st">&quot;Inhomogeneous Poisson Model&quot;</span>, <span class="at">legend =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-621-1.png" width="672" /></p>
<p>There appears to be a bit of regularity at smaller scales. The empirical curve (black line) falls slightly below the model (dashed red line). There are fewer nearby violent tornadoes than one would expect.</p>
<p>To see if this is statistically significant, you add an inhibition process to the model.</p>
<div class="sourceCode" id="cb1387"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1387-1"><a href="thursday-november-3-2022.html#cb1387-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">ppm</span>(V.ppp, </span>
<span id="cb1387-2"><a href="thursday-november-3-2022.html#cb1387-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">trend =</span> <span class="sc">~</span> Zc <span class="sc">+</span> Znv, </span>
<span id="cb1387-3"><a href="thursday-november-3-2022.html#cb1387-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">covariates =</span> <span class="fu">list</span>(<span class="at">Zc =</span> Zc, <span class="at">Znv =</span> Znv),</span>
<span id="cb1387-4"><a href="thursday-november-3-2022.html#cb1387-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">interaction =</span> <span class="fu">Strauss</span>(<span class="at">r =</span> <span class="dv">40000</span>))</span>
<span id="cb1387-5"><a href="thursday-november-3-2022.html#cb1387-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1387-6"><a href="thursday-november-3-2022.html#cb1387-6" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(model2))</span></code></pre></div>
<pre><code>##                  Estimate         S.E.       CI95.lo       CI95.hi Ztest
## (Intercept) -1.999626e+01 0.6389281922 -2.124853e+01 -1.874398e+01   ***
## Zc          -4.125674e-05 0.0000129859 -6.670864e-05 -1.580484e-05    **
## Znv         -2.325491e-04 0.0001163074 -4.605075e-04 -4.590757e-06     *
## Interaction -6.232454e-01 0.3926001130 -1.392727e+00  1.462367e-01      
##                   Zval
## (Intercept) -31.296564
## Zc           -3.177041
## Znv          -1.999435
## Interaction  -1.587481</code></pre>
<p>The interaction coefficient has a negative sign as expected from the above plot, but the standard error is relatively large so it is not significant.</p>
<p>Remove the inhibition process and add a trend term in the east-west direction.</p>
<div class="sourceCode" id="cb1389"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1389-1"><a href="thursday-november-3-2022.html#cb1389-1" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">ppm</span>(V.ppp, </span>
<span id="cb1389-2"><a href="thursday-november-3-2022.html#cb1389-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">trend =</span> <span class="sc">~</span> Zc <span class="sc">+</span> Znv <span class="sc">+</span> x, </span>
<span id="cb1389-3"><a href="thursday-november-3-2022.html#cb1389-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">covariates =</span> <span class="fu">list</span>(<span class="at">Zc =</span> Zc, <span class="at">Znv =</span> Znv))</span>
<span id="cb1389-4"><a href="thursday-november-3-2022.html#cb1389-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1389-5"><a href="thursday-november-3-2022.html#cb1389-5" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(model3))</span></code></pre></div>
<pre><code>##                  Estimate         S.E.       CI95.lo       CI95.hi Ztest
## (Intercept) -2.381531e+01 1.891801e+00 -2.752317e+01 -2.010745e+01   ***
## Zc          -2.274246e-05 1.255697e-05 -4.735366e-05  1.868739e-06      
## Znv         -2.379710e-04 8.651254e-05 -4.075324e-04 -6.840952e-05    **
## x            1.681064e-06 1.020308e-06 -3.187026e-07  3.680830e-06      
##                   Zval
## (Intercept) -12.588694
## Zc           -1.811143
## Znv          -2.750711
## x             1.647605</code></pre>
<p>There is a significant eastward trend but it appears to confound the distance to city term. Why is this?</p>
<p>Plot simulated data.</p>
<div class="sourceCode" id="cb1391"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1391-1"><a href="thursday-november-3-2022.html#cb1391-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(V.ppp)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-624-1.png" width="672" /></p>
<div class="sourceCode" id="cb1392"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1392-1"><a href="thursday-november-3-2022.html#cb1392-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">simulate</span>(model1, <span class="at">nsim =</span> <span class="dv">6</span>))</span></code></pre></div>
<pre><code>## Generating 6 simulated patterns ...1, 2, 3, 4, 5,  6.</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-624-2.png" width="672" /></p>
<p>Model one appears to due a good job simulating data that looks like the actual data.</p>
</div>
<div id="spatial-logistic-regression" class="section level2 unnumbered hasAnchor">
<h2>Spatial logistic regression<a href="thursday-november-3-2022.html#spatial-logistic-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Spatial logistic regression is a popular model for point pattern data. The study domain is divided into a grid of cells; each cell is assigned the value one if it contains at least one event, and zero otherwise.</p>
<p>Then a logistic regression models the presence probability <span class="math inline">\(p = P(Y = 1)\)</span> as a function of explanatory variables <span class="math inline">\(X\)</span> in the (matrix) form <span class="math display">\[
\log \frac{p}{1-p} = \beta X
\]</span> where the left-hand side is the logit (log of the odds ratio) and the <span class="math inline">\(\beta\)</span> are the coefficients to be determined.</p>
<p>If your data are stored as <code>ppp</code> objects, a spatial logistic model can be fit directly using functions from the {spatstat} package.</p>
<p>Let’s consider an example from the package (a good strategy in general when learning a new technique).</p>
<p>Consider the locations of 57 copper ore deposits (events) and 146 line segments representing geological ‘lineaments.’ Lineaments are linear features that consist of geological faults.</p>
<p>It is of interest to be able to predict the probability of a copper ore from the lineament pattern. The data are stored as a list in <code>copper</code>. The list contains a <code>ppp</code> object for the ore deposits and a <code>psp</code> object for the lineaments.</p>
<div class="sourceCode" id="cb1394"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1394-1"><a href="thursday-november-3-2022.html#cb1394-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(copper)</span>
<span id="cb1394-2"><a href="thursday-november-3-2022.html#cb1394-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(copper<span class="sc">$</span>SouthPoints)</span>
<span id="cb1394-3"><a href="thursday-november-3-2022.html#cb1394-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(copper<span class="sc">$</span>SouthLines, <span class="at">add =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-625-1.png" width="672" /></p>
<p>For convenience you first rotate the events (points and lines) by 90 degrees in the anticlockwise direction and save them as separate objects.</p>
<div class="sourceCode" id="cb1395"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1395-1"><a href="thursday-november-3-2022.html#cb1395-1" aria-hidden="true" tabindex="-1"></a>C <span class="ot">&lt;-</span> <span class="fu">rotate</span>(copper<span class="sc">$</span>SouthPoints, pi<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb1395-2"><a href="thursday-november-3-2022.html#cb1395-2" aria-hidden="true" tabindex="-1"></a>L <span class="ot">&lt;-</span> <span class="fu">rotate</span>(copper<span class="sc">$</span>SouthLines, pi<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb1395-3"><a href="thursday-november-3-2022.html#cb1395-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(C)</span>
<span id="cb1395-4"><a href="thursday-november-3-2022.html#cb1395-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(L, <span class="at">add =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-626-1.png" width="672" /></p>
<p>You summarize the planar point pattern data object <code>C</code>.</p>
<div class="sourceCode" id="cb1396"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1396-1"><a href="thursday-november-3-2022.html#cb1396-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(C)</span></code></pre></div>
<pre><code>## Planar point pattern:  57 points
## Average intensity 0.01020691 points per square km
## 
## Coordinates are given to 2 decimal places
## i.e. rounded to the nearest multiple of 0.01 km
## 
## Window: rectangle = [-158.233, -0.19] x [-0.335, 35] km
##                     (158 x 35.34 km)
## Window area = 5584.45 square km
## Unit of length: 1 km</code></pre>
<p>There are 57 ore deposits over a region of size 5584 square km resulting in an intensity of about .01 ore deposits per square km.</p>
<p>Next you create a distance map of the lineaments to be used as a covariate.</p>
<div class="sourceCode" id="cb1398"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1398-1"><a href="thursday-november-3-2022.html#cb1398-1" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> <span class="fu">distmap</span>(L)</span>
<span id="cb1398-2"><a href="thursday-november-3-2022.html#cb1398-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(D)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-628-1.png" width="672" /></p>
<p>Spatial logistic regression models are fit with the <code>slrm()</code> function from the {spatstat} package.</p>
<div class="sourceCode" id="cb1399"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1399-1"><a href="thursday-november-3-2022.html#cb1399-1" aria-hidden="true" tabindex="-1"></a>model.slr <span class="ot">&lt;-</span> <span class="fu">slrm</span>(C <span class="sc">~</span> D)</span>
<span id="cb1399-2"><a href="thursday-november-3-2022.html#cb1399-2" aria-hidden="true" tabindex="-1"></a>model.slr</span></code></pre></div>
<pre><code>## Fitted spatial logistic regression model
## Formula: C ~ D
## Fitted coefficients:
## (Intercept)           D 
## -4.72337865  0.07811134</code></pre>
<p>The model says that the odds of a copper ore along a lineament (D = 0) is exp(-4.723) = .00888. This is slightly less than the overall intensity of .01.</p>
<p>The model also says that for every one unit (one kilometer) increase in distance from a lineament the expected change in the log odds is .0781 [exp(.0781) = 1.0812] or an 8.1% increase in the odds. Ore deposits are more likely between the lineaments.</p>
<p>The fitted method produces an image (raster) of the window giving the local probability of an ore deposit. The values are the probability of a random ore deposit in each pixel.</p>
<div class="sourceCode" id="cb1401"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1401-1"><a href="thursday-november-3-2022.html#cb1401-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(model.slr))</span>
<span id="cb1401-2"><a href="thursday-november-3-2022.html#cb1401-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(C, <span class="at">add =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-630-1.png" width="672" /></p>
<p>Integrating the predictions over the area equals the observed number of ore deposits.</p>
<div class="sourceCode" id="cb1402"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1402-1"><a href="thursday-november-3-2022.html#cb1402-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">fitted</span>(model.slr))</span></code></pre></div>
<pre><code>## [1] 57</code></pre>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tuesday-november-1-2022.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="thursday-november-10-2022.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
