<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Thursday September 29, 2022 | GIS5122: Applied Spatial Statistics</title>
  <meta name="description" content="Thursday September 29, 2022 | GIS5122: Applied Spatial Statistics" />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="Thursday September 29, 2022 | GIS5122: Applied Spatial Statistics" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="jelsner/ASS-2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Thursday September 29, 2022 | GIS5122: Applied Spatial Statistics" />
  
  
  

<meta name="author" content="James B. Elsner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tuesday-september-27-2022.html"/>
<link rel="next" href="tuesday-october-4-2022.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied Spatial Statistics</a></li>

<li class="divider"></li>
<li><a href="index.html#section"></a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i>Syllabus</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#gis5122-applied-spatial-statistics"><i class="fa fa-check"></i>GIS5122: Applied Spatial Statistics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#contact-information"><i class="fa fa-check"></i>Contact information</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#course-description"><i class="fa fa-check"></i>Course description</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#expected-learning-outcomes"><i class="fa fa-check"></i>Expected learning outcomes</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#materials"><i class="fa fa-check"></i>Materials</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#class-meetings"><i class="fa fa-check"></i>Class meetings</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#grades"><i class="fa fa-check"></i>Grades</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#ethics"><i class="fa fa-check"></i>Ethics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#outline-of-topics"><i class="fa fa-check"></i>Outline of topics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#schedule-subject-to-change-with-notice"><i class="fa fa-check"></i>Schedule (subject to change with notice)</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#reference-materials"><i class="fa fa-check"></i>Reference materials</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#reproducible-research"><i class="fa fa-check"></i>Reproducible research</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html"><i class="fa fa-check"></i>Tuesday, August 23, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#install-r-and-rstudio-on-your-computer"><i class="fa fa-check"></i>Install R and RStudio on your computer</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#download-course-materials"><i class="fa fa-check"></i>Download course materials</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#read-the-syllabus"><i class="fa fa-check"></i>Read the syllabus</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#about-rstudio"><i class="fa fa-check"></i>About RStudio</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#lab-assignments"><i class="fa fa-check"></i>Lab assignments</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#getting-started-with-r"><i class="fa fa-check"></i>Getting started with R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#are-you-completely-new-to-r"><i class="fa fa-check"></i>Are you completely new to R?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html"><i class="fa fa-check"></i>Thursday, August 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#expectations"><i class="fa fa-check"></i>Expectations</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-science-workflow-with-r-markdown"><i class="fa fa-check"></i>Data science workflow with R markdown</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#an-introduction-to-using-r"><i class="fa fa-check"></i>An introduction to using R</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-frames"><i class="fa fa-check"></i>Data frames</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html"><i class="fa fa-check"></i>Tuesday August 30, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#working-with-data-frames"><i class="fa fa-check"></i>Working with data frames</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html"><i class="fa fa-check"></i>Thursday September 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#making-graphs"><i class="fa fa-check"></i>Making graphs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html"><i class="fa fa-check"></i>Tuesday September 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#working-with-spatial-data"><i class="fa fa-check"></i>Working with spatial data</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#geo-computation-on-simple-features"><i class="fa fa-check"></i>Geo-computation on simple features</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html"><i class="fa fa-check"></i>Thursday September 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#spatial-data-subsets-and-joins"><i class="fa fa-check"></i>Spatial data subsets and joins</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#interpolation-using-areal-weights"><i class="fa fa-check"></i>Interpolation using areal weights</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html"><i class="fa fa-check"></i>Tuesday September 13, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#s4-spatial-data-objects"><i class="fa fa-check"></i>S4 spatial data objects</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#working-with-raster-data"><i class="fa fa-check"></i>Working with raster data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html"><i class="fa fa-check"></i>Thursday September 15, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#working-with-space-time-data"><i class="fa fa-check"></i>Working with space-time data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#mapping-using-functions-from-the-ggplot2-package"><i class="fa fa-check"></i>Mapping using functions from the {ggplot2} package</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#mapping-using-functions-from-the-tmap-package"><i class="fa fa-check"></i>Mapping using functions from the {tmap} package</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#creating-an-interactive-map"><i class="fa fa-check"></i>Creating an interactive map</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#adding-an-inset-map"><i class="fa fa-check"></i>Adding an inset map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html"><i class="fa fa-check"></i>Tuesday September 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#defining-spatial-neighborhoods-and-spatial-weights"><i class="fa fa-check"></i>Defining spatial neighborhoods and spatial weights</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#computing-autocorrelation"><i class="fa fa-check"></i>Computing autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#spatial-lag-and-its-relation-to-autocorrelation"><i class="fa fa-check"></i>Spatial lag and its relation to autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html"><i class="fa fa-check"></i>Thursday September 22, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#other-neighbor-definitions"><i class="fa fa-check"></i>Other neighbor definitions</a></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#assessing-the-statistical-significance-of-autocorrelation"><i class="fa fa-check"></i>Assessing the statistical significance of autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#bivariate-spatial-autocorrelation"><i class="fa fa-check"></i>Bivariate spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#local-indicators-of-spatial-autocorrelation"><i class="fa fa-check"></i>Local indicators of spatial autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-27-2022.html"><a href="tuesday-september-27-2022.html"><i class="fa fa-check"></i>Tuesday September 27, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-27-2022.html"><a href="tuesday-september-27-2022.html#constraining-group-membership-based-on-spatial-autocorrelation"><i class="fa fa-check"></i>Constraining group membership based on spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-27-2022.html"><a href="tuesday-september-27-2022.html#estimating-spatial-autocorrelation-in-model-residuals"><i class="fa fa-check"></i>Estimating spatial autocorrelation in model residuals</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-27-2022.html"><a href="tuesday-september-27-2022.html#choosing-a-spatial-regression-model"><i class="fa fa-check"></i>Choosing a spatial regression model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html"><i class="fa fa-check"></i>Thursday September 29, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#fitting-and-interpreting-a-spatially-lagged-y-model"><i class="fa fa-check"></i>Fitting and interpreting a spatially-lagged Y model</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#fitting-and-interpreting-a-spatially-lagged-x-model"><i class="fa fa-check"></i>Fitting and interpreting a spatially-lagged X model</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#fitting-and-interpreting-spatial-durbin-models"><i class="fa fa-check"></i>Fitting and interpreting spatial Durbin models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html"><i class="fa fa-check"></i>Tuesday October 4, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#fitting-and-interpreting-geographic-regressions"><i class="fa fa-check"></i>Fitting and interpreting geographic regressions</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#mapping-incidence-and-risk-with-spatial-regression-models"><i class="fa fa-check"></i>Mapping incidence and risk with spatial regression models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html"><i class="fa fa-check"></i>Thursday October 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#spatial-data-as-point-patterns"><i class="fa fa-check"></i>Spatial data as point patterns</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#working-with-point-pattern-objects-using-functions-from-the-spatstat-package"><i class="fa fa-check"></i>Working with point pattern objects using functions from the {spatstat} package</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#quantifying-event-intensity"><i class="fa fa-check"></i>Quantifying event intensity</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html"><i class="fa fa-check"></i>Tuesday October 11, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#creating-ppp-and-owin-objects-from-simple-feature-data-frames"><i class="fa fa-check"></i>Creating <code>ppp</code> and <code>owin</code> objects from simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#estimating-spatial-intensity-as-a-function-of-distance"><i class="fa fa-check"></i>Estimating spatial intensity as a function of distance</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#intensity-trend-as-a-possible-confounding-factor"><i class="fa fa-check"></i>Intensity trend as a possible confounding factor</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html"><i class="fa fa-check"></i>Thursday October 13, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html#estimating-the-relative-risk-of-events"><i class="fa fa-check"></i>Estimating the relative risk of events</a></li>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html#estimating-second-moment-properties-of-spatial-events"><i class="fa fa-check"></i>Estimating second-moment properties of spatial events</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html"><i class="fa fa-check"></i>Tuesday October 18, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#examples-of-spatially-clustered-events"><i class="fa fa-check"></i>Examples of spatially clustered events</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#determining-the-statistical-significance-of-event-clustering"><i class="fa fa-check"></i>Determining the statistical significance of event clustering</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#estimating-event-clustering-in-multi-type-event-locations"><i class="fa fa-check"></i>Estimating event clustering in multi-type event locations</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#more-about-the-ripley-k-function"><i class="fa fa-check"></i>More about the Ripley K function</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GIS5122: Applied Spatial Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="thursday-september-29-2022" class="section level1 unnumbered hasAnchor">
<h1>Thursday September 29, 2022<a href="thursday-september-29-2022.html#thursday-september-29-2022" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>“Feeling a little uncomfortable with your skills is a sign of learning, and continuous learning is what the tech industry thrives on!”</strong> — Vanessa Hurst</p>
<p>Today</p>
<ul>
<li>Fitting and interpreting a spatially-lagged Y model</li>
<li>Fitting and interpreting a spatially-lagged X model</li>
<li>Fitting and interpreting spatial Durban models</li>
</ul>
<p>Ordinary least-squares regression models fit to spatial data can lead to improper inference because observations are not independent. This might lead to poor policy decisions. Thus it’s necessary to check the residuals from an aspatial model for autocorrelation. If the residuals are strongly correlated the model is not specified properly.</p>
<div id="fitting-and-interpreting-a-spatially-lagged-y-model" class="section level2 unnumbered hasAnchor">
<h2>Fitting and interpreting a spatially-lagged Y model<a href="thursday-september-29-2022.html#fitting-and-interpreting-a-spatially-lagged-y-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Continuing with the Columbus crime data.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="thursday-september-29-2022.html#cb1-1" aria-hidden="true" tabindex="-1"></a>( CC.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="at">dsn =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;columbus&quot;</span>),</span>
<span id="cb1-2"><a href="thursday-september-29-2022.html#cb1-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">layer =</span> <span class="st">&quot;columbus&quot;</span>) )</span></code></pre></div>
<pre><code>## Reading layer `columbus&#39; from data source 
##   `/Users/jameselsner/Desktop/ClassNotes/ASS-2022/data/columbus&#39; 
##   using driver `ESRI Shapefile&#39;
## Simple feature collection with 49 features and 20 fields
## Geometry type: POLYGON
## Dimension:     XY
## Bounding box:  xmin: 5.874907 ymin: 10.78863 xmax: 11.28742 ymax: 14.74245
## CRS:           NA</code></pre>
<pre><code>## Simple feature collection with 49 features and 20 fields
## Geometry type: POLYGON
## Dimension:     XY
## Bounding box:  xmin: 5.874907 ymin: 10.78863 xmax: 11.28742 ymax: 14.74245
## CRS:           NA
## First 10 features:
##        AREA PERIMETER COLUMBUS_ COLUMBUS_I POLYID NEIG  HOVAL    INC     CRIME
## 1  0.309441  2.440629         2          5      1    5 80.467 19.531 15.725980
## 2  0.259329  2.236939         3          1      2    1 44.567 21.232 18.801754
## 3  0.192468  2.187547         4          6      3    6 26.350 15.956 30.626781
## 4  0.083841  1.427635         5          2      4    2 33.200  4.477 32.387760
## 5  0.488888  2.997133         6          7      5    7 23.225 11.252 50.731510
## 6  0.283079  2.335634         7          8      6    8 28.750 16.029 26.066658
## 7  0.257084  2.554577         8          4      7    4 75.000  8.438  0.178269
## 8  0.204954  2.139524         9          3      8    3 37.125 11.337 38.425858
## 9  0.500755  3.169707        10         18      9   18 52.600 17.586 30.515917
## 10 0.246689  2.087235        11         10     10   10 96.400 13.598 34.000835
##        OPEN    PLUMB DISCBD     X     Y NSA NSB EW CP THOUS NEIGNO
## 1  2.850747 0.217155   5.03 38.80 44.07   1   1  1  0  1000   1005
## 2  5.296720 0.320581   4.27 35.62 42.38   1   1  0  0  1000   1001
## 3  4.534649 0.374404   3.89 39.82 41.18   1   1  1  0  1000   1006
## 4  0.394427 1.186944   3.70 36.50 40.52   1   1  0  0  1000   1002
## 5  0.405664 0.624596   2.83 40.01 38.00   1   1  1  0  1000   1007
## 6  0.563075 0.254130   3.78 43.75 39.28   1   1  1  0  1000   1008
## 7  0.000000 2.402402   2.74 33.36 38.41   1   1  0  0  1000   1004
## 8  3.483478 2.739726   2.89 36.71 38.71   1   1  0  0  1000   1003
## 9  0.527488 0.890736   3.17 43.44 35.92   1   1  1  0  1000   1018
## 10 1.548348 0.557724   4.33 47.61 36.42   1   1  1  0  1000   1010
##                          geometry
## 1  POLYGON ((8.624129 14.23698...
## 2  POLYGON ((8.25279 14.23694,...
## 3  POLYGON ((8.653305 14.00809...
## 4  POLYGON ((8.459499 13.82035...
## 5  POLYGON ((8.685274 13.63952...
## 6  POLYGON ((9.401384 13.5504,...
## 7  POLYGON ((8.037741 13.60752...
## 8  POLYGON ((8.247527 13.58651...
## 9  POLYGON ((9.333297 13.27242...
## 10 POLYGON ((10.08251 13.03377...</code></pre>
<p>Recall interest with these data centers on crime as a response variable and income and housing value as explanatory variables. You set the formula as a string and refit a OLS regression model.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="thursday-september-29-2022.html#cb4-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> CRIME <span class="sc">~</span> INC <span class="sc">+</span> HOVAL</span>
<span id="cb4-2"><a href="thursday-september-29-2022.html#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="thursday-september-29-2022.html#cb4-3" aria-hidden="true" tabindex="-1"></a>( model.ols <span class="ot">&lt;-</span> <span class="fu">lm</span>(f, <span class="at">data =</span> CC.sf) )</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = f, data = CC.sf)
## 
## Coefficients:
## (Intercept)          INC        HOVAL  
##     68.6190      -1.5973      -0.2739</code></pre>
<p>The marginal effect of income on crime is -1.6 and the marginal effect of housing value on crime is -.27.</p>
<p>A nice way to visualize the relative significance of the explanatory variables is to make a plot. Here you use the <code>broom::tidy()</code> method and then <code>ggplot()</code> as follows.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="thursday-september-29-2022.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(broom)) <span class="fu">install.packages</span>(<span class="at">pkgs =</span> <span class="st">&quot;broom&quot;</span>, <span class="at">repos =</span> <span class="st">&quot;http://cran.us.r-project.org&quot;</span>)</span></code></pre></div>
<pre><code>## Loading required package: broom</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="thursday-september-29-2022.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb8-2"><a href="thursday-september-29-2022.html#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="thursday-september-29-2022.html#cb8-3" aria-hidden="true" tabindex="-1"></a>( d <span class="ot">&lt;-</span> broom<span class="sc">::</span><span class="fu">tidy</span>(model.ols, </span>
<span id="cb8-4"><a href="thursday-september-29-2022.html#cb8-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">conf.int =</span> <span class="cn">TRUE</span>) )</span></code></pre></div>
<pre><code>## # A tibble: 3 × 7
##   term        estimate std.error statistic  p.value conf.low conf.high
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)   68.6       4.74      14.5  9.21e-19   59.1     78.2   
## 2 INC           -1.60      0.334     -4.78 1.83e- 5   -2.27    -0.925 
## 3 HOVAL         -0.274     0.103     -2.65 1.09e- 2   -0.482   -0.0662</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="thursday-september-29-2022.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb10-2"><a href="thursday-september-29-2022.html#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="thursday-september-29-2022.html#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(d[<span class="sc">-</span><span class="dv">1</span>,], <span class="fu">aes</span>(<span class="at">x =</span> estimate,  <span class="co"># we do not plot the intercept term</span></span>
<span id="cb10-4"><a href="thursday-september-29-2022.html#cb10-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">y =</span> term, </span>
<span id="cb10-5"><a href="thursday-september-29-2022.html#cb10-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">xmin =</span> conf.low, </span>
<span id="cb10-6"><a href="thursday-september-29-2022.html#cb10-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">xmax =</span> conf.high, </span>
<span id="cb10-7"><a href="thursday-september-29-2022.html#cb10-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">height =</span> <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb10-8"><a href="thursday-september-29-2022.html#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb10-9"><a href="thursday-september-29-2022.html#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb10-10"><a href="thursday-september-29-2022.html#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbarh</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>The maximum likelihood estimate is shown as a point and the confidence interval around the estimate is shown as a horizontal error bar. The default confidence level is 95% (<code>conf.level = .95</code>). The effects are statistically significant as the confidence intervals do not intersect the zero line (dashed-dotted).</p>
<p>Then check for spatial autocorrelation in the residuals. This is done by first defining the weights matrix and then applying Moran’s I test as follows.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="thursday-september-29-2022.html#cb11-1" aria-hidden="true" tabindex="-1"></a>nbs <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">poly2nb</span>(CC.sf, </span>
<span id="cb11-2"><a href="thursday-september-29-2022.html#cb11-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">queen =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-3"><a href="thursday-september-29-2022.html#cb11-3" aria-hidden="true" tabindex="-1"></a>wts <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">nb2listw</span>(nbs)</span>
<span id="cb11-4"><a href="thursday-september-29-2022.html#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="thursday-september-29-2022.html#cb11-5" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">lm.morantest</span>(model.ols, </span>
<span id="cb11-6"><a href="thursday-september-29-2022.html#cb11-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">listw =</span> wts)</span></code></pre></div>
<pre><code>## 
##  Global Moran I for regression residuals
## 
## data:  
## model: lm(formula = f, data = CC.sf)
## weights: wts
## 
## Moran I statistic standard deviate = 2.8393, p-value = 0.00226
## alternative hypothesis: greater
## sample estimates:
## Observed Moran I      Expectation         Variance 
##      0.222109407     -0.033418335      0.008099305</code></pre>
<p>The results show that the model residuals have significant spatial autocorrelation so reporting the marginal effects with an OLS regression model would not be correct.</p>
<p>You then fit a spatially-lagged Y model using the <code>lagsarlm()</code> function from the {spatialreg} package. The model is</p>
<p><span class="math display">\[
y = \rho W y + X \beta + \varepsilon
\]</span>
where <span class="math inline">\(Wy\)</span> is the weighted average of the neighborhood response values (spatial lag variable) with <span class="math inline">\(W\)</span> the spatial weights matrix, and <span class="math inline">\(\rho\)</span> is the autoregression coefficient.</p>
<p>The <code>spatialreg::lagsarlm()</code> function first determines a value for <span class="math inline">\(\rho\)</span> ( with the internal <code>optimize()</code> function) and then the <span class="math inline">\(\beta\)</span>’s are obtained using generalized least squares (GLS). The model formula <code>f</code> is the same as what you used to fit the OLS regression above. You save the model object as <code>model.slym</code>.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="thursday-september-29-2022.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(spatialreg)) <span class="fu">install.packages</span>(<span class="at">pkgs =</span> <span class="st">&quot;spatialreg&quot;</span>, <span class="at">repos =</span> <span class="st">&quot;http://cran.us.r-project.org&quot;</span>)</span></code></pre></div>
<pre><code>## Loading required package: spatialreg</code></pre>
<pre><code>## Loading required package: spData</code></pre>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## Loading required package: sf</code></pre>
<pre><code>## Linking to GEOS 3.9.1, GDAL 3.4.2, PROJ 8.2.1; sf_use_s2() is TRUE</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="thursday-september-29-2022.html#cb19-1" aria-hidden="true" tabindex="-1"></a>model.slym <span class="ot">&lt;-</span> spatialreg<span class="sc">::</span><span class="fu">lagsarlm</span>(<span class="at">formula =</span> f, </span>
<span id="cb19-2"><a href="thursday-september-29-2022.html#cb19-2" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">data =</span> CC.sf, </span>
<span id="cb19-3"><a href="thursday-september-29-2022.html#cb19-3" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">listw =</span> wts)</span>
<span id="cb19-4"><a href="thursday-september-29-2022.html#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="thursday-september-29-2022.html#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.slym)</span></code></pre></div>
<pre><code>## 
## Call:spatialreg::lagsarlm(formula = f, data = CC.sf, listw = wts)
## 
## Residuals:
##        Min         1Q     Median         3Q        Max 
## -37.652017  -5.334611   0.071473   6.107196  23.302618 
## 
## Type: lag 
## Coefficients: (asymptotic standard errors) 
##              Estimate Std. Error z value  Pr(&gt;|z|)
## (Intercept) 45.603249   7.257404  6.2837 3.306e-10
## INC         -1.048728   0.307406 -3.4115  0.000646
## HOVAL       -0.266335   0.089096 -2.9893  0.002796
## 
## Rho: 0.42333, LR test value: 9.4065, p-value: 0.0021621
## Asymptotic standard error: 0.11951
##     z-value: 3.5422, p-value: 0.00039686
## Wald statistic: 12.547, p-value: 0.00039686
## 
## Log likelihood: -182.674 for lag model
## ML residual variance (sigma squared): 96.857, (sigma: 9.8416)
## Number of observations: 49 
## Number of parameters estimated: 5 
## AIC: 375.35, (AIC for lm: 382.75)
## LM test for residual autocorrelation
## test value: 0.24703, p-value: 0.61917</code></pre>
<p>The first batch of output concerns the model residuals and the coefficients on the explanatory variables. The model residuals are the observed crime rates minus the predicted crime rates.</p>
<p>The coefficients on income and housing have the same sign (negative) and they remain statistically significant (-1.05 for income and -.27 for housing value). But you can’t interpret these coefficients as the marginal effects.</p>
<p>The next set of output is about the coefficient of spatial autocorrelation (<span class="math inline">\(\rho\)</span>). The value is .423 and a likelihood ratio test gives a value of 9.41 which translates to a <span class="math inline">\(p\)</span>-value of .002. The null hypothesis is the autocorrelation is zero, so you confidently reject it. This is consistent with the significant Moran’s I value that you found in the linear model residuals.</p>
<p>Two other tests are performed on the value of <span class="math inline">\(\rho\)</span> including a z-test (t-test) using the asymptotic standard error and a Wald test. Both tests confirm that the lag term should be included in the model from crime involving income and housing values.</p>
<p>In spatial models that contain a lagged response term, the coefficients are not marginal effects. The spatial lag model allows for ‘spillover’. That is a change in an explanatory variable anywhere in the study domain will affect the value of the response variable <em>everywhere</em>. Spillover occurs even when the neighborhood weights matrix represents local contiguity. The spillover makes interpreting the coefficients more complicated.</p>
<p>With a spatially-lagged Y model a change in the value of an explanatory variable results in both <em>direct</em> and <em>indirect</em> effects on the response variable.</p>
<p>For example, the direct effect gives the impact a change in income has on crime averaged over all tracts. It takes into account the effects that occur from a change in the <span class="math inline">\(i\)</span>th tract’s income on crime across neighboring tracts.</p>
<p>The indirect effect gives the impact of a change in income has on crime averaged over all <em>other</em> tracts. The indirect effect represent spillovers. The influences on the dependent variable <span class="math inline">\(y\)</span> in a region rendered by change in <span class="math inline">\(x\)</span> in some <em>other</em> region. For example, if all tracts <span class="math inline">\(i \ne j\)</span> (i not equal to j) increase their income, what will be the impact on crime in region <span class="math inline">\(i\)</span>?</p>
<p>The total effect (TE) is the sum of the direct and indirect effects. It measures the total cumulative impact on crime arising from one tract <span class="math inline">\(j\)</span> increasing its income over all other tracts (on average). It is given by</p>
<p><span class="math display">\[
\hbox{TE} = \left(\frac{\beta_k}{1-\rho^2}\right)\left(1 + \rho\right)
\]</span>
where <span class="math inline">\(\beta_k\)</span> is the marginal effect of variable <span class="math inline">\(k\)</span> and <span class="math inline">\(\rho\)</span> is the spatial autocorrelation coefficient. With <span class="math inline">\(\rho = 0\)</span> TE is <span class="math inline">\(\beta_k\)</span>.</p>
<p>Here <span class="math inline">\(\beta_{INC}\)</span> is -1.0487 and <span class="math inline">\(\rho\)</span> is .4233, so the total effect is</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="thursday-september-29-2022.html#cb21-1" aria-hidden="true" tabindex="-1"></a>( TE_INC <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">1.0487</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> .<span class="dv">4233</span><span class="sc">^</span><span class="dv">2</span>) <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">+</span> .<span class="dv">4233</span>) )</span></code></pre></div>
<pre><code>## [1] -1.81845</code></pre>
<p>The direct, indirect, and total effects are shown using the <code>spatialreg::impacts()</code> function.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="thursday-september-29-2022.html#cb23-1" aria-hidden="true" tabindex="-1"></a>spatialreg<span class="sc">::</span><span class="fu">impacts</span>(model.slym, </span>
<span id="cb23-2"><a href="thursday-september-29-2022.html#cb23-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">listw =</span> wts)</span></code></pre></div>
<pre><code>## Impact measures (lag, exact):
##           Direct   Indirect      Total
## INC   -1.1008955 -0.7176833 -1.8185788
## HOVAL -0.2795832 -0.1822627 -0.4618459</code></pre>
<p>The direct effects are the changes in the response variable of a particular region arising from a one unit increase in an explanatory variable in that region.</p>
<p>The indirect effects are the changes in the response variable of a particular region arising from a one unit increase in an explanatory variable in another region. For example, due to spatial autocorrelation, a one-unit change in the income variable in region 1 affects the crime rate in regions 2 and 3.</p>
<p>The next set of output concerns the overall model fit. It includes the log likelihood value and the AIC (Akaike Information Criterion). The AIC value for the linear model is included. Here it is clear that the spatial lag model is an improvement (smaller AIC) over the aspatial model.</p>
<p>The larger the likelihood, the better the model and two times the difference in log likelihoods from two competing models divided by the number of observations gives a scale for how much improvement.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="thursday-september-29-2022.html#cb25-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="fu">logLik</span>(model.slym) <span class="sc">-</span> <span class="fu">logLik</span>(model.ols))<span class="sc">/</span><span class="dv">49</span></span>
<span id="cb25-2"><a href="thursday-september-29-2022.html#cb25-2" aria-hidden="true" tabindex="-1"></a>x[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 0.1919701</code></pre>
<p>Improvement table</p>
<table>
<thead>
<tr class="header">
<th>Likelihood difference</th>
<th>Qualitative improvement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>huge</td>
</tr>
<tr class="even">
<td>.1</td>
<td>large</td>
</tr>
<tr class="odd">
<td>.01</td>
<td>good</td>
</tr>
<tr class="even">
<td>.001</td>
<td>okay</td>
</tr>
</tbody>
</table>
<p>The final bit of output is a Lagrange multiplier test for remaining autocorrelation. The null hypothesis is there is no remaining autocorrelation since we have a lag term in the model. The result is a high <span class="math inline">\(p\)</span>-value so you are satisfied that the lag term takes care of the autocorrelation.</p>
<p>Compare the spatial lag model to a spatial error model. Here you use the <code>spatialreg::errorsarlm()</code> function.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="thursday-september-29-2022.html#cb27-1" aria-hidden="true" tabindex="-1"></a>model.sem <span class="ot">&lt;-</span> spatialreg<span class="sc">::</span><span class="fu">errorsarlm</span>(<span class="at">formula =</span> f, </span>
<span id="cb27-2"><a href="thursday-september-29-2022.html#cb27-2" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">data =</span> CC.sf, </span>
<span id="cb27-3"><a href="thursday-september-29-2022.html#cb27-3" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">listw =</span> wts)</span>
<span id="cb27-4"><a href="thursday-september-29-2022.html#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.sem)</span></code></pre></div>
<pre><code>## 
## Call:spatialreg::errorsarlm(formula = f, data = CC.sf, listw = wts)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -34.65998  -6.16943  -0.70623   7.75392  23.43878 
## 
## Type: error 
## Coefficients: (asymptotic standard errors) 
##              Estimate Std. Error z value  Pr(&gt;|z|)
## (Intercept) 60.279469   5.365594 11.2344 &lt; 2.2e-16
## INC         -0.957305   0.334231 -2.8642 0.0041806
## HOVAL       -0.304559   0.092047 -3.3087 0.0009372
## 
## Lambda: 0.54675, LR test value: 7.2556, p-value: 0.0070679
## Asymptotic standard error: 0.13805
##     z-value: 3.9605, p-value: 7.4786e-05
## Wald statistic: 15.686, p-value: 7.4786e-05
## 
## Log likelihood: -183.7494 for error model
## ML residual variance (sigma squared): 97.674, (sigma: 9.883)
## Number of observations: 49 
## Number of parameters estimated: 5 
## AIC: 377.5, (AIC for lm: 382.75)</code></pre>
<p>You find the coefficient of spatial autocorrelation (<span class="math inline">\(\lambda\)</span>) is significant, but the log likelihood value from the model is smaller (-183.7) and the AIC value is larger (377.5) compared with corresponding values from the lag model. This is consistent with the lagrange multiplier (LM) tests indicating the spatial lag model is more appropriate.</p>
<p>Also you can compare the log likelihoods from the two spatial regression models that you fit.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="thursday-september-29-2022.html#cb29-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="fu">logLik</span>(model.slym) <span class="sc">-</span> <span class="fu">logLik</span>(model.sem))<span class="sc">/</span><span class="dv">49</span></span>
<span id="cb29-2"><a href="thursday-september-29-2022.html#cb29-2" aria-hidden="true" tabindex="-1"></a>x[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 0.04389617</code></pre>
<p>With a value of .04 you conclude that there is good improvement of the lag model over the error model. Again, this is consistent with your decision above to use the lag model.</p>
<p>With the spatial error model the coefficients can be interpreted as marginal effects like with the OLS model.</p>
<p>If there are large differences (e.g., different signs) between the coefficient estimate from SEM and OLS, this suggests that neither model is yielding parameters estimates matching the underlying parameters of the data generating process.</p>
<p>You test whether there is a significant difference in coefficient estimates with the Hausman test under the hypothesis of no difference.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="thursday-september-29-2022.html#cb31-1" aria-hidden="true" tabindex="-1"></a>spatialreg<span class="sc">::</span><span class="fu">Hausman.test</span>(model.sem)</span></code></pre></div>
<pre><code>## 
##  Spatial Hausman test (asymptotic)
## 
## data:  NULL
## Hausman test = 5.6132, df = 3, p-value = 0.132</code></pre>
<p>The <span class="math inline">\(p\)</span>-value gives inconclusive evidence that the coefficients are different and that maybe the SEM is not the right way to proceed with these data.</p>
<p>The <code>predict()</code> method implements the <code>predict.sarlm()</code> function to calculate predictions from the spatial regression model. The prediction on a spatial lag Y model is decomposed into a “trend” term (explanatory variable effect) and a “signal” term (spatial smoother). The predicted fit is the sum of the trend and the signal terms when using the spatial lag model.</p>
<p>You make predictions with the <code>predict()</code> method under the assumption that the mean response is known. You examine the structure of the corresponding predict object.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="thursday-september-29-2022.html#cb33-1" aria-hidden="true" tabindex="-1"></a>( predictedValues <span class="ot">&lt;-</span> <span class="fu">predict</span>(model.slym) )</span></code></pre></div>
<pre><code>## This method assumes the response is known - see manual page</code></pre>
<pre><code>##          fit     trend    signal
## 1  14.151553  3.689375 10.462178
## 2  22.577864 11.466909 11.110955
## 3  34.302562 21.851820 12.450742
## 4  46.732511 32.065777 14.666734
## 5  44.747335 27.617334 17.130002
## 6  38.333111 21.136061 17.197050
## 7  37.830286 16.778970 21.051316
## 8  41.393775 23.826138 17.567637
## 9  28.792040 13.151105 15.640935
## 10 16.390116  5.667967 10.722149
## 11 53.631524 32.525600 21.105925
## 12 48.074429 29.765566 18.308863
## 13 40.608933 24.482782 16.126151
## 14 41.856029 23.729006 18.127022
## 15 51.665885 30.455129 21.210756
## 16 54.767238 32.599603 22.167635
## 17 31.866731 24.208332  7.658399
## 18 37.461970 15.795680 21.666290
## 19 44.929428 25.269280 19.660148
## 20  5.110404 -8.624965 13.735370
## 21 47.617356 29.109013 18.508344
## 22 40.412907 25.213796 15.199111
## 23 18.640125 10.704444  7.935681
## 24 39.747461 16.504543 23.242918
## 25 53.116667 31.962567 21.154100
## 26 52.303708 31.717685 20.586023
## 27 39.228077 25.171896 14.056181
## 28 51.354572 31.278690 20.075882
## 29 49.767662 27.843359 21.924303
## 30 45.589426 25.027102 20.562325
## 31 27.465213 19.368346  8.096867
## 32 20.869990 15.004949  5.865041
## 33 44.697299 28.916462 15.780838
## 34 31.720867 22.349635  9.371232
## 35 38.985264 24.973806 14.011458
## 36 24.222607 16.283179  7.939428
## 37 37.811894 16.224745 21.587149
## 38 46.388525 27.909225 18.479300
## 39 22.524680 15.679042  6.845638
## 40  6.730001 -2.182900  8.912901
## 41 20.020878 11.101447  8.919432
## 42 14.764446  6.662085  8.102360
## 43 40.034408 24.726461 15.307947
## 44 34.026283 18.893554 15.132729
## 45 36.970894 23.393213 13.577681
## 46 13.189170  6.118277  7.070893
## 47 21.849812 14.410620  7.439192
## 48 38.162352 26.076851 12.085502
## 49 27.876102 16.356569 11.519534</code></pre>
<p>The predicted values are in the column labeled <code>fit</code>. The predicted values are a sum of the trend term (<span class="math inline">\(X\beta\)</span>) and the signal term (<span class="math inline">\(\rho W y\)</span>). The signal term is called the spatial smoother.</p>
<p>As a first-order check if things are what you think they are, compare the first five predicted values with the corresponding observed values.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="thursday-september-29-2022.html#cb36-1" aria-hidden="true" tabindex="-1"></a>predictedValues[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code></pre></div>
<pre><code>##        1        2        3        4        5 
## 14.15155 22.57786 34.30256 46.73251 44.74734</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="thursday-september-29-2022.html#cb38-1" aria-hidden="true" tabindex="-1"></a>CC.sf<span class="sc">$</span>CRIME[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code></pre></div>
<pre><code>## [1] 15.72598 18.80175 30.62678 32.38776 50.73151</code></pre>
<p>Some predicted values are lower than the corresponding observed values and some are higher.</p>
<p>The predicted values along with the values for the trend and signal are added to the simple features data frame.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="thursday-september-29-2022.html#cb40-1" aria-hidden="true" tabindex="-1"></a>CC.sf<span class="sc">$</span>fit <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(predictedValues)</span>
<span id="cb40-2"><a href="thursday-september-29-2022.html#cb40-2" aria-hidden="true" tabindex="-1"></a>CC.sf<span class="sc">$</span>trend <span class="ot">&lt;-</span> <span class="fu">attr</span>(predictedValues, <span class="st">&quot;trend&quot;</span>)</span>
<span id="cb40-3"><a href="thursday-september-29-2022.html#cb40-3" aria-hidden="true" tabindex="-1"></a>CC.sf<span class="sc">$</span>signal <span class="ot">&lt;-</span> <span class="fu">attr</span>(predictedValues, <span class="st">&quot;signal&quot;</span>)</span></code></pre></div>
<p>The components of the predictions are mapped and placed on the same plot.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="thursday-september-29-2022.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb41-2"><a href="thursday-september-29-2022.html#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="thursday-september-29-2022.html#cb41-3" aria-hidden="true" tabindex="-1"></a>( g1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb41-4"><a href="thursday-september-29-2022.html#cb41-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>(<span class="at">data =</span> CC.sf, <span class="fu">aes</span>(<span class="at">fill =</span> fit)) <span class="sc">+</span></span>
<span id="cb41-5"><a href="thursday-september-29-2022.html#cb41-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_viridis_c</span>() <span class="sc">+</span></span>
<span id="cb41-6"><a href="thursday-september-29-2022.html#cb41-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">&quot;Predicted Crime&quot;</span>) )</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="thursday-september-29-2022.html#cb42-1" aria-hidden="true" tabindex="-1"></a>( g2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb42-2"><a href="thursday-september-29-2022.html#cb42-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>(<span class="at">data =</span> CC.sf, <span class="fu">aes</span>(<span class="at">fill =</span> trend)) <span class="sc">+</span></span>
<span id="cb42-3"><a href="thursday-september-29-2022.html#cb42-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_viridis_c</span>() <span class="sc">+</span></span>
<span id="cb42-4"><a href="thursday-september-29-2022.html#cb42-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">&quot;Trend (Explanatory Variables)&quot;</span>) )</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-15-2.png" width="672" /></p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="thursday-september-29-2022.html#cb43-1" aria-hidden="true" tabindex="-1"></a>( g3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb43-2"><a href="thursday-september-29-2022.html#cb43-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>(<span class="at">data =</span> CC.sf, <span class="fu">aes</span>(<span class="at">fill =</span> signal)) <span class="sc">+</span></span>
<span id="cb43-3"><a href="thursday-september-29-2022.html#cb43-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_viridis_c</span>() <span class="sc">+</span></span>
<span id="cb43-4"><a href="thursday-september-29-2022.html#cb43-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">&quot;Signal&quot;</span>) )</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-15-3.png" width="672" /></p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="thursday-september-29-2022.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb44-2"><a href="thursday-september-29-2022.html#cb44-2" aria-hidden="true" tabindex="-1"></a>g1 <span class="sc">+</span> g2 <span class="sc">+</span> g3</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-15-4.png" width="672" /></p>
<p>The trend term and the spatial smoother have similar ranges indicating nearly equal contributions to the predictions. The largest difference between the two terms occurs in the city’s east side.</p>
<p>A map of the difference makes this clear.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="thursday-september-29-2022.html#cb45-1" aria-hidden="true" tabindex="-1"></a>CC.sf <span class="ot">&lt;-</span> CC.sf <span class="sc">|&gt;</span></span>
<span id="cb45-2"><a href="thursday-september-29-2022.html#cb45-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">CovMinusSmooth =</span> trend <span class="sc">-</span> signal)</span>
<span id="cb45-3"><a href="thursday-september-29-2022.html#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="thursday-september-29-2022.html#cb45-4" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_shape</span>(CC.sf) <span class="sc">+</span></span>
<span id="cb45-5"><a href="thursday-september-29-2022.html#cb45-5" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">&quot;CovMinusSmooth&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: Currect projection of shape CC.sf unknown. Long-lat (WGS84) is assumed.</code></pre>
<pre><code>## Variable(s) &quot;CovMinusSmooth&quot; contains positive and negative values, so midpoint is set to 0. Set midpoint = NA to show the full spectrum of the color palette.</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>How many tracts have a smaller residual with the lag model versus the OLS model?</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="thursday-september-29-2022.html#cb48-1" aria-hidden="true" tabindex="-1"></a>CC.sf <span class="sc">|&gt;</span></span>
<span id="cb48-2"><a href="thursday-september-29-2022.html#cb48-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">residualsL =</span> CRIME <span class="sc">-</span> fit,</span>
<span id="cb48-3"><a href="thursday-september-29-2022.html#cb48-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">lagWins =</span> <span class="fu">abs</span>(<span class="fu">residuals</span>(model.ols)) <span class="sc">&gt;</span> <span class="fu">abs</span>(residualsL),</span>
<span id="cb48-4"><a href="thursday-september-29-2022.html#cb48-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">CovMinusSmooth =</span> trend <span class="sc">-</span> signal) <span class="sc">|&gt;</span></span>
<span id="cb48-5"><a href="thursday-september-29-2022.html#cb48-5" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span></span>
<span id="cb48-6"><a href="thursday-september-29-2022.html#cb48-6" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">N =</span> <span class="fu">sum</span>(lagWins))</span></code></pre></div>
<pre><code>##    N
## 1 32</code></pre>
<p>In 32 out of the 49 tracts the residuals from the spatial model are smaller than the residuals from the OLS model.</p>
</div>
<div id="fitting-and-interpreting-a-spatially-lagged-x-model" class="section level2 unnumbered hasAnchor">
<h2>Fitting and interpreting a spatially-lagged X model<a href="thursday-september-29-2022.html#fitting-and-interpreting-a-spatially-lagged-x-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Another spatial regression option is to modify the linear model to include spatially-lagged explanatory variables. This is called the spatially-lagged X model. <span class="math display">\[
y = X \beta + WX \theta + \varepsilon
\]</span></p>
<p>In this case the weights matrix is (post) multiplied by the matrix of X variables where <span class="math inline">\(W\)</span> is again the weights matrix and <span class="math inline">\(\theta\)</span> is a vector of coefficients for each lagged explanatory variable.</p>
<p>Here you fit the spatially-lagged X model using the <code>spatialreg::lmSLX()</code> function and save the model object as <code>model.slxm</code>.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="thursday-september-29-2022.html#cb50-1" aria-hidden="true" tabindex="-1"></a>( model.slxm <span class="ot">&lt;-</span> spatialreg<span class="sc">::</span><span class="fu">lmSLX</span>(<span class="at">formula =</span> f, </span>
<span id="cb50-2"><a href="thursday-september-29-2022.html#cb50-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">data =</span> CC.sf, </span>
<span id="cb50-3"><a href="thursday-september-29-2022.html#cb50-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">listw =</span> wts) )</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = formula(paste(&quot;y ~ &quot;, paste(colnames(x)[-1], collapse = &quot;+&quot;))), 
##     data = as.data.frame(x), weights = weights)
## 
## Coefficients:
## (Intercept)          INC        HOVAL      lag.INC    lag.HOVAL  
##     74.5534      -1.0974      -0.2944      -1.3987       0.2148</code></pre>
<p>With this model, beside the direct marginal effects of income and housing value on crime, you also have the spatially-lagged indirect effects.</p>
<p>The total effect of income on crime is the sum of the direct effect and indirect effect. And again, using the <code>spatialreg::impacts()</code> function you see this.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="thursday-september-29-2022.html#cb52-1" aria-hidden="true" tabindex="-1"></a>spatialreg<span class="sc">::</span><span class="fu">impacts</span>(model.slxm, <span class="at">listw =</span> wts)</span></code></pre></div>
<pre><code>## Impact measures (SlX, estimable):
##           Direct  Indirect       Total
## INC   -1.0973898 -1.398746 -2.49613551
## HOVAL -0.2943898  0.214841 -0.07954881</code></pre>
<p>You get the impact measures and their standard errors, z-values and <span class="math inline">\(p\)</span>-values with the <code>summary()</code> method applied to the output of the <code>impacts()</code> function.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="thursday-september-29-2022.html#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(spatialreg<span class="sc">::</span><span class="fu">impacts</span>(model.slxm, <span class="at">listw =</span> wts))</span></code></pre></div>
<pre><code>## Impact measures (SlX, estimable, n-k):
##           Direct  Indirect       Total
## INC   -1.0973898 -1.398746 -2.49613551
## HOVAL -0.2943898  0.214841 -0.07954881
## ========================================================
## Standard errors:
##          Direct  Indirect     Total
## INC   0.3738313 0.5601247 0.4929713
## HOVAL 0.1016586 0.2079212 0.2074767
## ========================================================
## Z-values:
##          Direct  Indirect      Total
## INC   -2.935522 -2.497204 -5.0634496
## HOVAL -2.895867  1.033281 -0.3834108
## 
## p-values:
##       Direct    Indirect Total     
## INC   0.0033299 0.012518 4.1174e-07
## HOVAL 0.0037811 0.301473 0.70142</code></pre>
<p>Results show that income has a significant direct <em>and</em> indirect effect on crime rates, but housing values only show a significant direct effect and not a significant indirect effect.</p>
<p>Again you visualize the relative significance of the effects.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="thursday-september-29-2022.html#cb56-1" aria-hidden="true" tabindex="-1"></a>model.slxm <span class="sc">|&gt;</span></span>
<span id="cb56-2"><a href="thursday-september-29-2022.html#cb56-2" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>(<span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb56-3"><a href="thursday-september-29-2022.html#cb56-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">slice</span>(<span class="sc">-</span><span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb56-4"><a href="thursday-september-29-2022.html#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> estimate,</span>
<span id="cb56-5"><a href="thursday-september-29-2022.html#cb56-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">y =</span> term, </span>
<span id="cb56-6"><a href="thursday-september-29-2022.html#cb56-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">xmin =</span> conf.low, </span>
<span id="cb56-7"><a href="thursday-september-29-2022.html#cb56-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">xmax =</span> conf.high, </span>
<span id="cb56-8"><a href="thursday-september-29-2022.html#cb56-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">height =</span> <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb56-9"><a href="thursday-september-29-2022.html#cb56-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb56-10"><a href="thursday-september-29-2022.html#cb56-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb56-11"><a href="thursday-september-29-2022.html#cb56-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbarh</span>()</span></code></pre></div>
<pre><code>## Warning: The `tidy()` method for objects of class `SlX` is not maintained by the broom team, and is only supported through the `lm` tidier method. Please be cautious in interpreting and reporting broom output.
## 
## This warning is displayed once per session.</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>Compare R squared values between the OLS model and the spatially-lagged X model.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="thursday-september-29-2022.html#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.ols)<span class="sc">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.552404</code></pre>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="thursday-september-29-2022.html#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.slxm)<span class="sc">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.6105076</code></pre>
<p>The spatially lagged model has an R squared value that is higher than the R squared value from the linear regression.</p>
</div>
<div id="fitting-and-interpreting-spatial-durbin-models" class="section level2 unnumbered hasAnchor">
<h2>Fitting and interpreting spatial Durbin models<a href="thursday-september-29-2022.html#fitting-and-interpreting-spatial-durbin-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A workflow for finding the correct spatial model is to consider both the spatial Durbin error model and the spatial Durbin model.</p>
<p>The spatial Durban error model (SDEM) is a spatial error model with a spatially-lagged X term added. To fit a SDEM use the <code>spatialreg::errorsarlm()</code> function but include the argument <code>etype = "emixed"</code> to ensure that the spatially lagged X variables are added and the lagged intercept term is dropped when the weights style is row standardized (<code>"W"</code>).</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="thursday-september-29-2022.html#cb62-1" aria-hidden="true" tabindex="-1"></a>( model.sdem <span class="ot">&lt;-</span> spatialreg<span class="sc">::</span><span class="fu">errorsarlm</span>(<span class="at">formula =</span> f, </span>
<span id="cb62-2"><a href="thursday-september-29-2022.html#cb62-2" aria-hidden="true" tabindex="-1"></a>                                       <span class="at">data =</span> CC.sf, </span>
<span id="cb62-3"><a href="thursday-september-29-2022.html#cb62-3" aria-hidden="true" tabindex="-1"></a>                                       <span class="at">listw =</span> wts,</span>
<span id="cb62-4"><a href="thursday-september-29-2022.html#cb62-4" aria-hidden="true" tabindex="-1"></a>                                       <span class="at">etype =</span> <span class="st">&quot;emixed&quot;</span>) )</span></code></pre></div>
<pre><code>## 
## Call:
## spatialreg::errorsarlm(formula = f, data = CC.sf, listw = wts, 
##     etype = &quot;emixed&quot;)
## Type: error 
## 
## Coefficients:
##      lambda (Intercept)         INC       HOVAL     lag.INC   lag.HOVAL 
##   0.4035821  73.6450826  -1.0522585  -0.2781741  -1.2048761   0.1312451 
## 
## Log likelihood: -181.779</code></pre>
<p>The spatial Durban model (SDM) is a spatially-lagged Y model with a spatially-lagged X term added to it. To fit a SDM use the <code>lagsarlm()</code> function but include the argument <code>type = "mixed"</code> to ensure that the spatially lagged X variables are added and the lagged intercept term is dropped when the weights style is row standardized (<code>"W"</code>).</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="thursday-september-29-2022.html#cb64-1" aria-hidden="true" tabindex="-1"></a>( model.sdm <span class="ot">&lt;-</span> spatialreg<span class="sc">::</span><span class="fu">lagsarlm</span>(<span class="at">formula =</span> f, </span>
<span id="cb64-2"><a href="thursday-september-29-2022.html#cb64-2" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">data =</span> CC.sf, </span>
<span id="cb64-3"><a href="thursday-september-29-2022.html#cb64-3" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">listw =</span> wts,</span>
<span id="cb64-4"><a href="thursday-september-29-2022.html#cb64-4" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">type =</span> <span class="st">&quot;mixed&quot;</span>) )</span></code></pre></div>
<pre><code>## 
## Call:
## spatialreg::lagsarlm(formula = f, data = CC.sf, listw = wts, 
##     type = &quot;mixed&quot;)
## Type: mixed 
## 
## Coefficients:
##         rho (Intercept)         INC       HOVAL     lag.INC   lag.HOVAL 
##   0.4034626  44.3200052  -0.9199061  -0.2971294  -0.5839133   0.2576843 
## 
## Log likelihood: -181.6393</code></pre>
<p>How to do you choose between these two models? Is the relationship between crime and income and housing values a global or local effect? Is there any reason to think that if something happens in one tract it will spillover across the entire city? If crime happens in one tract does it influence crime across the entire city? If so, then it is a global relationship. Or should it be a more local effect? If there is more crime in one tract then maybe that influences crime in the neighboring tract but not tracts farther away. If so, then it is a local relationship.</p>
<p>If you think it is a local relationship, start with the spatial Durbin error model and look at the <span class="math inline">\(p\)</span>-values on the direct and indirect effects.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="thursday-september-29-2022.html#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(spatialreg<span class="sc">::</span><span class="fu">impacts</span>(model.sdem, </span>
<span id="cb66-2"><a href="thursday-september-29-2022.html#cb66-2" aria-hidden="true" tabindex="-1"></a>                            <span class="at">listw =</span> wts, </span>
<span id="cb66-3"><a href="thursday-september-29-2022.html#cb66-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">R =</span> <span class="dv">500</span>), <span class="at">zstats =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Impact measures (SDEM, estimable, n):
##           Direct   Indirect     Total
## INC   -1.0522585 -1.2048761 -2.257135
## HOVAL -0.2781741  0.1312451 -0.146929
## ========================================================
## Standard errors:
##           Direct  Indirect     Total
## INC   0.32127932 0.5736416 0.6326029
## HOVAL 0.09114185 0.2072449 0.2372854
## ========================================================
## Z-values:
##          Direct  Indirect     Total
## INC   -3.275214 -2.100399 -3.568012
## HOVAL -3.052101  0.633285 -0.619208
## 
## p-values:
##       Direct    Indirect Total    
## INC   0.0010558 0.035694 0.0003597
## HOVAL 0.0022725 0.526548 0.5357794</code></pre>
<p>You see that income has a statistically significant direct and indirect effect on crime. This means that tracts with higher income have lower crime and tracts whose <em>neighboring tracts</em> have higher income also have lower crime.</p>
<p>On the other hand, housing values have only a statistically significant direct effect on crime. Tracts with more expensive houses have lower crime but tracts whose neighboring tracts have more expensive houses do not imply lower crime. And the total effect of housing values on crime across the city is not significant. So if housing values go up in tracts citywide, there is no statistical evidence that crime will go down (or up).</p>
<p>Try a likelihood ratio test with the null hypothesis being that you should restrict the model.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="thursday-september-29-2022.html#cb68-1" aria-hidden="true" tabindex="-1"></a>spatialreg<span class="sc">::</span><span class="fu">LR.Sarlm</span>(model.sdem, </span>
<span id="cb68-2"><a href="thursday-september-29-2022.html#cb68-2" aria-hidden="true" tabindex="-1"></a>                     model.slxm)</span></code></pre></div>
<pre><code>## 
##  Likelihood ratio for spatial linear models
## 
## data:  
## Likelihood ratio = 4.3832, df = 1, p-value = 0.03629
## sample estimates:
## Log likelihood of model.sdem Log likelihood of model.slxm 
##                    -181.7790                    -183.9706</code></pre>
<p>The relatively small <span class="math inline">\(p\)</span>-value suggests you shouldn’t restrict the spatial Durbin model to just the spatially-lagged X model although the evidence is not overwhelming.</p>
<p>More information</p>
<ul>
<li><a href="https://youtu.be/b3HtV2Mhmvk" class="uri">https://youtu.be/b3HtV2Mhmvk</a></li>
<li><a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2420725" class="uri">https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2420725</a></li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tuesday-september-27-2022.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="tuesday-october-4-2022.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
