<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Thursday April 13, 2023 | GIS5122: Applied Spatial Statistics</title>
  <meta name="description" content="Thursday April 13, 2023 | GIS5122: Applied Spatial Statistics" />
  <meta name="generator" content="bookdown 0.32 and GitBook 2.6.7" />

  <meta property="og:title" content="Thursday April 13, 2023 | GIS5122: Applied Spatial Statistics" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="jelsner/ASS-2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Thursday April 13, 2023 | GIS5122: Applied Spatial Statistics" />
  
  
  

<meta name="author" content="James B. Elsner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tuesday-april-11-2023.html"/>
<link rel="next" href="tuesday-april-18-2023.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied Spatial Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="syllabus-and-set-up.html"><a href="syllabus-and-set-up.html"><i class="fa fa-check"></i>Syllabus and set up</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus-and-set-up.html"><a href="syllabus-and-set-up.html#contact-information"><i class="fa fa-check"></i>Contact information</a></li>
<li class="chapter" data-level="" data-path="syllabus-and-set-up.html"><a href="syllabus-and-set-up.html#course-description-and-expected-learning-outcomes"><i class="fa fa-check"></i>Course description and expected learning outcomes</a></li>
<li class="chapter" data-level="" data-path="syllabus-and-set-up.html"><a href="syllabus-and-set-up.html#grades-and-ethics"><i class="fa fa-check"></i>Grades and ethics</a></li>
<li class="chapter" data-level="" data-path="syllabus-and-set-up.html"><a href="syllabus-and-set-up.html#outline-of-topics-and-schedule"><i class="fa fa-check"></i>Outline of topics and schedule</a></li>
<li class="chapter" data-level="" data-path="syllabus-and-set-up.html"><a href="syllabus-and-set-up.html#reference-materials"><i class="fa fa-check"></i>Reference materials</a></li>
<li class="chapter" data-level="" data-path="syllabus-and-set-up.html"><a href="syllabus-and-set-up.html#reproducible-research"><i class="fa fa-check"></i>Reproducible research</a></li>
<li class="chapter" data-level="" data-path="syllabus-and-set-up.html"><a href="syllabus-and-set-up.html#getting-you-set-up"><i class="fa fa-check"></i>Getting you set up</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-january-12-2023.html"><a href="thursday-january-12-2023.html"><i class="fa fa-check"></i>Thursday, January 12, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-january-12-2023.html"><a href="thursday-january-12-2023.html#important-points-from-the-syllabus"><i class="fa fa-check"></i>Important points from the syllabus</a></li>
<li class="chapter" data-level="" data-path="thursday-january-12-2023.html"><a href="thursday-january-12-2023.html#continue-with-setup"><i class="fa fa-check"></i>Continue with setup</a></li>
<li class="chapter" data-level="" data-path="thursday-january-12-2023.html"><a href="thursday-january-12-2023.html#about-rstudio"><i class="fa fa-check"></i>About RStudio</a></li>
<li class="chapter" data-level="" data-path="thursday-january-12-2023.html"><a href="thursday-january-12-2023.html#lab-assignments"><i class="fa fa-check"></i>Lab assignments</a></li>
<li class="chapter" data-level="" data-path="thursday-january-12-2023.html"><a href="thursday-january-12-2023.html#data-science-workflow-with-r-markdown"><i class="fa fa-check"></i>Data science workflow with R markdown</a></li>
<li class="chapter" data-level="" data-path="thursday-january-12-2023.html"><a href="thursday-january-12-2023.html#getting-started-with-r"><i class="fa fa-check"></i>Getting started with R</a></li>
<li class="chapter" data-level="" data-path="thursday-january-12-2023.html"><a href="thursday-january-12-2023.html#completely-new-to-r"><i class="fa fa-check"></i>Completely new to R?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-january-17-2023.html"><a href="tuesday-january-17-2023.html"><i class="fa fa-check"></i>Tuesday, January 17, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-january-17-2023.html"><a href="tuesday-january-17-2023.html#class-notes"><i class="fa fa-check"></i>Class notes</a></li>
<li class="chapter" data-level="" data-path="tuesday-january-17-2023.html"><a href="tuesday-january-17-2023.html#using-r"><i class="fa fa-check"></i>Using R</a></li>
<li class="chapter" data-level="" data-path="tuesday-january-17-2023.html"><a href="tuesday-january-17-2023.html#data-frames"><i class="fa fa-check"></i>Data frames</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-january-19-2023.html"><a href="thursday-january-19-2023.html"><i class="fa fa-check"></i>Thursday January 19, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-january-19-2023.html"><a href="thursday-january-19-2023.html#getting-data-into-r"><i class="fa fa-check"></i>Getting data into R</a></li>
<li class="chapter" data-level="" data-path="thursday-january-19-2023.html"><a href="thursday-january-19-2023.html#working-with-data-frames-using-functions-from-dplyr"><i class="fa fa-check"></i>Working with data frames using functions from {dplyr}</a></li>
<li class="chapter" data-level="" data-path="thursday-january-19-2023.html"><a href="thursday-january-19-2023.html#making-graphs"><i class="fa fa-check"></i>Making graphs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-january-24-2023.html"><a href="tuesday-january-24-2023.html"><i class="fa fa-check"></i>Tuesday January 24, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-january-24-2023.html"><a href="tuesday-january-24-2023.html#making-graphs-1"><i class="fa fa-check"></i>Making graphs</a></li>
<li class="chapter" data-level="" data-path="tuesday-january-24-2023.html"><a href="tuesday-january-24-2023.html#introduction-to-simple-features"><i class="fa fa-check"></i>Introduction to simple features</a></li>
<li class="chapter" data-level="" data-path="tuesday-january-24-2023.html"><a href="tuesday-january-24-2023.html#geo-computation-on-simple-features"><i class="fa fa-check"></i>Geo-computation on simple features</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-january-31-2023.html"><a href="tuesday-january-31-2023.html"><i class="fa fa-check"></i>Tuesday January 31, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-january-31-2023.html"><a href="tuesday-january-31-2023.html#filtering-selecting-and-conditioning-on-attributes"><i class="fa fa-check"></i>Filtering, selecting, and conditioning on attributes</a></li>
<li class="chapter" data-level="" data-path="tuesday-january-31-2023.html"><a href="tuesday-january-31-2023.html#filtering-on-geographic-boundaries"><i class="fa fa-check"></i>Filtering on geographic boundaries</a></li>
<li class="chapter" data-level="" data-path="tuesday-january-31-2023.html"><a href="tuesday-january-31-2023.html#joining-data-frames"><i class="fa fa-check"></i>Joining data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-january-31-2023.html"><a href="tuesday-january-31-2023.html#interpolating-using-areal-weights"><i class="fa fa-check"></i>Interpolating using areal weights</a></li>
<li class="chapter" data-level="" data-path="tuesday-january-31-2023.html"><a href="tuesday-january-31-2023.html#s4-spatial-data-objects"><i class="fa fa-check"></i>S4 spatial data objects</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-february-2-2023.html"><a href="thursday-february-2-2023.html"><i class="fa fa-check"></i>Thursday February 2, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-february-2-2023.html"><a href="thursday-february-2-2023.html#working-with-raster-data"><i class="fa fa-check"></i>Working with raster data</a></li>
<li class="chapter" data-level="" data-path="thursday-february-2-2023.html"><a href="thursday-february-2-2023.html#working-with-space-time-data"><i class="fa fa-check"></i>Working with space-time data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-february-7-2023.html"><a href="tuesday-february-7-2023.html"><i class="fa fa-check"></i>Tuesday February 7, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-february-7-2023.html"><a href="tuesday-february-7-2023.html#mapping-using-functions-from-the-ggplot2-package"><i class="fa fa-check"></i>Mapping using functions from the {ggplot2} package</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-7-2023.html"><a href="tuesday-february-7-2023.html#mapping-using-functions-from-the-tmap-package"><i class="fa fa-check"></i>Mapping using functions from the {tmap} package</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-7-2023.html"><a href="tuesday-february-7-2023.html#creating-an-interactive-map"><i class="fa fa-check"></i>Creating an interactive map</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-7-2023.html"><a href="tuesday-february-7-2023.html#isolines-and-isobands"><i class="fa fa-check"></i>Isolines and isobands</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-7-2023.html"><a href="tuesday-february-7-2023.html#hillshape-and-colors-with-tidyterra"><i class="fa fa-check"></i>Hillshape and colors with tidyterra</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-7-2023.html"><a href="tuesday-february-7-2023.html#visualizing-spatial-data"><i class="fa fa-check"></i>Visualizing spatial data</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-7-2023.html"><a href="tuesday-february-7-2023.html#adding-an-inset-map"><i class="fa fa-check"></i>Adding an inset map</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-7-2023.html"><a href="tuesday-february-7-2023.html#making-maps-with-rdeck"><i class="fa fa-check"></i>Making maps with rdeck</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-february-14-2023.html"><a href="tuesday-february-14-2023.html"><i class="fa fa-check"></i>Tuesday February 14, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-february-14-2023.html"><a href="tuesday-february-14-2023.html#defining-spatial-neighborhoods-and-spatial-weights"><i class="fa fa-check"></i>Defining spatial neighborhoods and spatial weights</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-14-2023.html"><a href="tuesday-february-14-2023.html#computing-autocorrelation"><i class="fa fa-check"></i>Computing autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-14-2023.html"><a href="tuesday-february-14-2023.html#relating-autocorrelation-to-the-spatial-lag-variable"><i class="fa fa-check"></i>Relating autocorrelation to the spatial lag variable</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-february-16-2023.html"><a href="thursday-february-16-2023.html"><i class="fa fa-check"></i>Thursday February 16, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-february-16-2023.html"><a href="thursday-february-16-2023.html#defining-neighborhoods"><i class="fa fa-check"></i>Defining neighborhoods</a></li>
<li class="chapter" data-level="" data-path="thursday-february-16-2023.html"><a href="thursday-february-16-2023.html#assessing-the-statistical-significance-of-autocorrelation"><i class="fa fa-check"></i>Assessing the statistical significance of autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-february-16-2023.html"><a href="thursday-february-16-2023.html#computing-and-interpreting-bivariate-spatial-autocorrelation"><i class="fa fa-check"></i>Computing and interpreting bivariate spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-february-16-2023.html"><a href="thursday-february-16-2023.html#assessing-local-indicators-of-spatial-autocorrelation"><i class="fa fa-check"></i>Assessing local indicators of spatial autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-february-21-2023.html"><a href="tuesday-february-21-2023.html"><i class="fa fa-check"></i>Tuesday February 21, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-february-21-2023.html"><a href="tuesday-february-21-2023.html#using-local-spatial-autocorrelation-to-understand-the-tornado-record"><i class="fa fa-check"></i>Using local spatial autocorrelation to understand the tornado record</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-21-2023.html"><a href="tuesday-february-21-2023.html#constraining-group-membership-based-on-spatial-autocorrelation"><i class="fa fa-check"></i>Constraining group membership based on spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-21-2023.html"><a href="tuesday-february-21-2023.html#estimating-spatial-autocorrelation-in-model-residuals"><i class="fa fa-check"></i>Estimating spatial autocorrelation in model residuals</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-21-2023.html"><a href="tuesday-february-21-2023.html#choosing-a-spatial-regression-model"><i class="fa fa-check"></i>Choosing a spatial regression model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-february-23-2023.html"><a href="thursday-february-23-2023.html"><i class="fa fa-check"></i>Thursday February 23, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-february-23-2023.html"><a href="thursday-february-23-2023.html#fitting-and-interpreting-spatial-regression-models"><i class="fa fa-check"></i>Fitting and interpreting spatial regression models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-february-28-2023.html"><a href="tuesday-february-28-2023.html"><i class="fa fa-check"></i>Tuesday February 28, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-february-28-2023.html"><a href="tuesday-february-28-2023.html#fitting-and-interpreting-geographic-regression"><i class="fa fa-check"></i>Fitting and interpreting geographic regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-28-2023.html"><a href="tuesday-february-28-2023.html#mapping-incidence-and-risk-with-a-spatial-regression-model"><i class="fa fa-check"></i>Mapping incidence and risk with a spatial regression model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-march-7-2023.html"><a href="tuesday-march-7-2023.html"><i class="fa fa-check"></i>Tuesday March 7, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-march-7-2023.html"><a href="tuesday-march-7-2023.html#spatial-data-interpolation"><i class="fa fa-check"></i>Spatial data interpolation</a></li>
<li class="chapter" data-level="" data-path="tuesday-march-7-2023.html"><a href="tuesday-march-7-2023.html#computing-the-sample-variogram"><i class="fa fa-check"></i>Computing the sample variogram</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-march-9-2023.html"><a href="thursday-march-9-2023.html"><i class="fa fa-check"></i>Thursday March 9, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-march-9-2023.html"><a href="thursday-march-9-2023.html#fitting-a-variogram-model-to-the-sample-variogram"><i class="fa fa-check"></i>Fitting a variogram model to the sample variogram</a></li>
<li class="chapter" data-level="" data-path="thursday-march-9-2023.html"><a href="thursday-march-9-2023.html#creating-an-interpolated-surface-with-the-method-of-kriging"><i class="fa fa-check"></i>Creating an interpolated surface with the method of kriging</a></li>
<li class="chapter" data-level="" data-path="thursday-march-9-2023.html"><a href="thursday-march-9-2023.html#comparing-interpolation-methods"><i class="fa fa-check"></i>Comparing interpolation methods</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-march-21-2023.html"><a href="tuesday-march-21-2023.html"><i class="fa fa-check"></i>Tuesday March 21, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-march-21-2023.html"><a href="tuesday-march-21-2023.html#evaluating-interpolation-accuracy"><i class="fa fa-check"></i>Evaluating interpolation accuracy</a></li>
<li class="chapter" data-level="" data-path="tuesday-march-21-2023.html"><a href="tuesday-march-21-2023.html#block-cross-validation"><i class="fa fa-check"></i>Block cross validation</a></li>
<li class="chapter" data-level="" data-path="tuesday-march-21-2023.html"><a href="tuesday-march-21-2023.html#interpolating-to-areal-units-block-kriging"><i class="fa fa-check"></i>Interpolating to areal units (block kriging)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-march-28-2023.html"><a href="tuesday-march-28-2023.html"><i class="fa fa-check"></i>Tuesday March 28, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-march-28-2023.html"><a href="tuesday-march-28-2023.html#interpolating-multiple-variables"><i class="fa fa-check"></i>Interpolating multiple variables</a></li>
<li class="chapter" data-level="" data-path="tuesday-march-28-2023.html"><a href="tuesday-march-28-2023.html#machine-learning-for-spatial-interpolation"><i class="fa fa-check"></i>Machine learning for spatial interpolation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-april-4-2023.html"><a href="tuesday-april-4-2023.html"><i class="fa fa-check"></i>Tuesday April 4, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-april-4-2023.html"><a href="tuesday-april-4-2023.html#spatial-data-as-point-patterns"><i class="fa fa-check"></i>Spatial data as point patterns</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-4-2023.html"><a href="tuesday-april-4-2023.html#theoretical-framework-for-analyzingmodeling-point-pattern-data"><i class="fa fa-check"></i>Theoretical framework for analyzing/modeling point pattern data</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-4-2023.html"><a href="tuesday-april-4-2023.html#working-with-point-pattern-data-using-functions-from-the-spatstat-family-of-packages"><i class="fa fa-check"></i>Working with point pattern data using functions from the spatstat family of packages</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-4-2023.html"><a href="tuesday-april-4-2023.html#quantifying-the-spatial-intensity-of-events"><i class="fa fa-check"></i>Quantifying the spatial intensity of events</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-april-6-2023.html"><a href="thursday-april-6-2023.html"><i class="fa fa-check"></i>Thursday April 6, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-april-6-2023.html"><a href="thursday-april-6-2023.html#creating-ppp-and-owin-objects-from-simple-feature-data-frames"><i class="fa fa-check"></i>Creating <code>ppp</code> and <code>owin</code> objects from simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="thursday-april-6-2023.html"><a href="thursday-april-6-2023.html#estimating-spatial-intensity-as-a-function-of-distance"><i class="fa fa-check"></i>Estimating spatial intensity as a function of distance</a></li>
<li class="chapter" data-level="" data-path="thursday-april-6-2023.html"><a href="thursday-april-6-2023.html#covariate-trend-as-a-possible-confounding-factor"><i class="fa fa-check"></i>Covariate trend as a possible confounding factor</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-april-11-2023.html"><a href="tuesday-april-11-2023.html"><i class="fa fa-check"></i>Tuesday April 11, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-april-11-2023.html"><a href="tuesday-april-11-2023.html#estimating-the-relative-risk-of-an-event"><i class="fa fa-check"></i>Estimating the relative risk of an event</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-11-2023.html"><a href="tuesday-april-11-2023.html#estimating-second-moment-properties-of-events"><i class="fa fa-check"></i>Estimating second-moment properties of events</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-11-2023.html"><a href="tuesday-april-11-2023.html#examples-of-clustered-events"><i class="fa fa-check"></i>Examples of clustered events</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-april-13-2023.html"><a href="thursday-april-13-2023.html"><i class="fa fa-check"></i>Thursday April 13, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-april-13-2023.html"><a href="thursday-april-13-2023.html#removing-duplicate-events-and-defining-the-domain"><i class="fa fa-check"></i>Removing duplicate events and defining the domain</a></li>
<li class="chapter" data-level="" data-path="thursday-april-13-2023.html"><a href="thursday-april-13-2023.html#determining-statistical-significance-of-clustering"><i class="fa fa-check"></i>Determining statistical significance of clustering</a></li>
<li class="chapter" data-level="" data-path="thursday-april-13-2023.html"><a href="thursday-april-13-2023.html#estimating-clustering-in-multi-type-event-locations"><i class="fa fa-check"></i>Estimating clustering in multi-type event locations</a></li>
<li class="chapter" data-level="" data-path="thursday-april-13-2023.html"><a href="thursday-april-13-2023.html#interpolating-output-from-a-distance-function"><i class="fa fa-check"></i>Interpolating output from a distance function</a></li>
<li class="chapter" data-level="" data-path="thursday-april-13-2023.html"><a href="thursday-april-13-2023.html#limitations-of-the-distance-functions"><i class="fa fa-check"></i>Limitations of the distance functions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-april-18-2023.html"><a href="tuesday-april-18-2023.html"><i class="fa fa-check"></i>Tuesday April 18, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-april-18-2023.html"><a href="tuesday-april-18-2023.html#limitations-on-interpreting-distance-functions"><i class="fa fa-check"></i>Limitations on interpreting distance functions</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-18-2023.html"><a href="tuesday-april-18-2023.html#models-for-point-pattern-data"><i class="fa fa-check"></i>Models for point pattern data</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-18-2023.html"><a href="tuesday-april-18-2023.html#fitting-and-interpreting-inhibition-models"><i class="fa fa-check"></i>Fitting and interpreting inhibition models</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-18-2023.html"><a href="tuesday-april-18-2023.html#fitting-and-interpreting-cluster-models"><i class="fa fa-check"></i>Fitting and interpreting cluster models</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-18-2023.html"><a href="tuesday-april-18-2023.html#assessing-how-well-the-model-fits"><i class="fa fa-check"></i>Assessing how well the model fits</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-april-25-2023.html"><a href="tuesday-april-25-2023.html"><i class="fa fa-check"></i>Tuesday April 25, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-april-25-2023.html"><a href="tuesday-april-25-2023.html#fitting-a-log-gaussian-cox-model"><i class="fa fa-check"></i>Fitting a log-Gaussian Cox model</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-25-2023.html"><a href="tuesday-april-25-2023.html#assessing-how-well-a-point-pattern-model-fits-the-data"><i class="fa fa-check"></i>Assessing how well a point pattern model fits the data</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-25-2023.html"><a href="tuesday-april-25-2023.html#an-example-of-a-point-process-model-in-the-wild"><i class="fa fa-check"></i>An example of a point process model in the wild</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-25-2023.html"><a href="tuesday-april-25-2023.html#spatial-logistic-regression"><i class="fa fa-check"></i>Spatial logistic regression</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GIS5122: Applied Spatial Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="thursday-april-13-2023" class="section level1 unnumbered hasAnchor">
<h1>Thursday April 13, 2023<a href="thursday-april-13-2023.html#thursday-april-13-2023" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>“Good code is its own best documentation. As you’re about to add a comment, ask yourself, ‘How can I improve the code so that this comment isn’t needed?’ Improve the code and then document it to make it even clearer.”</strong> - Steve McConnell</p>
<div id="removing-duplicate-events-and-defining-the-domain" class="section level2 unnumbered hasAnchor">
<h2>Removing duplicate events and defining the domain<a href="thursday-april-13-2023.html#removing-duplicate-events-and-defining-the-domain" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Functions from the {spatstat} family of packages require the event locations (as a <code>ppp</code> object) and a domain over which the spatial statistics are computed (as an <code>owin</code> object)</p>
<p>If no <code>owin</code> object is specified the default is a rectangular bounding box defined by the northern, southern, eastern, and western most event locations</p>
<p>Consider the Florida wildfire data as a simple feature data frame. Import the Florida wildfire data from here <a href="http://myweb.fsu.edu/jelsner/temp/data/FL_Fires.zip" class="uri">http://myweb.fsu.edu/jelsner/temp/data/FL_Fires.zip</a> as a simple feature data frame called <code>FL_Fires.sf</code> and transform the native CRS to a Florida GDL Albers projected CRS (EPSG 3086).</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="thursday-april-13-2023.html#cb1-1" aria-hidden="true" tabindex="-1"></a>FL_Fires.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="at">dsn =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;FL_Fires&quot;</span>)) <span class="sc">|&gt;</span></span>
<span id="cb1-2"><a href="thursday-april-13-2023.html#cb1-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3086</span>)</span></code></pre></div>
<pre><code>## Reading layer `FL_Fires&#39; from data source 
##   `/Users/jelsner/Desktop/ClassNotes/ASS-2023/data/FL_Fires&#39; 
##   using driver `ESRI Shapefile&#39;
## Simple feature collection with 90261 features and 37 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -9750382 ymin: 2824449 xmax: -8908899 ymax: 3632749
## Projected CRS: Mercator_2SP</code></pre>
<p>Keep only fires occurring in Baker County (west of Jacksonville)</p>
<p>Use the <code>us_counties()</code> function with <code>resolution = "high"</code> from the {USAboundaries} package to get county boundaries in Florida as a simple feature data frame. Then select on the variable <code>name</code> before filtering on the variable <code>name</code> to keep only the boundary of Liberty County. Transform the native CRS to EPSG 3086. Assign the resulting simple feature data frame the name <code>Baker.sf</code></p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="thursday-april-13-2023.html#cb3-1" aria-hidden="true" tabindex="-1"></a>Baker.sf <span class="ot">&lt;-</span> USAboundaries<span class="sc">::</span><span class="fu">us_counties</span>(<span class="at">states =</span> <span class="st">&quot;FL&quot;</span>,</span>
<span id="cb3-2"><a href="thursday-april-13-2023.html#cb3-2" aria-hidden="true" tabindex="-1"></a>                                       <span class="at">resolution =</span> <span class="st">&quot;high&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb3-3"><a href="thursday-april-13-2023.html#cb3-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(name) <span class="sc">|&gt;</span></span>
<span id="cb3-4"><a href="thursday-april-13-2023.html#cb3-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(name <span class="sc">==</span> <span class="st">&quot;Baker&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb3-5"><a href="thursday-april-13-2023.html#cb3-5" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3086</span>)</span></code></pre></div>
<p>Extract the wildfires from <code>FL_Fires.sf</code> that intersect Baker County then filter by lightning and select the fire size variable</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="thursday-april-13-2023.html#cb4-1" aria-hidden="true" tabindex="-1"></a>BakerFires.sf <span class="ot">&lt;-</span> FL_Fires.sf <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="thursday-april-13-2023.html#cb4-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_intersection</span>(Baker.sf) <span class="sc">|&gt;</span></span>
<span id="cb4-3"><a href="thursday-april-13-2023.html#cb4-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(STAT_CAU_1 <span class="sc">==</span> <span class="st">&quot;Lightning&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb4-4"><a href="thursday-april-13-2023.html#cb4-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(FIRE_SIZE_)</span></code></pre></div>
<pre><code>## Warning: attribute variables are assumed to be spatially constant throughout
## all geometries</code></pre>
<p>Create and summarize an unmarked <code>ppp</code> object</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="thursday-april-13-2023.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spatstat)</span></code></pre></div>
<pre><code>## Loading required package: spatstat.data</code></pre>
<pre><code>## Loading required package: spatstat.geom</code></pre>
<pre><code>## spatstat.geom 3.0-6</code></pre>
<pre><code>## Loading required package: spatstat.random</code></pre>
<pre><code>## spatstat.random 3.1-3</code></pre>
<pre><code>## Loading required package: spatstat.explore</code></pre>
<pre><code>## Loading required package: nlme</code></pre>
<pre><code>## spatstat.explore 3.0-6</code></pre>
<pre><code>## Loading required package: spatstat.model</code></pre>
<pre><code>## Loading required package: rpart</code></pre>
<pre><code>## spatstat.model 3.1-2</code></pre>
<pre><code>## Loading required package: spatstat.linnet</code></pre>
<pre><code>## spatstat.linnet 3.0-4</code></pre>
<pre><code>## 
## spatstat 3.0-3 
## For an introduction to spatstat, type &#39;beginner&#39;</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="thursday-april-13-2023.html#cb21-1" aria-hidden="true" tabindex="-1"></a>BF.ppp <span class="ot">&lt;-</span> BakerFires.sf <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="thursday-april-13-2023.html#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.ppp</span>() <span class="sc">|&gt;</span></span>
<span id="cb21-3"><a href="thursday-april-13-2023.html#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unmark</span>() </span>
<span id="cb21-4"><a href="thursday-april-13-2023.html#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="thursday-april-13-2023.html#cb21-5" aria-hidden="true" tabindex="-1"></a>BF.ppp <span class="sc">|&gt;</span></span>
<span id="cb21-6"><a href="thursday-april-13-2023.html#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## Planar point pattern:  327 points
## Average intensity 1.801742e-07 points per square unit
## 
## *Pattern contains duplicated points*
## 
## Coordinates are given to 2 decimal places
## i.e. rounded to the nearest multiple of 0.01 units
## 
## Window: rectangle = [548071.4, 587567.5] x [682872.2, 728823.8] units
##                     (39500 x 45950 units)
## Window area = 1814910000 square units</code></pre>
<p>There are 327 events (wildfires). This is an average intensity of 18 wildfires per 10 square km (.18 X 100 = 18). The pattern also contains duplicated events</p>
<p>The average intensity is based on a square domain</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="thursday-april-13-2023.html#cb23-1" aria-hidden="true" tabindex="-1"></a>BF.ppp <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="thursday-april-13-2023.html#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>The lack of events in the northeast part of the domain is because you previously removed wildfires outside the county border</p>
<p>Further there are duplicated events. Events are duplicated if their locations x,y coordinates are the same, and their marks are the same. Whether you remove them depends on your knowledge of what they are and how the data were collected</p>
<p>Here you remove duplicate events with the <code>unique()</code> function. You then create a window (<code>W</code>) from the <code>Baker.sf</code> simple feature data frame and subset the <code>BF.ppp</code> object by that window</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="thursday-april-13-2023.html#cb24-1" aria-hidden="true" tabindex="-1"></a>BF.ppp <span class="ot">&lt;-</span> BF.ppp <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="thursday-april-13-2023.html#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>()</span>
<span id="cb24-3"><a href="thursday-april-13-2023.html#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="thursday-april-13-2023.html#cb24-4" aria-hidden="true" tabindex="-1"></a>W <span class="ot">&lt;-</span> Baker.sf <span class="sc">|&gt;</span></span>
<span id="cb24-5"><a href="thursday-april-13-2023.html#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.owin</span>()</span>
<span id="cb24-6"><a href="thursday-april-13-2023.html#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="thursday-april-13-2023.html#cb24-7" aria-hidden="true" tabindex="-1"></a>BF.ppp <span class="ot">&lt;-</span> BF.ppp[W]</span>
<span id="cb24-8"><a href="thursday-april-13-2023.html#cb24-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-9"><a href="thursday-april-13-2023.html#cb24-9" aria-hidden="true" tabindex="-1"></a>BF.ppp <span class="ot">&lt;-</span> BF.ppp <span class="sc">|&gt;</span></span>
<span id="cb24-10"><a href="thursday-april-13-2023.html#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rescale</span>(<span class="at">s =</span> <span class="dv">1000</span>,</span>
<span id="cb24-11"><a href="thursday-april-13-2023.html#cb24-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">unitname =</span> <span class="st">&quot;km&quot;</span>)</span>
<span id="cb24-12"><a href="thursday-april-13-2023.html#cb24-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-13"><a href="thursday-april-13-2023.html#cb24-13" aria-hidden="true" tabindex="-1"></a>BF.ppp <span class="sc">|&gt;</span></span>
<span id="cb24-14"><a href="thursday-april-13-2023.html#cb24-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>Summarize the resulting <code>ppp</code> object.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="thursday-april-13-2023.html#cb25-1" aria-hidden="true" tabindex="-1"></a>BF.ppp <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="thursday-april-13-2023.html#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## Planar point pattern:  322 points
## Average intensity 0.2111427 points per square km
## 
## Coordinates are given to 5 decimal places
## 
## Window: polygonal boundary
## single connected closed polygon with 109 vertices
## enclosing rectangle: [547.5882, 587.6825] x [681.9546, 731.6515] km
##                      (40.09 x 49.7 km)
## Window area = 1525.04 square km
## Unit of length: 1 km
## Fraction of frame area: 0.765</code></pre>
<p>Now the average intensity is 21 wildfires per 10 square kilometers, which is a better estimate of the wildfire occurrence rates at the county level</p>
</div>
<div id="determining-statistical-significance-of-clustering" class="section level2 unnumbered hasAnchor">
<h2>Determining statistical significance of clustering<a href="thursday-april-13-2023.html#determining-statistical-significance-of-clustering" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>With event distance functions like G, F, and K computed on <code>ppp</code> objects from the {statspat} family of packages, the default plot method is to show a black curve and a red curve. The black curve is the function computed from the data and the red curve is the function computed from a model of CSR</p>
<p>When you see a separation between the black and red curve, you should ask “Is this separation large relative to sampling variation?” Said another way. Is the difference between the empirical and theoretical distance curves large enough to conclude there is significant clustering?</p>
<p>There are two ways to approach statistical inference</p>
<ol style="list-style-type: decimal">
<li><p>Compare the curve computed with the observed data against curves computed with data generated under the null hypothesis and ask: “does the curve fall outside the envelope of curves from the null cases?”</p></li>
<li><p>Get estimates of uncertainty on the curve and ask: “does the uncertainty interval contain the null curve?”</p></li>
</ol>
<p>With the first approach you take a <code>ppp</code> object and then compute the curve of interest (e.g., Ripley’s K) for a specified number of samples under the null hypothesis of a homogeneous Poisson process</p>
<p>Returning again to the Kansas tornado reports since 1994</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="thursday-april-13-2023.html#cb27-1" aria-hidden="true" tabindex="-1"></a>Torn.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="at">dsn =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, </span>
<span id="cb27-2"><a href="thursday-april-13-2023.html#cb27-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">&quot;1950-2021-torn-initpoint&quot;</span>)) <span class="sc">|&gt;</span></span>
<span id="cb27-3"><a href="thursday-april-13-2023.html#cb27-3" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3082</span>) <span class="sc">|&gt;</span></span>
<span id="cb27-4"><a href="thursday-april-13-2023.html#cb27-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(mag <span class="sc">&gt;=</span> <span class="dv">0</span>, yr <span class="sc">&gt;=</span> <span class="dv">1994</span>) <span class="sc">|&gt;</span></span>
<span id="cb27-5"><a href="thursday-april-13-2023.html#cb27-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">EF =</span> <span class="fu">as.factor</span>(mag)) <span class="sc">|&gt;</span></span>
<span id="cb27-6"><a href="thursday-april-13-2023.html#cb27-6" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(EF)</span></code></pre></div>
<pre><code>## Reading layer `1950-2021-torn-initpoint&#39; from data source 
##   `/Users/jelsner/Desktop/ClassNotes/ASS-2023/data/1950-2021-torn-initpoint&#39; 
##   using driver `ESRI Shapefile&#39;
## Simple feature collection with 67558 features and 22 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -163.53 ymin: 17.7212 xmax: -64.7151 ymax: 61.02
## Geodetic CRS:  WGS 84</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="thursday-april-13-2023.html#cb29-1" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="ot">&lt;-</span> Torn.sf[<span class="st">&quot;EF&quot;</span>] <span class="sc">|&gt;</span></span>
<span id="cb29-2"><a href="thursday-april-13-2023.html#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.ppp</span>()</span>
<span id="cb29-3"><a href="thursday-april-13-2023.html#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="thursday-april-13-2023.html#cb29-4" aria-hidden="true" tabindex="-1"></a>KS.sf <span class="ot">&lt;-</span> USAboundaries<span class="sc">::</span><span class="fu">us_states</span>(<span class="at">states =</span> <span class="st">&quot;Kansas&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb29-5"><a href="thursday-april-13-2023.html#cb29-5" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> sf<span class="sc">::</span><span class="fu">st_crs</span>(Torn.sf)<span class="sc">$</span>proj4string)</span>
<span id="cb29-6"><a href="thursday-april-13-2023.html#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="thursday-april-13-2023.html#cb29-7" aria-hidden="true" tabindex="-1"></a>W <span class="ot">&lt;-</span> KS.sf <span class="sc">|&gt;</span></span>
<span id="cb29-8"><a href="thursday-april-13-2023.html#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.owin</span>()</span>
<span id="cb29-9"><a href="thursday-april-13-2023.html#cb29-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-10"><a href="thursday-april-13-2023.html#cb29-10" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="ot">&lt;-</span> T.ppp[W] <span class="sc">|&gt;</span></span>
<span id="cb29-11"><a href="thursday-april-13-2023.html#cb29-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rescale</span>(<span class="at">s =</span> <span class="dv">1000</span>, </span>
<span id="cb29-12"><a href="thursday-april-13-2023.html#cb29-12" aria-hidden="true" tabindex="-1"></a>          <span class="at">unitname =</span> <span class="st">&quot;km&quot;</span>)</span></code></pre></div>
<p>To make things run faster you consider a subset of all the tornadoes (those that have an EF rating of 2 or higher). You create a new <code>ppp</code> object that contains only tornadoes rated at least EF2. Since the marks is a factor vector you can’t use <code>&gt;=</code></p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="thursday-april-13-2023.html#cb30-1" aria-hidden="true" tabindex="-1"></a>ST.ppp <span class="ot">&lt;-</span> T.ppp[T.ppp<span class="sc">$</span>marks <span class="sc">==</span> <span class="dv">2</span> <span class="sc">|</span> </span>
<span id="cb30-2"><a href="thursday-april-13-2023.html#cb30-2" aria-hidden="true" tabindex="-1"></a>                T.ppp<span class="sc">$</span>marks <span class="sc">==</span> <span class="dv">3</span> <span class="sc">|</span> </span>
<span id="cb30-3"><a href="thursday-april-13-2023.html#cb30-3" aria-hidden="true" tabindex="-1"></a>                T.ppp<span class="sc">$</span>marks <span class="sc">==</span> <span class="dv">4</span> <span class="sc">|</span></span>
<span id="cb30-4"><a href="thursday-april-13-2023.html#cb30-4" aria-hidden="true" tabindex="-1"></a>                T.ppp<span class="sc">$</span>marks <span class="sc">==</span> <span class="dv">5</span>] <span class="sc">|&gt;</span></span>
<span id="cb30-5"><a href="thursday-april-13-2023.html#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unmark</span>()</span></code></pre></div>
<p>Plot a map displaying the local intensity and include the event locations. The <code>plot()</code> method applied to the output of the <code>density()</code> function and applied to the <code>ppp</code> object will produce such a map</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="thursday-april-13-2023.html#cb31-1" aria-hidden="true" tabindex="-1"></a>ST.ppp <span class="sc">|&gt;</span></span>
<span id="cb31-2"><a href="thursday-april-13-2023.html#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">density</span>() <span class="sc">|&gt;</span></span>
<span id="cb31-3"><a href="thursday-april-13-2023.html#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span>
<span id="cb31-4"><a href="thursday-april-13-2023.html#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="thursday-april-13-2023.html#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ST.ppp,</span>
<span id="cb31-6"><a href="thursday-april-13-2023.html#cb31-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="st">&#39;.&#39;</span>,</span>
<span id="cb31-7"><a href="thursday-april-13-2023.html#cb31-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">add =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Compute the nearest neighbor function (<span class="math inline">\(G\)</span>) using the <code>Gest()</code> function with a Kaplan-Meier correction for the borders (i.e., <code>correction = "km"</code>). Make a plot of this function that also includes a theoretical curve under the null hypothesis of complete spatial randomness. From the plot eyeball an estimate of the percentage of tornadoes there are within 15 km of another tornado</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="thursday-april-13-2023.html#cb32-1" aria-hidden="true" tabindex="-1"></a>ST.ppp <span class="sc">|&gt;</span></span>
<span id="cb32-2"><a href="thursday-april-13-2023.html#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Gest</span>(<span class="at">correction =</span> <span class="st">&quot;km&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb32-3"><a href="thursday-april-13-2023.html#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>() </span>
<span id="cb32-4"><a href="thursday-april-13-2023.html#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">15</span>, </span>
<span id="cb32-5"><a href="thursday-april-13-2023.html#cb32-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="st">&quot;black&quot;</span>,</span>
<span id="cb32-6"><a href="thursday-april-13-2023.html#cb32-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>Alternatively you can examine the case for clustering using the autocorrelation function (<span class="math inline">\(K\)</span>). Here you compute the autocorrelation function with the <code>Kest()</code> function using the border correction method of Ripley (<code>correction = "Ripley"</code>). You convert the output to a data frame with the <code>as.data.frame()</code> function</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="thursday-april-13-2023.html#cb33-1" aria-hidden="true" tabindex="-1"></a>K.df <span class="ot">&lt;-</span> ST.ppp <span class="sc">|&gt;</span></span>
<span id="cb33-2"><a href="thursday-april-13-2023.html#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Kest</span>(<span class="at">correction =</span> <span class="st">&quot;Ripley&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb33-3"><a href="thursday-april-13-2023.html#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span>
<span id="cb33-4"><a href="thursday-april-13-2023.html#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="thursday-april-13-2023.html#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(K.df)</span></code></pre></div>
<pre><code>##           r       theo      iso
## 1 0.0000000 0.00000000  0.00000
## 2 0.1677738 0.08842974 12.95845
## 3 0.3355477 0.35371897 12.95845
## 4 0.5033215 0.79586769 12.95845
## 5 0.6710954 1.41487589 12.95845
## 6 0.8388692 2.21074358 12.95845</code></pre>
<p>The resulting data frame contains values for distance (<code>r</code>), the model (<code>theo</code>) and the border-corrected data estimates (<code>iso</code>)</p>
<p>You then multiply the estimates from the data and from the model by the average intensity and send the output to <code>ggplot()</code> where you map the distance to the x aesthetic and the K estimates to the y aesthetic</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="thursday-april-13-2023.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb35-2"><a href="thursday-april-13-2023.html#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="thursday-april-13-2023.html#cb35-3" aria-hidden="true" tabindex="-1"></a>K.df <span class="sc">|&gt;</span></span>
<span id="cb35-4"><a href="thursday-april-13-2023.html#cb35-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Kdata =</span> iso <span class="sc">*</span> <span class="fu">intensity</span>(ST.ppp),</span>
<span id="cb35-5"><a href="thursday-april-13-2023.html#cb35-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">Kpois =</span> theo <span class="sc">*</span> <span class="fu">intensity</span>(ST.ppp)) <span class="sc">|&gt;</span></span>
<span id="cb35-6"><a href="thursday-april-13-2023.html#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> Kdata)) <span class="sc">+</span></span>
<span id="cb35-7"><a href="thursday-april-13-2023.html#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb35-8"><a href="thursday-april-13-2023.html#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">y =</span> Kpois), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb35-9"><a href="thursday-april-13-2023.html#cb35-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">50</span>, <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb35-10"><a href="thursday-april-13-2023.html#cb35-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r) * lambda&quot;</span>) <span class="sc">+</span></span>
<span id="cb35-11"><a href="thursday-april-13-2023.html#cb35-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="at">label =</span> <span class="st">&quot;Expected number of additional tornadoes within a distance r of any tornado&quot;</span>) <span class="sc">+</span></span>
<span id="cb35-12"><a href="thursday-april-13-2023.html#cb35-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>If the tornadoes were CSR we would expect about 6 additional tornadoes within a distance of 50 km from any tornado. We see that at this distance there are about 10 additional tornadoes</p>
<p>The above plots of <span class="math inline">\(G\)</span> and <span class="math inline">\(K\)</span> show differences between the curve computed from the data and the curve computed from the null hypothesis model for CSR</p>
<p>Is this difference significant? Or more precisely, how much evidence is there in support of the null hypothesis of CSR?</p>
<p>The <code>envelope()</code> method from the {spatstat} family of packages is used to help answer this question. You specify the function with the <code>fun = Kest</code> argument and the number of samples with the <code>nsim =</code> argument</p>
<p>You then convert the output to a data frame. It takes a few seconds to complete the computation of <span class="math inline">\(K\)</span> for all 99 samples</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="thursday-april-13-2023.html#cb36-1" aria-hidden="true" tabindex="-1"></a>Kenv.df <span class="ot">&lt;-</span> <span class="fu">envelope</span>(ST.ppp, </span>
<span id="cb36-2"><a href="thursday-april-13-2023.html#cb36-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">fun =</span> Kest, </span>
<span id="cb36-3"><a href="thursday-april-13-2023.html#cb36-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">nsim =</span> <span class="dv">99</span>) <span class="sc">|&gt;</span></span>
<span id="cb36-4"><a href="thursday-april-13-2023.html#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>## Generating 99 simulations of CSR  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
## 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,  99.
## 
## Done.</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="thursday-april-13-2023.html#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Kenv.df)</span></code></pre></div>
<pre><code>##           r      obs       theo lo       hi
## 1 0.0000000  0.00000 0.00000000  0  0.00000
## 2 0.1677738 12.95845 0.08842974  0 12.14663
## 3 0.3355477 12.95845 0.35371897  0 13.10164
## 4 0.5033215 12.95845 0.79586769  0 13.10164
## 5 0.6710954 12.95845 1.41487589  0 26.20328
## 6 0.8388692 12.95845 2.21074358  0 26.20328</code></pre>
<p>The resulting data frame contains estimates of <span class="math inline">\(K\)</span> as a function of lag distance (<code>r</code>) (column labeled <code>obs</code>). It also has the estimates of <span class="math inline">\(K\)</span> as a function of lag distance under the null hypothesis of CSR (<code>theo</code>) and the lowest (<code>lo</code>) and highest (<code>hi</code>) values of <span class="math inline">\(K\)</span> across the 99 samples</p>
<p>You plot this information using the <code>geom_ribbon()</code> layer. This adds a gray ribbon around the model for CSR</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="thursday-april-13-2023.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Kenv.df, </span>
<span id="cb40-2"><a href="thursday-april-13-2023.html#cb40-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> obs <span class="sc">*</span> <span class="fu">intensity</span>(ST.ppp))) <span class="sc">+</span></span>
<span id="cb40-3"><a href="thursday-april-13-2023.html#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">ymin =</span> lo <span class="sc">*</span> <span class="fu">intensity</span>(ST.ppp), </span>
<span id="cb40-4"><a href="thursday-april-13-2023.html#cb40-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">ymax =</span> hi <span class="sc">*</span> <span class="fu">intensity</span>(ST.ppp)), </span>
<span id="cb40-5"><a href="thursday-april-13-2023.html#cb40-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb40-6"><a href="thursday-april-13-2023.html#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb40-7"><a href="thursday-april-13-2023.html#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo <span class="sc">*</span> <span class="fu">intensity</span>(ST.ppp)), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb40-8"><a href="thursday-april-13-2023.html#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r) * lambda&quot;</span>) <span class="sc">+</span></span>
<span id="cb40-9"><a href="thursday-april-13-2023.html#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Again the black line is the <span class="math inline">\(K\)</span> function computed on the tornado report locations data and the red line is the same function under CSR. The uncertainty ribbon (gray band) connects the point-wise minimum and maximum values of the <span class="math inline">\(K\)</span> curves computed from the 99 generated point pattern samples</p>
<p>Since the black line lies outside the gray band you can confidently conclude that the tornado reports are <em>more</em> clustered than one would expect by chance</p>
<p>To directly test the null hypothesis of CSR you need a statistic indicating the departure of <span class="math inline">\(K\)</span> (or any other distance curve) computed on the observations from the theoretical <span class="math inline">\(K\)</span></p>
<p>One statistic is the maximum absolute deviation (MAD) implemented with the <code>mad.test()</code> function from the {spatstat} family of packages. The function performs a hypothesis test for the null hypothesis that point pattern is CSR. The larger the value of the statistic, the less likely it is that the data are CSR and the evidence in support of the null is given by the <span class="math inline">\(p\)</span> value on that statistic.</p>
<p>Here you use the test on the <span class="math inline">\(G\)</span> function with the <code>fun = Gest</code> argument and 999 simulations</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="thursday-april-13-2023.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mad.test</span>(ST.ppp, </span>
<span id="cb41-2"><a href="thursday-april-13-2023.html#cb41-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">fun =</span> Gest, </span>
<span id="cb41-3"><a href="thursday-april-13-2023.html#cb41-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">nsim =</span> <span class="dv">999</span>)</span></code></pre></div>
<pre><code>## Generating 999 simulations of CSR  ...
## 1, 2, 3, ......10.........20.........30.........40.........50.........60........
## .70.........80.........90.........100.........110.........120.........130......
## ...140.........150.........160.........170.........180.........190.........200....
## .....210.........220.........230.........240.........250.........260.........270..
## .......280.........290.........300.........310.........320.........330.........340
## .........350.........360.........370.........380.........390.........400........
## .410.........420.........430.........440.........450.........460.........470......
## ...480.........490.........500.........510.........520.........530.........540....
## .....550.........560.........570.........580.........590.........600.........610..
## .......620.........630.........640.........650.........660.........670.........680
## .........690.........700.........710.........720.........730.........740........
## .750.........760.........770.........780.........790.........800.........810......
## ...820.........830.........840.........850.........860.........870.........880....
## .....890.........900.........910.........920.........930.........940.........950..
## .......960.........970.........980.........990........ 999.
## 
## Done.</code></pre>
<pre><code>## 
##  Maximum absolute deviation test of CSR
##  Monte Carlo test based on 999 simulations
##  Summary function: G(r)
##  Reference function: theoretical
##  Alternative: two.sided
##  Interval of distance values: [0, 65.7378018120781] km
##  Test statistic: Maximum absolute deviation
##  Deviation = observed minus theoretical
## 
## data:  ST.ppp
## mad = 0.20482, rank = 3, p-value = 0.003</code></pre>
<p>The maximum absolute deviation is about .2 (largest difference in proportion of events within a given distance of an other event between the data and the model)</p>
<p>The value is relative large on the scale from 0 to 1 so the <span class="math inline">\(p\)</span>-value is small and you reject the null hypothesis of CSR for these data. This is consistent with the evidence gleaned from the graph. Note: Since there are 999 simulations the lowest the <span class="math inline">\(p\)</span>-value can be is .001</p>
<p>Another test statistic is related to the sum of the squared deviations between the estimated and theoretical functions. It is implemented with the <code>dclf.test()</code> function</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="thursday-april-13-2023.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dclf.test</span>(ST.ppp, </span>
<span id="cb44-2"><a href="thursday-april-13-2023.html#cb44-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">fun =</span> Gest, </span>
<span id="cb44-3"><a href="thursday-april-13-2023.html#cb44-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">nsim =</span> <span class="dv">999</span>)</span></code></pre></div>
<pre><code>## Generating 999 simulations of CSR  ...
## 1, 2, 3, ......10.........20.........30.........40.........50.........60........
## .70.........80.........90.........100.........110.........120.........130......
## ...140.........150.........160.........170.........180.........190.........200....
## .....210.........220.........230.........240.........250.........260.........270..
## .......280.........290.........300.........310.........320.........330.........340
## .........350.........360.........370.........380.........390.........400........
## .410.........420.........430.........440.........450.........460.........470......
## ...480.........490.........500.........510.........520.........530.........540....
## .....550.........560.........570.........580.........590.........600.........610..
## .......620.........630.........640.........650.........660.........670.........680
## .........690.........700.........710.........720.........730.........740........
## .750.........760.........770.........780.........790.........800.........810......
## ...820.........830.........840.........850.........860.........870.........880....
## .....890.........900.........910.........920.........930.........940.........950..
## .......960.........970.........980.........990........ 999.
## 
## Done.</code></pre>
<pre><code>## 
##  Diggle-Cressie-Loosmore-Ford test of CSR
##  Monte Carlo test based on 999 simulations
##  Summary function: G(r)
##  Reference function: theoretical
##  Alternative: two.sided
##  Interval of distance values: [0, 65.7378018120781] km
##  Test statistic: Integral of squared absolute deviation
##  Deviation = observed minus theoretical
## 
## data:  ST.ppp
## u = 0.38069, rank = 1, p-value = 0.001</code></pre>
<p>Again the <span class="math inline">\(p\)</span>-value on the test statistic against the two-sided alternative is small (less than .01) so you reject the null hypothesis of CSR</p>
<p>Compare these test results on tornado report clustering with test results on pine sapling clustering in the <code>swedishpines</code> data set</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="thursday-april-13-2023.html#cb47-1" aria-hidden="true" tabindex="-1"></a>SP <span class="ot">&lt;-</span> swedishpines</span>
<span id="cb47-2"><a href="thursday-april-13-2023.html#cb47-2" aria-hidden="true" tabindex="-1"></a>Kenv.df <span class="ot">&lt;-</span> <span class="fu">envelope</span>(SP, </span>
<span id="cb47-3"><a href="thursday-april-13-2023.html#cb47-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">fun =</span> Kest, </span>
<span id="cb47-4"><a href="thursday-april-13-2023.html#cb47-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">nsim =</span> <span class="dv">999</span>) <span class="sc">|&gt;</span></span>
<span id="cb47-5"><a href="thursday-april-13-2023.html#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>## Generating 999 simulations of CSR  ...
## 1, 2, 3, ......10.........20.........30.........40.........50.........60........
## .70.........80.........90.........100.........110.........120.........130......
## ...140.........150.........160.........170.........180.........190.........200....
## .....210.........220.........230.........240.........250.........260.........270..
## .......280.........290.........300.........310.........320.........330.........340
## .........350.........360.........370.........380.........390.........400........
## .410.........420.........430.........440.........450.........460.........470......
## ...480.........490.........500.........510.........520.........530.........540....
## .....550.........560.........570.........580.........590.........600.........610..
## .......620.........630.........640.........650.........660.........670.........680
## .........690.........700.........710.........720.........730.........740........
## .750.........760.........770.........780.........790.........800.........810......
## ...820.........830.........840.........850.........860.........870.........880....
## .....890.........900.........910.........920.........930.........940.........950..
## .......960.........970.........980.........990........ 999.
## 
## Done.</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="thursday-april-13-2023.html#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Kenv.df, </span>
<span id="cb49-2"><a href="thursday-april-13-2023.html#cb49-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r <span class="sc">*</span> .<span class="dv">1</span>, <span class="at">y =</span> obs <span class="sc">*</span> <span class="fu">intensity</span>(SP))) <span class="sc">+</span></span>
<span id="cb49-3"><a href="thursday-april-13-2023.html#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lo <span class="sc">*</span> <span class="fu">intensity</span>(SP),</span>
<span id="cb49-4"><a href="thursday-april-13-2023.html#cb49-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ymax =</span> hi <span class="sc">*</span> <span class="fu">intensity</span>(SP)), </span>
<span id="cb49-5"><a href="thursday-april-13-2023.html#cb49-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb49-6"><a href="thursday-april-13-2023.html#cb49-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo <span class="sc">*</span> <span class="fu">intensity</span>(SP)), </span>
<span id="cb49-7"><a href="thursday-april-13-2023.html#cb49-7" aria-hidden="true" tabindex="-1"></a>                          <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb49-8"><a href="thursday-april-13-2023.html#cb49-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (m)&quot;</span>) <span class="sc">+</span> </span>
<span id="cb49-9"><a href="thursday-april-13-2023.html#cb49-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;K(r), Expected number of additional saplings</span><span class="sc">\n</span><span class="st"> within a distance r of a sapling&quot;</span>) <span class="sc">+</span></span>
<span id="cb49-10"><a href="thursday-april-13-2023.html#cb49-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>At short distances (closer than about 1 m) the black line is below the red line and just outside the gray ribbon which you interpret to mean that there are fewer pine saplings near other pine saplings than would be expected by chance at this scale. This ‘regularity’ might be the result of competition among the saplings</p>
<p>At larger distances the black line is close to the red line and inside the gray ribbon which you interpret to mean that, at this larger spatial scale, the distribution of pine saplings is indistinguishable from CSR</p>
<p>Based on the fact that most of the black line is within the gray envelope you might anticipate that a formal test of the null hypothesis of CSR will likely fail</p>
<p>MAD test</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="thursday-april-13-2023.html#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mad.test</span>(SP, </span>
<span id="cb50-2"><a href="thursday-april-13-2023.html#cb50-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">fun =</span> Kest, </span>
<span id="cb50-3"><a href="thursday-april-13-2023.html#cb50-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">nsim =</span> <span class="dv">999</span>)</span></code></pre></div>
<pre><code>## Generating 999 simulations of CSR  ...
## 1, 2, 3, ......10.........20.........30.........40.........50.........60........
## .70.........80.........90.........100.........110.........120.........130......
## ...140.........150.........160.........170.........180.........190.........200....
## .....210.........220.........230.........240.........250.........260.........270..
## .......280.........290.........300.........310.........320.........330.........340
## .........350.........360.........370.........380.........390.........400........
## .410.........420.........430.........440.........450.........460.........470......
## ...480.........490.........500.........510.........520.........530.........540....
## .....550.........560.........570.........580.........590.........600.........610..
## .......620.........630.........640.........650.........660.........670.........680
## .........690.........700.........710.........720.........730.........740........
## .750.........760.........770.........780.........790.........800.........810......
## ...820.........830.........840.........850.........860.........870.........880....
## .....890.........900.........910.........920.........930.........940.........950..
## .......960.........970.........980.........990........ 999.
## 
## Done.</code></pre>
<pre><code>## 
##  Maximum absolute deviation test of CSR
##  Monte Carlo test based on 999 simulations
##  Summary function: K(r)
##  Reference function: theoretical
##  Alternative: two.sided
##  Interval of distance values: [0, 24] units (one unit = 0.1 metres)
##  Test statistic: Maximum absolute deviation
##  Deviation = observed minus theoretical
## 
## data:  SP
## mad = 150.69, rank = 213, p-value = 0.213</code></pre>
<p>DCLF test.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="thursday-april-13-2023.html#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dclf.test</span>(SP, </span>
<span id="cb53-2"><a href="thursday-april-13-2023.html#cb53-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">fun =</span> Kest, </span>
<span id="cb53-3"><a href="thursday-april-13-2023.html#cb53-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">nsim =</span> <span class="dv">999</span>)</span></code></pre></div>
<pre><code>## Generating 999 simulations of CSR  ...
## 1, 2, 3, ......10.........20.........30.........40.........50.........60........
## .70.........80.........90.........100.........110.........120.........130......
## ...140.........150.........160.........170.........180.........190.........200....
## .....210.........220.........230.........240.........250.........260.........270..
## .......280.........290.........300.........310.........320.........330.........340
## .........350.........360.........370.........380.........390.........400........
## .410.........420.........430.........440.........450.........460.........470......
## ...480.........490.........500.........510.........520.........530.........540....
## .....550.........560.........570.........580.........590.........600.........610..
## .......620.........630.........640.........650.........660.........670.........680
## .........690.........700.........710.........720.........730.........740........
## .750.........760.........770.........780.........790.........800.........810......
## ...820.........830.........840.........850.........860.........870.........880....
## .....890.........900.........910.........920.........930.........940.........950..
## .......960.........970.........980.........990........ 999.
## 
## Done.</code></pre>
<pre><code>## 
##  Diggle-Cressie-Loosmore-Ford test of CSR
##  Monte Carlo test based on 999 simulations
##  Summary function: K(r)
##  Reference function: theoretical
##  Alternative: two.sided
##  Interval of distance values: [0, 24] units (one unit = 0.1 metres)
##  Test statistic: Integral of squared absolute deviation
##  Deviation = observed minus theoretical
## 
## data:  SP
## u = 106917, rank = 169, p-value = 0.169</code></pre>
<p>Both return a <span class="math inline">\(p\)</span>-value that is greater than .15 so you fail to reject the null hypothesis of CSR</p>
<p>The other approach to inference is to use the procedure of re-sampling. <em>Re-sampling</em> refers to generating samples from the observed data while <em>sampling</em> refers to generating samples from a theoretical model</p>
<p>The bootstrap procedure is a re-sampling strategy whereby new samples are generated from the data by randomly choosing events within the domain with replacement. An event that is chosen for the ‘bootstrap’ sample gets the chance to be chosen again (called ‘with replacement’). The number of events in each bootstrap sample should equal the number of events in the data</p>
<p>Consider 15 numbers from 1 to 15. Then pick from that set of numbers with replacement until the sample size is 15 to create a bootstrap sample</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="thursday-april-13-2023.html#cb56-1" aria-hidden="true" tabindex="-1"></a>( x <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">15</span> )</span></code></pre></div>
<pre><code>##  [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15</code></pre>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="thursday-april-13-2023.html#cb58-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">|&gt;</span></span>
<span id="cb58-2"><a href="thursday-april-13-2023.html#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample</span>(<span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##  [1]  2  9  9  2 11  7 11  2  1 12  1 10  1  1 13</code></pre>
<p>Some numbers get picked more than once and some do not get picked at all</p>
<p>The average of the original 15 <code>x</code> values is 8 but the average over the set of numbers in the bootstrap sample will not necessarily be 8. However, the distribution of the averages over many bootstrap samples will be centered close to this average</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="thursday-april-13-2023.html#cb60-1" aria-hidden="true" tabindex="-1"></a>mx <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb60-2"><a href="thursday-april-13-2023.html#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">999</span>){</span>
<span id="cb60-3"><a href="thursday-april-13-2023.html#cb60-3" aria-hidden="true" tabindex="-1"></a>  mx[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">sample</span>(x, <span class="at">replace =</span> <span class="cn">TRUE</span>))</span>
<span id="cb60-4"><a href="thursday-april-13-2023.html#cb60-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb60-5"><a href="thursday-april-13-2023.html#cb60-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-6"><a href="thursday-april-13-2023.html#cb60-6" aria-hidden="true" tabindex="-1"></a>mx.df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(mx)</span>
<span id="cb60-7"><a href="thursday-april-13-2023.html#cb60-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> mx.df,</span>
<span id="cb60-8"><a href="thursday-april-13-2023.html#cb60-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">mapping =</span> <span class="fu">aes</span>(mx)) <span class="sc">+</span></span>
<span id="cb60-9"><a href="thursday-april-13-2023.html#cb60-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb60-10"><a href="thursday-april-13-2023.html#cb60-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(x),</span>
<span id="cb60-11"><a href="thursday-april-13-2023.html#cb60-11" aria-hidden="true" tabindex="-1"></a>               <span class="at">color =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>The important thing is that the bootstrap distribution provides an estimate of the uncertainty on the computed mean through the range of possible average values</p>
<p>In this way, the <code>lohboot()</code> function estimates the uncertainty on the computed spatial statistic using a bootstrap procedure. It works by computing a local version of the function (e.g., <code>localK()</code>) on the set of re-sampled events</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="thursday-april-13-2023.html#cb61-1" aria-hidden="true" tabindex="-1"></a>Kboot.df <span class="ot">&lt;-</span> ST.ppp <span class="sc">|&gt;</span></span>
<span id="cb61-2"><a href="thursday-april-13-2023.html#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lohboot</span>(<span class="at">fun =</span> Kest) <span class="sc">|&gt;</span></span>
<span id="cb61-3"><a href="thursday-april-13-2023.html#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>## 1, 2, 3, 4.6.8.10.12.14.16.18.20.22.24.26.28.30.32.34.36.38.40
## .42.44.46.48.50.52.54.56.58.60.62.64.66.68.70.72.74.76.78.80
## .82.84.86.88.90.92.94.96.98.100.102.104.106.108.110.112.114.116.118.120
## .122.124.126.128.130.132.134.136.138.140.142.144.146.148.150.152.154.156.158.160
## .162.164.166.168.170.172.174.176.178.180.182 183.</code></pre>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="thursday-april-13-2023.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Kboot.df, </span>
<span id="cb63-2"><a href="thursday-april-13-2023.html#cb63-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> iso <span class="sc">*</span> <span class="fu">intensity</span>(ST.ppp))) <span class="sc">+</span></span>
<span id="cb63-3"><a href="thursday-april-13-2023.html#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lo <span class="sc">*</span> <span class="fu">intensity</span>(ST.ppp), </span>
<span id="cb63-4"><a href="thursday-april-13-2023.html#cb63-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ymax =</span> hi <span class="sc">*</span> <span class="fu">intensity</span>(ST.ppp)), <span class="at">fill =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb63-5"><a href="thursday-april-13-2023.html#cb63-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb63-6"><a href="thursday-april-13-2023.html#cb63-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo <span class="sc">*</span> <span class="fu">intensity</span>(ST.ppp)), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb63-7"><a href="thursday-april-13-2023.html#cb63-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb63-8"><a href="thursday-april-13-2023.html#cb63-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>The uncertainty band is plotted about the black line (<span class="math inline">\(K\)</span> curve computed from the observations) rather than about the null model (red line). The 95% uncertainty band does to include the CSR model so you confidently conclude that the tornadoes in Kansas are more clustered than chance</p>
<p>Repeat by computing the uncertainty estimate for the Swedish pine saplings</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="thursday-april-13-2023.html#cb64-1" aria-hidden="true" tabindex="-1"></a>Kboot.df <span class="ot">&lt;-</span> SP <span class="sc">|&gt;</span></span>
<span id="cb64-2"><a href="thursday-april-13-2023.html#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lohboot</span>(<span class="at">fun =</span> Kest) <span class="sc">|&gt;</span></span>
<span id="cb64-3"><a href="thursday-april-13-2023.html#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,  71.</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="thursday-april-13-2023.html#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Kboot.df, <span class="fu">aes</span>(<span class="at">x =</span> r <span class="sc">*</span> .<span class="dv">1</span>, <span class="at">y =</span> iso <span class="sc">*</span> <span class="fu">intensity</span>(SP))) <span class="sc">+</span></span>
<span id="cb66-2"><a href="thursday-april-13-2023.html#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lo <span class="sc">*</span> <span class="fu">intensity</span>(SP), </span>
<span id="cb66-3"><a href="thursday-april-13-2023.html#cb66-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ymax =</span> hi <span class="sc">*</span> <span class="fu">intensity</span>(SP)), <span class="at">fill =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb66-4"><a href="thursday-april-13-2023.html#cb66-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb66-5"><a href="thursday-april-13-2023.html#cb66-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo <span class="sc">*</span> <span class="fu">intensity</span>(SP)), <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb66-6"><a href="thursday-april-13-2023.html#cb66-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (m)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb66-7"><a href="thursday-april-13-2023.html#cb66-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>At short distances (closer than about 1.5 m) the gray ribbon is below the blue line which you interpret to mean that there are fewer pine saplings near other pine saplings than would be expected by chance at this scale indicating regularity</p>
</div>
<div id="estimating-clustering-in-multi-type-event-locations" class="section level2 unnumbered hasAnchor">
<h2>Estimating clustering in multi-type event locations<a href="thursday-april-13-2023.html#estimating-clustering-in-multi-type-event-locations" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Often the interest is on whether the occurrence of one event type influences (or is influenced by) another event type. For example, does the occurrence of one species of tree influence the occurrence of another species of tree?</p>
<p>Analogues to the <span class="math inline">\(G\)</span> and <span class="math inline">\(K\)</span> functions are available for ‘multi-type’ point patterns where the marks are factors</p>
<p>A commonly-used statistic for examining ‘cross correlation’ of event type occurrences is the cross K function <span class="math inline">\(K_{ij}(r)\)</span>, which estimates the expected number of events of type <span class="math inline">\(j\)</span> within a distance <span class="math inline">\(r\)</span> of type <span class="math inline">\(i\)</span></p>
<p>Consider the data called <code>lansing</code> from {spatstat} that contains the locations of 2,251 trees of various species in a wooded lot in Lansing, MI as a <code>ppp</code> object</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="thursday-april-13-2023.html#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(lansing)</span>
<span id="cb67-2"><a href="thursday-april-13-2023.html#cb67-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-3"><a href="thursday-april-13-2023.html#cb67-3" aria-hidden="true" tabindex="-1"></a>lansing <span class="sc">|&gt;</span></span>
<span id="cb67-4"><a href="thursday-april-13-2023.html#cb67-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## Marked planar point pattern:  2251 points
## Average intensity 2251 points per square unit (one unit = 924 feet)
## 
## *Pattern contains duplicated points*
## 
## Coordinates are given to 3 decimal places
## i.e. rounded to the nearest multiple of 0.001 units (one unit = 924 feet)
## 
## Multitype:
##          frequency proportion intensity
## blackoak       135 0.05997335       135
## hickory        703 0.31230560       703
## maple          514 0.22834300       514
## misc           105 0.04664594       105
## redoak         346 0.15370950       346
## whiteoak       448 0.19902270       448
## 
## Window: rectangle = [0, 1] x [0, 1] units
## Window area = 1 square unit
## Unit of length: 924 feet</code></pre>
<p>The data are a multi-type planar point pattern with the marks indicating tree species. There are 135 black oaks, 703 hickories, etc. The spatial unit is 924 feet</p>
<p>Compute and plot the cross <span class="math inline">\(K_{i,j}\)</span> function using i = Maple and j = Hickory events</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="thursday-april-13-2023.html#cb69-1" aria-hidden="true" tabindex="-1"></a>Kc.df <span class="ot">&lt;-</span> lansing <span class="sc">|&gt;</span></span>
<span id="cb69-2"><a href="thursday-april-13-2023.html#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Kcross</span>(<span class="at">i =</span> <span class="st">&quot;maple&quot;</span>,</span>
<span id="cb69-3"><a href="thursday-april-13-2023.html#cb69-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">j =</span> <span class="st">&quot;hickory&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb69-4"><a href="thursday-april-13-2023.html#cb69-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span>
<span id="cb69-5"><a href="thursday-april-13-2023.html#cb69-5" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb69-6"><a href="thursday-april-13-2023.html#cb69-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Kc.df, </span>
<span id="cb69-7"><a href="thursday-april-13-2023.html#cb69-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> iso)) <span class="sc">+</span></span>
<span id="cb69-8"><a href="thursday-april-13-2023.html#cb69-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb69-9"><a href="thursday-april-13-2023.html#cb69-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb69-10"><a href="thursday-april-13-2023.html#cb69-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> .<span class="dv">2</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb69-11"><a href="thursday-april-13-2023.html#cb69-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> .<span class="dv">093</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb69-12"><a href="thursday-april-13-2023.html#cb69-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> .<span class="dv">125</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb69-13"><a href="thursday-april-13-2023.html#cb69-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Distance&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Kc(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb69-14"><a href="thursday-april-13-2023.html#cb69-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>The vertical axis is the number of hickory trees within a radius r of a maple tree divided by the average intensity of the hickories. So at a distance of .2 (.2 x 924 ft = 180 ft) from a random maple there is an average of roughly 65 hickories (.093 x 703 hickories). If hickory and maple trees are CSR you would expect about 88 maples (.125 x 703) within that distance</p>
<p>The presence of a hickory tree reduces the likelihood that a maple tree is nearby</p>
<p>Make the same plots for the EF1 and EF3 tornadoes in Kansas</p>
<p>Using {base} R</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="thursday-april-13-2023.html#cb70-1" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="sc">|&gt;</span></span>
<span id="cb70-2"><a href="thursday-april-13-2023.html#cb70-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Kcross</span>(<span class="at">i =</span> <span class="st">&quot;1&quot;</span>,</span>
<span id="cb70-3"><a href="thursday-april-13-2023.html#cb70-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">j =</span> <span class="st">&quot;3&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb70-4"><a href="thursday-april-13-2023.html#cb70-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span>
<span id="cb70-5"><a href="thursday-april-13-2023.html#cb70-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">70</span>)</span>
<span id="cb70-6"><a href="thursday-april-13-2023.html#cb70-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">18700</span>)</span>
<span id="cb70-7"><a href="thursday-april-13-2023.html#cb70-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">15500</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p>Using {ggplot} syntax</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="thursday-april-13-2023.html#cb71-1" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="sc">|&gt;</span></span>
<span id="cb71-2"><a href="thursday-april-13-2023.html#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Kcross</span>(<span class="at">i =</span> <span class="st">&quot;1&quot;</span>, </span>
<span id="cb71-3"><a href="thursday-april-13-2023.html#cb71-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">j =</span> <span class="st">&quot;3&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb71-4"><a href="thursday-april-13-2023.html#cb71-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb71-5"><a href="thursday-april-13-2023.html#cb71-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> iso)) <span class="sc">+</span></span>
<span id="cb71-6"><a href="thursday-april-13-2023.html#cb71-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb71-7"><a href="thursday-april-13-2023.html#cb71-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb71-8"><a href="thursday-april-13-2023.html#cb71-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">70</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb71-9"><a href="thursday-april-13-2023.html#cb71-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">18700</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb71-10"><a href="thursday-april-13-2023.html#cb71-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">15500</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb71-11"><a href="thursday-april-13-2023.html#cb71-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Distance&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Kc(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb71-12"><a href="thursday-april-13-2023.html#cb71-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>The vertical axis is the number of EF3 tornadoes within a radius r of an EF1 tornado divided by the average intensity of the EF3 tornadoes. At a distance of 70 km from a random EF1 tornado there are on average 18500 x .000296 = 5.5 EF3 tornadoes. If EF1 and EF3 tornadoes are CSR then you would expect, on average, somewhat fewer EF3 tornadoes in the vicinity of EF1 tornadoes (15500 x .000296 = 4.6)</p>
<p>You can see this more clearly using the <code>envelope()</code> function with the <code>fun = Kross</code>. You first use the <code>subset()</code> method with <code>drop = TRUE</code> to make a new <code>ppp</code> object with only those two groups</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="thursday-april-13-2023.html#cb72-1" aria-hidden="true" tabindex="-1"></a>T.ppp13 <span class="ot">&lt;-</span> <span class="fu">subset</span>(T.ppp,</span>
<span id="cb72-2"><a href="thursday-april-13-2023.html#cb72-2" aria-hidden="true" tabindex="-1"></a>                  marks <span class="sc">==</span> <span class="st">&quot;1&quot;</span> <span class="sc">|</span></span>
<span id="cb72-3"><a href="thursday-april-13-2023.html#cb72-3" aria-hidden="true" tabindex="-1"></a>                  marks <span class="sc">==</span> <span class="st">&quot;3&quot;</span>,</span>
<span id="cb72-4"><a href="thursday-april-13-2023.html#cb72-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">drop =</span> <span class="cn">TRUE</span>)</span>
<span id="cb72-5"><a href="thursday-april-13-2023.html#cb72-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-6"><a href="thursday-april-13-2023.html#cb72-6" aria-hidden="true" tabindex="-1"></a>T.ppp13 <span class="sc">|&gt;</span></span>
<span id="cb72-7"><a href="thursday-april-13-2023.html#cb72-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">envelope</span>(<span class="at">fun =</span> Kcross,</span>
<span id="cb72-8"><a href="thursday-april-13-2023.html#cb72-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">nsim =</span> <span class="dv">99</span>) <span class="sc">|&gt;</span></span>
<span id="cb72-9"><a href="thursday-april-13-2023.html#cb72-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb72-10"><a href="thursday-april-13-2023.html#cb72-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> obs)) <span class="sc">+</span></span>
<span id="cb72-11"><a href="thursday-april-13-2023.html#cb72-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lo, <span class="at">ymax =</span> hi), <span class="at">fill =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb72-12"><a href="thursday-april-13-2023.html#cb72-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb72-13"><a href="thursday-april-13-2023.html#cb72-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb72-14"><a href="thursday-april-13-2023.html#cb72-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Kc(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb72-15"><a href="thursday-april-13-2023.html#cb72-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## Generating 99 simulations of CSR  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
## 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,  99.
## 
## Done.</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<p>And you formally test as before using the <code>mad.test()</code> function</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="thursday-april-13-2023.html#cb74-1" aria-hidden="true" tabindex="-1"></a>T.ppp13 <span class="sc">|&gt;</span></span>
<span id="cb74-2"><a href="thursday-april-13-2023.html#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mad.test</span>(<span class="at">fun =</span> Kcross,</span>
<span id="cb74-3"><a href="thursday-april-13-2023.html#cb74-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">nsim =</span> <span class="dv">99</span>)</span></code></pre></div>
<pre><code>## Generating 99 simulations of CSR  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
## 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,  99.
## 
## Done.</code></pre>
<pre><code>## 
##  Maximum absolute deviation test of CSR
##  Monte Carlo test based on 99 simulations
##  Summary function: &quot;K&quot;[&quot;1&quot;, &quot;3&quot;](r)
##  Reference function: theoretical
##  Alternative: two.sided
##  Interval of distance values: [0, 85.9002061907829] km
##  Test statistic: Maximum absolute deviation
##  Deviation = observed minus theoretical
## 
## data:  T.ppp13
## mad = 4861.9, rank = 1, p-value = 0.01</code></pre>
<p>Or the <code>dclf.test()</code> function</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="thursday-april-13-2023.html#cb77-1" aria-hidden="true" tabindex="-1"></a>T.ppp13 <span class="sc">|&gt;</span></span>
<span id="cb77-2"><a href="thursday-april-13-2023.html#cb77-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dclf.test</span>(<span class="at">fun =</span> Kcross, </span>
<span id="cb77-3"><a href="thursday-april-13-2023.html#cb77-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">nsim =</span> <span class="dv">99</span>)</span></code></pre></div>
<pre><code>## Generating 99 simulations of CSR  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
## 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,  99.
## 
## Done.</code></pre>
<pre><code>## 
##  Diggle-Cressie-Loosmore-Ford test of CSR
##  Monte Carlo test based on 99 simulations
##  Summary function: &quot;K&quot;[&quot;1&quot;, &quot;3&quot;](r)
##  Reference function: theoretical
##  Alternative: two.sided
##  Interval of distance values: [0, 85.9002061907829] km
##  Test statistic: Integral of squared absolute deviation
##  Deviation = observed minus theoretical
## 
## data:  T.ppp13
## u = 555094904, rank = 1, p-value = 0.01</code></pre>
<p>Both tests lead you to conclude that EF3 tornadoes are more likely near EF1 tornadoes than would be expected if they were independently CSR.</p>
</div>
<div id="interpolating-output-from-a-distance-function" class="section level2 unnumbered hasAnchor">
<h2>Interpolating output from a distance function<a href="thursday-april-13-2023.html#interpolating-output-from-a-distance-function" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Spatial scale matters. Departures from CSR might depend on the lag distance so it is important to be able to interpolate values that are output from the various distance functions</p>
<p>As an example, compute <span class="math inline">\(K\)</span> and look at the classes of the resulting object</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="thursday-april-13-2023.html#cb80-1" aria-hidden="true" tabindex="-1"></a>K <span class="ot">&lt;-</span> T.ppp <span class="sc">|&gt;</span></span>
<span id="cb80-2"><a href="thursday-april-13-2023.html#cb80-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Kest</span>()</span>
<span id="cb80-3"><a href="thursday-april-13-2023.html#cb80-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-4"><a href="thursday-april-13-2023.html#cb80-4" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(K)</span></code></pre></div>
<pre><code>## [1] &quot;fv&quot;         &quot;data.frame&quot;</code></pre>
<p>It has two classes <code>fv</code> and <code>data.frame</code>. It is a data frame but with additional attribute information. You focus on the data frame portion</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="thursday-april-13-2023.html#cb82-1" aria-hidden="true" tabindex="-1"></a>K.df <span class="ot">&lt;-</span> K <span class="sc">|&gt;</span></span>
<span id="cb82-2"><a href="thursday-april-13-2023.html#cb82-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span>
<span id="cb82-3"><a href="thursday-april-13-2023.html#cb82-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-4"><a href="thursday-april-13-2023.html#cb82-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(K.df)</span></code></pre></div>
<pre><code>##           r       theo   border    trans      iso
## 1 0.0000000 0.00000000 0.000000 0.000000 0.000000
## 2 0.1677738 0.08842974 5.567168 5.569631 5.569631
## 3 0.3355477 0.35371897 6.089427 6.075961 6.075961
## 4 0.5033215 0.79586769 6.705232 6.751067 6.751067
## 5 0.6710954 1.41487589 7.214490 7.257397 7.257397
## 6 0.8388692 2.21074358 7.900530 7.932504 7.932504</code></pre>
<p>In particular you want the values of <code>r</code> and <code>iso</code>. The value of <code>iso</code> times the average spatial intensity is the number of tornadoes within a distance <code>r</code></p>
<p>You add this information to the data frame</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="thursday-april-13-2023.html#cb84-1" aria-hidden="true" tabindex="-1"></a>K.df <span class="ot">&lt;-</span> K.df <span class="sc">|&gt;</span></span>
<span id="cb84-2"><a href="thursday-april-13-2023.html#cb84-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">nT =</span> <span class="fu">summary</span>(T.ppp)<span class="sc">$</span>intensity <span class="sc">*</span> iso)</span></code></pre></div>
<p>Suppose you are interested in the average number of tornadoes at a distance of exactly 50 km. Use the <code>approx()</code> function to interpolate the value of <code>nT</code> at a distance of 50 km</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="thursday-april-13-2023.html#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">approx</span>(<span class="at">x =</span> K.df<span class="sc">$</span>r, </span>
<span id="cb85-2"><a href="thursday-april-13-2023.html#cb85-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> K.df<span class="sc">$</span>nT,</span>
<span id="cb85-3"><a href="thursday-april-13-2023.html#cb85-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">xout =</span> <span class="dv">50</span>)<span class="sc">$</span>y</span></code></pre></div>
<pre><code>## [1] 93.62085</code></pre>
</div>
<div id="limitations-of-the-distance-functions" class="section level2 unnumbered hasAnchor">
<h2>Limitations of the distance functions<a href="thursday-april-13-2023.html#limitations-of-the-distance-functions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The distance functions (<span class="math inline">\(G\)</span>, <span class="math inline">\(K\)</span>, etc) that are used to quantify clustering are defined and estimated under the assumption that the process that produced the events is stationary (homogeneous). If this is true then you can treat any sub-region of the domain as an independent and identically distributed (iid) sample from the entire set of data</p>
<p>If the spatial distribution of the event locations is influenced by event interaction then the functions will deviate from the theoretical model of CSR. But a deviation from CSR does not imply event interaction</p>
<p>Moreover, the functions characterize the spatial arrangement of event locations ‘on average’ so variability in an interaction as a function of scale may not be detected</p>
<p>As an example of the latter case, here you generate event locations at random with clustering on a small scale but with regularity on a larger scale. Then, on average, the event locations will be CSR as indicated by the <span class="math inline">\(K\)</span> function</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="thursday-april-13-2023.html#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">0112</span>)</span>
<span id="cb87-2"><a href="thursday-april-13-2023.html#cb87-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-3"><a href="thursday-april-13-2023.html#cb87-3" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">rcell</span>(<span class="at">nx =</span> <span class="dv">15</span>)</span>
<span id="cb87-4"><a href="thursday-april-13-2023.html#cb87-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X, <span class="at">main =</span> <span class="st">&quot;&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<p>There are two ‘local’ clusters one in the north and one in the south. But overall the events appear to be more regular (inhibition) than CSR.</p>
<p>Interpretation of the process that created the event locations based on <span class="math inline">\(K\)</span> would be that the arrangement of events is CSR.</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="thursday-april-13-2023.html#cb88-1" aria-hidden="true" tabindex="-1"></a>X <span class="sc">|&gt;</span></span>
<span id="cb88-2"><a href="thursday-april-13-2023.html#cb88-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Kest</span>() <span class="sc">|&gt;</span></span>
<span id="cb88-3"><a href="thursday-april-13-2023.html#cb88-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb88-4"><a href="thursday-april-13-2023.html#cb88-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> iso)) <span class="sc">+</span></span>
<span id="cb88-5"><a href="thursday-april-13-2023.html#cb88-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb88-6"><a href="thursday-april-13-2023.html#cb88-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb88-7"><a href="thursday-april-13-2023.html#cb88-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb88-8"><a href="thursday-april-13-2023.html#cb88-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<p>The empirical curve (black line) coincides with the theoretical CSR line (red line) indicating CSR</p>
<p>And the maximum absolute deviation test under the null hypothesis of CSR returns a large <span class="math inline">\(p\)</span>-value so you fail to reject it</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="thursday-april-13-2023.html#cb89-1" aria-hidden="true" tabindex="-1"></a>X <span class="sc">|&gt;</span></span>
<span id="cb89-2"><a href="thursday-april-13-2023.html#cb89-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mad.test</span>(<span class="at">fun =</span> Kest, </span>
<span id="cb89-3"><a href="thursday-april-13-2023.html#cb89-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">nsim =</span> <span class="dv">99</span>)</span></code></pre></div>
<pre><code>## Generating 99 simulations of CSR  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
## 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,  99.
## 
## Done.</code></pre>
<pre><code>## 
##  Maximum absolute deviation test of CSR
##  Monte Carlo test based on 99 simulations
##  Summary function: K(r)
##  Reference function: theoretical
##  Alternative: two.sided
##  Interval of distance values: [0, 0.25]
##  Test statistic: Maximum absolute deviation
##  Deviation = observed minus theoretical
## 
## data:  X
## mad = 0.0023931, rank = 87, p-value = 0.87</code></pre>
<p>As an example of the former case, here you generate event locations that have no inter-event interaction but there is a trend in the spatial intensity</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="thursday-april-13-2023.html#cb92-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">rpoispp</span>(<span class="cf">function</span>(x, y){ <span class="dv">300</span> <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="dv">3</span> <span class="sc">*</span> x) })</span>
<span id="cb92-2"><a href="thursday-april-13-2023.html#cb92-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-3"><a href="thursday-april-13-2023.html#cb92-3" aria-hidden="true" tabindex="-1"></a>X <span class="sc">|&gt;</span></span>
<span id="cb92-4"><a href="thursday-april-13-2023.html#cb92-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="at">main =</span> <span class="st">&quot;&quot;</span>) </span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
<p>By design there is a clear trend toward fewer events moving toward the east</p>
<p>You compute and plot the <span class="math inline">\(K\)</span> function on these event locations</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="thursday-april-13-2023.html#cb93-1" aria-hidden="true" tabindex="-1"></a>X <span class="sc">|&gt;</span></span>
<span id="cb93-2"><a href="thursday-april-13-2023.html#cb93-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Kest</span>() <span class="sc">|&gt;</span></span>
<span id="cb93-3"><a href="thursday-april-13-2023.html#cb93-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb93-4"><a href="thursday-april-13-2023.html#cb93-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> iso)) <span class="sc">+</span></span>
<span id="cb93-5"><a href="thursday-april-13-2023.html#cb93-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb93-6"><a href="thursday-april-13-2023.html#cb93-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb93-7"><a href="thursday-april-13-2023.html#cb93-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb93-8"><a href="thursday-april-13-2023.html#cb93-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-40-1.png" width="672" /></p>
<p>The <span class="math inline">\(K\)</span> function indicates clustering but this is an artifact of the trend in the intensity</p>
<p>In the case of a known trend in the spatial intensity, you need to use the <code>Kinhom()</code> function. For example, compare the uncertainty envelopes from a homogeneous and inhomogeneous Poisson process</p>
<p>Start by plotting the output from the <code>envelope()</code> function with <code>fun = Kest</code>. The <code>global = TRUE</code> argument indicates that the envelopes are simultaneous rather than point-wise (<code>global = FALSE</code> which is the default). Point-wise envelopes assume the estimates are independent (usually not a good assumption) across the range of distances so the standard errors will be smaller resulting in narrower bands</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="thursday-april-13-2023.html#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">envelope</span>(X, </span>
<span id="cb94-2"><a href="thursday-april-13-2023.html#cb94-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">fun =</span> Kest, </span>
<span id="cb94-3"><a href="thursday-april-13-2023.html#cb94-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">nsim =</span> <span class="dv">999</span>, </span>
<span id="cb94-4"><a href="thursday-april-13-2023.html#cb94-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">rank =</span> <span class="dv">1</span>, </span>
<span id="cb94-5"><a href="thursday-april-13-2023.html#cb94-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">global =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb94-6"><a href="thursday-april-13-2023.html#cb94-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb94-7"><a href="thursday-april-13-2023.html#cb94-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> obs)) <span class="sc">+</span></span>
<span id="cb94-8"><a href="thursday-april-13-2023.html#cb94-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">ymin =</span> lo, <span class="at">ymax =</span> hi), </span>
<span id="cb94-9"><a href="thursday-april-13-2023.html#cb94-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb94-10"><a href="thursday-april-13-2023.html#cb94-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb94-11"><a href="thursday-april-13-2023.html#cb94-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">y =</span> theo), </span>
<span id="cb94-12"><a href="thursday-april-13-2023.html#cb94-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb94-13"><a href="thursday-april-13-2023.html#cb94-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb94-14"><a href="thursday-april-13-2023.html#cb94-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## Generating 999 simulations of CSR  ...
## 1, 2, 3, ......10.........20.........30.........40.........50.........60........
## .70.........80.........90.........100.........110.........120.........130......
## ...140.........150.........160.........170.........180.........190.........200....
## .....210.........220.........230.........240.........250.........260.........270..
## .......280.........290.........300.........310.........320.........330.........340
## .........350.........360.........370.........380.........390.........400........
## .410.........420.........430.........440.........450.........460.........470......
## ...480.........490.........500.........510.........520.........530.........540....
## .....550.........560.........570.........580.........590.........600.........610..
## .......620.........630.........640.........650.........660.........670.........680
## .........690.........700.........710.........720.........730.........740........
## .750.........760.........770.........780.........790.........800.........810......
## ...820.........830.........840.........850.........860.........870.........880....
## .....890.........900.........910.........920.........930.........940.........950..
## .......960.........970.........980.........990........ 999.
## 
## Done.</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<p>After a distance of about .15 units the empirical curve (black line) is outside the uncertainty band indicating the events are more clustered than CSR</p>
<p>However when you use the <code>fun = Kinhom</code> the empirical curve is completely inside the uncertainty band</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="thursday-april-13-2023.html#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">envelope</span>(X, </span>
<span id="cb96-2"><a href="thursday-april-13-2023.html#cb96-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">fun =</span> Kinhom, </span>
<span id="cb96-3"><a href="thursday-april-13-2023.html#cb96-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">nsim =</span> <span class="dv">999</span>, </span>
<span id="cb96-4"><a href="thursday-april-13-2023.html#cb96-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">rank =</span> <span class="dv">1</span>, </span>
<span id="cb96-5"><a href="thursday-april-13-2023.html#cb96-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">global =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb96-6"><a href="thursday-april-13-2023.html#cb96-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb96-7"><a href="thursday-april-13-2023.html#cb96-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> obs)) <span class="sc">+</span></span>
<span id="cb96-8"><a href="thursday-april-13-2023.html#cb96-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">ymin =</span> lo, <span class="at">ymax =</span> hi), </span>
<span id="cb96-9"><a href="thursday-april-13-2023.html#cb96-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb96-10"><a href="thursday-april-13-2023.html#cb96-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb96-11"><a href="thursday-april-13-2023.html#cb96-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">y =</span> theo), </span>
<span id="cb96-12"><a href="thursday-april-13-2023.html#cb96-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb96-13"><a href="thursday-april-13-2023.html#cb96-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb96-14"><a href="thursday-april-13-2023.html#cb96-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## Generating 999 simulations of CSR  ...
## 1, 2, 3, ......10.........20.........30.........40.........50.........60........
## .70.........80.........90.........100.........110.........120.........130......
## ...140.........150.........160.........170.........180.........190.........200....
## .....210.........220.........230.........240.........250.........260.........270..
## .......280.........290.........300.........310.........320.........330.........340
## .........350.........360.........370.........380.........390.........400........
## .410.........420.........430.........440.........450.........460.........470......
## ...480.........490.........500.........510.........520.........530.........540....
## .....550.........560.........570.........580.........590.........600.........610..
## .......620.........630.........640.........650.........660.........670.........680
## .........690.........700.........710.........720.........730.........740........
## .750.........760.........770.........780.........790.........800.........810......
## ...820.........830.........840.........850.........860.........870.........880....
## .....890.........900.........910.........920.........930.........940.........950..
## .......960.........970.........980.........990........ 999.
## 
## Done.</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>
<p>You conclude that the point pattern data are more consistent with an inhomogeneous Poisson process</p>
<p>Let’s return to the Kansas tornadoes (EF1+). You imported the data and created a point pattern object windowed by the state borders</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="thursday-april-13-2023.html#cb98-1" aria-hidden="true" tabindex="-1"></a>ST.ppp <span class="sc">|&gt;</span></span>
<span id="cb98-2"><a href="thursday-april-13-2023.html#cb98-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-43-1.png" width="672" /></p>
<p>There are more tornado reports in the west than in the east, especially across the southern part of the state indicating the process producing the events is not homogeneous. This means there are other factors contributing to local event intensity</p>
<p>Evidence for clustering must account for this inhomogeneity. Here you do this by computing the envelope around the inhomogeneous Ripley K function using the argument <code>fun = Kinhom</code></p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="thursday-april-13-2023.html#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">envelope</span>(ST.ppp,</span>
<span id="cb99-2"><a href="thursday-april-13-2023.html#cb99-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">fun =</span> Kinhom,</span>
<span id="cb99-3"><a href="thursday-april-13-2023.html#cb99-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">nsim =</span> <span class="dv">99</span>,</span>
<span id="cb99-4"><a href="thursday-april-13-2023.html#cb99-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">rank =</span> <span class="dv">1</span>,</span>
<span id="cb99-5"><a href="thursday-april-13-2023.html#cb99-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">global =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb99-6"><a href="thursday-april-13-2023.html#cb99-6" aria-hidden="true" tabindex="-1"></a><span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb99-7"><a href="thursday-april-13-2023.html#cb99-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> obs)) <span class="sc">+</span></span>
<span id="cb99-8"><a href="thursday-april-13-2023.html#cb99-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">ymin =</span> lo, <span class="at">ymax =</span> hi), </span>
<span id="cb99-9"><a href="thursday-april-13-2023.html#cb99-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb99-10"><a href="thursday-april-13-2023.html#cb99-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb99-11"><a href="thursday-april-13-2023.html#cb99-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">y =</span> theo), </span>
<span id="cb99-12"><a href="thursday-april-13-2023.html#cb99-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb99-13"><a href="thursday-april-13-2023.html#cb99-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb99-14"><a href="thursday-april-13-2023.html#cb99-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## Generating 99 simulations of CSR  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
## 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,  99.
## 
## Done.</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-44-1.png" width="672" /></p>
<p>The output reveals no evidence of clustering at distances less than about 70 km. At greater distances there is some evidence of regularity indicated by the black line below the red line and just outside the uncertainty ribbon. This is due to the fact that tornado reports are more common near cities and towns and cities and towns tend to be spread out more regular than CSR</p>
<p>Finally, the variance stabilized Ripley <span class="math inline">\(K\)</span> function called the <span class="math inline">\(L\)</span> function is often used instead of <span class="math inline">\(K\)</span>. The sample version of <span class="math inline">\(L\)</span> is defined as</p>
<p><span class="math display">\[
\hat{L}(r) = \Big( \hat{K}(r)/\pi\Big)^{1/2}
\]</span></p>
<p>For data that is CSR, the <span class="math inline">\(L\)</span> function has expected value <span class="math inline">\(r\)</span> and its variance is approximately constant in <span class="math inline">\(r\)</span>. A common plot is a graph of <span class="math inline">\(r - \hat{L}(r)\)</span> against <span class="math inline">\(r\)</span>, which approximately follows the horizontal zero-axis with constant dispersion if the data follow a homogeneous Poisson process</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tuesday-april-11-2023.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="tuesday-april-18-2023.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
