<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Thursday October 27, 2022 | GIS5122: Applied Spatial Statistics</title>
  <meta name="description" content="Thursday October 27, 2022 | GIS5122: Applied Spatial Statistics" />
  <meta name="generator" content="bookdown 0.29 and GitBook 2.6.7" />

  <meta property="og:title" content="Thursday October 27, 2022 | GIS5122: Applied Spatial Statistics" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="jelsner/ASS-2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Thursday October 27, 2022 | GIS5122: Applied Spatial Statistics" />
  
  
  

<meta name="author" content="James B. Elsner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tuesday-october-25-2022.html"/>
<link rel="next" href="thursday-october-27-2022-1.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied Spatial Statistics</a></li>

<li class="divider"></li>
<li><a href="index.html#section" id="toc-section"></a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i>Syllabus</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#gis5122-applied-spatial-statistics"><i class="fa fa-check"></i>GIS5122: Applied Spatial Statistics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#contact-information"><i class="fa fa-check"></i>Contact information</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#course-description-and-expected-learning-outcomes"><i class="fa fa-check"></i>Course description and expected learning outcomes</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#grades-and-ethics"><i class="fa fa-check"></i>Grades and ethics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#outline-of-topics-and-schedule"><i class="fa fa-check"></i>Outline of topics and schedule</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#reference-materials"><i class="fa fa-check"></i>Reference materials</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#reproducible-research"><i class="fa fa-check"></i>Reproducible research</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html"><i class="fa fa-check"></i>Tuesday, August 23, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#install-r-and-rstudio-on-your-computer"><i class="fa fa-check"></i>Install R and RStudio on your computer</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#download-course-materials"><i class="fa fa-check"></i>Download course materials</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#read-the-syllabus"><i class="fa fa-check"></i>Read the syllabus</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#about-rstudio"><i class="fa fa-check"></i>About RStudio</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#lab-assignments"><i class="fa fa-check"></i>Lab assignments</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#getting-started-with-r"><i class="fa fa-check"></i>Getting started with R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#are-you-completely-new-to-r"><i class="fa fa-check"></i>Are you completely new to R?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html"><i class="fa fa-check"></i>Thursday, August 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-science-workflow-with-r-markdown"><i class="fa fa-check"></i>Data science workflow with R markdown</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#an-introduction-to-using-r"><i class="fa fa-check"></i>An introduction to using R</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-frames"><i class="fa fa-check"></i>Data frames</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html"><i class="fa fa-check"></i>Tuesday August 30, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#working-with-data-frames-using-base-r"><i class="fa fa-check"></i>Working with data frames using base R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#getting-data-into-r"><i class="fa fa-check"></i>Getting data into R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#working-with-data-frames-using-functions-from-dplyr"><i class="fa fa-check"></i>Working with data frames using functions from {dplyr}</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html"><i class="fa fa-check"></i>Thursday September 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#making-graphs"><i class="fa fa-check"></i>Making graphs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html"><i class="fa fa-check"></i>Thursday September 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#introduction-to-simple-features"><i class="fa fa-check"></i>Introduction to simple features</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#geo-computation-on-simple-features"><i class="fa fa-check"></i>Geo-computation on simple features</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html"><i class="fa fa-check"></i>Tuesday September 13, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#spatial-data-subsets-and-joins"><i class="fa fa-check"></i>Spatial data subsets and joins</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#interpolation-using-areal-weights"><i class="fa fa-check"></i>Interpolation using areal weights</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html"><i class="fa fa-check"></i>Thursday September 15, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#s4-spatial-data-objects"><i class="fa fa-check"></i>S4 spatial data objects</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#working-with-raster-data"><i class="fa fa-check"></i>Working with raster data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#working-with-space-time-data"><i class="fa fa-check"></i>Working with space-time data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html"><i class="fa fa-check"></i>Tuesday September 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#mapping-using-functions-from-the-ggplot2-package"><i class="fa fa-check"></i>Mapping using functions from the {ggplot2} package</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#mapping-using-functions-from-the-tmap-package"><i class="fa fa-check"></i>Mapping using functions from the {tmap} package</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#creating-an-interactive-map"><i class="fa fa-check"></i>Creating an interactive map</a></li>
<li class="chapter" data-level="0.1" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#hillshape-and-colors-with-tidyterra"><i class="fa fa-check"></i><b>0.1</b> Hillshape and colors with tidyterra</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#adding-an-inset-map"><i class="fa fa-check"></i>Adding an inset map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html"><i class="fa fa-check"></i>Tuesday October 4, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#defining-spatial-neighborhoods-and-spatial-weights"><i class="fa fa-check"></i>Defining spatial neighborhoods and spatial weights</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#computing-autocorrelation"><i class="fa fa-check"></i>Computing autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#spatial-lag-and-its-relation-to-autocorrelation"><i class="fa fa-check"></i>Spatial lag and its relation to autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#other-neighbor-definitions"><i class="fa fa-check"></i>Other neighbor definitions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html"><i class="fa fa-check"></i>Thursday October 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#assessing-the-statistical-significance-of-autocorrelation"><i class="fa fa-check"></i>Assessing the statistical significance of autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#bivariate-spatial-autocorrelation"><i class="fa fa-check"></i>Bivariate spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#local-indicators-of-spatial-autocorrelation"><i class="fa fa-check"></i>Local indicators of spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#constraining-group-membership-based-on-spatial-autocorrelation"><i class="fa fa-check"></i>Constraining group membership based on spatial autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html"><i class="fa fa-check"></i>Tuesday October 11, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#estimating-spatial-autocorrelation-in-model-residuals"><i class="fa fa-check"></i>Estimating spatial autocorrelation in model residuals</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#choosing-a-spatial-regression-model"><i class="fa fa-check"></i>Choosing a spatial regression model</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#fitting-and-interpreting-spatial-regression-models"><i class="fa fa-check"></i>Fitting and interpreting spatial regression models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html"><i class="fa fa-check"></i>Thursday October 13, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html#fitting-and-interpreting-geographic-regression"><i class="fa fa-check"></i>Fitting and interpreting geographic regression</a></li>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html#mapping-incidence-and-risk-with-a-spatial-regression-model"><i class="fa fa-check"></i>Mapping incidence and risk with a spatial regression model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html"><i class="fa fa-check"></i>Thursday October 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#spatial-data-as-point-patterns"><i class="fa fa-check"></i>Spatial data as point patterns</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#theoretical-framework-for-analyzingmodeling-point-pattern-data"><i class="fa fa-check"></i>Theoretical framework for analyzing/modeling point pattern data</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#working-with-point-pattern-data-using-functions-from-the-spatstat-package"><i class="fa fa-check"></i>Working with point pattern data using functions from the spatstat package</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#quantifying-the-spatial-intensity-of-events"><i class="fa fa-check"></i>Quantifying the spatial intensity of events</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html"><i class="fa fa-check"></i>Tuesday October 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#creating-ppp-and-owin-objects-from-simple-feature-data-frames"><i class="fa fa-check"></i>Creating <code>ppp</code> and <code>owin</code> objects from simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#estimating-spatial-intensity-as-a-function-of-distance"><i class="fa fa-check"></i>Estimating spatial intensity as a function of distance</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#covariate-trend-as-a-possible-confounding-factor"><i class="fa fa-check"></i>Covariate trend as a possible confounding factor</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html"><i class="fa fa-check"></i>Thursday October 27, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#estimating-the-relative-risk-of-events"><i class="fa fa-check"></i>Estimating the relative risk of events</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#estimating-second-moment-properties-of-spatial-events"><i class="fa fa-check"></i>Estimating second-moment properties of spatial events</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#examples-of-spatially-clustered-events"><i class="fa fa-check"></i>Examples of spatially clustered events</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022-1.html"><a href="thursday-october-27-2022-1.html"><i class="fa fa-check"></i>Thursday October 27, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-27-2022-1.html"><a href="thursday-october-27-2022-1.html#examples-of-spatially-clustered-events-1"><i class="fa fa-check"></i>Examples of spatially clustered events</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022-1.html"><a href="thursday-october-27-2022-1.html#determining-the-statistical-significance-of-event-clustering"><i class="fa fa-check"></i>Determining the statistical significance of event clustering</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022-1.html"><a href="thursday-october-27-2022-1.html#estimating-event-clustering-in-multi-type-event-locations"><i class="fa fa-check"></i>Estimating event clustering in multi-type event locations</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022-1.html"><a href="thursday-october-27-2022-1.html#more-about-the-ripley-k-function"><i class="fa fa-check"></i>More about the Ripley K function</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html"><i class="fa fa-check"></i>Tuesday November 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#inferring-event-interaction-from-distance-functions"><i class="fa fa-check"></i>Inferring event interaction from distance functions</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#removing-duplicate-event-locations-and-defining-the-domain"><i class="fa fa-check"></i>Removing duplicate event locations and defining the domain</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#modeling-point-pattern-data"><i class="fa fa-check"></i>Modeling point pattern data</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#fitting-and-interpreting-an-inhibition-model"><i class="fa fa-check"></i>Fitting and interpreting an inhibition model</a></li>
<li class="chapter" data-level="0.2" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#fitting-a-log-gaussian-cox-process-model-to-one-dimensional-point-pattern-data"><i class="fa fa-check"></i><b>0.2</b> Fitting a log-Gaussian Cox process model to one-dimensional point pattern data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html"><i class="fa fa-check"></i>Thursday November 3, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#fitting-and-interpreting-a-cluster-model"><i class="fa fa-check"></i>Fitting and interpreting a cluster model</a></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#assessing-how-well-the-model-fits"><i class="fa fa-check"></i>Assessing how well the model fits</a></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#spatial-logistic-regression"><i class="fa fa-check"></i>Spatial logistic regression</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html"><i class="fa fa-check"></i>Thursday November 10, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html#spatial-data-interpolation"><i class="fa fa-check"></i>Spatial data interpolation</a></li>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html#computing-the-sample-variogram"><i class="fa fa-check"></i>Computing the sample variogram</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html"><i class="fa fa-check"></i>Tuesday November 15, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#fitting-a-variogram-model-to-the-sample-variogram"><i class="fa fa-check"></i>Fitting a variogram model to the sample variogram</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#creating-an-interpolated-surface-with-the-method-of-kriging"><i class="fa fa-check"></i>Creating an interpolated surface with the method of kriging</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html"><i class="fa fa-check"></i>Thursday November 17, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#comparing-interpolation-methods"><i class="fa fa-check"></i>Comparing interpolation methods</a></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#evaluating-the-accuracy-of-the-interpolation"><i class="fa fa-check"></i>Evaluating the accuracy of the interpolation</a></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#block-cross-validation"><i class="fa fa-check"></i>Block cross validation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html"><i class="fa fa-check"></i>Thursday November 29, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html#interpolating-to-areal-units-block-kriging"><i class="fa fa-check"></i>Interpolating to areal units (block kriging)</a></li>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html#simulating-spatial-fields"><i class="fa fa-check"></i>Simulating spatial fields</a></li>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html#interpolating-multiple-variables"><i class="fa fa-check"></i>Interpolating multiple variables</a></li>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html#machine-learning-for-spatial-interpolation"><i class="fa fa-check"></i>Machine learning for spatial interpolation</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GIS5122: Applied Spatial Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="thursday-october-27-2022" class="section level1 unnumbered hasAnchor">
<h1>Thursday October 27, 2022<a href="thursday-october-27-2022.html#thursday-october-27-2022" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>“To me programming is more than an important practical art. It is also a gigantic undertaking in the foundations of knowledge.”</strong> – Grace Hopper</p>
<p><em>Please remember to vote in the upcoming midterm elections!</em></p>
<p>Today</p>
<ul>
<li>Estimating the relative risk of events</li>
<li>Estimating second-order properties of spatial events</li>
<li>Examples of spatial clustered events</li>
</ul>
<div id="estimating-the-relative-risk-of-events" class="section level2 unnumbered hasAnchor">
<h2>Estimating the relative risk of events<a href="thursday-october-27-2022.html#estimating-the-relative-risk-of-events" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The relative risk of occurrence of some event is a conditional probability. In a non-spatial context, the risk of catching a disease if you are elderly relative to the risk if you are young.</p>
<p>Spatial intensity maps constructed from two different point pattern data provides a way to estimate the risk of one event conditional on the other event.</p>
<p>For example, given a tornado somewhere in Texas what is the chance that it will cause at least EF3 damage? With the historical set of all tornadoes marked by the damage rating you can make a map of all tornadoes and a map of the EF3+ tornadoes and then take the ratio.</p>
<p>To see this start by importing the tornado data, mutating and selecting the damage rating as a factor called <code>EF</code> before turning the resulting simple feature data frame into a planar point pattern.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="thursday-october-27-2022.html#cb1-1" aria-hidden="true" tabindex="-1"></a>Torn.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="at">dsn =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;1950-2020-torn-initpoint&quot;</span>)) <span class="sc">|&gt;</span></span>
<span id="cb1-2"><a href="thursday-october-27-2022.html#cb1-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3082</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-3"><a href="thursday-october-27-2022.html#cb1-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(mag <span class="sc">&gt;=</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-4"><a href="thursday-october-27-2022.html#cb1-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">EF =</span> <span class="fu">as.factor</span>(mag)) <span class="sc">|&gt;</span></span>
<span id="cb1-5"><a href="thursday-october-27-2022.html#cb1-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(EF)</span></code></pre></div>
<pre><code>## Reading layer `1950-2020-torn-initpoint&#39; from data source 
##   `/Users/jameselsner/Desktop/ClassNotes/ASS-2022/data/1950-2020-torn-initpoint&#39; 
##   using driver `ESRI Shapefile&#39;
## Simple feature collection with 66244 features and 22 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -163.53 ymin: 17.7212 xmax: -64.7151 ymax: 61.02
## Geodetic CRS:  WGS 84</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="thursday-october-27-2022.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spatstat)</span></code></pre></div>
<pre><code>## Loading required package: spatstat.data</code></pre>
<pre><code>## Loading required package: spatstat.geom</code></pre>
<pre><code>## spatstat.geom 2.4-0</code></pre>
<pre><code>## Loading required package: spatstat.random</code></pre>
<pre><code>## spatstat.random 2.2-0</code></pre>
<pre><code>## Loading required package: spatstat.core</code></pre>
<pre><code>## Loading required package: nlme</code></pre>
<pre><code>## Loading required package: rpart</code></pre>
<pre><code>## spatstat.core 2.4-4</code></pre>
<pre><code>## Loading required package: spatstat.linnet</code></pre>
<pre><code>## spatstat.linnet 2.3-2</code></pre>
<pre><code>## 
## spatstat 2.3-4       (nickname: &#39;Watch this space&#39;) 
## For an introduction to spatstat, type &#39;beginner&#39;</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="thursday-october-27-2022.html#cb16-1" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="ot">&lt;-</span> Torn.sf <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="thursday-october-27-2022.html#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.ppp</span>()</span></code></pre></div>
<p>Next get the state boundary and transform the CRS to that of the tornadoes. Then create a <code>owin</code> object from it. Finally, subset the tornadoes by the window.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="thursday-october-27-2022.html#cb17-1" aria-hidden="true" tabindex="-1"></a>TX.sf <span class="ot">&lt;-</span> USAboundaries<span class="sc">::</span><span class="fu">us_states</span>(<span class="at">states =</span> <span class="st">&quot;Texas&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="thursday-october-27-2022.html#cb17-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> sf<span class="sc">::</span><span class="fu">st_crs</span>(Torn.sf))</span>
<span id="cb17-3"><a href="thursday-october-27-2022.html#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="thursday-october-27-2022.html#cb17-4" aria-hidden="true" tabindex="-1"></a>W <span class="ot">&lt;-</span> TX.sf <span class="sc">|&gt;</span></span>
<span id="cb17-5"><a href="thursday-october-27-2022.html#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.owin</span>()</span>
<span id="cb17-6"><a href="thursday-october-27-2022.html#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="thursday-october-27-2022.html#cb17-7" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="ot">&lt;-</span> T.ppp[W]</span>
<span id="cb17-8"><a href="thursday-october-27-2022.html#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(T.ppp)</span></code></pre></div>
<pre><code>## Marked planar point pattern:  8932 points
## Average intensity 1.293119e-08 points per square unit
## 
## *Pattern contains duplicated points*
## 
## Coordinates are given to 1 decimal place
## i.e. rounded to the nearest multiple of 0.1 units
## 
## Multitype:
##   frequency   proportion    intensity
## 0      4773 0.5343708000 6.910052e-09
## 1      2557 0.2862741000 3.701865e-09
## 2      1225 0.1371473000 1.773479e-09
## 3       323 0.0361621100 4.676192e-10
## 4        48 0.0053739360 6.949141e-11
## 5         6 0.0006717421 8.686426e-12
## 
## Window: polygonal boundary
## single connected closed polygon with 550 vertices
## enclosing rectangle: [873763.8, 2116649.8] x [5881245, 7063086] units
##                      (1243000 x 1182000 units)
## Window area = 6.90733e+11 square units
## Fraction of frame area: 0.47</code></pre>
<p>You note the chance that a tornado anywhere in Texas will be at least EF3 or worse is the sum of the proportions for these types: .03616 + .00537 + .00067 = .042 (or 4.2%).</p>
<p>As noted last time there is a spatial intensity gradient across the state with fewer tornadoes in the southwest and more in the northeast. Also, the more damaging tornadoes might be more common relative to all tornadoes in some parts of the state compared to other parts of the state.</p>
<p>To create a map of the relative risk of the more damaging tornadoes you start by making two <code>ppp</code> objects, one being the set of all tornado events with damage ratings 0, 1, or 2 and the other the set of all tornado locations with damage ratings 3, 4, or 5. You do this by subset the object using brackets (<code>[]</code>) and the logical operator <code>|</code> (or) and then merge the two subsets assigning names <code>H</code> and <code>I</code> as marks with the <code>superimpose()</code> function.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="thursday-october-27-2022.html#cb19-1" aria-hidden="true" tabindex="-1"></a>H.ppp <span class="ot">&lt;-</span> <span class="fu">unmark</span>(T.ppp[T.ppp<span class="sc">$</span>marks <span class="sc">==</span> <span class="dv">2</span> <span class="sc">|</span> </span>
<span id="cb19-2"><a href="thursday-october-27-2022.html#cb19-2" aria-hidden="true" tabindex="-1"></a>                      T.ppp<span class="sc">$</span>marks <span class="sc">==</span> <span class="dv">1</span> <span class="sc">|</span> </span>
<span id="cb19-3"><a href="thursday-october-27-2022.html#cb19-3" aria-hidden="true" tabindex="-1"></a>                      T.ppp<span class="sc">$</span>marks <span class="sc">==</span> <span class="dv">0</span>])</span>
<span id="cb19-4"><a href="thursday-october-27-2022.html#cb19-4" aria-hidden="true" tabindex="-1"></a>I.ppp <span class="ot">&lt;-</span> <span class="fu">unmark</span>(T.ppp[T.ppp<span class="sc">$</span>marks <span class="sc">==</span> <span class="dv">3</span> <span class="sc">|</span> </span>
<span id="cb19-5"><a href="thursday-october-27-2022.html#cb19-5" aria-hidden="true" tabindex="-1"></a>                        T.ppp<span class="sc">$</span>marks <span class="sc">==</span> <span class="dv">4</span> <span class="sc">|</span> </span>
<span id="cb19-6"><a href="thursday-october-27-2022.html#cb19-6" aria-hidden="true" tabindex="-1"></a>                        T.ppp<span class="sc">$</span>marks <span class="sc">==</span> <span class="dv">5</span>])</span>
<span id="cb19-7"><a href="thursday-october-27-2022.html#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="thursday-october-27-2022.html#cb19-8" aria-hidden="true" tabindex="-1"></a>T2.ppp <span class="ot">&lt;-</span> <span class="fu">superimpose</span>(<span class="at">H =</span> H.ppp, </span>
<span id="cb19-9"><a href="thursday-october-27-2022.html#cb19-9" aria-hidden="true" tabindex="-1"></a>                      <span class="at">I =</span> I.ppp)</span></code></pre></div>
<pre><code>## Warning: data contain duplicated points</code></pre>
<p>See <a href="https://en.wikipedia.org/wiki/Enhanced_Fujita_scale" class="uri">https://en.wikipedia.org/wiki/Enhanced_Fujita_scale</a> for definitions of EF tornado rating.</p>
<p>The chance that a tornado chosen at random is intense (EF3+) is 4.2%. Plot the event locations for the set of intense tornadoes.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="thursday-october-27-2022.html#cb21-1" aria-hidden="true" tabindex="-1"></a>I.ppp <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="thursday-october-27-2022.html#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="at">pch =</span> <span class="dv">25</span>, </span>
<span id="cb21-3"><a href="thursday-october-27-2022.html#cb21-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">cols =</span> <span class="st">&quot;red&quot;</span>, </span>
<span id="cb21-4"><a href="thursday-october-27-2022.html#cb21-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="st">&quot;&quot;</span>)</span>
<span id="cb21-5"><a href="thursday-october-27-2022.html#cb21-5" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="sc">|&gt;</span></span>
<span id="cb21-6"><a href="thursday-october-27-2022.html#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="at">add =</span> <span class="cn">TRUE</span>, </span>
<span id="cb21-7"><a href="thursday-october-27-2022.html#cb21-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">lwd =</span> .<span class="dv">1</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>To get the relative risk use the <code>relrisk()</code> function. If X is a multi-type point pattern with factor marks and two levels of the factor then the events of the first type (the first level of <code>marks(X)</code>) are treated as controls (conditionals) or non-events, and events of the second type are treated as cases.</p>
<p>The <code>relrisk()</code> function estimates the local chance of a case (i.e. the probability <span class="math inline">\(p(u)\)</span> that a point at <span class="math inline">\(u\)</span> will be a case) using a kernel density smoother. The bandwidth for the kernel is specified or can be found through an iterative cross-validation procedure (recall the bandwidth selection procedure used in geographic regression) using the <code>bw.relrisk()</code> function (Lesson 12).</p>
<p>The bandwidth has units of length (here meters). You specify a minimum and maximum bandwidth with the <code>hmin =</code> and <code>hmax =</code> arguments. This takes a few seconds.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="thursday-october-27-2022.html#cb22-1" aria-hidden="true" tabindex="-1"></a>( bw <span class="ot">&lt;-</span> T2.ppp <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="thursday-october-27-2022.html#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bw.relrisk</span>(<span class="at">hmin =</span> <span class="dv">1000</span>,</span>
<span id="cb22-3"><a href="thursday-october-27-2022.html#cb22-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">hmax =</span> <span class="dv">200000</span>) )</span></code></pre></div>
<pre><code>##    sigma 
## 119770.4</code></pre>
<p>The optimal bandwidth (<code>sigma</code>) is 119770 meters or about 120 km.</p>
<p>Now estimate the relative risk at points defined by a 256 by 256 grid and using the 120 km bandwidth for the kernel smoother.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="thursday-october-27-2022.html#cb24-1" aria-hidden="true" tabindex="-1"></a>rr.im <span class="ot">&lt;-</span> T2.ppp <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="thursday-october-27-2022.html#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relrisk</span>(<span class="at">sigma =</span> bw,</span>
<span id="cb24-3"><a href="thursday-october-27-2022.html#cb24-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">dimyx =</span> <span class="fu">c</span>(<span class="dv">256</span>, <span class="dv">256</span>))</span></code></pre></div>
<p>The result is an object of class <code>im</code> (image) with values you interpret as the conditional probability of an ‘intense’ tornado.</p>
<p>You retrieve the range of probabilities with the <code>range()</code> function. Note that many of the values are <code>NA</code> corresponding pixels that are outside the window so you set the <code>na.rm</code> argument to <code>TRUE</code>.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="thursday-october-27-2022.html#cb25-1" aria-hidden="true" tabindex="-1"></a>rr.im <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="thursday-october-27-2022.html#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">range</span>(<span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 0.005003694 0.060170214</code></pre>
<p>The probabilities range from a low of .5% to a high of 6%. This range compares with the statewide average probability of 4.2%.</p>
<p>Map the probabilities with the <code>plot()</code> method.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="thursday-october-27-2022.html#cb27-1" aria-hidden="true" tabindex="-1"></a>rr.im <span class="sc">|&gt;</span></span>
<span id="cb27-2"><a href="thursday-october-27-2022.html#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Improve the map by converting the image to a raster (<code>SpatRaster</code>), assigning the CRS, and then using functions from the {tmap} package.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="thursday-october-27-2022.html#cb28-1" aria-hidden="true" tabindex="-1"></a>rr.r <span class="ot">&lt;-</span> rr.im <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a href="thursday-october-27-2022.html#cb28-2" aria-hidden="true" tabindex="-1"></a>  terra<span class="sc">::</span><span class="fu">rast</span>()</span>
<span id="cb28-3"><a href="thursday-october-27-2022.html#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="thursday-october-27-2022.html#cb28-4" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">crs</span>(rr.r) <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_crs</span>(Torn.sf)<span class="sc">$</span>proj4string</span>
<span id="cb28-5"><a href="thursday-october-27-2022.html#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="thursday-october-27-2022.html#cb28-6" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_shape</span>(rr.r) <span class="sc">+</span></span>
<span id="cb28-7"><a href="thursday-october-27-2022.html#cb28-7" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_raster</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>The relative chance of a more damaging tornado peaks across the northeast part of the state.</p>
<p>Since the relative risk is computed for any point across the domain, it is interesting to extract these relative risks for cities and towns.</p>
<p>You get city locations with the <code>us_cities()</code> function from the {USAboundaries} package that extracts a simple feature data frame of cities. The CRS is 4326 and you filter to keep only cities with at least 100K residents in 2010.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="thursday-october-27-2022.html#cb29-1" aria-hidden="true" tabindex="-1"></a>( Cities.sf <span class="ot">&lt;-</span> USAboundaries<span class="sc">::</span><span class="fu">us_cities</span>(<span class="at">state =</span> <span class="st">&quot;TX&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb29-2"><a href="thursday-october-27-2022.html#cb29-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> sf<span class="sc">::</span><span class="fu">st_crs</span>(Torn.sf)) <span class="sc">|&gt;</span></span>
<span id="cb29-3"><a href="thursday-october-27-2022.html#cb29-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(population <span class="sc">&gt;</span> <span class="dv">100000</span>) )</span></code></pre></div>
<pre><code>## City populations for contemporary data come from the 2010 census.</code></pre>
<pre><code>## Simple feature collection with 29 features and 12 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: 893306.2 ymin: 5900924 xmax: 2063028 ymax: 6916010
## Projected CRS: NAD83 / Texas Centric Lambert Conformal
## # A tibble: 29 × 13
##    city   state…¹ state…² county count…³ stplf…⁴ name_…⁵ city_…⁶ popul…⁷ place…⁸
##  * &lt;chr&gt;  &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;  
##  1 Abile… Texas   TX      TAYLOR Taylor  4801000 Abilen… US Cen… US Cen… Incorp…
##  2 Amari… Texas   TX      multi… Multip… 4803000 Amaril… US Cen… US Cen… Incorp…
##  3 Arlin… Texas   TX      TARRA… Tarrant 4804000 Arling… US Cen… US Cen… Incorp…
##  4 Austin Texas   TX      TRAVIS Travis  4805000 Austin… US Cen… US Cen… Incorp…
##  5 Beaum… Texas   TX      JEFFE… Jeffer… 4807000 Beaumo… US Cen… US Cen… Incorp…
##  6 Brown… Texas   TX      CAMER… Cameron 4810768 Browns… US Cen… US Cen… Incorp…
##  7 Carro… Texas   TX      Dallas Dallas  4813024 Carrol… US Cen… US Cen… Incorp…
##  8 Corpu… Texas   TX      NUECES Nueces  4817000 Corpus… US Cen… US Cen… Incorp…
##  9 Dallas Texas   TX      DALLAS Dallas  4819000 Dallas… US Cen… US Cen… Incorp…
## 10 Denton Texas   TX      DENTON Denton  4819972 Denton… US Cen… US Cen… Incorp…
## # … with 19 more rows, 3 more variables: year &lt;int&gt;, population &lt;int&gt;,
## #   geometry &lt;POINT [m]&gt;, and abbreviated variable names ¹​state_name,
## #   ²​state_abbr, ³​county_name, ⁴​stplfips_2010, ⁵​name_2010, ⁶​city_source,
## #   ⁷​population_source, ⁸​place_type</code></pre>
<p>The resulting simple feature data frame contains 29 rows (one row for each city with a population of at least 100K) and 13 columns. The geometry column is S3 simple feature column of type <code>POINT</code> as the center location.</p>
<p>Use the <code>extract()</code> function from the {terra} package to get a data frame containing the relative risk at each of the 29 cities.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="thursday-october-27-2022.html#cb32-1" aria-hidden="true" tabindex="-1"></a>( rr.v <span class="ot">&lt;-</span> rr.r <span class="sc">|&gt;</span></span>
<span id="cb32-2"><a href="thursday-october-27-2022.html#cb32-2" aria-hidden="true" tabindex="-1"></a>    terra<span class="sc">::</span><span class="fu">extract</span>(Cities.sf) <span class="sc">|&gt;</span></span>
<span id="cb32-3"><a href="thursday-october-27-2022.html#cb32-3" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">pull</span>(lyr<span class="fl">.1</span>) )</span></code></pre></div>
<pre><code>##  [1] 0.040181777 0.038711058 0.053751495 0.042836129 0.043559229 0.021952615
##  [7] 0.055164961 0.025910846 0.055613807 0.054530511 0.006268908 0.052901830
## [13] 0.055852968 0.056147124 0.054253968 0.040255552 0.054743220 0.047154604
## [19] 0.025026377 0.031264429 0.021623937 0.056305996 0.056243196 0.025423059
## [25] 0.040201363 0.055928375 0.036054024 0.051147204 0.053815148</code></pre>
<p>Attach these relative risk values to the <code>Cities.sf</code> object.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="thursday-october-27-2022.html#cb34-1" aria-hidden="true" tabindex="-1"></a>( Cities.sf <span class="ot">&lt;-</span> Cities.sf <span class="sc">|&gt;</span></span>
<span id="cb34-2"><a href="thursday-october-27-2022.html#cb34-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">rr =</span> rr.v) <span class="sc">|&gt;</span></span>
<span id="cb34-3"><a href="thursday-october-27-2022.html#cb34-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">arrange</span>(<span class="fu">desc</span>(rr)) )</span></code></pre></div>
<pre><code>## Simple feature collection with 29 features and 13 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: 893306.2 ymin: 5900924 xmax: 2063028 ymax: 6916010
## Projected CRS: NAD83 / Texas Centric Lambert Conformal
## # A tibble: 29 × 14
##    city   state…¹ state…² county count…³ stplf…⁴ name_…⁵ city_…⁶ popul…⁷ place…⁸
##    &lt;chr&gt;  &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;  
##  1 Mckin… Texas   TX      COLLIN Collin  4845744 McKinn… US Cen… US Cen… Incorp…
##  2 Mesqu… Texas   TX      Dallas Dallas  4847892 Mesqui… US Cen… US Cen… Incorp…
##  3 Garla… Texas   TX      Dallas Dallas  4829000 Garlan… US Cen… US Cen… Incorp…
##  4 Plano  Texas   TX      Collin Collin  4858016 Plano … US Cen… US Cen… Incorp…
##  5 Frisco Texas   TX      Collin Collin  4827684 Frisco… US Cen… US Cen… Incorp…
##  6 Dallas Texas   TX      DALLAS Dallas  4819000 Dallas… US Cen… US Cen… Incorp…
##  7 Carro… Texas   TX      Dallas Dallas  4813024 Carrol… US Cen… US Cen… Incorp…
##  8 Irving Texas   TX      Dallas Dallas  4837000 Irving… US Cen… US Cen… Incorp…
##  9 Denton Texas   TX      DENTON Denton  4819972 Denton… US Cen… US Cen… Incorp…
## 10 Grand… Texas   TX      Dallas Dallas  4830464 Grand … US Cen… US Cen… Incorp…
## # … with 19 more rows, 4 more variables: year &lt;int&gt;, population &lt;int&gt;,
## #   geometry &lt;POINT [m]&gt;, rr &lt;dbl&gt;, and abbreviated variable names ¹​state_name,
## #   ²​state_abbr, ³​county_name, ⁴​stplfips_2010, ⁵​name_2010, ⁶​city_source,
## #   ⁷​population_source, ⁸​place_type</code></pre>
<p>To illustrate the results create a graph using the <code>geom_lollipop()</code> function from the {ggalt} package. Use the package {scales} to allow for labels in percent.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="thursday-october-27-2022.html#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggalt)</span></code></pre></div>
<pre><code>## Loading required package: ggplot2</code></pre>
<pre><code>## Registered S3 methods overwritten by &#39;ggalt&#39;:
##   method                  from   
##   grid.draw.absoluteGrob  ggplot2
##   grobHeight.absoluteGrob ggplot2
##   grobWidth.absoluteGrob  ggplot2
##   grobX.absoluteGrob      ggplot2
##   grobY.absoluteGrob      ggplot2</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="thursday-october-27-2022.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;scales&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:spatstat.geom&#39;:
## 
##     rescale</code></pre>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="thursday-october-27-2022.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Cities.sf, </span>
<span id="cb42-2"><a href="thursday-october-27-2022.html#cb42-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(city, rr), <span class="at">y =</span> rr)) <span class="sc">+</span></span>
<span id="cb42-3"><a href="thursday-october-27-2022.html#cb42-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_lollipop</span>(<span class="at">point.colour =</span> <span class="st">&quot;steelblue&quot;</span>, </span>
<span id="cb42-4"><a href="thursday-october-27-2022.html#cb42-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">point.size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb42-5"><a href="thursday-october-27-2022.html#cb42-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> percent, </span>
<span id="cb42-6"><a href="thursday-october-27-2022.html#cb42-6" aria-hidden="true" tabindex="-1"></a>                       <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, .<span class="dv">0625</span>)) <span class="sc">+</span></span>
<span id="cb42-7"><a href="thursday-october-27-2022.html#cb42-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb42-8"><a href="thursday-october-27-2022.html#cb42-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, </span>
<span id="cb42-9"><a href="thursday-october-27-2022.html#cb42-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="cn">NULL</span>, </span>
<span id="cb42-10"><a href="thursday-october-27-2022.html#cb42-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">title =</span> <span class="st">&quot;Historical chance that a tornado caused at least EF3 damage&quot;</span>,</span>
<span id="cb42-11"><a href="thursday-october-27-2022.html#cb42-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">subtitle =</span> <span class="st">&quot;Cities in Texas with a 2010 population &gt; 100,000&quot;</span>,</span>
<span id="cb42-12"><a href="thursday-october-27-2022.html#cb42-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">caption =</span> <span class="st">&quot;Data from SPC (1950-2020)&quot;</span>) <span class="sc">+</span></span>
<span id="cb42-13"><a href="thursday-october-27-2022.html#cb42-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>Another example: Florida wildfires</p>
<p>Given a wildfire in Florida what is the probability that it was started by lightning?</p>
<p>Import wildfire data (available here: <a href="https://www.fs.usda.gov/rds/archive/catalog/RDS-2013-0009.4" class="uri">https://www.fs.usda.gov/rds/archive/catalog/RDS-2013-0009.4</a>) as a simple feature data frame and transform the native CRS to a Florida GDL Albers (EPSG 3086).</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="thursday-october-27-2022.html#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="st">&quot;FL_Fires&quot;</span> <span class="sc">%in%</span> <span class="fu">list.files</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>))){</span>
<span id="cb43-2"><a href="thursday-october-27-2022.html#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">download.file</span>(<span class="st">&quot;http://myweb.fsu.edu/jelsner/temp/data/FL_Fires.zip&quot;</span>,</span>
<span id="cb43-3"><a href="thursday-october-27-2022.html#cb43-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">destfile =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;FL_Fires.zip&quot;</span>))</span>
<span id="cb43-4"><a href="thursday-october-27-2022.html#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="fu">unzip</span>(<span class="at">zipfile =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;FL_Fires.zip&quot;</span>),</span>
<span id="cb43-5"><a href="thursday-october-27-2022.html#cb43-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">exdir =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>))</span>
<span id="cb43-6"><a href="thursday-october-27-2022.html#cb43-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb43-7"><a href="thursday-october-27-2022.html#cb43-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-8"><a href="thursday-october-27-2022.html#cb43-8" aria-hidden="true" tabindex="-1"></a>FL_Fires.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="at">dsn =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;FL_Fires&quot;</span>)) <span class="sc">|&gt;</span></span>
<span id="cb43-9"><a href="thursday-october-27-2022.html#cb43-9" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3086</span>)</span></code></pre></div>
<pre><code>## Reading layer `FL_Fires&#39; from data source 
##   `/Users/jameselsner/Desktop/ClassNotes/ASS-2022/data/FL_Fires&#39; 
##   using driver `ESRI Shapefile&#39;
## Simple feature collection with 90261 features and 37 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -9750382 ymin: 2824449 xmax: -8908899 ymax: 3632749
## Projected CRS: Mercator_2SP</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="thursday-october-27-2022.html#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(FL_Fires.sf)</span></code></pre></div>
<pre><code>## [1] 90261    38</code></pre>
<p>Each row is a unique fire and the data spans the period 1992-2015. There are over 90K rows and 38 variables.</p>
<p>To make things run faster, here you analyze only a random sample of all the data. You do this with the <code>dplyr::sample_n()</code> function where the argument <code>size =</code> specifies the number of rows to choose at random. Save the sample of events to the object <code>FL_FiresS.sf</code>. First set the seed for the random number generator so that the set of rows chosen will be the same every time you run the code.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="thursday-october-27-2022.html#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">78732</span>)</span>
<span id="cb47-2"><a href="thursday-october-27-2022.html#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="thursday-october-27-2022.html#cb47-3" aria-hidden="true" tabindex="-1"></a>FL_FiresS.sf <span class="ot">&lt;-</span> FL_Fires.sf <span class="sc">|&gt;</span></span>
<span id="cb47-4"><a href="thursday-october-27-2022.html#cb47-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">sample_n</span>(<span class="at">size =</span> <span class="dv">2000</span>)</span>
<span id="cb47-5"><a href="thursday-october-27-2022.html#cb47-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-6"><a href="thursday-october-27-2022.html#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(FL_FiresS.sf)</span></code></pre></div>
<pre><code>## [1] 2000   38</code></pre>
<p>The result is a simple feature data frame with exactly 2000 rows.</p>
<p>The character variable <code>STAT_CAU_1</code> indicates the cause of the wildfire.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="thursday-october-27-2022.html#cb49-1" aria-hidden="true" tabindex="-1"></a>FL_FiresS.sf<span class="sc">$</span>STAT_CAU_1 <span class="sc">|&gt;</span></span>
<span id="cb49-2"><a href="thursday-october-27-2022.html#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>()</span></code></pre></div>
<pre><code>## 
##             Arson          Campfire          Children    Debris Burning 
##               147                32                93               239 
##     Equipment Use         Fireworks         Lightning     Miscellaneous 
##               308                 4               495               199 
## Missing/Undefined         Powerline          Railroad           Smoking 
##                74                 9               365                31 
##         Structure 
##                 4</code></pre>
<p>There are 13 causes (listed in alphabetical order) with various occurrence frequencies. Lightning is the most common.</p>
<p>To analyze these data as spatial events, you first convert the simple feature data to a <code>ppp</code> object over a window defined by the state boundaries. Use the cause of the fire as a factor mark.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="thursday-october-27-2022.html#cb51-1" aria-hidden="true" tabindex="-1"></a>F.ppp <span class="ot">&lt;-</span> FL_FiresS.sf[<span class="st">&quot;STAT_CAU_1&quot;</span>] <span class="sc">|&gt;</span></span>
<span id="cb51-2"><a href="thursday-october-27-2022.html#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.ppp</span>()</span>
<span id="cb51-3"><a href="thursday-october-27-2022.html#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="thursday-october-27-2022.html#cb51-4" aria-hidden="true" tabindex="-1"></a>W <span class="ot">&lt;-</span> USAboundaries<span class="sc">::</span><span class="fu">us_states</span>(<span class="at">states =</span> <span class="st">&quot;Florida&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb51-5"><a href="thursday-october-27-2022.html#cb51-5" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> sf<span class="sc">::</span><span class="fu">st_crs</span>(FL_Fires.sf)) <span class="sc">|&gt;</span></span>
<span id="cb51-6"><a href="thursday-october-27-2022.html#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.owin</span>()</span>
<span id="cb51-7"><a href="thursday-october-27-2022.html#cb51-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-8"><a href="thursday-october-27-2022.html#cb51-8" aria-hidden="true" tabindex="-1"></a>F.ppp <span class="ot">&lt;-</span> F.ppp[W]</span>
<span id="cb51-9"><a href="thursday-october-27-2022.html#cb51-9" aria-hidden="true" tabindex="-1"></a><span class="fu">marks</span>(F.ppp) <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">marks</span>(F.ppp)) <span class="co"># make the character marks factor marks</span></span>
<span id="cb51-10"><a href="thursday-october-27-2022.html#cb51-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-11"><a href="thursday-october-27-2022.html#cb51-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(F.ppp)</span></code></pre></div>
<pre><code>## Marked planar point pattern:  2000 points
## Average intensity 1.297232e-08 points per square unit
## 
## *Pattern contains duplicated points*
## 
## Coordinates are given to 2 decimal places
## i.e. rounded to the nearest multiple of 0.01 units
## 
## Multitype:
##                   frequency proportion    intensity
## Arson                   147     0.0735 9.534653e-10
## Campfire                 32     0.0160 2.075571e-10
## Children                 93     0.0465 6.032128e-10
## Debris Burning          239     0.1195 1.550192e-09
## Equipment Use           308     0.1540 1.997737e-09
## Fireworks                 4     0.0020 2.594463e-11
## Lightning               495     0.2475 3.210649e-09
## Miscellaneous           199     0.0995 1.290746e-09
## Missing/Undefined        74     0.0370 4.799757e-10
## Powerline                 9     0.0045 5.837543e-11
## Railroad                365     0.1825 2.367448e-09
## Smoking                  31     0.0155 2.010709e-10
## Structure                 4     0.0020 2.594463e-11
## 
## Window: polygonal boundary
## 4 separate polygons (no holes)
##            vertices        area relative.area
## polygon 1       356 1.53185e+11      0.994000
## polygon 2        15 8.05114e+08      0.005220
## polygon 3         5 7.46249e+07      0.000484
## polygon 4         5 1.09937e+08      0.000713
## enclosing rectangle: [52649.1, 794026.5] x [56850.4, 781579.4] units
##                      (741400 x 724700 units)
## Window area = 1.54174e+11 square units
## Fraction of frame area: 0.287</code></pre>
<p>Output from the <code>summary()</code> method displays a table of frequency by type including the proportion and the average spatial intensity (per square meters).</p>
<p>The probability that a wildfire is caused by lightning is about 25% (<code>proportion</code> column of the frequency versus type table). How does this probability vary over the state?</p>
<p>Note that the window contains four separate polygons to capture the main boundary (<code>polygon 4</code>) and the Florida Keys.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="thursday-october-27-2022.html#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(W)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>First split the object <code>F.ppp</code> on whether or not the cause was lightning and then merge the two event types and assign names <code>NL</code> (human caused) and <code>L</code> (lightning caused) as marks.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="thursday-october-27-2022.html#cb54-1" aria-hidden="true" tabindex="-1"></a>L.ppp <span class="ot">&lt;-</span> F.ppp[F.ppp<span class="sc">$</span>marks <span class="sc">==</span> <span class="st">&quot;Lightning&quot;</span>] <span class="sc">|&gt;</span></span>
<span id="cb54-2"><a href="thursday-october-27-2022.html#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unmark</span>()</span>
<span id="cb54-3"><a href="thursday-october-27-2022.html#cb54-3" aria-hidden="true" tabindex="-1"></a>NL.ppp <span class="ot">&lt;-</span> F.ppp[F.ppp<span class="sc">$</span>marks <span class="sc">!=</span> <span class="st">&quot;Lightning&quot;</span>] <span class="sc">|&gt;</span></span>
<span id="cb54-4"><a href="thursday-october-27-2022.html#cb54-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unmark</span>()</span>
<span id="cb54-5"><a href="thursday-october-27-2022.html#cb54-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-6"><a href="thursday-october-27-2022.html#cb54-6" aria-hidden="true" tabindex="-1"></a>LNL.ppp <span class="ot">&lt;-</span> <span class="fu">superimpose</span>(<span class="at">NL =</span> NL.ppp, </span>
<span id="cb54-7"><a href="thursday-october-27-2022.html#cb54-7" aria-hidden="true" tabindex="-1"></a>                       <span class="at">L =</span> L.ppp)</span></code></pre></div>
<pre><code>## Warning: data contain duplicated points</code></pre>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="thursday-october-27-2022.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(LNL.ppp)</span></code></pre></div>
<pre><code>## Marked planar point pattern:  2000 points
## Average intensity 1.297232e-08 points per square unit
## 
## *Pattern contains duplicated points*
## 
## Coordinates are given to 2 decimal places
## i.e. rounded to the nearest multiple of 0.01 units
## 
## Multitype:
##    frequency proportion    intensity
## NL      1505     0.7525 9.761669e-09
## L        495     0.2475 3.210649e-09
## 
## Window: polygonal boundary
## 4 separate polygons (no holes)
##            vertices        area relative.area
## polygon 1       356 1.53185e+11      0.994000
## polygon 2        15 8.05114e+08      0.005220
## polygon 3         5 7.46249e+07      0.000484
## polygon 4         5 1.09937e+08      0.000713
## enclosing rectangle: [52649.1, 794026.5] x [56850.4, 781579.4] units
##                      (741400 x 724700 units)
## Window area = 1.54174e+11 square units
## Fraction of frame area: 0.287</code></pre>
<p>Now the two types are <code>NL</code> and <code>L</code> composing 75% and 25% of all wildfire events.</p>
<p>The function <code>relrisk()</code> computes the spatially-varying probability of a case (event type), (i.e. the probability <span class="math inline">\(p(u)\)</span> that a point at location <span class="math inline">\(u\)</span> will be a case).</p>
<p>Here you compute the relative risk on a 256 by 256 grid.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="thursday-october-27-2022.html#cb58-1" aria-hidden="true" tabindex="-1"></a>wfr.im <span class="ot">&lt;-</span> <span class="fu">relrisk</span>(LNL.ppp, </span>
<span id="cb58-2"><a href="thursday-october-27-2022.html#cb58-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">dimyx =</span> <span class="fu">c</span>(<span class="dv">256</span>, <span class="dv">256</span>))</span></code></pre></div>
<p>Create a map from the raster by first converting the image object to a raster object and assigning the CRS with the <code>crs()</code> function from the {terra} package. Add the county borders for geographic reference.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="thursday-october-27-2022.html#cb59-1" aria-hidden="true" tabindex="-1"></a>wfr.r <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">rast</span>(wfr.im)</span>
<span id="cb59-2"><a href="thursday-october-27-2022.html#cb59-2" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">crs</span>(wfr.r) <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_crs</span>(FL_Fires.sf)<span class="sc">$</span>proj4string</span>
<span id="cb59-3"><a href="thursday-october-27-2022.html#cb59-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-4"><a href="thursday-october-27-2022.html#cb59-4" aria-hidden="true" tabindex="-1"></a>FL.sf <span class="ot">&lt;-</span> USAboundaries<span class="sc">::</span><span class="fu">us_counties</span>(<span class="at">state =</span> <span class="st">&quot;FL&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb59-5"><a href="thursday-october-27-2022.html#cb59-5" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> sf<span class="sc">::</span><span class="fu">st_crs</span>(FL_Fires.sf))</span>
<span id="cb59-6"><a href="thursday-october-27-2022.html#cb59-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-7"><a href="thursday-october-27-2022.html#cb59-7" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_shape</span>(wfr.r) <span class="sc">+</span></span>
<span id="cb59-8"><a href="thursday-october-27-2022.html#cb59-8" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_raster</span>(<span class="at">title =</span> <span class="st">&quot;Probability&quot;</span>) <span class="sc">+</span></span>
<span id="cb59-9"><a href="thursday-october-27-2022.html#cb59-9" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_shape</span>(FL.sf) <span class="sc">+</span></span>
<span id="cb59-10"><a href="thursday-october-27-2022.html#cb59-10" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb59-11"><a href="thursday-october-27-2022.html#cb59-11" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_legend</span>(<span class="at">position =</span> <span class="fu">c</span>(<span class="st">&quot;left&quot;</span>, <span class="st">&quot;center&quot;</span>) ) <span class="sc">+</span></span>
<span id="cb59-12"><a href="thursday-october-27-2022.html#cb59-12" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">&quot;Chance a wildfire was started by lightning (1992-2015)&quot;</span>,</span>
<span id="cb59-13"><a href="thursday-october-27-2022.html#cb59-13" aria-hidden="true" tabindex="-1"></a>                <span class="at">main.title.size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb59-14"><a href="thursday-october-27-2022.html#cb59-14" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_compass</span>(<span class="at">position =</span> <span class="fu">c</span>(<span class="st">&quot;right&quot;</span>, <span class="st">&quot;top&quot;</span>)) <span class="sc">+</span></span>
<span id="cb59-15"><a href="thursday-october-27-2022.html#cb59-15" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_credits</span>(<span class="at">text =</span> <span class="st">&quot;Data source: Karen Short https://doi.org/10.2737/RDS-2013-0009.4&quot;</span>,</span>
<span id="cb59-16"><a href="thursday-october-27-2022.html#cb59-16" aria-hidden="true" tabindex="-1"></a>                 <span class="at">position =</span> <span class="fu">c</span>(<span class="st">&quot;left&quot;</span>, <span class="st">&quot;bottom&quot;</span>)) </span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
</div>
<div id="estimating-second-moment-properties-of-spatial-events" class="section level2 unnumbered hasAnchor">
<h2>Estimating second-moment properties of spatial events<a href="thursday-october-27-2022.html#estimating-second-moment-properties-of-spatial-events" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>It is important to distinguish between a point pattern and a point process: the latter is the stochastic process that, when sampled, generates a point pattern. A set of data is always a point pattern, and inference involves figuring out the properties of a process that could have generated a pattern like the one you observed.</p>
<p>Properties of a spatial point process include: First order properties or intensity function, which measures the number of events per area unit; this function is spatially varying for a inhomogeneous point process</p>
<p>Second order properties, e.g. pairwise interactions: given a constant or varying intensity function, are events distributed independently from one another, or do they tend to attract each other (clustering) or repulse each other (appear regularly distributed, compared to complete spatial randomness)</p>
<p>On example of clustering occurs with the location of trees in a forest. A tree’s seed dispersal mechanism leads to a greater likelihood of another tree nearby.</p>
<p>Let <span class="math inline">\(r\)</span> be the distance between two event locations or the distance between an event and an arbitrary point within the domain, then functions to describe clustering include:</p>
<ul>
<li><p>The nearest neighbor distance function <span class="math inline">\(G(r)\)</span>: The cumulative distribution of the distances from an event to the nearest other event (event-to-event function). It summarizes the distance between events (amount of clustering).</p></li>
<li><p>The empty space function <span class="math inline">\(F(r)\)</span>: The cumulative distribution of the distances from a point in the domain to the nearest event (point-to-event function). It summarizes the distance gaps between events (amount of gappiness or lacunarity).</p></li>
<li><p>The reduced second-moment function (Ripley <span class="math inline">\(K\)</span>) <span class="math inline">\(K(r)\)</span>: Defined such that <span class="math inline">\(\lambda \times K(r)\)</span> is the expected number of <em>additional</em> events within a distance <span class="math inline">\(r\)</span> of an event, where <span class="math inline">\(\lambda\)</span> is the average intensity of the events. It is a commonly used measure of the spatial autocorrelation among the events.</p></li>
</ul>
<p><em>Key idea</em>: To assess the degree of clustering and its significance (in a statistical sense), you estimate values of the function using your data and compare the resulting curve (empirical curve) to a theoretical curve assuming a non-cluster process.</p>
<p>The theoretical curve is well defined for homogeneous point patterns (recall: CSR–complete spatial randomness). Deviations of an ‘empirical’ curve from a theoretical curve provides evidence against CSR.</p>
<p>The theoretical functions assuming a homogeneous Poisson process are:</p>
<ul>
<li><span class="math display">\[F(r) = G(r) = 1 - \exp(-\lambda \pi r^2)\]</span></li>
<li><span class="math display">\[K(r) = \pi r^2\]</span></li>
</ul>
<p>where <span class="math inline">\(\lambda\)</span> is the domain average spatial intensity <span class="math inline">\(\exp()\)</span> is the exponential function, and <span class="math inline">\(\pi\)</span> is the ratio of a circles circumference to its diameter.</p>
<p>Recall the Swedish pine saplings data that comes with the {spatstat} package.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="thursday-october-27-2022.html#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(swedishpines)</span>
<span id="cb60-2"><a href="thursday-october-27-2022.html#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(swedishpines)</span></code></pre></div>
<pre><code>## [1] &quot;ppp&quot;</code></pre>
<p>Assign the data to an object called <code>SP</code> to reduce the amount of typing.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="thursday-october-27-2022.html#cb62-1" aria-hidden="true" tabindex="-1"></a>( SP <span class="ot">&lt;-</span> swedishpines )</span></code></pre></div>
<pre><code>## Planar point pattern: 71 points
## window: rectangle = [0, 96] x [0, 100] units (one unit = 0.1 metres)</code></pre>
<p>The output indicates that there are 71 events within a rectangle window 96 by 100 units where one unit is .1 meters.</p>
<p>Plot the event locations together with the window.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="thursday-october-27-2022.html#cb64-1" aria-hidden="true" tabindex="-1"></a>SP <span class="sc">|&gt;</span></span>
<span id="cb64-2"><a href="thursday-october-27-2022.html#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>It appears like the spatial distribution of the saplings is random. But as we noted looks can be deceiving.</p>
<p>You obtain the values for the nearest neighbor function using the <code>Gest()</code> function from the {spatstat} package. Use the argument <code>correction = "none"</code> so no corrections are made when computing the nearest-neighbor distances for events near the windo borders. Assign the output to a list object called <code>G</code>.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="thursday-october-27-2022.html#cb65-1" aria-hidden="true" tabindex="-1"></a>( G <span class="ot">&lt;-</span> <span class="fu">Gest</span>(SP,</span>
<span id="cb65-2"><a href="thursday-october-27-2022.html#cb65-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">correction =</span> <span class="st">&quot;none&quot;</span>) )</span></code></pre></div>
<pre><code>## Function value object (class &#39;fv&#39;)
## for the function r -&gt; G(r)
## ................................................
##      Math.label     Description                 
## r    r              distance argument r         
## theo G[pois](r)     theoretical Poisson G(r)    
## raw  hat(G)[raw](r) uncorrected estimate of G(r)
## ................................................
## Default plot formula:  .~r
## where &quot;.&quot; stands for &#39;raw&#39;, &#39;theo&#39;
## Recommended range of argument r: [0, 22.26]
## Available range of argument r: [0, 22.26]
## Unit of length: 0.1 metres</code></pre>
<p>The output includes the distance <code>r</code>, the raw uncorrected estimate of <span class="math inline">\(G(r)\)</span> (empirical estimate) at various distances, and a theoretical estimate at those same distances based on a homogeneous Poisson process.</p>
<p>Using the <code>plot()</code> method on the saved object <code>G</code> you compare the empirical estimates with the theoretical estimates. Here two horizontal lines are added to help with the interpretation.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="thursday-october-27-2022.html#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(G)</span>
<span id="cb67-2"><a href="thursday-october-27-2022.html#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">c</span>(.<span class="dv">2</span>, .<span class="dv">5</span>), </span>
<span id="cb67-3"><a href="thursday-october-27-2022.html#cb67-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="st">&quot;black&quot;</span>,</span>
<span id="cb67-4"><a href="thursday-october-27-2022.html#cb67-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>Values of G are on the vertical axis and values of inter-event distances (lag distances) are on the horizontal axis starting at 0. The black curve is the estimate of <span class="math inline">\(G_{raw}(r)\)</span> from the event locations and the red curve is <span class="math inline">\(G_{pois}(r)\)</span> estimated from a homogeneous Poisson process with the same average intensity as the pine saplings.</p>
<p>The horizontal dashed line at G = .2 intersects the black line at a lag distance (r) of 5 units. This means that 20% of the events have another event <em>within</em> 5 units. (20% of the saplings have another sapling withing .5 mete).</p>
<p>Imagine placing a disc of radius .5 meter around all 71 saplings then counting the number of saplings that have at least one other sapling under the disc. That number divided by 71 is G(r).</p>
<p>To check this compute all pairwise distances with the <code>pairdist()</code> function. Print the first 5 rows of the matrix.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="thursday-october-27-2022.html#cb68-1" aria-hidden="true" tabindex="-1"></a>PD.m <span class="ot">&lt;-</span> SP <span class="sc">|&gt;</span> </span>
<span id="cb68-2"><a href="thursday-october-27-2022.html#cb68-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairdist</span>()</span>
<span id="cb68-3"><a href="thursday-october-27-2022.html#cb68-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-4"><a href="thursday-october-27-2022.html#cb68-4" aria-hidden="true" tabindex="-1"></a>PD.m[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code></pre></div>
<pre><code>##          [,1]     [,2]     [,3]     [,4]     [,5]
## [1,]  0.00000 27.00000 37.01351 15.03330 54.33231
## [2,] 27.00000  0.00000 10.04988 12.04159 27.65863
## [3,] 37.01351 10.04988  0.00000 22.00000 17.72005
## [4,] 15.03330 12.04159 22.00000  0.00000 39.31921
## [5,] 54.33231 27.65863 17.72005 39.31921  0.00000</code></pre>
<p>The object <code>PD.m</code> is a 71 x 71 <code>matrix</code> of distances.</p>
<p>Sum the number of rows whose distances are less than 5 units and divide by the total number of saplings.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="thursday-october-27-2022.html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">rowSums</span>(PD.m <span class="sc">&lt;</span> <span class="dv">5</span>) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="fu">nrow</span>(PD.m)</span></code></pre></div>
<pre><code>## [1] 0.1971831</code></pre>
<p>This is the proportion of all the saplings in the data with another sapling within .5 meter.</p>
<p>The minus one means you don’t count the row containing the sapling over which you are summing (a sapling is not a neighbor of itself).</p>
<p>Returning to the plot, the horizontal dashed line at G = .5 intersects the black line at .8 meters indicating that 50% of the saplings have another sapling within .8 meter.</p>
<p>You see that for a given radius the <span class="math inline">\(G_{raw}\)</span> line is <em>below</em> the <span class="math inline">\(G_{pois}(r)\)</span> line indicating that there are <em>fewer</em> saplings with another sapling in the vicinity than expected by chance.</p>
<p>For example, if the saplings were arranged under a model of CSR, you would expect 20% of the pairwise distances to be within .3 meter and 50% of them to be within .55 meter.</p>
<p>You make a better plot by first converting the object <code>G</code> to a data frame and then using {ggplot2} functions. Here you do this and then remove estimates for distances greater than 1.1 meter and convert the distance units to meters.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="thursday-october-27-2022.html#cb72-1" aria-hidden="true" tabindex="-1"></a>G.df <span class="ot">&lt;-</span> G <span class="sc">|&gt;</span></span>
<span id="cb72-2"><a href="thursday-october-27-2022.html#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb72-3"><a href="thursday-october-27-2022.html#cb72-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(r <span class="sc">&lt;</span> <span class="dv">11</span>) <span class="sc">|&gt;</span></span>
<span id="cb72-4"><a href="thursday-october-27-2022.html#cb72-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">r =</span> r <span class="sc">*</span> .<span class="dv">1</span>)</span>
<span id="cb72-5"><a href="thursday-october-27-2022.html#cb72-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-6"><a href="thursday-october-27-2022.html#cb72-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> G.df, </span>
<span id="cb72-7"><a href="thursday-october-27-2022.html#cb72-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> raw)) <span class="sc">+</span></span>
<span id="cb72-8"><a href="thursday-october-27-2022.html#cb72-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb72-9"><a href="thursday-october-27-2022.html#cb72-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb72-10"><a href="thursday-october-27-2022.html#cb72-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb72-11"><a href="thursday-october-27-2022.html#cb72-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(.<span class="dv">2</span>, .<span class="dv">5</span>), <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb72-12"><a href="thursday-october-27-2022.html#cb72-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (m)&quot;</span>) <span class="sc">+</span>  <span class="fu">ylab</span>(<span class="st">&quot;G(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb72-13"><a href="thursday-october-27-2022.html#cb72-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="at">label =</span> <span class="st">&quot;Proportion of events having another event within a distance r&quot;</span>) <span class="sc">+</span></span>
<span id="cb72-14"><a href="thursday-october-27-2022.html#cb72-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<p>Although CSR appeared to be a good model for the spatial distribution of pine saplings when visually examined with a map, the inter-event distance function suggests the distribution is more regular than CSR.</p>
<p>What about the other functions?</p>
<p>Values for the empty space function are obtained using the <code>Fest()</code> function. Here you apply the Kaplan-Meier correction for edge effects with <code>correction = "km"</code>. The function returns the percent of the domain within a distance from any event.</p>
<p>Imagine again placing the disc, but this time on top of every point in the window and counting the number of points that have an event underneath.</p>
<p>Make a plot and add some lines to help with interpretation.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="thursday-october-27-2022.html#cb73-1" aria-hidden="true" tabindex="-1"></a>F.df <span class="ot">&lt;-</span> SP <span class="sc">|&gt;</span></span>
<span id="cb73-2"><a href="thursday-october-27-2022.html#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Fest</span>(<span class="at">correction =</span> <span class="st">&quot;km&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb73-3"><a href="thursday-october-27-2022.html#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb73-4"><a href="thursday-october-27-2022.html#cb73-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(r <span class="sc">&lt;</span> <span class="dv">11</span>) <span class="sc">|&gt;</span></span>
<span id="cb73-5"><a href="thursday-october-27-2022.html#cb73-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">r =</span> r <span class="sc">*</span> .<span class="dv">1</span>)</span>
<span id="cb73-6"><a href="thursday-october-27-2022.html#cb73-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-7"><a href="thursday-october-27-2022.html#cb73-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> F.df, </span>
<span id="cb73-8"><a href="thursday-october-27-2022.html#cb73-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> km)) <span class="sc">+</span></span>
<span id="cb73-9"><a href="thursday-october-27-2022.html#cb73-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb73-10"><a href="thursday-october-27-2022.html#cb73-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb73-11"><a href="thursday-october-27-2022.html#cb73-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(.<span class="dv">7</span>, .<span class="dv">58</span>), <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb73-12"><a href="thursday-october-27-2022.html#cb73-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> .<span class="dv">61</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb73-13"><a href="thursday-october-27-2022.html#cb73-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (m)&quot;</span>) <span class="sc">+</span>  <span class="fu">ylab</span>(<span class="st">&quot;F(r)&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="thursday-october-27-2022.html#cb74-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="at">label =</span> <span class="st">&quot;Proportion of the domain within a distance r of any event&quot;</span>) <span class="sc">+</span></span>
<span id="cb74-2"><a href="thursday-october-27-2022.html#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## NULL</code></pre>
<p>The horizontal dashed line at F = .7 intersects the black line at a distance of .61 meter. This means that 70% of the spatial domain is less than .61 meters from a sapling. The red line is the theoretical homogeneous Poisson process model. If the process was CSR slightly less than 58% (F = .58) of the domain would be less than .6 meter from a sapling. In words, the arrangement of saplings is less “gappy” (more regular) than expected by chance.</p>
<p>The J function is the ratio of the F function to the G function. For a CSR processes the value of J is one. The {spatstat} function is called <code>Jest()</code>. Here you compute the J function on the saplings data frame and then make a plot.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="thursday-october-27-2022.html#cb76-1" aria-hidden="true" tabindex="-1"></a>J.df <span class="ot">&lt;-</span> SP <span class="sc">|&gt;</span></span>
<span id="cb76-2"><a href="thursday-october-27-2022.html#cb76-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">Jest</span>() <span class="sc">|&gt;</span></span>
<span id="cb76-3"><a href="thursday-october-27-2022.html#cb76-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb76-4"><a href="thursday-october-27-2022.html#cb76-4" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">filter</span>(r <span class="sc">&lt;</span> <span class="dv">10</span>) <span class="sc">|&gt;</span></span>
<span id="cb76-5"><a href="thursday-october-27-2022.html#cb76-5" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">r =</span> r <span class="sc">*</span> .<span class="dv">1</span>)</span>
<span id="cb76-6"><a href="thursday-october-27-2022.html#cb76-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-7"><a href="thursday-october-27-2022.html#cb76-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> J.df, </span>
<span id="cb76-8"><a href="thursday-october-27-2022.html#cb76-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> km)) <span class="sc">+</span></span>
<span id="cb76-9"><a href="thursday-october-27-2022.html#cb76-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb76-10"><a href="thursday-october-27-2022.html#cb76-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb76-11"><a href="thursday-october-27-2022.html#cb76-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (m)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;J(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb76-12"><a href="thursday-october-27-2022.html#cb76-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="at">label =</span> <span class="st">&quot;F(r) / G(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb76-13"><a href="thursday-october-27-2022.html#cb76-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<p>There is a large and systematic departure of J from one (red line) for distances greater than about .5 meter. This is due to the regularity in the spacing of the saplings relative to CSR.</p>
<p>A commonly used distance function for assessing clustering in point pattern data is called Ripley’s K function. It is estimated with the <code>Kest()</code> function.</p>
<p>Mathematically it is defined as</p>
<p><span class="math display">\[
\hat K(r) = \frac{1}{\hat \lambda} \sum_{j \ne i} \frac{I(r_{ij} &lt; r)}{n}
\]</span></p>
<p>where <span class="math inline">\(r_{ij}\)</span> is the Euclidean distance between event <span class="math inline">\(i\)</span> and event <span class="math inline">\(j\)</span>, <span class="math inline">\(r\)</span> is the search radius, and <span class="math inline">\(\hat \lambda\)</span> is an estimate of the intensity <span class="math inline">\((\hat \lambda = n/|A|)\)</span> where <span class="math inline">\(|A|\)</span> is the window area and <span class="math inline">\(n\)</span> is the number of events. <span class="math inline">\(I(.)\)</span> is an indicator function equal to 1 when the expression <span class="math inline">\(r_{ij} &lt; r\)</span>, and 0 otherwise. If the events are homogeneous, <span class="math inline">\(\hat{K}(r)\)</span> increases at a rate proportional to <span class="math inline">\(\pi r^2\)</span>.</p>
</div>
<div id="examples-of-spatially-clustered-events" class="section level2 unnumbered hasAnchor">
<h2>Examples of spatially clustered events<a href="thursday-october-27-2022.html#examples-of-spatially-clustered-events" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The distance functions indicate that the pine sapling data is more “regular” than CSR suggesting the point pattern process likely has some inhibition factors.</p>
<p>On the other side are point pattern processes that result in data that are more clustered than CSR.</p>
<p>Consider the <code>ppp</code> object <code>bramblecanes</code> from the {spatstat} family of packages giving the locations and marks of bramble canes. A bramble is a rough (usually wild) tangled prickly shrub with thorny stems.</p>
<p>Rename the object then summarize its contents.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="thursday-october-27-2022.html#cb77-1" aria-hidden="true" tabindex="-1"></a>BC <span class="ot">&lt;-</span> bramblecanes</span>
<span id="cb77-2"><a href="thursday-october-27-2022.html#cb77-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-3"><a href="thursday-october-27-2022.html#cb77-3" aria-hidden="true" tabindex="-1"></a>BC <span class="sc">|&gt;</span></span>
<span id="cb77-4"><a href="thursday-october-27-2022.html#cb77-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## Marked planar point pattern:  823 points
## Average intensity 823 points per square unit (one unit = 9 metres)
## 
## Coordinates are given to 3 decimal places
## i.e. rounded to the nearest multiple of 0.001 units (one unit = 9 metres)
## 
## Multitype:
##   frequency proportion intensity
## 0       359 0.43620900       359
## 1       385 0.46780070       385
## 2        79 0.09599028        79
## 
## Window: rectangle = [0, 1] x [0, 1] units
## Window area = 1 square unit
## Unit of length: 9 metres</code></pre>
<p>The marks represent three different ages (as an ordered factor with 0 being the youngest) for the bramble canes. The unit of length is 9 meters.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="thursday-october-27-2022.html#cb79-1" aria-hidden="true" tabindex="-1"></a>BC <span class="sc">|&gt;</span></span>
<span id="cb79-2"><a href="thursday-october-27-2022.html#cb79-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>() </span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<p>Consider the point pattern for all the bramble canes regardless of age and estimate the <span class="math inline">\(K\)</span> function and a corresponding plot. Plot the empirical estimate of <span class="math inline">\(K\)</span> with an ‘isotropic’ correction at the domain borders (<code>iso</code>). Include a line for the theoretical <span class="math inline">\(K\)</span> under the assumption of CSR.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="thursday-october-27-2022.html#cb80-1" aria-hidden="true" tabindex="-1"></a>K.df <span class="ot">&lt;-</span> BC <span class="sc">|&gt;</span></span>
<span id="cb80-2"><a href="thursday-october-27-2022.html#cb80-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Kest</span>() <span class="sc">|&gt;</span></span>
<span id="cb80-3"><a href="thursday-october-27-2022.html#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb80-4"><a href="thursday-october-27-2022.html#cb80-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">r =</span> r <span class="sc">*</span> <span class="dv">9</span>)</span>
<span id="cb80-5"><a href="thursday-october-27-2022.html#cb80-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-6"><a href="thursday-october-27-2022.html#cb80-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> K.df, </span>
<span id="cb80-7"><a href="thursday-october-27-2022.html#cb80-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> iso)) <span class="sc">+</span></span>
<span id="cb80-8"><a href="thursday-october-27-2022.html#cb80-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb80-9"><a href="thursday-october-27-2022.html#cb80-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb80-10"><a href="thursday-october-27-2022.html#cb80-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fl">1.6</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb80-11"><a href="thursday-october-27-2022.html#cb80-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (m)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb80-12"><a href="thursday-october-27-2022.html#cb80-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<p>The <span class="math inline">\(K\)</span> estimate from the actual data (black line) lies to the left of the theoretical <span class="math inline">\(K\)</span> under CSR (red line). This means that for any distance from an event (lag distance) there tends to be <em>more</em> events within this distance (larger <span class="math inline">\(K\)</span>) than expected under CSR. You conclude that these bramble canes are more clustered than CRS.</p>
<p>The expected number of additional events is multiplied by the total number of events (823) so a value of .1 indicates that at a distance of 1.6 meters (where .1 value of <span class="math inline">\(K(r)\)</span> intersects the red curve) you should expect to see about 82 additional events.</p>
<p>Kansas tornado reports</p>
<p>Previously you mapped the intensity of tornadoes across Kansas using the start locations as point pattern data. Here we return to these data and consider only tornadoes since 1994.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="thursday-october-27-2022.html#cb81-1" aria-hidden="true" tabindex="-1"></a>Torn.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="at">dsn =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;1950-2020-torn-initpoint&quot;</span>)) <span class="sc">|&gt;</span></span>
<span id="cb81-2"><a href="thursday-october-27-2022.html#cb81-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3082</span>) <span class="sc">|&gt;</span></span>
<span id="cb81-3"><a href="thursday-october-27-2022.html#cb81-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(mag <span class="sc">&gt;=</span> <span class="dv">0</span>, yr <span class="sc">&gt;=</span> <span class="dv">1994</span>) <span class="sc">|&gt;</span></span>
<span id="cb81-4"><a href="thursday-october-27-2022.html#cb81-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">EF =</span> <span class="fu">as.factor</span>(mag)) <span class="sc">|&gt;</span></span>
<span id="cb81-5"><a href="thursday-october-27-2022.html#cb81-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(EF)</span></code></pre></div>
<pre><code>## Reading layer `1950-2020-torn-initpoint&#39; from data source 
##   `/Users/jameselsner/Desktop/ClassNotes/ASS-2022/data/1950-2020-torn-initpoint&#39; 
##   using driver `ESRI Shapefile&#39;
## Simple feature collection with 66244 features and 22 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -163.53 ymin: 17.7212 xmax: -64.7151 ymax: 61.02
## Geodetic CRS:  WGS 84</code></pre>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="thursday-october-27-2022.html#cb83-1" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="ot">&lt;-</span> Torn.sf[<span class="st">&quot;EF&quot;</span>] <span class="sc">|&gt;</span></span>
<span id="cb83-2"><a href="thursday-october-27-2022.html#cb83-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.ppp</span>()</span>
<span id="cb83-3"><a href="thursday-october-27-2022.html#cb83-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-4"><a href="thursday-october-27-2022.html#cb83-4" aria-hidden="true" tabindex="-1"></a>KS.sf <span class="ot">&lt;-</span> USAboundaries<span class="sc">::</span><span class="fu">us_states</span>(<span class="at">states =</span> <span class="st">&quot;Kansas&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb83-5"><a href="thursday-october-27-2022.html#cb83-5" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> sf<span class="sc">::</span><span class="fu">st_crs</span>(Torn.sf)<span class="sc">$</span>proj4string)</span>
<span id="cb83-6"><a href="thursday-october-27-2022.html#cb83-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-7"><a href="thursday-october-27-2022.html#cb83-7" aria-hidden="true" tabindex="-1"></a>W <span class="ot">&lt;-</span> KS.sf <span class="sc">|&gt;</span></span>
<span id="cb83-8"><a href="thursday-october-27-2022.html#cb83-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.owin</span>()</span>
<span id="cb83-9"><a href="thursday-october-27-2022.html#cb83-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-10"><a href="thursday-october-27-2022.html#cb83-10" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="ot">&lt;-</span> T.ppp[W] <span class="sc">|&gt;</span></span>
<span id="cb83-11"><a href="thursday-october-27-2022.html#cb83-11" aria-hidden="true" tabindex="-1"></a>  spatstat.geom<span class="sc">::</span><span class="fu">rescale</span>(<span class="at">s =</span> <span class="dv">1000</span>, </span>
<span id="cb83-12"><a href="thursday-october-27-2022.html#cb83-12" aria-hidden="true" tabindex="-1"></a>                         <span class="at">unitname =</span> <span class="st">&quot;km&quot;</span>)</span>
<span id="cb83-13"><a href="thursday-october-27-2022.html#cb83-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-14"><a href="thursday-october-27-2022.html#cb83-14" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="sc">|&gt;</span></span>
<span id="cb83-15"><a href="thursday-october-27-2022.html#cb83-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="thursday-october-27-2022.html#cb84-1" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="sc">|&gt;</span></span>
<span id="cb84-2"><a href="thursday-october-27-2022.html#cb84-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## Marked planar point pattern:  2241 points
## Average intensity 0.01038475 points per square km
## 
## *Pattern contains duplicated points*
## 
## Coordinates are given to 4 decimal places
## 
## Multitype:
##   frequency   proportion    intensity
## 0      1623 0.7242303000 7.520953e-03
## 1       436 0.1945560000 2.020416e-03
## 2       104 0.0464078500 4.819342e-04
## 3        64 0.0285586800 2.965749e-04
## 4        13 0.0058009820 6.024177e-05
## 5         1 0.0004462294 4.633982e-06
## 
## Window: polygonal boundary
## single connected closed polygon with 169 vertices
## enclosing rectangle: [1317.6759, 1980.2948] x [7114.969, 7458.57] km
##                      (662.6 x 343.6 km)
## Window area = 215797 square km
## Unit of length: 1 km
## Fraction of frame area: 0.948</code></pre>
<p>There are 2241 events with an average intensity of .01 events per square km (1 tornado per 10 square km over the 26-year period 1994–2020).</p>
<p>You compare the <span class="math inline">\(K\)</span> function estimated from the set of tornado reports with a theoretical <span class="math inline">\(K\)</span> function from a model of CSR.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="thursday-october-27-2022.html#cb86-1" aria-hidden="true" tabindex="-1"></a>K.df <span class="ot">&lt;-</span> T.ppp <span class="sc">|&gt;</span></span>
<span id="cb86-2"><a href="thursday-october-27-2022.html#cb86-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Kest</span>(<span class="at">correction =</span> <span class="st">&quot;iso&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb86-3"><a href="thursday-october-27-2022.html#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb86-4"><a href="thursday-october-27-2022.html#cb86-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Kdata =</span> iso <span class="sc">*</span> <span class="fu">sum</span>(<span class="fu">intensity</span>(T.ppp)),</span>
<span id="cb86-5"><a href="thursday-october-27-2022.html#cb86-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">Kpois =</span> theo <span class="sc">*</span> <span class="fu">sum</span>(<span class="fu">intensity</span>(T.ppp)))</span>
<span id="cb86-6"><a href="thursday-october-27-2022.html#cb86-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-7"><a href="thursday-october-27-2022.html#cb86-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> K.df, </span>
<span id="cb86-8"><a href="thursday-october-27-2022.html#cb86-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> Kdata)) <span class="sc">+</span></span>
<span id="cb86-9"><a href="thursday-october-27-2022.html#cb86-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb86-10"><a href="thursday-october-27-2022.html#cb86-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">y =</span> Kpois), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb86-11"><a href="thursday-october-27-2022.html#cb86-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">60</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb86-12"><a href="thursday-october-27-2022.html#cb86-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">129</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb86-13"><a href="thursday-october-27-2022.html#cb86-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">115</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb86-14"><a href="thursday-october-27-2022.html#cb86-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb86-15"><a href="thursday-october-27-2022.html#cb86-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="at">label =</span> <span class="st">&quot;Expected number of additional tornadoes within a distance r of any tornado&quot;</span>) <span class="sc">+</span></span>
<span id="cb86-16"><a href="thursday-october-27-2022.html#cb86-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<p>Consider the lag distance of 60 km along the horizontal axis. If you draw a vertical line at that distance it intersects the black curve at a height of about 129. This value indicates that at a distance of 60 km from a random tornado report about 129 other tornado reports are in the vicinity (on average).</p>
<p>Imagine placing a disc with radius 60 km centered on each event and then averaging the number of events under the disc over all events.</p>
<p>The red line is the theoretical curve under the assumption that the tornado reports are CSR across the state. If this is the case then you would expect to see about 115 tornadoes within a distance 60 km from any tornado (on average). Since there are MORE tornadoes than expected within a given 60 km radius you conclude that there is evidence for clustering (at this spatial scale).</p>
<p>The black line lies above the red line across distances from 0 to greater than 100 km.</p>
<p>What about the nearest neighbor function? Here you create a data frame from the output of the <code>Gest()</code> function and remove distances exceeding 8 km.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="thursday-october-27-2022.html#cb87-1" aria-hidden="true" tabindex="-1"></a>G.df <span class="ot">&lt;-</span> T.ppp <span class="sc">|&gt;</span></span>
<span id="cb87-2"><a href="thursday-october-27-2022.html#cb87-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Gest</span>(<span class="at">correction =</span> <span class="st">&quot;km&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb87-3"><a href="thursday-october-27-2022.html#cb87-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb87-4"><a href="thursday-october-27-2022.html#cb87-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(r <span class="sc">&lt;</span> <span class="dv">8</span>)</span>
<span id="cb87-5"><a href="thursday-october-27-2022.html#cb87-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-6"><a href="thursday-october-27-2022.html#cb87-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> G.df, </span>
<span id="cb87-7"><a href="thursday-october-27-2022.html#cb87-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> km)) <span class="sc">+</span></span>
<span id="cb87-8"><a href="thursday-october-27-2022.html#cb87-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb87-9"><a href="thursday-october-27-2022.html#cb87-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb87-10"><a href="thursday-october-27-2022.html#cb87-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> .<span class="dv">4</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb87-11"><a href="thursday-october-27-2022.html#cb87-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">c</span>(<span class="fl">3.2</span>, <span class="dv">4</span>), <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb87-12"><a href="thursday-october-27-2022.html#cb87-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;G(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb87-13"><a href="thursday-october-27-2022.html#cb87-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="at">label =</span> <span class="st">&quot;Proportion of tornadoes within a distance r of another tornado&quot;</span>) <span class="sc">+</span></span>
<span id="cb87-14"><a href="thursday-october-27-2022.html#cb87-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<p>The interpretation is that 40% (<span class="math inline">\(G\)</span> = .4) of all tornado reports have another report within a distance of about 3.2 km on average. If the reports where homogeneous Poisson then the distance would be 4 km. You conclude they are more clustered.</p>
<p>Note: With a data set containing many events the difference between the raw and border-corrected estimates of the distance functions is typically small.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tuesday-october-25-2022.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="thursday-october-27-2022-1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
