<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tuesday September 27, 2022 | GIS5122: Applied Spatial Statistics</title>
  <meta name="description" content="Tuesday September 27, 2022 | GIS5122: Applied Spatial Statistics" />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="Tuesday September 27, 2022 | GIS5122: Applied Spatial Statistics" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="jelsner/ASS-2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tuesday September 27, 2022 | GIS5122: Applied Spatial Statistics" />
  
  
  

<meta name="author" content="James B. Elsner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tuesday-september-20-2022.html"/>
<link rel="next" href="thursday-september-29-2022.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.1.1/leaflet.js"></script>
<script src="libs/leaflet-providers-1.9.0/leaflet-providers_1.9.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.1.1/leaflet-providers-plugin.js"></script>
<script src="libs/Leaflet.Sync-0.0.5/L.Map.Sync.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied Spatial Statistics</a></li>

<li class="divider"></li>
<li><a href="index.html#section"></a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i>Syllabus</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#contact-information"><i class="fa fa-check"></i>Contact information</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#course-description-and-expected-learning-outcomes"><i class="fa fa-check"></i>Course description and expected learning outcomes</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#materials-and-class-meetings"><i class="fa fa-check"></i>Materials and class meetings</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#grades-and-ethics"><i class="fa fa-check"></i>Grades and ethics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#outline-of-topics-and-schedule"><i class="fa fa-check"></i>Outline of topics and schedule</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#reference-materials"><i class="fa fa-check"></i>Reference materials</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#reproducible-research"><i class="fa fa-check"></i>Reproducible research</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html"><i class="fa fa-check"></i>Tuesday, August 23, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#install-r-and-rstudio-on-your-computer"><i class="fa fa-check"></i>Install R and RStudio on your computer</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#download-course-materials"><i class="fa fa-check"></i>Download course materials</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#read-the-syllabus"><i class="fa fa-check"></i>Read the syllabus</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#about-rstudio"><i class="fa fa-check"></i>About RStudio</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#lab-assignments"><i class="fa fa-check"></i>Lab assignments</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#getting-started-with-r"><i class="fa fa-check"></i>Getting started with R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#are-you-completely-new-to-r"><i class="fa fa-check"></i>Are you completely new to R?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html"><i class="fa fa-check"></i>Thursday, August 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#expectations"><i class="fa fa-check"></i>Expectations</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-science-workflow-with-r-markdown"><i class="fa fa-check"></i>Data science workflow with R markdown</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#an-introduction-to-using-r"><i class="fa fa-check"></i>An introduction to using R</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-frames"><i class="fa fa-check"></i>Data frames</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html"><i class="fa fa-check"></i>Tuesday August 30, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#working-with-data-frames"><i class="fa fa-check"></i>Working with data frames</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html"><i class="fa fa-check"></i>Thursday September 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#making-graphs"><i class="fa fa-check"></i>Making graphs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html"><i class="fa fa-check"></i>Thursday September 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#working-with-spatial-data"><i class="fa fa-check"></i>Working with spatial data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#geo-computation-on-simple-features"><i class="fa fa-check"></i>Geo-computation on simple features</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html"><i class="fa fa-check"></i>Tuesday September 13, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#spatial-data-subsets-and-joins"><i class="fa fa-check"></i>Spatial data subsets and joins</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#interpolation-using-areal-weights"><i class="fa fa-check"></i>Interpolation using areal weights</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html"><i class="fa fa-check"></i>Thursday September 15, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#s4-spatial-data-objects"><i class="fa fa-check"></i>S4 spatial data objects</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#working-with-raster-data"><i class="fa fa-check"></i>Working with raster data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html"><i class="fa fa-check"></i>Tuesday September 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#working-with-space-time-data"><i class="fa fa-check"></i>Working with space-time data</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#mapping-using-functions-from-the-ggplot2-package"><i class="fa fa-check"></i>Mapping using functions from the {ggplot2} package</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#mapping-using-functions-from-the-tmap-package"><i class="fa fa-check"></i>Mapping using functions from the {tmap} package</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#creating-an-interactive-map"><i class="fa fa-check"></i>Creating an interactive map</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#adding-an-inset-map"><i class="fa fa-check"></i>Adding an inset map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-27-2022.html"><a href="tuesday-september-27-2022.html"><i class="fa fa-check"></i>Tuesday September 27, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-27-2022.html"><a href="tuesday-september-27-2022.html#defining-spatial-neighborhoods-and-spatial-weights"><i class="fa fa-check"></i>Defining spatial neighborhoods and spatial weights</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-27-2022.html"><a href="tuesday-september-27-2022.html#computing-autocorrelation"><i class="fa fa-check"></i>Computing autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-27-2022.html"><a href="tuesday-september-27-2022.html#spatial-lag-and-its-relation-to-autocorrelation"><i class="fa fa-check"></i>Spatial lag and its relation to autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html"><i class="fa fa-check"></i>Thursday September 29, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#other-neighbor-definitions"><i class="fa fa-check"></i>Other neighbor definitions</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#assessing-the-statistical-significance-of-autocorrelation"><i class="fa fa-check"></i>Assessing the statistical significance of autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#bivariate-spatial-autocorrelation"><i class="fa fa-check"></i>Bivariate spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#local-indicators-of-spatial-autocorrelation"><i class="fa fa-check"></i>Local indicators of spatial autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html"><i class="fa fa-check"></i>Tuesday October 4, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#constraining-group-membership-based-on-spatial-autocorrelation"><i class="fa fa-check"></i>Constraining group membership based on spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#estimating-spatial-autocorrelation-in-model-residuals"><i class="fa fa-check"></i>Estimating spatial autocorrelation in model residuals</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#choosing-a-spatial-regression-model"><i class="fa fa-check"></i>Choosing a spatial regression model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html"><i class="fa fa-check"></i>Thursday October 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#fitting-and-interpreting-a-spatially-lagged-y-model"><i class="fa fa-check"></i>Fitting and interpreting a spatially-lagged Y model</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#fitting-and-interpreting-a-spatially-lagged-x-model"><i class="fa fa-check"></i>Fitting and interpreting a spatially-lagged X model</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#fitting-and-interpreting-spatial-durbin-models"><i class="fa fa-check"></i>Fitting and interpreting spatial Durbin models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html"><i class="fa fa-check"></i>Tuesday October 11, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#fitting-and-interpreting-geographic-regressions"><i class="fa fa-check"></i>Fitting and interpreting geographic regressions</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#mapping-incidence-and-risk-with-spatial-regression-models"><i class="fa fa-check"></i>Mapping incidence and risk with spatial regression models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html"><i class="fa fa-check"></i>Tuesday October 18, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#spatial-data-as-point-patterns"><i class="fa fa-check"></i>Spatial data as point patterns</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#working-with-point-pattern-objects-using-functions-from-the-spatstat-package"><i class="fa fa-check"></i>Working with point pattern objects using functions from the {spatstat} package</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#quantifying-event-intensity"><i class="fa fa-check"></i>Quantifying event intensity</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html"><i class="fa fa-check"></i>Thursday October 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#creating-ppp-and-owin-objects-from-simple-feature-data-frames"><i class="fa fa-check"></i>Creating <code>ppp</code> and <code>owin</code> objects from simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#estimating-spatial-intensity-as-a-function-of-distance"><i class="fa fa-check"></i>Estimating spatial intensity as a function of distance</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#intensity-trend-as-a-possible-confounding-factor"><i class="fa fa-check"></i>Intensity trend as a possible confounding factor</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html"><i class="fa fa-check"></i>Tuesday October 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#estimating-the-relative-risk-of-events"><i class="fa fa-check"></i>Estimating the relative risk of events</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#estimating-second-moment-properties-of-spatial-events"><i class="fa fa-check"></i>Estimating second-moment properties of spatial events</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html"><i class="fa fa-check"></i>Thursday October 27, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#examples-of-spatially-clustered-events"><i class="fa fa-check"></i>Examples of spatially clustered events</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#determining-the-statistical-significance-of-event-clustering"><i class="fa fa-check"></i>Determining the statistical significance of event clustering</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#estimating-event-clustering-in-multi-type-event-locations"><i class="fa fa-check"></i>Estimating event clustering in multi-type event locations</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#more-about-the-ripley-k-function"><i class="fa fa-check"></i>More about the Ripley K function</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html"><i class="fa fa-check"></i>Tuesday November 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#inferring-event-interaction-from-distance-functions"><i class="fa fa-check"></i>Inferring event interaction from distance functions</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#removing-duplicate-event-locations-and-defining-the-domain"><i class="fa fa-check"></i>Removing duplicate event locations and defining the domain</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#modeling-point-pattern-data"><i class="fa fa-check"></i>Modeling point pattern data</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#fitting-and-interpreting-an-inhibition-model"><i class="fa fa-check"></i>Fitting and interpreting an inhibition model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html"><i class="fa fa-check"></i>Thursday November 3, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#fitting-and-interpreting-a-cluster-model"><i class="fa fa-check"></i>Fitting and interpreting a cluster model</a></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#assessing-how-well-the-model-fits"><i class="fa fa-check"></i>Assessing how well the model fits</a></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#spatial-logistic-regression"><i class="fa fa-check"></i>Spatial logistic regression</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html"><i class="fa fa-check"></i>Thursday November 10, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html#spatial-data-interpolation"><i class="fa fa-check"></i>Spatial data interpolation</a></li>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html#computing-the-sample-variogram"><i class="fa fa-check"></i>Computing the sample variogram</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html"><i class="fa fa-check"></i>Tuesday November 15, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#fitting-a-variogram-model-to-the-sample-variogram"><i class="fa fa-check"></i>Fitting a variogram model to the sample variogram</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#creating-an-interpolated-surface-with-the-method-of-kriging"><i class="fa fa-check"></i>Creating an interpolated surface with the method of kriging</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html"><i class="fa fa-check"></i>Thursday November 17, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#comparing-interpolation-methods"><i class="fa fa-check"></i>Comparing interpolation methods</a></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#evaluating-the-accuracy-of-the-interpolation"><i class="fa fa-check"></i>Evaluating the accuracy of the interpolation</a></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#block-cross-validation"><i class="fa fa-check"></i>Block cross validation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html"><i class="fa fa-check"></i>Thursday November 29, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html#interpolating-to-areal-units-block-kriging"><i class="fa fa-check"></i>Interpolating to areal units (block kriging)</a></li>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html#simulating-spatial-fields"><i class="fa fa-check"></i>Simulating spatial fields</a></li>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html#interpolating-multiple-variables"><i class="fa fa-check"></i>Interpolating multiple variables</a></li>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html#machine-learning-for-spatial-interpolation"><i class="fa fa-check"></i>Machine learning for spatial interpolation</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GIS5122: Applied Spatial Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="tuesday-september-27-2022" class="section level1 unnumbered hasAnchor">
<h1>Tuesday September 27, 2022<a href="tuesday-september-27-2022.html#tuesday-september-27-2022" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>“You haven’t mastered a tool until you understand when it should not be used.”</strong> – Kelsey Hightower</p>
<p>Today</p>
<ul>
<li>Defining spatial neighborhoods and spatial weights</li>
<li>Computing spatial autocorrelation</li>
<li>Spatial lag and its relation to autocorrelation</li>
</ul>
<div id="defining-spatial-neighborhoods-and-spatial-weights" class="section level2 unnumbered hasAnchor">
<h2>Defining spatial neighborhoods and spatial weights<a href="tuesday-september-27-2022.html#defining-spatial-neighborhoods-and-spatial-weights" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Autocorrelation plays a central role in spatial statistics. It measures the degree to which things tend to cluster. Things include attribute values aggregated to polygons (or raster cells) as well as locations. How autocorrelation gets estimated depends on the geometry of the spatial data.</p>
<p>Things tend to cluster because of:</p>
<ul>
<li><p>Association: whatever causes an attribute to have a certain value in one area causes the same attribute to have a similar value in areas nearby. Crime rates in nearby neighborhoods might tend to cluster due to similar factors.</p></li>
<li><p>Causality: something within a given area directly influences outcomes within nearby areas. Non-infectious diseases (e.g., lung cancer) have similar rates in neighborhoods close to an oil refinery.</p></li>
<li><p>Interaction: the movement of people, goods or information creates relationships between areas. COVID spreads through areas through the movement of people.</p></li>
</ul>
<p>Spatial statistics quantify, and condition on, autocorrelation but they are silent about physical causes. Understanding the reason for autocorrelation in your data is important for inference because the causal mechanism might be confounded by its. The divorce rate is high in southern states, but so is the number of Waffle Houses. Understanding causation requires domain specific knowledge.</p>
<p>When a variable’s values are aggregated (summed or averaged) to regions, autocorrelation is quantified by calculating how similar a value in region <span class="math inline">\(i\)</span> is to the value in region <span class="math inline">\(j\)</span> and weighting this similarity by how ‘close’ region <span class="math inline">\(i\)</span> is to region <span class="math inline">\(j\)</span>. Closer regions are given greater weight.</p>
<p>High similarities with high weight (similar values close together) yield high values of spatial autocorrelation. Low similarities with high weight (dissimilar values close together) yield low values of spatial autocorrelation. Let <span class="math inline">\(\hbox{sim}_{ij}\)</span> denote the similarity between values <span class="math inline">\(Y_i\)</span> and <span class="math inline">\(Y_j\)</span>, and let <span class="math inline">\(w_{ij}\)</span> denote a set of weights describing the ‘distance’ between regions <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span>, for <span class="math inline">\(i\)</span>, <span class="math inline">\(j\)</span> = 1, …, <span class="math inline">\(N\)</span>.</p>
<p>A general spatial autocorrelation index (SAI) is given by <span class="math display">\[
\hbox{SAI} = \frac{\sum_{i,j=1}^N w_{ij}\hbox{sim}_{ij}}{\sum_{i,j=1}^N w_{ij}}
\]</span> which represents the weighted similarity between regions. The set of weights (<span class="math inline">\(w_{ij}\)</span>) is called a spatial weights matrix. The spatial weights matrix defines the neighbors for each region and defines the strength of each association.</p>
<p>For cells in a raster under the rook-contiguity criterion, <span class="math inline">\(w_{ij}\)</span> = 1 if cell <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> share a boundary, and 0 if they don’t share a boundary. In this case <span class="math inline">\(w_{ij}\)</span> = <span class="math inline">\(w_{ji}\)</span>. Also, a cell is not a neighbor of itself so <span class="math inline">\(w_{ii}\)</span> = 0.</p>
<p>Alternatively you can define center locations from a set of polygon regions and let <span class="math inline">\(w_{ij}\)</span> = 1 if the center of region <span class="math inline">\(i\)</span> is near the center of region <span class="math inline">\(j\)</span> and 0 otherwise. Here you need to decide on the number of nearest neighbors.</p>
<p>You can also define neighbors by distance. For example, if <span class="math inline">\(d_{ij}\)</span> is the distance between centers <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span>, you can let <span class="math inline">\(w_{ij}\)</span> = 1 if <span class="math inline">\(d_{ij}\)</span> &lt; <span class="math inline">\(\delta\)</span> and 0 otherwise.</p>
<p>Consider crime data at the tract level in the city of Columbus, Ohio. The tract polygons are projected with arbitrary spatial coordinates.</p>
<div class="sourceCode" id="cb711"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb711-1"><a href="tuesday-september-27-2022.html#cb711-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="st">&quot;columbus&quot;</span> <span class="sc">%in%</span> <span class="fu">list.files</span>(<span class="st">&quot;data&quot;</span>)) {</span>
<span id="cb711-2"><a href="tuesday-september-27-2022.html#cb711-2" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(<span class="at">url =</span> <span class="st">&quot;http://myweb.fsu.edu/jelsner/temp/data/columbus.zip&quot;</span>,</span>
<span id="cb711-3"><a href="tuesday-september-27-2022.html#cb711-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">destfile =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;columbus.zip&quot;</span>))</span>
<span id="cb711-4"><a href="tuesday-september-27-2022.html#cb711-4" aria-hidden="true" tabindex="-1"></a><span class="fu">unzip</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;columbus.zip&quot;</span>),</span>
<span id="cb711-5"><a href="tuesday-september-27-2022.html#cb711-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">exdir =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>))</span>
<span id="cb711-6"><a href="tuesday-september-27-2022.html#cb711-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb711-7"><a href="tuesday-september-27-2022.html#cb711-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb711-8"><a href="tuesday-september-27-2022.html#cb711-8" aria-hidden="true" tabindex="-1"></a>( CC.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="at">dsn =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;columbus&quot;</span>),</span>
<span id="cb711-9"><a href="tuesday-september-27-2022.html#cb711-9" aria-hidden="true" tabindex="-1"></a>                       <span class="at">layer =</span> <span class="st">&quot;columbus&quot;</span>) )</span></code></pre></div>
<pre><code>## Reading layer `columbus&#39; from data source 
##   `/Users/jelsner/Desktop/ClassNotes/ASS-2022/data/columbus&#39; 
##   using driver `ESRI Shapefile&#39;
## Simple feature collection with 49 features and 20 fields
## Geometry type: POLYGON
## Dimension:     XY
## Bounding box:  xmin: 5.874907 ymin: 10.78863 xmax: 11.28742 ymax: 14.74245
## CRS:           NA</code></pre>
<pre><code>## Simple feature collection with 49 features and 20 fields
## Geometry type: POLYGON
## Dimension:     XY
## Bounding box:  xmin: 5.874907 ymin: 10.78863 xmax: 11.28742 ymax: 14.74245
## CRS:           NA
## First 10 features:
##        AREA PERIMETER COLUMBUS_ COLUMBUS_I POLYID NEIG  HOVAL    INC     CRIME
## 1  0.309441  2.440629         2          5      1    5 80.467 19.531 15.725980
## 2  0.259329  2.236939         3          1      2    1 44.567 21.232 18.801754
## 3  0.192468  2.187547         4          6      3    6 26.350 15.956 30.626781
## 4  0.083841  1.427635         5          2      4    2 33.200  4.477 32.387760
## 5  0.488888  2.997133         6          7      5    7 23.225 11.252 50.731510
## 6  0.283079  2.335634         7          8      6    8 28.750 16.029 26.066658
## 7  0.257084  2.554577         8          4      7    4 75.000  8.438  0.178269
## 8  0.204954  2.139524         9          3      8    3 37.125 11.337 38.425858
## 9  0.500755  3.169707        10         18      9   18 52.600 17.586 30.515917
## 10 0.246689  2.087235        11         10     10   10 96.400 13.598 34.000835
##        OPEN    PLUMB DISCBD     X     Y NSA NSB EW CP THOUS NEIGNO
## 1  2.850747 0.217155   5.03 38.80 44.07   1   1  1  0  1000   1005
## 2  5.296720 0.320581   4.27 35.62 42.38   1   1  0  0  1000   1001
## 3  4.534649 0.374404   3.89 39.82 41.18   1   1  1  0  1000   1006
## 4  0.394427 1.186944   3.70 36.50 40.52   1   1  0  0  1000   1002
## 5  0.405664 0.624596   2.83 40.01 38.00   1   1  1  0  1000   1007
## 6  0.563075 0.254130   3.78 43.75 39.28   1   1  1  0  1000   1008
## 7  0.000000 2.402402   2.74 33.36 38.41   1   1  0  0  1000   1004
## 8  3.483478 2.739726   2.89 36.71 38.71   1   1  0  0  1000   1003
## 9  0.527488 0.890736   3.17 43.44 35.92   1   1  1  0  1000   1018
## 10 1.548348 0.557724   4.33 47.61 36.42   1   1  1  0  1000   1010
##                          geometry
## 1  POLYGON ((8.624129 14.23698...
## 2  POLYGON ((8.25279 14.23694,...
## 3  POLYGON ((8.653305 14.00809...
## 4  POLYGON ((8.459499 13.82035...
## 5  POLYGON ((8.685274 13.63952...
## 6  POLYGON ((9.401384 13.5504,...
## 7  POLYGON ((8.037741 13.60752...
## 8  POLYGON ((8.247527 13.58651...
## 9  POLYGON ((9.333297 13.27242...
## 10 POLYGON ((10.08251 13.03377...</code></pre>
<p>The simple feature data frame contains housing values (<code>HOVAL</code>), income values (<code>INC</code>) and (<code>CRIME</code>) in census tracts across the city. Crime (<code>CRIME</code>) is residential burglaries and vehicle thefts per 1000 households. Income (<code>INC</code>) and housing values (<code>HOVAL</code>) are annual values with units of 1000 dollars.</p>
<p>Create a choropleth map of the crime rates (<code>CRIME</code>).</p>
<div class="sourceCode" id="cb714"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb714-1"><a href="tuesday-september-27-2022.html#cb714-1" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_shape</span>(CC.sf) <span class="sc">+</span></span>
<span id="cb714-2"><a href="tuesday-september-27-2022.html#cb714-2" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">&quot;CRIME&quot;</span>,</span>
<span id="cb714-3"><a href="tuesday-september-27-2022.html#cb714-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">title =</span> <span class="st">&quot;Burglary &amp; Vehicle Thefts</span><span class="sc">\n</span><span class="st">/1000 Households&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: Currect projection of shape CC.sf unknown. Long-lat (WGS84) is assumed.</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-306-1.png" width="672" /></p>
<p>Note that the variable name CRIME must be in quotes.</p>
<p>Alternatively we create a choropleth map of the crime rates using <code>geom_sf()</code>. Here the variable name CRIME is without quotes.</p>
<div class="sourceCode" id="cb716"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb716-1"><a href="tuesday-september-27-2022.html#cb716-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb716-2"><a href="tuesday-september-27-2022.html#cb716-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb716-3"><a href="tuesday-september-27-2022.html#cb716-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> CC.sf) <span class="sc">+</span> </span>
<span id="cb716-4"><a href="tuesday-september-27-2022.html#cb716-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">fill =</span> CRIME)) <span class="sc">+</span></span>
<span id="cb716-5"><a href="tuesday-september-27-2022.html#cb716-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">&quot;Burglary &amp; Vehicle Thefts</span><span class="sc">\n</span><span class="st">/1000 Households&quot;</span>) <span class="sc">+</span></span>
<span id="cb716-6"><a href="tuesday-september-27-2022.html#cb716-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-307-1.png" width="672" /></p>
<p>High crime areas tend to be clustered.</p>
<p>Autocorrelation quantifies the amount of clustering. To compute the autocorrelation you first need to define the neighbors for each polygon.</p>
<p>You create a list of neighbors using the spdep::<code>poly2nb()</code> function from the {spdep} package. The ‘nb’ in the function names stands for neighbor list object. The function builds the list from geometries based on contiguity. Neighbors must share at least one geographic location. By default the contiguity is defined as having at least one location in common. This is changed by using the argument <code>queen = FALSE</code>. Functions in the {spdep} package support S3 and S4 spatial data objects.</p>
<div class="sourceCode" id="cb717"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb717-1"><a href="tuesday-september-27-2022.html#cb717-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(spdep)) <span class="fu">install.packages</span>(<span class="st">&quot;spdep&quot;</span>, <span class="at">repos =</span> <span class="st">&quot;http://cran.us.r-project.org&quot;</span>)</span></code></pre></div>
<pre><code>## Loading required package: spdep</code></pre>
<div class="sourceCode" id="cb719"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb719-1"><a href="tuesday-september-27-2022.html#cb719-1" aria-hidden="true" tabindex="-1"></a>( nbs <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">poly2nb</span>(CC.sf) )</span></code></pre></div>
<pre><code>## Neighbour list object:
## Number of regions: 49 
## Number of nonzero links: 236 
## Percentage nonzero weights: 9.829238 
## Average number of links: 4.816327</code></pre>
<p>Note that this only works for spatial data frames.</p>
<p>The output tells you there are 49 tracts (polygons). Each tract is bordered by at least one other tract. The average number of neighbors is 4.8. The total number of neighbors over all tracts is 236. This represents 9.8% of all possible connections (if every tract is a neighbor of itself and every other tract 49 * 49).</p>
<p>A graph of the neighbor links is obtained with the <code>plot()</code> method. The arguments include the neighbor list object (<code>nbs</code>) and the location of the polygon centers, which are extracted from the simple feature data frame using the sf::<code>st_centroid()</code>.</p>
<div class="sourceCode" id="cb721"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb721-1"><a href="tuesday-september-27-2022.html#cb721-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(CC.sf<span class="sc">$</span>geometry)</span>
<span id="cb721-2"><a href="tuesday-september-27-2022.html#cb721-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(nbs, </span>
<span id="cb721-3"><a href="tuesday-september-27-2022.html#cb721-3" aria-hidden="true" tabindex="-1"></a>     sf<span class="sc">::</span><span class="fu">st_centroid</span>(CC.sf<span class="sc">$</span>geometry),</span>
<span id="cb721-4"><a href="tuesday-september-27-2022.html#cb721-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">add =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-309-1.png" width="672" /></p>
<p>The graph is a network showing the contiguity pattern (adjacency neighbor structure). Tracts close to the center of the city have more neighboring tracts and thus more links in the network.</p>
<p>The number of links per tract (node)–link distribution–is obtained with the <code>summary()</code> method.</p>
<div class="sourceCode" id="cb722"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb722-1"><a href="tuesday-september-27-2022.html#cb722-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nbs)</span></code></pre></div>
<pre><code>## Neighbour list object:
## Number of regions: 49 
## Number of nonzero links: 236 
## Percentage nonzero weights: 9.829238 
## Average number of links: 4.816327 
## Link number distribution:
## 
##  2  3  4  5  6  7  8  9 10 
##  5  9 12  5  9  3  4  1  1 
## 5 least connected regions:
## 1 6 42 46 47 with 2 links
## 1 most connected region:
## 20 with 10 links</code></pre>
<p>The list of neighboring tracts for the first two tracts.</p>
<div class="sourceCode" id="cb724"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb724-1"><a href="tuesday-september-27-2022.html#cb724-1" aria-hidden="true" tabindex="-1"></a>nbs[[<span class="dv">1</span>]]</span></code></pre></div>
<pre><code>## [1] 2 3</code></pre>
<div class="sourceCode" id="cb726"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb726-1"><a href="tuesday-september-27-2022.html#cb726-1" aria-hidden="true" tabindex="-1"></a>nbs[[<span class="dv">2</span>]]</span></code></pre></div>
<pre><code>## [1] 1 3 4</code></pre>
<p>The first tract has two neighbors that include tracts 2 and 3. The neighbor numbers are stored as an integer vector within the <code>nb</code> object. Tract 2 has three neighbors that include tracts 1, 3, and 4. Tract 5 has 8 neighbors and so on. The function spdep::<code>card()</code> tallies the number of neighbors by tract.</p>
<div class="sourceCode" id="cb728"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb728-1"><a href="tuesday-september-27-2022.html#cb728-1" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">card</span>(nbs)</span></code></pre></div>
<pre><code>##  [1]  2  3  4  4  8  2  4  6  8  4  5  6  4  6  6  8  3  4  3 10  3  6  3  7  8
## [26]  6  4  9  7  5  3  4  4  4  7  5  6  6  3  5  3  2  6  5  4  2  2  4  3</code></pre>
<p>Tract 5 has 8 neighbors and so on.</p>
<p>The next step is to include weights to the neighbor list object indicate how close each neighbor is. The function spdep::<code>nb2listw()</code> turns the neighbor list object into a spatial weights object. By default the weighting scheme gives each link the same weight equal to the multiplicative inverse of the number of neighbors.</p>
<div class="sourceCode" id="cb730"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb730-1"><a href="tuesday-september-27-2022.html#cb730-1" aria-hidden="true" tabindex="-1"></a>wts <span class="ot">&lt;-</span> nbs <span class="sc">|&gt;</span></span>
<span id="cb730-2"><a href="tuesday-september-27-2022.html#cb730-2" aria-hidden="true" tabindex="-1"></a>  spdep<span class="sc">::</span><span class="fu">nb2listw</span>()</span>
<span id="cb730-3"><a href="tuesday-september-27-2022.html#cb730-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb730-4"><a href="tuesday-september-27-2022.html#cb730-4" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(wts)</span></code></pre></div>
<pre><code>## [1] &quot;listw&quot; &quot;nb&quot;</code></pre>
<p>This <code>wts</code> object is a list with two elements. The first element (<code>listw</code>) is the weights matrix and the second element (<code>nb</code>) is the neighbor list object.</p>
<div class="sourceCode" id="cb732"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb732-1"><a href="tuesday-september-27-2022.html#cb732-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wts)</span></code></pre></div>
<pre><code>## Characteristics of weights list object:
## Neighbour list object:
## Number of regions: 49 
## Number of nonzero links: 236 
## Percentage nonzero weights: 9.829238 
## Average number of links: 4.816327 
## Link number distribution:
## 
##  2  3  4  5  6  7  8  9 10 
##  5  9 12  5  9  3  4  1  1 
## 5 least connected regions:
## 1 6 42 46 47 with 2 links
## 1 most connected region:
## 20 with 10 links
## 
## Weights style: W 
## Weights constants summary:
##    n   nn S0       S1       S2
## W 49 2401 49 22.75119 203.7091</code></pre>
<p>The network statistics are given along with information about the weights. The default weighting scheme assigns a weight to each neighbor equal to the inverse of the number of neighbors (<code>style = "W"</code>). For a tract with 5 neighbors each neighbor gets a weight of 1/5. The sum over all weights (<code>S0</code>) is the number of tracts.</p>
<p>To see the weights for the first two tracts type</p>
<div class="sourceCode" id="cb734"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb734-1"><a href="tuesday-september-27-2022.html#cb734-1" aria-hidden="true" tabindex="-1"></a>wts<span class="sc">$</span>weights[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span></code></pre></div>
<pre><code>## [[1]]
## [1] 0.5 0.5
## 
## [[2]]
## [1] 0.3333333 0.3333333 0.3333333</code></pre>
<p>The object <code>weights</code> represents the weights matrix as a list. The full matrix has dimensions 49 x 49 but most of the entries are zero.</p>
<div class="sourceCode" id="cb736"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb736-1"><a href="tuesday-september-27-2022.html#cb736-1" aria-hidden="true" tabindex="-1"></a>nbs <span class="sc">|&gt;</span></span>
<span id="cb736-2"><a href="tuesday-september-27-2022.html#cb736-2" aria-hidden="true" tabindex="-1"></a>  spdep<span class="sc">::</span><span class="fu">nb2mat</span>() <span class="sc">|&gt;</span></span>
<span id="cb736-3"><a href="tuesday-september-27-2022.html#cb736-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>##        [,1] [,2]      [,3]      [,4] [,5]  [,6] [,7]  [,8]  [,9] [,10] [,11]
## 1 0.0000000 0.50 0.5000000 0.0000000 0.00 0.000    0 0.000 0.000     0 0.000
## 2 0.3333333 0.00 0.3333333 0.3333333 0.00 0.000    0 0.000 0.000     0 0.000
## 3 0.2500000 0.25 0.0000000 0.2500000 0.25 0.000    0 0.000 0.000     0 0.000
## 4 0.0000000 0.25 0.2500000 0.0000000 0.25 0.000    0 0.250 0.000     0 0.000
## 5 0.0000000 0.00 0.1250000 0.1250000 0.00 0.125    0 0.125 0.125     0 0.125
## 6 0.0000000 0.00 0.0000000 0.0000000 0.50 0.000    0 0.000 0.500     0 0.000
##   [,12] [,13] [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24]
## 1     0     0     0 0.000 0.000     0     0     0     0     0     0     0     0
## 2     0     0     0 0.000 0.000     0     0     0     0     0     0     0     0
## 3     0     0     0 0.000 0.000     0     0     0     0     0     0     0     0
## 4     0     0     0 0.000 0.000     0     0     0     0     0     0     0     0
## 5     0     0     0 0.125 0.125     0     0     0     0     0     0     0     0
## 6     0     0     0 0.000 0.000     0     0     0     0     0     0     0     0
##   [,25] [,26] [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37]
## 1     0     0     0     0     0     0     0     0     0     0     0     0     0
## 2     0     0     0     0     0     0     0     0     0     0     0     0     0
## 3     0     0     0     0     0     0     0     0     0     0     0     0     0
## 4     0     0     0     0     0     0     0     0     0     0     0     0     0
## 5     0     0     0     0     0     0     0     0     0     0     0     0     0
## 6     0     0     0     0     0     0     0     0     0     0     0     0     0
##   [,38] [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49]
## 1     0     0     0     0     0     0     0     0     0     0     0     0
## 2     0     0     0     0     0     0     0     0     0     0     0     0
## 3     0     0     0     0     0     0     0     0     0     0     0     0
## 4     0     0     0     0     0     0     0     0     0     0     0     0
## 5     0     0     0     0     0     0     0     0     0     0     0     0
## 6     0     0     0     0     0     0     0     0     0     0     0     0</code></pre>
<p>To see the neighbors of the first two tracts type</p>
<div class="sourceCode" id="cb738"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb738-1"><a href="tuesday-september-27-2022.html#cb738-1" aria-hidden="true" tabindex="-1"></a>wts<span class="sc">$</span>neighbours[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span></code></pre></div>
<pre><code>## [[1]]
## [1] 2 3
## 
## [[2]]
## [1] 1 3 4</code></pre>
<p>Tract 1 has two neighbors (tract 2 &amp; 3) so each are given a weight of 1/2. Tract 2 has three neighbors (tract 1, 3, &amp; 4) so each are given a weight of 1/3.</p>
<p>With the weights matrix saved as an object you are ready to compute a metric of spatial autocorrelation.</p>
<p>Caution: Neighbors defined by contiguity can leave some areas without any. Islands for example. By default the <code>spdep::nb2listw()</code> function assumes each area has at least one neighbor. If this is not the case you need to specify how areas without neighbors are handled using the argument <code>zero.policy = TRUE</code>. This permits the weights list to be formed with zero-length weights vectors.</p>
<p>For example, consider the districts in the country of Scotland.</p>
<div class="sourceCode" id="cb740"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb740-1"><a href="tuesday-september-27-2022.html#cb740-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="st">&quot;scotlip&quot;</span> <span class="sc">%in%</span> <span class="fu">list.files</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>))) {</span>
<span id="cb740-2"><a href="tuesday-september-27-2022.html#cb740-2" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(<span class="st">&quot;http://myweb.fsu.edu/jelsner/temp/data/scotlip.zip&quot;</span>,</span>
<span id="cb740-3"><a href="tuesday-september-27-2022.html#cb740-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">destfile =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;scotlip.zip&quot;</span>))</span>
<span id="cb740-4"><a href="tuesday-september-27-2022.html#cb740-4" aria-hidden="true" tabindex="-1"></a><span class="fu">unzip</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;scotlip.zip&quot;</span>),</span>
<span id="cb740-5"><a href="tuesday-september-27-2022.html#cb740-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">exdir =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>))</span>
<span id="cb740-6"><a href="tuesday-september-27-2022.html#cb740-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb740-7"><a href="tuesday-september-27-2022.html#cb740-7" aria-hidden="true" tabindex="-1"></a>SL.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="at">dsn =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;scotlip&quot;</span>), </span>
<span id="cb740-8"><a href="tuesday-september-27-2022.html#cb740-8" aria-hidden="true" tabindex="-1"></a>                     <span class="at">layer =</span> <span class="st">&quot;scotlip&quot;</span>)</span></code></pre></div>
<pre><code>## Reading layer `scotlip&#39; from data source 
##   `/Users/jelsner/Desktop/ClassNotes/ASS-2022/data/scotlip&#39; using driver `ESRI Shapefile&#39;
## Simple feature collection with 56 features and 11 fields
## Geometry type: POLYGON
## Dimension:     XY
## Bounding box:  xmin: 95631 ymin: 530297 xmax: 454570 ymax: 1203008
## CRS:           NA</code></pre>
<div class="sourceCode" id="cb742"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb742-1"><a href="tuesday-september-27-2022.html#cb742-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(SL.sf<span class="sc">$</span>geometry)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-318-1.png" width="672" /></p>
<p>Three of the districts are islands. These districts have no bordering districts.</p>
<p>Create a list of neighbors.</p>
<div class="sourceCode" id="cb743"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb743-1"><a href="tuesday-september-27-2022.html#cb743-1" aria-hidden="true" tabindex="-1"></a>( nbs2 <span class="ot">&lt;-</span> SL.sf <span class="sc">|&gt;</span></span>
<span id="cb743-2"><a href="tuesday-september-27-2022.html#cb743-2" aria-hidden="true" tabindex="-1"></a>    spdep<span class="sc">::</span><span class="fu">poly2nb</span>() )</span></code></pre></div>
<pre><code>## Neighbour list object:
## Number of regions: 56 
## Number of nonzero links: 234 
## Percentage nonzero weights: 7.461735 
## Average number of links: 4.178571 
## 3 regions with no links:
## 6 8 11</code></pre>
<p>Three regions with no links.</p>
<p>Use the <code>spdep::nb2listw()</code> function with the argument <code>zero.policy = TRUE</code>. Otherwise we get an error saying the empty neighbor sets are found.</p>
<div class="sourceCode" id="cb745"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb745-1"><a href="tuesday-september-27-2022.html#cb745-1" aria-hidden="true" tabindex="-1"></a>wts2 <span class="ot">&lt;-</span> nbs2 <span class="sc">|&gt;</span></span>
<span id="cb745-2"><a href="tuesday-september-27-2022.html#cb745-2" aria-hidden="true" tabindex="-1"></a>  spdep<span class="sc">::</span><span class="fu">nb2listw</span>(<span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span>
<span id="cb745-3"><a href="tuesday-september-27-2022.html#cb745-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(wts2<span class="sc">$</span>weights)</span></code></pre></div>
<pre><code>## [[1]]
## [1] 0.3333333 0.3333333 0.3333333
## 
## [[2]]
## [1] 0.5 0.5
## 
## [[3]]
## [1] 1
## 
## [[4]]
## [1] 0.3333333 0.3333333 0.3333333
## 
## [[5]]
## [1] 0.3333333 0.3333333 0.3333333
## 
## [[6]]
## NULL</code></pre>
</div>
<div id="computing-autocorrelation" class="section level2 unnumbered hasAnchor">
<h2>Computing autocorrelation<a href="tuesday-september-27-2022.html#computing-autocorrelation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A common autocorrelation statistic is Moran’s I. Moran’s I follows the basic form of autocorrelation indexes where the similarity between regions <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> is proportional to the product of the deviations from the mean <span class="math display">\[
\hbox{sim}_{ij} \propto (Y_i - \bar Y) (Y_j - \bar Y)
\]</span> where <span class="math inline">\(i\)</span> indexes the region and <span class="math inline">\(j\)</span> indexes the neighbors of <span class="math inline">\(i\)</span>. The value of <span class="math inline">\(\hbox{sim}_{ij}\)</span> is large when the <span class="math inline">\(Y\)</span> values in the product are on the same side of their respective means (both above or below) and small when they are on opposite sides of their respective means (one above and one below or vice versa).</p>
<p>The formula for I is <span class="math display">\[
\hbox{I} = \frac{N} {W} \frac {\sum_{i,j} w_{ij}(Y_i-\bar Y) (Y_j-\bar Y)} {\sum_{i} (Y_i-\bar Y)^2}
\]</span> where <span class="math inline">\(N\)</span> is the number regions, <span class="math inline">\(w_{ij}\)</span> is the matrix of weights, and <span class="math inline">\(W\)</span> is the sum over all weights.</p>
<p>Consider the following grid of cells containing attribute values.</p>
<div class="sourceCode" id="cb747"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb747-1"><a href="tuesday-september-27-2022.html#cb747-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(spatstat)) <span class="fu">install.packages</span>(<span class="at">pkgs =</span> <span class="st">&quot;spatstat&quot;</span>, <span class="at">repos =</span> <span class="st">&quot;http://cran.us.r-project.org&quot;</span>)</span></code></pre></div>
<pre><code>## Loading required package: spatstat</code></pre>
<pre><code>## Loading required package: spatstat.data</code></pre>
<pre><code>## Loading required package: spatstat.geom</code></pre>
<pre><code>## spatstat.geom 2.4-0</code></pre>
<pre><code>## 
## Attaching package: &#39;spatstat.geom&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:grid&#39;:
## 
##     as.mask</code></pre>
<pre><code>## The following objects are masked from &#39;package:raster&#39;:
## 
##     area, rotate, shift</code></pre>
<pre><code>## The following object is masked from &#39;package:patchwork&#39;:
## 
##     area</code></pre>
<pre><code>## Loading required package: spatstat.random</code></pre>
<pre><code>## spatstat.random 2.2-0</code></pre>
<pre><code>## Loading required package: spatstat.core</code></pre>
<pre><code>## Loading required package: nlme</code></pre>
<pre><code>## 
## Attaching package: &#39;nlme&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:raster&#39;:
## 
##     getData</code></pre>
<pre><code>## Loading required package: rpart</code></pre>
<pre><code>## spatstat.core 2.4-4</code></pre>
<pre><code>## Loading required package: spatstat.linnet</code></pre>
<pre><code>## spatstat.linnet 2.3-2</code></pre>
<pre><code>## 
## spatstat 2.3-4       (nickname: &#39;Watch this space&#39;) 
## For an introduction to spatstat, type &#39;beginner&#39;</code></pre>
<div class="sourceCode" id="cb767"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb767-1"><a href="tuesday-september-27-2022.html#cb767-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(spatstat))</span>
<span id="cb767-2"><a href="tuesday-september-27-2022.html#cb767-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb767-3"><a href="tuesday-september-27-2022.html#cb767-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">6750</span>)</span>
<span id="cb767-4"><a href="tuesday-september-27-2022.html#cb767-4" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> <span class="fu">ppp</span>(<span class="fu">runif</span>(<span class="dv">200</span>, <span class="dv">0</span>, <span class="dv">1</span>), </span>
<span id="cb767-5"><a href="tuesday-september-27-2022.html#cb767-5" aria-hidden="true" tabindex="-1"></a>         <span class="fu">runif</span>(<span class="dv">200</span>, <span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb767-6"><a href="tuesday-september-27-2022.html#cb767-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">quadratcount</span>(Y), <span class="at">main =</span> <span class="st">&quot;&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-321-1.png" width="672" /></p>
<p>The formula for results in one value of I representing the magnitude of the autocorrelation (amount of clustering) over the entire area.</p>
<p>First consider a single cell in the area (<span class="math inline">\(N\)</span> = 1). Start with the middle cell (row 3, column 3). Let <span class="math inline">\(i\)</span> = 3 in the above formula and let <span class="math inline">\(j\)</span> index the cells touching the center cell in reading order starting with cell (2, 2), then cell (2, 3), etc.</p>
<p>Assume each neighbor is given a weight of 1/8 so <span class="math inline">\(W = \sum_{j=1}^8 w_j = 1\)</span>. Then the value of I for the single center cell is I_{3, 3} = (6 - mean(y)) * ((8 - mean(y)) + (3 - mean(y)) + (9 - mean(y)) + (12 - mean(y)) + (10 - mean(y)) + (10 - mean(y)) + (9 - mean(y))) / (6 - mean(y))^2)</p>
<div class="sourceCode" id="cb768"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb768-1"><a href="tuesday-september-27-2022.html#cb768-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">10</span>, <span class="dv">7</span>, <span class="dv">12</span>, <span class="dv">5</span>, <span class="dv">11</span>, <span class="dv">8</span>, <span class="dv">3</span>, <span class="dv">9</span>, <span class="dv">12</span>, </span>
<span id="cb768-2"><a href="tuesday-september-27-2022.html#cb768-2" aria-hidden="true" tabindex="-1"></a>      <span class="dv">6</span>, <span class="dv">12</span>, <span class="dv">6</span>, <span class="dv">10</span>, <span class="dv">3</span>, <span class="dv">8</span>, <span class="dv">10</span>, <span class="dv">10</span>, <span class="dv">9</span>, <span class="dv">7</span>, </span>
<span id="cb768-3"><a href="tuesday-september-27-2022.html#cb768-3" aria-hidden="true" tabindex="-1"></a>      <span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">8</span>, <span class="dv">5</span>, <span class="dv">11</span>)</span>
<span id="cb768-4"><a href="tuesday-september-27-2022.html#cb768-4" aria-hidden="true" tabindex="-1"></a>( yb <span class="ot">&lt;-</span> <span class="fu">mean</span>(y) )</span></code></pre></div>
<pre><code>## [1] 8</code></pre>
<div class="sourceCode" id="cb770"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb770-1"><a href="tuesday-september-27-2022.html#cb770-1" aria-hidden="true" tabindex="-1"></a>Inum_i <span class="ot">&lt;-</span> (<span class="dv">6</span> <span class="sc">-</span> yb) <span class="sc">*</span> </span>
<span id="cb770-2"><a href="tuesday-september-27-2022.html#cb770-2" aria-hidden="true" tabindex="-1"></a>                 ((<span class="dv">8</span> <span class="sc">-</span> yb) <span class="sc">+</span> (<span class="dv">3</span> <span class="sc">-</span> yb) <span class="sc">+</span> (<span class="dv">9</span> <span class="sc">-</span> yb) <span class="sc">+</span> </span>
<span id="cb770-3"><a href="tuesday-september-27-2022.html#cb770-3" aria-hidden="true" tabindex="-1"></a>                  (<span class="dv">12</span> <span class="sc">-</span> yb) <span class="sc">+</span> (<span class="dv">10</span> <span class="sc">-</span> yb) <span class="sc">+</span> (<span class="dv">10</span> <span class="sc">-</span> yb) <span class="sc">+</span> </span>
<span id="cb770-4"><a href="tuesday-september-27-2022.html#cb770-4" aria-hidden="true" tabindex="-1"></a>                  (<span class="dv">10</span> <span class="sc">-</span> yb) <span class="sc">+</span> (<span class="dv">9</span> <span class="sc">-</span> yb))</span>
<span id="cb770-5"><a href="tuesday-september-27-2022.html#cb770-5" aria-hidden="true" tabindex="-1"></a>Iden_i <span class="ot">&lt;-</span> (<span class="dv">6</span> <span class="sc">-</span> yb)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb770-6"><a href="tuesday-september-27-2022.html#cb770-6" aria-hidden="true" tabindex="-1"></a>Inum_i<span class="sc">/</span>Iden_i</span></code></pre></div>
<pre><code>## [1] -3.5</code></pre>
<p>The I value of -3.5 indicates that the center cell, which has a value below the average over all 25 cells, is mostly surrounded by cells having values above the average.</p>
<p>Repeat this calculation for every cell and then take the sum.</p>
<p>This is what the function <code>spdep::moran()</code> from the {spdep} package does. The first argument is the vector containing the values for which you are interested in determining the magnitude of the spatial autocorrelation and the second argument is the <code>listw</code> object.</p>
<p>Further, you need to specify the number of regions and the sum of the weights <code>S0</code>. The latter is obtained from the <code>spdep::Szero()</code> function applied to the <code>listw</code> object.</p>
<p>Returning to the Columbus crime data here let <code>m</code> be the number of census tracts and <code>s</code> be the sum of the weights. You then apply the <code>spdep::moran()</code> function on the variable <code>CRIME</code>.</p>
<div class="sourceCode" id="cb772"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb772-1"><a href="tuesday-september-27-2022.html#cb772-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">length</span>(CC.sf<span class="sc">$</span>CRIME)</span>
<span id="cb772-2"><a href="tuesday-september-27-2022.html#cb772-2" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">Szero</span>(wts)</span>
<span id="cb772-3"><a href="tuesday-september-27-2022.html#cb772-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb772-4"><a href="tuesday-september-27-2022.html#cb772-4" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">moran</span>(CC.sf<span class="sc">$</span>CRIME, </span>
<span id="cb772-5"><a href="tuesday-september-27-2022.html#cb772-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">listw =</span> wts, </span>
<span id="cb772-6"><a href="tuesday-september-27-2022.html#cb772-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">n =</span> m, </span>
<span id="cb772-7"><a href="tuesday-september-27-2022.html#cb772-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">S0 =</span> s)</span></code></pre></div>
<pre><code>## $I
## [1] 0.5001886
## 
## $K
## [1] 2.225946</code></pre>
<p>The function returns the Moran’s I statistic and the kurtosis (K) of the distribution of crime values. Moran’s I ranges from -1 to +1.</p>
<p>The value of .5 for the crime rates indicates a high level of spatial autocorrelation. This is expected based on the clustering of crime in the central city.</p>
<p>Positive values of Moran’s I indicate clustering and negative values indicate inhibition. Inhibition is a process leading to nearby values having attribute values that are opposite in magnitude as those at each location (like a checkerboard pattern)</p>
<p>Kurtosis is a statistic that indicates how peaked the distribution of the attribute values is. A normal distribution has a kurtosis of 3. If the kurtosis is too large (or small) relative to a normal distribution then any statistical inference we make with Moran’s I will be suspect.</p>
<p><a href="https://en.wikipedia.org/wiki/Moran%27s_I">Wikipedia Moran’s I</a></p>
<p>Another statistic that indicates the amount of spatial autocorrelation is Geary’s C. The equation is
<span class="math display">\[
\hbox{C} = \frac{(N-1) \sum_{i,j} w_{ij} (Y_i-Y_j)^2}{2 W \sum_{i}(Y_i-\bar Y)^2}
\]</span>
where <span class="math inline">\(W\)</span> is the sum over all weights (<span class="math inline">\(w_{ij}\)</span>) and <span class="math inline">\(N\)</span> is the number of areas.</p>
<p>The syntax of the <code>spdep::geary()</code> function is similar that of <code>spdep::moran()</code> except you also specify <code>n1</code> to be one minus the number of areas.</p>
<div class="sourceCode" id="cb774"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb774-1"><a href="tuesday-september-27-2022.html#cb774-1" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">geary</span>(CC.sf<span class="sc">$</span>CRIME, </span>
<span id="cb774-2"><a href="tuesday-september-27-2022.html#cb774-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">listw =</span> wts,</span>
<span id="cb774-3"><a href="tuesday-september-27-2022.html#cb774-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">n =</span> m, </span>
<span id="cb774-4"><a href="tuesday-september-27-2022.html#cb774-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">S0 =</span> s, </span>
<span id="cb774-5"><a href="tuesday-september-27-2022.html#cb774-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">n1 =</span> m <span class="sc">-</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## $C
## [1] 0.5405282
## 
## $K
## [1] 2.225946</code></pre>
<p>Values for Geary’s C range from 0 to 2 with 1 indicating no autocorrelation. Values less than 1 indicate positive autocorrelation. Both I and C are global measures of autocorrelation, but C is more sensitive to local variations in autocorrelation.</p>
<p>Rule of thumb: If the interpretation of Geary’s C is much different than the interpretation of Moran’s I then consider computing local measures of autocorrelation.</p>
<p><a href="https://en.wikipedia.org/wiki/Geary%27s_C">Wikipedia Geary’s C</a></p>
</div>
<div id="spatial-lag-and-its-relation-to-autocorrelation" class="section level2 unnumbered hasAnchor">
<h2>Spatial lag and its relation to autocorrelation<a href="tuesday-september-27-2022.html#spatial-lag-and-its-relation-to-autocorrelation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The interpretation of Moran’s I is simplified by the fact that the value of Moran’s I is the slope coefficient from a regression of the weighted average of the neighborhood values onto the observed values.</p>
<p>The weighted average of neighborhood values is called the spatial lag.</p>
<p>Let <code>crime</code> be the set of crime values in each region as a data vector. You create a spatial lag variable using the <code>spdep::lag.listw()</code> function. The first argument is the <code>listw</code> object and the second is the vector of crime values.</p>
<div class="sourceCode" id="cb776"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb776-1"><a href="tuesday-september-27-2022.html#cb776-1" aria-hidden="true" tabindex="-1"></a>crime <span class="ot">&lt;-</span> CC.sf<span class="sc">$</span>CRIME</span>
<span id="cb776-2"><a href="tuesday-september-27-2022.html#cb776-2" aria-hidden="true" tabindex="-1"></a>Wcrime <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">lag.listw</span>(wts, </span>
<span id="cb776-3"><a href="tuesday-september-27-2022.html#cb776-3" aria-hidden="true" tabindex="-1"></a>                           crime)</span></code></pre></div>
<p>For each value in the vector <code>crime</code> there is a corresponding value in the vector <code>Wcrime</code> representing the average crime over the neighboring regions.</p>
<p>Recall tract 1 had tract 2 and 3 as its only neighbors. So the following should return a <code>TRUE</code>.</p>
<div class="sourceCode" id="cb777"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb777-1"><a href="tuesday-september-27-2022.html#cb777-1" aria-hidden="true" tabindex="-1"></a>Wcrime[<span class="dv">1</span>] <span class="sc">==</span> (crime[<span class="dv">2</span>] <span class="sc">+</span> crime[<span class="dv">3</span>])<span class="sc">/</span><span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>A scatter plot of the neighborhood average crime rates versus the individual polygon crime rates in each shows there is a relationship.</p>
<div class="sourceCode" id="cb779"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb779-1"><a href="tuesday-september-27-2022.html#cb779-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(crime, Wcrime) <span class="sc">|&gt;</span></span>
<span id="cb779-2"><a href="tuesday-september-27-2022.html#cb779-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> crime, <span class="at">y =</span> Wcrime)) <span class="sc">+</span> </span>
<span id="cb779-3"><a href="tuesday-september-27-2022.html#cb779-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb779-4"><a href="tuesday-september-27-2022.html#cb779-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm) <span class="sc">+</span></span>
<span id="cb779-5"><a href="tuesday-september-27-2022.html#cb779-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">70</span>)) <span class="sc">+</span></span>
<span id="cb779-6"><a href="tuesday-september-27-2022.html#cb779-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">70</span>)) <span class="sc">+</span></span>
<span id="cb779-7"><a href="tuesday-september-27-2022.html#cb779-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Crime&quot;</span>) <span class="sc">+</span> </span>
<span id="cb779-8"><a href="tuesday-september-27-2022.html#cb779-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Average Crime in the Neighborhood&quot;</span>) <span class="sc">+</span></span>
<span id="cb779-9"><a href="tuesday-september-27-2022.html#cb779-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-328-1.png" width="672" /></p>
<p>The vertical axis contains the neighborhood average crime rate. The range of neighborhood averages is smaller than the range of individual polygon crime rates.</p>
<p>Tracts with low values of crime tend to be surrounded by tracts with low values of crime on average and tracts with high values of crime tend be surrounded by tracts with high values of crime. The slope is upward (positive).</p>
<p>The magnitude of the slope is the Moran’s I value. To check this use the <code>lm()</code> function from the base set of packages. The function is used to fit linear regression models.</p>
<div class="sourceCode" id="cb781"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb781-1"><a href="tuesday-september-27-2022.html#cb781-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(Wcrime <span class="sc">~</span> crime)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Wcrime ~ crime)
## 
## Coefficients:
## (Intercept)        crime  
##     17.4797       0.5002</code></pre>
<p>The coefficient on the <code>crime</code> variable in the linear regression is .5.</p>
<p>The scatter plot is called a ‘Moran’s scatter plot.’</p>
<p>Let’s consider another data set.</p>
<div class="sourceCode" id="cb783"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb783-1"><a href="tuesday-september-27-2022.html#cb783-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="st">&quot;sids2&quot;</span> <span class="sc">%in%</span> <span class="fu">list.files</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>))) {</span>
<span id="cb783-2"><a href="tuesday-september-27-2022.html#cb783-2" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(<span class="st">&quot;http://myweb.fsu.edu/jelsner/temp/data/sids2.zip&quot;</span>,</span>
<span id="cb783-3"><a href="tuesday-september-27-2022.html#cb783-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">destfile =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;sids2.zip&quot;</span>))</span>
<span id="cb783-4"><a href="tuesday-september-27-2022.html#cb783-4" aria-hidden="true" tabindex="-1"></a><span class="fu">unzip</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;sids2.zip&quot;</span>),</span>
<span id="cb783-5"><a href="tuesday-september-27-2022.html#cb783-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">exdir =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>))</span>
<span id="cb783-6"><a href="tuesday-september-27-2022.html#cb783-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb783-7"><a href="tuesday-september-27-2022.html#cb783-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb783-8"><a href="tuesday-september-27-2022.html#cb783-8" aria-hidden="true" tabindex="-1"></a>SIDS.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="at">dsn =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;sids2&quot;</span>)) <span class="sc">|&gt;</span></span>
<span id="cb783-9"><a href="tuesday-september-27-2022.html#cb783-9" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_set_crs</span>(<span class="dv">4326</span>)</span></code></pre></div>
<pre><code>## Reading layer `sids2&#39; from data source 
##   `/Users/jelsner/Desktop/ClassNotes/ASS-2022/data/sids2&#39; using driver `ESRI Shapefile&#39;
## Simple feature collection with 100 features and 18 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
## CRS:           NA</code></pre>
<div class="sourceCode" id="cb785"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb785-1"><a href="tuesday-september-27-2022.html#cb785-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(SIDS.sf)</span></code></pre></div>
<pre><code>## Simple feature collection with 6 features and 18 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -81.74107 ymin: 36.07282 xmax: -75.77316 ymax: 36.58965
## Geodetic CRS:  WGS 84
##    AREA PERIMETER CNTY_ CNTY_ID        NAME  FIPS FIPSNO CRESS_ID BIR74 SID74
## 1 0.114     1.442  1825    1825        Ashe 37009  37009        5  1091     1
## 2 0.061     1.231  1827    1827   Alleghany 37005  37005        3   487     0
## 3 0.143     1.630  1828    1828       Surry 37171  37171       86  3188     5
## 4 0.070     2.968  1831    1831   Currituck 37053  37053       27   508     1
## 5 0.153     2.206  1832    1832 Northampton 37131  37131       66  1421     9
## 6 0.097     1.670  1833    1833    Hertford 37091  37091       46  1452     7
##   NWBIR74 BIR79 SID79 NWBIR79   SIDR74   SIDR79      NWR74     NWR79
## 1      10  1364     0      19 0.916590 0.000000   9.165903  13.92962
## 2      10   542     3      12 0.000000 5.535055  20.533881  22.14022
## 3     208  3616     6     260 1.568381 1.659292  65.244668  71.90265
## 4     123   830     2     145 1.968504 2.409639 242.125984 174.69879
## 5    1066  1606     3    1197 6.333568 1.867995 750.175932 745.33001
## 6     954  1838     5    1237 4.820937 2.720348 657.024793 673.01415
##                         geometry
## 1 MULTIPOLYGON (((-81.47276 3...
## 2 MULTIPOLYGON (((-81.23989 3...
## 3 MULTIPOLYGON (((-80.45634 3...
## 4 MULTIPOLYGON (((-76.00897 3...
## 5 MULTIPOLYGON (((-77.21767 3...
## 6 MULTIPOLYGON (((-76.74506 3...</code></pre>
<p>The column <code>SIDR79</code> contains the death rate (per 1000 live births) (1979-84) from sudden infant death syndrome. Create a choropleth map of the SIDS rates.</p>
<div class="sourceCode" id="cb787"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb787-1"><a href="tuesday-september-27-2022.html#cb787-1" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_shape</span>(SIDS.sf) <span class="sc">+</span></span>
<span id="cb787-2"><a href="tuesday-september-27-2022.html#cb787-2" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_fill</span>(<span class="st">&quot;SIDR79&quot;</span>, <span class="at">title =</span> <span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb787-3"><a href="tuesday-september-27-2022.html#cb787-3" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb787-4"><a href="tuesday-september-27-2022.html#cb787-4" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_layout</span>(<span class="at">title =</span> <span class="st">&quot;SIDS Rates 1979-84 [per 1000]&quot;</span>,</span>
<span id="cb787-5"><a href="tuesday-september-27-2022.html#cb787-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-331-1.png" width="672" /></p>
<p>Create a neighborhood list (<code>nb</code>) and a <code>listw</code> object (<code>wts</code>) then graph the neighborhood network.</p>
<div class="sourceCode" id="cb788"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb788-1"><a href="tuesday-september-27-2022.html#cb788-1" aria-hidden="true" tabindex="-1"></a>nbs <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">poly2nb</span>(SIDS.sf)</span>
<span id="cb788-2"><a href="tuesday-september-27-2022.html#cb788-2" aria-hidden="true" tabindex="-1"></a>wts <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">nb2listw</span>(nbs)</span>
<span id="cb788-3"><a href="tuesday-september-27-2022.html#cb788-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb788-4"><a href="tuesday-september-27-2022.html#cb788-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(nbs, </span>
<span id="cb788-5"><a href="tuesday-september-27-2022.html#cb788-5" aria-hidden="true" tabindex="-1"></a>     sf<span class="sc">::</span><span class="fu">st_centroid</span>(<span class="fu">st_geometry</span>(SIDS.sf)))</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-332-1.png" width="672" /></p>
<p>Next compute Moran’s I on the SIDS rates over the period 1974–1979.</p>
<div class="sourceCode" id="cb789"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb789-1"><a href="tuesday-september-27-2022.html#cb789-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">length</span>(SIDS.sf<span class="sc">$</span>SIDR79)</span>
<span id="cb789-2"><a href="tuesday-september-27-2022.html#cb789-2" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">Szero</span>(wts)</span>
<span id="cb789-3"><a href="tuesday-september-27-2022.html#cb789-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb789-4"><a href="tuesday-september-27-2022.html#cb789-4" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">moran</span>(SIDS.sf<span class="sc">$</span>SIDR79, </span>
<span id="cb789-5"><a href="tuesday-september-27-2022.html#cb789-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">listw =</span> wts, </span>
<span id="cb789-6"><a href="tuesday-september-27-2022.html#cb789-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">n =</span> m, </span>
<span id="cb789-7"><a href="tuesday-september-27-2022.html#cb789-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">S0 =</span> s)</span></code></pre></div>
<pre><code>## $I
## [1] 0.1427504
## 
## $K
## [1] 4.44434</code></pre>
<p>I is .14 and K is 4.4. A normal distribution has a kurtosis of 3. Values less than about 2 or greater than about 4 indicate that inferences about autocorrelation based on the assumption of normality are suspect.</p>
<p>Weights are specified using the <code>style =</code> argument in the <code>nb2listw()</code> function. The default “W” is row standardized (sum of the weights over all links equals the number of polygons). “B” is binary (each neighbor gets a weight of one). “S” is a variance stabilizing scheme.</p>
<p>Each style gives a somewhat different value for I.</p>
<div class="sourceCode" id="cb791"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb791-1"><a href="tuesday-september-27-2022.html#cb791-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> SIDS.sf<span class="sc">$</span>SIDR79</span>
<span id="cb791-2"><a href="tuesday-september-27-2022.html#cb791-2" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">moran.test</span>(x, spdep<span class="sc">::</span><span class="fu">nb2listw</span>(nbs, <span class="at">style =</span> <span class="st">&quot;W&quot;</span>))<span class="sc">$</span>estimate[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## Moran I statistic 
##         0.1427504</code></pre>
<div class="sourceCode" id="cb793"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb793-1"><a href="tuesday-september-27-2022.html#cb793-1" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">moran.test</span>(x, spdep<span class="sc">::</span><span class="fu">nb2listw</span>(nbs, <span class="at">style =</span> <span class="st">&quot;B&quot;</span>))<span class="sc">$</span>estimate[<span class="dv">1</span>]  <span class="co"># binary</span></span></code></pre></div>
<pre><code>## Moran I statistic 
##         0.1105207</code></pre>
<div class="sourceCode" id="cb795"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb795-1"><a href="tuesday-september-27-2022.html#cb795-1" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">moran.test</span>(x, spdep<span class="sc">::</span><span class="fu">nb2listw</span>(nbs, <span class="at">style =</span> <span class="st">&quot;S&quot;</span>))<span class="sc">$</span>estimate[<span class="dv">1</span>]  <span class="co"># variance-stabilizing</span></span></code></pre></div>
<pre><code>## Moran I statistic 
##         0.1260686</code></pre>
<p>When reporting a Moran’s I you need to state what type of weighting was used.</p>
<p>Let <code>sids</code> be a vector with elements containing the SIDS rate in each county. You create a spatial lag variable using the <code>spdep::lag.listw()</code> function. The first argument is the <code>listw</code> object and the second is the vector of rates.</p>
<div class="sourceCode" id="cb797"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb797-1"><a href="tuesday-september-27-2022.html#cb797-1" aria-hidden="true" tabindex="-1"></a>sids <span class="ot">&lt;-</span> SIDS.sf<span class="sc">$</span>SIDR79</span>
<span id="cb797-2"><a href="tuesday-september-27-2022.html#cb797-2" aria-hidden="true" tabindex="-1"></a>Wsids <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">lag.listw</span>(wts, </span>
<span id="cb797-3"><a href="tuesday-september-27-2022.html#cb797-3" aria-hidden="true" tabindex="-1"></a>                          sids)</span></code></pre></div>
<p>For each value in the vector <code>sids</code> there is a corresponding value in the object <code>Wsids</code> representing the neighborhood average SIDS rate.</p>
<div class="sourceCode" id="cb798"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb798-1"><a href="tuesday-september-27-2022.html#cb798-1" aria-hidden="true" tabindex="-1"></a>Wsids[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 2.65921</code></pre>
<div class="sourceCode" id="cb800"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb800-1"><a href="tuesday-september-27-2022.html#cb800-1" aria-hidden="true" tabindex="-1"></a>j <span class="ot">&lt;-</span> wts<span class="sc">$</span>neighbours[[<span class="dv">1</span>]]</span>
<span id="cb800-2"><a href="tuesday-september-27-2022.html#cb800-2" aria-hidden="true" tabindex="-1"></a>j</span></code></pre></div>
<pre><code>## [1]  2 18 19</code></pre>
<div class="sourceCode" id="cb802"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb802-1"><a href="tuesday-september-27-2022.html#cb802-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(SIDS.sf<span class="sc">$</span>SIDR79[j])<span class="sc">/</span><span class="fu">length</span>(j)</span></code></pre></div>
<pre><code>## [1] 2.65921</code></pre>
<p>The weight for county one is <code>Wsids[1]</code> = 2.659. The neighbor indexes for this county are in the vector <code>wts$neighbours[[1]]</code> of length 3. Add the SIDS rates from those counties and divide by the number of counties (<code>length(j)</code>).</p>
<p>A scatter plot of the neighborhood average SIDS rate versus the actual SIDS rate in each region.</p>
<div class="sourceCode" id="cb804"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb804-1"><a href="tuesday-september-27-2022.html#cb804-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(sids, Wsids) <span class="sc">|&gt;</span></span>
<span id="cb804-2"><a href="tuesday-september-27-2022.html#cb804-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> sids, <span class="at">y =</span> Wsids)) <span class="sc">+</span> </span>
<span id="cb804-3"><a href="tuesday-september-27-2022.html#cb804-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb804-4"><a href="tuesday-september-27-2022.html#cb804-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm) <span class="sc">+</span></span>
<span id="cb804-5"><a href="tuesday-september-27-2022.html#cb804-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">7</span>)) <span class="sc">+</span></span>
<span id="cb804-6"><a href="tuesday-september-27-2022.html#cb804-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">7</span>)) <span class="sc">+</span></span>
<span id="cb804-7"><a href="tuesday-september-27-2022.html#cb804-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;SIDS&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Spatial Lag of SIDS&quot;</span>) <span class="sc">+</span></span>
<span id="cb804-8"><a href="tuesday-september-27-2022.html#cb804-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-337-1.png" width="672" /></p>
<p>The regression line slopes upward indicating positive spatial autocorrelation. The value of the slope is I. To check this type</p>
<div class="sourceCode" id="cb806"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb806-1"><a href="tuesday-september-27-2022.html#cb806-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(Wsids <span class="sc">~</span> sids)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Wsids ~ sids)
## 
## Coefficients:
## (Intercept)         sids  
##      1.7622       0.1428</code></pre>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tuesday-september-20-2022.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="thursday-september-29-2022.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
