<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tuesday, January 17, 2023 | Untitled</title>
  <meta name="description" content="Tuesday, January 17, 2023 | Untitled" />
  <meta name="generator" content="bookdown 0.31 and GitBook 2.6.7" />

  <meta property="og:title" content="Tuesday, January 17, 2023 | Untitled" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="jelsner/ASS-2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tuesday, January 17, 2023 | Untitled" />
  
  
  

<meta name="author" content="James B. Elsner" />


<meta name="date" content="2023-01-12" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="thursday-january-12-2023.html"/>
<link rel="next" href="thursday-january-19-2023.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied Spatial Statistics</a></li>

<li class="divider"></li>
<li><a href="index.html#section" id="toc-section"></a></li>
<li class="chapter" data-level="" data-path="syllabus-and-set-up.html"><a href="syllabus-and-set-up.html"><i class="fa fa-check"></i>Syllabus and set up</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus-and-set-up.html"><a href="syllabus-and-set-up.html#contact-information"><i class="fa fa-check"></i>Contact information</a></li>
<li class="chapter" data-level="" data-path="syllabus-and-set-up.html"><a href="syllabus-and-set-up.html#course-description-and-expected-learning-outcomes"><i class="fa fa-check"></i>Course description and expected learning outcomes</a></li>
<li class="chapter" data-level="" data-path="syllabus-and-set-up.html"><a href="syllabus-and-set-up.html#grades-and-ethics"><i class="fa fa-check"></i>Grades and ethics</a></li>
<li class="chapter" data-level="" data-path="syllabus-and-set-up.html"><a href="syllabus-and-set-up.html#outline-of-topics-and-schedule"><i class="fa fa-check"></i>Outline of topics and schedule</a></li>
<li class="chapter" data-level="" data-path="syllabus-and-set-up.html"><a href="syllabus-and-set-up.html#reference-materials"><i class="fa fa-check"></i>Reference materials</a></li>
<li class="chapter" data-level="" data-path="syllabus-and-set-up.html"><a href="syllabus-and-set-up.html#reproducible-research"><i class="fa fa-check"></i>Reproducible research</a></li>
<li class="chapter" data-level="" data-path="syllabus-and-set-up.html"><a href="syllabus-and-set-up.html#getting-you-set-up"><i class="fa fa-check"></i>Getting you set up</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-january-12-2023.html"><a href="thursday-january-12-2023.html"><i class="fa fa-check"></i>Thursday, January 12, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-january-12-2023.html"><a href="thursday-january-12-2023.html#important-points-from-the-syllabus"><i class="fa fa-check"></i>Important points from the syllabus</a></li>
<li class="chapter" data-level="" data-path="thursday-january-12-2023.html"><a href="thursday-january-12-2023.html#continue-with-setup"><i class="fa fa-check"></i>Continue with setup</a></li>
<li class="chapter" data-level="" data-path="thursday-january-12-2023.html"><a href="thursday-january-12-2023.html#about-rstudio"><i class="fa fa-check"></i>About RStudio</a></li>
<li class="chapter" data-level="" data-path="thursday-january-12-2023.html"><a href="thursday-january-12-2023.html#lab-assignments"><i class="fa fa-check"></i>Lab assignments</a></li>
<li class="chapter" data-level="" data-path="thursday-january-12-2023.html"><a href="thursday-january-12-2023.html#data-science-workflow-with-r-markdown"><i class="fa fa-check"></i>Data science workflow with R markdown</a></li>
<li class="chapter" data-level="" data-path="thursday-january-12-2023.html"><a href="thursday-january-12-2023.html#getting-started-with-r"><i class="fa fa-check"></i>Getting started with R</a></li>
<li class="chapter" data-level="" data-path="thursday-january-12-2023.html"><a href="thursday-january-12-2023.html#completely-new-to-r"><i class="fa fa-check"></i>Completely new to R?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-january-17-2023.html"><a href="tuesday-january-17-2023.html"><i class="fa fa-check"></i>Tuesday, January 17, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-january-17-2023.html"><a href="tuesday-january-17-2023.html#class-notes"><i class="fa fa-check"></i>Class notes</a></li>
<li class="chapter" data-level="" data-path="tuesday-january-17-2023.html"><a href="tuesday-january-17-2023.html#using-r"><i class="fa fa-check"></i>Using R</a></li>
<li class="chapter" data-level="" data-path="tuesday-january-17-2023.html"><a href="tuesday-january-17-2023.html#data-frames"><i class="fa fa-check"></i>Data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-january-17-2023.html"><a href="tuesday-january-17-2023.html#getting-data-into-r"><i class="fa fa-check"></i>Getting data into R</a></li>
<li class="chapter" data-level="" data-path="tuesday-january-17-2023.html"><a href="tuesday-january-17-2023.html#working-with-data-frames-using-functions-from-dplyr"><i class="fa fa-check"></i>Working with data frames using functions from {dplyr}</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-january-19-2023.html"><a href="thursday-january-19-2023.html"><i class="fa fa-check"></i>Thursday January 19, 2023</a></li>
<li class="chapter" data-level="" data-path="tuesday-january-24-2023.html"><a href="tuesday-january-24-2023.html"><i class="fa fa-check"></i>Tuesday January 24, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-january-24-2023.html"><a href="tuesday-january-24-2023.html#making-graphs"><i class="fa fa-check"></i>Making graphs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-january-31-2023.html"><a href="tuesday-january-31-2023.html"><i class="fa fa-check"></i>Tuesday January 31, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-january-31-2023.html"><a href="tuesday-january-31-2023.html#introduction-to-simple-features"><i class="fa fa-check"></i>Introduction to simple features</a></li>
<li class="chapter" data-level="" data-path="tuesday-january-31-2023.html"><a href="tuesday-january-31-2023.html#geo-computation-on-simple-features"><i class="fa fa-check"></i>Geo-computation on simple features</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-february-2-2023.html"><a href="thursday-february-2-2023.html"><i class="fa fa-check"></i>Thursday February 2, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-february-2-2023.html"><a href="thursday-february-2-2023.html#spatial-data-subsets-and-joins"><i class="fa fa-check"></i>Spatial data subsets and joins</a></li>
<li class="chapter" data-level="" data-path="thursday-february-2-2023.html"><a href="thursday-february-2-2023.html#interpolation-using-areal-weights"><i class="fa fa-check"></i>Interpolation using areal weights</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-february-7-2023.html"><a href="tuesday-february-7-2023.html"><i class="fa fa-check"></i>Tuesday February 7, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-february-7-2023.html"><a href="tuesday-february-7-2023.html#s4-spatial-data-objects"><i class="fa fa-check"></i>S4 spatial data objects</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-7-2023.html"><a href="tuesday-february-7-2023.html#working-with-raster-data"><i class="fa fa-check"></i>Working with raster data</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-7-2023.html"><a href="tuesday-february-7-2023.html#working-with-space-time-data"><i class="fa fa-check"></i>Working with space-time data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-february-9-2023.html"><a href="thursday-february-9-2023.html"><i class="fa fa-check"></i>Thursday February 9, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-february-9-2023.html"><a href="thursday-february-9-2023.html#mapping-using-functions-from-the-ggplot2-package"><i class="fa fa-check"></i>Mapping using functions from the {ggplot2} package</a></li>
<li class="chapter" data-level="" data-path="thursday-february-9-2023.html"><a href="thursday-february-9-2023.html#mapping-using-functions-from-the-tmap-package"><i class="fa fa-check"></i>Mapping using functions from the {tmap} package</a></li>
<li class="chapter" data-level="" data-path="thursday-february-9-2023.html"><a href="thursday-february-9-2023.html#creating-an-interactive-map"><i class="fa fa-check"></i>Creating an interactive map</a></li>
<li class="chapter" data-level="0.1" data-path="thursday-february-9-2023.html"><a href="thursday-february-9-2023.html#isolines-and-isobands"><i class="fa fa-check"></i><b>0.1</b> Isolines and isobands</a></li>
<li class="chapter" data-level="" data-path="thursday-february-9-2023.html"><a href="thursday-february-9-2023.html#hillshape-and-colors-with-tidyterra"><i class="fa fa-check"></i>Hillshape and colors with tidyterra</a></li>
<li class="chapter" data-level="0.2" data-path="thursday-february-9-2023.html"><a href="thursday-february-9-2023.html#visualizing-spatial-data"><i class="fa fa-check"></i><b>0.2</b> Visualizing spatial data</a></li>
<li class="chapter" data-level="" data-path="thursday-february-9-2023.html"><a href="thursday-february-9-2023.html#adding-an-inset-map"><i class="fa fa-check"></i>Adding an inset map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-february-16-2023.html"><a href="thursday-february-16-2023.html"><i class="fa fa-check"></i>Thursday February 16, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-february-16-2023.html"><a href="thursday-february-16-2023.html#defining-spatial-neighborhoods-and-spatial-weights"><i class="fa fa-check"></i>Defining spatial neighborhoods and spatial weights</a></li>
<li class="chapter" data-level="" data-path="thursday-february-16-2023.html"><a href="thursday-february-16-2023.html#computing-autocorrelation"><i class="fa fa-check"></i>Computing autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-february-16-2023.html"><a href="thursday-february-16-2023.html#spatial-lag-and-its-relation-to-autocorrelation"><i class="fa fa-check"></i>Spatial lag and its relation to autocorrelation</a></li>
<li class="chapter" data-level="0.3" data-path="thursday-february-16-2023.html"><a href="thursday-february-16-2023.html#making-maps-with-rdeck"><i class="fa fa-check"></i><b>0.3</b> Making maps with rdeck</a></li>
<li class="chapter" data-level="" data-path="thursday-february-16-2023.html"><a href="thursday-february-16-2023.html#other-neighbor-definitions"><i class="fa fa-check"></i>Other neighbor definitions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-february-21-2023.html"><a href="tuesday-february-21-2023.html"><i class="fa fa-check"></i>Tuesday February 21, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-february-21-2023.html"><a href="tuesday-february-21-2023.html#assessing-the-statistical-significance-of-autocorrelation"><i class="fa fa-check"></i>Assessing the statistical significance of autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-21-2023.html"><a href="tuesday-february-21-2023.html#bivariate-spatial-autocorrelation"><i class="fa fa-check"></i>Bivariate spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-21-2023.html"><a href="tuesday-february-21-2023.html#local-indicators-of-spatial-autocorrelation"><i class="fa fa-check"></i>Local indicators of spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-21-2023.html"><a href="tuesday-february-21-2023.html#constraining-group-membership-based-on-spatial-autocorrelation"><i class="fa fa-check"></i>Constraining group membership based on spatial autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-february-23-2023.html"><a href="thursday-february-23-2023.html"><i class="fa fa-check"></i>Thursday February 23, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-february-23-2023.html"><a href="thursday-february-23-2023.html#estimating-spatial-autocorrelation-in-model-residuals"><i class="fa fa-check"></i>Estimating spatial autocorrelation in model residuals</a></li>
<li class="chapter" data-level="" data-path="thursday-february-23-2023.html"><a href="thursday-february-23-2023.html#choosing-a-spatial-regression-model"><i class="fa fa-check"></i>Choosing a spatial regression model</a></li>
<li class="chapter" data-level="" data-path="thursday-february-23-2023.html"><a href="thursday-february-23-2023.html#fitting-and-interpreting-spatial-regression-models"><i class="fa fa-check"></i>Fitting and interpreting spatial regression models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-february-28-2023.html"><a href="tuesday-february-28-2023.html"><i class="fa fa-check"></i>Tuesday February 28, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-february-28-2023.html"><a href="tuesday-february-28-2023.html#fitting-and-interpreting-geographic-regression"><i class="fa fa-check"></i>Fitting and interpreting geographic regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-28-2023.html"><a href="tuesday-february-28-2023.html#mapping-incidence-and-risk-with-a-spatial-regression-model"><i class="fa fa-check"></i>Mapping incidence and risk with a spatial regression model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-march-7-2023.html"><a href="tuesday-march-7-2023.html"><i class="fa fa-check"></i>Tuesday March 7, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-march-7-2023.html"><a href="tuesday-march-7-2023.html#spatial-data-as-point-patterns"><i class="fa fa-check"></i>Spatial data as point patterns</a></li>
<li class="chapter" data-level="" data-path="tuesday-march-7-2023.html"><a href="tuesday-march-7-2023.html#theoretical-framework-for-analyzingmodeling-point-pattern-data"><i class="fa fa-check"></i>Theoretical framework for analyzing/modeling point pattern data</a></li>
<li class="chapter" data-level="" data-path="tuesday-march-7-2023.html"><a href="tuesday-march-7-2023.html#working-with-point-pattern-data-using-functions-from-the-spatstat-package"><i class="fa fa-check"></i>Working with point pattern data using functions from the spatstat package</a></li>
<li class="chapter" data-level="" data-path="tuesday-march-7-2023.html"><a href="tuesday-march-7-2023.html#quantifying-the-spatial-intensity-of-events"><i class="fa fa-check"></i>Quantifying the spatial intensity of events</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-march-21-2023.html"><a href="tuesday-march-21-2023.html"><i class="fa fa-check"></i>Tuesday March 21, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-march-21-2023.html"><a href="tuesday-march-21-2023.html#creating-ppp-and-owin-objects-from-simple-feature-data-frames"><i class="fa fa-check"></i>Creating <code>ppp</code> and <code>owin</code> objects from simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-march-21-2023.html"><a href="tuesday-march-21-2023.html#estimating-spatial-intensity-as-a-function-of-distance"><i class="fa fa-check"></i>Estimating spatial intensity as a function of distance</a></li>
<li class="chapter" data-level="" data-path="tuesday-march-21-2023.html"><a href="tuesday-march-21-2023.html#covariate-trend-as-a-possible-confounding-factor"><i class="fa fa-check"></i>Covariate trend as a possible confounding factor</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-march-23-2023.html"><a href="thursday-march-23-2023.html"><i class="fa fa-check"></i>Thursday March 23, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-march-23-2023.html"><a href="thursday-march-23-2023.html#estimating-the-relative-risk"><i class="fa fa-check"></i>Estimating the relative risk</a></li>
<li class="chapter" data-level="" data-path="thursday-march-23-2023.html"><a href="thursday-march-23-2023.html#estimating-second-moment-properties-of-events"><i class="fa fa-check"></i>Estimating second-moment properties of events</a></li>
<li class="chapter" data-level="" data-path="thursday-march-23-2023.html"><a href="thursday-march-23-2023.html#examples-of-clustered-events"><i class="fa fa-check"></i>Examples of clustered events</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-march-28-2023.html"><a href="tuesday-march-28-2023.html"><i class="fa fa-check"></i>Tuesday March 28, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-march-28-2023.html"><a href="tuesday-march-28-2023.html#removing-duplicate-events-and-defining-the-domain"><i class="fa fa-check"></i>Removing duplicate events and defining the domain</a></li>
<li class="chapter" data-level="" data-path="tuesday-march-28-2023.html"><a href="tuesday-march-28-2023.html#determining-statistical-significance-of-clustering"><i class="fa fa-check"></i>Determining statistical significance of clustering</a></li>
<li class="chapter" data-level="" data-path="tuesday-march-28-2023.html"><a href="tuesday-march-28-2023.html#estimating-clustering-in-multi-type-event-locations"><i class="fa fa-check"></i>Estimating clustering in multi-type event locations</a></li>
<li class="chapter" data-level="" data-path="tuesday-march-28-2023.html"><a href="tuesday-march-28-2023.html#interpolating-output-from-a-distance-function"><i class="fa fa-check"></i>Interpolating output from a distance function</a></li>
<li class="chapter" data-level="" data-path="tuesday-march-28-2023.html"><a href="tuesday-march-28-2023.html#limitations-of-the-distance-functions"><i class="fa fa-check"></i>Limitations of the distance functions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-march-30-2023.html"><a href="thursday-march-30-2023.html"><i class="fa fa-check"></i>Thursday March 30, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-march-30-2023.html"><a href="thursday-march-30-2023.html#limitations-on-interpreting-distance-functions"><i class="fa fa-check"></i>Limitations on interpreting distance functions</a></li>
<li class="chapter" data-level="" data-path="thursday-march-30-2023.html"><a href="thursday-march-30-2023.html#models-for-point-pattern-data"><i class="fa fa-check"></i>Models for point pattern data</a></li>
<li class="chapter" data-level="" data-path="thursday-march-30-2023.html"><a href="thursday-march-30-2023.html#fitting-and-interpreting-inhibition-models"><i class="fa fa-check"></i>Fitting and interpreting inhibition models</a></li>
<li class="chapter" data-level="" data-path="thursday-march-30-2023.html"><a href="thursday-march-30-2023.html#fitting-and-interpreting-cluster-models"><i class="fa fa-check"></i>Fitting and interpreting cluster models</a></li>
<li class="chapter" data-level="" data-path="thursday-march-30-2023.html"><a href="thursday-march-30-2023.html#assessing-how-well-the-model-fits"><i class="fa fa-check"></i>Assessing how well the model fits</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-april-4-2023.html"><a href="tuesday-april-4-2023.html"><i class="fa fa-check"></i>Tuesday April 4, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-april-4-2023.html"><a href="tuesday-april-4-2023.html#fitting-a-log-gaussian-cox-model"><i class="fa fa-check"></i>Fitting a log-Gaussian Cox model</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-4-2023.html"><a href="tuesday-april-4-2023.html#assessing-how-well-a-point-pattern-model-fits-the-data"><i class="fa fa-check"></i>Assessing how well a point pattern model fits the data</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-4-2023.html"><a href="tuesday-april-4-2023.html#an-example-of-a-point-process-model-in-the-wild"><i class="fa fa-check"></i>An example of a point process model in the wild</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-april-6-2023.html"><a href="thursday-april-6-2023.html"><i class="fa fa-check"></i>Thursday April 6, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-april-6-2023.html"><a href="thursday-april-6-2023.html#spatial-logistic-regression"><i class="fa fa-check"></i>Spatial logistic regression</a></li>
<li class="chapter" data-level="" data-path="thursday-april-6-2023.html"><a href="thursday-april-6-2023.html#spatial-data-interpolation"><i class="fa fa-check"></i>Spatial data interpolation</a></li>
<li class="chapter" data-level="" data-path="thursday-april-6-2023.html"><a href="thursday-april-6-2023.html#computing-the-sample-variogram"><i class="fa fa-check"></i>Computing the sample variogram</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-april-13-2023.html"><a href="thursday-april-13-2023.html"><i class="fa fa-check"></i>Thursday April 13, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-april-13-2023.html"><a href="thursday-april-13-2023.html#fitting-a-variogram-model-to-the-sample-variogram"><i class="fa fa-check"></i>Fitting a variogram model to the sample variogram</a></li>
<li class="chapter" data-level="" data-path="thursday-april-13-2023.html"><a href="thursday-april-13-2023.html#creating-an-interpolated-surface-with-the-method-of-kriging"><i class="fa fa-check"></i>Creating an interpolated surface with the method of kriging</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-april-18-2023.html"><a href="tuesday-april-18-2023.html"><i class="fa fa-check"></i>Tuesday April 18, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-april-18-2023.html"><a href="tuesday-april-18-2023.html#comparing-interpolation-methods"><i class="fa fa-check"></i>Comparing interpolation methods</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-18-2023.html"><a href="tuesday-april-18-2023.html#evaluating-interpolation-accuracy"><i class="fa fa-check"></i>Evaluating interpolation accuracy</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-18-2023.html"><a href="tuesday-april-18-2023.html#block-cross-validation"><i class="fa fa-check"></i>Block cross validation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-april-20-2023.html"><a href="thursday-april-20-2023.html"><i class="fa fa-check"></i>Thursday April 20, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-april-20-2023.html"><a href="thursday-april-20-2023.html#interpolating-to-areal-units-block-kriging"><i class="fa fa-check"></i>Interpolating to areal units (block kriging)</a></li>
<li class="chapter" data-level="" data-path="thursday-april-20-2023.html"><a href="thursday-april-20-2023.html#simulating-spatial-fields"><i class="fa fa-check"></i>Simulating spatial fields</a></li>
<li class="chapter" data-level="" data-path="thursday-april-20-2023.html"><a href="thursday-april-20-2023.html#interpolating-multiple-variables"><i class="fa fa-check"></i>Interpolating multiple variables</a></li>
<li class="chapter" data-level="" data-path="thursday-april-20-2023.html"><a href="thursday-april-20-2023.html#machine-learning-for-spatial-interpolation"><i class="fa fa-check"></i>Machine learning for spatial interpolation</a></li>
<li class="chapter" data-level="0.4" data-path="thursday-april-20-2023.html"><a href="thursday-april-20-2023.html#r-markdown"><i class="fa fa-check"></i><b>0.4</b> R Markdown</a></li>
<li class="chapter" data-level="0.5" data-path="thursday-april-20-2023.html"><a href="thursday-april-20-2023.html#including-plots"><i class="fa fa-check"></i><b>0.5</b> Including Plots</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Untitled</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="tuesday-january-17-2023" class="section level1 unnumbered hasAnchor">
<h1>Tuesday, January 17, 2023<a href="tuesday-january-17-2023.html#tuesday-january-17-2023" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>“If you give your code to a competent programmer who’s never seen it and they ask any questions, you’ve failed. Every question is a defect.”</strong> — Allen Holub</p>
<div id="class-notes" class="section level2 unnumbered hasAnchor">
<h2>Class notes<a href="tuesday-january-17-2023.html#class-notes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>You should now have a set of class notes as lesson files in your own GitHub repository and on your laptop. Note that these files are based on last semester’s class. I will update them as we proceed through the semester</p>
<p>So at the start of each class (Sync from GitHub then Pull from RStudio)</p>
<ul>
<li><p>Go to <code>https://github.com/[your GitHub username]</code></p></li>
<li><p>Select the <code>Sync fork</code> button under the green <code>Code</code> button</p></li>
<li><p>Click <code>Update branch</code></p></li>
<li><p>Open the Folder <code>ASS-2023-[your name]</code> on your Desktop</p></li>
<li><p>Open the file <code>ASS-2023.Rproj</code></p></li>
<li><p>Under the <code>Git</code> tab select blue arrow (pointing down) to <code>Pull</code> down changes from your GitHub repository</p></li>
<li><p>Select the <code>XX-Lesson.Rmd</code> file</p></li>
</ul>
<p>Note: If you see a yellow caution sign when you open the lesson file, download the required packages</p>
<p>Don’t push and rename your files</p>
<ul>
<li>You can add notes to the lesson files (<code>_.Rmd</code>) on your computer</li>
<li>You can add new files to your local directory</li>
<li>These changes stay on your computer only</li>
<li>Don’t push them to your GitHub repository!</li>
</ul>
<p>At the end of the semester you can push your notes to your repository</p>
<ul>
<li>Check the <code>Staged</code> button under the <code>Git</code> tab for all files you want to push</li>
<li>Then select the <code>Commit</code> button</li>
<li>Add a note to the <code>Commit message</code> section (e.g., my updates)</li>
<li>Select the green arrow (pointing up) to <code>Push</code> changes to your GitHub</li>
<li>The <em>first time</em> you do this you need to include your GitHub username and Personal access token</li>
</ul>
<p>Get a personal access token</p>
<ul>
<li>Go to your GitHub account</li>
<li>In the far upper-right pull down menu (next to your avatar) select <code>Settings</code> then <code>Developer settings</code></li>
<li>In the left menu select <code>Personal access tokens &gt; Tokens (classic)</code></li>
<li>Follow instructions to generate a personal access toke (PAT)</li>
<li>Use your PAT as your password when pushing changes made on your computer to your GitHub account</li>
</ul>
<p>Finally you can unfork your repository (see the instructions here <a href="https://nickymeuleman.netlify.app/blog/unfork-github-repo" class="uri">https://nickymeuleman.netlify.app/blog/unfork-github-repo</a>)</p>
<p>New resource for applied spatial statistics <a href="https://geocompx.org/" class="uri">https://geocompx.org/</a></p>
</div>
<div id="using-r" class="section level2 unnumbered hasAnchor">
<h2>Using R<a href="tuesday-january-17-2023.html#using-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Consider a set of integers representing the number of hurricanes making landfall in the United States from the last ten years. You assign the values to an object and print the contents of the object by wrapping the line of code in parentheses</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="tuesday-january-17-2023.html#cb1-1" aria-hidden="true" tabindex="-1"></a>( d <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">1</span>) )</span></code></pre></div>
<pre><code>##  [1] 2 3 0 3 1 0 0 1 2 1</code></pre>
<p>Suppose you are interested in the inter annual variability in the set of landfall counts. The variance is computed as</p>
<p><span class="math display">\[
\hbox{var}(x) = \frac{(x_1 - \bar x)^2 + (x_2 - \bar x)^2 + \cdots + (x_n - \bar x)^2}{n-1} = \frac{1}{n-1}\sum_{i=1}^n (x_i - \bar x)^2
\]</span></p>
<p>Note: the markdown file recognizes math written in LaTeX. The formula for the variance is written using LaTeX notation gets rendered as a math equation (like you see in a textbook) See <a href="https://www.overleaf.com/learn/latex/Mathematical_expressions" class="uri">https://www.overleaf.com/learn/latex/Mathematical_expressions</a></p>
<p>Although the <code>var()</code> function computes this, here you do this using simple functions. The key is to find the squared differences and then sum these values</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="tuesday-january-17-2023.html#cb3-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> d</span>
<span id="cb3-2"><a href="tuesday-january-17-2023.html#cb3-2" aria-hidden="true" tabindex="-1"></a>xbar <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)</span>
<span id="cb3-3"><a href="tuesday-january-17-2023.html#cb3-3" aria-hidden="true" tabindex="-1"></a>x <span class="sc">-</span> xbar</span></code></pre></div>
<pre><code>##  [1]  0.7  1.7 -1.3  1.7 -0.3 -1.3 -1.3 -0.3  0.7 -0.3</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="tuesday-january-17-2023.html#cb5-1" aria-hidden="true" tabindex="-1"></a>(x <span class="sc">-</span> xbar)<span class="sc">^</span><span class="dv">2</span></span></code></pre></div>
<pre><code>##  [1] 0.49 2.89 1.69 2.89 0.09 1.69 1.69 0.09 0.49 0.09</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="tuesday-january-17-2023.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>((x <span class="sc">-</span> xbar)<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 12.1</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="tuesday-january-17-2023.html#cb9-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(x)</span>
<span id="cb9-2"><a href="tuesday-january-17-2023.html#cb9-2" aria-hidden="true" tabindex="-1"></a>n</span></code></pre></div>
<pre><code>## [1] 10</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="tuesday-january-17-2023.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>((x <span class="sc">-</span> xbar)<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>(n <span class="sc">-</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 1.344444</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="tuesday-january-17-2023.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(x)</span></code></pre></div>
<pre><code>## [1] 1.344444</code></pre>
<p>Elements in a vector object must all have the same type. This type can be numeric, as in counts, character strings, as in</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="tuesday-january-17-2023.html#cb15-1" aria-hidden="true" tabindex="-1"></a>simpsons <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&#39;Homer&#39;</span>, <span class="st">&#39;Marge&#39;</span>, <span class="st">&#39;Bart&#39;</span>, <span class="st">&#39;Lisa&#39;</span>, <span class="st">&#39;Maggie&#39;</span>)</span>
<span id="cb15-2"><a href="tuesday-january-17-2023.html#cb15-2" aria-hidden="true" tabindex="-1"></a>simpsons</span></code></pre></div>
<pre><code>## [1] &quot;Homer&quot;  &quot;Marge&quot;  &quot;Bart&quot;   &quot;Lisa&quot;   &quot;Maggie&quot;</code></pre>
<p>Character strings are made with matching quotes, either double, <code>"</code>, or single, <code>'</code>. If you mix types the values will be coerced into a common type, which is usually a character string. Arithmetic operations do not work on character strings</p>
<p>Returning to the land falling hurricane counts. Suppose the National Hurricane Center (NHC) reanalyzes a storm, and that the 6th year of the decade is a 1 rather than a 0 for the number of landfalls. In this case you change the sixth element to have the value 1</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="tuesday-january-17-2023.html#cb17-1" aria-hidden="true" tabindex="-1"></a>d[<span class="dv">6</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span></code></pre></div>
<p>You assign to the 6th year of the decade a value of one. The square brackets <code>[]</code> are used to reference elements of the data vector</p>
<p>Key: Parentheses <code>()</code> are used by functions and square brackets <code>[]</code> are used by data objects</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="tuesday-january-17-2023.html#cb18-1" aria-hidden="true" tabindex="-1"></a>d</span></code></pre></div>
<pre><code>##  [1] 2 3 0 3 1 1 0 1 2 1</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="tuesday-january-17-2023.html#cb20-1" aria-hidden="true" tabindex="-1"></a>d[<span class="dv">2</span>]</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="tuesday-january-17-2023.html#cb22-1" aria-hidden="true" tabindex="-1"></a>d[<span class="sc">-</span><span class="dv">4</span>]</span></code></pre></div>
<pre><code>## [1] 2 3 0 1 1 0 1 2 1</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="tuesday-january-17-2023.html#cb24-1" aria-hidden="true" tabindex="-1"></a>d[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">9</span>)]</span></code></pre></div>
<pre><code>## [1] 2 0 1 0 2</code></pre>
<p>The first line prints all the elements of the vector <code>d</code>. The second prints only the 2nd value of the vector. The third prints all but the 4th value. The fourth prints the values with odd element numbers</p>
<p>To create structured data, for example the integers 1 through 99 you can use the <code>:</code> operator</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="tuesday-january-17-2023.html#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">:</span><span class="dv">99</span></span>
<span id="cb26-2"><a href="tuesday-january-17-2023.html#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rev</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">99</span>)</span>
<span id="cb26-3"><a href="tuesday-january-17-2023.html#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="dv">99</span><span class="sc">:</span><span class="dv">1</span></span></code></pre></div>
<p>The <code>seq()</code> function is more general. You specify the sequence interval with the <code>by =</code> or <code>length =</code> arguments</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="tuesday-january-17-2023.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">1</span>, <span class="at">to =</span> <span class="dv">9</span>, <span class="at">by =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 1 3 5 7 9</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="tuesday-january-17-2023.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">1</span>, <span class="at">to =</span> <span class="dv">10</span>, <span class="at">by =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 1 3 5 7 9</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="tuesday-january-17-2023.html#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">1</span>, <span class="at">to =</span> <span class="dv">9</span>, <span class="at">length =</span> <span class="dv">5</span>)</span></code></pre></div>
<pre><code>## [1] 1 3 5 7 9</code></pre>
<p>The <code>rep()</code> function is used to create repetitive sequences. The first argument is a value or vector that you want repeated and the second argument is the number of times you want it repeated</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="tuesday-january-17-2023.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rep</span>(<span class="dv">1</span>, <span class="at">times =</span> <span class="dv">10</span>)</span></code></pre></div>
<pre><code>##  [1] 1 1 1 1 1 1 1 1 1 1</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="tuesday-january-17-2023.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rep</span>(simpsons, <span class="at">times =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##  [1] &quot;Homer&quot;  &quot;Marge&quot;  &quot;Bart&quot;   &quot;Lisa&quot;   &quot;Maggie&quot; &quot;Homer&quot;  &quot;Marge&quot;  &quot;Bart&quot;  
##  [9] &quot;Lisa&quot;   &quot;Maggie&quot;</code></pre>
<p>In the second example the vector <code>simpsons</code> containing the Simpson characters is repeated twice</p>
<p>To repeat each element of the vector use the <code>each =</code> argument</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="tuesday-january-17-2023.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rep</span>(simpsons, <span class="at">each =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##  [1] &quot;Homer&quot;  &quot;Homer&quot;  &quot;Marge&quot;  &quot;Marge&quot;  &quot;Bart&quot;   &quot;Bart&quot;   &quot;Lisa&quot;   &quot;Lisa&quot;  
##  [9] &quot;Maggie&quot; &quot;Maggie&quot;</code></pre>
<p>More complicated patterns can be repeated by specifying pairs of equal length vectors. In this case, each element of the first vector is repeated the corresponding number of times given by the element in the second vector</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="tuesday-january-17-2023.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;long&quot;</span>, <span class="st">&quot;short&quot;</span>),  <span class="at">times =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>))</span></code></pre></div>
<pre><code>## [1] &quot;long&quot;  &quot;long&quot;  &quot;short&quot; &quot;short&quot; &quot;short&quot;</code></pre>
<p>To find the maximum number of landfalls during the first decade you type</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="tuesday-january-17-2023.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(d)</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>What years had the maximum?</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="tuesday-january-17-2023.html#cb43-1" aria-hidden="true" tabindex="-1"></a>d <span class="sc">==</span> <span class="dv">3</span></span></code></pre></div>
<pre><code>##  [1] FALSE  TRUE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE</code></pre>
<p>Notice the double equals signs (<code>==</code>). This is a logical operator that tests each value in <code>d</code> to see if it is equal to 3. The 2nd and 4th values are equal to 3 so <code>TRUE</code>s are returned</p>
<p>Think of this as asking R a question. Is the value equal to 3? R answers all at once with a vector of <code>TRUE</code>’s and <code>FALSE</code>’s</p>
<p>What years had more than 2 hurricanes?</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="tuesday-january-17-2023.html#cb45-1" aria-hidden="true" tabindex="-1"></a>d <span class="sc">&gt;</span> <span class="dv">2</span></span></code></pre></div>
<pre><code>##  [1] FALSE  TRUE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE</code></pre>
<p>Now the question is how do you get the vector element corresponding to the <code>TRUE</code> values? That is, which years have 3 landfalls?</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="tuesday-january-17-2023.html#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(d <span class="sc">==</span> <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] 2 4</code></pre>
<p>The function <code>which.max()</code> can be used to get the first maximum</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="tuesday-january-17-2023.html#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which.max</span>(d)</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<p>You might be interested in the total number of landfalls in the decade or the number of years in a decade without a landfall</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="tuesday-january-17-2023.html#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(d)</span></code></pre></div>
<pre><code>## [1] 14</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="tuesday-january-17-2023.html#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(d <span class="sc">==</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<p>With a logical vector the <code>TRUE</code> elements are treated as having a value of 1 and the <code>FALSE</code> elements are treated as having a value of 0</p>
<p>The <code>rm()</code> function removes an object from your environment</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="tuesday-january-17-2023.html#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(d)</span></code></pre></div>
</div>
<div id="data-frames" class="section level2 unnumbered hasAnchor">
<h2>Data frames<a href="tuesday-january-17-2023.html#data-frames" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Spatial data frames are used throughout this course. A spatial data frame is a data frame plus information on where the observations were taken</p>
<p>A data frame stores data in a tabular format like a spreadsheet. It is a list of vectors each with the same length. It has column names (and sometimes row names)</p>
<p>For example, you create a data frame object <code>df</code> containing three vectors <code>n</code>, <code>s</code>, <code>b</code> each with three elements using the <code>data.frame()</code> function</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="tuesday-january-17-2023.html#cb56-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">5</span>) </span>
<span id="cb56-2"><a href="tuesday-january-17-2023.html#cb56-2" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;aa&quot;</span>, <span class="st">&quot;bb&quot;</span>, <span class="st">&quot;cc&quot;</span>) </span>
<span id="cb56-3"><a href="tuesday-january-17-2023.html#cb56-3" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">FALSE</span>, <span class="cn">TRUE</span>) </span>
<span id="cb56-4"><a href="tuesday-january-17-2023.html#cb56-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-5"><a href="tuesday-january-17-2023.html#cb56-5" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(n, s, b)</span></code></pre></div>
<p>To see check on the type of object you use the <code>class()</code> function with the name of the object inside the parentheses</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="tuesday-january-17-2023.html#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(df)</span></code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<p>The object <code>df</code> is of class <code>data.frame</code>. Note that the object name shows up in our <em>Environment</em> under <em>Data</em> and it includes a little blue arrow indicating that you can view it by clicking on the row</p>
<p>The data frame shows up as a table (like a spreadsheet) in the <code>View()</code> mode (see the command in the console below). This is not advised for large data frames!</p>
<p>The top line of the table is called the header. Each line below the header contains a row of data, which begins with the name (or number) of the row followed by the data values</p>
<p>Each data element is in a cell. To retrieve a data value from a cell, you enter its row and column coordinates in that order in the single square bracket <code>[]</code> operator and separated by a column</p>
<p>df[row, column]</p>
<p>Here is the cell value from the first row, second column of <code>df</code></p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="tuesday-january-17-2023.html#cb59-1" aria-hidden="true" tabindex="-1"></a>df[<span class="dv">1</span>, <span class="dv">2</span>]</span></code></pre></div>
<pre><code>## [1] &quot;aa&quot;</code></pre>
<p>You print the column names (located in the top row in the <code>View()</code> mode) with the <code>names()</code> function</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="tuesday-january-17-2023.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(df)</span></code></pre></div>
<pre><code>## [1] &quot;n&quot; &quot;s&quot; &quot;b&quot;</code></pre>
<p>The list of names is a vector of length three containing the elements <code>n</code>, <code>s</code>, and <code>b</code> in that order</p>
<p>You access individual columns of a data frame as vectors by appending the dollar sign (<code>$</code>) to the object name. For example, to print the values of the column labeled <code>s</code> type</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="tuesday-january-17-2023.html#cb63-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>s</span></code></pre></div>
<pre><code>## [1] &quot;aa&quot; &quot;bb&quot; &quot;cc&quot;</code></pre>
<p>Many packages include example data frames. The data frame called <code>mtcars</code>, for instance, contains information extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models)</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="tuesday-january-17-2023.html#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(mtcars)</span></code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="tuesday-january-17-2023.html#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(mtcars)</span></code></pre></div>
<pre><code>##  [1] &quot;mpg&quot;  &quot;cyl&quot;  &quot;disp&quot; &quot;hp&quot;   &quot;drat&quot; &quot;wt&quot;   &quot;qsec&quot; &quot;vs&quot;   &quot;am&quot;   &quot;gear&quot;
## [11] &quot;carb&quot;</code></pre>
<p>The number of data rows and data columns in the data frame are printed using the <code>nrow()</code> and <code>ncol()</code> functions</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="tuesday-january-17-2023.html#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(mtcars)</span></code></pre></div>
<pre><code>## [1] 32</code></pre>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="tuesday-january-17-2023.html#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ncol</span>(mtcars)</span></code></pre></div>
<pre><code>## [1] 11</code></pre>
<p>Further details of built-in data frames like <code>mtcars</code> is available in the documentation accessed with the <code>help()</code> (or <code>?</code>) function</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="tuesday-january-17-2023.html#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">help</span>(mtcars)</span></code></pre></div>
<p>If you type the name of the data frame in the console all the data are printed</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="tuesday-january-17-2023.html#cb74-1" aria-hidden="true" tabindex="-1"></a>mtcars</span></code></pre></div>
<pre><code>##                      mpg cyl  disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4           21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
## Mazda RX4 Wag       21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
## Datsun 710          22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
## Hornet 4 Drive      21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
## Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
## Valiant             18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
## Duster 360          14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
## Merc 240D           24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
## Merc 230            22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
## Merc 280            19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4
## Merc 280C           17.8   6 167.6 123 3.92 3.440 18.90  1  0    4    4
## Merc 450SE          16.4   8 275.8 180 3.07 4.070 17.40  0  0    3    3
## Merc 450SL          17.3   8 275.8 180 3.07 3.730 17.60  0  0    3    3
## Merc 450SLC         15.2   8 275.8 180 3.07 3.780 18.00  0  0    3    3
## Cadillac Fleetwood  10.4   8 472.0 205 2.93 5.250 17.98  0  0    3    4
## Lincoln Continental 10.4   8 460.0 215 3.00 5.424 17.82  0  0    3    4
## Chrysler Imperial   14.7   8 440.0 230 3.23 5.345 17.42  0  0    3    4
## Fiat 128            32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
## Honda Civic         30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
## Toyota Corolla      33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
## Toyota Corona       21.5   4 120.1  97 3.70 2.465 20.01  1  0    3    1
## Dodge Challenger    15.5   8 318.0 150 2.76 3.520 16.87  0  0    3    2
## AMC Javelin         15.2   8 304.0 150 3.15 3.435 17.30  0  0    3    2
## Camaro Z28          13.3   8 350.0 245 3.73 3.840 15.41  0  0    3    4
## Pontiac Firebird    19.2   8 400.0 175 3.08 3.845 17.05  0  0    3    2
## Fiat X1-9           27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
## Porsche 914-2       26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2
## Lotus Europa        30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2
## Ford Pantera L      15.8   8 351.0 264 4.22 3.170 14.50  0  1    5    4
## Ferrari Dino        19.7   6 145.0 175 3.62 2.770 15.50  0  1    5    6
## Maserati Bora       15.0   8 301.0 335 3.54 3.570 14.60  0  1    5    8
## Volvo 142E          21.4   4 121.0 109 4.11 2.780 18.60  1  1    4    2</code></pre>
<p>Instead, you use the function <code>head()</code>, which prints the first six rows, or <code>str()</code>, which lists all the columns by data type</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="tuesday-january-17-2023.html#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mtcars)</span></code></pre></div>
<pre><code>##                    mpg cyl disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
## Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
## Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
## Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
## Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
## Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="tuesday-january-17-2023.html#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mtcars)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    32 obs. of  11 variables:
##  $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
##  $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
##  $ disp: num  160 160 108 258 360 ...
##  $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
##  $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
##  $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
##  $ qsec: num  16.5 17 18.6 19.4 17 ...
##  $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
##  $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
##  $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
##  $ carb: num  4 4 1 1 2 1 4 2 2 4 ...</code></pre>
<p>Consider the data frame <code>studentdata</code> from the {LearnBayes} package. To access this data frame, first install the package with the <code>install.packages()</code> function</p>
<p>You put the name of the package {LearnBayes} in quotes (single or double). Then to make the functions from the package available to your current session use the <code>library()</code> function with the name of the package (unquoted) inside the parentheses</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="tuesday-january-17-2023.html#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(LearnBayes)) <span class="fu">install.packages</span>(<span class="at">pkgs =</span> <span class="st">&quot;LearnBayes&quot;</span>, <span class="at">repos =</span> <span class="st">&quot;http://cran.us.r-project.org&quot;</span>)</span></code></pre></div>
<pre><code>## Loading required package: LearnBayes</code></pre>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="tuesday-january-17-2023.html#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(LearnBayes)</span></code></pre></div>
<p>Note: The argument <code>repos =</code> in the <code>install.packages()</code> function directs where the package is obtained on CRAN (comprehensive R archive network). The CRAN repository is set automatically when using RStudio and you can install packages by clicking on <em>Packages</em> &gt; <em>Install</em> in the lower-right panel</p>
<p>You need to specify the repository. When you render the markdown file (using the <code>Knit</code> button) you don’t want to install packages that already exist on your computer so you add the conditional <code>if()</code> function that says “only install the package IF it is not (<code>!</code>) available”</p>
<p>Make a copy of the data frame by assigning it to an object with the name <code>df</code> and print the first six rows using the <code>head()</code> function</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="tuesday-january-17-2023.html#cb83-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> studentdata</span>
<span id="cb83-2"><a href="tuesday-january-17-2023.html#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code></pre></div>
<pre><code>##   Student Height Gender Shoes Number Dvds ToSleep WakeUp Haircut  Job Drink
## 1       1     67 female    10      5   10    -2.5    5.5      60 30.0 water
## 2       2     64 female    20      7    5     1.5    8.0       0 20.0   pop
## 3       3     61 female    12      2    6    -1.5    7.5      48  0.0  milk
## 4       4     61 female     3      6   40     2.0    8.5      10  0.0 water
## 5       5     70   male     4      5    6     0.0    9.0      15 17.5   pop
## 6       6     63 female    NA      3    5     1.0    8.5      25  0.0 water</code></pre>
<p>Data frames are like spreadsheets with rows and columns. Each row is an observation (here each row is a student in an intro stats class at Bowling Green State University) and each column is a variable. Here the variables are answers to questions like what is your height, choose a number between 1 and 10, what time did you go to bed last night, etc</p>
<p>The names of the columns are printed using the <code>names()</code> function</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="tuesday-january-17-2023.html#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(df)</span></code></pre></div>
<pre><code>##  [1] &quot;Student&quot; &quot;Height&quot;  &quot;Gender&quot;  &quot;Shoes&quot;   &quot;Number&quot;  &quot;Dvds&quot;    &quot;ToSleep&quot;
##  [8] &quot;WakeUp&quot;  &quot;Haircut&quot; &quot;Job&quot;     &quot;Drink&quot;</code></pre>
<p>All columns are of the same length, but not all students answered all questions so some of the data frame cells contain the missing-value indicator <code>NA</code> (not available)</p>
<p>Values in a data frame stored in rows and columns and are accessed with bracket notation [row, column] where row is the row number and column is the column number like a matrix</p>
<p>For example here you specify the value in the 10th row and 2nd column (<code>Height</code> column) of the <code>df</code> data frame</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="tuesday-january-17-2023.html#cb87-1" aria-hidden="true" tabindex="-1"></a>df[<span class="dv">10</span>, <span class="dv">2</span>]</span></code></pre></div>
<pre><code>## [1] 65</code></pre>
<p>By specifying only the row index and leaving the column index blank you get all values in that row, which corresponds to all the responses given by the 10th student</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="tuesday-january-17-2023.html#cb89-1" aria-hidden="true" tabindex="-1"></a>df[<span class="dv">10</span>, ]</span></code></pre></div>
<pre><code>##    Student Height Gender Shoes Number Dvds ToSleep WakeUp Haircut Job Drink
## 10      10     65   male    10      7   22     2.5    8.5      12   0  milk</code></pre>
<p>Drink preference was one of the questions. Responses across all students are available in the column labeled <code>Drink</code> as a vector of character values. You list the various drink preferences by typing</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="tuesday-january-17-2023.html#cb91-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Drink</span></code></pre></div>
<pre><code>##   [1] water pop   milk  water pop   water water pop   water milk  milk  water
##  [13] pop   milk  pop   water water pop   water water water water water milk 
##  [25] pop   water water pop   water water water water pop   water water water
##  [37] pop   milk  pop   water water water pop   milk  water water water pop  
##  [49] pop   water milk  pop   pop   water water pop   milk  pop   pop   water
##  [61] water water water water water milk  pop   pop   pop   water water water
##  [73] pop   water pop   pop   water pop   pop   milk  water pop   water water
##  [85] milk  pop   water water pop   water water water milk  water pop   water
##  [97] pop   pop   pop   water water pop   water pop   milk  milk  water water
## [109] water water water pop   water milk  milk  milk  water milk  pop   water
## [121] pop   pop   pop   pop   water water water water water water milk  water
## [133] pop   milk  water water water water water &lt;NA&gt;  pop   water water pop  
## [145] milk  milk  water water pop   water water water pop   water &lt;NA&gt;  water
## [157] water water water water milk  milk  water milk  water water milk  water
## [169] pop   pop   pop   water pop   pop   water water milk  milk  water water
## [181] water pop   pop   water water pop   pop   water water milk  water water
## [193] milk  &lt;NA&gt;  water pop   milk  pop   milk  water water water water water
## [205] water pop   pop   water milk  water milk  water milk  water milk  water
## [217] milk  water pop   water water milk  water water pop   milk  milk  water
## [229] milk  water pop   pop   pop   water water milk  pop   milk  water milk 
## [241] water water pop   water water water pop   pop   water water pop   water
## [253] water milk  water pop   water pop   milk  milk  pop   pop   water water
## [265] water pop   pop   milk  water water water water milk  milk  water water
## [277] milk  milk  milk  pop   water water &lt;NA&gt;  water water water pop   milk 
## [289] water water pop   water water milk  pop   milk  milk  water water water
## [301] pop   water water &lt;NA&gt;  water water water water water pop   water water
## [313] water water pop   water water water milk  milk  pop   water water water
## [325] water water pop   pop   milk  milk  water water pop   pop   pop   pop  
## [337] water milk  water water pop   milk  pop   water water water pop   water
## [349] water water water water water &lt;NA&gt;  pop   pop   water milk  water water
## [361] milk  water water pop   water water water water water water pop   water
## [373] water milk  water water milk  milk  milk  water water water water pop  
## [385] water water pop   water pop   milk  pop   water water &lt;NA&gt;  water water
## [397] water water milk  water pop   milk  water water water water water milk 
## [409] pop   pop   pop   water pop   milk  water water milk  milk  pop   water
## [421] milk  water pop   milk  water water water water pop   water pop   pop  
## [433] pop   milk  pop   water milk  pop   water pop   pop   pop   water water
## [445] water water water water pop   milk  water water water pop   milk  milk 
## [457] pop   pop   water water milk  water milk  pop   water water water water
## [469] pop   water milk  water water water water water milk  milk  water water
## [481] pop   water water milk  water milk  water pop   pop   water water pop  
## [493] pop   pop   milk  water water pop   water water water water pop   water
## [505] pop   milk  water &lt;NA&gt;  milk  water pop   water water milk  water water
## [517] water water water milk  water water pop   water pop   water milk  milk 
## [529] milk  milk  pop   water pop   milk  &lt;NA&gt;  milk  pop   water water pop  
## [541] milk  pop   water milk  water pop   water pop   water pop   water water
## [553] pop   milk  water water water water &lt;NA&gt;  water water pop   pop   milk 
## [565] water milk  pop   pop   water water water pop   pop   pop   pop   water
## [577] water water water water pop   pop   water pop   water water water water
## [589] milk  water water water water pop   pop   water water water water water
## [601] water water pop   water water &lt;NA&gt;  milk  pop   water water water pop  
## [613] water pop   water pop   water water pop   pop   water pop   water milk 
## [625] water pop   pop   pop   water milk  pop   water pop   water water milk 
## [637] water water water water water water water pop   pop   pop   pop   water
## [649] pop   water milk  water water pop   pop   pop   water
## Levels: milk pop water</code></pre>
<p>Some students left that response blank and therefore the response is coded with the missing-value indicator</p>
<p>The variable type depends on the question asked. For example, answers given to the question of student height result in a numeric variable, answers given to the question about drink preference result in a character (or factor) variable</p>
<p>For integer, character, and factor variables you summarize the set of responses with the <code>table()</code> function</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="tuesday-january-17-2023.html#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>Drink)</span></code></pre></div>
<pre><code>## 
##  milk   pop water 
##   113   178   355</code></pre>
<p>There are 113 students who prefer milk, 178 prefer soda, and 355 prefer water</p>
<p>Here you use the<code>plot()</code> method to make a draft plot of this table</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="tuesday-january-17-2023.html#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> df<span class="sc">$</span>Drink)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<p>Notice that the sum of the responses is 646, which is less than the total number of students (657).</p>
<p>Students who left that question blank are ignored in the <code>table()</code> function. To include the missing values you add the argument <code>useNA = "ifany"</code> to the <code>table()</code> function.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="tuesday-january-17-2023.html#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>Drink, </span>
<span id="cb96-2"><a href="tuesday-january-17-2023.html#cb96-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">useNA =</span> <span class="st">&quot;ifany&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  milk   pop water  &lt;NA&gt; 
##   113   178   355    11</code></pre>
<p>Note: When you want code executed directly within the text you separate the code using single back ticks. This is useful when you write reports that need periodic updates when new data becomes available. Instead if you hard code the values in the text then you need to search the document for these values during each update of the report</p>
<p>Suppose you are interested in examining how long students reported sleeping during the night. This was not asked directly. You compute it from the <code>ToSleep</code> and <code>WakeUp</code> times columns. You assign the result of the difference to a column we call <code>SleepHrs</code></p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="tuesday-january-17-2023.html#cb98-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>SleepHrs <span class="ot">&lt;-</span> df<span class="sc">$</span>WakeUp <span class="sc">-</span> df<span class="sc">$</span>ToSleep</span>
<span id="cb98-2"><a href="tuesday-january-17-2023.html#cb98-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code></pre></div>
<pre><code>##   Student Height Gender Shoes Number Dvds ToSleep WakeUp Haircut  Job Drink
## 1       1     67 female    10      5   10    -2.5    5.5      60 30.0 water
## 2       2     64 female    20      7    5     1.5    8.0       0 20.0   pop
## 3       3     61 female    12      2    6    -1.5    7.5      48  0.0  milk
## 4       4     61 female     3      6   40     2.0    8.5      10  0.0 water
## 5       5     70   male     4      5    6     0.0    9.0      15 17.5   pop
## 6       6     63 female    NA      3    5     1.0    8.5      25  0.0 water
##   SleepHrs
## 1      8.0
## 2      6.5
## 3      9.0
## 4      6.5
## 5      9.0
## 6      7.5</code></pre>
<p>Now you have a new numeric variable in the data frame called <code>SleepHrs</code></p>
<p>You can’t table numeric variables, but the <code>summary()</code> method prints a set of summary statistics for the set of values</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="tuesday-january-17-2023.html#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df<span class="sc">$</span>SleepHrs)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   2.500   6.500   7.500   7.385   8.500  12.500       4</code></pre>
<p>The average number of hours slept is 7.4 with a maximum of 12.5 and a minimum of 2.5. There are four students that did not answer either when they went to sleep or when they woke up questions</p>
<p>You use the <code>hist()</code> function to plot a histogram of sleep hours. The function takes as input a vector of values</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="tuesday-january-17-2023.html#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(df<span class="sc">$</span>SleepHrs)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
<p>The function divides the number of sleep hours into one-hour bins and counts the number of students whose reported sleep hours falls into each bin. For example based on when they said they went to sleep and when the said they woke up, about 100 students slept between five and six hours the night before the survey</p>
<p>Is the amount of sleep for a student related to when they go to bed? If you place numeric variables on the x and y axes then you get a scatter plot</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="tuesday-january-17-2023.html#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> df<span class="sc">$</span>ToSleep,</span>
<span id="cb103-2"><a href="tuesday-january-17-2023.html#cb103-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">y =</span> df<span class="sc">$</span>SleepHrs)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-40-1.png" width="672" /></p>
<p>The <code>ToSleep</code> variable is centered on midnight so that -2 means a student went to sleep at 10p</p>
<p>You describe the decreasing relationship with a line through the points. The least-squares line is fit using the <code>lm()</code> function and the line is drawn on the existing plot with the <code>abline()</code> function applied to the linear regression object <code>model</code>.</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="tuesday-january-17-2023.html#cb104-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(SleepHrs <span class="sc">~</span> ToSleep, </span>
<span id="cb104-2"><a href="tuesday-january-17-2023.html#cb104-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> df)</span>
<span id="cb104-3"><a href="tuesday-january-17-2023.html#cb104-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-4"><a href="tuesday-january-17-2023.html#cb104-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> df<span class="sc">$</span>ToSleep,</span>
<span id="cb104-5"><a href="tuesday-january-17-2023.html#cb104-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">y =</span> df<span class="sc">$</span>SleepHrs)</span>
<span id="cb104-6"><a href="tuesday-january-17-2023.html#cb104-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(model)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
</div>
<div id="getting-data-into-r" class="section level2 unnumbered hasAnchor">
<h2>Getting data into R<a href="tuesday-january-17-2023.html#getting-data-into-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>You often start a research project by getting data into R. The file is on your computer or in the cloud. Secondary source data should be imported directly from repositories on the Web. When there is no direct link or API (application programming interface) to the repository, you need to first download the data</p>
<p>For example, consider the annually updated reports of tornadoes in the United States. The data repository is the Storm Prediction Center (SPC) <a href="https://www.spc.noaa.gov/wcm/index.html#data" class="uri">https://www.spc.noaa.gov/wcm/index.html#data</a></p>
<p>Here you are interested in the file <code>1950-2021_actual_tornadoes.csv</code>. First download the file from the site with the <code>download.file()</code> function specifying the location (<code>url =</code>) and a name you want the file to be called on your computer (<code>destfile =</code>)</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="tuesday-january-17-2023.html#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(<span class="at">url =</span> <span class="st">&quot;http://www.spc.noaa.gov/wcm/data/1950-2021_actual_tornadoes.csv&quot;</span>,</span>
<span id="cb105-2"><a href="tuesday-january-17-2023.html#cb105-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">destfile =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;Tornadoes.csv&quot;</span>))</span></code></pre></div>
<p>A file called <code>Tornadoes.csv</code> is now be located in the directory <code>data</code>. Click on the <em>Files</em> tab in the lower-right panel, then select the <code>data</code> folder</p>
<p>Next you read (import) the file as a data frame using the <code>readr::read_csv()</code> function from the {tidyverse} group of packages.</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="tuesday-january-17-2023.html#cb106-1" aria-hidden="true" tabindex="-1"></a>Torn.df <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="at">file =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;Tornadoes.csv&quot;</span>))</span></code></pre></div>
<pre><code>## Rows: 67558 Columns: 29
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr   (4): mo, dy, st, stf
## dbl  (23): om, yr, tz, stn, mag, inj, fat, loss, closs, slat, slon, elat, el...
## date  (1): date
## time  (1): time
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<p>You preview the data frame using the <code>head()</code> function</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="tuesday-january-17-2023.html#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Torn.df)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 29
##      om    yr mo    dy    date       time      tz st    stf     stn   mag   inj
##   &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;date&gt;     &lt;time&gt; &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1   192  1950 10    01    1950-10-01 21:00      3 OK    40       23     1     0
## 2   193  1950 10    09    1950-10-09 02:15      3 NC    37        9     3     3
## 3   195  1950 11    20    1950-11-20 02:20      3 KY    21        1     2     0
## 4   196  1950 11    20    1950-11-20 04:00      3 KY    21        2     1     0
## 5   197  1950 11    20    1950-11-20 07:30      3 MS    28       14     1     3
## 6   194  1950 11    04    1950-11-04 17:00      3 PA    42        5     3     1
## # … with 17 more variables: fat &lt;dbl&gt;, loss &lt;dbl&gt;, closs &lt;dbl&gt;, slat &lt;dbl&gt;,
## #   slon &lt;dbl&gt;, elat &lt;dbl&gt;, elon &lt;dbl&gt;, len &lt;dbl&gt;, wid &lt;dbl&gt;, ns &lt;dbl&gt;,
## #   sn &lt;dbl&gt;, sg &lt;dbl&gt;, f1 &lt;dbl&gt;, f2 &lt;dbl&gt;, f3 &lt;dbl&gt;, f4 &lt;dbl&gt;, fc &lt;dbl&gt;</code></pre>
<p>Each row is a unique tornado report. Observations for each report include variables like the day and time, the state (<code>st</code>), the maximum EF rating (<code>mag</code>), the number of injuries (<code>inj</code>), the number of fatalities (<code>fat</code>), estimated property losses (<code>loss</code>), estimated crop losses (<code>closs</code>), start and end locations in decimal degrees longitude and latitude, length of the damage path in miles (<code>len</code>), width of the damage in yards (<code>wid</code>)</p>
<p>The total number of tornado reports in the data set is returned using the <code>nrow()</code> function</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="tuesday-january-17-2023.html#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(Torn.df)</span></code></pre></div>
<pre><code>## [1] 67558</code></pre>
<p>To create a subset of the data frame that contains only tornadoes in years (<code>yr</code>) since 2001, you include the logical operator <code>yr &gt;= 2001</code> inside the subset operator (<code>[]</code>). The logical operator is placed in front of the comma since you want all <em>rows</em> where the result of the operator returns a value <code>TRUE</code>. After the column is left blank since you want all the variables</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="tuesday-january-17-2023.html#cb112-1" aria-hidden="true" tabindex="-1"></a>Torn2.df <span class="ot">&lt;-</span> Torn.df[Torn.df<span class="sc">$</span>yr <span class="sc">&gt;=</span> <span class="dv">2001</span>, ]</span></code></pre></div>
<p>You see that there are fewer rows (tornado reports) in this new data frame assigned the object name <code>Torn2.df</code>.</p>
<p>You subset again, keeping only tornadoes with EF ratings (<code>mag</code> variable) greater than zero. Here you <em>recycle</em> the name <code>Torn2.df</code></p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="tuesday-january-17-2023.html#cb113-1" aria-hidden="true" tabindex="-1"></a>Torn2.df <span class="ot">&lt;-</span> Torn2.df[Torn2.df<span class="sc">$</span>mag <span class="sc">&gt;</span> <span class="dv">0</span>, ]</span></code></pre></div>
<p>Now you compute the correlation between EF rating (<code>mag</code>) and path length (<code>len</code>) with the <code>cor()</code> function. The first argument is the vector of EF ratings and the second argument is the vector of path lengths</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="tuesday-january-17-2023.html#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(Torn2.df<span class="sc">$</span>mag, Torn2.df<span class="sc">$</span>len)</span></code></pre></div>
<pre><code>## [1] 0.4868764</code></pre>
<p>Path length is recorded in miles and path width in yards and the EF damage rating variable <code>mag</code> is numeric. Here you convert path length to kilometers, path width to meters, and the EF rating to a factor and include these changes as new columns in the data frame.</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="tuesday-january-17-2023.html#cb116-1" aria-hidden="true" tabindex="-1"></a>Torn2.df<span class="sc">$</span>Length <span class="ot">&lt;-</span> Torn2.df<span class="sc">$</span>len <span class="sc">*</span> <span class="fl">1609.34</span></span>
<span id="cb116-2"><a href="tuesday-january-17-2023.html#cb116-2" aria-hidden="true" tabindex="-1"></a>Torn2.df<span class="sc">$</span>Width <span class="ot">&lt;-</span> Torn2.df<span class="sc">$</span>wid <span class="sc">*</span> .<span class="dv">9144</span></span>
<span id="cb116-3"><a href="tuesday-january-17-2023.html#cb116-3" aria-hidden="true" tabindex="-1"></a>Torn2.df<span class="sc">$</span>EF <span class="ot">&lt;-</span> <span class="fu">factor</span>(Torn2.df<span class="sc">$</span>mag)</span></code></pre></div>
<p>Create side-by-side box plots of path length (in kilometers) by EF rating.</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="tuesday-january-17-2023.html#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> Torn2.df<span class="sc">$</span>EF, </span>
<span id="cb117-2"><a href="tuesday-january-17-2023.html#cb117-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">y =</span> Torn2.df<span class="sc">$</span>Length<span class="sc">/</span><span class="dv">1000</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-50-1.png" width="672" /></p>
<p>Another example: Annual U.S. hurricane counts</p>
<p>Here you import the data directly from the Web by specifying the URL as a character string using the <code>file =</code> argument</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="tuesday-january-17-2023.html#cb118-1" aria-hidden="true" tabindex="-1"></a>loc <span class="ot">&lt;-</span> <span class="st">&quot;http://myweb.fsu.edu/jelsner/temp/data/US.txt&quot;</span></span>
<span id="cb118-2"><a href="tuesday-january-17-2023.html#cb118-2" aria-hidden="true" tabindex="-1"></a>USHur.df <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_table</span>(<span class="at">file =</span> loc)</span></code></pre></div>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   Year = col_double(),
##   All = col_double(),
##   MUS = col_double(),
##   G = col_double(),
##   FL = col_double(),
##   E = col_double()
## )</code></pre>
<p>The <code>dim()</code> function returns the size of the data frame defined as the number of rows and the number of columns</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="tuesday-january-17-2023.html#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(USHur.df)</span></code></pre></div>
<pre><code>## [1] 166   6</code></pre>
<p>There are 166 rows and 6 columns in the data frame. Each row is a year and the columns include <code>Year</code>, number of hurricanes (<code>All</code>), number of major hurricanes (<code>MUS</code>), number of Gulf coast hurricanes (<code>G</code>), number of Florida hurricanes (<code>FL</code>), and number of East coast hurricanes (<code>E</code>) in that order</p>
<p>To get a glimpse of the data values you list the first six lines of the data frame using the <code>head()</code> function</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="tuesday-january-17-2023.html#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(USHur.df)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 6
##    Year   All   MUS     G    FL     E
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  1851     1     1     0     1     0
## 2  1852     3     1     1     2     0
## 3  1853     0     0     0     0     0
## 4  1854     2     1     1     0     1
## 5  1855     1     1     1     0     0
## 6  1856     2     1     1     1     0</code></pre>
<p>The distribution of Florida hurricane counts by year is obtained using the <code>table()</code> function and specifying the <code>FL</code> column with <code>df$FL</code></p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="tuesday-january-17-2023.html#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(USHur.df<span class="sc">$</span>FL)</span></code></pre></div>
<pre><code>## 
##  0  1  2  3  4 
## 93 43 24  5  1</code></pre>
<p>There are 93 years without a FL hurricane, 43 years with exactly one hurricane, 24 years with two hurricanes, and so on</p>
<p>Another example: Statewide average rainfall in Florida. Work through it on your own</p>
<p>The data are monthly statewide average rainfall (in inches) for Florida starting in 1895. The data were obtained from <a href="http://www.esrl.noaa.gov/psd/data/timeseries/" class="uri">http://www.esrl.noaa.gov/psd/data/timeseries/</a></p>
<p>I put values into a text editor and then uploaded the file to <a href="http://myweb.fsu.edu/jelsner/temp/data/FLprecip.txt" class="uri">http://myweb.fsu.edu/jelsner/temp/data/FLprecip.txt</a></p>
<p>You get the data into R with the <code>readr::read_table()</code> function. You assign the data object the name <code>FLp.df</code>. You type the name of the object to see that it is a tabled data frame (tibble) with 117 rows and 13 columns</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="tuesday-january-17-2023.html#cb126-1" aria-hidden="true" tabindex="-1"></a>loc <span class="ot">&lt;-</span> <span class="st">&quot;http://myweb.fsu.edu/jelsner/temp/data/FLprecip.txt&quot;</span></span>
<span id="cb126-2"><a href="tuesday-january-17-2023.html#cb126-2" aria-hidden="true" tabindex="-1"></a>FLp.df <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_table</span>(<span class="at">file =</span> loc)</span></code></pre></div>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   Year = col_double(),
##   Jan = col_double(),
##   Feb = col_double(),
##   Mar = col_double(),
##   Apr = col_double(),
##   May = col_double(),
##   Jun = col_double(),
##   Jul = col_double(),
##   Aug = col_double(),
##   Sep = col_double(),
##   Oct = col_double(),
##   Nov = col_double(),
##   Dec = col_double()
## )</code></pre>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="tuesday-january-17-2023.html#cb128-1" aria-hidden="true" tabindex="-1"></a>FLp.df</span></code></pre></div>
<pre><code>## # A tibble: 117 × 13
##     Year   Jan   Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov   Dec
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1  1895 3.28   3.24  2.50 4.53   4.25  4.5   7.45  6.10  4.67  3.09 2.65   1.59
##  2  1896 3.93   3.02  2.57 0.498  2.7  11.2   8.22  5.89  4.35  2.96 3.52   2.07
##  3  1897 1.84   6     2.12 4.39   2.28  5.22  7.21  6.83 11.1   4.10 1.75   2.68
##  4  1898 0.704  2.01  1.26 1.32   1.51  3.29  8.95 13.1   5.23  5.88 2.19   3.89
##  5  1899 4.52   5.92  1.90 3.40   1.11  5.80  9.26  6.71  5.13  5.88 0.751  1.94
##  6  1900 3.21   4.37  6.8  4.32   3.89  9.99  7.50  4.49  4.93  5.23 1.22   4.29
##  7  1901 2.34   4.21  5.37 2.14   4.15 10.4   6.42 10.9   8.33  1.71 0.841  2.49
##  8  1902 0.633  4.81  4.29 1.38   2.36  6.22  5.24  4.80  9.54  5.21 3.02   3.52
##  9  1903 5.06   5.58  5.45 0.429  4.74  7.01  6.63  6.96  7.47  1.75 2.7    1.70
## 10  1904 4.96   3.02  1.59 1.66   2.49  6.59  6.27  7.53  4.5   4.41 2.87   1.84
## # … with 107 more rows</code></pre>
<p>The first column is the year and the next 12 columns are the months.</p>
<p>What was the statewide rainfall during June of 1900?</p>
<p>What happens when you check the column (vector) labeled <code>Year</code> to see what elements are equal to 1900?</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="tuesday-january-17-2023.html#cb130-1" aria-hidden="true" tabindex="-1"></a>FLp.df<span class="sc">$</span>Year <span class="sc">==</span> <span class="dv">1900</span></span></code></pre></div>
<pre><code>##   [1] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE
##  [13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [25] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [37] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [49] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [61] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [73] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [85] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [97] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [109] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE</code></pre>
<p>Returns a vector with one element equal to <code>TRUE</code>.</p>
<p>What happens when you use this vector to select the vector of June rainfall values?</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="tuesday-january-17-2023.html#cb132-1" aria-hidden="true" tabindex="-1"></a>FLp.df<span class="sc">$</span>Jun[FLp.df<span class="sc">$</span>Year <span class="sc">==</span> <span class="dv">1900</span>]</span></code></pre></div>
<pre><code>## [1] 9.993</code></pre>
<p>What year had the wettest March?</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="tuesday-january-17-2023.html#cb134-1" aria-hidden="true" tabindex="-1"></a>FLp.df<span class="sc">$</span>Mar</span></code></pre></div>
<pre><code>##   [1] 2.499 2.570 2.125 1.259 1.898 6.800 5.370 4.291 5.451 1.591 3.849 3.191
##  [13] 0.562 0.779 2.792 1.899 2.180 3.932 5.553 1.528 2.598 0.889 2.027 2.497
##  [25] 5.409 1.388 1.981 2.422 2.181 5.969 1.858 4.329 2.400 4.392 3.374 7.449
##  [37] 5.312 3.659 3.898 3.363 0.960 3.103 4.257 1.764 1.407 3.515 3.918 6.123
##  [49] 4.441 5.685 0.637 4.152 7.133 6.822 2.043 4.018 3.293 3.852 3.090 2.404
##  [61] 1.643 1.325 4.601 6.416 8.701 6.357 2.489 3.808 1.707 3.237 4.042 1.826
##  [73] 1.193 1.569 5.991 8.388 2.142 4.494 5.516 2.525 2.353 2.553 2.002 4.226
##  [85] 2.143 5.043 3.176 5.379 7.213 4.710 2.537 4.297 8.443 5.101 3.349 2.672
##  [97] 7.097 3.299 5.097 3.839 3.395 7.575 2.754 6.042 1.790 3.207 6.824 2.700
## [109] 6.642 0.994 6.027 0.496 1.213 3.568 2.662 5.995 4.063</code></pre>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="tuesday-january-17-2023.html#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(FLp.df<span class="sc">$</span>Mar)</span></code></pre></div>
<pre><code>## [1] 8.701</code></pre>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="tuesday-january-17-2023.html#cb138-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which.max</span>(FLp.df<span class="sc">$</span>Mar)</span></code></pre></div>
<pre><code>## [1] 65</code></pre>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="tuesday-january-17-2023.html#cb140-1" aria-hidden="true" tabindex="-1"></a>FLp.df<span class="sc">$</span>Year[<span class="fu">which.max</span>(FLp.df<span class="sc">$</span>Mar)]</span></code></pre></div>
<pre><code>## [1] 1959</code></pre>
<p>What month during 1965 was the wettest? How wet was it?</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="tuesday-january-17-2023.html#cb142-1" aria-hidden="true" tabindex="-1"></a>FLp.df<span class="sc">$</span>Year <span class="sc">==</span> <span class="dv">1965</span></span></code></pre></div>
<pre><code>##   [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [25] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [37] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [49] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [61] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE
##  [73] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [85] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [97] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [109] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE</code></pre>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="tuesday-january-17-2023.html#cb144-1" aria-hidden="true" tabindex="-1"></a>FLp.df[FLp.df<span class="sc">$</span>Year <span class="sc">==</span> <span class="dv">1965</span>, ]</span></code></pre></div>
<pre><code>## # A tibble: 1 × 13
##    Year   Jan   Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov   Dec
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  1965  1.80  4.58  4.04  2.54  1.08  10.0  8.54  7.14  6.69  4.66  1.58  2.76</code></pre>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="tuesday-january-17-2023.html#cb146-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which.max</span>(FLp.df[FLp.df<span class="sc">$</span>Year <span class="sc">==</span> <span class="dv">1965</span>, <span class="dv">2</span><span class="sc">:</span><span class="dv">12</span>])</span></code></pre></div>
<pre><code>## Jun 
##   6</code></pre>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="tuesday-january-17-2023.html#cb148-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which.max</span>(FLp.df[FLp.df<span class="sc">$</span>Year <span class="sc">==</span> <span class="dv">1965</span>, <span class="dv">2</span><span class="sc">:</span><span class="dv">12</span>])</span></code></pre></div>
<pre><code>## Jun 
##   6</code></pre>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="tuesday-january-17-2023.html#cb150-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(FLp.df[FLp.df<span class="sc">$</span>Year <span class="sc">==</span> <span class="dv">1965</span>, <span class="dv">2</span><span class="sc">:</span><span class="dv">12</span>])</span></code></pre></div>
<pre><code>## [1] 10.032</code></pre>
</div>
<div id="working-with-data-frames-using-functions-from-dplyr" class="section level2 unnumbered hasAnchor">
<h2>Working with data frames using functions from {dplyr}<a href="tuesday-january-17-2023.html#working-with-data-frames-using-functions-from-dplyr" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The functions in the {dplyr} package (part of the tidyverse set of packages) simplify working with data frames. The functions work only on data frames</p>
<p>Function names are English language <em>verbs</em> so they are easier to remember. The verbs help you translate thought into code</p>
<p>Here we consider some of verbs using the <code>airquality</code> data frame. The data frame contains air quality measurements taken in New York City between May and September 1973 (<code>?airquality</code>) at time when pollution levels in the city were at an all time high</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="tuesday-january-17-2023.html#cb152-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(airquality)</span></code></pre></div>
<pre><code>## [1] 153   6</code></pre>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="tuesday-january-17-2023.html#cb154-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airquality)</span></code></pre></div>
<pre><code>##   Ozone Solar.R Wind Temp Month Day
## 1    41     190  7.4   67     5   1
## 2    36     118  8.0   72     5   2
## 3    12     149 12.6   74     5   3
## 4    18     313 11.5   62     5   4
## 5    NA      NA 14.3   56     5   5
## 6    28      NA 14.9   66     5   6</code></pre>
<p>The columns include <code>Ozone</code> (ozone concentration in ppb), <code>Solar.R</code> (solar radiation in langleys), <code>Wind</code> (wind speed in mph), <code>Temp</code> (air temperature in degrees F), <code>Month</code>, and <code>Day</code></p>
<p>You get summary statistics on the values in each column with the <code>summary()</code> method</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="tuesday-january-17-2023.html#cb156-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(airquality)</span></code></pre></div>
<pre><code>##      Ozone           Solar.R           Wind             Temp      
##  Min.   :  1.00   Min.   :  7.0   Min.   : 1.700   Min.   :56.00  
##  1st Qu.: 18.00   1st Qu.:115.8   1st Qu.: 7.400   1st Qu.:72.00  
##  Median : 31.50   Median :205.0   Median : 9.700   Median :79.00  
##  Mean   : 42.13   Mean   :185.9   Mean   : 9.958   Mean   :77.88  
##  3rd Qu.: 63.25   3rd Qu.:258.8   3rd Qu.:11.500   3rd Qu.:85.00  
##  Max.   :168.00   Max.   :334.0   Max.   :20.700   Max.   :97.00  
##  NA&#39;s   :37       NA&#39;s   :7                                       
##      Month            Day      
##  Min.   :5.000   Min.   : 1.0  
##  1st Qu.:6.000   1st Qu.: 8.0  
##  Median :7.000   Median :16.0  
##  Mean   :6.993   Mean   :15.8  
##  3rd Qu.:8.000   3rd Qu.:23.0  
##  Max.   :9.000   Max.   :31.0  
## </code></pre>
<p>Note that columns that have missing values are tabulated. For example, there are 37 missing ozone measurements and 7 missing radiation measurements</p>
<p>Importantly for making your code more human readable you can apply the <code>summary()</code> function on the <code>airquality</code> data frame using the pipe operator (<code>|&gt;</code>)</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="tuesday-january-17-2023.html#cb158-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span> <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>##      Ozone           Solar.R           Wind             Temp      
##  Min.   :  1.00   Min.   :  7.0   Min.   : 1.700   Min.   :56.00  
##  1st Qu.: 18.00   1st Qu.:115.8   1st Qu.: 7.400   1st Qu.:72.00  
##  Median : 31.50   Median :205.0   Median : 9.700   Median :79.00  
##  Mean   : 42.13   Mean   :185.9   Mean   : 9.958   Mean   :77.88  
##  3rd Qu.: 63.25   3rd Qu.:258.8   3rd Qu.:11.500   3rd Qu.:85.00  
##  Max.   :168.00   Max.   :334.0   Max.   :20.700   Max.   :97.00  
##  NA&#39;s   :37       NA&#39;s   :7                                       
##      Month            Day      
##  Min.   :5.000   Min.   : 1.0  
##  1st Qu.:6.000   1st Qu.: 8.0  
##  Median :7.000   Median :16.0  
##  Mean   :6.993   Mean   :15.8  
##  3rd Qu.:8.000   3rd Qu.:23.0  
##  Max.   :9.000   Max.   :31.0  
## </code></pre>
<p>You read the pipe as THEN. “take the <code>airquality</code> data frame THEN summarize the columns”</p>
<p>The pipe operator allows you to string together functions that when read by a human makes it easy to understand what is being done</p>
<p>Think of it this way: suppose the object of interest is called <code>me</code> and there is a function called <code>wake_up()</code>. I could apply this function called <code>wake_up()</code> in two ways</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="tuesday-january-17-2023.html#cb160-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wake_up</span>(me)  <span class="co"># classic</span></span>
<span id="cb160-2"><a href="tuesday-january-17-2023.html#cb160-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb160-3"><a href="tuesday-january-17-2023.html#cb160-3" aria-hidden="true" tabindex="-1"></a>me <span class="sc">|&gt;</span> <span class="fu">wake_up</span>()  <span class="co"># tidyverse</span></span></code></pre></div>
<p>The second way involves more typing but it is easier to read (the subject comes before the predicate like simple English grammar) and thus easier to interpret. This becomes clear when stringing many functions together</p>
<p>Continuing, what happens to the result of <code>me</code> after the function <code>wake_up()</code> has been applied? I <code>get_out_of_bed()</code> and then <code>get_dressed()</code></p>
<p>Again, you can apply these functions in two ways</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="tuesday-january-17-2023.html#cb161-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_dressed</span>(<span class="fu">get_out_of_bed</span>(<span class="fu">wake_up</span>(me))) <span class="co"># classic</span></span>
<span id="cb161-2"><a href="tuesday-january-17-2023.html#cb161-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb161-3"><a href="tuesday-january-17-2023.html#cb161-3" aria-hidden="true" tabindex="-1"></a>me <span class="sc">|&gt;</span> <span class="co"># tidyverse</span></span>
<span id="cb161-4"><a href="tuesday-january-17-2023.html#cb161-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">wake_up</span>() <span class="sc">|&gt;</span></span>
<span id="cb161-5"><a href="tuesday-january-17-2023.html#cb161-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_out_of_bed</span>() <span class="sc">|&gt;</span></span>
<span id="cb161-6"><a href="tuesday-january-17-2023.html#cb161-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_dressed</span>()</span></code></pre></div>
<p>The order of the functions often matters. I can’t get dressed before I wake up but I could get dressed without getting out of bed</p>
<p>Note how I format the code. Each line is gets only one verb and each line ends with the pipe (except the last one). This makes it easy to read. Continuing</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="tuesday-january-17-2023.html#cb162-1" aria-hidden="true" tabindex="-1"></a>me <span class="sc">|&gt;</span></span>
<span id="cb162-2"><a href="tuesday-january-17-2023.html#cb162-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">wake_up</span>() <span class="sc">|&gt;</span></span>
<span id="cb162-3"><a href="tuesday-january-17-2023.html#cb162-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_out_of_bed</span>() <span class="sc">|&gt;</span></span>
<span id="cb162-4"><a href="tuesday-january-17-2023.html#cb162-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_dressed</span>() <span class="sc">|&gt;</span></span>
<span id="cb162-5"><a href="tuesday-january-17-2023.html#cb162-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">make_coffee</span>() <span class="sc">|&gt;</span></span>
<span id="cb162-6"><a href="tuesday-january-17-2023.html#cb162-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drink_coffee</span>() <span class="sc">|&gt;</span></span>
<span id="cb162-7"><a href="tuesday-january-17-2023.html#cb162-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">leave_house</span>()</span></code></pre></div>
<p>Which is much better in terms of ‘readability’ then <code>leave_house(drink_coffee(make_coffee(get_dressed(get_out_of_bed(wake_up(me))))))</code>.</p>
<p>Now lets look at some of the commonly used verbs and to see how to apply them to a data frame</p>
<p>The function <code>select()</code> chooses variables by name. For example, choose the month (<code>Month</code>), day (<code>Day</code>), and temperature (<code>Temp</code>) columns.</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="tuesday-january-17-2023.html#cb163-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb163-2"><a href="tuesday-january-17-2023.html#cb163-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Month, Day, Temp)</span></code></pre></div>
<pre><code>##     Month Day Temp
## 1       5   1   67
## 2       5   2   72
## 3       5   3   74
## 4       5   4   62
## 5       5   5   56
## 6       5   6   66
## 7       5   7   65
## 8       5   8   59
## 9       5   9   61
## 10      5  10   69
## 11      5  11   74
## 12      5  12   69
## 13      5  13   66
## 14      5  14   68
## 15      5  15   58
## 16      5  16   64
## 17      5  17   66
## 18      5  18   57
## 19      5  19   68
## 20      5  20   62
## 21      5  21   59
## 22      5  22   73
## 23      5  23   61
## 24      5  24   61
## 25      5  25   57
## 26      5  26   58
## 27      5  27   57
## 28      5  28   67
## 29      5  29   81
## 30      5  30   79
## 31      5  31   76
## 32      6   1   78
## 33      6   2   74
## 34      6   3   67
## 35      6   4   84
## 36      6   5   85
## 37      6   6   79
## 38      6   7   82
## 39      6   8   87
## 40      6   9   90
## 41      6  10   87
## 42      6  11   93
## 43      6  12   92
## 44      6  13   82
## 45      6  14   80
## 46      6  15   79
## 47      6  16   77
## 48      6  17   72
## 49      6  18   65
## 50      6  19   73
## 51      6  20   76
## 52      6  21   77
## 53      6  22   76
## 54      6  23   76
## 55      6  24   76
## 56      6  25   75
## 57      6  26   78
## 58      6  27   73
## 59      6  28   80
## 60      6  29   77
## 61      6  30   83
## 62      7   1   84
## 63      7   2   85
## 64      7   3   81
## 65      7   4   84
## 66      7   5   83
## 67      7   6   83
## 68      7   7   88
## 69      7   8   92
## 70      7   9   92
## 71      7  10   89
## 72      7  11   82
## 73      7  12   73
## 74      7  13   81
## 75      7  14   91
## 76      7  15   80
## 77      7  16   81
## 78      7  17   82
## 79      7  18   84
## 80      7  19   87
## 81      7  20   85
## 82      7  21   74
## 83      7  22   81
## 84      7  23   82
## 85      7  24   86
## 86      7  25   85
## 87      7  26   82
## 88      7  27   86
## 89      7  28   88
## 90      7  29   86
## 91      7  30   83
## 92      7  31   81
## 93      8   1   81
## 94      8   2   81
## 95      8   3   82
## 96      8   4   86
## 97      8   5   85
## 98      8   6   87
## 99      8   7   89
## 100     8   8   90
## 101     8   9   90
## 102     8  10   92
## 103     8  11   86
## 104     8  12   86
## 105     8  13   82
## 106     8  14   80
## 107     8  15   79
## 108     8  16   77
## 109     8  17   79
## 110     8  18   76
## 111     8  19   78
## 112     8  20   78
## 113     8  21   77
## 114     8  22   72
## 115     8  23   75
## 116     8  24   79
## 117     8  25   81
## 118     8  26   86
## 119     8  27   88
## 120     8  28   97
## 121     8  29   94
## 122     8  30   96
## 123     8  31   94
## 124     9   1   91
## 125     9   2   92
## 126     9   3   93
## 127     9   4   93
## 128     9   5   87
## 129     9   6   84
## 130     9   7   80
## 131     9   8   78
## 132     9   9   75
## 133     9  10   73
## 134     9  11   81
## 135     9  12   76
## 136     9  13   77
## 137     9  14   71
## 138     9  15   71
## 139     9  16   78
## 140     9  17   67
## 141     9  18   76
## 142     9  19   68
## 143     9  20   82
## 144     9  21   64
## 145     9  22   71
## 146     9  23   81
## 147     9  24   69
## 148     9  25   63
## 149     9  26   70
## 150     9  27   77
## 151     9  28   75
## 152     9  29   76
## 153     9  30   68</code></pre>
<p>The result is a data frame containing only the three columns with column names listed in the <code>select()</code> function.</p>
<p>Suppose you want a new data frame with only the temperature and ozone concentrations. You include an assignment operator (<code>&lt;-</code>) and an object name (here <code>df</code>).</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="tuesday-january-17-2023.html#cb165-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> airquality <span class="sc">|&gt;</span></span>
<span id="cb165-2"><a href="tuesday-january-17-2023.html#cb165-2" aria-hidden="true" tabindex="-1"></a>        dplyr<span class="sc">::</span><span class="fu">select</span>(Temp, Ozone)</span>
<span id="cb165-3"><a href="tuesday-january-17-2023.html#cb165-3" aria-hidden="true" tabindex="-1"></a>df</span></code></pre></div>
<pre><code>##     Temp Ozone
## 1     67    41
## 2     72    36
## 3     74    12
## 4     62    18
## 5     56    NA
## 6     66    28
## 7     65    23
## 8     59    19
## 9     61     8
## 10    69    NA
## 11    74     7
## 12    69    16
## 13    66    11
## 14    68    14
## 15    58    18
## 16    64    14
## 17    66    34
## 18    57     6
## 19    68    30
## 20    62    11
## 21    59     1
## 22    73    11
## 23    61     4
## 24    61    32
## 25    57    NA
## 26    58    NA
## 27    57    NA
## 28    67    23
## 29    81    45
## 30    79   115
## 31    76    37
## 32    78    NA
## 33    74    NA
## 34    67    NA
## 35    84    NA
## 36    85    NA
## 37    79    NA
## 38    82    29
## 39    87    NA
## 40    90    71
## 41    87    39
## 42    93    NA
## 43    92    NA
## 44    82    23
## 45    80    NA
## 46    79    NA
## 47    77    21
## 48    72    37
## 49    65    20
## 50    73    12
## 51    76    13
## 52    77    NA
## 53    76    NA
## 54    76    NA
## 55    76    NA
## 56    75    NA
## 57    78    NA
## 58    73    NA
## 59    80    NA
## 60    77    NA
## 61    83    NA
## 62    84   135
## 63    85    49
## 64    81    32
## 65    84    NA
## 66    83    64
## 67    83    40
## 68    88    77
## 69    92    97
## 70    92    97
## 71    89    85
## 72    82    NA
## 73    73    10
## 74    81    27
## 75    91    NA
## 76    80     7
## 77    81    48
## 78    82    35
## 79    84    61
## 80    87    79
## 81    85    63
## 82    74    16
## 83    81    NA
## 84    82    NA
## 85    86    80
## 86    85   108
## 87    82    20
## 88    86    52
## 89    88    82
## 90    86    50
## 91    83    64
## 92    81    59
## 93    81    39
## 94    81     9
## 95    82    16
## 96    86    78
## 97    85    35
## 98    87    66
## 99    89   122
## 100   90    89
## 101   90   110
## 102   92    NA
## 103   86    NA
## 104   86    44
## 105   82    28
## 106   80    65
## 107   79    NA
## 108   77    22
## 109   79    59
## 110   76    23
## 111   78    31
## 112   78    44
## 113   77    21
## 114   72     9
## 115   75    NA
## 116   79    45
## 117   81   168
## 118   86    73
## 119   88    NA
## 120   97    76
## 121   94   118
## 122   96    84
## 123   94    85
## 124   91    96
## 125   92    78
## 126   93    73
## 127   93    91
## 128   87    47
## 129   84    32
## 130   80    20
## 131   78    23
## 132   75    21
## 133   73    24
## 134   81    44
## 135   76    21
## 136   77    28
## 137   71     9
## 138   71    13
## 139   78    46
## 140   67    18
## 141   76    13
## 142   68    24
## 143   82    16
## 144   64    13
## 145   71    23
## 146   81    36
## 147   69     7
## 148   63    14
## 149   70    30
## 150   77    NA
## 151   75    14
## 152   76    18
## 153   68    20</code></pre>
<p>The verbs take data frames as input and return data frames</p>
<p>The function <code>filter()</code> chooses observations based on specific values. Suppose you want only the observations where the temperature is at or above 80 F</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="tuesday-january-17-2023.html#cb167-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb167-2"><a href="tuesday-january-17-2023.html#cb167-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(Temp <span class="sc">&gt;=</span> <span class="dv">80</span>)</span></code></pre></div>
<pre><code>##    Ozone Solar.R Wind Temp Month Day
## 1     45     252 14.9   81     5  29
## 2     NA     186  9.2   84     6   4
## 3     NA     220  8.6   85     6   5
## 4     29     127  9.7   82     6   7
## 5     NA     273  6.9   87     6   8
## 6     71     291 13.8   90     6   9
## 7     39     323 11.5   87     6  10
## 8     NA     259 10.9   93     6  11
## 9     NA     250  9.2   92     6  12
## 10    23     148  8.0   82     6  13
## 11    NA     332 13.8   80     6  14
## 12    NA      98 11.5   80     6  28
## 13    NA     138  8.0   83     6  30
## 14   135     269  4.1   84     7   1
## 15    49     248  9.2   85     7   2
## 16    32     236  9.2   81     7   3
## 17    NA     101 10.9   84     7   4
## 18    64     175  4.6   83     7   5
## 19    40     314 10.9   83     7   6
## 20    77     276  5.1   88     7   7
## 21    97     267  6.3   92     7   8
## 22    97     272  5.7   92     7   9
## 23    85     175  7.4   89     7  10
## 24    NA     139  8.6   82     7  11
## 25    27     175 14.9   81     7  13
## 26    NA     291 14.9   91     7  14
## 27     7      48 14.3   80     7  15
## 28    48     260  6.9   81     7  16
## 29    35     274 10.3   82     7  17
## 30    61     285  6.3   84     7  18
## 31    79     187  5.1   87     7  19
## 32    63     220 11.5   85     7  20
## 33    NA     258  9.7   81     7  22
## 34    NA     295 11.5   82     7  23
## 35    80     294  8.6   86     7  24
## 36   108     223  8.0   85     7  25
## 37    20      81  8.6   82     7  26
## 38    52      82 12.0   86     7  27
## 39    82     213  7.4   88     7  28
## 40    50     275  7.4   86     7  29
## 41    64     253  7.4   83     7  30
## 42    59     254  9.2   81     7  31
## 43    39      83  6.9   81     8   1
## 44     9      24 13.8   81     8   2
## 45    16      77  7.4   82     8   3
## 46    78      NA  6.9   86     8   4
## 47    35      NA  7.4   85     8   5
## 48    66      NA  4.6   87     8   6
## 49   122     255  4.0   89     8   7
## 50    89     229 10.3   90     8   8
## 51   110     207  8.0   90     8   9
## 52    NA     222  8.6   92     8  10
## 53    NA     137 11.5   86     8  11
## 54    44     192 11.5   86     8  12
## 55    28     273 11.5   82     8  13
## 56    65     157  9.7   80     8  14
## 57   168     238  3.4   81     8  25
## 58    73     215  8.0   86     8  26
## 59    NA     153  5.7   88     8  27
## 60    76     203  9.7   97     8  28
## 61   118     225  2.3   94     8  29
## 62    84     237  6.3   96     8  30
## 63    85     188  6.3   94     8  31
## 64    96     167  6.9   91     9   1
## 65    78     197  5.1   92     9   2
## 66    73     183  2.8   93     9   3
## 67    91     189  4.6   93     9   4
## 68    47      95  7.4   87     9   5
## 69    32      92 15.5   84     9   6
## 70    20     252 10.9   80     9   7
## 71    44     236 14.9   81     9  11
## 72    16     201  8.0   82     9  20
## 73    36     139 10.3   81     9  23</code></pre>
<p>The result is a data frame with the same 6 columns but now only 73 observations. Each of the observations has a temperature of at least 80 F</p>
<p>Suppose you want a new data frame keeping only observations when temperature is at least 80 F and when winds are less than 5 mph</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="tuesday-january-17-2023.html#cb169-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> airquality <span class="sc">|&gt;</span> </span>
<span id="cb169-2"><a href="tuesday-january-17-2023.html#cb169-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(Temp <span class="sc">&gt;=</span> <span class="dv">80</span> <span class="sc">&amp;</span> Wind <span class="sc">&lt;</span> <span class="dv">5</span>)</span>
<span id="cb169-3"><a href="tuesday-january-17-2023.html#cb169-3" aria-hidden="true" tabindex="-1"></a>df</span></code></pre></div>
<pre><code>##   Ozone Solar.R Wind Temp Month Day
## 1   135     269  4.1   84     7   1
## 2    64     175  4.6   83     7   5
## 3    66      NA  4.6   87     8   6
## 4   122     255  4.0   89     8   7
## 5   168     238  3.4   81     8  25
## 6   118     225  2.3   94     8  29
## 7    73     183  2.8   93     9   3
## 8    91     189  4.6   93     9   4</code></pre>
<p>The function <code>arrange()</code> orders the rows by values given in a particular column.</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="tuesday-january-17-2023.html#cb171-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb171-2"><a href="tuesday-january-17-2023.html#cb171-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">arrange</span>(Solar.R)</span></code></pre></div>
<pre><code>##     Ozone Solar.R Wind Temp Month Day
## 1      16       7  6.9   74     7  21
## 2       1       8  9.7   59     5  21
## 3      23      13 12.0   67     5  28
## 4      23      14  9.2   71     9  22
## 5       8      19 20.1   61     5   9
## 6      14      20 16.6   63     9  25
## 7       9      24 13.8   81     8   2
## 8       9      24 10.9   71     9  14
## 9       4      25  9.7   61     5  23
## 10     13      27 10.3   76     9  18
## 11     NA      31 14.9   77     6  29
## 12      9      36 14.3   72     8  22
## 13     20      37  9.2   65     6  18
## 14     11      44  9.7   62     5  20
## 15     NA      47 10.3   73     6  27
## 16      7      48 14.3   80     7  15
## 17      7      49 10.3   69     9  24
## 18     59      51  6.3   79     8  17
## 19     NA      59  1.7   76     6  22
## 20     NA      64 11.5   79     8  15
## 21     18      65 13.2   58     5  15
## 22     NA      66 16.6   57     5  25
## 23     22      71 10.3   77     8  16
## 24     16      77  7.4   82     8   3
## 25      6      78 18.4   57     5  18
## 26     20      81  8.6   82     7  26
## 27     52      82 12.0   86     7  27
## 28     39      83  6.9   81     8   1
## 29     NA      91  4.6   76     6  23
## 30     32      92 12.0   61     5  24
## 31     32      92 15.5   84     9   6
## 32     47      95  7.4   87     9   5
## 33     NA      98 11.5   80     6  28
## 34     19      99 13.8   59     5   8
## 35     NA     101 10.9   84     7   4
## 36     13     112 11.5   71     9  15
## 37     23     115  7.4   76     8  18
## 38     36     118  8.0   72     5   2
## 39     12     120 11.5   73     6  19
## 40     29     127  9.7   82     6   7
## 41     NA     127  8.0   78     6  26
## 42     18     131  8.0   76     9  29
## 43     NA     135  8.0   75     6  25
## 44     13     137 10.3   76     6  20
## 45     NA     137 11.5   86     8  11
## 46     NA     138  8.0   83     6  30
## 47     NA     139  8.6   82     7  11
## 48     36     139 10.3   81     9  23
## 49     NA     145 13.2   77     9  27
## 50     23     148  8.0   82     6  13
## 51     12     149 12.6   74     5   3
## 52     NA     150  6.3   77     6  21
## 53     NA     153  5.7   88     8  27
## 54     65     157  9.7   80     8  14
## 55     96     167  6.9   91     9   1
## 56     64     175  4.6   83     7   5
## 57     85     175  7.4   89     7  10
## 58     27     175 14.9   81     7  13
## 59     73     183  2.8   93     9   3
## 60     NA     186  9.2   84     6   4
## 61     79     187  5.1   87     7  19
## 62     85     188  6.3   94     8  31
## 63     91     189  4.6   93     9   4
## 64     41     190  7.4   67     5   1
## 65     44     190 10.3   78     8  20
## 66     21     191 14.9   77     6  16
## 67     14     191 14.3   75     9  28
## 68     44     192 11.5   86     8  12
## 69     30     193  6.9   70     9  26
## 70     NA     194  8.6   69     5  10
## 71     78     197  5.1   92     9   2
## 72     16     201  8.0   82     9  20
## 73     76     203  9.7   97     8  28
## 74    110     207  8.0   90     8   9
## 75     45     212  9.7   79     8  24
## 76     82     213  7.4   88     7  28
## 77     73     215  8.0   86     8  26
## 78     NA     220  8.6   85     6   5
## 79     63     220 11.5   85     7  20
## 80     23     220 10.3   78     9   8
## 81     NA     222  8.6   92     8  10
## 82    115     223  5.7   79     5  30
## 83    108     223  8.0   85     7  25
## 84     20     223 11.5   68     9  30
## 85     18     224 13.8   67     9  17
## 86    118     225  2.3   94     8  29
## 87     89     229 10.3   90     8   8
## 88     21     230 10.9   75     9   9
## 89     32     236  9.2   81     7   3
## 90     44     236 14.9   81     9  11
## 91     84     237  6.3   96     8  30
## 92     46     237  6.9   78     9  16
## 93    168     238  3.4   81     8  25
## 94     28     238  6.3   77     9  13
## 95     24     238 10.3   68     9  19
## 96     13     238 12.6   64     9  21
## 97     NA     242 16.1   67     6   3
## 98     31     244 10.9   78     8  19
## 99     49     248  9.2   85     7   2
## 100    NA     250  9.2   92     6  12
## 101    NA     250  6.3   76     6  24
## 102    45     252 14.9   81     5  29
## 103    20     252 10.9   80     9   7
## 104    64     253  7.4   83     7  30
## 105    59     254  9.2   81     7  31
## 106   122     255  4.0   89     8   7
## 107    NA     255 12.6   75     8  23
## 108    16     256  9.7   69     5  12
## 109    NA     258  9.7   81     7  22
## 110    NA     259 10.9   93     6  11
## 111    21     259 15.5   77     8  21
## 112    24     259  9.7   73     9  10
## 113    21     259 15.5   76     9  12
## 114    48     260  6.9   81     7  16
## 115    NA     264 14.3   79     6   6
## 116    10     264 14.3   73     7  12
## 117    NA     266 14.9   58     5  26
## 118    97     267  6.3   92     7   8
## 119   135     269  4.1   84     7   1
## 120    97     272  5.7   92     7   9
## 121    NA     273  6.9   87     6   8
## 122    28     273 11.5   82     8  13
## 123    14     274 10.9   68     5  14
## 124    35     274 10.3   82     7  17
## 125    50     275  7.4   86     7  29
## 126    77     276  5.1   88     7   7
## 127    37     279  7.4   76     5  31
## 128    37     284 20.7   72     6  17
## 129    61     285  6.3   84     7  18
## 130    NA     286  8.6   78     6   1
## 131    NA     287  9.7   74     6   2
## 132    11     290  9.2   66     5  13
## 133    71     291 13.8   90     6   9
## 134    NA     291 14.9   91     7  14
## 135    80     294  8.6   86     7  24
## 136    NA     295 11.5   82     7  23
## 137    23     299  8.6   65     5   7
## 138    34     307 12.0   66     5  17
## 139    18     313 11.5   62     5   4
## 140    40     314 10.9   83     7   6
## 141    11     320 16.6   73     5  22
## 142    30     322 11.5   68     5  19
## 143    NA     322 11.5   79     6  15
## 144    39     323 11.5   87     6  10
## 145    NA     332 13.8   80     6  14
## 146    14     334 11.5   64     5  16
## 147    NA      NA 14.3   56     5   5
## 148    28      NA 14.9   66     5   6
## 149     7      NA  6.9   74     5  11
## 150    NA      NA  8.0   57     5  27
## 151    78      NA  6.9   86     8   4
## 152    35      NA  7.4   85     8   5
## 153    66      NA  4.6   87     8   6</code></pre>
<p>The ordering is done from the lowest value of radiation to highest value. Here you see the first 10 rows. Note <code>Month</code> and <code>Day</code> are no longer chronological</p>
<p>Repeat, but order by the value of air temperature</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="tuesday-january-17-2023.html#cb173-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb173-2"><a href="tuesday-january-17-2023.html#cb173-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">arrange</span>(Temp)</span></code></pre></div>
<pre><code>##     Ozone Solar.R Wind Temp Month Day
## 1      NA      NA 14.3   56     5   5
## 2       6      78 18.4   57     5  18
## 3      NA      66 16.6   57     5  25
## 4      NA      NA  8.0   57     5  27
## 5      18      65 13.2   58     5  15
## 6      NA     266 14.9   58     5  26
## 7      19      99 13.8   59     5   8
## 8       1       8  9.7   59     5  21
## 9       8      19 20.1   61     5   9
## 10      4      25  9.7   61     5  23
## 11     32      92 12.0   61     5  24
## 12     18     313 11.5   62     5   4
## 13     11      44  9.7   62     5  20
## 14     14      20 16.6   63     9  25
## 15     14     334 11.5   64     5  16
## 16     13     238 12.6   64     9  21
## 17     23     299  8.6   65     5   7
## 18     20      37  9.2   65     6  18
## 19     28      NA 14.9   66     5   6
## 20     11     290  9.2   66     5  13
## 21     34     307 12.0   66     5  17
## 22     41     190  7.4   67     5   1
## 23     23      13 12.0   67     5  28
## 24     NA     242 16.1   67     6   3
## 25     18     224 13.8   67     9  17
## 26     14     274 10.9   68     5  14
## 27     30     322 11.5   68     5  19
## 28     24     238 10.3   68     9  19
## 29     20     223 11.5   68     9  30
## 30     NA     194  8.6   69     5  10
## 31     16     256  9.7   69     5  12
## 32      7      49 10.3   69     9  24
## 33     30     193  6.9   70     9  26
## 34      9      24 10.9   71     9  14
## 35     13     112 11.5   71     9  15
## 36     23      14  9.2   71     9  22
## 37     36     118  8.0   72     5   2
## 38     37     284 20.7   72     6  17
## 39      9      36 14.3   72     8  22
## 40     11     320 16.6   73     5  22
## 41     12     120 11.5   73     6  19
## 42     NA      47 10.3   73     6  27
## 43     10     264 14.3   73     7  12
## 44     24     259  9.7   73     9  10
## 45     12     149 12.6   74     5   3
## 46      7      NA  6.9   74     5  11
## 47     NA     287  9.7   74     6   2
## 48     16       7  6.9   74     7  21
## 49     NA     135  8.0   75     6  25
## 50     NA     255 12.6   75     8  23
## 51     21     230 10.9   75     9   9
## 52     14     191 14.3   75     9  28
## 53     37     279  7.4   76     5  31
## 54     13     137 10.3   76     6  20
## 55     NA      59  1.7   76     6  22
## 56     NA      91  4.6   76     6  23
## 57     NA     250  6.3   76     6  24
## 58     23     115  7.4   76     8  18
## 59     21     259 15.5   76     9  12
## 60     13      27 10.3   76     9  18
## 61     18     131  8.0   76     9  29
## 62     21     191 14.9   77     6  16
## 63     NA     150  6.3   77     6  21
## 64     NA      31 14.9   77     6  29
## 65     22      71 10.3   77     8  16
## 66     21     259 15.5   77     8  21
## 67     28     238  6.3   77     9  13
## 68     NA     145 13.2   77     9  27
## 69     NA     286  8.6   78     6   1
## 70     NA     127  8.0   78     6  26
## 71     31     244 10.9   78     8  19
## 72     44     190 10.3   78     8  20
## 73     23     220 10.3   78     9   8
## 74     46     237  6.9   78     9  16
## 75    115     223  5.7   79     5  30
## 76     NA     264 14.3   79     6   6
## 77     NA     322 11.5   79     6  15
## 78     NA      64 11.5   79     8  15
## 79     59      51  6.3   79     8  17
## 80     45     212  9.7   79     8  24
## 81     NA     332 13.8   80     6  14
## 82     NA      98 11.5   80     6  28
## 83      7      48 14.3   80     7  15
## 84     65     157  9.7   80     8  14
## 85     20     252 10.9   80     9   7
## 86     45     252 14.9   81     5  29
## 87     32     236  9.2   81     7   3
## 88     27     175 14.9   81     7  13
## 89     48     260  6.9   81     7  16
## 90     NA     258  9.7   81     7  22
## 91     59     254  9.2   81     7  31
## 92     39      83  6.9   81     8   1
## 93      9      24 13.8   81     8   2
## 94    168     238  3.4   81     8  25
## 95     44     236 14.9   81     9  11
## 96     36     139 10.3   81     9  23
## 97     29     127  9.7   82     6   7
## 98     23     148  8.0   82     6  13
## 99     NA     139  8.6   82     7  11
## 100    35     274 10.3   82     7  17
## 101    NA     295 11.5   82     7  23
## 102    20      81  8.6   82     7  26
## 103    16      77  7.4   82     8   3
## 104    28     273 11.5   82     8  13
## 105    16     201  8.0   82     9  20
## 106    NA     138  8.0   83     6  30
## 107    64     175  4.6   83     7   5
## 108    40     314 10.9   83     7   6
## 109    64     253  7.4   83     7  30
## 110    NA     186  9.2   84     6   4
## 111   135     269  4.1   84     7   1
## 112    NA     101 10.9   84     7   4
## 113    61     285  6.3   84     7  18
## 114    32      92 15.5   84     9   6
## 115    NA     220  8.6   85     6   5
## 116    49     248  9.2   85     7   2
## 117    63     220 11.5   85     7  20
## 118   108     223  8.0   85     7  25
## 119    35      NA  7.4   85     8   5
## 120    80     294  8.6   86     7  24
## 121    52      82 12.0   86     7  27
## 122    50     275  7.4   86     7  29
## 123    78      NA  6.9   86     8   4
## 124    NA     137 11.5   86     8  11
## 125    44     192 11.5   86     8  12
## 126    73     215  8.0   86     8  26
## 127    NA     273  6.9   87     6   8
## 128    39     323 11.5   87     6  10
## 129    79     187  5.1   87     7  19
## 130    66      NA  4.6   87     8   6
## 131    47      95  7.4   87     9   5
## 132    77     276  5.1   88     7   7
## 133    82     213  7.4   88     7  28
## 134    NA     153  5.7   88     8  27
## 135    85     175  7.4   89     7  10
## 136   122     255  4.0   89     8   7
## 137    71     291 13.8   90     6   9
## 138    89     229 10.3   90     8   8
## 139   110     207  8.0   90     8   9
## 140    NA     291 14.9   91     7  14
## 141    96     167  6.9   91     9   1
## 142    NA     250  9.2   92     6  12
## 143    97     267  6.3   92     7   8
## 144    97     272  5.7   92     7   9
## 145    NA     222  8.6   92     8  10
## 146    78     197  5.1   92     9   2
## 147    NA     259 10.9   93     6  11
## 148    73     183  2.8   93     9   3
## 149    91     189  4.6   93     9   4
## 150   118     225  2.3   94     8  29
## 151    85     188  6.3   94     8  31
## 152    84     237  6.3   96     8  30
## 153    76     203  9.7   97     8  28</code></pre>
<p>Importantly you can string the functions together. For example select the variables radiation, wind, and temperature then filter by temperatures above 90 F and arrange by temperature</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="tuesday-january-17-2023.html#cb175-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb175-2"><a href="tuesday-january-17-2023.html#cb175-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Solar.R, Wind, Temp) <span class="sc">|&gt;</span></span>
<span id="cb175-3"><a href="tuesday-january-17-2023.html#cb175-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(Temp <span class="sc">&gt;</span> <span class="dv">90</span>) <span class="sc">|&gt;</span></span>
<span id="cb175-4"><a href="tuesday-january-17-2023.html#cb175-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">arrange</span>(Temp)</span></code></pre></div>
<pre><code>##    Solar.R Wind Temp
## 1      291 14.9   91
## 2      167  6.9   91
## 3      250  9.2   92
## 4      267  6.3   92
## 5      272  5.7   92
## 6      222  8.6   92
## 7      197  5.1   92
## 8      259 10.9   93
## 9      183  2.8   93
## 10     189  4.6   93
## 11     225  2.3   94
## 12     188  6.3   94
## 13     237  6.3   96
## 14     203  9.7   97</code></pre>
<p>The result is a data frame with three columns and 14 rows arranged by increasing temperatures above 90 F</p>
<p>The <code>mutate()</code> function adds new columns to the data frame. For example, create a new column called <code>TempC</code> as the temperature in degrees Celsius. Also create a column called <code>WindMS</code> as the wind speed in meters per second</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="tuesday-january-17-2023.html#cb177-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb177-2"><a href="tuesday-january-17-2023.html#cb177-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">TempC =</span> (Temp <span class="sc">-</span> <span class="dv">32</span>) <span class="sc">*</span> <span class="dv">5</span><span class="sc">/</span><span class="dv">9</span>,</span>
<span id="cb177-3"><a href="tuesday-january-17-2023.html#cb177-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">WindMS =</span> Wind <span class="sc">*</span> .<span class="dv">44704</span>) </span></code></pre></div>
<pre><code>##     Ozone Solar.R Wind Temp Month Day    TempC   WindMS
## 1      41     190  7.4   67     5   1 19.44444 3.308096
## 2      36     118  8.0   72     5   2 22.22222 3.576320
## 3      12     149 12.6   74     5   3 23.33333 5.632704
## 4      18     313 11.5   62     5   4 16.66667 5.140960
## 5      NA      NA 14.3   56     5   5 13.33333 6.392672
## 6      28      NA 14.9   66     5   6 18.88889 6.660896
## 7      23     299  8.6   65     5   7 18.33333 3.844544
## 8      19      99 13.8   59     5   8 15.00000 6.169152
## 9       8      19 20.1   61     5   9 16.11111 8.985504
## 10     NA     194  8.6   69     5  10 20.55556 3.844544
## 11      7      NA  6.9   74     5  11 23.33333 3.084576
## 12     16     256  9.7   69     5  12 20.55556 4.336288
## 13     11     290  9.2   66     5  13 18.88889 4.112768
## 14     14     274 10.9   68     5  14 20.00000 4.872736
## 15     18      65 13.2   58     5  15 14.44444 5.900928
## 16     14     334 11.5   64     5  16 17.77778 5.140960
## 17     34     307 12.0   66     5  17 18.88889 5.364480
## 18      6      78 18.4   57     5  18 13.88889 8.225536
## 19     30     322 11.5   68     5  19 20.00000 5.140960
## 20     11      44  9.7   62     5  20 16.66667 4.336288
## 21      1       8  9.7   59     5  21 15.00000 4.336288
## 22     11     320 16.6   73     5  22 22.77778 7.420864
## 23      4      25  9.7   61     5  23 16.11111 4.336288
## 24     32      92 12.0   61     5  24 16.11111 5.364480
## 25     NA      66 16.6   57     5  25 13.88889 7.420864
## 26     NA     266 14.9   58     5  26 14.44444 6.660896
## 27     NA      NA  8.0   57     5  27 13.88889 3.576320
## 28     23      13 12.0   67     5  28 19.44444 5.364480
## 29     45     252 14.9   81     5  29 27.22222 6.660896
## 30    115     223  5.7   79     5  30 26.11111 2.548128
## 31     37     279  7.4   76     5  31 24.44444 3.308096
## 32     NA     286  8.6   78     6   1 25.55556 3.844544
## 33     NA     287  9.7   74     6   2 23.33333 4.336288
## 34     NA     242 16.1   67     6   3 19.44444 7.197344
## 35     NA     186  9.2   84     6   4 28.88889 4.112768
## 36     NA     220  8.6   85     6   5 29.44444 3.844544
## 37     NA     264 14.3   79     6   6 26.11111 6.392672
## 38     29     127  9.7   82     6   7 27.77778 4.336288
## 39     NA     273  6.9   87     6   8 30.55556 3.084576
## 40     71     291 13.8   90     6   9 32.22222 6.169152
## 41     39     323 11.5   87     6  10 30.55556 5.140960
## 42     NA     259 10.9   93     6  11 33.88889 4.872736
## 43     NA     250  9.2   92     6  12 33.33333 4.112768
## 44     23     148  8.0   82     6  13 27.77778 3.576320
## 45     NA     332 13.8   80     6  14 26.66667 6.169152
## 46     NA     322 11.5   79     6  15 26.11111 5.140960
## 47     21     191 14.9   77     6  16 25.00000 6.660896
## 48     37     284 20.7   72     6  17 22.22222 9.253728
## 49     20      37  9.2   65     6  18 18.33333 4.112768
## 50     12     120 11.5   73     6  19 22.77778 5.140960
## 51     13     137 10.3   76     6  20 24.44444 4.604512
## 52     NA     150  6.3   77     6  21 25.00000 2.816352
## 53     NA      59  1.7   76     6  22 24.44444 0.759968
## 54     NA      91  4.6   76     6  23 24.44444 2.056384
## 55     NA     250  6.3   76     6  24 24.44444 2.816352
## 56     NA     135  8.0   75     6  25 23.88889 3.576320
## 57     NA     127  8.0   78     6  26 25.55556 3.576320
## 58     NA      47 10.3   73     6  27 22.77778 4.604512
## 59     NA      98 11.5   80     6  28 26.66667 5.140960
## 60     NA      31 14.9   77     6  29 25.00000 6.660896
## 61     NA     138  8.0   83     6  30 28.33333 3.576320
## 62    135     269  4.1   84     7   1 28.88889 1.832864
## 63     49     248  9.2   85     7   2 29.44444 4.112768
## 64     32     236  9.2   81     7   3 27.22222 4.112768
## 65     NA     101 10.9   84     7   4 28.88889 4.872736
## 66     64     175  4.6   83     7   5 28.33333 2.056384
## 67     40     314 10.9   83     7   6 28.33333 4.872736
## 68     77     276  5.1   88     7   7 31.11111 2.279904
## 69     97     267  6.3   92     7   8 33.33333 2.816352
## 70     97     272  5.7   92     7   9 33.33333 2.548128
## 71     85     175  7.4   89     7  10 31.66667 3.308096
## 72     NA     139  8.6   82     7  11 27.77778 3.844544
## 73     10     264 14.3   73     7  12 22.77778 6.392672
## 74     27     175 14.9   81     7  13 27.22222 6.660896
## 75     NA     291 14.9   91     7  14 32.77778 6.660896
## 76      7      48 14.3   80     7  15 26.66667 6.392672
## 77     48     260  6.9   81     7  16 27.22222 3.084576
## 78     35     274 10.3   82     7  17 27.77778 4.604512
## 79     61     285  6.3   84     7  18 28.88889 2.816352
## 80     79     187  5.1   87     7  19 30.55556 2.279904
## 81     63     220 11.5   85     7  20 29.44444 5.140960
## 82     16       7  6.9   74     7  21 23.33333 3.084576
## 83     NA     258  9.7   81     7  22 27.22222 4.336288
## 84     NA     295 11.5   82     7  23 27.77778 5.140960
## 85     80     294  8.6   86     7  24 30.00000 3.844544
## 86    108     223  8.0   85     7  25 29.44444 3.576320
## 87     20      81  8.6   82     7  26 27.77778 3.844544
## 88     52      82 12.0   86     7  27 30.00000 5.364480
## 89     82     213  7.4   88     7  28 31.11111 3.308096
## 90     50     275  7.4   86     7  29 30.00000 3.308096
## 91     64     253  7.4   83     7  30 28.33333 3.308096
## 92     59     254  9.2   81     7  31 27.22222 4.112768
## 93     39      83  6.9   81     8   1 27.22222 3.084576
## 94      9      24 13.8   81     8   2 27.22222 6.169152
## 95     16      77  7.4   82     8   3 27.77778 3.308096
## 96     78      NA  6.9   86     8   4 30.00000 3.084576
## 97     35      NA  7.4   85     8   5 29.44444 3.308096
## 98     66      NA  4.6   87     8   6 30.55556 2.056384
## 99    122     255  4.0   89     8   7 31.66667 1.788160
## 100    89     229 10.3   90     8   8 32.22222 4.604512
## 101   110     207  8.0   90     8   9 32.22222 3.576320
## 102    NA     222  8.6   92     8  10 33.33333 3.844544
## 103    NA     137 11.5   86     8  11 30.00000 5.140960
## 104    44     192 11.5   86     8  12 30.00000 5.140960
## 105    28     273 11.5   82     8  13 27.77778 5.140960
## 106    65     157  9.7   80     8  14 26.66667 4.336288
## 107    NA      64 11.5   79     8  15 26.11111 5.140960
## 108    22      71 10.3   77     8  16 25.00000 4.604512
## 109    59      51  6.3   79     8  17 26.11111 2.816352
## 110    23     115  7.4   76     8  18 24.44444 3.308096
## 111    31     244 10.9   78     8  19 25.55556 4.872736
## 112    44     190 10.3   78     8  20 25.55556 4.604512
## 113    21     259 15.5   77     8  21 25.00000 6.929120
## 114     9      36 14.3   72     8  22 22.22222 6.392672
## 115    NA     255 12.6   75     8  23 23.88889 5.632704
## 116    45     212  9.7   79     8  24 26.11111 4.336288
## 117   168     238  3.4   81     8  25 27.22222 1.519936
## 118    73     215  8.0   86     8  26 30.00000 3.576320
## 119    NA     153  5.7   88     8  27 31.11111 2.548128
## 120    76     203  9.7   97     8  28 36.11111 4.336288
## 121   118     225  2.3   94     8  29 34.44444 1.028192
## 122    84     237  6.3   96     8  30 35.55556 2.816352
## 123    85     188  6.3   94     8  31 34.44444 2.816352
## 124    96     167  6.9   91     9   1 32.77778 3.084576
## 125    78     197  5.1   92     9   2 33.33333 2.279904
## 126    73     183  2.8   93     9   3 33.88889 1.251712
## 127    91     189  4.6   93     9   4 33.88889 2.056384
## 128    47      95  7.4   87     9   5 30.55556 3.308096
## 129    32      92 15.5   84     9   6 28.88889 6.929120
## 130    20     252 10.9   80     9   7 26.66667 4.872736
## 131    23     220 10.3   78     9   8 25.55556 4.604512
## 132    21     230 10.9   75     9   9 23.88889 4.872736
## 133    24     259  9.7   73     9  10 22.77778 4.336288
## 134    44     236 14.9   81     9  11 27.22222 6.660896
## 135    21     259 15.5   76     9  12 24.44444 6.929120
## 136    28     238  6.3   77     9  13 25.00000 2.816352
## 137     9      24 10.9   71     9  14 21.66667 4.872736
## 138    13     112 11.5   71     9  15 21.66667 5.140960
## 139    46     237  6.9   78     9  16 25.55556 3.084576
## 140    18     224 13.8   67     9  17 19.44444 6.169152
## 141    13      27 10.3   76     9  18 24.44444 4.604512
## 142    24     238 10.3   68     9  19 20.00000 4.604512
## 143    16     201  8.0   82     9  20 27.77778 3.576320
## 144    13     238 12.6   64     9  21 17.77778 5.632704
## 145    23      14  9.2   71     9  22 21.66667 4.112768
## 146    36     139 10.3   81     9  23 27.22222 4.604512
## 147     7      49 10.3   69     9  24 20.55556 4.604512
## 148    14      20 16.6   63     9  25 17.22222 7.420864
## 149    30     193  6.9   70     9  26 21.11111 3.084576
## 150    NA     145 13.2   77     9  27 25.00000 5.900928
## 151    14     191 14.3   75     9  28 23.88889 6.392672
## 152    18     131  8.0   76     9  29 24.44444 3.576320
## 153    20     223 11.5   68     9  30 20.00000 5.140960</code></pre>
<p>The resulting data frame has 8 columns (two new ones) labeled <code>TempC</code> and <code>WindMS</code></p>
<p>On days when the temperature is below 60 F add a column giving the apparent temperature based on the cooling effect of the wind (wind chill) and then arrange from coldest to warmest apparent temperature</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="tuesday-january-17-2023.html#cb179-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb179-2"><a href="tuesday-january-17-2023.html#cb179-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(Temp <span class="sc">&lt;</span> <span class="dv">60</span>) <span class="sc">|&gt;</span></span>
<span id="cb179-3"><a href="tuesday-january-17-2023.html#cb179-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">TempAp =</span> <span class="fl">35.74</span> <span class="sc">+</span> .<span class="dv">6215</span> <span class="sc">*</span> Temp <span class="sc">-</span> <span class="fl">35.75</span> <span class="sc">*</span> Wind<span class="sc">^</span>.<span class="dv">16</span> <span class="sc">+</span> .<span class="dv">4275</span> <span class="sc">*</span> Temp <span class="sc">*</span> Wind<span class="sc">^</span>.<span class="dv">16</span>) <span class="sc">|&gt;</span></span>
<span id="cb179-4"><a href="tuesday-january-17-2023.html#cb179-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">arrange</span>(TempAp)</span></code></pre></div>
<pre><code>##   Ozone Solar.R Wind Temp Month Day   TempAp
## 1    NA      NA 14.3   56     5   5 52.46794
## 2     6      78 18.4   57     5  18 53.02670
## 3    NA      66 16.6   57     5  25 53.32303
## 4    NA     266 14.9   58     5  26 54.90895
## 5    18      65 13.2   58     5  15 55.23295
## 6    NA      NA  8.0   57     5  27 55.28983
## 7    19      99 13.8   59     5   8 56.38690
## 8     1       8  9.7   59     5  21 57.26561</code></pre>
<p>The <code>summarize()</code> function reduces the data frame based on a function that computes a statistic. For example, to compute the average wind speed during July or the average temperature during June type</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="tuesday-january-17-2023.html#cb181-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb181-2"><a href="tuesday-january-17-2023.html#cb181-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(Month <span class="sc">==</span> <span class="dv">7</span>) <span class="sc">|&gt;</span></span>
<span id="cb181-3"><a href="tuesday-january-17-2023.html#cb181-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">Wavg =</span> <span class="fu">mean</span>(Wind))</span></code></pre></div>
<pre><code>##       Wavg
## 1 8.941935</code></pre>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="tuesday-january-17-2023.html#cb183-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb183-2"><a href="tuesday-january-17-2023.html#cb183-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(Month <span class="sc">==</span> <span class="dv">6</span>) <span class="sc">|&gt;</span></span>
<span id="cb183-3"><a href="tuesday-january-17-2023.html#cb183-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">Tavg =</span> <span class="fu">mean</span>(Temp))</span></code></pre></div>
<pre><code>##   Tavg
## 1 79.1</code></pre>
<p>You’ve seen functions that compute statistics including <code>sum()</code>, <code>sd()</code>, <code>min()</code>, <code>max()</code>, <code>var()</code>, <code>range()</code>, <code>median()</code>. Others include</p>
<table>
<thead>
<tr class="header">
<th align="right">Summary function</th>
<th align="left">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right"><code>dplyr::n()</code></td>
<td align="left">Length of the column</td>
</tr>
<tr class="even">
<td align="right"><code>dplyr::first()</code></td>
<td align="left">First value of the column</td>
</tr>
<tr class="odd">
<td align="right"><code>dplyr::last()</code></td>
<td align="left">Last value of the column</td>
</tr>
<tr class="even">
<td align="right"><code>dplyr::n_distinct()</code></td>
<td align="left">Number of distinct values</td>
</tr>
</tbody>
</table>
<p>Find the maximum and median wind speed and maximum ozone concentration values during the month of May. Also determine the number of observations during May</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="tuesday-january-17-2023.html#cb185-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb185-2"><a href="tuesday-january-17-2023.html#cb185-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(Month <span class="sc">==</span> <span class="dv">5</span>) <span class="sc">|&gt;</span></span>
<span id="cb185-3"><a href="tuesday-january-17-2023.html#cb185-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">Wmax =</span> <span class="fu">max</span>(Wind),</span>
<span id="cb185-4"><a href="tuesday-january-17-2023.html#cb185-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">Wmed =</span> <span class="fu">median</span>(Wind),</span>
<span id="cb185-5"><a href="tuesday-january-17-2023.html#cb185-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">OzoneMax =</span> <span class="fu">max</span>(Ozone),</span>
<span id="cb185-6"><a href="tuesday-january-17-2023.html#cb185-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">NumDays =</span> dplyr<span class="sc">::</span><span class="fu">n</span>())</span></code></pre></div>
<pre><code>##   Wmax Wmed OzoneMax NumDays
## 1 20.1 11.5       NA      31</code></pre>
<p>The result gives an <code>NA</code> for the maximum value of ozone (<code>OzoneMax</code>) because there is at least one missing value in the <code>Ozone</code> column. You fix this with the <code>na.rm = TRUE</code> argument in the function <code>max()</code></p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="tuesday-january-17-2023.html#cb187-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb187-2"><a href="tuesday-january-17-2023.html#cb187-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(Month <span class="sc">==</span> <span class="dv">5</span>) <span class="sc">|&gt;</span></span>
<span id="cb187-3"><a href="tuesday-january-17-2023.html#cb187-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">Wmax =</span> <span class="fu">max</span>(Wind),</span>
<span id="cb187-4"><a href="tuesday-january-17-2023.html#cb187-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">Wmed =</span> <span class="fu">median</span>(Wind),</span>
<span id="cb187-5"><a href="tuesday-january-17-2023.html#cb187-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">OzoneMax =</span> <span class="fu">max</span>(Ozone, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb187-6"><a href="tuesday-january-17-2023.html#cb187-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">NumDays =</span> dplyr<span class="sc">::</span><span class="fu">n</span>())</span></code></pre></div>
<pre><code>##   Wmax Wmed OzoneMax NumDays
## 1 20.1 11.5      115      31</code></pre>
<p>If you want to summarize separately for each month you use the <code>group_by()</code> function. You split the data frame by some variable (e.g., <code>Month</code>), apply a function to the individual data frames, and then combine the output</p>
<p>Find the highest ozone concentration by month. Include the number of observations (days) in the month</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="tuesday-january-17-2023.html#cb189-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb189-2"><a href="tuesday-january-17-2023.html#cb189-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(Month) <span class="sc">|&gt;</span></span>
<span id="cb189-3"><a href="tuesday-january-17-2023.html#cb189-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">OzoneMax =</span>  <span class="fu">max</span>(Ozone, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb189-4"><a href="tuesday-january-17-2023.html#cb189-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">NumDays =</span> dplyr<span class="sc">::</span><span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 5 × 3
##   Month OzoneMax NumDays
##   &lt;int&gt;    &lt;int&gt;   &lt;int&gt;
## 1     5      115      31
## 2     6       71      30
## 3     7      135      31
## 4     8      168      31
## 5     9       96      30</code></pre>
<p>Find the average ozone concentration when temperatures are above and below 70 F. Include the number of observations (days) in the two groups</p>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="tuesday-january-17-2023.html#cb191-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb191-2"><a href="tuesday-january-17-2023.html#cb191-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(Temp <span class="sc">&gt;=</span> <span class="dv">70</span>) <span class="sc">|&gt;</span></span>
<span id="cb191-3"><a href="tuesday-january-17-2023.html#cb191-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">OzoneAvg =</span>  <span class="fu">mean</span>(Ozone, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb191-4"><a href="tuesday-january-17-2023.html#cb191-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">NumDays =</span> dplyr<span class="sc">::</span><span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 2 × 3
##   `Temp &gt;= 70` OzoneAvg NumDays
##   &lt;lgl&gt;           &lt;dbl&gt;   &lt;int&gt;
## 1 FALSE            18.0      32
## 2 TRUE             49.1     121</code></pre>
<p>On average ozone concentration is higher on warm days (Temp &gt;= 70 F) days. Said another way; mean ozone concentration statistically depends on temperature</p>
<p>The mean is a model for the data. The statistical dependency of the mean implies that a model for ozone concentration will be improved by including temperature as an explanatory variable</p>
<p>In summary, the important verbs are</p>
<table>
<colgroup>
<col width="54%" />
<col width="45%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">Verb</th>
<th align="left">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right"><code>select()</code></td>
<td align="left">selects columns; pick variables by their names</td>
</tr>
<tr class="even">
<td align="right"><code>filter()</code></td>
<td align="left">filters rows; pick observations by their values</td>
</tr>
<tr class="odd">
<td align="right"><code>arrange()</code></td>
<td align="left">re-orders the rows</td>
</tr>
<tr class="even">
<td align="right"><code>mutate()</code></td>
<td align="left">creates new columns; create new variables with functions of existing variables</td>
</tr>
<tr class="odd">
<td align="right"><code>summarize()</code></td>
<td align="left">summarizes values; collapse many values down to a single summary</td>
</tr>
<tr class="even">
<td align="right"><code>group_by()</code></td>
<td align="left">allows operations to be grouped</td>
</tr>
</tbody>
</table>
<p>The six functions form the basis of a grammar for data. You can only alter a data frame by reordering the rows (<code>arrange()</code>), picking observations and variables of interest (<code>filter()</code> and <code>select()</code>), adding new variables that are functions of existing variables (<code>mutate()</code>), collapsing many values to a summary (<code>summarise()</code>), and conditioning on variables (<code>group_by()</code>)</p>
<p>The syntax of the functions are all the same</p>
<ul>
<li>The first argument is a data frame. This argument is implicit when using the <code>|&gt;</code> operator</li>
<li>The subsequent arguments describe what to do with the data frame. You refer to columns in the data frame directly (without using <code>$</code>)</li>
<li>The result is a new data frame</li>
</ul>
<p>These properties make it easy to chain together many simple lines of code to do complex data manipulations and summaries all while making it easy to read by humans</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="thursday-january-12-2023.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="thursday-january-19-2023.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
