<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tuesday April 18, 2023 | GIS5122: Applied Spatial Statistics</title>
  <meta name="description" content="Tuesday April 18, 2023 | GIS5122: Applied Spatial Statistics" />
  <meta name="generator" content="bookdown 0.32 and GitBook 2.6.7" />

  <meta property="og:title" content="Tuesday April 18, 2023 | GIS5122: Applied Spatial Statistics" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="jelsner/ASS-2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tuesday April 18, 2023 | GIS5122: Applied Spatial Statistics" />
  
  
  

<meta name="author" content="James B. Elsner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="thursday-april-13-2023.html"/>
<link rel="next" href="tuesday-april-25-2023.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied Spatial Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="syllabus-and-set-up.html"><a href="syllabus-and-set-up.html"><i class="fa fa-check"></i>Syllabus and set up</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus-and-set-up.html"><a href="syllabus-and-set-up.html#contact-information"><i class="fa fa-check"></i>Contact information</a></li>
<li class="chapter" data-level="" data-path="syllabus-and-set-up.html"><a href="syllabus-and-set-up.html#course-description-and-expected-learning-outcomes"><i class="fa fa-check"></i>Course description and expected learning outcomes</a></li>
<li class="chapter" data-level="" data-path="syllabus-and-set-up.html"><a href="syllabus-and-set-up.html#grades-and-ethics"><i class="fa fa-check"></i>Grades and ethics</a></li>
<li class="chapter" data-level="" data-path="syllabus-and-set-up.html"><a href="syllabus-and-set-up.html#outline-of-topics-and-schedule"><i class="fa fa-check"></i>Outline of topics and schedule</a></li>
<li class="chapter" data-level="" data-path="syllabus-and-set-up.html"><a href="syllabus-and-set-up.html#reference-materials"><i class="fa fa-check"></i>Reference materials</a></li>
<li class="chapter" data-level="" data-path="syllabus-and-set-up.html"><a href="syllabus-and-set-up.html#reproducible-research"><i class="fa fa-check"></i>Reproducible research</a></li>
<li class="chapter" data-level="" data-path="syllabus-and-set-up.html"><a href="syllabus-and-set-up.html#getting-you-set-up"><i class="fa fa-check"></i>Getting you set up</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-january-12-2023.html"><a href="thursday-january-12-2023.html"><i class="fa fa-check"></i>Thursday, January 12, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-january-12-2023.html"><a href="thursday-january-12-2023.html#important-points-from-the-syllabus"><i class="fa fa-check"></i>Important points from the syllabus</a></li>
<li class="chapter" data-level="" data-path="thursday-january-12-2023.html"><a href="thursday-january-12-2023.html#continue-with-setup"><i class="fa fa-check"></i>Continue with setup</a></li>
<li class="chapter" data-level="" data-path="thursday-january-12-2023.html"><a href="thursday-january-12-2023.html#about-rstudio"><i class="fa fa-check"></i>About RStudio</a></li>
<li class="chapter" data-level="" data-path="thursday-january-12-2023.html"><a href="thursday-january-12-2023.html#lab-assignments"><i class="fa fa-check"></i>Lab assignments</a></li>
<li class="chapter" data-level="" data-path="thursday-january-12-2023.html"><a href="thursday-january-12-2023.html#data-science-workflow-with-r-markdown"><i class="fa fa-check"></i>Data science workflow with R markdown</a></li>
<li class="chapter" data-level="" data-path="thursday-january-12-2023.html"><a href="thursday-january-12-2023.html#getting-started-with-r"><i class="fa fa-check"></i>Getting started with R</a></li>
<li class="chapter" data-level="" data-path="thursday-january-12-2023.html"><a href="thursday-january-12-2023.html#completely-new-to-r"><i class="fa fa-check"></i>Completely new to R?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-january-17-2023.html"><a href="tuesday-january-17-2023.html"><i class="fa fa-check"></i>Tuesday, January 17, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-january-17-2023.html"><a href="tuesday-january-17-2023.html#class-notes"><i class="fa fa-check"></i>Class notes</a></li>
<li class="chapter" data-level="" data-path="tuesday-january-17-2023.html"><a href="tuesday-january-17-2023.html#using-r"><i class="fa fa-check"></i>Using R</a></li>
<li class="chapter" data-level="" data-path="tuesday-january-17-2023.html"><a href="tuesday-january-17-2023.html#data-frames"><i class="fa fa-check"></i>Data frames</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-january-19-2023.html"><a href="thursday-january-19-2023.html"><i class="fa fa-check"></i>Thursday January 19, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-january-19-2023.html"><a href="thursday-january-19-2023.html#getting-data-into-r"><i class="fa fa-check"></i>Getting data into R</a></li>
<li class="chapter" data-level="" data-path="thursday-january-19-2023.html"><a href="thursday-january-19-2023.html#working-with-data-frames-using-functions-from-dplyr"><i class="fa fa-check"></i>Working with data frames using functions from {dplyr}</a></li>
<li class="chapter" data-level="" data-path="thursday-january-19-2023.html"><a href="thursday-january-19-2023.html#making-graphs"><i class="fa fa-check"></i>Making graphs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-january-24-2023.html"><a href="tuesday-january-24-2023.html"><i class="fa fa-check"></i>Tuesday January 24, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-january-24-2023.html"><a href="tuesday-january-24-2023.html#making-graphs-1"><i class="fa fa-check"></i>Making graphs</a></li>
<li class="chapter" data-level="" data-path="tuesday-january-24-2023.html"><a href="tuesday-january-24-2023.html#introduction-to-simple-features"><i class="fa fa-check"></i>Introduction to simple features</a></li>
<li class="chapter" data-level="" data-path="tuesday-january-24-2023.html"><a href="tuesday-january-24-2023.html#geo-computation-on-simple-features"><i class="fa fa-check"></i>Geo-computation on simple features</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-january-31-2023.html"><a href="tuesday-january-31-2023.html"><i class="fa fa-check"></i>Tuesday January 31, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-january-31-2023.html"><a href="tuesday-january-31-2023.html#filtering-selecting-and-conditioning-on-attributes"><i class="fa fa-check"></i>Filtering, selecting, and conditioning on attributes</a></li>
<li class="chapter" data-level="" data-path="tuesday-january-31-2023.html"><a href="tuesday-january-31-2023.html#filtering-on-geographic-boundaries"><i class="fa fa-check"></i>Filtering on geographic boundaries</a></li>
<li class="chapter" data-level="" data-path="tuesday-january-31-2023.html"><a href="tuesday-january-31-2023.html#joining-data-frames"><i class="fa fa-check"></i>Joining data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-january-31-2023.html"><a href="tuesday-january-31-2023.html#interpolating-using-areal-weights"><i class="fa fa-check"></i>Interpolating using areal weights</a></li>
<li class="chapter" data-level="" data-path="tuesday-january-31-2023.html"><a href="tuesday-january-31-2023.html#s4-spatial-data-objects"><i class="fa fa-check"></i>S4 spatial data objects</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-february-2-2023.html"><a href="thursday-february-2-2023.html"><i class="fa fa-check"></i>Thursday February 2, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-february-2-2023.html"><a href="thursday-february-2-2023.html#working-with-raster-data"><i class="fa fa-check"></i>Working with raster data</a></li>
<li class="chapter" data-level="" data-path="thursday-february-2-2023.html"><a href="thursday-february-2-2023.html#working-with-space-time-data"><i class="fa fa-check"></i>Working with space-time data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-february-7-2023.html"><a href="tuesday-february-7-2023.html"><i class="fa fa-check"></i>Tuesday February 7, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-february-7-2023.html"><a href="tuesday-february-7-2023.html#mapping-using-functions-from-the-ggplot2-package"><i class="fa fa-check"></i>Mapping using functions from the {ggplot2} package</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-7-2023.html"><a href="tuesday-february-7-2023.html#mapping-using-functions-from-the-tmap-package"><i class="fa fa-check"></i>Mapping using functions from the {tmap} package</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-7-2023.html"><a href="tuesday-february-7-2023.html#creating-an-interactive-map"><i class="fa fa-check"></i>Creating an interactive map</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-7-2023.html"><a href="tuesday-february-7-2023.html#isolines-and-isobands"><i class="fa fa-check"></i>Isolines and isobands</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-7-2023.html"><a href="tuesday-february-7-2023.html#hillshape-and-colors-with-tidyterra"><i class="fa fa-check"></i>Hillshape and colors with tidyterra</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-7-2023.html"><a href="tuesday-february-7-2023.html#visualizing-spatial-data"><i class="fa fa-check"></i>Visualizing spatial data</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-7-2023.html"><a href="tuesday-february-7-2023.html#adding-an-inset-map"><i class="fa fa-check"></i>Adding an inset map</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-7-2023.html"><a href="tuesday-february-7-2023.html#making-maps-with-rdeck"><i class="fa fa-check"></i>Making maps with rdeck</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-february-14-2023.html"><a href="tuesday-february-14-2023.html"><i class="fa fa-check"></i>Tuesday February 14, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-february-14-2023.html"><a href="tuesday-february-14-2023.html#defining-spatial-neighborhoods-and-spatial-weights"><i class="fa fa-check"></i>Defining spatial neighborhoods and spatial weights</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-14-2023.html"><a href="tuesday-february-14-2023.html#computing-autocorrelation"><i class="fa fa-check"></i>Computing autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-14-2023.html"><a href="tuesday-february-14-2023.html#relating-autocorrelation-to-the-spatial-lag-variable"><i class="fa fa-check"></i>Relating autocorrelation to the spatial lag variable</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-february-16-2023.html"><a href="thursday-february-16-2023.html"><i class="fa fa-check"></i>Thursday February 16, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-february-16-2023.html"><a href="thursday-february-16-2023.html#defining-neighborhoods"><i class="fa fa-check"></i>Defining neighborhoods</a></li>
<li class="chapter" data-level="" data-path="thursday-february-16-2023.html"><a href="thursday-february-16-2023.html#assessing-the-statistical-significance-of-autocorrelation"><i class="fa fa-check"></i>Assessing the statistical significance of autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-february-16-2023.html"><a href="thursday-february-16-2023.html#computing-and-interpreting-bivariate-spatial-autocorrelation"><i class="fa fa-check"></i>Computing and interpreting bivariate spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-february-16-2023.html"><a href="thursday-february-16-2023.html#assessing-local-indicators-of-spatial-autocorrelation"><i class="fa fa-check"></i>Assessing local indicators of spatial autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-february-21-2023.html"><a href="tuesday-february-21-2023.html"><i class="fa fa-check"></i>Tuesday February 21, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-february-21-2023.html"><a href="tuesday-february-21-2023.html#using-local-spatial-autocorrelation-to-understand-the-tornado-record"><i class="fa fa-check"></i>Using local spatial autocorrelation to understand the tornado record</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-21-2023.html"><a href="tuesday-february-21-2023.html#constraining-group-membership-based-on-spatial-autocorrelation"><i class="fa fa-check"></i>Constraining group membership based on spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-21-2023.html"><a href="tuesday-february-21-2023.html#estimating-spatial-autocorrelation-in-model-residuals"><i class="fa fa-check"></i>Estimating spatial autocorrelation in model residuals</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-21-2023.html"><a href="tuesday-february-21-2023.html#choosing-a-spatial-regression-model"><i class="fa fa-check"></i>Choosing a spatial regression model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-february-23-2023.html"><a href="thursday-february-23-2023.html"><i class="fa fa-check"></i>Thursday February 23, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-february-23-2023.html"><a href="thursday-february-23-2023.html#fitting-and-interpreting-spatial-regression-models"><i class="fa fa-check"></i>Fitting and interpreting spatial regression models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-february-28-2023.html"><a href="tuesday-february-28-2023.html"><i class="fa fa-check"></i>Tuesday February 28, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-february-28-2023.html"><a href="tuesday-february-28-2023.html#fitting-and-interpreting-geographic-regression"><i class="fa fa-check"></i>Fitting and interpreting geographic regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-february-28-2023.html"><a href="tuesday-february-28-2023.html#mapping-incidence-and-risk-with-a-spatial-regression-model"><i class="fa fa-check"></i>Mapping incidence and risk with a spatial regression model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-march-7-2023.html"><a href="tuesday-march-7-2023.html"><i class="fa fa-check"></i>Tuesday March 7, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-march-7-2023.html"><a href="tuesday-march-7-2023.html#spatial-data-interpolation"><i class="fa fa-check"></i>Spatial data interpolation</a></li>
<li class="chapter" data-level="" data-path="tuesday-march-7-2023.html"><a href="tuesday-march-7-2023.html#computing-the-sample-variogram"><i class="fa fa-check"></i>Computing the sample variogram</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-march-9-2023.html"><a href="thursday-march-9-2023.html"><i class="fa fa-check"></i>Thursday March 9, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-march-9-2023.html"><a href="thursday-march-9-2023.html#fitting-a-variogram-model-to-the-sample-variogram"><i class="fa fa-check"></i>Fitting a variogram model to the sample variogram</a></li>
<li class="chapter" data-level="" data-path="thursday-march-9-2023.html"><a href="thursday-march-9-2023.html#creating-an-interpolated-surface-with-the-method-of-kriging"><i class="fa fa-check"></i>Creating an interpolated surface with the method of kriging</a></li>
<li class="chapter" data-level="" data-path="thursday-march-9-2023.html"><a href="thursday-march-9-2023.html#comparing-interpolation-methods"><i class="fa fa-check"></i>Comparing interpolation methods</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-march-21-2023.html"><a href="tuesday-march-21-2023.html"><i class="fa fa-check"></i>Tuesday March 21, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-march-21-2023.html"><a href="tuesday-march-21-2023.html#evaluating-interpolation-accuracy"><i class="fa fa-check"></i>Evaluating interpolation accuracy</a></li>
<li class="chapter" data-level="" data-path="tuesday-march-21-2023.html"><a href="tuesday-march-21-2023.html#block-cross-validation"><i class="fa fa-check"></i>Block cross validation</a></li>
<li class="chapter" data-level="" data-path="tuesday-march-21-2023.html"><a href="tuesday-march-21-2023.html#interpolating-to-areal-units-block-kriging"><i class="fa fa-check"></i>Interpolating to areal units (block kriging)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-march-28-2023.html"><a href="tuesday-march-28-2023.html"><i class="fa fa-check"></i>Tuesday March 28, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-march-28-2023.html"><a href="tuesday-march-28-2023.html#interpolating-multiple-variables"><i class="fa fa-check"></i>Interpolating multiple variables</a></li>
<li class="chapter" data-level="" data-path="tuesday-march-28-2023.html"><a href="tuesday-march-28-2023.html#machine-learning-for-spatial-interpolation"><i class="fa fa-check"></i>Machine learning for spatial interpolation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-april-4-2023.html"><a href="tuesday-april-4-2023.html"><i class="fa fa-check"></i>Tuesday April 4, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-april-4-2023.html"><a href="tuesday-april-4-2023.html#spatial-data-as-point-patterns"><i class="fa fa-check"></i>Spatial data as point patterns</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-4-2023.html"><a href="tuesday-april-4-2023.html#theoretical-framework-for-analyzingmodeling-point-pattern-data"><i class="fa fa-check"></i>Theoretical framework for analyzing/modeling point pattern data</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-4-2023.html"><a href="tuesday-april-4-2023.html#working-with-point-pattern-data-using-functions-from-the-spatstat-family-of-packages"><i class="fa fa-check"></i>Working with point pattern data using functions from the spatstat family of packages</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-4-2023.html"><a href="tuesday-april-4-2023.html#quantifying-the-spatial-intensity-of-events"><i class="fa fa-check"></i>Quantifying the spatial intensity of events</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-april-6-2023.html"><a href="thursday-april-6-2023.html"><i class="fa fa-check"></i>Thursday April 6, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-april-6-2023.html"><a href="thursday-april-6-2023.html#creating-ppp-and-owin-objects-from-simple-feature-data-frames"><i class="fa fa-check"></i>Creating <code>ppp</code> and <code>owin</code> objects from simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="thursday-april-6-2023.html"><a href="thursday-april-6-2023.html#estimating-spatial-intensity-as-a-function-of-distance"><i class="fa fa-check"></i>Estimating spatial intensity as a function of distance</a></li>
<li class="chapter" data-level="" data-path="thursday-april-6-2023.html"><a href="thursday-april-6-2023.html#covariate-trend-as-a-possible-confounding-factor"><i class="fa fa-check"></i>Covariate trend as a possible confounding factor</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-april-11-2023.html"><a href="tuesday-april-11-2023.html"><i class="fa fa-check"></i>Tuesday April 11, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-april-11-2023.html"><a href="tuesday-april-11-2023.html#estimating-the-relative-risk-of-an-event"><i class="fa fa-check"></i>Estimating the relative risk of an event</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-11-2023.html"><a href="tuesday-april-11-2023.html#estimating-second-moment-properties-of-events"><i class="fa fa-check"></i>Estimating second-moment properties of events</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-11-2023.html"><a href="tuesday-april-11-2023.html#examples-of-clustered-events"><i class="fa fa-check"></i>Examples of clustered events</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-april-13-2023.html"><a href="thursday-april-13-2023.html"><i class="fa fa-check"></i>Thursday April 13, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-april-13-2023.html"><a href="thursday-april-13-2023.html#removing-duplicate-events-and-defining-the-domain"><i class="fa fa-check"></i>Removing duplicate events and defining the domain</a></li>
<li class="chapter" data-level="" data-path="thursday-april-13-2023.html"><a href="thursday-april-13-2023.html#determining-statistical-significance-of-clustering"><i class="fa fa-check"></i>Determining statistical significance of clustering</a></li>
<li class="chapter" data-level="" data-path="thursday-april-13-2023.html"><a href="thursday-april-13-2023.html#estimating-clustering-in-multi-type-event-locations"><i class="fa fa-check"></i>Estimating clustering in multi-type event locations</a></li>
<li class="chapter" data-level="" data-path="thursday-april-13-2023.html"><a href="thursday-april-13-2023.html#interpolating-output-from-a-distance-function"><i class="fa fa-check"></i>Interpolating output from a distance function</a></li>
<li class="chapter" data-level="" data-path="thursday-april-13-2023.html"><a href="thursday-april-13-2023.html#limitations-of-interpreting-the-distance-functions"><i class="fa fa-check"></i>Limitations of interpreting the distance functions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-april-18-2023.html"><a href="tuesday-april-18-2023.html"><i class="fa fa-check"></i>Tuesday April 18, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-april-18-2023.html"><a href="tuesday-april-18-2023.html#models-for-point-pattern-data"><i class="fa fa-check"></i>Models for point pattern data</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-18-2023.html"><a href="tuesday-april-18-2023.html#fitting-and-interpreting-inhibition-models"><i class="fa fa-check"></i>Fitting and interpreting inhibition models</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-18-2023.html"><a href="tuesday-april-18-2023.html#fitting-and-interpreting-cluster-models"><i class="fa fa-check"></i>Fitting and interpreting cluster models</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-18-2023.html"><a href="tuesday-april-18-2023.html#fitting-and-interpreting-a-log-gaussian-cox-cluster-model"><i class="fa fa-check"></i>Fitting and interpreting a log-Gaussian Cox (cluster) model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-april-25-2023.html"><a href="tuesday-april-25-2023.html"><i class="fa fa-check"></i>Tuesday April 25, 2023</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-april-25-2023.html"><a href="tuesday-april-25-2023.html#assessing-how-well-a-point-pattern-model-fits-the-data"><i class="fa fa-check"></i>Assessing how well a point pattern model fits the data</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-25-2023.html"><a href="tuesday-april-25-2023.html#an-example-of-a-point-process-model-in-the-wild"><i class="fa fa-check"></i>An example of a point process model in the wild</a></li>
<li class="chapter" data-level="" data-path="tuesday-april-25-2023.html"><a href="tuesday-april-25-2023.html#spatial-logistic-regression"><i class="fa fa-check"></i>Spatial logistic regression</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GIS5122: Applied Spatial Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="tuesday-april-18-2023" class="section level1 unnumbered hasAnchor">
<h1>Tuesday April 18, 2023<a href="tuesday-april-18-2023.html#tuesday-april-18-2023" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>“Weeks of coding can save you hours of planning.”</strong> - Unknown</p>
<div id="models-for-point-pattern-data" class="section level2 unnumbered hasAnchor">
<h2>Models for point pattern data<a href="tuesday-april-18-2023.html#models-for-point-pattern-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Models are helpful in trying to understanding the processes leading to the event locations when event interaction is suspected. Event interaction means that an event at one location changes the probability of an event nearby</p>
<p>Cluster models can be derived by starting with a Poisson model. For example, you begin with a homogeneous Poisson model describing a set of events <span class="math inline">\(Y\)</span>. Then each individual event <span class="math inline">\(y_i\)</span> in <span class="math inline">\(Y\)</span> is considered a ‘parent’ that produces ‘offspring’ events (<span class="math inline">\(x_i\)</span>) according to some mechanism</p>
<p>The resulting set of offspring forms clustered point pattern data <span class="math inline">\(X\)</span>. Said another way, the model is homogeneous Poisson at an unobserved level <span class="math inline">\(Y\)</span> (latent level) but clustered at the level of the observations (<span class="math inline">\(X\)</span>)</p>
<p>One example of this parent-child process is the Matérn cluster model. Parent events come from a homogeneous Poisson process with intensity <span class="math inline">\(\kappa\)</span> and then each parent has a Poisson (<span class="math inline">\(\mu\)</span>) number of offspring that are independent and identically distributed (iid) within a radius <span class="math inline">\(r\)</span> centered on the parent</p>
<p>For instance here you use the <code>rMatClust()</code> function from the {spatstat} package to produce a clustered <code>ppp</code> object. You use a disc radius of .1 units and an offspring rate equal to 5 (<code>mu = 5</code>)</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="tuesday-april-18-2023.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spatstat)</span></code></pre></div>
<pre><code>## Loading required package: spatstat.data</code></pre>
<pre><code>## Loading required package: spatstat.geom</code></pre>
<pre><code>## spatstat.geom 3.0-6</code></pre>
<pre><code>## Loading required package: spatstat.random</code></pre>
<pre><code>## spatstat.random 3.1-3</code></pre>
<pre><code>## Loading required package: spatstat.explore</code></pre>
<pre><code>## Loading required package: nlme</code></pre>
<pre><code>## spatstat.explore 3.0-6</code></pre>
<pre><code>## Loading required package: spatstat.model</code></pre>
<pre><code>## Loading required package: rpart</code></pre>
<pre><code>## spatstat.model 3.1-2</code></pre>
<pre><code>## Loading required package: spatstat.linnet</code></pre>
<pre><code>## spatstat.linnet 3.0-4</code></pre>
<pre><code>## 
## spatstat 3.0-3 
## For an introduction to spatstat, type &#39;beginner&#39;</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="tuesday-april-18-2023.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rMatClust</span>(<span class="at">kappa =</span> <span class="dv">10</span>, </span>
<span id="cb16-2"><a href="tuesday-april-18-2023.html#cb16-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">r =</span> .<span class="dv">1</span>, </span>
<span id="cb16-3"><a href="tuesday-april-18-2023.html#cb16-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">mu =</span> <span class="dv">5</span>) <span class="sc">|&gt;</span></span>
<span id="cb16-4"><a href="tuesday-april-18-2023.html#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="at">main =</span> <span class="st">&quot;&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>The result is a set of event locations and the process that produced them is described as <em>doubly Poisson</em>. You can vary <span class="math inline">\(\kappa\)</span>, <span class="math inline">\(r\)</span>, and <span class="math inline">\(\mu\)</span> to generate more or fewer events</p>
<p>Other clustered Poisson models include
- Thomas model: each cluster consists of a Poisson number of random events with each event having an isotropic Gaussian displacement from its parent
- Gauss-Poisson model: each cluster is either a single event or a pair of events.
- Neyman-Scott model: the cluster mechanism is arbitrary</p>
<p>A Cox model is a homogeneous Poisson model with a random intensity function. Let <span class="math inline">\(\Lambda(s)\)</span> be a function with non-negative values defined at all points <span class="math inline">\(s\)</span> inside the domain. Then at each point let <span class="math inline">\(X\)</span> be a Poisson model with an intensity <span class="math inline">\(\Lambda\)</span>. Then <span class="math inline">\(X\)</span> will be a sample from a Cox model</p>
<p>A Cox model is doubly Poisson since <span class="math inline">\(\Lambda\)</span> is generated from some distribution that allow only positive numbers and then, conditional on <span class="math inline">\(\Lambda\)</span>, a homogeneous point process is generated</p>
<p>Following are two samples from a Cox point process</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="tuesday-april-18-2023.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">3042</span>)</span>
<span id="cb17-2"><a href="tuesday-april-18-2023.html#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb17-3"><a href="tuesday-april-18-2023.html#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>){</span>
<span id="cb17-4"><a href="tuesday-april-18-2023.html#cb17-4" aria-hidden="true" tabindex="-1"></a>  lambda <span class="ot">&lt;-</span> <span class="fu">rexp</span>(<span class="at">n =</span> <span class="dv">1</span>, <span class="at">rate =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">100</span>)</span>
<span id="cb17-5"><a href="tuesday-april-18-2023.html#cb17-5" aria-hidden="true" tabindex="-1"></a>  X <span class="ot">&lt;-</span> <span class="fu">rpoispp</span>(lambda)</span>
<span id="cb17-6"><a href="tuesday-april-18-2023.html#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(X)</span>
<span id="cb17-7"><a href="tuesday-april-18-2023.html#cb17-7" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="tuesday-april-18-2023.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div>
<p>The statistical moments of Cox models are defined in terms of the moments of <span class="math inline">\(\Lambda\)</span>. For instance, the intensity function of <span class="math inline">\(X\)</span> is <span class="math inline">\(\lambda(s)\)</span> = E[<span class="math inline">\(\Lambda(s)\)</span>], where E[] is the expected value</p>
<p>Cox models are convenient for describing clustered point pattern data. A Cox model is over-dispersed relative to a Poisson model (i.e. the variance of the number of events falling in any region of size A, is greater than the mean number of events in those regions)</p>
<p>The Matérn cluster model and the Thomas models are types of Cox models. Another common type of Cox model is the log-Gaussian Cox processes (LGCP) model in which the logarithm of <span class="math inline">\(\Lambda(s)\)</span> is a Gaussian random function</p>
<p>If you have a way of generating samples from a random function <span class="math inline">\(\Lambda\)</span> of interest, then you can use the <code>rpoispp()</code> function to generate the Cox process. The intensity argument <code>lambda</code> of <code>rpoispp()</code> can be a function of x or y or a pixel image</p>
<p>Another way to generate clustered point pattern data is by ‘thinning’. Thinning refers to deleting some of the events. With ‘independent thinning’ the fate of each event is independent of the fate of the other events. When independent thinning is applied to a homogeneous Poisson point pattern, the resulting point pattern consisting of the retained events is also Poisson</p>
<p>An example of this is Matérn’s Model I model. Here a homogeneous Poisson model first generates a point pattern <span class="math inline">\(Y\)</span>, then any event in <span class="math inline">\(Y\)</span> that lies closer than a distance <span class="math inline">\(r\)</span> from another event is deleted. This results in point pattern data whereby close neighbor events do not exist</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="tuesday-april-18-2023.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">rMaternI</span>(<span class="at">kappa =</span> <span class="dv">7</span>, </span>
<span id="cb19-2"><a href="tuesday-april-18-2023.html#cb19-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">r =</span> .<span class="dv">05</span>), </span>
<span id="cb19-3"><a href="tuesday-april-18-2023.html#cb19-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="tuesday-april-18-2023.html#cb20-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">rMaternI</span>(<span class="at">kappa =</span> <span class="dv">70</span>, </span>
<span id="cb20-2"><a href="tuesday-april-18-2023.html#cb20-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">r =</span> .<span class="dv">05</span>)</span>
<span id="cb20-3"><a href="tuesday-april-18-2023.html#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="tuesday-april-18-2023.html#cb20-4" aria-hidden="true" tabindex="-1"></a>X <span class="sc">|&gt;</span></span>
<span id="cb20-5"><a href="tuesday-april-18-2023.html#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Kest</span>() <span class="sc">|&gt;</span></span>
<span id="cb20-6"><a href="tuesday-april-18-2023.html#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-3-2.png" width="672" /></p>
<p>Changing <span class="math inline">\(\kappa\)</span> and <span class="math inline">\(r\)</span> will change the event intensity</p>
<p>The various spatial models for event locations can be described with math. For instance, expanding on the earlier notation you write that a homogeneous Poisson model with intensity <span class="math inline">\(\lambda &gt; 0\)</span> has intensity</p>
<p><span class="math display">\[\lambda(s, x) = \lambda\]</span> where <span class="math inline">\(s\)</span> is any location in the window W and <span class="math inline">\(x\)</span> is the set of events</p>
<p>Then the inhomogeneous Poisson model has conditional intensity</p>
<p><span class="math display">\[\lambda(s, x) = \lambda(s)\]</span></p>
<p>The intensity <span class="math inline">\(\lambda(s)\)</span> depends on a spatial trend or on an explanatory variable</p>
<p>There is also a class of ‘Markov’ point process models that allow for clustering (or inhibition) due to event interaction. Markov refers to the fact that the interaction is limited to nearest neighbors. Said another way, a Markov point process generalizes a Poisson process in the case where events are pairwise dependent</p>
<p>A Markov process with parameters <span class="math inline">\(\beta &gt; 0\)</span> and <span class="math inline">\(0 &lt; \gamma &lt; \infty\)</span> with interaction radius <span class="math inline">\(r &gt; 0\)</span> has conditional intensity <span class="math inline">\(\lambda(s, x)\)</span> given by</p>
<p><span class="math display">\[
\lambda(s, x) = \beta \gamma^{t(s, x)}
\]</span></p>
<p>where <span class="math inline">\(t(s, x)\)</span> is the number of events that lie within a distance <span class="math inline">\(r\)</span> of location <span class="math inline">\(s\)</span></p>
<p>Three cases:
- If <span class="math inline">\(\gamma = 1\)</span>, then <span class="math inline">\(\lambda(s, x) = \beta\)</span> No interaction between events, <span class="math inline">\(\beta\)</span> can vary with <span class="math inline">\(s\)</span>
- If <span class="math inline">\(\gamma &lt; 1\)</span>, then <span class="math inline">\(\lambda(s, x) &lt; \beta\)</span>. Events inhibit nearby events
- If <span class="math inline">\(\gamma &gt; 1\)</span>, then <span class="math inline">\(\lambda(s, x) &gt; \beta\)</span>. Events encourage nearby events</p>
<p>Note the distinction between the interaction term <span class="math inline">\(\gamma\)</span> and the trend term <span class="math inline">\(\beta\)</span>. A similar distinction exists between autocorrelation <span class="math inline">\(\rho\)</span> and trend <span class="math inline">\(\beta\)</span> in spatial regression models</p>
<p>More generally, you write the logarithm of the conditional intensity <span class="math inline">\(\log[\lambda(s, x)]\)</span> as linear expression with two components</p>
<p><span class="math display">\[
\log\big[\lambda(s, x)\big] = \theta_1 B(s) + \theta_2 C(s, x)
\]</span></p>
<p>where the <span class="math inline">\(\theta\)</span>’s are model parameters that need to be estimated</p>
<p>The term <span class="math inline">\(B(s)\)</span> depends only on location so it represents trend and explanatory variable (covariate) effects. It is the ‘systematic component’ of the model. The term <span class="math inline">\(C(s, x)\)</span> represents stochastic interactions (dependency) between events</p>
</div>
<div id="fitting-and-interpreting-inhibition-models" class="section level2 unnumbered hasAnchor">
<h2>Fitting and interpreting inhibition models<a href="tuesday-april-18-2023.html#fitting-and-interpreting-inhibition-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The {spatstat} family of packages contains functions for fitting statistical models to point pattern data. Models can include trend, explanatory variables, and event interactions of any order (not restricted to pairwise). Models are fit with the method of maximum likelihood and the method of minimum contrasts</p>
<p>The method of maximum likelihood estimates the probability of the empirical <span class="math inline">\(K\)</span> curve given the theoretical curve for various parameter values. Parameter values are chosen so as to maximize the likelihood of the empirical curve</p>
<p>The method of minimum contrasts derives a cost function as the difference between the theoretical and empirical <span class="math inline">\(K\)</span> curves. Parameter values for the theoretical curve are those that minimize this cost function</p>
<p>The <code>ppm()</code> function from {spatstat} is used to fit a spatial point pattern model. The syntax has the form <code>ppm(X, formula, interaction, ...)</code> where <code>X</code> is the point pattern object of class <code>ppp</code>, <code>formula</code> describes the systematic (trend and covariate) part of the model, and <code>interaction</code> describes the stochastic dependence between events (e.g., Matérn process)</p>
<p>Recall a plot the Swedish pine saplings. There was no indication of a trend (no systematic variation in the intensity of saplings)</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="tuesday-april-18-2023.html#cb21-1" aria-hidden="true" tabindex="-1"></a>SP <span class="ot">&lt;-</span> swedishpines</span>
<span id="cb21-2"><a href="tuesday-april-18-2023.html#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="tuesday-april-18-2023.html#cb21-3" aria-hidden="true" tabindex="-1"></a>SP <span class="sc">|&gt;</span></span>
<span id="cb21-4"><a href="tuesday-april-18-2023.html#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="tuesday-april-18-2023.html#cb22-1" aria-hidden="true" tabindex="-1"></a>SP <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="tuesday-april-18-2023.html#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">intensity</span>()</span></code></pre></div>
<pre><code>## [1] 0.007395833</code></pre>
<p>There is no obvious spatial trend in the distribution of saplings and the average intensity is .0074 saplings per unit area</p>
<p>A plot of the Ripley’s <span class="math inline">\(K\)</span> function indicated some regularity relative to CSR for distances between .5 and 1.2 meters</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="tuesday-april-18-2023.html#cb24-1" aria-hidden="true" tabindex="-1"></a>SP <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="tuesday-april-18-2023.html#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Kest</span>(<span class="at">correction =</span> <span class="st">&quot;iso&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb24-3"><a href="tuesday-april-18-2023.html#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>The red dashed line is the <span class="math inline">\(K\)</span> curve under CSR. The black line is the empirical curve. At lag distances of between 5 and 15 units the empirical curve is below the CSR curve indicating there are fewer events within other events at those scales than would be expected by chance</p>
<p>This suggests a process of between-event inhibition. A simple inhibition model is a Strauss process when the inhibition is constant with a fixed radius (r) around each event. The amount of inhibition ranges between zero (100% chance of a nearby event) to complete (0% chance of a nearby event). In the case of no inhibition the process is equivalent to a homogeneous Poisson process</p>
<p>If you assume the inhibition process is constant across the domain with a fixed interaction radius (r), then you can fit a Strauss model to the data. You use the <code>ppm()</code> function from the {spatstat} package and include the point pattern data as the first argument. You set the trend term to a constant (implying a stationary process) with the argument <code>trend ~ 1</code> and the interaction radius to 10 units with the argument <code>interaction = Strauss(r = 10)</code>. Finally you use a border correction out to a distance of 10 units from the window with the <code>rbord =</code> argument</p>
<p>Save the output in the object called <code>model.in</code> (inhibition model)</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="tuesday-april-18-2023.html#cb25-1" aria-hidden="true" tabindex="-1"></a>model.in <span class="ot">&lt;-</span> <span class="fu">ppm</span>(SP, </span>
<span id="cb25-2"><a href="tuesday-april-18-2023.html#cb25-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">trend =</span> <span class="sc">~</span> <span class="dv">1</span>, </span>
<span id="cb25-3"><a href="tuesday-april-18-2023.html#cb25-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">interaction =</span> <span class="fu">Strauss</span>(<span class="at">r =</span> <span class="dv">10</span>), </span>
<span id="cb25-4"><a href="tuesday-april-18-2023.html#cb25-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">rbord =</span> <span class="dv">10</span>)</span></code></pre></div>
<p>The value for <code>r</code> in the <code>Strauss()</code> function is based on our visual inspection of the plot of <code>Kest()</code>. A value is chosen to be the distance at which there is the largest departure from a CSR model</p>
<p>You inspect the model parameters by typing the object name</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="tuesday-april-18-2023.html#cb26-1" aria-hidden="true" tabindex="-1"></a>model.in</span></code></pre></div>
<pre><code>## Stationary Strauss process
## 
## First order term:  beta = 0.07567442
## 
## Interaction distance:    10
## Fitted interaction parameter gamma:  0.2752048
## 
## Relevant coefficients:
## Interaction 
##    -1.29024 
## 
## For standard errors, type coef(summary(x))</code></pre>
<p>The first-order term (<code>beta</code>) has a value of .0757. This is the intensity of the ‘proposal’ events. Beta exceeds the average intensity by a factor of ten</p>
<p>Recall the intensity of the events is obtained as</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="tuesday-april-18-2023.html#cb28-1" aria-hidden="true" tabindex="-1"></a>SP <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a href="tuesday-april-18-2023.html#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">intensity</span>()</span></code></pre></div>
<pre><code>## [1] 0.007395833</code></pre>
<p>The interaction parameter (<code>gamma</code>) is .275. It is less than one, indicating an inhibition process. The logarithm of gamma, called the interaction coefficient (<code>Interaction</code>), is -1.29. Interaction coefficients less than zero imply inhibition</p>
<p>A table with the coefficients including the standard errors and uncertainty ranges is obtained with the <code>coef()</code> method</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="tuesday-april-18-2023.html#cb30-1" aria-hidden="true" tabindex="-1"></a>model.in <span class="sc">|&gt;</span></span>
<span id="cb30-2"><a href="tuesday-april-18-2023.html#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>() <span class="sc">|&gt;</span></span>
<span id="cb30-3"><a href="tuesday-april-18-2023.html#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coef</span>()</span></code></pre></div>
<pre><code>##              Estimate      S.E.   CI95.lo    CI95.hi Ztest      Zval
## (Intercept) -2.581315 0.4524077 -3.468018 -1.6946123   *** -5.705728
## Interaction -1.290240 0.2375515 -1.755832 -0.8246475   *** -5.431411</code></pre>
<p>The output includes the <code>Interaction</code> coefficient along with it’s standard error (<code>S.E.</code>) and the associated 95% uncertainty interval. The ratio of the <code>Interaction</code> coefficient to its standard error is the <code>Zval</code>. A large z-value (in absolute magnitude) translates to a low <span class="math inline">\(p\)</span>-value and a rejection of the null hypothesis of no interaction between events</p>
<p>Output also shows the value for the <code>(Intercept)</code> term. It is the logarithm of the beta value, so exp(-2.58) = .0757 is the intensity of the proposal events</p>
<p>You interpret the model output as follows. The process producing the spatial pattern of pine saplings is such that you should see .0757 saplings per unit area [unobserved (latent) rate]</p>
<p>But because of event inhibition, where saplings nearby other saplings fail to grow, the number of saplings is reduced to .0074 per unit area. Thus the spatial pattern is suggestive of sibling-sibling interaction. Adults have many offspring, but only some survive due to limited resources</p>
</div>
<div id="fitting-and-interpreting-cluster-models" class="section level2 unnumbered hasAnchor">
<h2>Fitting and interpreting cluster models<a href="tuesday-april-18-2023.html#fitting-and-interpreting-cluster-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s compare this inhibition model with a cluster model for describing the Lansing Woods maple trees (in the <code>ppp</code> object called <code>lansing</code> from the {spatstat} package)</p>
<p>Start by extracting the events marked as <code>maple</code> and putting them in a separate <code>ppp</code> object called <code>MT</code></p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="tuesday-april-18-2023.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(lansing)</span>
<span id="cb32-2"><a href="tuesday-april-18-2023.html#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lansing)</span></code></pre></div>
<pre><code>## Marked planar point pattern:  2251 points
## Average intensity 2251 points per square unit (one unit = 924 feet)
## 
## *Pattern contains duplicated points*
## 
## Coordinates are given to 3 decimal places
## i.e. rounded to the nearest multiple of 0.001 units (one unit = 924 feet)
## 
## Multitype:
##          frequency proportion intensity
## blackoak       135 0.05997335       135
## hickory        703 0.31230560       703
## maple          514 0.22834300       514
## misc           105 0.04664594       105
## redoak         346 0.15370950       346
## whiteoak       448 0.19902270       448
## 
## Window: rectangle = [0, 1] x [0, 1] units
## Window area = 1 square unit
## Unit of length: 924 feet</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="tuesday-april-18-2023.html#cb34-1" aria-hidden="true" tabindex="-1"></a>MT <span class="ot">&lt;-</span> lansing <span class="sc">|&gt;</span></span>
<span id="cb34-2"><a href="tuesday-april-18-2023.html#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">subset</span>(marks <span class="sc">==</span> <span class="st">&quot;maple&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb34-3"><a href="tuesday-april-18-2023.html#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unmark</span>()</span>
<span id="cb34-4"><a href="tuesday-april-18-2023.html#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="tuesday-april-18-2023.html#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(MT)</span></code></pre></div>
<pre><code>## Planar point pattern:  514 points
## Average intensity 514 points per square unit (one unit = 924 feet)
## 
## Coordinates are given to 3 decimal places
## i.e. rounded to the nearest multiple of 0.001 units (one unit = 924 feet)
## 
## Window: rectangle = [0, 1] x [0, 1] units
## Window area = 1 square unit
## Unit of length: 924 feet</code></pre>
<p>There are 514 maple trees over this square region (924 x 924 square feet).</p>
<p>Plots of tree locations and the local intensity function help you examine the first-order property of these data.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="tuesday-april-18-2023.html#cb36-1" aria-hidden="true" tabindex="-1"></a>MT <span class="sc">|&gt;</span></span>
<span id="cb36-2"><a href="tuesday-april-18-2023.html#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">density</span>() <span class="sc">|&gt;</span></span>
<span id="cb36-3"><a href="tuesday-april-18-2023.html#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span>
<span id="cb36-4"><a href="tuesday-april-18-2023.html#cb36-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-5"><a href="tuesday-april-18-2023.html#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(MT, <span class="at">add =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>There are maple trees across the southern and central parts of the study domain</p>
<p>A plot of the <span class="math inline">\(G\)</span> function summarizes the second-order properties under the assumption of no trend</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="tuesday-april-18-2023.html#cb37-1" aria-hidden="true" tabindex="-1"></a>G.df <span class="ot">&lt;-</span> MT <span class="sc">|&gt;</span></span>
<span id="cb37-2"><a href="tuesday-april-18-2023.html#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Gest</span>() <span class="sc">|&gt;</span></span>
<span id="cb37-3"><a href="tuesday-april-18-2023.html#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb37-4"><a href="tuesday-april-18-2023.html#cb37-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(r <span class="sc">&lt;</span> .<span class="dv">033</span>) <span class="sc">|&gt;</span></span>
<span id="cb37-5"><a href="tuesday-april-18-2023.html#cb37-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">r =</span> r <span class="sc">*</span> <span class="dv">924</span>)</span>
<span id="cb37-6"><a href="tuesday-april-18-2023.html#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="tuesday-april-18-2023.html#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb37-8"><a href="tuesday-april-18-2023.html#cb37-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-9"><a href="tuesday-april-18-2023.html#cb37-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(G.df, <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> km)) <span class="sc">+</span></span>
<span id="cb37-10"><a href="tuesday-april-18-2023.html#cb37-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb37-11"><a href="tuesday-april-18-2023.html#cb37-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb37-12"><a href="tuesday-april-18-2023.html#cb37-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">18</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb37-13"><a href="tuesday-april-18-2023.html#cb37-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (ft)&quot;</span>) <span class="sc">+</span> </span>
<span id="cb37-14"><a href="tuesday-april-18-2023.html#cb37-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;G(r): Cumulative % of events within a distance r of another maple&quot;</span>) <span class="sc">+</span></span>
<span id="cb37-15"><a href="tuesday-april-18-2023.html#cb37-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>The plot provides evidence that the maple trees are clustered. The empirical curve is above the theoretical curve. About 74% of the maple trees are within 18 feet of another maple tree (vertical line). If the trees were arranged as CSR then only 49% of the trees would be within 18 feet of another maple</p>
<p>Is the clustering due to interaction or trends (or both)?</p>
<p>You start the modeling process by investigating event interaction using a stationary Strauss model with interaction radius of .019 units (18 ft)</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="tuesday-april-18-2023.html#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ppm</span>(MT, </span>
<span id="cb38-2"><a href="tuesday-april-18-2023.html#cb38-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">trend =</span> <span class="sc">~</span> <span class="dv">1</span>, </span>
<span id="cb38-3"><a href="tuesday-april-18-2023.html#cb38-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">interaction =</span> <span class="fu">Strauss</span>(<span class="at">r =</span> .<span class="dv">019</span>))</span></code></pre></div>
<pre><code>## Stationary Strauss process
## 
## First order term:  beta = 344.625
## 
## Interaction distance:    0.019
## Fitted interaction parameter gamma:  1.7253743
## 
## Relevant coefficients:
## Interaction 
##    0.545444 
## 
## For standard errors, type coef(summary(x))
## 
## *** Model is not valid ***
## *** Interaction parameters are outside valid range ***</code></pre>
<p>Here the first order term beta is 345. It is the ‘latent’ rate (intensity) of maple trees per unit area. This rate is less than the 514 actual maple trees. The fitted interaction parameter (gamma) is 1.72. It is greater than one since the trees are clustered. The logarithm of gamma is positive at .545</p>
<p>The model is interpreted as follows. The process producing the maple trees is such that you expect to see about 345 maples. Because of clustering where maple trees are more likely in the vicinity of other maple trees, the number of maples increases to the observed 514 per unit area</p>
<p>Here the physical explanation could be event interaction. But it also could be inhibition with hickory trees. You can model this using a term for cross event type interaction</p>
<p>The Strauss process is for inhibition models. So although you use it here for diagnostics, you need to fit a cluster model (thus the <code>*** Model is not valid ***</code> warning)</p>
<p>For a cluster model the spatial intensity <span class="math display">\[\lambda(s) = \kappa \mu(s)\]</span> where <span class="math inline">\(\kappa\)</span> is the average number of clusters and where <span class="math inline">\(\mu(s)\)</span> is the spatial varying cluster size (number events per cluster)</p>
<p>Cluster models are fit using the <code>kppm()</code> function from the {spatstat} package. Here you specify the cluster process with <code>clusters = "Thomas"</code></p>
<p>That means each cluster consists of a Poisson number of maple trees and where each tree in the cluster is placed randomly about the ‘parent’ tree with intensity that varies inversely with distance from the parent as a Gaussian function</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="tuesday-april-18-2023.html#cb40-1" aria-hidden="true" tabindex="-1"></a>( model.cl <span class="ot">&lt;-</span> <span class="fu">kppm</span>(MT, </span>
<span id="cb40-2"><a href="tuesday-april-18-2023.html#cb40-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">trend =</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb40-3"><a href="tuesday-april-18-2023.html#cb40-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">clusters =</span> <span class="st">&quot;Thomas&quot;</span>) )</span></code></pre></div>
<pre><code>## Stationary cluster point process model
## Fitted to point pattern dataset &#39;MT&#39;
## Fitted by minimum contrast
##  Summary statistic: K-function
## 
## Uniform intensity:   514
## 
## Cluster model: Thomas process
## Fitted cluster parameters:
##       kappa       scale 
## 21.74344366  0.06752959 
## Mean cluster size:  23.63931 points
## 
## Cluster strength: phi =  0.8026
## Sibling probability: psib =  0.4452</code></pre>
<p>Here <span class="math inline">\(\kappa\)</span> is 21.75 and <span class="math inline">\(\bar \mu(s)\)</span> (mean cluster size) is 23.6 trees. The product of kappa and the mean cluster size is the number of events. The cluster model describes a parent-child process. The number of parents is about 22. The distribution of the parents can be described as CSR. Each parent produces about 24 offspring distributed randomly about the location of the parent within a characteristic distance. Note: The physical process might be different from the statistical process used to describe it</p>
<p>The cluster scale parameter indicating the characteristic size (area units) of the clusters is <span class="math inline">\(\sigma^2\)</span></p>
<p>A <code>plot()</code> method verifies that the cluster process statistically ‘explains’ the spatial correlation.=</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="tuesday-april-18-2023.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model.cl, </span>
<span id="cb42-2"><a href="tuesday-april-18-2023.html#cb42-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">what =</span> <span class="st">&quot;statistic&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>The model (black line) is very close to the cluster process line (red dashed line). Also note that it is far from the CSR model (green line)</p>
<p>The spatial scale of the clustering is visualized with the <code>what = "cluster"</code> argument</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="tuesday-april-18-2023.html#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model.cl, </span>
<span id="cb43-2"><a href="tuesday-april-18-2023.html#cb43-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">what =</span> <span class="st">&quot;cluster&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>The color ramp is the spatial intensity (number of events per unit area) about an arbitrary single event revealing the spatial scale and extent of clustering</p>
</div>
<div id="fitting-and-interpreting-a-log-gaussian-cox-cluster-model" class="section level2 unnumbered hasAnchor">
<h2>Fitting and interpreting a log-Gaussian Cox (cluster) model<a href="tuesday-april-18-2023.html#fitting-and-interpreting-a-log-gaussian-cox-cluster-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The Thomas cluster model is a type of Cox process where the logarithm of the spatial intensity is a sample from a non-negative random variable. If the dispersion of events around other events is uniform rather than Gaussian than you fit a Matérn cluster model</p>
<p>A limitation of the Thomas and Matérn cluster models is that the samples are assumed to be <em>spatially independent</em>. Nearby locations might have different spatial intensities</p>
<p>If there is a systematic trend or covariate influence on the spatial intensity then you can include this in the model</p>
<p>A related but more flexible process is the log-Gaussian Cox process (LGCP). A LGCP has a hierarchical structure, where at the first level the events are assumed to be drawn from a Poisson distribution conditional on the intensity function, and at the second level the log of the intensity function is assumed to be drawn from a Gaussian process. That is, the log spatial intensity values are <em>spatially correlated</em></p>
<p>The flexibility of the model arises from the Gaussian process prior specified over the log-intensity function. Given this hierarchical structure with a Gaussian process at the second level, fitting this model to observed spatial point pattern data is a computational challenge</p>
<p>One way is through the method of stochastic partial differential equations (SPDE), which involves a probability (Bayesian) framework to approximate posterior distributions</p>
<p>To see how this works and to get a glimpse of the Bayesian framework, here you consider a 1D space and you fit the model using functions from the {inlabru} and {INLA} packages</p>
<p>Example modified from <a href="https://inlabru-org.github.io/inlabru/articles/web/1d_lgcp.html" class="uri">https://inlabru-org.github.io/inlabru/articles/web/1d_lgcp.html</a></p>
<p>Install and make the packages available to this session</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="tuesday-april-18-2023.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(inlabru)</span></code></pre></div>
<pre><code>## Loading required package: sp</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="tuesday-april-18-2023.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(INLA)</span></code></pre></div>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## Loading required package: foreach</code></pre>
<pre><code>## Loading required package: parallel</code></pre>
<pre><code>## This is INLA_22.05.07 built 2022-05-07 09:58:26 UTC.
##  - See www.r-inla.org/contact-us for how to get help.
##  - To enable PARDISO sparse library; see inla.pardiso()</code></pre>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="tuesday-april-18-2023.html#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mgcv)</span></code></pre></div>
<pre><code>## This is mgcv 1.8-41. For overview type &#39;help(&quot;mgcv-package&quot;)&#39;.</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="tuesday-april-18-2023.html#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code></pre></div>
<p>Get the data to model from the {inlabru} package using the <code>data(Poisson2_1D)</code> function. The data are in the object <code>pts2</code></p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="tuesday-april-18-2023.html#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Poisson2_1D)</span>
<span id="cb54-2"><a href="tuesday-april-18-2023.html#cb54-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-3"><a href="tuesday-april-18-2023.html#cb54-3" aria-hidden="true" tabindex="-1"></a>pts2 <span class="sc">|&gt;</span></span>
<span id="cb54-4"><a href="tuesday-april-18-2023.html#cb54-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 130
## Columns: 1
## $ x &lt;dbl&gt; 25.1064528, 9.1504482, 17.8802463, 28.0073385, 1.8994489, 8.3805420,…</code></pre>
<p>The object <code>pts2</code> is a one column data frame with column name <code>x</code></p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="tuesday-april-18-2023.html#cb56-1" aria-hidden="true" tabindex="-1"></a>pts2 <span class="sc">|&gt;</span></span>
<span id="cb56-2"><a href="tuesday-april-18-2023.html#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">range</span>()</span></code></pre></div>
<pre><code>## [1]  0.3293196 51.0375325</code></pre>
<p>The values of <code>x</code> are strictly positive between .33 and 51</p>
<p>Plot the data as points along a horizontal line together with a histogram estimating the 1D spatial intensity. Here you choose about 20 bins across the range of values from 0 to 55</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="tuesday-april-18-2023.html#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> pts2) <span class="sc">+</span></span>
<span id="cb58-2"><a href="tuesday-april-18-2023.html#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> x), </span>
<span id="cb58-3"><a href="tuesday-april-18-2023.html#cb58-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">binwidth =</span> <span class="dv">55</span> <span class="sc">/</span> <span class="dv">20</span>, </span>
<span id="cb58-4"><a href="tuesday-april-18-2023.html#cb58-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">boundary =</span> <span class="dv">0</span>, </span>
<span id="cb58-5"><a href="tuesday-april-18-2023.html#cb58-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="cn">NA</span>, </span>
<span id="cb58-6"><a href="tuesday-april-18-2023.html#cb58-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb58-7"><a href="tuesday-april-18-2023.html#cb58-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> x), </span>
<span id="cb58-8"><a href="tuesday-april-18-2023.html#cb58-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> <span class="dv">0</span>, <span class="at">pch =</span> <span class="st">&quot;|&quot;</span>, <span class="at">cex =</span> <span class="dv">4</span>) </span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>The histogram is a discrete version of the spatial intensity. It shows that events along the horizontal axis tend to be most common near the value of 20</p>
<p>Your goal is a smoothed estimate of the 1-D spatial intensity taking into account event clustering</p>
<p>First create a 1D mesh of 50 points (<code>length.out =</code>) across the range of values (from 0 to 55). The end points of the mesh are unconstrained by setting <code>boundary = "free"</code>. Assign the mesh to an object with name <code>mesh1D</code></p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="tuesday-april-18-2023.html#cb59-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, </span>
<span id="cb59-2"><a href="tuesday-april-18-2023.html#cb59-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">to =</span> <span class="dv">55</span>, </span>
<span id="cb59-3"><a href="tuesday-april-18-2023.html#cb59-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">length.out =</span> <span class="dv">50</span>)</span>
<span id="cb59-4"><a href="tuesday-april-18-2023.html#cb59-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-5"><a href="tuesday-april-18-2023.html#cb59-5" aria-hidden="true" tabindex="-1"></a>mesh1D <span class="ot">&lt;-</span> <span class="fu">inla.mesh.1d</span>(<span class="at">loc =</span> x, </span>
<span id="cb59-6"><a href="tuesday-april-18-2023.html#cb59-6" aria-hidden="true" tabindex="-1"></a>                       <span class="at">boundary =</span> <span class="st">&quot;free&quot;</span>)</span></code></pre></div>
<p>Then specify the <em>prior</em> spatial correlation as a Matérn cluster model</p>
<p>The first argument is the mesh onto which the model will be built and the next two arguments are the prior distributions for the range and standard deviation of the spatial correlation</p>
<p>This allows you to control the priors of the parameters by supplying information on the scale of the problem. What is a reasonable upper magnitude for the spatial effect and what is a reasonable lower scale at which the spatial effect can operate?</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="tuesday-april-18-2023.html#cb60-1" aria-hidden="true" tabindex="-1"></a>Matern <span class="ot">&lt;-</span> <span class="fu">inla.spde2.pcmatern</span>(<span class="at">mesh =</span> mesh1D, </span>
<span id="cb60-2"><a href="tuesday-april-18-2023.html#cb60-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">prior.range =</span> <span class="fu">c</span>(<span class="dv">150</span>, .<span class="dv">75</span>),</span>
<span id="cb60-3"><a href="tuesday-april-18-2023.html#cb60-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">prior.sigma =</span> <span class="fu">c</span>(.<span class="dv">1</span>, .<span class="dv">75</span>))</span></code></pre></div>
<pre><code>## as(&lt;dtCMatrix&gt;, &quot;dgCMatrix&quot;) is deprecated since Matrix 1.5-0; do as(., &quot;generalMatrix&quot;) instead</code></pre>
<p>The argument <code>prior.range =</code> accepts a vector of length two with the first element the lag distance (range) of the spatial correlation and the second element the probability that the range will be less than that value. If the second value is <code>NA</code>, the value of the first element is used as a fixed range</p>
<p>The argument <code>prior.sigma =</code> accepts a vector of length two with the first element the marginal standard deviation of the spatial intensity and the second element the probability that the standard deviation will be greater than that value</p>
<p>Here you are non-committal on the range of spatial correlation so you specify a large distance (150) with a 75% chance that it will be less than that. That is you give a broad range to the prior</p>
<p>Values for <code>prior.range</code> and <code>prior.sigma</code> are called hyper-parameters</p>
<p><em>Key idea</em>: In the frequentist context you are interested in the likelihood of the data given the model P(D | M). In a Bayesian context, you are interested in the probability of the model given the data P(M | D). This is called the posterior. You get from P(D | M) to P(M | D) by multiplying the likelihood by the priors P(M). This requires you to specify the priors</p>
<p>Next specify the full model and assign it to the object <code>f</code></p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="tuesday-april-18-2023.html#cb62-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> x <span class="sc">~</span> <span class="fu">spde1D</span>(x, <span class="at">model =</span> Matern) <span class="sc">+</span> <span class="fu">Intercept</span>(<span class="dv">1</span>)</span></code></pre></div>
<p>Next fit the model to the actual event locations in <code>pts2</code>. You use the log Gaussian Cox process <code>lgcp()</code> function from the {inlabru} package. The <code>domain =</code> argument specifies the 1D mesh as a list object</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="tuesday-april-18-2023.html#cb63-1" aria-hidden="true" tabindex="-1"></a>model.lgcp <span class="ot">&lt;-</span> <span class="fu">lgcp</span>(<span class="at">components =</span> f, </span>
<span id="cb63-2"><a href="tuesday-april-18-2023.html#cb63-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> pts2, </span>
<span id="cb63-3"><a href="tuesday-april-18-2023.html#cb63-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">domain =</span> <span class="fu">list</span>(<span class="at">x =</span> mesh1D))</span></code></pre></div>
<p>You look at the output posterior distributions of the model parameters using the <code>spde.posterior()</code> function. The function returns x and y values for a plot of the posterior probability density function (PDF) as a data frame, which you plot with the <code>plot.bru()</code> function (<code>plot()</code> method)</p>
<p>Start with the probability density function for the range parameter by specifying <code>what = "range"</code></p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="tuesday-april-18-2023.html#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">spde.posterior</span>(<span class="at">result =</span> model.lgcp, </span>
<span id="cb64-2"><a href="tuesday-april-18-2023.html#cb64-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">name =</span> <span class="st">&quot;spde1D&quot;</span>, </span>
<span id="cb64-3"><a href="tuesday-april-18-2023.html#cb64-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">what =</span> <span class="st">&quot;range&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb64-4"><a href="tuesday-april-18-2023.html#cb64-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>The prior range value was specified broadly but the posterior range is focused on values between 2.5 and 5. The output is better viewed on a logarithmic scale by specifying <code>what = "log.range"</code></p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="tuesday-april-18-2023.html#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">spde.posterior</span>(model.lgcp, </span>
<span id="cb65-2"><a href="tuesday-april-18-2023.html#cb65-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">name =</span> <span class="st">&quot;spde1D&quot;</span>, </span>
<span id="cb65-3"><a href="tuesday-april-18-2023.html#cb65-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">what =</span> <span class="st">&quot;log.range&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb65-4"><a href="tuesday-april-18-2023.html#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>Next you plot the probability density function for the Matérn correlation component of the model</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="tuesday-april-18-2023.html#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">spde.posterior</span>(model.lgcp, </span>
<span id="cb66-2"><a href="tuesday-april-18-2023.html#cb66-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">name =</span> <span class="st">&quot;spde1D&quot;</span>, </span>
<span id="cb66-3"><a href="tuesday-april-18-2023.html#cb66-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">what =</span> <span class="st">&quot;matern.correlation&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb66-4"><a href="tuesday-april-18-2023.html#cb66-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p>The black line is the posterior median correlation as a function of lag distance. The maximum correlation of 1 at zero lag distance decays to .5 correlation out at a distance of about 20 units</p>
<p>You can get a feel for sensitivity to priors by specifying different priors and looking at these posterior plots. Always a good idea when fitting models using Bayesian methods</p>
<p>For example, change the prior range from 150 to 30 and refit the model. Compare the probability density function of the Matérn correlation</p>
<p>You predict on the ‘response’ scale [i.e. the intensity function <span class="math inline">\(\lambda\)</span>(s)] as follows. First set up a data frame of explanatory values at which to predict (here <code>grid.df</code>). Then use the <code>predict()</code> method with <code>data = grid.df</code> and <code>formula = ~ exp(spde1D + Intercept</code>. It takes a few seconds to make predictions at each grid point location</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="tuesday-april-18-2023.html#cb67-1" aria-hidden="true" tabindex="-1"></a>grid.df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">55</span>, <span class="at">by =</span> <span class="dv">1</span>)) </span>
<span id="cb67-2"><a href="tuesday-april-18-2023.html#cb67-2" aria-hidden="true" tabindex="-1"></a>pred.df <span class="ot">&lt;-</span> <span class="fu">predict</span>(model.lgcp, </span>
<span id="cb67-3"><a href="tuesday-april-18-2023.html#cb67-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> grid.df, </span>
<span id="cb67-4"><a href="tuesday-april-18-2023.html#cb67-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">formula =</span> <span class="sc">~</span> <span class="fu">exp</span>(spde1D <span class="sc">+</span> Intercept))</span></code></pre></div>
<p>The output is a data frame containing the locations on the grid (<code>x</code>) and the corresponding summary statistics (mean, median, standard deviation, and quantiles) on the posterior predictions at those location</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="tuesday-april-18-2023.html#cb68-1" aria-hidden="true" tabindex="-1"></a>pred.df <span class="sc">|&gt;</span></span>
<span id="cb68-2"><a href="tuesday-april-18-2023.html#cb68-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 56
## Columns: 9
## $ x               &lt;dbl&gt; 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, …
## $ mean            &lt;dbl&gt; 1.889903, 1.965244, 2.079264, 2.192633, 2.317669, 2.44…
## $ sd              &lt;dbl&gt; 0.7277578, 0.5635577, 0.5140244, 0.4791365, 0.4671477,…
## $ q0.025          &lt;dbl&gt; 0.9064511, 1.0438830, 1.1939807, 1.3368514, 1.5529105,…
## $ q0.5            &lt;dbl&gt; 1.736144, 1.906014, 2.050241, 2.132197, 2.288178, 2.45…
## $ q0.975          &lt;dbl&gt; 3.325537, 3.065726, 3.031495, 3.149327, 3.240703, 3.40…
## $ median          &lt;dbl&gt; 1.736144, 1.906014, 2.050241, 2.132197, 2.288178, 2.45…
## $ mean.mc_std_err &lt;dbl&gt; 0.07277578, 0.05635577, 0.05140244, 0.04791365, 0.0467…
## $ sd.mc_std_err   &lt;dbl&gt; 0.10077055, 0.03425871, 0.02966621, 0.02899213, 0.0287…</code></pre>
<p>You pass this data frame to the <code>plot()</code> method to produce the following prediction plot using the grammar of graphics</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="tuesday-april-18-2023.html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pred.df, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb70-2"><a href="tuesday-april-18-2023.html#cb70-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> pts2, </span>
<span id="cb70-3"><a href="tuesday-april-18-2023.html#cb70-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> x), </span>
<span id="cb70-4"><a href="tuesday-april-18-2023.html#cb70-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> <span class="dv">0</span>, <span class="at">pch =</span> <span class="st">&quot;|&quot;</span>, <span class="at">cex =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb70-5"><a href="tuesday-april-18-2023.html#cb70-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;x&quot;</span>) <span class="sc">+</span> </span>
<span id="cb70-6"><a href="tuesday-april-18-2023.html#cb70-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Spatial intensity</span><span class="sc">\n</span><span class="st"> number of events per unit interval&quot;</span>) <span class="sc">+</span></span>
<span id="cb70-7"><a href="tuesday-april-18-2023.html#cb70-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<p>The LGCP model provides a smoothed spatial intensity of the events and a 95% credible interval about the intensity at each grid location. The intensity values are the number of events per unit interval</p>
<p>How does this compare with the intensity function that generated the data?</p>
<p>The function <code>lambda2_1D( )</code>in the data object <code>Poission2_1D</code> calculates the true intensity that was used in simulating the data</p>
<p>To plot this function you make a data frame with x- and y-coordinates giving the true intensity function, <span class="math inline">\(\lambda(s)\)</span>. Here you use 150 x-values to get a smooth plot</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="tuesday-april-18-2023.html#cb71-1" aria-hidden="true" tabindex="-1"></a>xs <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">55</span>, <span class="at">length =</span> <span class="dv">150</span>)</span>
<span id="cb71-2"><a href="tuesday-april-18-2023.html#cb71-2" aria-hidden="true" tabindex="-1"></a>true.lambda <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> xs, </span>
<span id="cb71-3"><a href="tuesday-april-18-2023.html#cb71-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">y =</span> <span class="fu">lambda2_1D</span>(xs))</span></code></pre></div>
<p>Now plot the LGCP model predicted values together with the true intensity function</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="tuesday-april-18-2023.html#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pred.df, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb72-2"><a href="tuesday-april-18-2023.html#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> pts2, </span>
<span id="cb72-3"><a href="tuesday-april-18-2023.html#cb72-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> x), </span>
<span id="cb72-4"><a href="tuesday-april-18-2023.html#cb72-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> <span class="dv">0</span>, <span class="at">pch =</span> <span class="st">&quot;|&quot;</span>, <span class="at">cex =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb72-5"><a href="tuesday-april-18-2023.html#cb72-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> true.lambda, </span>
<span id="cb72-6"><a href="tuesday-april-18-2023.html#cb72-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">mapping =</span> <span class="fu">aes</span>(x, y)) <span class="sc">+</span></span>
<span id="cb72-7"><a href="tuesday-april-18-2023.html#cb72-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;x&quot;</span>) <span class="sc">+</span> </span>
<span id="cb72-8"><a href="tuesday-april-18-2023.html#cb72-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Spatial intensity&quot;</span>) <span class="sc">+</span></span>
<span id="cb72-9"><a href="tuesday-april-18-2023.html#cb72-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p>The match is pretty good. Keep in mind that the data represents just one sample generated from the model</p>
<p>You can look at the goodness-of-fit of the model using the function <code>bincount( )</code>, which plots the 95% credible intervals in a set of bins along the x-axis together with the observed count in each bin</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="tuesday-april-18-2023.html#cb73-1" aria-hidden="true" tabindex="-1"></a>bc <span class="ot">&lt;-</span> <span class="fu">bincount</span>(</span>
<span id="cb73-2"><a href="tuesday-april-18-2023.html#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">result =</span> model.lgcp,</span>
<span id="cb73-3"><a href="tuesday-april-18-2023.html#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">observations =</span> pts2,</span>
<span id="cb73-4"><a href="tuesday-april-18-2023.html#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="fu">max</span>(pts2), <span class="at">length =</span> <span class="dv">12</span>),</span>
<span id="cb73-5"><a href="tuesday-april-18-2023.html#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">predictor =</span> x <span class="sc">~</span> <span class="fu">exp</span>(spde1D <span class="sc">+</span> Intercept)</span>
<span id="cb73-6"><a href="tuesday-april-18-2023.html#cb73-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb73-7"><a href="tuesday-april-18-2023.html#cb73-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-8"><a href="tuesday-april-18-2023.html#cb73-8" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(bc)<span class="sc">$</span>ggp</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<p>The credible intervals are shown as red rectangles, the mean fitted value as a short horizontal blue line, and the observed data as black points</p>
<p>Abundance is the integral of the intensity over the entire space. Here space is 1D and you estimate the abundance by integrating the predicted intensity over the range of x</p>
<p>Integration is done as a weighted sum of the intensities. The locations along the x axis and their weights are constructed using the <code>ipoints()</code> function</p>
<p>Here you create 50 equally-space integration points cover the 1D range. The weights are all equal to 55/100</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="tuesday-april-18-2023.html#cb74-1" aria-hidden="true" tabindex="-1"></a>ips <span class="ot">&lt;-</span> <span class="fu">ipoints</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">55</span>), <span class="dv">100</span>, <span class="at">name =</span> <span class="st">&quot;x&quot;</span>)</span>
<span id="cb74-2"><a href="tuesday-april-18-2023.html#cb74-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-3"><a href="tuesday-april-18-2023.html#cb74-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ips)</span></code></pre></div>
<pre><code>##       x weight group
## 1 0.275   0.55     1
## 2 0.825   0.55     1
## 3 1.375   0.55     1
## 4 1.925   0.55     1
## 5 2.475   0.55     1
## 6 3.025   0.55     1</code></pre>
<p>Then compute the abundance over the entire domain with the <code>predict()</code> method</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="tuesday-april-18-2023.html#cb76-1" aria-hidden="true" tabindex="-1"></a>( Lambda <span class="ot">&lt;-</span> <span class="fu">predict</span>(model.lgcp, </span>
<span id="cb76-2"><a href="tuesday-april-18-2023.html#cb76-2" aria-hidden="true" tabindex="-1"></a>                    ips, </span>
<span id="cb76-3"><a href="tuesday-april-18-2023.html#cb76-3" aria-hidden="true" tabindex="-1"></a>                    <span class="sc">~</span> <span class="fu">sum</span>(weight <span class="sc">*</span> <span class="fu">exp</span>(spde1D <span class="sc">+</span> Intercept))) )</span></code></pre></div>
<pre><code>##       mean       sd   q0.025     q0.5  q0.975   median mean.mc_std_err
## 1 130.6649 13.20506 108.7045 130.0565 154.991 130.0565        1.320506
##   sd.mc_std_err
## 1     0.7423157</code></pre>
<ul>
<li><code>mean</code> is the posterior mean abundance</li>
<li><code>sd</code> is the estimated standard error of the posterior of the abundance</li>
<li><code>q0.025</code> and <code>q0.975</code> are the 95% credible interval bounds</li>
<li><code>q0.5</code> is the posterior median abundance</li>
</ul>
<p>The mean number of events is just over 130 with a standard deviation of 11.5 events</p>
<p>Recall that the LGCP has a hierarchical structure, where at the first level the process is assumed Poisson conditional on the intensity function, and at the second level the log of the intensity function is assumed to be drawn from a Gaussian process</p>
<p>The above posterior values for the abundance takes into account only the variance due to the parameters of the intensity function (2nd level). It neglects the variance in the number of events, given the intensity function (first level)</p>
<p>To include both variances you need to modify the input to the <code>predict( )</code> method. You include a data frame that samples from a Poisson density for each value of the abundance (here <code>N = 50:250</code>)</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="tuesday-april-18-2023.html#cb78-1" aria-hidden="true" tabindex="-1"></a>Nest <span class="ot">&lt;-</span> <span class="fu">predict</span>(model.lgcp, </span>
<span id="cb78-2"><a href="tuesday-april-18-2023.html#cb78-2" aria-hidden="true" tabindex="-1"></a>                ips,</span>
<span id="cb78-3"><a href="tuesday-april-18-2023.html#cb78-3" aria-hidden="true" tabindex="-1"></a>                <span class="sc">~</span> <span class="fu">data.frame</span>(<span class="at">N =</span> <span class="dv">50</span><span class="sc">:</span><span class="dv">250</span>,</span>
<span id="cb78-4"><a href="tuesday-april-18-2023.html#cb78-4" aria-hidden="true" tabindex="-1"></a>                             <span class="at">dpois =</span> <span class="fu">dpois</span>(<span class="dv">50</span><span class="sc">:</span><span class="dv">250</span>,</span>
<span id="cb78-5"><a href="tuesday-april-18-2023.html#cb78-5" aria-hidden="true" tabindex="-1"></a>                             <span class="at">lambda =</span> <span class="fu">sum</span>(weight <span class="sc">*</span> <span class="fu">exp</span>(spde1D <span class="sc">+</span> Intercept)))))</span></code></pre></div>
<p>The result shows the same set of statistics as were calculated for <code>Lambda</code>, but here for every abundance value between 50 and 250, rather than for the posterior mean abundance alone.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="tuesday-april-18-2023.html#cb79-1" aria-hidden="true" tabindex="-1"></a>Nest <span class="sc">|&gt;</span></span>
<span id="cb79-2"><a href="tuesday-april-18-2023.html#cb79-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>##    N         mean           sd       q0.025         q0.5       q0.975
## 1 50 5.342594e-12 3.216028e-11 1.755266e-22 8.809126e-16 5.765682e-11
## 2 51 1.137589e-11 6.782482e-11 5.259628e-22 2.233199e-15 1.242328e-10
## 3 52 2.376544e-11 1.403077e-10 1.545788e-21 5.552506e-15 2.625566e-10
## 4 53 4.873052e-11 2.848138e-10 4.457466e-21 1.354497e-14 5.444671e-10
## 5 54 9.810998e-11 5.675241e-10 1.261609e-20 3.243019e-14 1.108249e-09
## 6 55 1.940168e-10 1.110459e-09 3.505974e-20 7.623458e-14 2.214981e-09
##         median mean.mc_std_err sd.mc_std_err
## 1 8.809126e-16    3.216028e-12  1.341788e-11
## 2 2.233199e-15    6.782482e-12  2.811034e-11
## 3 5.552506e-15    1.403077e-11  5.775262e-11
## 4 1.354497e-14    2.848138e-11  1.164020e-10
## 5 3.243019e-14    5.675241e-11  2.302430e-10
## 6 7.623458e-14    1.110459e-10  4.470928e-10</code></pre>
<p>You compute the 95% prediction interval and the median with the <code>inla.qmarginal()</code> function</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="tuesday-april-18-2023.html#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">inla.qmarginal</span>(<span class="fu">c</span>(.<span class="dv">025</span>, .<span class="dv">5</span>, .<span class="dv">975</span>), </span>
<span id="cb81-2"><a href="tuesday-april-18-2023.html#cb81-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">marginal =</span> <span class="fu">list</span>(<span class="at">x =</span> Nest<span class="sc">$</span>N, </span>
<span id="cb81-3"><a href="tuesday-april-18-2023.html#cb81-3" aria-hidden="true" tabindex="-1"></a>                               <span class="at">y =</span> Nest<span class="sc">$</span>mean))</span></code></pre></div>
<pre><code>## [1] 101.4664 129.7675 164.2138</code></pre>
<p>Now compare <code>Lambda</code> to <code>Nest</code> using a plot</p>
<p>First calculate the posterior distribution conditional on the mean of <code>Lambda</code></p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="tuesday-april-18-2023.html#cb83-1" aria-hidden="true" tabindex="-1"></a>Nest<span class="sc">$</span>plugin_estimate <span class="ot">&lt;-</span> <span class="fu">dpois</span>(Nest<span class="sc">$</span>N, </span>
<span id="cb83-2"><a href="tuesday-april-18-2023.html#cb83-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">lambda =</span> Lambda<span class="sc">$</span>mean)</span></code></pre></div>
<p>Then plot it together with the unconditional posterior distribution</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="tuesday-april-18-2023.html#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Nest) <span class="sc">+</span></span>
<span id="cb84-2"><a href="tuesday-april-18-2023.html#cb84-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> N, </span>
<span id="cb84-3"><a href="tuesday-april-18-2023.html#cb84-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">y =</span> mean, </span>
<span id="cb84-4"><a href="tuesday-april-18-2023.html#cb84-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">color =</span> <span class="st">&quot;Posterior&quot;</span>)) <span class="sc">+</span></span>
<span id="cb84-5"><a href="tuesday-april-18-2023.html#cb84-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> N, </span>
<span id="cb84-6"><a href="tuesday-april-18-2023.html#cb84-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">y =</span> plugin_estimate, </span>
<span id="cb84-7"><a href="tuesday-april-18-2023.html#cb84-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">color =</span> <span class="st">&quot;Plugin&quot;</span>))</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-40-1.png" width="672" /></p>
<p>The posterior distribution takes into account both levels of uncertainty so it is less peaked and broader than the plugin distribution</p>
<p>An example of LGCP model using SPDE in two-dimensions with real data (gorilla nesting sites) is available here <a href="https://inlabru-org.github.io/inlabru/index.html" class="uri">https://inlabru-org.github.io/inlabru/index.html</a></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="thursday-april-13-2023.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="tuesday-april-25-2023.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
