<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tuesday October 25, 2022 | GIS5122: Applied Spatial Statistics</title>
  <meta name="description" content="Tuesday October 25, 2022 | GIS5122: Applied Spatial Statistics" />
  <meta name="generator" content="bookdown 0.29 and GitBook 2.6.7" />

  <meta property="og:title" content="Tuesday October 25, 2022 | GIS5122: Applied Spatial Statistics" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="jelsner/ASS-2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tuesday October 25, 2022 | GIS5122: Applied Spatial Statistics" />
  
  
  

<meta name="author" content="James B. Elsner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="thursday-october-20-2022.html"/>
<link rel="next" href="thursday-october-27-2022.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied Spatial Statistics</a></li>

<li class="divider"></li>
<li><a href="index.html#section" id="toc-section"></a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i>Syllabus</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#gis5122-applied-spatial-statistics"><i class="fa fa-check"></i>GIS5122: Applied Spatial Statistics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#contact-information"><i class="fa fa-check"></i>Contact information</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#course-description-and-expected-learning-outcomes"><i class="fa fa-check"></i>Course description and expected learning outcomes</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#grades-and-ethics"><i class="fa fa-check"></i>Grades and ethics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#outline-of-topics-and-schedule"><i class="fa fa-check"></i>Outline of topics and schedule</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#reference-materials"><i class="fa fa-check"></i>Reference materials</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#reproducible-research"><i class="fa fa-check"></i>Reproducible research</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html"><i class="fa fa-check"></i>Tuesday, August 23, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#install-r-and-rstudio-on-your-computer"><i class="fa fa-check"></i>Install R and RStudio on your computer</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#download-course-materials"><i class="fa fa-check"></i>Download course materials</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#read-the-syllabus"><i class="fa fa-check"></i>Read the syllabus</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#about-rstudio"><i class="fa fa-check"></i>About RStudio</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#lab-assignments"><i class="fa fa-check"></i>Lab assignments</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#getting-started-with-r"><i class="fa fa-check"></i>Getting started with R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#are-you-completely-new-to-r"><i class="fa fa-check"></i>Are you completely new to R?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html"><i class="fa fa-check"></i>Thursday, August 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-science-workflow-with-r-markdown"><i class="fa fa-check"></i>Data science workflow with R markdown</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#an-introduction-to-using-r"><i class="fa fa-check"></i>An introduction to using R</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-frames"><i class="fa fa-check"></i>Data frames</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html"><i class="fa fa-check"></i>Tuesday August 30, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#working-with-data-frames-using-base-r"><i class="fa fa-check"></i>Working with data frames using base R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#getting-data-into-r"><i class="fa fa-check"></i>Getting data into R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#working-with-data-frames-using-functions-from-dplyr"><i class="fa fa-check"></i>Working with data frames using functions from {dplyr}</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html"><i class="fa fa-check"></i>Thursday September 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#making-graphs"><i class="fa fa-check"></i>Making graphs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html"><i class="fa fa-check"></i>Thursday September 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#introduction-to-simple-features"><i class="fa fa-check"></i>Introduction to simple features</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#geo-computation-on-simple-features"><i class="fa fa-check"></i>Geo-computation on simple features</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html"><i class="fa fa-check"></i>Tuesday September 13, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#spatial-data-subsets-and-joins"><i class="fa fa-check"></i>Spatial data subsets and joins</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#interpolation-using-areal-weights"><i class="fa fa-check"></i>Interpolation using areal weights</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html"><i class="fa fa-check"></i>Thursday September 15, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#s4-spatial-data-objects"><i class="fa fa-check"></i>S4 spatial data objects</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#working-with-raster-data"><i class="fa fa-check"></i>Working with raster data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#working-with-space-time-data"><i class="fa fa-check"></i>Working with space-time data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html"><i class="fa fa-check"></i>Tuesday September 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#mapping-using-functions-from-the-ggplot2-package"><i class="fa fa-check"></i>Mapping using functions from the {ggplot2} package</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#mapping-using-functions-from-the-tmap-package"><i class="fa fa-check"></i>Mapping using functions from the {tmap} package</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#creating-an-interactive-map"><i class="fa fa-check"></i>Creating an interactive map</a></li>
<li class="chapter" data-level="0.1" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#hillshape-and-colors-with-tidyterra"><i class="fa fa-check"></i><b>0.1</b> Hillshape and colors with tidyterra</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#adding-an-inset-map"><i class="fa fa-check"></i>Adding an inset map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html"><i class="fa fa-check"></i>Tuesday October 4, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#defining-spatial-neighborhoods-and-spatial-weights"><i class="fa fa-check"></i>Defining spatial neighborhoods and spatial weights</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#computing-autocorrelation"><i class="fa fa-check"></i>Computing autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#spatial-lag-and-its-relation-to-autocorrelation"><i class="fa fa-check"></i>Spatial lag and its relation to autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#other-neighbor-definitions"><i class="fa fa-check"></i>Other neighbor definitions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html"><i class="fa fa-check"></i>Thursday October 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#assessing-the-statistical-significance-of-autocorrelation"><i class="fa fa-check"></i>Assessing the statistical significance of autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#bivariate-spatial-autocorrelation"><i class="fa fa-check"></i>Bivariate spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#local-indicators-of-spatial-autocorrelation"><i class="fa fa-check"></i>Local indicators of spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#constraining-group-membership-based-on-spatial-autocorrelation"><i class="fa fa-check"></i>Constraining group membership based on spatial autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html"><i class="fa fa-check"></i>Tuesday October 11, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#estimating-spatial-autocorrelation-in-model-residuals"><i class="fa fa-check"></i>Estimating spatial autocorrelation in model residuals</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#choosing-a-spatial-regression-model"><i class="fa fa-check"></i>Choosing a spatial regression model</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#fitting-and-interpreting-spatial-regression-models"><i class="fa fa-check"></i>Fitting and interpreting spatial regression models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html"><i class="fa fa-check"></i>Thursday October 13, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html#fitting-and-interpreting-geographic-regression"><i class="fa fa-check"></i>Fitting and interpreting geographic regression</a></li>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html#mapping-incidence-and-risk-with-a-spatial-regression-model"><i class="fa fa-check"></i>Mapping incidence and risk with a spatial regression model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html"><i class="fa fa-check"></i>Thursday October 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#spatial-data-as-point-patterns"><i class="fa fa-check"></i>Spatial data as point patterns</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#theoretical-framework-for-analyzingmodeling-point-pattern-data"><i class="fa fa-check"></i>Theoretical framework for analyzing/modeling point pattern data</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#working-with-point-pattern-data-using-functions-from-the-spatstat-package"><i class="fa fa-check"></i>Working with point pattern data using functions from the spatstat package</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#quantifying-the-spatial-intensity-of-events"><i class="fa fa-check"></i>Quantifying the spatial intensity of events</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html"><i class="fa fa-check"></i>Tuesday October 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#creating-ppp-and-owin-objects-from-simple-feature-data-frames"><i class="fa fa-check"></i>Creating <code>ppp</code> and <code>owin</code> objects from simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#estimating-spatial-intensity-as-a-function-of-distance"><i class="fa fa-check"></i>Estimating spatial intensity as a function of distance</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#intensity-trend-as-a-possible-confounding-factor"><i class="fa fa-check"></i>Intensity trend as a possible confounding factor</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html"><i class="fa fa-check"></i>Thursday October 27, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#estimating-the-relative-risk-of-events"><i class="fa fa-check"></i>Estimating the relative risk of events</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#estimating-second-moment-properties-of-spatial-events"><i class="fa fa-check"></i>Estimating second-moment properties of spatial events</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022-1.html"><a href="thursday-october-27-2022-1.html"><i class="fa fa-check"></i>Thursday October 27, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-27-2022-1.html"><a href="thursday-october-27-2022-1.html#examples-of-spatially-clustered-events"><i class="fa fa-check"></i>Examples of spatially clustered events</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022-1.html"><a href="thursday-october-27-2022-1.html#determining-the-statistical-significance-of-event-clustering"><i class="fa fa-check"></i>Determining the statistical significance of event clustering</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022-1.html"><a href="thursday-october-27-2022-1.html#estimating-event-clustering-in-multi-type-event-locations"><i class="fa fa-check"></i>Estimating event clustering in multi-type event locations</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022-1.html"><a href="thursday-october-27-2022-1.html#more-about-the-ripley-k-function"><i class="fa fa-check"></i>More about the Ripley K function</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html"><i class="fa fa-check"></i>Tuesday November 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#inferring-event-interaction-from-distance-functions"><i class="fa fa-check"></i>Inferring event interaction from distance functions</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#removing-duplicate-event-locations-and-defining-the-domain"><i class="fa fa-check"></i>Removing duplicate event locations and defining the domain</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#modeling-point-pattern-data"><i class="fa fa-check"></i>Modeling point pattern data</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#fitting-and-interpreting-an-inhibition-model"><i class="fa fa-check"></i>Fitting and interpreting an inhibition model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html"><i class="fa fa-check"></i>Thursday November 3, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#fitting-and-interpreting-a-cluster-model"><i class="fa fa-check"></i>Fitting and interpreting a cluster model</a></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#assessing-how-well-the-model-fits"><i class="fa fa-check"></i>Assessing how well the model fits</a></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#spatial-logistic-regression"><i class="fa fa-check"></i>Spatial logistic regression</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html"><i class="fa fa-check"></i>Thursday November 10, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html#spatial-data-interpolation"><i class="fa fa-check"></i>Spatial data interpolation</a></li>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html#computing-the-sample-variogram"><i class="fa fa-check"></i>Computing the sample variogram</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html"><i class="fa fa-check"></i>Tuesday November 15, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#fitting-a-variogram-model-to-the-sample-variogram"><i class="fa fa-check"></i>Fitting a variogram model to the sample variogram</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#creating-an-interpolated-surface-with-the-method-of-kriging"><i class="fa fa-check"></i>Creating an interpolated surface with the method of kriging</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html"><i class="fa fa-check"></i>Thursday November 17, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#comparing-interpolation-methods"><i class="fa fa-check"></i>Comparing interpolation methods</a></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#evaluating-the-accuracy-of-the-interpolation"><i class="fa fa-check"></i>Evaluating the accuracy of the interpolation</a></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#block-cross-validation"><i class="fa fa-check"></i>Block cross validation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html"><i class="fa fa-check"></i>Thursday November 29, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html#interpolating-to-areal-units-block-kriging"><i class="fa fa-check"></i>Interpolating to areal units (block kriging)</a></li>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html#simulating-spatial-fields"><i class="fa fa-check"></i>Simulating spatial fields</a></li>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html#interpolating-multiple-variables"><i class="fa fa-check"></i>Interpolating multiple variables</a></li>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html#machine-learning-for-spatial-interpolation"><i class="fa fa-check"></i>Machine learning for spatial interpolation</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GIS5122: Applied Spatial Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="tuesday-october-25-2022" class="section level1 unnumbered hasAnchor">
<h1>Tuesday October 25, 2022<a href="tuesday-october-25-2022.html#tuesday-october-25-2022" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>“So much complexity in software comes from trying to make one thing do two things.”</strong> - Ryan Singer</p>
<p>Today</p>
<ul>
<li>Creating <code>ppp</code> and <code>owin</code> objects from simple feature data frames</li>
<li>Estimating spatial intensity as a function of distance</li>
<li>Intensity trend as a possible confounding factor</li>
</ul>
<p>Last time the terminology of point pattern data including the concept of complete spatial randomness (CSR) was introduced.</p>
<p>Focus is on natural occurring systems where the geographic location of events is examined through the lens of statistics to better understand physical processes.</p>
<p><a href="https://www.washingtonpost.com/business/2022/10/21/dead-bugs-on-windshields/" class="uri">https://www.washingtonpost.com/business/2022/10/21/dead-bugs-on-windshields/</a></p>
<p>The {spatstat} family of packages provides a comprehensive set of functions for analyzing, plotting, and modeling point pattern data. The package requires the data be of spatial class <code>ppp</code>.</p>
<p>Typical work flow includes importing and munging data as a simple feature data frame and then converting the simple feature data frame to a <code>ppp</code> object for analysis and modeling. But it is sometimes convenient to do some of the data munging after conversion to a <code>ppp</code> object.</p>
<div id="creating-ppp-and-owin-objects-from-simple-feature-data-frames" class="section level2 unnumbered hasAnchor">
<h2>Creating <code>ppp</code> and <code>owin</code> objects from simple feature data frames<a href="tuesday-october-25-2022.html#creating-ppp-and-owin-objects-from-simple-feature-data-frames" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Consider again Kansas tornadoes. Import the data as a simple feature data frame and transform the geographic CRS to Lambert conic conformal centered on Kansas (EPSG:6922). Keep all tornadoes (having an EF damage rating) since 1950 whose initial location occurred within the state.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="tuesday-october-25-2022.html#cb1-1" aria-hidden="true" tabindex="-1"></a>Torn.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="at">dsn =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;1950-2020-torn-initpoint&quot;</span>)) <span class="sc">|&gt;</span></span>
<span id="cb1-2"><a href="tuesday-october-25-2022.html#cb1-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">6922</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-3"><a href="tuesday-october-25-2022.html#cb1-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(st <span class="sc">==</span> <span class="st">&quot;KS&quot;</span>, mag <span class="sc">&gt;=</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-4"><a href="tuesday-october-25-2022.html#cb1-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">EF =</span> <span class="fu">factor</span>(mag)) <span class="sc">|&gt;</span></span>
<span id="cb1-5"><a href="tuesday-october-25-2022.html#cb1-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(EF)</span></code></pre></div>
<pre><code>## Reading layer `1950-2020-torn-initpoint&#39; from data source 
##   `/Users/jameselsner/Desktop/ClassNotes/ASS-2022/data/1950-2020-torn-initpoint&#39; 
##   using driver `ESRI Shapefile&#39;
## Simple feature collection with 66244 features and 22 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -163.53 ymin: 17.7212 xmax: -64.7151 ymax: 61.02
## Geodetic CRS:  WGS 84</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="tuesday-october-25-2022.html#cb3-1" aria-hidden="true" tabindex="-1"></a>Torn.sf <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="tuesday-october-25-2022.html#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>## Simple feature collection with 6 features and 1 field
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: 308290.4 ymin: 172079 xmax: 610402.8 ymax: 427368.7
## Projected CRS: NAD83 / Kansas LCC
##   EF                  geometry
## 1  1 POINT (610402.8 238069.8)
## 2  2   POINT (384977.9 172079)
## 3  3 POINT (525374.2 236300.3)
## 4  0 POINT (395720.4 427368.7)
## 5  0 POINT (523250.6 202968.5)
## 6  0 POINT (308290.4 416796.4)</code></pre>
<p>The length unit is meters. This can be seen by printing the CRS.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="tuesday-october-25-2022.html#cb5-1" aria-hidden="true" tabindex="-1"></a>sf<span class="sc">::</span><span class="fu">st_crs</span>(Torn.sf)</span></code></pre></div>
<pre><code>## Coordinate Reference System:
##   User input: EPSG:6922 
##   wkt:
## PROJCRS[&quot;NAD83 / Kansas LCC&quot;,
##     BASEGEOGCRS[&quot;NAD83&quot;,
##         DATUM[&quot;North American Datum 1983&quot;,
##             ELLIPSOID[&quot;GRS 1980&quot;,6378137,298.257222101,
##                 LENGTHUNIT[&quot;metre&quot;,1]]],
##         PRIMEM[&quot;Greenwich&quot;,0,
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433]],
##         ID[&quot;EPSG&quot;,4269]],
##     CONVERSION[&quot;Kansas DOT Lambert (meters)&quot;,
##         METHOD[&quot;Lambert Conic Conformal (2SP)&quot;,
##             ID[&quot;EPSG&quot;,9802]],
##         PARAMETER[&quot;Latitude of false origin&quot;,36,
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433],
##             ID[&quot;EPSG&quot;,8821]],
##         PARAMETER[&quot;Longitude of false origin&quot;,-98.25,
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433],
##             ID[&quot;EPSG&quot;,8822]],
##         PARAMETER[&quot;Latitude of 1st standard parallel&quot;,39.5,
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433],
##             ID[&quot;EPSG&quot;,8823]],
##         PARAMETER[&quot;Latitude of 2nd standard parallel&quot;,37.5,
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433],
##             ID[&quot;EPSG&quot;,8824]],
##         PARAMETER[&quot;Easting at false origin&quot;,400000,
##             LENGTHUNIT[&quot;metre&quot;,1],
##             ID[&quot;EPSG&quot;,8826]],
##         PARAMETER[&quot;Northing at false origin&quot;,0,
##             LENGTHUNIT[&quot;metre&quot;,1],
##             ID[&quot;EPSG&quot;,8827]]],
##     CS[Cartesian,2],
##         AXIS[&quot;easting (X)&quot;,east,
##             ORDER[1],
##             LENGTHUNIT[&quot;metre&quot;,1]],
##         AXIS[&quot;northing (Y)&quot;,north,
##             ORDER[2],
##             LENGTHUNIT[&quot;metre&quot;,1]],
##     USAGE[
##         SCOPE[&quot;Topographic mapping (small scale).&quot;],
##         AREA[&quot;United States (USA) - Kansas.&quot;],
##         BBOX[36.99,-102.06,40.01,-94.58]],
##     ID[&quot;EPSG&quot;,6922]]</code></pre>
<p>Further you note that some tornadoes are incorrectly coded as Kansas tornadoes by plotting the event locations.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="tuesday-october-25-2022.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Torn.sf<span class="sc">$</span>geometry)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>Most events are within the near-rectangle shape of the state border but you also see a few events clearly outside the border.</p>
<p>Instead of filtering by column name (<code>st == "KS"</code>) you can subset by geometry using the <code>sf::st_intersection()</code> function as you did earlier in the semester. You also can do this by defining the state border as an <code>owin</code> object.</p>
<p>You get the Kansas border as a simple feature data frame from the {USAboundaries} package and transform the CRS to that of the CRS in the tornado simple feature data frame.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="tuesday-october-25-2022.html#cb8-1" aria-hidden="true" tabindex="-1"></a>KS.sf <span class="ot">&lt;-</span> USAboundaries<span class="sc">::</span><span class="fu">us_states</span>(<span class="at">states =</span> <span class="st">&quot;Kansas&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb8-2"><a href="tuesday-october-25-2022.html#cb8-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> sf<span class="sc">::</span><span class="fu">st_crs</span>(Torn.sf))</span></code></pre></div>
<p>You then create an <code>owin</code> object from the simple feature data frame using the <code>as.owin()</code> function.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="tuesday-october-25-2022.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(spatstat))</span>
<span id="cb9-2"><a href="tuesday-october-25-2022.html#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="tuesday-october-25-2022.html#cb9-3" aria-hidden="true" tabindex="-1"></a>KS.win <span class="ot">&lt;-</span> KS.sf <span class="sc">|&gt;</span></span>
<span id="cb9-4"><a href="tuesday-october-25-2022.html#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.owin</span>()</span></code></pre></div>
<p>Next you convert the simple feature data frame of tornado reports to a <code>ppp</code> object with the EF damage rating as the marks using the <code>as.ppp()</code> function.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="tuesday-october-25-2022.html#cb10-1" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="ot">&lt;-</span> Torn.sf <span class="sc">|&gt;</span></span>
<span id="cb10-2"><a href="tuesday-october-25-2022.html#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.ppp</span>()</span>
<span id="cb10-3"><a href="tuesday-october-25-2022.html#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="tuesday-october-25-2022.html#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(T.ppp)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>Finally you subset the event locations in the <code>ppp</code> object by the Kansas border using the subset operator (<code>[]</code>).</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="tuesday-october-25-2022.html#cb11-1" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="ot">&lt;-</span> T.ppp[KS.win]</span>
<span id="cb11-2"><a href="tuesday-october-25-2022.html#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(T.ppp)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>With your <code>T.ppp</code> object you are ready to analyze the tornado locations as spatial point pattern data.</p>
<p>The <code>summary()</code> method provides information about the <code>ppp</code> object.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="tuesday-october-25-2022.html#cb12-1" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a href="tuesday-october-25-2022.html#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## Marked planar point pattern:  4281 points
## Average intensity 2.008277e-08 points per square unit
## 
## *Pattern contains duplicated points*
## 
## Coordinates are given to 2 decimal places
## i.e. rounded to the nearest multiple of 0.01 units
## 
## Multitype:
##   frequency  proportion    intensity
## 0      2534 0.591917800 1.188735e-08
## 1      1062 0.248072900 4.981990e-09
## 2       453 0.105816400 2.125086e-09
## 3       188 0.043914970 8.819343e-10
## 4        38 0.008876431 1.782633e-10
## 5         6 0.001401542 2.814684e-11
## 
## Window: polygonal boundary
## single connected closed polygon with 169 vertices
## enclosing rectangle: [62446.7, 723275.4] x [110798.6, 451072.2] units
##                      (660800 x 340300 units)
## Window area = 2.13168e+11 square units
## Fraction of frame area: 0.948</code></pre>
<p>There are 4281 events (tornado reports) with an average spatial intensity of .0000000201 (2.008277e-08) events per unit area.</p>
<p>The distance unit is meter since that is the length unit in the simple feature data frame from which the <code>ppp</code> object was derived. So the area is in square meters making the spatial intensity (number of tornado reports per square meter) quite small.</p>
<p>To make it easier to interpret the intensity, you convert the length unit from meters to kilometers within the <code>ppp</code> object with the <code>rescale()</code> function from the {spatstat} package (spatstat.geom). The scaling factor argument is <code>s =</code> and the conversion is 1000 m = 1 km so the argument is set to 1000. You then set the unit name to <code>km</code> with the <code>unitname =</code> argument.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="tuesday-october-25-2022.html#cb14-1" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="ot">&lt;-</span> T.ppp <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="tuesday-october-25-2022.html#cb14-2" aria-hidden="true" tabindex="-1"></a>  spatstat.geom<span class="sc">::</span><span class="fu">rescale</span>(<span class="at">s =</span> <span class="dv">1000</span>, </span>
<span id="cb14-3"><a href="tuesday-october-25-2022.html#cb14-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">unitname =</span> <span class="st">&quot;km&quot;</span>)</span>
<span id="cb14-4"><a href="tuesday-october-25-2022.html#cb14-4" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="sc">|&gt;</span></span>
<span id="cb14-5"><a href="tuesday-october-25-2022.html#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## Marked planar point pattern:  4281 points
## Average intensity 0.02008277 points per square km
## 
## *Pattern contains duplicated points*
## 
## Coordinates are given to 5 decimal places
## 
## Multitype:
##   frequency  proportion    intensity
## 0      2534 0.591917800 1.188735e-02
## 1      1062 0.248072900 4.981990e-03
## 2       453 0.105816400 2.125086e-03
## 3       188 0.043914970 8.819343e-04
## 4        38 0.008876431 1.782633e-04
## 5         6 0.001401542 2.814684e-05
## 
## Window: polygonal boundary
## single connected closed polygon with 169 vertices
## enclosing rectangle: [62.4467, 723.2754] x [110.7986, 451.0722] km
##                      (660.8 x 340.3 km)
## Window area = 213168 square km
## Unit of length: 1 km
## Fraction of frame area: 0.948</code></pre>
<p>Caution here as you are recycling the object name <code>T.ppp</code>. If you run the above code chunk again the scale will change again by a factor of 1000 while the unit name will stay the same.</p>
<p>There are 4281 tornado reports with an average intensity of .02 tornadoes per square km over this time period. Nearly 60% of Kansas tornadoes are rated as doing EF0 (lowest damage level). Less than 1% of them are rated as ‘violent’ (doing EF4 or EF5 level damage). The area of the state is 213,168 square kilometers (km).</p>
<p>Plot the events separated by the marks using the <code>plot()</code> method together with the <code>split()</code> function.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="tuesday-october-25-2022.html#cb16-1" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="tuesday-october-25-2022.html#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">split</span>() <span class="sc">|&gt;</span></span>
<span id="cb16-3"><a href="tuesday-october-25-2022.html#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>The spatial intensity of EF3 and less damaging tornadoes appears to be fairly uniform across the state.</p>
<p>Can the spatial distribution of Kansas tornadoes be described by complete spatial randomness?</p>
<p>The number of tornadoes varies across the state (EF4 tornadoes are rare in the far western part of the state for example) but it’s difficult to say whether this is due to sampling variation. To illustrate this here you compare the EF1 tornado locations with a sample of events generated under the null hypothesis of CSR.</p>
<p>First create <code>Y</code> as an unmarked <code>ppp</code> object containing only the EF1 tornadoes. You do this by keeping only the events with marks equal to one with the <code>subset()</code> function. Since the marks are a factor you remove the levels with the <code>unmark()</code> function.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="tuesday-october-25-2022.html#cb17-1" aria-hidden="true" tabindex="-1"></a>( Y <span class="ot">&lt;-</span> T.ppp <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="tuesday-october-25-2022.html#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">subset</span>(marks <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb17-3"><a href="tuesday-october-25-2022.html#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unmark</span>() )</span></code></pre></div>
<pre><code>## Planar point pattern: 1062 points
## window: polygonal boundary
## enclosing rectangle: [62.4467, 723.2754] x [110.7986, 451.0722] km</code></pre>
<p>There were 1062 reported EF1 tornadoes originating within the state over the period 1950 through 2020.</p>
<p>The average intensity of the EF1 tornado events is obtained with the <code>intensity()</code> function.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="tuesday-october-25-2022.html#cb19-1" aria-hidden="true" tabindex="-1"></a>Y <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a href="tuesday-october-25-2022.html#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">intensity</span>()</span></code></pre></div>
<pre><code>## [1] 0.00498199</code></pre>
<p>On average there has been .005 EF1 tornadoes per square km or 50 per 100 square km.</p>
<p>Make a map to check if things look right.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="tuesday-october-25-2022.html#cb21-1" aria-hidden="true" tabindex="-1"></a>Y <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="tuesday-october-25-2022.html#cb21-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>EF1 tornado reports are found throughout the state and they appear to be distributed randomly.</p>
<p>Formally: Is the spatial distribution of EF1 tornado reports consistent with a set of event locations that are described as complete spatial randomness?</p>
<p>To help answer this question you construct <code>X</code> to be a set of events generated from a homogeneous Poisson process (a model for CSR) where the intensity of the events is equal to the average intensity of the EF1 tornado reports.</p>
<p>You assign the average intensity to an object called <code>lambdaEF1</code> and then use <code>rpoispp()</code> (random Poisson point pattern) with lambda set to that intensity and the domain specified with the <code>win =</code> argument.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="tuesday-october-25-2022.html#cb22-1" aria-hidden="true" tabindex="-1"></a>( lambdaEF1 <span class="ot">&lt;-</span> <span class="fu">intensity</span>(Y) )</span></code></pre></div>
<pre><code>## [1] 0.00498199</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="tuesday-october-25-2022.html#cb24-1" aria-hidden="true" tabindex="-1"></a>( X <span class="ot">&lt;-</span> <span class="fu">rpoispp</span>(<span class="at">lambda =</span> lambdaEF1, </span>
<span id="cb24-2"><a href="tuesday-october-25-2022.html#cb24-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">win =</span> <span class="fu">window</span>(Y)) )</span></code></pre></div>
<pre><code>## Planar point pattern: 1020 points
## window: polygonal boundary
## enclosing rectangle: [62.4467, 723.2754] x [110.7986, 451.0722] km</code></pre>
<p>The average intensity of <code>X</code> matches (closely) the average intensity of <code>Y</code> by design and the <code>plot()</code> method reveals a similar looking pattern of event locations.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="tuesday-october-25-2022.html#cb26-1" aria-hidden="true" tabindex="-1"></a>X <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="tuesday-october-25-2022.html#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">intensity</span>()</span></code></pre></div>
<pre><code>## [1] 0.004784963</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="tuesday-october-25-2022.html#cb28-1" aria-hidden="true" tabindex="-1"></a>X <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a href="tuesday-october-25-2022.html#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>While the pattern is similar, there does appear to be a difference. Can you describe the difference?</p>
<p>To make comparisons between the two point pattern data (one observed events and the other simulated) easier you use the <code>superimpose()</code> function to create a single <code>ppp</code> object and assign to <code>Z</code> marks <code>Y</code> and <code>X</code>. Then plot the two intensity rasters split by mark type.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="tuesday-october-25-2022.html#cb29-1" aria-hidden="true" tabindex="-1"></a>Z <span class="ot">&lt;-</span> <span class="fu">superimpose</span>(<span class="at">Y =</span> Y, </span>
<span id="cb29-2"><a href="tuesday-october-25-2022.html#cb29-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">X =</span> X)</span></code></pre></div>
<pre><code>## Warning: data contain duplicated points</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="tuesday-october-25-2022.html#cb31-1" aria-hidden="true" tabindex="-1"></a>Z <span class="sc">|&gt;</span></span>
<span id="cb31-2"><a href="tuesday-october-25-2022.html#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">split</span>() <span class="sc">|&gt;</span></span>
<span id="cb31-3"><a href="tuesday-october-25-2022.html#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">density</span>() <span class="sc">|&gt;</span></span>
<span id="cb31-4"><a href="tuesday-october-25-2022.html#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>The range of local intensity variations is similar. So we don’t have much evidence against the null model of CSR as defined by a homogeneous Poisson process.</p>
</div>
<div id="estimating-spatial-intensity-as-a-function-of-distance" class="section level2 unnumbered hasAnchor">
<h2>Estimating spatial intensity as a function of distance<a href="tuesday-october-25-2022.html#estimating-spatial-intensity-as-a-function-of-distance" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Are tornado reports more common in the vicinity of towns?</p>
<p>Based on domain specific knowledge of how these data were collected you suspect that tornado reports will cluster near cities and towns. This is especially true in the earlier years of the record.</p>
<p>This understanding is available from the literature on tornadoes (not from the data) and it is a well-known artifact of the data set, but it had never been quantified until 2013 in a paper we wrote. <a href="http://myweb.fsu.edu/jelsner/PDF/Research/ElsnerMichaelsScheitlinElsner2013.pdf" class="uri">http://myweb.fsu.edu/jelsner/PDF/Research/ElsnerMichaelsScheitlinElsner2013.pdf</a>.</p>
<p>How was this done? We estimated the spatial intensity of the observed tornado reports as a function of distance from nearest town and compared it with an estimate of the spatial intensity of randomly placed events as a function of distance from the nearest town.</p>
<p>First get the city locations from the <code>us_cities()</code> function in the {USAboundaries} package. Exclude towns with fewer than 1000 people and transform the geometry to that of the tornado locations.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="tuesday-october-25-2022.html#cb32-1" aria-hidden="true" tabindex="-1"></a>C.sf <span class="ot">&lt;-</span> USAboundaries<span class="sc">::</span><span class="fu">us_cities</span>() <span class="sc">|&gt;</span></span>
<span id="cb32-2"><a href="tuesday-october-25-2022.html#cb32-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(population <span class="sc">&gt;=</span> <span class="dv">1000</span>) <span class="sc">|&gt;</span></span>
<span id="cb32-3"><a href="tuesday-october-25-2022.html#cb32-3" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> sf<span class="sc">::</span><span class="fu">st_crs</span>(Torn.sf))</span></code></pre></div>
<pre><code>## City populations for contemporary data come from the 2010 census.</code></pre>
<p>Create a <code>ppp</code> object of events from the city/town locations in the simple feature data frame. Remove the marks and include only events inside the window object (<code>KS.own</code>). Convert the distance unit from meters to kilometers.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="tuesday-october-25-2022.html#cb34-1" aria-hidden="true" tabindex="-1"></a>C.ppp <span class="ot">&lt;-</span> C.sf <span class="sc">|&gt;</span></span>
<span id="cb34-2"><a href="tuesday-october-25-2022.html#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.ppp</span>() <span class="sc">|&gt;</span></span>
<span id="cb34-3"><a href="tuesday-october-25-2022.html#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unmark</span>()</span></code></pre></div>
<pre><code>## Warning in as.ppp.sf(C.sf): only first attribute column is used for marks</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="tuesday-october-25-2022.html#cb36-1" aria-hidden="true" tabindex="-1"></a>C.ppp <span class="ot">&lt;-</span> C.ppp[KS.win] <span class="sc">|&gt;</span></span>
<span id="cb36-2"><a href="tuesday-october-25-2022.html#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rescale</span>(<span class="at">s =</span> <span class="dv">1000</span>,</span>
<span id="cb36-3"><a href="tuesday-october-25-2022.html#cb36-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">unitname =</span> <span class="st">&quot;km&quot;</span>)</span>
<span id="cb36-4"><a href="tuesday-october-25-2022.html#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(C.ppp)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>Next compute a ‘distance map’. A distance map for a spatial domain A is a function <span class="math inline">\(f(s)\)</span> whose value is defined for any <em>point</em> <span class="math inline">\(s\)</span> as the shortest distance from <span class="math inline">\(s\)</span> to any <em>event</em> location in A.</p>
<p>This is done with the <code>distmap()</code> function and the points are the intersections of a 128 x 128 rectangular grid.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="tuesday-october-25-2022.html#cb37-1" aria-hidden="true" tabindex="-1"></a>Zc <span class="ot">&lt;-</span> C.ppp <span class="sc">|&gt;</span></span>
<span id="cb37-2"><a href="tuesday-october-25-2022.html#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distmap</span>()</span>
<span id="cb37-3"><a href="tuesday-october-25-2022.html#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="tuesday-october-25-2022.html#cb37-4" aria-hidden="true" tabindex="-1"></a>Zc <span class="sc">|&gt;</span></span>
<span id="cb37-5"><a href="tuesday-october-25-2022.html#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>The result is an object of class <code>im</code> (image raster). Distances are in kilometers. Most points in Kansas are less than 50 km from the nearest town (reds and blues) but some points are more than 80 km away (yellow).</p>
<p>Other distance functions include <code>pairdist()</code>, which is the pairwise distance between all event pairs and <code>crossdist()</code>, which is the distance between events from two point patterns. The <code>nndist()</code> computes the distance between an event and its nearest neighbor event.</p>
<p>The distance map (distance from any point in Kansas to the nearest town) is used to quantify the population bias in the tornado records.</p>
<p>This is done with <code>rhohat()</code> which estimates the smoothed spatial intensity as a function of some explanatory variable. The relationship between spatial intensity and an explanatory variable is called a ‘resource selection’ function (if the events are organisms and the variable is a descriptor of habitat) or a ‘prospectivity index’ (if the events are mineral deposits and the variable is a geological variable).</p>
<p>The method assumes the events are a realization from a Poisson process with intensity function <span class="math inline">\(\lambda(u)\)</span> of the form</p>
<p><span class="math display">\[
\lambda(u) = \rho[Z(u)]
\]</span></p>
<p>where <span class="math inline">\(Z\)</span> is the spatial explanatory variable (covariate) function (with continuous values) and <span class="math inline">\(\rho(z)\)</span> is a function to be estimated.</p>
<p>The function does not assume a particular form for the relationship between the point pattern and the variable (thus it is said to be ‘non-parametric’).</p>
<p>Here you use <code>rhohat()</code> to estimate tornado report intensity as a function of distance to nearest city.</p>
<p>The first argument in <code>rhohat()</code> is the <code>ppp</code> object for which you want the intensity estimate and the <code>covariate =</code> argument is the spatial variable, here as object of class <code>im</code>. By default kernel smoothing is done using a fixed bandwidth. With <code>method = "transform"</code> a variable bandwidth is used.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="tuesday-october-25-2022.html#cb38-1" aria-hidden="true" tabindex="-1"></a>rhat <span class="ot">&lt;-</span> Y <span class="sc">|&gt;</span></span>
<span id="cb38-2"><a href="tuesday-october-25-2022.html#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rhohat</span>(<span class="at">covariate =</span> Zc,</span>
<span id="cb38-3"><a href="tuesday-october-25-2022.html#cb38-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">method =</span> <span class="st">&quot;transform&quot;</span>)</span>
<span id="cb38-4"><a href="tuesday-october-25-2022.html#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="tuesday-october-25-2022.html#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(rhat)</span></code></pre></div>
<pre><code>## [1] &quot;rhohat&quot;     &quot;fv&quot;         &quot;data.frame&quot;</code></pre>
<p>The resulting object (<code>rhat</code>) has three classes including a data frame. The data frame contains the explanatory variable as a single vector (<code>Zc</code>), an estimate of the intensity at the distances (<code>rho</code>), the variance (<code>var</code>) and upper (<code>hi</code>) and lower (<code>lo</code>) uncertainty values (point-wise).</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="tuesday-october-25-2022.html#cb40-1" aria-hidden="true" tabindex="-1"></a>rhat <span class="sc">|&gt;</span></span>
<span id="cb40-2"><a href="tuesday-october-25-2022.html#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb40-3"><a href="tuesday-october-25-2022.html#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>##           Zc         rho        ave          var          hi          lo
## 1 0.06513302 0.008502359 0.00498199 3.757168e-07 0.009703734 0.007300985
## 2 0.25982641 0.008488554 0.00498199 3.734550e-07 0.009686307 0.007290801
## 3 0.45451980 0.008473601 0.00498199 3.710003e-07 0.009667411 0.007279791
## 4 0.64921319 0.008456926 0.00498199 3.682819e-07 0.009646354 0.007267498
## 5 0.84390658 0.008438833 0.00498199 3.653370e-07 0.009623497 0.007254170
## 6 1.03859997 0.008419390 0.00498199 3.621735e-07 0.009598913 0.007239867</code></pre>
<p>Here you put these values into a new data frame (<code>df</code>) multiplying the intensities by 10,000 (so areal units are 100 sq. km) then use <code>ggplot()</code> method with a <code>geom_ribbon()</code> layer to overlay the uncertainty band.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="tuesday-october-25-2022.html#cb42-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">dist =</span> rhat<span class="sc">$</span>Zc, </span>
<span id="cb42-2"><a href="tuesday-october-25-2022.html#cb42-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">rho =</span> rhat<span class="sc">$</span>rho <span class="sc">*</span> <span class="dv">10000</span>, </span>
<span id="cb42-3"><a href="tuesday-october-25-2022.html#cb42-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">hi =</span> rhat<span class="sc">$</span>hi <span class="sc">*</span> <span class="dv">10000</span>, </span>
<span id="cb42-4"><a href="tuesday-october-25-2022.html#cb42-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">lo =</span> rhat<span class="sc">$</span>lo <span class="sc">*</span> <span class="dv">10000</span>)</span>
<span id="cb42-5"><a href="tuesday-october-25-2022.html#cb42-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-6"><a href="tuesday-october-25-2022.html#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb42-7"><a href="tuesday-october-25-2022.html#cb42-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-8"><a href="tuesday-october-25-2022.html#cb42-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> df) <span class="sc">+</span></span>
<span id="cb42-9"><a href="tuesday-october-25-2022.html#cb42-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> dist, </span>
<span id="cb42-10"><a href="tuesday-october-25-2022.html#cb42-10" aria-hidden="true" tabindex="-1"></a>                            <span class="at">ymin =</span> lo , </span>
<span id="cb42-11"><a href="tuesday-october-25-2022.html#cb42-11" aria-hidden="true" tabindex="-1"></a>                            <span class="at">ymax =</span> hi), <span class="at">alpha =</span> .<span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb42-12"><a href="tuesday-october-25-2022.html#cb42-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> dist, </span>
<span id="cb42-13"><a href="tuesday-october-25-2022.html#cb42-13" aria-hidden="true" tabindex="-1"></a>                          <span class="at">y =</span> rho), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span>  </span>
<span id="cb42-14"><a href="tuesday-october-25-2022.html#cb42-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">intensity</span>(Y) <span class="sc">*</span> <span class="dv">10000</span>, </span>
<span id="cb42-15"><a href="tuesday-october-25-2022.html#cb42-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb42-16"><a href="tuesday-october-25-2022.html#cb42-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb42-17"><a href="tuesday-october-25-2022.html#cb42-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Tornado reports (EF1) per 100 sq. km&quot;</span>) <span class="sc">+</span></span>
<span id="cb42-18"><a href="tuesday-october-25-2022.html#cb42-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Distance from nearest town center (km)&quot;</span>) <span class="sc">+</span></span>
<span id="cb42-19"><a href="tuesday-october-25-2022.html#cb42-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>The vertical axis on the plot is the tornado report intensity in units of number of reports per 100 square kilometers. The horizontal axis is the distance to nearest town in km. The red line is the average spatial intensity as a function of distance from nearest town. The 95% uncertainty band about this estimate is shown in gray.</p>
<p>At points close to the town (center) tornado reports are high relative to at points far from town. The blue line is the average intensity across the state computed with the <code>intensity()</code> function and scaled appropriately.</p>
<p>At points within about 15 km the tornado report intensity is above the statewide average intensity. At points greater than about 60 km the report intensity is below the statewide average.</p>
<p>At zero distance from a town, this number is more than 1.7 times higher (85 tornadoes per 100 sq. km). The spatial scale is about 15 km (distance along the spatial axis where the red line falls below the blue line).</p>
<p>At this point in the analysis you need to think that although the plot look reasonable based on your expectations of a population bias in the tornado reports (fewer reports away from cities/towns), could this result be an artifact of the smoothing algorithm?</p>
<p>You need to know how to apply statistical tools to accomplish specific tasks. But you also need to be a bit skeptical of the tool’s outcome. The skepticism provides a critical check against being fooled by randomness (null hypothesis).</p>
<p>As an example, the method of computing the spatial intensity as a function of a covariate should give you a different answer if events are randomly distributed. If the events are randomly distributed, what would you expect to find on a plot such as this?</p>
<p>Recall Friday’s seminar talk by Jeffery Cannon. Where he found an increase in cone production on pine trees a few years after a hurricane. He needed to compare his graph with a graph showing cone production a few years after an other year (null hypothesis).</p>
<p>You already generated a set of events from a homogeneous Poisson model so you can check simply by applying the <code>rhohat()</code> function to these events using the same set of city/town locations.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="tuesday-october-25-2022.html#cb43-1" aria-hidden="true" tabindex="-1"></a>rhat0 <span class="ot">&lt;-</span> X <span class="sc">|&gt;</span></span>
<span id="cb43-2"><a href="tuesday-october-25-2022.html#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rhohat</span>(<span class="at">covariate =</span> Zc,</span>
<span id="cb43-3"><a href="tuesday-october-25-2022.html#cb43-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">method =</span> <span class="st">&quot;transform&quot;</span>)</span>
<span id="cb43-4"><a href="tuesday-october-25-2022.html#cb43-4" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">dist =</span> rhat0<span class="sc">$</span>Zc, </span>
<span id="cb43-5"><a href="tuesday-october-25-2022.html#cb43-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">rho =</span> rhat0<span class="sc">$</span>rho <span class="sc">*</span> <span class="dv">10000</span>, </span>
<span id="cb43-6"><a href="tuesday-october-25-2022.html#cb43-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">hi =</span> rhat0<span class="sc">$</span>hi <span class="sc">*</span> <span class="dv">10000</span>, </span>
<span id="cb43-7"><a href="tuesday-october-25-2022.html#cb43-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">lo =</span> rhat0<span class="sc">$</span>lo <span class="sc">*</span> <span class="dv">10000</span>)</span>
<span id="cb43-8"><a href="tuesday-october-25-2022.html#cb43-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> df) <span class="sc">+</span></span>
<span id="cb43-9"><a href="tuesday-october-25-2022.html#cb43-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> dist, </span>
<span id="cb43-10"><a href="tuesday-october-25-2022.html#cb43-10" aria-hidden="true" tabindex="-1"></a>                            <span class="at">ymin =</span> lo , </span>
<span id="cb43-11"><a href="tuesday-october-25-2022.html#cb43-11" aria-hidden="true" tabindex="-1"></a>                            <span class="at">ymax =</span> hi), <span class="at">alpha =</span> .<span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb43-12"><a href="tuesday-october-25-2022.html#cb43-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> dist, </span>
<span id="cb43-13"><a href="tuesday-october-25-2022.html#cb43-13" aria-hidden="true" tabindex="-1"></a>                          <span class="at">y =</span> rho), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span>  </span>
<span id="cb43-14"><a href="tuesday-october-25-2022.html#cb43-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">intensity</span>(Y) <span class="sc">*</span> <span class="dv">10000</span>, </span>
<span id="cb43-15"><a href="tuesday-october-25-2022.html#cb43-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb43-16"><a href="tuesday-october-25-2022.html#cb43-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb43-17"><a href="tuesday-october-25-2022.html#cb43-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Random events per 100 sq. km&quot;</span>) <span class="sc">+</span></span>
<span id="cb43-18"><a href="tuesday-october-25-2022.html#cb43-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Distance from nearest town center (km)&quot;</span>) <span class="sc">+</span></span>
<span id="cb43-19"><a href="tuesday-october-25-2022.html#cb43-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>As expected, the number of random events near cities/towns is not higher than the number of random events at greater distances. Thus you reject the null hypothesis of no difference in tornado reports near and far from cities.</p>
</div>
<div id="intensity-trend-as-a-possible-confounding-factor" class="section level2 unnumbered hasAnchor">
<h2>Intensity trend as a possible confounding factor<a href="tuesday-october-25-2022.html#intensity-trend-as-a-possible-confounding-factor" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Quantifying the report bias with the spatial intensity function works well for Kansas where there is no trend in the local intensity. Local tornado intensity is largely uniform across Kansas.</p>
<p>Things are different in Texas where a significant intensity trend makes it more difficult to estimate the report bias.</p>
<p>Convert the tornado reports (EF1 or worse) occurring over Texas as a <code>ppp</code> object. Use a Texas-centric Lambert conic conformal projection.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="tuesday-october-25-2022.html#cb44-1" aria-hidden="true" tabindex="-1"></a>Torn.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="at">dsn =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;1950-2020-torn-initpoint&quot;</span>)) <span class="sc">|&gt;</span></span>
<span id="cb44-2"><a href="tuesday-october-25-2022.html#cb44-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3082</span>) <span class="sc">|&gt;</span></span>
<span id="cb44-3"><a href="tuesday-october-25-2022.html#cb44-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(mag <span class="sc">&gt;=</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## Reading layer `1950-2020-torn-initpoint&#39; from data source 
##   `/Users/jameselsner/Desktop/ClassNotes/ASS-2022/data/1950-2020-torn-initpoint&#39; 
##   using driver `ESRI Shapefile&#39;
## Simple feature collection with 66244 features and 22 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -163.53 ymin: 17.7212 xmax: -64.7151 ymax: 61.02
## Geodetic CRS:  WGS 84</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="tuesday-october-25-2022.html#cb46-1" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="ot">&lt;-</span> Torn.sf <span class="sc">|&gt;</span></span>
<span id="cb46-2"><a href="tuesday-october-25-2022.html#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.ppp</span>()</span></code></pre></div>
<pre><code>## Warning in as.ppp.sf(Torn.sf): only first attribute column is used for marks</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="tuesday-october-25-2022.html#cb48-1" aria-hidden="true" tabindex="-1"></a>W <span class="ot">&lt;-</span> USAboundaries<span class="sc">::</span><span class="fu">us_states</span>(<span class="at">states =</span> <span class="st">&quot;Texas&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb48-2"><a href="tuesday-october-25-2022.html#cb48-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> sf<span class="sc">::</span><span class="fu">st_crs</span>(Torn.sf)) <span class="sc">|&gt;</span></span>
<span id="cb48-3"><a href="tuesday-october-25-2022.html#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.owin</span>()</span>
<span id="cb48-4"><a href="tuesday-october-25-2022.html#cb48-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-5"><a href="tuesday-october-25-2022.html#cb48-5" aria-hidden="true" tabindex="-1"></a>( T.ppp <span class="ot">&lt;-</span> T.ppp[W] <span class="sc">|&gt;</span></span>
<span id="cb48-6"><a href="tuesday-october-25-2022.html#cb48-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rescale</span>(<span class="at">s =</span> <span class="dv">1000</span>, </span>
<span id="cb48-7"><a href="tuesday-october-25-2022.html#cb48-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">unitname =</span> <span class="st">&quot;km&quot;</span>) )</span></code></pre></div>
<pre><code>## Marked planar point pattern: 8932 points
## marks are numeric, of storage type  &#39;double&#39;
## window: polygonal boundary
## enclosing rectangle: [873.7638, 2116.6498] x [5881.245, 7063.086] km</code></pre>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="tuesday-october-25-2022.html#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">intensity</span>(T.ppp)</span></code></pre></div>
<pre><code>## [1] 0.01293119</code></pre>
<p>There are 8,932 tornado reports. The distance unit is kilometer. The average intensity is .013 events per square kilometer over this 71-year period (1950-2020).</p>
<p>Next plot the local intensity using a kernel smoother.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="tuesday-october-25-2022.html#cb52-1" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="sc">|&gt;</span></span>
<span id="cb52-2"><a href="tuesday-october-25-2022.html#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">density</span>() <span class="sc">|&gt;</span></span>
<span id="cb52-3"><a href="tuesday-october-25-2022.html#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>There is a clear trend of tornado reports from a low number of reports in the southwest part of the state along the Rio Grande to a high number of reports in the northeast part of the state. The statewide average intensity of .013 tornado reports per square km is too high in southwest and too low in the northern.</p>
<p>Next compute and plot the spatial intensity as a smoothed function of distance to nearest town or city. Start by removing the marks on the tornado events assigning the unmarked <code>ppp</code> object to <code>Tum.ppp</code>. Then create a <code>ppp</code> object from the city/town locations and subset the tornado events by the window.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="tuesday-october-25-2022.html#cb53-1" aria-hidden="true" tabindex="-1"></a>Tum.ppp <span class="ot">&lt;-</span> T.ppp <span class="sc">|&gt;</span></span>
<span id="cb53-2"><a href="tuesday-october-25-2022.html#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unmark</span>()</span>
<span id="cb53-3"><a href="tuesday-october-25-2022.html#cb53-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-4"><a href="tuesday-october-25-2022.html#cb53-4" aria-hidden="true" tabindex="-1"></a>C.ppp <span class="ot">&lt;-</span> C.sf <span class="sc">|&gt;</span></span>
<span id="cb53-5"><a href="tuesday-october-25-2022.html#cb53-5" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> sf<span class="sc">::</span><span class="fu">st_crs</span>(Torn.sf)) <span class="sc">|&gt;</span></span>
<span id="cb53-6"><a href="tuesday-october-25-2022.html#cb53-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.ppp</span>() <span class="sc">|&gt;</span></span>
<span id="cb53-7"><a href="tuesday-october-25-2022.html#cb53-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unmark</span>()</span></code></pre></div>
<pre><code>## Warning in as.ppp.sf(sf::st_transform(C.sf, crs = sf::st_crs(Torn.sf))): only
## first attribute column is used for marks</code></pre>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="tuesday-october-25-2022.html#cb55-1" aria-hidden="true" tabindex="-1"></a>C.ppp <span class="ot">&lt;-</span> C.ppp[W] <span class="sc">|&gt;</span></span>
<span id="cb55-2"><a href="tuesday-october-25-2022.html#cb55-2" aria-hidden="true" tabindex="-1"></a>  spatstat.geom<span class="sc">::</span><span class="fu">rescale</span>(<span class="at">s =</span> <span class="dv">1000</span>,</span>
<span id="cb55-3"><a href="tuesday-october-25-2022.html#cb55-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">unitname =</span> <span class="st">&quot;km&quot;</span>)</span></code></pre></div>
<p>Next create a distance map of the city/town locations using the <code>distmap()</code> function.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="tuesday-october-25-2022.html#cb56-1" aria-hidden="true" tabindex="-1"></a>Zc <span class="ot">&lt;-</span> C.ppp <span class="sc">|&gt;</span></span>
<span id="cb56-2"><a href="tuesday-october-25-2022.html#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distmap</span>()</span>
<span id="cb56-3"><a href="tuesday-october-25-2022.html#cb56-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-4"><a href="tuesday-october-25-2022.html#cb56-4" aria-hidden="true" tabindex="-1"></a>Zc <span class="sc">|&gt;</span></span>
<span id="cb56-5"><a href="tuesday-october-25-2022.html#cb56-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p>Finally, compute the intensity of tornadoes as a smoothed function of distance to nearest town/city with the <code>rhohat()</code> function. Prepare the output and make a plot.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="tuesday-october-25-2022.html#cb57-1" aria-hidden="true" tabindex="-1"></a>rhat <span class="ot">&lt;-</span> Tum.ppp <span class="sc">|&gt;</span></span>
<span id="cb57-2"><a href="tuesday-october-25-2022.html#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rhohat</span>(<span class="at">covariate =</span> Zc,</span>
<span id="cb57-3"><a href="tuesday-october-25-2022.html#cb57-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">method =</span> <span class="st">&quot;transform&quot;</span>)</span>
<span id="cb57-4"><a href="tuesday-october-25-2022.html#cb57-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-5"><a href="tuesday-october-25-2022.html#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">dist =</span> rhat<span class="sc">$</span>Zc, </span>
<span id="cb57-6"><a href="tuesday-october-25-2022.html#cb57-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">rho =</span> rhat<span class="sc">$</span>rho, </span>
<span id="cb57-7"><a href="tuesday-october-25-2022.html#cb57-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">hi =</span> rhat<span class="sc">$</span>hi, </span>
<span id="cb57-8"><a href="tuesday-october-25-2022.html#cb57-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">lo =</span> rhat<span class="sc">$</span>lo) <span class="sc">|&gt;</span></span>
<span id="cb57-9"><a href="tuesday-october-25-2022.html#cb57-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb57-10"><a href="tuesday-october-25-2022.html#cb57-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> dist, </span>
<span id="cb57-11"><a href="tuesday-october-25-2022.html#cb57-11" aria-hidden="true" tabindex="-1"></a>                            <span class="at">ymin =</span> lo , </span>
<span id="cb57-12"><a href="tuesday-october-25-2022.html#cb57-12" aria-hidden="true" tabindex="-1"></a>                            <span class="at">ymax =</span> hi), <span class="at">alpha =</span> .<span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb57-13"><a href="tuesday-october-25-2022.html#cb57-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> dist, </span>
<span id="cb57-14"><a href="tuesday-october-25-2022.html#cb57-14" aria-hidden="true" tabindex="-1"></a>                          <span class="at">y =</span> rho), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span>  </span>
<span id="cb57-15"><a href="tuesday-october-25-2022.html#cb57-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="cn">NA</span>)) <span class="sc">+</span></span>
<span id="cb57-16"><a href="tuesday-october-25-2022.html#cb57-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">intensity</span>(Tum.ppp), <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb57-17"><a href="tuesday-october-25-2022.html#cb57-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Tornado reports per sq. km&quot;</span>) <span class="sc">+</span></span>
<span id="cb57-18"><a href="tuesday-october-25-2022.html#cb57-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Distance from nearest town center (km)&quot;</span>) <span class="sc">+</span></span>
<span id="cb57-19"><a href="tuesday-october-25-2022.html#cb57-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>The plot shows that the intensity of the tornado reports is much higher than the average intensity in the vicinity of towns and cities. Yet caution needs to exercised in the interpretation because the trend of increasing tornado reports moving from southwest to northeast across the state is mirrored by the trend in the occurrence of cities/towns. There are many fewer towns in the southwestern part of Texas compared to the northern and eastern part of the state.</p>
<p>You can quantify this effect by specifying a function in the <code>covariate =</code> argument. Here you specify a planar surface with <code>x,y</code> as arguments and <code>x + y</code> inside the function. Here you use the <code>plot()</code> method on the output (instead of creating a data frame and using <code>ggplot()</code>).</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="tuesday-october-25-2022.html#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">rhohat</span>(Tum.ppp, </span>
<span id="cb58-2"><a href="tuesday-october-25-2022.html#cb58-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">covariate =</span> <span class="cf">function</span>(x,y){x <span class="sc">+</span> y},</span>
<span id="cb58-3"><a href="tuesday-october-25-2022.html#cb58-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">method =</span> <span class="st">&quot;transform&quot;</span>),</span>
<span id="cb58-4"><a href="tuesday-october-25-2022.html#cb58-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Spatial intensity trend of tornadoes&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<p>Local intensity increases along the axis labeled <code>X</code> starting at a value of 7,400. At value of <code>X</code> equal to about 8,200 the spatial intensity stops increasing.</p>
<p>Units along the horizontal axis are kilometers but the reference (intercept) distance is at the far left. So you interpret the increase in spatial intensity going from southwest to northeast as a change across about 800 km (8200 - 7400).</p>
<p>The local intensity of cities has the same property (increasing from southwest to northeast then leveling off). Here you substitute <code>C.ppp</code> for <code>Tum.ppp</code> in the <code>rhohat()</code> function.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="tuesday-october-25-2022.html#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">rhohat</span>(C.ppp, </span>
<span id="cb59-2"><a href="tuesday-october-25-2022.html#cb59-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">covariate =</span> <span class="cf">function</span>(x,y){x <span class="sc">+</span> y},</span>
<span id="cb59-3"><a href="tuesday-october-25-2022.html#cb59-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">method =</span> <span class="st">&quot;transform&quot;</span>),</span>
<span id="cb59-4"><a href="tuesday-october-25-2022.html#cb59-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Spatial intensity trend of cities&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<p>So the population bias towards more reports near towns/cities is confounded by the fact that there tends to be more cities and towns in areas that have conditions more favorable for tornadoes.</p>
<p>Thus you can only get so far by examining intensity estimates. If your interest lies in inferring the causes of spatial variation in the intensity you will need to use a spatial model.</p>
<p>Before doing that we will want to quantify the second-order property of spatial events. We will use various functions to do this and we will compare outputs from these functions when applied to the observed data and when applied to models for CSR.</p>
<p>But, spatial intensity can be used to estimate the relative risk. Separate spatial intensity maps across two marked types provides a way to estimate the risk of one event type conditional on the other event type. More generally, the relative risk of occurrence of some event is a conditional probability. In a non-spatial context, the risk of catching a disease if you are elderly relative to the risk if you are young.</p>
<p>Given a tornado somewhere in Texas what is the chance that it will cause at least EF3 damage? With the historical set of all tornadoes marked by the damage rating you can make a map of all tornadoes and a map of the EF3+ tornadoes and then take the ratio.</p>
<p>Summary: Analyzing spatial point pattern data with function from the {spatstat} family of packages requires the data be of class <code>ppp</code>. A <code>ppp</code> object contains the events and the domain (window). You saw how to create <code>ppp</code> and <code>owin</code> objects from simple feature data frames. Visually you can compare your events against events generated from simple models of CSR. You saw how to estimate spatial intensity as a function of a covariate. This allowed you to examine the hypothesis of no population bias in the tornado reports. However, if the covariate has the same spatial intensity as the observed events then inference is not straight forward.</p>
<p>Next we will look at estimating relative risk before examining spatial clustering.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="thursday-october-20-2022.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="thursday-october-27-2022.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
