<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tuesday November 15, 2022 | GIS5122: Applied Spatial Statistics</title>
  <meta name="description" content="Tuesday November 15, 2022 | GIS5122: Applied Spatial Statistics" />
  <meta name="generator" content="bookdown 0.29 and GitBook 2.6.7" />

  <meta property="og:title" content="Tuesday November 15, 2022 | GIS5122: Applied Spatial Statistics" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="jelsner/ASS-2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tuesday November 15, 2022 | GIS5122: Applied Spatial Statistics" />
  
  
  

<meta name="author" content="James B. Elsner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tuesday-november-8-2022.html"/>
<link rel="next" href="thursday-november-17-2022.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied Spatial Statistics</a></li>

<li class="divider"></li>
<li><a href="index.html#section" id="toc-section"></a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i>Syllabus</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#gis5122-applied-spatial-statistics"><i class="fa fa-check"></i>GIS5122: Applied Spatial Statistics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#contact-information"><i class="fa fa-check"></i>Contact information</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#course-description-and-expected-learning-outcomes"><i class="fa fa-check"></i>Course description and expected learning outcomes</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#grades-and-ethics"><i class="fa fa-check"></i>Grades and ethics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#outline-of-topics-and-schedule"><i class="fa fa-check"></i>Outline of topics and schedule</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#reference-materials"><i class="fa fa-check"></i>Reference materials</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#reproducible-research"><i class="fa fa-check"></i>Reproducible research</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html"><i class="fa fa-check"></i>Tuesday, August 23, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#install-r-and-rstudio-on-your-computer"><i class="fa fa-check"></i>Install R and RStudio on your computer</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#download-course-materials"><i class="fa fa-check"></i>Download course materials</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#read-the-syllabus"><i class="fa fa-check"></i>Read the syllabus</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#about-rstudio"><i class="fa fa-check"></i>About RStudio</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#lab-assignments"><i class="fa fa-check"></i>Lab assignments</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#getting-started-with-r"><i class="fa fa-check"></i>Getting started with R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#are-you-completely-new-to-r"><i class="fa fa-check"></i>Are you completely new to R?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html"><i class="fa fa-check"></i>Thursday, August 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-science-workflow-with-r-markdown"><i class="fa fa-check"></i>Data science workflow with R markdown</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#an-introduction-to-using-r"><i class="fa fa-check"></i>An introduction to using R</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-frames"><i class="fa fa-check"></i>Data frames</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html"><i class="fa fa-check"></i>Tuesday August 30, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#working-with-data-frames-using-base-r"><i class="fa fa-check"></i>Working with data frames using base R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#getting-data-into-r"><i class="fa fa-check"></i>Getting data into R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#working-with-data-frames-using-functions-from-dplyr"><i class="fa fa-check"></i>Working with data frames using functions from {dplyr}</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html"><i class="fa fa-check"></i>Thursday September 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#making-graphs"><i class="fa fa-check"></i>Making graphs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html"><i class="fa fa-check"></i>Thursday September 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#introduction-to-simple-features"><i class="fa fa-check"></i>Introduction to simple features</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#geo-computation-on-simple-features"><i class="fa fa-check"></i>Geo-computation on simple features</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html"><i class="fa fa-check"></i>Tuesday September 13, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#spatial-data-subsets-and-joins"><i class="fa fa-check"></i>Spatial data subsets and joins</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#interpolation-using-areal-weights"><i class="fa fa-check"></i>Interpolation using areal weights</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html"><i class="fa fa-check"></i>Thursday September 15, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#s4-spatial-data-objects"><i class="fa fa-check"></i>S4 spatial data objects</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#working-with-raster-data"><i class="fa fa-check"></i>Working with raster data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#working-with-space-time-data"><i class="fa fa-check"></i>Working with space-time data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html"><i class="fa fa-check"></i>Tuesday September 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#mapping-using-functions-from-the-ggplot2-package"><i class="fa fa-check"></i>Mapping using functions from the {ggplot2} package</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#mapping-using-functions-from-the-tmap-package"><i class="fa fa-check"></i>Mapping using functions from the {tmap} package</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#creating-an-interactive-map"><i class="fa fa-check"></i>Creating an interactive map</a></li>
<li class="chapter" data-level="0.1" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#hillshape-and-colors-with-tidyterra"><i class="fa fa-check"></i><b>0.1</b> Hillshape and colors with tidyterra</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#adding-an-inset-map"><i class="fa fa-check"></i>Adding an inset map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html"><i class="fa fa-check"></i>Tuesday October 4, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#defining-spatial-neighborhoods-and-spatial-weights"><i class="fa fa-check"></i>Defining spatial neighborhoods and spatial weights</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#computing-autocorrelation"><i class="fa fa-check"></i>Computing autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#spatial-lag-and-its-relation-to-autocorrelation"><i class="fa fa-check"></i>Spatial lag and its relation to autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#other-neighbor-definitions"><i class="fa fa-check"></i>Other neighbor definitions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html"><i class="fa fa-check"></i>Thursday October 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#assessing-the-statistical-significance-of-autocorrelation"><i class="fa fa-check"></i>Assessing the statistical significance of autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#bivariate-spatial-autocorrelation"><i class="fa fa-check"></i>Bivariate spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#local-indicators-of-spatial-autocorrelation"><i class="fa fa-check"></i>Local indicators of spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#constraining-group-membership-based-on-spatial-autocorrelation"><i class="fa fa-check"></i>Constraining group membership based on spatial autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html"><i class="fa fa-check"></i>Tuesday October 11, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#estimating-spatial-autocorrelation-in-model-residuals"><i class="fa fa-check"></i>Estimating spatial autocorrelation in model residuals</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#choosing-a-spatial-regression-model"><i class="fa fa-check"></i>Choosing a spatial regression model</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#fitting-and-interpreting-spatial-regression-models"><i class="fa fa-check"></i>Fitting and interpreting spatial regression models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html"><i class="fa fa-check"></i>Thursday October 13, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html#fitting-and-interpreting-geographic-regression"><i class="fa fa-check"></i>Fitting and interpreting geographic regression</a></li>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html#mapping-incidence-and-risk-with-a-spatial-regression-model"><i class="fa fa-check"></i>Mapping incidence and risk with a spatial regression model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html"><i class="fa fa-check"></i>Thursday October 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#spatial-data-as-point-patterns"><i class="fa fa-check"></i>Spatial data as point patterns</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#theoretical-framework-for-analyzingmodeling-point-pattern-data"><i class="fa fa-check"></i>Theoretical framework for analyzing/modeling point pattern data</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#working-with-point-pattern-data-using-functions-from-the-spatstat-package"><i class="fa fa-check"></i>Working with point pattern data using functions from the spatstat package</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#quantifying-the-spatial-intensity-of-events"><i class="fa fa-check"></i>Quantifying the spatial intensity of events</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html"><i class="fa fa-check"></i>Tuesday October 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#creating-ppp-and-owin-objects-from-simple-feature-data-frames"><i class="fa fa-check"></i>Creating <code>ppp</code> and <code>owin</code> objects from simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#estimating-spatial-intensity-as-a-function-of-distance"><i class="fa fa-check"></i>Estimating spatial intensity as a function of distance</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#covariate-trend-as-a-possible-confounding-factor"><i class="fa fa-check"></i>Covariate trend as a possible confounding factor</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html"><i class="fa fa-check"></i>Thursday October 27, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#estimating-the-relative-risk"><i class="fa fa-check"></i>Estimating the relative risk</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#estimating-second-moment-properties-of-events"><i class="fa fa-check"></i>Estimating second-moment properties of events</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#examples-of-clustered-events"><i class="fa fa-check"></i>Examples of clustered events</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html"><i class="fa fa-check"></i>Tuesday November 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#removing-duplicate-events-and-defining-the-domain"><i class="fa fa-check"></i>Removing duplicate events and defining the domain</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#determining-statistical-significance-of-clustering"><i class="fa fa-check"></i>Determining statistical significance of clustering</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#estimating-clustering-in-multi-type-event-locations"><i class="fa fa-check"></i>Estimating clustering in multi-type event locations</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#interpolating-output-from-a-distance-function"><i class="fa fa-check"></i>Interpolating output from a distance function</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#limitations-of-the-distance-functions"><i class="fa fa-check"></i>Limitations of the distance functions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html"><i class="fa fa-check"></i>Tuesday November 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#limitations-on-interpreting-distance-functions"><i class="fa fa-check"></i>Limitations on interpreting distance functions</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#models-for-point-pattern-data"><i class="fa fa-check"></i>Models for point pattern data</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#fitting-and-interpreting-inhibition-models"><i class="fa fa-check"></i>Fitting and interpreting inhibition models</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#fitting-and-interpreting-cluster-models"><i class="fa fa-check"></i>Fitting and interpreting cluster models</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#assessing-how-well-the-model-fits"><i class="fa fa-check"></i>Assessing how well the model fits</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html"><i class="fa fa-check"></i>Tuesday November 15, 2022</a>
<ul>
<li class="chapter" data-level="0.2" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#fitting-a-log-gaussian-cox-model"><i class="fa fa-check"></i><b>0.2</b> Fitting a log-Gaussian Cox model</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#assessing-how-well-the-model-fits-1"><i class="fa fa-check"></i>Assessing how well the model fits</a></li>
<li class="chapter" data-level="0.3" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#example-from-my-research-on-tornadoes"><i class="fa fa-check"></i><b>0.3</b> Example from my research on tornadoes</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#spatial-logistic-regression"><i class="fa fa-check"></i>Spatial logistic regression</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html"><i class="fa fa-check"></i>Thursday November 17, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#spatial-data-interpolation"><i class="fa fa-check"></i>Spatial data interpolation</a></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#computing-the-sample-variogram"><i class="fa fa-check"></i>Computing the sample variogram</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-22-2022.html"><a href="tuesday-november-22-2022.html"><i class="fa fa-check"></i>Tuesday November 22, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-22-2022.html"><a href="tuesday-november-22-2022.html#fitting-a-variogram-model-to-the-sample-variogram"><i class="fa fa-check"></i>Fitting a variogram model to the sample variogram</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-22-2022.html"><a href="tuesday-november-22-2022.html#creating-an-interpolated-surface-with-the-method-of-kriging"><i class="fa fa-check"></i>Creating an interpolated surface with the method of kriging</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-29-2022.html"><a href="tuesday-november-29-2022.html"><i class="fa fa-check"></i>Tuesday November 29, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-29-2022.html"><a href="tuesday-november-29-2022.html#comparing-interpolation-methods"><i class="fa fa-check"></i>Comparing interpolation methods</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-29-2022.html"><a href="tuesday-november-29-2022.html#evaluating-the-accuracy-of-the-interpolation"><i class="fa fa-check"></i>Evaluating the accuracy of the interpolation</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-29-2022.html"><a href="tuesday-november-29-2022.html#block-cross-validation"><i class="fa fa-check"></i>Block cross validation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-december-1-2022.html"><a href="thursday-december-1-2022.html"><i class="fa fa-check"></i>Thursday December 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-december-1-2022.html"><a href="thursday-december-1-2022.html#interpolating-to-areal-units-block-kriging"><i class="fa fa-check"></i>Interpolating to areal units (block kriging)</a></li>
<li class="chapter" data-level="" data-path="thursday-december-1-2022.html"><a href="thursday-december-1-2022.html#simulating-spatial-fields"><i class="fa fa-check"></i>Simulating spatial fields</a></li>
<li class="chapter" data-level="" data-path="thursday-december-1-2022.html"><a href="thursday-december-1-2022.html#interpolating-multiple-variables"><i class="fa fa-check"></i>Interpolating multiple variables</a></li>
<li class="chapter" data-level="" data-path="thursday-december-1-2022.html"><a href="thursday-december-1-2022.html#machine-learning-for-spatial-interpolation"><i class="fa fa-check"></i>Machine learning for spatial interpolation</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GIS5122: Applied Spatial Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="tuesday-november-15-2022" class="section level1 unnumbered hasAnchor">
<h1>Tuesday November 15, 2022<a href="tuesday-november-15-2022.html#tuesday-november-15-2022" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>“Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday’s code.”</strong> - Christopher Thompson</p>
<p>Today</p>
<ul>
<li>Fitting a log-Gaussian Cox model</li>
<li>Assessing how well the model fits</li>
<li>Example from my research on tornadoes</li>
<li>Spatial logistic regression</li>
</ul>
<div id="fitting-a-log-gaussian-cox-model" class="section level2 hasAnchor" number="0.2">
<h2><span class="header-section-number">0.2</span> Fitting a log-Gaussian Cox model<a href="tuesday-november-15-2022.html#fitting-a-log-gaussian-cox-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Last time you saw how to fit a cluster model using the <code>kppm()</code> function from the {spatstat} family of packages. You fit a Thomas model to the maple trees in the Lansing Woods data.</p>
<p>The Thomas model is a type of Cox model where the logarithm of the spatial intensity is a sample from a non-negative random variable. A limitation is that the samples are spatially independent. Nearby locations might have vastly different spatial intensities.</p>
<p>A log Gaussian Cox process (LGCP) is one where the non-negative random variable is a Gaussian random field (GRF). That is, the log spatial intensity values are spatially correlated. LGCP models are more difficult to fit using conventional methods.</p>
<p>You can fit a Cox model using the method of stochastic partial differential equations (SPDE). This involves a probability (Bayesian) framework that approximates marginal posterior distributions.</p>
<p>To see how this works, here you consider a 1D space.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="tuesday-november-15-2022.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(inlabru)</span></code></pre></div>
<pre><code>## Loading required package: sp</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="tuesday-november-15-2022.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(INLA)</span></code></pre></div>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## Loading required package: foreach</code></pre>
<pre><code>## Loading required package: parallel</code></pre>
<pre><code>## This is INLA_22.05.07 built 2022-05-07 10:00:43 UTC.
##  - See www.r-inla.org/contact-us for how to get help.
##  - To enable PARDISO sparse library; see inla.pardiso()</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="tuesday-november-15-2022.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mgcv)</span></code></pre></div>
<pre><code>## Loading required package: nlme</code></pre>
<pre><code>## This is mgcv 1.8-40. For overview type &#39;help(&quot;mgcv-package&quot;)&#39;.</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="tuesday-november-15-2022.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code></pre></div>
<p>Get the data</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="tuesday-november-15-2022.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Poisson2_1D)</span>
<span id="cb12-2"><a href="tuesday-november-15-2022.html#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="tuesday-november-15-2022.html#cb12-3" aria-hidden="true" tabindex="-1"></a>pts2 <span class="sc">|&gt;</span></span>
<span id="cb12-4"><a href="tuesday-november-15-2022.html#cb12-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 130
## Columns: 1
## $ x &lt;dbl&gt; 25.1064528, 9.1504482, 17.8802463, 28.0073385, 1.8994489, 8.3805420,…</code></pre>
<p>The object <code>pts2</code> is a one column data frame with column name <code>x</code>.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="tuesday-november-15-2022.html#cb14-1" aria-hidden="true" tabindex="-1"></a>pts2 <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="tuesday-november-15-2022.html#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">range</span>()</span></code></pre></div>
<pre><code>## [1]  0.3293196 51.0375325</code></pre>
<p>The values of <code>x</code> range between .33 and 51</p>
<p>Plot the data as points along a line and a histogram. Here you choose about 20 bins across the range of values.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="tuesday-november-15-2022.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> pts2) <span class="sc">+</span></span>
<span id="cb16-2"><a href="tuesday-november-15-2022.html#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> x), </span>
<span id="cb16-3"><a href="tuesday-november-15-2022.html#cb16-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">binwidth =</span> <span class="dv">55</span> <span class="sc">/</span> <span class="dv">20</span>, </span>
<span id="cb16-4"><a href="tuesday-november-15-2022.html#cb16-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">boundary =</span> <span class="dv">0</span>, </span>
<span id="cb16-5"><a href="tuesday-november-15-2022.html#cb16-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="cn">NA</span>, </span>
<span id="cb16-6"><a href="tuesday-november-15-2022.html#cb16-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb16-7"><a href="tuesday-november-15-2022.html#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> x), </span>
<span id="cb16-8"><a href="tuesday-november-15-2022.html#cb16-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> <span class="dv">0</span>, <span class="at">pch =</span> <span class="st">&quot;|&quot;</span>, <span class="at">cex =</span> <span class="dv">4</span>) </span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>The histogram is a discrete version of the spatial intensity. It shows that events tend to be most common near the value of 20.</p>
<p>Our goal is a smoothed estimate of the 1-D spatial intensity taking into account clustering.</p>
<p>First create a 1D mesh of 50 points (<code>length.out =</code>) across the range of values (from 0 to 55). The end points of the mesh are not constrained.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="tuesday-november-15-2022.html#cb17-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">55</span>, <span class="at">length.out =</span> <span class="dv">50</span>)</span>
<span id="cb17-2"><a href="tuesday-november-15-2022.html#cb17-2" aria-hidden="true" tabindex="-1"></a>mesh1D <span class="ot">&lt;-</span> <span class="fu">inla.mesh.1d</span>(<span class="at">loc =</span> x, </span>
<span id="cb17-3"><a href="tuesday-november-15-2022.html#cb17-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">boundary =</span> <span class="st">&quot;free&quot;</span>)</span></code></pre></div>
<p>Then specify the spatial correlation with a Matern cluster model. The first argument is the mesh onto which the model will be built.</p>
<p>The argument <code>prior.range =</code> accepts a vector of length two with the first element the lag distance (range) of the spatial correlation and the second element the probability that the range will be less than that value. If the second value is <code>NA</code>, the value of the first element is used as a fixed range.</p>
<p>The argument <code>prior.sigma =</code> accepts a vector of length two with the first element the marginal standard deviation of the spatial intensity and the second element the probability that the standard deviation will be greater than that value.</p>
<p>Here you are non-committal on the range of spatial correlation so you specify a large distance (150) with a 75% chance that it will be less than that. A broad prior range.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="tuesday-november-15-2022.html#cb18-1" aria-hidden="true" tabindex="-1"></a>Matern <span class="ot">&lt;-</span> <span class="fu">inla.spde2.pcmatern</span>(<span class="at">mesh =</span> mesh1D, </span>
<span id="cb18-2"><a href="tuesday-november-15-2022.html#cb18-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">prior.range =</span> <span class="fu">c</span>(<span class="dv">150</span>, .<span class="dv">75</span>),</span>
<span id="cb18-3"><a href="tuesday-november-15-2022.html#cb18-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">prior.sigma =</span> <span class="fu">c</span>(.<span class="dv">1</span>, .<span class="dv">75</span>))</span></code></pre></div>
<pre><code>## as(&lt;dtCMatrix&gt;, &quot;dgCMatrix&quot;) is deprecated since Matrix 1.5-0; do as(., &quot;generalMatrix&quot;) instead</code></pre>
<p>Next specify the full model.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="tuesday-november-15-2022.html#cb20-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> x <span class="sc">~</span> <span class="fu">spde1D</span>(x, <span class="at">model =</span> Matern) <span class="sc">+</span> <span class="fu">Intercept</span>(<span class="dv">1</span>)</span></code></pre></div>
<p>Next you fit the model to the actual event locations in <code>pts2</code>. You use the log Gaussian Cox process <code>lgcp()</code> function from the {inlabru} package. The <code>domain =</code> argument specifies the 1D mesh as a list object.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="tuesday-november-15-2022.html#cb21-1" aria-hidden="true" tabindex="-1"></a>model.lgcp <span class="ot">&lt;-</span> <span class="fu">lgcp</span>(<span class="at">components =</span> f, </span>
<span id="cb21-2"><a href="tuesday-november-15-2022.html#cb21-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> pts2, </span>
<span id="cb21-3"><a href="tuesday-november-15-2022.html#cb21-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">domain =</span> <span class="fu">list</span>(<span class="at">x =</span> mesh1D))</span></code></pre></div>
<p>You look at the posterior distributions of the model parameters using the function <code>spde.posterior()</code>. It returns x and y values for a plot of the posterior probability density function (PDF) as a data frame, which you plot with the <code>plot.bru()</code> function (<code>plot()</code> method).</p>
<p>Here is the probability density function for the range parameter.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="tuesday-november-15-2022.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">spde.posterior</span>(<span class="at">result =</span> model.lgcp, </span>
<span id="cb22-2"><a href="tuesday-november-15-2022.html#cb22-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">name =</span> <span class="st">&quot;spde1D&quot;</span>, </span>
<span id="cb22-3"><a href="tuesday-november-15-2022.html#cb22-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">what =</span> <span class="st">&quot;range&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb22-4"><a href="tuesday-november-15-2022.html#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>The prior range value was specified quite broadly but the posterior range is focused on values between 2.5 and 5.</p>
<p>Perhaps better viewed on a log scale.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="tuesday-november-15-2022.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">spde.posterior</span>(model.lgcp, </span>
<span id="cb23-2"><a href="tuesday-november-15-2022.html#cb23-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">name =</span> <span class="st">&quot;spde1D&quot;</span>, </span>
<span id="cb23-3"><a href="tuesday-november-15-2022.html#cb23-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">what =</span> <span class="st">&quot;log.range&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb23-4"><a href="tuesday-november-15-2022.html#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Here you plot the probability density function for the Matern correlation component of the model.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="tuesday-november-15-2022.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">spde.posterior</span>(model.lgcp, </span>
<span id="cb24-2"><a href="tuesday-november-15-2022.html#cb24-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">name =</span> <span class="st">&quot;spde1D&quot;</span>, </span>
<span id="cb24-3"><a href="tuesday-november-15-2022.html#cb24-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">what =</span> <span class="st">&quot;matern.correlation&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb24-4"><a href="tuesday-november-15-2022.html#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>The black line is the posterior median correlation as a function of lag distance. The maximum correlation of 1 at zero lag distance decays to .5 correlation out at a distance of about 20 units.</p>
<p>You can get a feel for sensitivity to priors by specifying different priors and looking at these posterior plots. Always a good idea when fitting models using Bayesian methods.</p>
<p>For example, change the prior range from 150 to 30 and refit, then compare the probability density function of the Matern correlation.</p>
<p>You can predict on the ‘response’ scale [i.e. the intensity function <span class="math inline">\(\lambda\)</span>(s)]. First set up a data frame of explanatory values at which to predict (here <code>grid.df</code>). Then use the <code>predict()</code> method.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="tuesday-november-15-2022.html#cb25-1" aria-hidden="true" tabindex="-1"></a>grid.df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">55</span>, <span class="at">by =</span> <span class="dv">1</span>)) </span>
<span id="cb25-2"><a href="tuesday-november-15-2022.html#cb25-2" aria-hidden="true" tabindex="-1"></a>pred.df <span class="ot">&lt;-</span> <span class="fu">predict</span>(model.lgcp, </span>
<span id="cb25-3"><a href="tuesday-november-15-2022.html#cb25-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> grid.df, </span>
<span id="cb25-4"><a href="tuesday-november-15-2022.html#cb25-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">formula =</span> <span class="sc">~</span> <span class="fu">exp</span>(spde1D <span class="sc">+</span> Intercept))</span></code></pre></div>
<p>It takes a few seconds.</p>
<p>The output is a data frame containing the locations on the grid (<code>x</code>) and the corresponding summary statistics on the posterior predictions at those location.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="tuesday-november-15-2022.html#cb26-1" aria-hidden="true" tabindex="-1"></a>pred.df <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="tuesday-november-15-2022.html#cb26-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 56
## Columns: 9
## $ x               &lt;dbl&gt; 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, …
## $ mean            &lt;dbl&gt; 1.921107, 1.967856, 2.043962, 2.135274, 2.234348, 2.34…
## $ sd              &lt;dbl&gt; 0.9374101, 0.7401160, 0.6331776, 0.5401297, 0.4532644,…
## $ q0.025          &lt;dbl&gt; 0.8948342, 1.0189518, 1.1877727, 1.3724857, 1.5771321,…
## $ q0.5            &lt;dbl&gt; 1.701059, 1.800168, 1.895023, 2.027208, 2.188462, 2.28…
## $ q0.975          &lt;dbl&gt; 4.407098, 3.727074, 3.519524, 3.488390, 3.351370, 3.26…
## $ median          &lt;dbl&gt; 1.701059, 1.800168, 1.895023, 2.027208, 2.188462, 2.28…
## $ mean.mc_std_err &lt;dbl&gt; 0.09374101, 0.07401160, 0.06331776, 0.05401297, 0.0453…
## $ sd.mc_std_err   &lt;dbl&gt; 0.11741556, 0.07849490, 0.06781651, 0.05277743, 0.0407…</code></pre>
<p>You pass this data frame to the <code>plot()</code> method to produce the following prediction plot.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="tuesday-november-15-2022.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pred.df, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb28-2"><a href="tuesday-november-15-2022.html#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> pts2, </span>
<span id="cb28-3"><a href="tuesday-november-15-2022.html#cb28-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> x), </span>
<span id="cb28-4"><a href="tuesday-november-15-2022.html#cb28-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> <span class="dv">0</span>, <span class="at">pch =</span> <span class="st">&quot;|&quot;</span>, <span class="at">cex =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb28-5"><a href="tuesday-november-15-2022.html#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;x&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Spatial intensity&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>The LGCP model provides a smoothed spatial intensity of the events and a 95% credible interval about the intensity at each grid location.</p>
<p>How does this compare with the intensity function that generated the data?</p>
<p>The function <code>lambda2_1D( )</code>in the dataset <code>Poission2_1D</code> calculates the true intensity that was used in simulating these data.</p>
<p>To plot this, you make a data frame with x- and y-coordinates giving the true intensity function, <span class="math inline">\(\lambda\)</span>(s). Use a lot of x-values to get a nice smooth plot (150 values).</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="tuesday-november-15-2022.html#cb29-1" aria-hidden="true" tabindex="-1"></a>xs <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">55</span>, <span class="at">length =</span> <span class="dv">150</span>)</span>
<span id="cb29-2"><a href="tuesday-november-15-2022.html#cb29-2" aria-hidden="true" tabindex="-1"></a>true.lambda <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> xs, </span>
<span id="cb29-3"><a href="tuesday-november-15-2022.html#cb29-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">y =</span> <span class="fu">lambda2_1D</span>(xs))</span></code></pre></div>
<p>Now plot the fitted (from the LGCP model) and the true intensity functions.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="tuesday-november-15-2022.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pred.df, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb30-2"><a href="tuesday-november-15-2022.html#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> pts2, </span>
<span id="cb30-3"><a href="tuesday-november-15-2022.html#cb30-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> x), </span>
<span id="cb30-4"><a href="tuesday-november-15-2022.html#cb30-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> <span class="dv">0</span>, <span class="at">pch =</span> <span class="st">&quot;|&quot;</span>, <span class="at">cex =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb30-5"><a href="tuesday-november-15-2022.html#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> true.lambda, </span>
<span id="cb30-6"><a href="tuesday-november-15-2022.html#cb30-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">mapping =</span> <span class="fu">aes</span>(x, y)) <span class="sc">+</span></span>
<span id="cb30-7"><a href="tuesday-november-15-2022.html#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;x&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Spatial intensity&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>You can look at the goodness-of-fit of the model using the function <code>bincount( )</code>, which plots the 95% credible intervals in a specified set of bins along the x-axis together with the observed count in each bin.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="tuesday-november-15-2022.html#cb31-1" aria-hidden="true" tabindex="-1"></a>bc <span class="ot">&lt;-</span> <span class="fu">bincount</span>(</span>
<span id="cb31-2"><a href="tuesday-november-15-2022.html#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">result =</span> model.lgcp,</span>
<span id="cb31-3"><a href="tuesday-november-15-2022.html#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">observations =</span> pts2,</span>
<span id="cb31-4"><a href="tuesday-november-15-2022.html#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fu">max</span>(pts2), <span class="at">length =</span> <span class="dv">12</span>),</span>
<span id="cb31-5"><a href="tuesday-november-15-2022.html#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">predictor =</span> x <span class="sc">~</span> <span class="fu">exp</span>(spde1D <span class="sc">+</span> Intercept)</span>
<span id="cb31-6"><a href="tuesday-november-15-2022.html#cb31-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-7"><a href="tuesday-november-15-2022.html#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="tuesday-november-15-2022.html#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(bc)<span class="sc">$</span>ggp</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>The credible intervals are shown as red rectangles, the mean fitted value as a short horizontal blue line, and the observed data as black points.</p>
<p>Abundance is the integral of the intensity over space. You estimate it by integrating the predicted intensity over x.</p>
<p>Integration is done by a weighted sum of the intensities.</p>
<p>The locations x and their weights are constructed using the <code>ipoints()</code> function.</p>
<p>Here you create 50 equally-space integration points cover the 1D range. The weights are all the same (55/100).</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="tuesday-november-15-2022.html#cb32-1" aria-hidden="true" tabindex="-1"></a>ips <span class="ot">&lt;-</span> <span class="fu">ipoints</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">55</span>), <span class="dv">100</span>, <span class="at">name =</span> <span class="st">&quot;x&quot;</span>)</span>
<span id="cb32-2"><a href="tuesday-november-15-2022.html#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="tuesday-november-15-2022.html#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ips)</span></code></pre></div>
<pre><code>##       x weight group
## 1 0.275   0.55     1
## 2 0.825   0.55     1
## 3 1.375   0.55     1
## 4 1.925   0.55     1
## 5 2.475   0.55     1
## 6 3.025   0.55     1</code></pre>
<p>Then compute the abundance over the entire domain with the <code>predict()</code> method.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="tuesday-november-15-2022.html#cb34-1" aria-hidden="true" tabindex="-1"></a>( Lambda <span class="ot">&lt;-</span> <span class="fu">predict</span>(model.lgcp, </span>
<span id="cb34-2"><a href="tuesday-november-15-2022.html#cb34-2" aria-hidden="true" tabindex="-1"></a>                    ips, </span>
<span id="cb34-3"><a href="tuesday-november-15-2022.html#cb34-3" aria-hidden="true" tabindex="-1"></a>                    <span class="sc">~</span> <span class="fu">sum</span>(weight <span class="sc">*</span> <span class="fu">exp</span>(spde1D <span class="sc">+</span> Intercept))) )</span></code></pre></div>
<pre><code>##       mean       sd   q0.025     q0.5   q0.975   median mean.mc_std_err
## 1 129.7847 10.34895 110.3926 129.8629 153.7783 129.8629        1.034895
##   sd.mc_std_err
## 1     0.7929944</code></pre>
<ul>
<li><code>mean</code> is the posterior mean abundance</li>
<li><code>sd</code> is the estimated standard error of the posterior of the abundance</li>
<li><code>q0.025</code> and <code>q0.975</code> are the 95% credible interval bounds</li>
<li><code>q0.5</code> is the posterior median abundance</li>
</ul>
<p>The above posterior values for the abundance takes into account only the variance due to the parameters of the intensity function. It neglects the variance in the number of events, given the intensity function.</p>
<p>To include this you need to modify the input to the <code>predict( )</code> method. You include a data frame that samples from a Poisson density for each value of the abundance (here <code>N = 50:250</code>).</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="tuesday-november-15-2022.html#cb36-1" aria-hidden="true" tabindex="-1"></a>Nest <span class="ot">&lt;-</span> <span class="fu">predict</span>(model.lgcp, </span>
<span id="cb36-2"><a href="tuesday-november-15-2022.html#cb36-2" aria-hidden="true" tabindex="-1"></a>                ips,</span>
<span id="cb36-3"><a href="tuesday-november-15-2022.html#cb36-3" aria-hidden="true" tabindex="-1"></a>                <span class="sc">~</span> <span class="fu">data.frame</span>(<span class="at">N =</span> <span class="dv">50</span><span class="sc">:</span><span class="dv">250</span>,</span>
<span id="cb36-4"><a href="tuesday-november-15-2022.html#cb36-4" aria-hidden="true" tabindex="-1"></a>                             <span class="at">dpois =</span> <span class="fu">dpois</span>(<span class="dv">50</span><span class="sc">:</span><span class="dv">250</span>,</span>
<span id="cb36-5"><a href="tuesday-november-15-2022.html#cb36-5" aria-hidden="true" tabindex="-1"></a>                             <span class="at">lambda =</span> <span class="fu">sum</span>(weight <span class="sc">*</span> <span class="fu">exp</span>(spde1D <span class="sc">+</span> Intercept)))))</span></code></pre></div>
<p>The result is the same statistics as were calculated for <code>Lambda</code>, but here for every abundance value between 50 and 250, rather than for the posterior mean abundance alone.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="tuesday-november-15-2022.html#cb37-1" aria-hidden="true" tabindex="-1"></a>Nest <span class="sc">|&gt;</span></span>
<span id="cb37-2"><a href="tuesday-november-15-2022.html#cb37-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 201
## Columns: 9
## $ N               &lt;dbl&gt; 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63…
## $ mean            &lt;dbl&gt; 7.817213e-12, 1.651472e-11, 3.423363e-11, 6.965730e-11…
## $ sd              &lt;dbl&gt; 4.979422e-11, 1.041234e-10, 2.135674e-10, 4.298351e-10…
## $ q0.025          &lt;dbl&gt; 7.317116e-22, 2.155683e-21, 6.228954e-21, 1.766004e-20…
## $ q0.5            &lt;dbl&gt; 1.451814e-16, 3.763544e-16, 9.568641e-16, 2.386884e-15…
## $ q0.975          &lt;dbl&gt; 6.009402e-11, 1.292125e-10, 2.725134e-10, 5.639532e-10…
## $ median          &lt;dbl&gt; 1.451814e-16, 3.763544e-16, 9.568641e-16, 2.386884e-15…
## $ mean.mc_std_err &lt;dbl&gt; 4.979422e-12, 1.041234e-11, 2.135674e-11, 4.298351e-11…
## $ sd.mc_std_err   &lt;dbl&gt; 2.147275e-11, 4.464829e-11, 9.104312e-11, 1.821269e-10…</code></pre>
<p>You compute the 95% prediction interval and the median with the <code>inla.qmarginal()</code> function.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="tuesday-november-15-2022.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">inla.qmarginal</span>(<span class="fu">c</span>(.<span class="dv">025</span>, .<span class="dv">5</span>, .<span class="dv">975</span>), </span>
<span id="cb39-2"><a href="tuesday-november-15-2022.html#cb39-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">marginal =</span> <span class="fu">list</span>(<span class="at">x =</span> Nest<span class="sc">$</span>N, </span>
<span id="cb39-3"><a href="tuesday-november-15-2022.html#cb39-3" aria-hidden="true" tabindex="-1"></a>                               <span class="at">y =</span> Nest<span class="sc">$</span>mean))</span></code></pre></div>
<pre><code>## [1] 100.9000 130.2834 162.4960</code></pre>
<p>Now compare <code>Lambda</code> to <code>Nest</code> using a plot.</p>
<p>First calculate the posterior conditional on the mean of <code>Lambda</code>.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="tuesday-november-15-2022.html#cb41-1" aria-hidden="true" tabindex="-1"></a>Nest<span class="sc">$</span>plugin_estimate <span class="ot">&lt;-</span> <span class="fu">dpois</span>(Nest<span class="sc">$</span>N, </span>
<span id="cb41-2"><a href="tuesday-november-15-2022.html#cb41-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">lambda =</span> Lambda<span class="sc">$</span>mean)</span></code></pre></div>
<p>Then plot it and the unconditional posterior.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="tuesday-november-15-2022.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Nest) <span class="sc">+</span></span>
<span id="cb42-2"><a href="tuesday-november-15-2022.html#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> N, </span>
<span id="cb42-3"><a href="tuesday-november-15-2022.html#cb42-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">y =</span> mean, </span>
<span id="cb42-4"><a href="tuesday-november-15-2022.html#cb42-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">color =</span> <span class="st">&quot;Posterior&quot;</span>)) <span class="sc">+</span></span>
<span id="cb42-5"><a href="tuesday-november-15-2022.html#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> N, </span>
<span id="cb42-6"><a href="tuesday-november-15-2022.html#cb42-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">y =</span> plugin_estimate, </span>
<span id="cb42-7"><a href="tuesday-november-15-2022.html#cb42-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">color =</span> <span class="st">&quot;Plugin&quot;</span>))</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>Can you explain the difference?</p>
<p>Spatial distribution of gorilla nests using SPDE <a href="https://inlabru-org.github.io/inlabru/index.html" class="uri">https://inlabru-org.github.io/inlabru/index.html</a></p>
<p>More info <a href="https://inlabru-org.github.io/inlabru/articles/web/1d_lgcp.html" class="uri">https://inlabru-org.github.io/inlabru/articles/web/1d_lgcp.html</a></p>
</div>
<div id="assessing-how-well-the-model-fits-1" class="section level2 unnumbered hasAnchor">
<h2>Assessing how well the model fits<a href="tuesday-november-15-2022.html#assessing-how-well-the-model-fits-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A model should be capable of generating fake data that are statistically indistinguishable from the real data. If your model is a point pattern model you produce samples of event locations with the <code>simulate()</code> function.</p>
<p>Let’s return to the Swedish pine sapling data and the inhibition model that you fit last time.</p>
<p>You assume a (stationary) Strauss process with interaction radius r. The parameters <span class="math inline">\(\beta\)</span> and <span class="math inline">\(\gamma\)</span> define the pairwise interaction in which each event contributes a factor <span class="math inline">\(\beta\)</span> to the probability density of the point pattern, and each pair of events closer than r units apart contributes a factor <span class="math inline">\(\gamma\)</span> to the density where <span class="math inline">\(\gamma\)</span> is less than one.</p>
<p>You use the <code>ppm()</code> function and include the point pattern data as the first argument. You set the trend term to a constant (implying a stationary process) with the argument <code>trend ~ 1</code> and the interaction radius to 10 units with the argument <code>interaction = Strauss(r = 10)</code> and a border correction out to a distance of 10 units from the window with the <code>rbord =</code> argument.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="tuesday-november-15-2022.html#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spatstat)</span></code></pre></div>
<pre><code>## Loading required package: spatstat.data</code></pre>
<pre><code>## Loading required package: spatstat.geom</code></pre>
<pre><code>## spatstat.geom 2.4-0</code></pre>
<pre><code>## 
## Attaching package: &#39;spatstat.geom&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:inlabru&#39;:
## 
##     vertices</code></pre>
<pre><code>## Loading required package: spatstat.random</code></pre>
<pre><code>## spatstat.random 2.2-0</code></pre>
<pre><code>## Loading required package: spatstat.core</code></pre>
<pre><code>## Loading required package: rpart</code></pre>
<pre><code>## spatstat.core 2.4-4</code></pre>
<pre><code>## Loading required package: spatstat.linnet</code></pre>
<pre><code>## spatstat.linnet 2.3-2</code></pre>
<pre><code>## 
## spatstat 2.3-4       (nickname: &#39;Watch this space&#39;) 
## For an introduction to spatstat, type &#39;beginner&#39;</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="tuesday-november-15-2022.html#cb57-1" aria-hidden="true" tabindex="-1"></a>SP <span class="ot">&lt;-</span> swedishpines</span>
<span id="cb57-2"><a href="tuesday-november-15-2022.html#cb57-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-3"><a href="tuesday-november-15-2022.html#cb57-3" aria-hidden="true" tabindex="-1"></a>model.in <span class="ot">&lt;-</span> SP <span class="sc">|&gt;</span></span>
<span id="cb57-4"><a href="tuesday-november-15-2022.html#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ppm</span>(<span class="at">trend =</span> <span class="sc">~</span> <span class="dv">1</span>, </span>
<span id="cb57-5"><a href="tuesday-november-15-2022.html#cb57-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">interaction =</span> <span class="fu">Strauss</span>(<span class="at">r =</span> <span class="dv">10</span>), </span>
<span id="cb57-6"><a href="tuesday-november-15-2022.html#cb57-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">rbord =</span> <span class="dv">10</span>)</span></code></pre></div>
<p>Here you generate three samples of the Swedish pine sapling data and for comparison plot them alongside the actual data.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="tuesday-november-15-2022.html#cb58-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> model.in <span class="sc">|&gt;</span></span>
<span id="cb58-2"><a href="tuesday-november-15-2022.html#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">simulate</span>(<span class="at">nsim =</span> <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## Generating 3 simulated patterns ...1, 2,  3.</code></pre>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="tuesday-november-15-2022.html#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(SP) </span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="tuesday-november-15-2022.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X[[<span class="dv">1</span>]])</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-26-2.png" width="672" /></p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="tuesday-november-15-2022.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X[[<span class="dv">2</span>]])</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-26-3.png" width="672" /></p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="tuesday-november-15-2022.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X[[<span class="dv">3</span>]])</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-26-4.png" width="672" /></p>
<p>The samples of point pattern data look similar to the actual data providing evidence that the inhibition model is adequate.</p>
<p>To quantitatively assess the similarity you can use the <code>envelope()</code> function to compute the <span class="math inline">\(K\)</span> function on 99 samples and on the actual data.</p>
<p>The <span class="math inline">\(K\)</span> function values are averaged over all samples and a mean line represents the mean model curve. Uncertainty is assessed with a band that ranges from the minimum to the maximum K at each distance.</p>
<p>Do this with the inhibition model for the pine saplings. This takes a few seconds to complete.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="tuesday-november-15-2022.html#cb64-1" aria-hidden="true" tabindex="-1"></a>model.in <span class="sc">|&gt;</span></span>
<span id="cb64-2"><a href="tuesday-november-15-2022.html#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">envelope</span>(<span class="at">fun =</span> Kest, </span>
<span id="cb64-3"><a href="tuesday-november-15-2022.html#cb64-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">nsim =</span> <span class="dv">99</span>, </span>
<span id="cb64-4"><a href="tuesday-november-15-2022.html#cb64-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">correction =</span> <span class="st">&#39;border&#39;</span>) <span class="sc">|&gt;</span></span>
<span id="cb64-5"><a href="tuesday-november-15-2022.html#cb64-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="at">legend =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Generating 99 simulated realisations of fitted Gibbs model  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
## 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,  99.
## 
## Done.</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p>The black line is the empirical (data) curve and the red line is the average over the 99 samples. The two lines are close and the black line falls nearly completely within the gray uncertainty band indicating the model fits the data well. The kink in the red curve is the result of specifying 10 units for the interaction distance.</p>
<p>From this plot you confidently conclude that a homogeneous inhibition model is adequate for describing the pine sapling data.</p>
<p>What about the cluster model for the maple trees? You used a Thomas cluster process which means that centered on each event the chance of a nearby event decays as a two-dimensional Gaussian distribution. The latent rate of a nearby event is a two-dimensional kernel.</p>
<p>This differs from a Matern cluster process which means that centered on each event there is an equal chance of a nearby event out to some distance r.</p>
<p>Use use the <code>kppm()</code> function and include the point pattern data as the first argument. You assume stationarity so <code>trend = 1</code> and the argument <code>clusters =</code> is set to <code>"Thomas"</code>.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="tuesday-november-15-2022.html#cb66-1" aria-hidden="true" tabindex="-1"></a>MT <span class="ot">&lt;-</span> lansing <span class="sc">|&gt;</span></span>
<span id="cb66-2"><a href="tuesday-november-15-2022.html#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">subset</span>(marks <span class="sc">==</span> <span class="st">&quot;maple&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb66-3"><a href="tuesday-november-15-2022.html#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unmark</span>()</span>
<span id="cb66-4"><a href="tuesday-november-15-2022.html#cb66-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-5"><a href="tuesday-november-15-2022.html#cb66-5" aria-hidden="true" tabindex="-1"></a>( model.cl <span class="ot">&lt;-</span> MT <span class="sc">|&gt;</span></span>
<span id="cb66-6"><a href="tuesday-november-15-2022.html#cb66-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kppm</span>(<span class="at">trend =</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb66-7"><a href="tuesday-november-15-2022.html#cb66-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">clusters =</span> <span class="st">&quot;Thomas&quot;</span>) )</span></code></pre></div>
<pre><code>## Stationary cluster point process model
## Fitted to point pattern dataset &#39;MT&#39;
## Fitted by minimum contrast
##  Summary statistic: K-function
## 
## Uniform intensity:   514
## 
## Cluster model: Thomas process
## Fitted cluster parameters:
##       kappa       scale 
## 21.74344366  0.06752959 
## Mean cluster size:  23.63931 points</code></pre>
<p>Now plot the <span class="math inline">\(K\)</span> function on the data and on 99 model simulations.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="tuesday-november-15-2022.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">envelope</span>(model.cl, </span>
<span id="cb68-2"><a href="tuesday-november-15-2022.html#cb68-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">fun =</span> Kest, </span>
<span id="cb68-3"><a href="tuesday-november-15-2022.html#cb68-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">nsim =</span> <span class="dv">99</span>, </span>
<span id="cb68-4"><a href="tuesday-november-15-2022.html#cb68-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">correction =</span> <span class="st">&#39;border&#39;</span>), <span class="at">legend =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Generating 99 simulated realisations of fitted cluster model  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
## 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,  99.
## 
## Done.</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<p>In the case of the maple trees, a cluster model is adequate.</p>
<p>However, it might not be satisfying since you know about the potential for inhibition caused by the presence of hickory trees.</p>
<p>Also there were more trees in the south than in the north so the stationary assumption is suspect.</p>
<p>You fit a second cluster model where the intensity is a linear function of distance in the north-south direction.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="tuesday-november-15-2022.html#cb70-1" aria-hidden="true" tabindex="-1"></a>model.cl2 <span class="ot">&lt;-</span> MT <span class="sc">|&gt;</span></span>
<span id="cb70-2"><a href="tuesday-november-15-2022.html#cb70-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kppm</span>(<span class="at">trend =</span> <span class="sc">~</span> y,</span>
<span id="cb70-3"><a href="tuesday-november-15-2022.html#cb70-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">clusters =</span> <span class="st">&quot;Thomas&quot;</span>)</span>
<span id="cb70-4"><a href="tuesday-november-15-2022.html#cb70-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-5"><a href="tuesday-november-15-2022.html#cb70-5" aria-hidden="true" tabindex="-1"></a>model.cl2</span></code></pre></div>
<pre><code>## Inhomogeneous cluster point process model
## Fitted to point pattern dataset &#39;MT&#39;
## Fitted by minimum contrast
##  Summary statistic: inhomogeneous K-function
## 
## Log intensity:  ~y
## 
## Fitted trend coefficients:
## (Intercept)           y 
##    6.894933   -1.486252 
## 
## Cluster model: Thomas process
## Fitted cluster parameters:
##     kappa     scale 
## 26.955877  0.053585 
## Mean cluster size:  [pixel image]</code></pre>
<p>This is an inhomogeneous cluster point process model. The logarithm of the intensity depends on y (<code>Log intensity:  ~y</code>). The fitted trend coefficient is negative as expected, since there are fewer trees as you move north (increasing y direction). There is one spatial unit in the north-south direction so you interpret this coefficient to mean there are 77% fewer trees in the north than in the south. The 77% comes from the formula 1 - exp(-1.486) = .77.</p>
<p>The average number of clusters (<code>kappa</code>) is higher at about 27 (it was 22 with the stationary model). The cluster scale parameter (<code>sigma</code>), indicating the characteristic size of the cluster (in distance units) is lower at .0536. That makes sense since some of the event-to-event distances are accounted for by the trend term.</p>
<p>Simulate data using the new model and compare the inhomogenous <span class="math inline">\(K\)</span> function between the simulations and the observed data.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="tuesday-november-15-2022.html#cb72-1" aria-hidden="true" tabindex="-1"></a>model.cl2 <span class="sc">|&gt;</span> </span>
<span id="cb72-2"><a href="tuesday-november-15-2022.html#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">envelope</span>(<span class="at">fun =</span> Kinhom, </span>
<span id="cb72-3"><a href="tuesday-november-15-2022.html#cb72-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">nsim =</span> <span class="dv">99</span>,</span>
<span id="cb72-4"><a href="tuesday-november-15-2022.html#cb72-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">correction =</span> <span class="st">&#39;border&#39;</span>) <span class="sc">|&gt;</span></span>
<span id="cb72-5"><a href="tuesday-november-15-2022.html#cb72-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="at">legend =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Generating 99 simulated realisations of fitted cluster model  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
## 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,  99.
## 
## Done.</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<p>The black line falls within the gray band and the gray band is narrower than the simulations using the homogeneous cluster model.</p>
<p>If the intensity of events depends on spatial location as it does with the maple trees you can include a trend and covariate term in the model.</p>
<p>For a trend term, the <code>formula ~ x</code> corresponds to a spatial trend of the form <span class="math inline">\(\lambda(x) = \exp(a + bx)\)</span>, while <code>~ x + y</code> corresponds to <span class="math inline">\(\lambda(x, y) = \exp(a + bx + cy)\)</span> where <code>x</code>, <code>y</code> are the spatial coordinates. For a covariates, the formula is <code>~ covariate1 + covariate2</code>.</p>
<p>Consider the <code>bei</code> data from the {spatstat} package containing the locations of 3605 trees in a tropical rain forest.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="tuesday-november-15-2022.html#cb74-1" aria-hidden="true" tabindex="-1"></a>bei <span class="sc">|&gt;</span></span>
<span id="cb74-2"><a href="tuesday-november-15-2022.html#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p>Accompanied by covariate data giving the elevation (altitude) and slope of elevation in the study region. The data <code>bei.extra</code> is a list containing two pixel images, <code>elev</code> (elevation in meters) and <code>grad</code> (norm of elevation gradient). These pixel images are objects of class <code>im</code>, see <code>im.object</code>.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="tuesday-november-15-2022.html#cb75-1" aria-hidden="true" tabindex="-1"></a>bei.extra <span class="sc">|&gt;</span></span>
<span id="cb75-2"><a href="tuesday-november-15-2022.html#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">image</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<p>Compute and plot the <span class="math inline">\(L\)</span> function on the <code>ppp</code> object <code>bei</code>.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="tuesday-november-15-2022.html#cb76-1" aria-hidden="true" tabindex="-1"></a>bei <span class="sc">|&gt;</span></span>
<span id="cb76-2"><a href="tuesday-november-15-2022.html#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">envelope</span>(<span class="at">fun =</span> Lest,</span>
<span id="cb76-3"><a href="tuesday-november-15-2022.html#cb76-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">nsim =</span> <span class="dv">39</span>, </span>
<span id="cb76-4"><a href="tuesday-november-15-2022.html#cb76-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">global =</span> <span class="cn">TRUE</span>, </span>
<span id="cb76-5"><a href="tuesday-november-15-2022.html#cb76-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">correction =</span> <span class="st">&quot;border&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb76-6"><a href="tuesday-november-15-2022.html#cb76-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="at">legend =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Generating 39 simulations of CSR  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,  39.
## 
## Done.</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<p>There is significant clustering indicated by the black line sitting far above the CSR line. There are more trees in the vicinity of other trees than expected by chance.</p>
<p>But how much of the clustering is due to variations in terrain?</p>
<p>You start by fitting a model that includes elevation and gradient as covariates without clustering. This is done with the <code>trend =</code> argument naming the image variables and including the argument <code>covariates =</code> indicating a data frame or, in this case, a list whose entries are image functions.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="tuesday-november-15-2022.html#cb78-1" aria-hidden="true" tabindex="-1"></a>model.ppm1 <span class="ot">&lt;-</span> bei <span class="sc">|&gt;</span></span>
<span id="cb78-2"><a href="tuesday-november-15-2022.html#cb78-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ppm</span>(<span class="at">trend =</span> <span class="sc">~</span> elev <span class="sc">+</span> grad, </span>
<span id="cb78-3"><a href="tuesday-november-15-2022.html#cb78-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">covariates =</span> bei.extra)</span></code></pre></div>
<p>Check to see if elevation and gradient as explanatory variables are significant in the model.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="tuesday-november-15-2022.html#cb79-1" aria-hidden="true" tabindex="-1"></a>model.ppm1 <span class="sc">|&gt;</span></span>
<span id="cb79-2"><a href="tuesday-november-15-2022.html#cb79-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## Point process model
## Fitting method: maximum likelihood (Berman-Turner approximation)
## Model was fitted using glm()
## Algorithm converged
## Call:
## ppm.ppp(Q = bei, trend = ~elev + grad, covariates = bei.extra)
## Edge correction: &quot;border&quot;
##  [border correction distance r = 0 ]
## --------------------------------------------------------------------------------
## Quadrature scheme (Berman-Turner) = data + dummy + weights
## 
## Data pattern:
## Planar point pattern:  3604 points
## Average intensity 0.00721 points per square metre
## Window: rectangle = [0, 1000] x [0, 500] metres
## Window area = 5e+05 square metres
## Unit of length: 1 metre
## 
## Dummy quadrature points:
##      130 x 130 grid of dummy points, plus 4 corner points
##      dummy spacing: 7.692308 x 3.846154 metres
## 
## Original dummy parameters: =
## Planar point pattern:  16904 points
## Average intensity 0.0338 points per square metre
## Window: rectangle = [0, 1000] x [0, 500] metres
## Window area = 5e+05 square metres
## Unit of length: 1 metre
## Quadrature weights:
##      (counting weights based on 130 x 130 array of rectangular tiles)
## All weights:
##  range: [1.64, 29.6] total: 5e+05
## Weights on data points:
##  range: [1.64, 14.8] total: 41000
## Weights on dummy points:
##  range: [1.64, 29.6] total: 459000
## --------------------------------------------------------------------------------
## FITTED MODEL:
## 
## Nonstationary Poisson process
## 
## ---- Intensity: ----
## 
## Log intensity: ~elev + grad
## Model depends on external covariates &#39;elev&#39; and &#39;grad&#39;
## Covariates provided:
##  elev: im
##  grad: im
## 
## Fitted trend coefficients:
## (Intercept)        elev        grad 
## -8.56355220  0.02143995  5.84646680 
## 
##                Estimate        S.E.     CI95.lo     CI95.hi Ztest       Zval
## (Intercept) -8.56355220 0.341113849 -9.23212306 -7.89498134   *** -25.104675
## elev         0.02143995 0.002287866  0.01695581  0.02592408   ***   9.371155
## grad         5.84646680 0.255781018  5.34514522  6.34778838   ***  22.857313
## 
## ----------- gory details -----
## 
## Fitted regular parameters (theta):
## (Intercept)        elev        grad 
## -8.56355220  0.02143995  5.84646680 
## 
## Fitted exp(theta):
##  (Intercept)         elev         grad 
## 1.909398e-04 1.021671e+00 3.460097e+02</code></pre>
<p>The output shows that both elevation and elevation gradient are significant in explaining the spatial varying intensity of the trees.</p>
<p>Since the conditional intensity is on a log scale you interpret the elevation coefficient as follows: For a one meter increase in elevation the local spatial intensity increases by a amount equal to exp(.021) or 2%.</p>
<p>Check how well the model fits the data. Again this is done with the <code>envelope()</code> function using the model object as the first argument.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="tuesday-november-15-2022.html#cb81-1" aria-hidden="true" tabindex="-1"></a>E <span class="ot">&lt;-</span> model.ppm1 <span class="sc">|&gt;</span></span>
<span id="cb81-2"><a href="tuesday-november-15-2022.html#cb81-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">envelope</span>(<span class="at">fun =</span> Lest, </span>
<span id="cb81-3"><a href="tuesday-november-15-2022.html#cb81-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">nsim =</span> <span class="dv">39</span>,</span>
<span id="cb81-4"><a href="tuesday-november-15-2022.html#cb81-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">correction =</span> <span class="st">&quot;border&quot;</span>,</span>
<span id="cb81-5"><a href="tuesday-november-15-2022.html#cb81-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">global =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Generating 78 simulated realisations of fitted Poisson model (39 to estimate 
## the mean and 39 to calculate envelopes) ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,  78.
## 
## Done.</code></pre>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="tuesday-november-15-2022.html#cb83-1" aria-hidden="true" tabindex="-1"></a>E <span class="sc">|&gt;</span></span>
<span id="cb83-2"><a href="tuesday-november-15-2022.html#cb83-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="at">main =</span> <span class="st">&quot;Inhomogeneous Poisson Model&quot;</span>, </span>
<span id="cb83-3"><a href="tuesday-november-15-2022.html#cb83-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<p>You conclude that although elevation and elevation slope are significant in explaining the spatial distribution of trees, they do not explain all the clustering.</p>
<p>An improvement is made by adding a cluster process to the model. This is done with the function <code>kppm()</code>.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="tuesday-november-15-2022.html#cb84-1" aria-hidden="true" tabindex="-1"></a>model.ppm2 <span class="ot">&lt;-</span> bei <span class="sc">|&gt;</span></span>
<span id="cb84-2"><a href="tuesday-november-15-2022.html#cb84-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kppm</span>(<span class="at">trend =</span> <span class="sc">~</span> elev <span class="sc">+</span> grad, </span>
<span id="cb84-3"><a href="tuesday-november-15-2022.html#cb84-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">covariates =</span> bei.extra, </span>
<span id="cb84-4"><a href="tuesday-november-15-2022.html#cb84-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">clusters =</span> <span class="st">&quot;Thomas&quot;</span>)</span>
<span id="cb84-5"><a href="tuesday-november-15-2022.html#cb84-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-6"><a href="tuesday-november-15-2022.html#cb84-6" aria-hidden="true" tabindex="-1"></a>E <span class="ot">&lt;-</span> model.ppm2 <span class="sc">|&gt;</span></span>
<span id="cb84-7"><a href="tuesday-november-15-2022.html#cb84-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">envelope</span>(Lest, </span>
<span id="cb84-8"><a href="tuesday-november-15-2022.html#cb84-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">nsim =</span> <span class="dv">39</span>, </span>
<span id="cb84-9"><a href="tuesday-november-15-2022.html#cb84-9" aria-hidden="true" tabindex="-1"></a>           <span class="at">global =</span> <span class="cn">TRUE</span>, </span>
<span id="cb84-10"><a href="tuesday-november-15-2022.html#cb84-10" aria-hidden="true" tabindex="-1"></a>           <span class="at">correction =</span> <span class="st">&quot;border&quot;</span>)</span></code></pre></div>
<pre><code>## Generating 78 simulated realisations of fitted cluster model (39 to estimate 
## the mean and 39 to calculate envelopes) ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,  78.
## 
## Done.</code></pre>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="tuesday-november-15-2022.html#cb86-1" aria-hidden="true" tabindex="-1"></a>E <span class="sc">|&gt;</span></span>
<span id="cb86-2"><a href="tuesday-november-15-2022.html#cb86-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="at">main =</span> <span class="st">&quot;Clustered Inhomogeneous Model&quot;</span>, </span>
<span id="cb86-3"><a href="tuesday-november-15-2022.html#cb86-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<p>The uncertainty band is much wider. The empirical curve fits inside the band so you conclude that an inhomogeneous cluster process appears to be an adequate description of the point pattern data.</p>
</div>
<div id="example-from-my-research-on-tornadoes" class="section level2 hasAnchor" number="0.3">
<h2><span class="header-section-number">0.3</span> Example from my research on tornadoes<a href="tuesday-november-15-2022.html#example-from-my-research-on-tornadoes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The vast majority of tornadoes have winds of less than 60 m/s (120 mph). Violent tornadoes, with winds exceeding 90 m/s, are rare. Most of these potentially destructive and deadly tornadoes occur from rotating thunderstorms called supercells, with formation contingent on local (storm-scale) meteorological conditions.</p>
<p>The long-term risk of a tornado at a given location is assessed using historical records, however, the rarity of the most violent tornadoes make these rate estimates unstable. Here you use the more stable rate estimates from the larger set of less violent tornadoes to create more reliable estimates of violent tornado frequency.</p>
<p>For this exercise attention is restricted to tornadoes occurring in Kansas over the period 1954–2020.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="tuesday-november-15-2022.html#cb87-1" aria-hidden="true" tabindex="-1"></a>Torn.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="at">dsn =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;1950-2020-torn-initpoint&quot;</span>)) <span class="sc">|&gt;</span></span>
<span id="cb87-2"><a href="tuesday-november-15-2022.html#cb87-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3082</span>) <span class="sc">|&gt;</span></span>
<span id="cb87-3"><a href="tuesday-november-15-2022.html#cb87-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(mag <span class="sc">&gt;=</span> <span class="dv">0</span>, yr <span class="sc">&gt;=</span> <span class="dv">1954</span>) <span class="sc">|&gt;</span></span>
<span id="cb87-4"><a href="tuesday-november-15-2022.html#cb87-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">EF =</span> mag,</span>
<span id="cb87-5"><a href="tuesday-november-15-2022.html#cb87-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">EFf =</span> <span class="fu">as.factor</span>(EF)) <span class="sc">|&gt;</span></span>
<span id="cb87-6"><a href="tuesday-november-15-2022.html#cb87-6" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(yr, EF, EFf)</span></code></pre></div>
<pre><code>## Reading layer `1950-2020-torn-initpoint&#39; from data source 
##   `/Users/jameselsner/Desktop/ClassNotes/ASS-2022/data/1950-2020-torn-initpoint&#39; 
##   using driver `ESRI Shapefile&#39;
## Simple feature collection with 66244 features and 22 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -163.53 ymin: 17.7212 xmax: -64.7151 ymax: 61.02
## Geodetic CRS:  WGS 84</code></pre>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="tuesday-november-15-2022.html#cb89-1" aria-hidden="true" tabindex="-1"></a>W.sfc <span class="ot">&lt;-</span> USAboundaries<span class="sc">::</span><span class="fu">us_states</span>(<span class="at">states =</span> <span class="st">&quot;Kansas&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb89-2"><a href="tuesday-november-15-2022.html#cb89-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> sf<span class="sc">::</span><span class="fu">st_crs</span>(Torn.sf)) <span class="sc">|&gt;</span></span>
<span id="cb89-3"><a href="tuesday-november-15-2022.html#cb89-3" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_geometry</span>()</span>
<span id="cb89-4"><a href="tuesday-november-15-2022.html#cb89-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-5"><a href="tuesday-november-15-2022.html#cb89-5" aria-hidden="true" tabindex="-1"></a>Torn.sf <span class="ot">&lt;-</span> Torn.sf[W.sfc, ]</span></code></pre></div>
<p>Create a <code>owin</code> and <code>ppp</code> objects. Note that although you already subset by Kansas tornadoes above you need to subset on the <code>ppp</code> object to assign the KS boundary as the analysis window.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="tuesday-november-15-2022.html#cb90-1" aria-hidden="true" tabindex="-1"></a>KS.win <span class="ot">&lt;-</span> W.sfc <span class="sc">|&gt;</span></span>
<span id="cb90-2"><a href="tuesday-november-15-2022.html#cb90-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.owin</span>()</span>
<span id="cb90-3"><a href="tuesday-november-15-2022.html#cb90-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-4"><a href="tuesday-november-15-2022.html#cb90-4" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="ot">&lt;-</span> Torn.sf[<span class="st">&quot;EF&quot;</span>] <span class="sc">|&gt;</span></span>
<span id="cb90-5"><a href="tuesday-november-15-2022.html#cb90-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.ppp</span>()</span>
<span id="cb90-6"><a href="tuesday-november-15-2022.html#cb90-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-7"><a href="tuesday-november-15-2022.html#cb90-7" aria-hidden="true" tabindex="-1"></a>T.ppp <span class="ot">&lt;-</span> T.ppp[KS.win]</span>
<span id="cb90-8"><a href="tuesday-november-15-2022.html#cb90-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-9"><a href="tuesday-november-15-2022.html#cb90-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(T.ppp)</span></code></pre></div>
<pre><code>## Marked planar point pattern:  4139 points
## Average intensity 1.918005e-08 points per square unit
## 
## *Pattern contains duplicated points*
## 
## Coordinates are given to 1 decimal place
## i.e. rounded to the nearest multiple of 0.1 units
## 
## marks are numeric, of type &#39;double&#39;
## Summary:
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0000  0.0000  0.0000  0.6139  1.0000  5.0000 
## 
## Window: polygonal boundary
## single connected closed polygon with 169 vertices
## enclosing rectangle: [1317675.9, 1980294.8] x [7114969, 7458570] units
##                      (662600 x 343600 units)
## Window area = 2.15797e+11 square units
## Fraction of frame area: 0.948</code></pre>
<p>There are 4139 tornadoes over the period with an average intensity of 192 per 100 square kilometer (multiply the average intensity in square meters by 10^10).</p>
<p>Separate the point pattern data into non-violent tornadoes and violent tornadoes. The non-violent tornadoes include those with an EF rating of 0, 1, 2 or 3. The violent tornadoes include those with an EF rating of 4 or 5.</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="tuesday-november-15-2022.html#cb92-1" aria-hidden="true" tabindex="-1"></a>NV.ppp <span class="ot">&lt;-</span> T.ppp <span class="sc">|&gt;</span></span>
<span id="cb92-2"><a href="tuesday-november-15-2022.html#cb92-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">subset</span>(marks <span class="sc">&lt;=</span> <span class="dv">3</span> <span class="sc">&amp;</span> marks <span class="sc">&gt;=</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb92-3"><a href="tuesday-november-15-2022.html#cb92-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unmark</span>()</span>
<span id="cb92-4"><a href="tuesday-november-15-2022.html#cb92-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-5"><a href="tuesday-november-15-2022.html#cb92-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(NV.ppp)</span></code></pre></div>
<pre><code>## Planar point pattern:  4098 points
## Average intensity 1.899006e-08 points per square unit
## 
## *Pattern contains duplicated points*
## 
## Coordinates are given to 1 decimal place
## i.e. rounded to the nearest multiple of 0.1 units
## 
## Window: polygonal boundary
## single connected closed polygon with 169 vertices
## enclosing rectangle: [1317675.9, 1980294.8] x [7114969, 7458570] units
##                      (662600 x 343600 units)
## Window area = 2.15797e+11 square units
## Fraction of frame area: 0.948</code></pre>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="tuesday-november-15-2022.html#cb94-1" aria-hidden="true" tabindex="-1"></a>V.ppp <span class="ot">&lt;-</span> T.ppp <span class="sc">|&gt;</span></span>
<span id="cb94-2"><a href="tuesday-november-15-2022.html#cb94-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">subset</span>(marks <span class="sc">&gt;=</span> <span class="dv">4</span>) <span class="sc">|&gt;</span> </span>
<span id="cb94-3"><a href="tuesday-november-15-2022.html#cb94-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unmark</span>()</span>
<span id="cb94-4"><a href="tuesday-november-15-2022.html#cb94-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-5"><a href="tuesday-november-15-2022.html#cb94-5" aria-hidden="true" tabindex="-1"></a>V.ppp <span class="sc">|&gt;</span></span>
<span id="cb94-6"><a href="tuesday-november-15-2022.html#cb94-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## Planar point pattern:  41 points
## Average intensity 1.899933e-10 points per square unit
## 
## Coordinates are given to 1 decimal place
## i.e. rounded to the nearest multiple of 0.1 units
## 
## Window: polygonal boundary
## single connected closed polygon with 169 vertices
## enclosing rectangle: [1317675.9, 1980294.8] x [7114969, 7458570] units
##                      (662600 x 343600 units)
## Window area = 2.15797e+11 square units
## Fraction of frame area: 0.948</code></pre>
<p>The spatial intensity of the non-violent tornadoes is 190 per 100 sq km. The spatial intensity of the violent tornadoes is 1.9 per 100 square kilometer.</p>
<p>Plot the locations of the violent tornado events.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="tuesday-november-15-2022.html#cb96-1" aria-hidden="true" tabindex="-1"></a>V.ppp <span class="sc">|&gt;</span></span>
<span id="cb96-2"><a href="tuesday-november-15-2022.html#cb96-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>
<p>Early we found that the spatial intensity of tornado reports was a function of distance to nearest city with fewer reports in rural areas.</p>
<p>So here you include this as an explanatory variable. Import the data, set the CRS, and transform the CRS to match that of the tornadoes. Exclude cities with fewer than 1000 people.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="tuesday-november-15-2022.html#cb97-1" aria-hidden="true" tabindex="-1"></a>C.sf <span class="ot">&lt;-</span> USAboundaries<span class="sc">::</span><span class="fu">us_cities</span>() <span class="sc">|&gt;</span></span>
<span id="cb97-2"><a href="tuesday-november-15-2022.html#cb97-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(population <span class="sc">&gt;=</span> <span class="dv">1000</span>) <span class="sc">|&gt;</span></span>
<span id="cb97-3"><a href="tuesday-november-15-2022.html#cb97-3" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> sf<span class="sc">::</span><span class="fu">st_crs</span>(Torn.sf))</span></code></pre></div>
<pre><code>## City populations for contemporary data come from the 2010 census.</code></pre>
<p>Then convert the simple feature data frame to a <code>ppp</code> object. Then subset the events by the analysis window (Kansas border).</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="tuesday-november-15-2022.html#cb99-1" aria-hidden="true" tabindex="-1"></a>C.ppp <span class="ot">&lt;-</span> C.sf <span class="sc">|&gt;</span></span>
<span id="cb99-2"><a href="tuesday-november-15-2022.html#cb99-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.ppp</span>()</span></code></pre></div>
<pre><code>## Warning in as.ppp.sf(C.sf): only first attribute column is used for marks</code></pre>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="tuesday-november-15-2022.html#cb101-1" aria-hidden="true" tabindex="-1"></a>C.ppp <span class="ot">&lt;-</span> C.ppp[KS.win] <span class="sc">|&gt;</span></span>
<span id="cb101-2"><a href="tuesday-november-15-2022.html#cb101-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unmark</span>()</span>
<span id="cb101-3"><a href="tuesday-november-15-2022.html#cb101-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-4"><a href="tuesday-november-15-2022.html#cb101-4" aria-hidden="true" tabindex="-1"></a>C.ppp <span class="sc">|&gt;</span></span>
<span id="cb101-5"><a href="tuesday-november-15-2022.html#cb101-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-44-1.png" width="672" /></p>
<p>Next create a distance map of the city locations using the <code>distmap()</code> function.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="tuesday-november-15-2022.html#cb102-1" aria-hidden="true" tabindex="-1"></a>Zc <span class="ot">&lt;-</span> C.ppp <span class="sc">|&gt;</span></span>
<span id="cb102-2"><a href="tuesday-november-15-2022.html#cb102-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distmap</span>()</span>
<span id="cb102-3"><a href="tuesday-november-15-2022.html#cb102-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-4"><a href="tuesday-november-15-2022.html#cb102-4" aria-hidden="true" tabindex="-1"></a>Zc <span class="sc">|&gt;</span></span>
<span id="cb102-5"><a href="tuesday-november-15-2022.html#cb102-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-45-1.png" width="672" /></p>
<p>The pixel values of the <code>im</code> object are distances is meters. Blue indicates locations that are less than 20 km from a city.</p>
<p>Interest lies with the distance to nearest non-violent tornado. You check to see if this might be a useful variable in a model so you make a distance map for the non-violent events and then use the <code>rhohat()</code> function.</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="tuesday-november-15-2022.html#cb103-1" aria-hidden="true" tabindex="-1"></a>Znv <span class="ot">&lt;-</span> NV.ppp <span class="sc">|&gt;</span></span>
<span id="cb103-2"><a href="tuesday-november-15-2022.html#cb103-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distmap</span>()</span>
<span id="cb103-3"><a href="tuesday-november-15-2022.html#cb103-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb103-4"><a href="tuesday-november-15-2022.html#cb103-4" aria-hidden="true" tabindex="-1"></a>rhat <span class="ot">&lt;-</span> <span class="fu">rhohat</span>(V.ppp, Znv, </span>
<span id="cb103-5"><a href="tuesday-november-15-2022.html#cb103-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">adjust =</span> <span class="fl">1.5</span>, </span>
<span id="cb103-6"><a href="tuesday-november-15-2022.html#cb103-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">smoother =</span> <span class="st">&quot;kernel&quot;</span>, </span>
<span id="cb103-7"><a href="tuesday-november-15-2022.html#cb103-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">method =</span> <span class="st">&quot;transform&quot;</span>)</span>
<span id="cb103-8"><a href="tuesday-november-15-2022.html#cb103-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-9"><a href="tuesday-november-15-2022.html#cb103-9" aria-hidden="true" tabindex="-1"></a>dist <span class="ot">&lt;-</span> rhat<span class="sc">$</span>Znv</span>
<span id="cb103-10"><a href="tuesday-november-15-2022.html#cb103-10" aria-hidden="true" tabindex="-1"></a>rho <span class="ot">&lt;-</span> rhat<span class="sc">$</span>rho</span>
<span id="cb103-11"><a href="tuesday-november-15-2022.html#cb103-11" aria-hidden="true" tabindex="-1"></a>hi <span class="ot">&lt;-</span> rhat<span class="sc">$</span>hi</span>
<span id="cb103-12"><a href="tuesday-november-15-2022.html#cb103-12" aria-hidden="true" tabindex="-1"></a>lo <span class="ot">&lt;-</span> rhat<span class="sc">$</span>lo</span>
<span id="cb103-13"><a href="tuesday-november-15-2022.html#cb103-13" aria-hidden="true" tabindex="-1"></a>Rho.df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">dist =</span> dist, <span class="at">rho =</span> rho, <span class="at">hi =</span> hi, <span class="at">lo =</span> lo)</span>
<span id="cb103-14"><a href="tuesday-november-15-2022.html#cb103-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-15"><a href="tuesday-november-15-2022.html#cb103-15" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Rho.df) <span class="sc">+</span> </span>
<span id="cb103-16"><a href="tuesday-november-15-2022.html#cb103-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> dist, </span>
<span id="cb103-17"><a href="tuesday-november-15-2022.html#cb103-17" aria-hidden="true" tabindex="-1"></a>                            <span class="at">ymin =</span> lo, </span>
<span id="cb103-18"><a href="tuesday-november-15-2022.html#cb103-18" aria-hidden="true" tabindex="-1"></a>                            <span class="at">ymax =</span> hi), </span>
<span id="cb103-19"><a href="tuesday-november-15-2022.html#cb103-19" aria-hidden="true" tabindex="-1"></a>              <span class="at">alpha =</span> .<span class="dv">3</span>) <span class="sc">+</span> </span>
<span id="cb103-20"><a href="tuesday-november-15-2022.html#cb103-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> dist, <span class="at">y =</span> rho), <span class="at">col =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span> </span>
<span id="cb103-21"><a href="tuesday-november-15-2022.html#cb103-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Spatial intensity of violent tornadoes&quot;</span>) <span class="sc">+</span></span>
<span id="cb103-22"><a href="tuesday-november-15-2022.html#cb103-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Distance from nearest non-violent tornado (m)&quot;</span>) <span class="sc">+</span> </span>
<span id="cb103-23"><a href="tuesday-november-15-2022.html#cb103-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-46-1.png" width="672" /></p>
<p>This shows that regions that get non-violent tornadoes also see higher rates of violent tornadoes.</p>
<p>So the model should include two covariates (trend terms), distance to nearest city and distance to nearest non-violent tornado.</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="tuesday-november-15-2022.html#cb104-1" aria-hidden="true" tabindex="-1"></a>model.ppm1 <span class="ot">&lt;-</span> V.ppp <span class="sc">|&gt;</span></span>
<span id="cb104-2"><a href="tuesday-november-15-2022.html#cb104-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ppm</span>(<span class="at">trend =</span> <span class="sc">~</span> Zc <span class="sc">+</span> Znv, </span>
<span id="cb104-3"><a href="tuesday-november-15-2022.html#cb104-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">covariates =</span> <span class="fu">list</span>(<span class="at">Zc =</span> Zc, <span class="at">Znv =</span> Znv))</span>
<span id="cb104-4"><a href="tuesday-november-15-2022.html#cb104-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-5"><a href="tuesday-november-15-2022.html#cb104-5" aria-hidden="true" tabindex="-1"></a>model.ppm1 <span class="sc">|&gt;</span></span>
<span id="cb104-6"><a href="tuesday-november-15-2022.html#cb104-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>() <span class="sc">|&gt;</span></span>
<span id="cb104-7"><a href="tuesday-november-15-2022.html#cb104-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coef</span>()</span></code></pre></div>
<pre><code>##                  Estimate         S.E.       CI95.lo       CI95.hi Ztest
## (Intercept) -2.079665e+01 3.689920e-01 -2.151986e+01 -2.007344e+01   ***
## Zc          -3.213231e-05 1.118327e-05 -5.405111e-05 -1.021350e-05    **
## Znv         -2.235788e-04 8.585891e-05 -3.918592e-04 -5.529845e-05    **
##                   Zval
## (Intercept) -56.360705
## Zc           -2.873248
## Znv          -2.604026</code></pre>
<p>As expected the model shows fewer violent tornadoes with increasing distance from the nearest city (negative coefficient on <code>Zc</code>) and fewer violent tornadoes with increasing distance from a non-violent tornado (negative coefficient on <code>Znv</code>).</p>
<p>Since the spatial unit is meters the coefficient of -3.06e-05 is interpreted as a [1 - exp(-.0306)] * 100% or 3% decrease in violent tornado reports per kilometer of distance from a city. Similarly the coefficient on distance from nearest non-violent tornado is interpreted as a 23% decrease in violent tornado reports per kilometer of distance from nearest non-violent tornado.</p>
<p>Check if there is any residual nearest neighbor correlation.</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="tuesday-november-15-2022.html#cb106-1" aria-hidden="true" tabindex="-1"></a>E <span class="ot">&lt;-</span> model.ppm1 <span class="sc">|&gt;</span></span>
<span id="cb106-2"><a href="tuesday-november-15-2022.html#cb106-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">envelope</span>(<span class="at">fun =</span> Kest, </span>
<span id="cb106-3"><a href="tuesday-november-15-2022.html#cb106-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">nsim =</span> <span class="dv">39</span>,</span>
<span id="cb106-4"><a href="tuesday-november-15-2022.html#cb106-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">global =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Generating 78 simulated realisations of fitted Poisson model (39 to estimate 
## the mean and 39 to calculate envelopes) ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,  78.
## 
## Done.</code></pre>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="tuesday-november-15-2022.html#cb108-1" aria-hidden="true" tabindex="-1"></a>E <span class="sc">|&gt;</span></span>
<span id="cb108-2"><a href="tuesday-november-15-2022.html#cb108-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="at">main =</span> <span class="st">&quot;Inhomogeneous Poisson Model&quot;</span>, </span>
<span id="cb108-3"><a href="tuesday-november-15-2022.html#cb108-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<p>There appears to be a bit of regularity at smaller scales. The empirical curve (black line) falls slightly below the model (dashed red line). There are fewer nearby violent tornadoes than one would expect.</p>
<p>To see if this is statistically significant, you add an inhibition process to the model.</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="tuesday-november-15-2022.html#cb109-1" aria-hidden="true" tabindex="-1"></a>model.ppm2 <span class="ot">&lt;-</span> V.ppp <span class="sc">|&gt;</span> </span>
<span id="cb109-2"><a href="tuesday-november-15-2022.html#cb109-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ppm</span>(<span class="at">trend =</span> <span class="sc">~</span> Zc <span class="sc">+</span> Znv, </span>
<span id="cb109-3"><a href="tuesday-november-15-2022.html#cb109-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">covariates =</span> <span class="fu">list</span>(<span class="at">Zc =</span> Zc, <span class="at">Znv =</span> Znv),</span>
<span id="cb109-4"><a href="tuesday-november-15-2022.html#cb109-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">interaction =</span> <span class="fu">Strauss</span>(<span class="at">r =</span> <span class="dv">40000</span>))</span>
<span id="cb109-5"><a href="tuesday-november-15-2022.html#cb109-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb109-6"><a href="tuesday-november-15-2022.html#cb109-6" aria-hidden="true" tabindex="-1"></a>model.ppm2 <span class="sc">|&gt;</span></span>
<span id="cb109-7"><a href="tuesday-november-15-2022.html#cb109-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>() <span class="sc">|&gt;</span></span>
<span id="cb109-8"><a href="tuesday-november-15-2022.html#cb109-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coef</span>()</span></code></pre></div>
<pre><code>##                  Estimate         S.E.       CI95.lo       CI95.hi Ztest
## (Intercept) -1.999626e+01 0.6389281922 -2.124853e+01 -1.874398e+01   ***
## Zc          -4.125674e-05 0.0000129859 -6.670864e-05 -1.580484e-05    **
## Znv         -2.325491e-04 0.0001163074 -4.605075e-04 -4.590757e-06     *
## Interaction -6.232454e-01 0.3926001130 -1.392727e+00  1.462367e-01      
##                   Zval
## (Intercept) -31.296564
## Zc           -3.177041
## Znv          -1.999435
## Interaction  -1.587481</code></pre>
<p>The interaction coefficient has a negative sign as expected from the above plot, but the standard error is relatively large so it is not statistically significant.</p>
<p>Remove the inhibition process and add a trend term in the east-west direction.</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="tuesday-november-15-2022.html#cb111-1" aria-hidden="true" tabindex="-1"></a>model.ppm3 <span class="ot">&lt;-</span> V.ppp <span class="sc">|&gt;</span></span>
<span id="cb111-2"><a href="tuesday-november-15-2022.html#cb111-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ppm</span>(<span class="at">trend =</span> <span class="sc">~</span> Zc <span class="sc">+</span> Znv <span class="sc">+</span> x, </span>
<span id="cb111-3"><a href="tuesday-november-15-2022.html#cb111-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">covariates =</span> <span class="fu">list</span>(<span class="at">Zc =</span> Zc, <span class="at">Znv =</span> Znv))</span>
<span id="cb111-4"><a href="tuesday-november-15-2022.html#cb111-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-5"><a href="tuesday-november-15-2022.html#cb111-5" aria-hidden="true" tabindex="-1"></a>model.ppm3 <span class="sc">|&gt;</span></span>
<span id="cb111-6"><a href="tuesday-november-15-2022.html#cb111-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>() <span class="sc">|&gt;</span></span>
<span id="cb111-7"><a href="tuesday-november-15-2022.html#cb111-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coef</span>()</span></code></pre></div>
<pre><code>##                  Estimate         S.E.       CI95.lo       CI95.hi Ztest
## (Intercept) -2.381531e+01 1.891801e+00 -2.752317e+01 -2.010745e+01   ***
## Zc          -2.274246e-05 1.255697e-05 -4.735366e-05  1.868739e-06      
## Znv         -2.379710e-04 8.651254e-05 -4.075324e-04 -6.840952e-05    **
## x            1.681064e-06 1.020308e-06 -3.187026e-07  3.680830e-06      
##                   Zval
## (Intercept) -12.588694
## Zc           -1.811143
## Znv          -2.750711
## x             1.647605</code></pre>
<p>There is a significant eastward trend but it appears to confound the distance to city term because the Zc term is no longer significant. Why is this?</p>
<p>Settle on the first model and generate simulated data from it.</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="tuesday-november-15-2022.html#cb113-1" aria-hidden="true" tabindex="-1"></a>model.ppm1 <span class="sc">|&gt;</span></span>
<span id="cb113-2"><a href="tuesday-november-15-2022.html#cb113-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">simulate</span>(<span class="at">nsim =</span> <span class="dv">6</span>) <span class="sc">|&gt;</span></span>
<span id="cb113-3"><a href="tuesday-november-15-2022.html#cb113-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<pre><code>## Generating 6 simulated patterns ...1, 2, 3, 4, 5,  6.</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-51-1.png" width="672" /></p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="tuesday-november-15-2022.html#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(V.ppp)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-51-2.png" width="672" /></p>
<p>The model appears to due a good job simulating data that looks like the actual data.</p>
</div>
<div id="spatial-logistic-regression" class="section level2 unnumbered hasAnchor">
<h2>Spatial logistic regression<a href="tuesday-november-15-2022.html#spatial-logistic-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Spatial logistic regression is a popular model for point pattern data. The study domain is divided into a grid of cells; each cell is assigned the value one if it contains at least one event, and zero otherwise.</p>
<p>Then a logistic regression models the presence probability <span class="math inline">\(p = P(Y = 1)\)</span> as a function of explanatory variables <span class="math inline">\(X\)</span> in the (matrix) form</p>
<p><span class="math display">\[
\log \frac{p}{1-p} = \beta X
\]</span>
where the left-hand side is the logit (log of the odds ratio) and the <span class="math inline">\(\beta\)</span> are the coefficients to be determined.</p>
<p>If your data are stored as <code>ppp</code> objects, a spatial logistic model can be fit directly using functions from the {spatstat} package.</p>
<p>Let’s look at an example from the package (a good strategy in general when learning a new technique).</p>
<p>Consider the locations of 57 copper ore deposits (events) and 146 line segments representing geological ‘lineaments.’ Lineaments are linear features that consist of geological faults.</p>
<p>It is of interest to be able to predict the probability of a copper ore from the lineament pattern. The data are stored as a list in <code>copper</code>. The list contains a <code>ppp</code> object for the ore deposits and a <code>psp</code> object for the lineaments.</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="tuesday-november-15-2022.html#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(copper)</span>
<span id="cb116-2"><a href="tuesday-november-15-2022.html#cb116-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(copper<span class="sc">$</span>SouthPoints)</span>
<span id="cb116-3"><a href="tuesday-november-15-2022.html#cb116-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(copper<span class="sc">$</span>SouthLines, <span class="at">add =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-52-1.png" width="672" /></p>
<p>For convenience you first rotate the events (points and lines) by 90 degrees in the anticlockwise direction and save them as separate objects.</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="tuesday-november-15-2022.html#cb117-1" aria-hidden="true" tabindex="-1"></a>C <span class="ot">&lt;-</span> <span class="fu">rotate</span>(copper<span class="sc">$</span>SouthPoints, pi<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb117-2"><a href="tuesday-november-15-2022.html#cb117-2" aria-hidden="true" tabindex="-1"></a>L <span class="ot">&lt;-</span> <span class="fu">rotate</span>(copper<span class="sc">$</span>SouthLines, pi<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb117-3"><a href="tuesday-november-15-2022.html#cb117-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb117-4"><a href="tuesday-november-15-2022.html#cb117-4" aria-hidden="true" tabindex="-1"></a>C <span class="sc">|&gt;</span></span>
<span id="cb117-5"><a href="tuesday-november-15-2022.html#cb117-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span>
<span id="cb117-6"><a href="tuesday-november-15-2022.html#cb117-6" aria-hidden="true" tabindex="-1"></a>L <span class="sc">|&gt;</span></span>
<span id="cb117-7"><a href="tuesday-november-15-2022.html#cb117-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="at">add =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-53-1.png" width="672" /></p>
<p>You summarize the planar point pattern data object <code>C</code>.</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="tuesday-november-15-2022.html#cb118-1" aria-hidden="true" tabindex="-1"></a>C <span class="sc">|&gt;</span></span>
<span id="cb118-2"><a href="tuesday-november-15-2022.html#cb118-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## Planar point pattern:  57 points
## Average intensity 0.01020691 points per square km
## 
## Coordinates are given to 2 decimal places
## i.e. rounded to the nearest multiple of 0.01 km
## 
## Window: rectangle = [-158.233, -0.19] x [-0.335, 35] km
##                     (158 x 35.34 km)
## Window area = 5584.45 square km
## Unit of length: 1 km</code></pre>
<p>There are 57 ore deposits over a region of size 5584 square km resulting in an intensity of about .01 ore deposits per square km.</p>
<p>Next you create a distance map of the lineaments to be used as a covariate.</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="tuesday-november-15-2022.html#cb120-1" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> L <span class="sc">|&gt;</span></span>
<span id="cb120-2"><a href="tuesday-november-15-2022.html#cb120-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distmap</span>()</span>
<span id="cb120-3"><a href="tuesday-november-15-2022.html#cb120-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb120-4"><a href="tuesday-november-15-2022.html#cb120-4" aria-hidden="true" tabindex="-1"></a>D <span class="sc">|&gt;</span></span>
<span id="cb120-5"><a href="tuesday-november-15-2022.html#cb120-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-55-1.png" width="672" /></p>
<p>Spatial logistic regression models are fit with the <code>slrm()</code> function from the {spatstat} package.</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="tuesday-november-15-2022.html#cb121-1" aria-hidden="true" tabindex="-1"></a>model.slr <span class="ot">&lt;-</span> <span class="fu">slrm</span>(C <span class="sc">~</span> D)</span>
<span id="cb121-2"><a href="tuesday-november-15-2022.html#cb121-2" aria-hidden="true" tabindex="-1"></a>model.slr</span></code></pre></div>
<pre><code>## Fitted spatial logistic regression model
## Formula: C ~ D
## Fitted coefficients:
## (Intercept)           D 
## -4.72337865  0.07811134</code></pre>
<p>The model says that the odds of a copper ore along a lineament (D = 0) is exp(-4.723) = .00888. This is slightly less than the overall intensity of .01.</p>
<p>The model also says that for every one unit (one kilometer) increase in distance from a lineament the expected change in the log odds is .0781 [exp(.0781) = 1.0812] or an 8.1% increase in the odds. Ore deposits are more likely between the lineaments.</p>
<p>The fitted method produces an image (raster) of the window giving the local probability of an ore deposit. The values are the probability of a random ore deposit in each pixel.</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="tuesday-november-15-2022.html#cb123-1" aria-hidden="true" tabindex="-1"></a>model.slr <span class="sc">|&gt;</span></span>
<span id="cb123-2"><a href="tuesday-november-15-2022.html#cb123-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fitted</span>() <span class="sc">|&gt;</span></span>
<span id="cb123-3"><a href="tuesday-november-15-2022.html#cb123-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span>
<span id="cb123-4"><a href="tuesday-november-15-2022.html#cb123-4" aria-hidden="true" tabindex="-1"></a>C <span class="sc">|&gt;</span></span>
<span id="cb123-5"><a href="tuesday-november-15-2022.html#cb123-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="at">add =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-57-1.png" width="672" /></p>
<p>Integrating the predictions over the area equals the observed number of ore deposits.</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="tuesday-november-15-2022.html#cb124-1" aria-hidden="true" tabindex="-1"></a>model.slr <span class="sc">|&gt;</span></span>
<span id="cb124-2"><a href="tuesday-november-15-2022.html#cb124-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fitted</span>() <span class="sc">|&gt;</span></span>
<span id="cb124-3"><a href="tuesday-november-15-2022.html#cb124-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>()</span></code></pre></div>
<pre><code>## [1] 57</code></pre>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tuesday-november-8-2022.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="thursday-november-17-2022.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
