<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tuesday November 29, 2022 | GIS5122: Applied Spatial Statistics</title>
  <meta name="description" content="Tuesday November 29, 2022 | GIS5122: Applied Spatial Statistics" />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="Tuesday November 29, 2022 | GIS5122: Applied Spatial Statistics" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="jelsner/ASS-2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tuesday November 29, 2022 | GIS5122: Applied Spatial Statistics" />
  
  
  

<meta name="author" content="James B. Elsner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tuesday-november-22-2022.html"/>
<link rel="next" href="thursday-december-1-2022.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied Spatial Statistics</a></li>

<li class="divider"></li>
<li><a href="index.html#section" id="toc-section"></a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i>Syllabus</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#gis5122-applied-spatial-statistics"><i class="fa fa-check"></i>GIS5122: Applied Spatial Statistics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#contact-information"><i class="fa fa-check"></i>Contact information</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#course-description-and-expected-learning-outcomes"><i class="fa fa-check"></i>Course description and expected learning outcomes</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#grades-and-ethics"><i class="fa fa-check"></i>Grades and ethics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#outline-of-topics-and-schedule"><i class="fa fa-check"></i>Outline of topics and schedule</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#reference-materials"><i class="fa fa-check"></i>Reference materials</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#reproducible-research"><i class="fa fa-check"></i>Reproducible research</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html"><i class="fa fa-check"></i>Tuesday, August 23, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#install-r-and-rstudio-on-your-computer"><i class="fa fa-check"></i>Install R and RStudio on your computer</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#download-course-materials"><i class="fa fa-check"></i>Download course materials</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#read-the-syllabus"><i class="fa fa-check"></i>Read the syllabus</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#about-rstudio"><i class="fa fa-check"></i>About RStudio</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#lab-assignments"><i class="fa fa-check"></i>Lab assignments</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#getting-started-with-r"><i class="fa fa-check"></i>Getting started with R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#are-you-completely-new-to-r"><i class="fa fa-check"></i>Are you completely new to R?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html"><i class="fa fa-check"></i>Thursday, August 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-science-workflow-with-r-markdown"><i class="fa fa-check"></i>Data science workflow with R markdown</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#an-introduction-to-using-r"><i class="fa fa-check"></i>An introduction to using R</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-frames"><i class="fa fa-check"></i>Data frames</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html"><i class="fa fa-check"></i>Tuesday August 30, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#working-with-data-frames-using-base-r"><i class="fa fa-check"></i>Working with data frames using base R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#getting-data-into-r"><i class="fa fa-check"></i>Getting data into R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#working-with-data-frames-using-functions-from-dplyr"><i class="fa fa-check"></i>Working with data frames using functions from {dplyr}</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html"><i class="fa fa-check"></i>Thursday September 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#making-graphs"><i class="fa fa-check"></i>Making graphs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html"><i class="fa fa-check"></i>Thursday September 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#introduction-to-simple-features"><i class="fa fa-check"></i>Introduction to simple features</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#geo-computation-on-simple-features"><i class="fa fa-check"></i>Geo-computation on simple features</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html"><i class="fa fa-check"></i>Tuesday September 13, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#spatial-data-subsets-and-joins"><i class="fa fa-check"></i>Spatial data subsets and joins</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#interpolation-using-areal-weights"><i class="fa fa-check"></i>Interpolation using areal weights</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html"><i class="fa fa-check"></i>Thursday September 15, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#s4-spatial-data-objects"><i class="fa fa-check"></i>S4 spatial data objects</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#working-with-raster-data"><i class="fa fa-check"></i>Working with raster data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#working-with-space-time-data"><i class="fa fa-check"></i>Working with space-time data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html"><i class="fa fa-check"></i>Tuesday September 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#mapping-using-functions-from-the-ggplot2-package"><i class="fa fa-check"></i>Mapping using functions from the {ggplot2} package</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#mapping-using-functions-from-the-tmap-package"><i class="fa fa-check"></i>Mapping using functions from the {tmap} package</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#creating-an-interactive-map"><i class="fa fa-check"></i>Creating an interactive map</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#hillshape-and-colors-with-tidyterra"><i class="fa fa-check"></i>Hillshape and colors with tidyterra</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#adding-an-inset-map"><i class="fa fa-check"></i>Adding an inset map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html"><i class="fa fa-check"></i>Tuesday October 4, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#defining-spatial-neighborhoods-and-spatial-weights"><i class="fa fa-check"></i>Defining spatial neighborhoods and spatial weights</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#computing-autocorrelation"><i class="fa fa-check"></i>Computing autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#spatial-lag-and-its-relation-to-autocorrelation"><i class="fa fa-check"></i>Spatial lag and its relation to autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#other-neighbor-definitions"><i class="fa fa-check"></i>Other neighbor definitions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html"><i class="fa fa-check"></i>Thursday October 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#assessing-the-statistical-significance-of-autocorrelation"><i class="fa fa-check"></i>Assessing the statistical significance of autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#bivariate-spatial-autocorrelation"><i class="fa fa-check"></i>Bivariate spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#local-indicators-of-spatial-autocorrelation"><i class="fa fa-check"></i>Local indicators of spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#constraining-group-membership-based-on-spatial-autocorrelation"><i class="fa fa-check"></i>Constraining group membership based on spatial autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html"><i class="fa fa-check"></i>Tuesday October 11, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#estimating-spatial-autocorrelation-in-model-residuals"><i class="fa fa-check"></i>Estimating spatial autocorrelation in model residuals</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#choosing-a-spatial-regression-model"><i class="fa fa-check"></i>Choosing a spatial regression model</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#fitting-and-interpreting-spatial-regression-models"><i class="fa fa-check"></i>Fitting and interpreting spatial regression models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html"><i class="fa fa-check"></i>Thursday October 13, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html#fitting-and-interpreting-geographic-regression"><i class="fa fa-check"></i>Fitting and interpreting geographic regression</a></li>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html#mapping-incidence-and-risk-with-a-spatial-regression-model"><i class="fa fa-check"></i>Mapping incidence and risk with a spatial regression model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html"><i class="fa fa-check"></i>Thursday October 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#spatial-data-as-point-patterns"><i class="fa fa-check"></i>Spatial data as point patterns</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#theoretical-framework-for-analyzingmodeling-point-pattern-data"><i class="fa fa-check"></i>Theoretical framework for analyzing/modeling point pattern data</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#working-with-point-pattern-data-using-functions-from-the-spatstat-package"><i class="fa fa-check"></i>Working with point pattern data using functions from the spatstat package</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#quantifying-the-spatial-intensity-of-events"><i class="fa fa-check"></i>Quantifying the spatial intensity of events</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html"><i class="fa fa-check"></i>Tuesday October 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#creating-ppp-and-owin-objects-from-simple-feature-data-frames"><i class="fa fa-check"></i>Creating <code>ppp</code> and <code>owin</code> objects from simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#estimating-spatial-intensity-as-a-function-of-distance"><i class="fa fa-check"></i>Estimating spatial intensity as a function of distance</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#covariate-trend-as-a-possible-confounding-factor"><i class="fa fa-check"></i>Covariate trend as a possible confounding factor</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html"><i class="fa fa-check"></i>Thursday October 27, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#estimating-the-relative-risk"><i class="fa fa-check"></i>Estimating the relative risk</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#estimating-second-moment-properties-of-events"><i class="fa fa-check"></i>Estimating second-moment properties of events</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#examples-of-clustered-events"><i class="fa fa-check"></i>Examples of clustered events</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html"><i class="fa fa-check"></i>Tuesday November 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#removing-duplicate-events-and-defining-the-domain"><i class="fa fa-check"></i>Removing duplicate events and defining the domain</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#determining-statistical-significance-of-clustering"><i class="fa fa-check"></i>Determining statistical significance of clustering</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#estimating-clustering-in-multi-type-event-locations"><i class="fa fa-check"></i>Estimating clustering in multi-type event locations</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#interpolating-output-from-a-distance-function"><i class="fa fa-check"></i>Interpolating output from a distance function</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#limitations-of-the-distance-functions"><i class="fa fa-check"></i>Limitations of the distance functions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html"><i class="fa fa-check"></i>Tuesday November 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#limitations-on-interpreting-distance-functions"><i class="fa fa-check"></i>Limitations on interpreting distance functions</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#models-for-point-pattern-data"><i class="fa fa-check"></i>Models for point pattern data</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#fitting-and-interpreting-inhibition-models"><i class="fa fa-check"></i>Fitting and interpreting inhibition models</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#fitting-and-interpreting-cluster-models"><i class="fa fa-check"></i>Fitting and interpreting cluster models</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#assessing-how-well-the-model-fits"><i class="fa fa-check"></i>Assessing how well the model fits</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html"><i class="fa fa-check"></i>Tuesday November 15, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#fitting-a-log-gaussian-cox-model"><i class="fa fa-check"></i>Fitting a log-Gaussian Cox model</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#assessing-how-well-a-point-pattern-model-fits-the-data"><i class="fa fa-check"></i>Assessing how well a point pattern model fits the data</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#an-example-of-a-point-process-model-in-the-wild"><i class="fa fa-check"></i>An example of a point process model in the wild</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html"><i class="fa fa-check"></i>Thursday November 17, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#spatial-logistic-regression"><i class="fa fa-check"></i>Spatial logistic regression</a></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#spatial-data-interpolation"><i class="fa fa-check"></i>Spatial data interpolation</a></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#computing-the-sample-variogram"><i class="fa fa-check"></i>Computing the sample variogram</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-22-2022.html"><a href="tuesday-november-22-2022.html"><i class="fa fa-check"></i>Tuesday November 22, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-22-2022.html"><a href="tuesday-november-22-2022.html#fitting-a-variogram-model-to-the-sample-variogram"><i class="fa fa-check"></i>Fitting a variogram model to the sample variogram</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-22-2022.html"><a href="tuesday-november-22-2022.html#creating-an-interpolated-surface-with-the-method-of-kriging"><i class="fa fa-check"></i>Creating an interpolated surface with the method of kriging</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-29-2022.html"><a href="tuesday-november-29-2022.html"><i class="fa fa-check"></i>Tuesday November 29, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-29-2022.html"><a href="tuesday-november-29-2022.html#comparing-interpolation-methods"><i class="fa fa-check"></i>Comparing interpolation methods</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-29-2022.html"><a href="tuesday-november-29-2022.html#evaluating-the-accuracy-of-the-interpolation"><i class="fa fa-check"></i>Evaluating the accuracy of the interpolation</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-29-2022.html"><a href="tuesday-november-29-2022.html#block-cross-validation"><i class="fa fa-check"></i>Block cross validation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-december-1-2022.html"><a href="thursday-december-1-2022.html"><i class="fa fa-check"></i>Thursday December 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-december-1-2022.html"><a href="thursday-december-1-2022.html#interpolating-to-areal-units-block-kriging"><i class="fa fa-check"></i>Interpolating to areal units (block kriging)</a></li>
<li class="chapter" data-level="" data-path="thursday-december-1-2022.html"><a href="thursday-december-1-2022.html#simulating-spatial-fields"><i class="fa fa-check"></i>Simulating spatial fields</a></li>
<li class="chapter" data-level="" data-path="thursday-december-1-2022.html"><a href="thursday-december-1-2022.html#interpolating-multiple-variables"><i class="fa fa-check"></i>Interpolating multiple variables</a></li>
<li class="chapter" data-level="" data-path="thursday-december-1-2022.html"><a href="thursday-december-1-2022.html#machine-learning-for-spatial-interpolation"><i class="fa fa-check"></i>Machine learning for spatial interpolation</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GIS5122: Applied Spatial Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="tuesday-november-29-2022" class="section level1 unnumbered hasAnchor">
<h1>Tuesday November 29, 2022<a href="tuesday-november-29-2022.html#tuesday-november-29-2022" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>“The problem of nonparametric estimation consists in estimation, from the observations, of an unknown function belonging to a sufficiently large class of functions.”</strong> - A.B. Tsybakov</p>
<div id="comparing-interpolation-methods" class="section level2 unnumbered hasAnchor">
<h2>Comparing interpolation methods<a href="tuesday-november-29-2022.html#comparing-interpolation-methods" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s start by reviewing the steps involved with statistical spatial interpolation.</p>
<p>Here you consider a data set of monthly average near-surface air temperatures during April across the Midwest. The data set is available on my website in the file <code>MidwestTemps.txt</code>.</p>
<p>Start by importing the data as a data frame.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="tuesday-november-29-2022.html#cb1-1" aria-hidden="true" tabindex="-1"></a>L <span class="ot">&lt;-</span> <span class="st">&quot;http://myweb.fsu.edu/jelsner/temp/data/MidwestTemps.txt&quot;</span></span>
<span id="cb1-2"><a href="tuesday-november-29-2022.html#cb1-2" aria-hidden="true" tabindex="-1"></a>t.df <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_table</span>(L)</span></code></pre></div>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   lon = col_double(),
##   lat = col_double(),
##   temp = col_double()
## )</code></pre>
<p>The data frame contains three columns. The first two are longitude (<code>lon</code>) and latitude (<code>lat</code>) and the third is average air temperatures (<code>temp</code>) in tens of °F. These are the climate observations at specified locations and you want a continuous field of climate values across the domain.</p>
<p>Convert the data frame to a simple feature data frame by specifying which columns you want as coordinates (first X then Y).</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="tuesday-november-29-2022.html#cb3-1" aria-hidden="true" tabindex="-1"></a>t.sf <span class="ot">&lt;-</span> t.df <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="tuesday-november-29-2022.html#cb3-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">&quot;lon&quot;</span>, <span class="st">&quot;lat&quot;</span>),</span>
<span id="cb3-3"><a href="tuesday-november-29-2022.html#cb3-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">crs =</span> <span class="dv">4326</span>)</span></code></pre></div>
<p>Next include the spatial coordinates as attributes (<code>X</code> and <code>Y</code>) in the simple feature data frame. They were removed as attributes by the <code>sf::st_as_sf()</code> function.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="tuesday-november-29-2022.html#cb4-1" aria-hidden="true" tabindex="-1"></a>t.sf<span class="sc">$</span>X <span class="ot">&lt;-</span> t.df<span class="sc">$</span>lon</span>
<span id="cb4-2"><a href="tuesday-november-29-2022.html#cb4-2" aria-hidden="true" tabindex="-1"></a>t.sf<span class="sc">$</span>Y <span class="ot">&lt;-</span> t.df<span class="sc">$</span>lat</span></code></pre></div>
<p>Check to see if there are duplicated coordinates.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="tuesday-november-29-2022.html#cb5-1" aria-hidden="true" tabindex="-1"></a>t.sf<span class="sc">$</span>geometry <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="tuesday-november-29-2022.html#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">duplicated</span>() <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href="tuesday-november-29-2022.html#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">any</span>()</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p>Plot the climatological temperatures at the observation locations on a map.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="tuesday-november-29-2022.html#cb7-1" aria-hidden="true" tabindex="-1"></a>sts <span class="ot">&lt;-</span> USAboundaries<span class="sc">::</span><span class="fu">us_states</span>()</span>
<span id="cb7-2"><a href="tuesday-november-29-2022.html#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="tuesday-november-29-2022.html#cb7-3" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_shape</span>(t.sf) <span class="sc">+</span></span>
<span id="cb7-4"><a href="tuesday-november-29-2022.html#cb7-4" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_text</span>(<span class="at">text =</span> <span class="st">&quot;temp&quot;</span>, </span>
<span id="cb7-5"><a href="tuesday-november-29-2022.html#cb7-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">size =</span> .<span class="dv">6</span>) <span class="sc">+</span></span>
<span id="cb7-6"><a href="tuesday-november-29-2022.html#cb7-6" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_shape</span>(sts) <span class="sc">+</span></span>
<span id="cb7-7"><a href="tuesday-november-29-2022.html#cb7-7" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_borders</span>() </span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>There is a clear trend in temperatures with the coolest air to the north. Besides this north-south trend, there appears to be some clustering (spatial autocorrelation) of the temperatures due to local variations.</p>
<p>Next, compute and plot the sample variogram (omni-directional) using the residuals after removing the trend. The trend term is specified in the formula as <code>temp ~ X + Y</code>.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="tuesday-november-29-2022.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gstat)</span>
<span id="cb8-2"><a href="tuesday-november-29-2022.html#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="tuesday-november-29-2022.html#cb8-3" aria-hidden="true" tabindex="-1"></a>t.v <span class="ot">&lt;-</span> <span class="fu">variogram</span>(temp <span class="sc">~</span> X <span class="sc">+</span> Y, </span>
<span id="cb8-4"><a href="tuesday-november-29-2022.html#cb8-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> t.sf)</span>
<span id="cb8-5"><a href="tuesday-november-29-2022.html#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(t.v)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>The sample variogram values confirm spatial autocorrelation as there is an increase in the semi-variance for increasing lag distance out to about 150 km.</p>
<p>Next, check for anisotropy. Specify four directions and compute the corresponding directional sample variograms.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="tuesday-november-29-2022.html#cb9-1" aria-hidden="true" tabindex="-1"></a>t.vd <span class="ot">&lt;-</span> <span class="fu">variogram</span>(temp <span class="sc">~</span> X <span class="sc">+</span> Y, </span>
<span id="cb9-2"><a href="tuesday-november-29-2022.html#cb9-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> t.sf,</span>
<span id="cb9-3"><a href="tuesday-november-29-2022.html#cb9-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">alpha =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">45</span>, <span class="dv">90</span>, <span class="dv">135</span>))</span>
<span id="cb9-4"><a href="tuesday-november-29-2022.html#cb9-4" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> t.vd <span class="sc">|&gt;</span></span>
<span id="cb9-5"><a href="tuesday-november-29-2022.html#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb9-6"><a href="tuesday-november-29-2022.html#cb9-6" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">direction =</span> <span class="fu">factor</span>(dir.hor))</span>
<span id="cb9-7"><a href="tuesday-november-29-2022.html#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="tuesday-november-29-2022.html#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb9-9"><a href="tuesday-november-29-2022.html#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="tuesday-november-29-2022.html#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> df, </span>
<span id="cb9-11"><a href="tuesday-november-29-2022.html#cb9-11" aria-hidden="true" tabindex="-1"></a>              <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> dist, <span class="at">y =</span> gamma, <span class="at">color =</span> direction)) <span class="sc">+</span> </span>
<span id="cb9-12"><a href="tuesday-november-29-2022.html#cb9-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb9-13"><a href="tuesday-november-29-2022.html#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">alpha =</span> .<span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb9-14"><a href="tuesday-november-29-2022.html#cb9-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="cn">NA</span>)) <span class="sc">+</span></span>
<span id="cb9-15"><a href="tuesday-november-29-2022.html#cb9-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">&quot;Variogram [&quot;</span>, gamma,<span class="st">&quot;(h)]&quot;</span>))) <span class="sc">+</span></span>
<span id="cb9-16"><a href="tuesday-november-29-2022.html#cb9-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (h)&quot;</span>) <span class="sc">+</span></span>
<span id="cb9-17"><a href="tuesday-november-29-2022.html#cb9-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>The four sample variograms are all quite similar providing no strong evidence to reject the assumption of isotropy.</p>
<p>Next, fit a variogram model to the variogram sample. Plot the sample variogram again to eyeball initial estimates of the model parameters.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="tuesday-november-29-2022.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(t.v)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-8-1.png" width="672" />
Choose a nugget of .5, a partial sill of 2.5, and a range of 150.</p>
<p>Next set the initial parameters for an exponential model then fit the model. Plot the sample variogram and the variogram model.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="tuesday-november-29-2022.html#cb12-1" aria-hidden="true" tabindex="-1"></a>t.vmi <span class="ot">&lt;-</span> <span class="fu">vgm</span>(<span class="at">model =</span> <span class="st">&quot;Exp&quot;</span>, </span>
<span id="cb12-2"><a href="tuesday-november-29-2022.html#cb12-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">psill =</span> <span class="fl">2.5</span>, </span>
<span id="cb12-3"><a href="tuesday-november-29-2022.html#cb12-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">range =</span> <span class="dv">150</span>, </span>
<span id="cb12-4"><a href="tuesday-november-29-2022.html#cb12-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">nugget =</span> .<span class="dv">5</span>)</span>
<span id="cb12-5"><a href="tuesday-november-29-2022.html#cb12-5" aria-hidden="true" tabindex="-1"></a>t.vmi</span></code></pre></div>
<pre><code>##   model psill range
## 1   Nug   0.5     0
## 2   Exp   2.5   150</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="tuesday-november-29-2022.html#cb14-1" aria-hidden="true" tabindex="-1"></a>t.vm <span class="ot">&lt;-</span> <span class="fu">fit.variogram</span>(<span class="at">object =</span> t.v, </span>
<span id="cb14-2"><a href="tuesday-november-29-2022.html#cb14-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">model =</span> t.vmi)</span>
<span id="cb14-3"><a href="tuesday-november-29-2022.html#cb14-3" aria-hidden="true" tabindex="-1"></a>t.vm</span></code></pre></div>
<pre><code>##   model    psill    range
## 1   Nug 0.000000  0.00000
## 2   Exp 3.042847 73.81357</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="tuesday-november-29-2022.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(t.v, t.vm)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>Next, make a grid of locations at which values will be interpolated. Add the coordinates as attributes to the resulting <code>sfc</code>.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="tuesday-november-29-2022.html#cb17-1" aria-hidden="true" tabindex="-1"></a>grid.sfc <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_make_grid</span>(t.sf,</span>
<span id="cb17-2"><a href="tuesday-november-29-2022.html#cb17-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">n =</span> <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">100</span>),</span>
<span id="cb17-3"><a href="tuesday-november-29-2022.html#cb17-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">what =</span> <span class="st">&quot;centers&quot;</span>)</span>
<span id="cb17-4"><a href="tuesday-november-29-2022.html#cb17-4" aria-hidden="true" tabindex="-1"></a>XY <span class="ot">&lt;-</span> grid.sfc <span class="sc">|&gt;</span></span>
<span id="cb17-5"><a href="tuesday-november-29-2022.html#cb17-5" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_coordinates</span>()</span>
<span id="cb17-6"><a href="tuesday-november-29-2022.html#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="tuesday-november-29-2022.html#cb17-7" aria-hidden="true" tabindex="-1"></a>grid.sf <span class="ot">&lt;-</span> grid.sfc <span class="sc">|&gt;</span></span>
<span id="cb17-8"><a href="tuesday-november-29-2022.html#cb17-8" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_as_sf</span>() <span class="sc">|&gt;</span></span>
<span id="cb17-9"><a href="tuesday-november-29-2022.html#cb17-9" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">X =</span> XY[, <span class="dv">1</span>],</span>
<span id="cb17-10"><a href="tuesday-november-29-2022.html#cb17-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">Y =</span> XY[, <span class="dv">2</span>])</span></code></pre></div>
<p>Next, interpolate the observed temperatures to the grid locations using the method of universal kriging.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="tuesday-november-29-2022.html#cb18-1" aria-hidden="true" tabindex="-1"></a>t.int <span class="ot">&lt;-</span> <span class="fu">krige</span>(temp <span class="sc">~</span> X <span class="sc">+</span> Y,</span>
<span id="cb18-2"><a href="tuesday-november-29-2022.html#cb18-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">locations =</span> t.sf,</span>
<span id="cb18-3"><a href="tuesday-november-29-2022.html#cb18-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">newdata =</span> grid.sf,</span>
<span id="cb18-4"><a href="tuesday-november-29-2022.html#cb18-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">model =</span> t.vm)</span></code></pre></div>
<pre><code>## [using universal kriging]</code></pre>
<p>The interpolated values at the grid locations are returned in the simple feature data frame you assigned as <code>t.int</code>. Take a glimpse of the the contents of the file.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="tuesday-november-29-2022.html#cb20-1" aria-hidden="true" tabindex="-1"></a>t.int <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a href="tuesday-november-29-2022.html#cb20-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 10,000
## Columns: 3
## $ var1.pred &lt;dbl&gt; 56.69103, 56.62371, 56.64901, 56.81402, 57.02691, 57.22771, …
## $ var1.var  &lt;dbl&gt; 1.2599718, 0.9075707, 0.7767522, 0.9968012, 1.3129199, 1.587…
## $ geometry  &lt;POINT [°]&gt; POINT (-98.4204 38.62435), POINT (-98.3212 38.62435), …</code></pre>
<p>There are 10,000 rows (100 by 100 grid locations). The first column labeled <code>var1.pred</code> contains the interpolated temperatures. The second column contains the variance of the interpolated temperatures and the third column is the simple feature column.</p>
<p>The trend term captures the north-south temperature gradient and the variogram captures the local spatial autocorrelation. Together they make up the interpolated values.</p>
<p>To see this, you refit the interpolation first without the variogram model and second without the trend.</p>
<p>First, rename the columns.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="tuesday-november-29-2022.html#cb22-1" aria-hidden="true" tabindex="-1"></a>t.int <span class="ot">&lt;-</span> t.int <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="tuesday-november-29-2022.html#cb22-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">rename</span>(<span class="at">uk.pred =</span> var1.pred,</span>
<span id="cb22-3"><a href="tuesday-november-29-2022.html#cb22-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">uk.var =</span> var1.var)</span></code></pre></div>
<p>Next, use the <code>krige()</code> function but do not include the <code>model =</code> argument.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="tuesday-november-29-2022.html#cb23-1" aria-hidden="true" tabindex="-1"></a>t.trend <span class="ot">&lt;-</span> <span class="fu">krige</span>(temp <span class="sc">~</span> X <span class="sc">+</span> Y,</span>
<span id="cb23-2"><a href="tuesday-november-29-2022.html#cb23-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">locations =</span> t.sf,</span>
<span id="cb23-3"><a href="tuesday-november-29-2022.html#cb23-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">newdata =</span> grid.sf) </span></code></pre></div>
<pre><code>## [ordinary or weighted least squares prediction]</code></pre>
<p>Add the interpolated temperature trend (located in <code>t.trend$var1.pred</code>) to the <code>t.int</code> simple feature data frame.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="tuesday-november-29-2022.html#cb25-1" aria-hidden="true" tabindex="-1"></a>t.int <span class="ot">&lt;-</span> t.int <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="tuesday-november-29-2022.html#cb25-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">trend.pred =</span> t.trend<span class="sc">$</span>var1.pred)</span></code></pre></div>
<p>Next, again use the <code>krige()</code> function but do not include the trend term. That is interpolate using ordinary kriging.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="tuesday-november-29-2022.html#cb26-1" aria-hidden="true" tabindex="-1"></a>t.ok <span class="ot">&lt;-</span> <span class="fu">krige</span>(temp <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb26-2"><a href="tuesday-november-29-2022.html#cb26-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">locations =</span> t.sf,</span>
<span id="cb26-3"><a href="tuesday-november-29-2022.html#cb26-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">newdata =</span> grid.sf,</span>
<span id="cb26-4"><a href="tuesday-november-29-2022.html#cb26-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">model =</span> t.vm)</span></code></pre></div>
<pre><code>## [using ordinary kriging]</code></pre>
<p>Again add the interpolated temperatures from ordinary kriging to the <code>t.int</code> simple feature data frame.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="tuesday-november-29-2022.html#cb28-1" aria-hidden="true" tabindex="-1"></a>t.int <span class="ot">&lt;-</span> t.int <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a href="tuesday-november-29-2022.html#cb28-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">ok.pred =</span> t.ok<span class="sc">$</span>var1.pred)</span></code></pre></div>
<p>Now we have three interpolations of the temperatures in the <code>t.int</code> simple feature data frame all labeled with <code>.pred</code>.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="tuesday-november-29-2022.html#cb29-1" aria-hidden="true" tabindex="-1"></a>t.int <span class="sc">|&gt;</span></span>
<span id="cb29-2"><a href="tuesday-november-29-2022.html#cb29-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 10,000
## Columns: 5
## $ uk.pred    &lt;dbl&gt; 56.69103, 56.62371, 56.64901, 56.81402, 57.02691, 57.22771,…
## $ uk.var     &lt;dbl&gt; 1.2599718, 0.9075707, 0.7767522, 0.9968012, 1.3129199, 1.58…
## $ geometry   &lt;POINT [°]&gt; POINT (-98.4204 38.62435), POINT (-98.3212 38.62435),…
## $ trend.pred &lt;dbl&gt; 57.25042, 57.23585, 57.22128, 57.20672, 57.19215, 57.17758,…
## $ ok.pred    &lt;dbl&gt; 54.96613, 55.37918, 55.66495, 55.74478, 55.73389, 55.69921,…</code></pre>
<p>Map the interpolations</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="tuesday-november-29-2022.html#cb31-1" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_shape</span>(t.int) <span class="sc">+</span></span>
<span id="cb31-2"><a href="tuesday-november-29-2022.html#cb31-2" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_dots</span>(<span class="at">title =</span> <span class="st">&quot;°F&quot;</span>,</span>
<span id="cb31-3"><a href="tuesday-november-29-2022.html#cb31-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">shape =</span> <span class="dv">15</span>, </span>
<span id="cb31-4"><a href="tuesday-november-29-2022.html#cb31-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">size =</span> <span class="dv">2</span>,</span>
<span id="cb31-5"><a href="tuesday-november-29-2022.html#cb31-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">col =</span> <span class="fu">c</span>(<span class="st">&quot;uk.pred&quot;</span>, <span class="st">&quot;trend.pred&quot;</span>, <span class="st">&quot;ok.pred&quot;</span>), </span>
<span id="cb31-6"><a href="tuesday-november-29-2022.html#cb31-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">n =</span> <span class="dv">9</span>, </span>
<span id="cb31-7"><a href="tuesday-november-29-2022.html#cb31-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">palette =</span> <span class="st">&quot;OrRd&quot;</span>) <span class="sc">+</span></span>
<span id="cb31-8"><a href="tuesday-november-29-2022.html#cb31-8" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_shape</span>(sts) <span class="sc">+</span></span>
<span id="cb31-9"><a href="tuesday-november-29-2022.html#cb31-9" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_borders</span>() <span class="sc">+</span></span>
<span id="cb31-10"><a href="tuesday-november-29-2022.html#cb31-10" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_shape</span>(t.sf) <span class="sc">+</span></span>
<span id="cb31-11"><a href="tuesday-november-29-2022.html#cb31-11" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_text</span>(<span class="st">&quot;temp&quot;</span>, </span>
<span id="cb31-12"><a href="tuesday-november-29-2022.html#cb31-12" aria-hidden="true" tabindex="-1"></a>                <span class="at">col =</span> <span class="st">&quot;white&quot;</span>, </span>
<span id="cb31-13"><a href="tuesday-november-29-2022.html#cb31-13" aria-hidden="true" tabindex="-1"></a>                <span class="at">size =</span> .<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb31-14"><a href="tuesday-november-29-2022.html#cb31-14" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_layout</span>(<span class="at">legend.outside =</span> <span class="cn">TRUE</span>,</span>
<span id="cb31-15"><a href="tuesday-november-29-2022.html#cb31-15" aria-hidden="true" tabindex="-1"></a>                <span class="at">legend.outside.position =</span> <span class="st">&quot;bottom&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>The trend term (middle panel) captures the north-south temperature gradient and ordinary kriging (right panel) captures the local spatial autocorrelation. Together they make the universal kriging (left panel) interpolated surface.</p>
<p>The pattern obtained with ordinary kriging is similar to that obtained using inverse distance weighting.</p>
<p>Inverse distance weighting (IDW) is a deterministic method for interpolation. The values assigned to locations are calculated with a weighted average of the values available at the observed locations. The weights are proportional to the inverse of the distance to each location.</p>
<p>The function <code>krige()</code> performs IDW when there is no trend term and no variogram model given as arguments to the function.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="tuesday-november-29-2022.html#cb32-1" aria-hidden="true" tabindex="-1"></a>t.idw <span class="ot">&lt;-</span> <span class="fu">krige</span>(temp <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb32-2"><a href="tuesday-november-29-2022.html#cb32-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">locations =</span> t.sf,</span>
<span id="cb32-3"><a href="tuesday-november-29-2022.html#cb32-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">newdata =</span> grid.sf) </span></code></pre></div>
<pre><code>## [inverse distance weighted interpolation]</code></pre>
<p>The IDW interpolation is not statistical so there is no estimate of the uncertainty on the interpolated values. This shows up as <code>NA</code> values in the <code>var1.pred</code> column.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="tuesday-november-29-2022.html#cb34-1" aria-hidden="true" tabindex="-1"></a>t.idw <span class="sc">|&gt;</span></span>
<span id="cb34-2"><a href="tuesday-november-29-2022.html#cb34-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 10,000
## Columns: 3
## $ var1.pred &lt;dbl&gt; 55.68144, 55.98071, 56.06647, 55.89950, 55.59632, 55.30513, …
## $ var1.var  &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ geometry  &lt;POINT [°]&gt; POINT (-98.4204 38.62435), POINT (-98.3212 38.62435), …</code></pre>
<p>Put the IDW interpolated values into the <code>t.int</code> simple feature data frame and compare them to the universal kriging interpolated values on a map.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="tuesday-november-29-2022.html#cb36-1" aria-hidden="true" tabindex="-1"></a>t.int <span class="ot">&lt;-</span> t.int <span class="sc">|&gt;</span></span>
<span id="cb36-2"><a href="tuesday-november-29-2022.html#cb36-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">idw.pred =</span> t.idw<span class="sc">$</span>var1.pred)</span>
<span id="cb36-3"><a href="tuesday-november-29-2022.html#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="tuesday-november-29-2022.html#cb36-4" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_shape</span>(t.int) <span class="sc">+</span></span>
<span id="cb36-5"><a href="tuesday-november-29-2022.html#cb36-5" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_dots</span>(<span class="at">title =</span> <span class="st">&quot;°F&quot;</span>,</span>
<span id="cb36-6"><a href="tuesday-november-29-2022.html#cb36-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">shape =</span> <span class="dv">15</span>, </span>
<span id="cb36-7"><a href="tuesday-november-29-2022.html#cb36-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">size =</span> <span class="dv">2</span>,</span>
<span id="cb36-8"><a href="tuesday-november-29-2022.html#cb36-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">col =</span> <span class="fu">c</span>(<span class="st">&quot;uk.pred&quot;</span>, <span class="st">&quot;idw.pred&quot;</span>), </span>
<span id="cb36-9"><a href="tuesday-november-29-2022.html#cb36-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">n =</span> <span class="dv">9</span>, </span>
<span id="cb36-10"><a href="tuesday-november-29-2022.html#cb36-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">palette =</span> <span class="st">&quot;OrRd&quot;</span>) <span class="sc">+</span></span>
<span id="cb36-11"><a href="tuesday-november-29-2022.html#cb36-11" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_shape</span>(sts) <span class="sc">+</span></span>
<span id="cb36-12"><a href="tuesday-november-29-2022.html#cb36-12" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_borders</span>() <span class="sc">+</span></span>
<span id="cb36-13"><a href="tuesday-november-29-2022.html#cb36-13" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_layout</span>(<span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>IDW tends to create more ‘bulls-eye’ patterns in the interpolations compared with universal kriging. It also tends to over smooth at the larger scales.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="tuesday-november-29-2022.html#cb37-1" aria-hidden="true" tabindex="-1"></a>t.int <span class="ot">&lt;-</span> t.int <span class="sc">|&gt;</span></span>
<span id="cb37-2"><a href="tuesday-november-29-2022.html#cb37-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">diff.pred =</span> idw.pred <span class="sc">-</span> uk.pred)</span>
<span id="cb37-3"><a href="tuesday-november-29-2022.html#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="tuesday-november-29-2022.html#cb37-4" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_shape</span>(t.int) <span class="sc">+</span></span>
<span id="cb37-5"><a href="tuesday-november-29-2022.html#cb37-5" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_dots</span>(<span class="at">title =</span> <span class="st">&quot;°F&quot;</span>,</span>
<span id="cb37-6"><a href="tuesday-november-29-2022.html#cb37-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">shape =</span> <span class="dv">15</span>, </span>
<span id="cb37-7"><a href="tuesday-november-29-2022.html#cb37-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">size =</span> <span class="dv">2</span>,</span>
<span id="cb37-8"><a href="tuesday-november-29-2022.html#cb37-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">col =</span> <span class="st">&quot;diff.pred&quot;</span>, </span>
<span id="cb37-9"><a href="tuesday-november-29-2022.html#cb37-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">n =</span> <span class="dv">9</span>, </span>
<span id="cb37-10"><a href="tuesday-november-29-2022.html#cb37-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">palette =</span> <span class="st">&quot;BrBG&quot;</span>) <span class="sc">+</span></span>
<span id="cb37-11"><a href="tuesday-november-29-2022.html#cb37-11" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_shape</span>(sts) <span class="sc">+</span></span>
<span id="cb37-12"><a href="tuesday-november-29-2022.html#cb37-12" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_borders</span>()</span></code></pre></div>
<pre><code>## Variable(s) &quot;diff.pred&quot; contains positive and negative values, so midpoint is set to 0. Set midpoint = NA to show the full spectrum of the color palette.</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-23-1.png" width="672" />
Relative to universal kriging, IDW over estimates the temperatures in the coldest regions and under estimates the temperatures in the warmest regions. At the largest scales IDW is too smooth and at the smallest scales it is too coarse.</p>
<p>By taking into account to different models (trend at the largest scale and autocorrelation at the smallest scales) universal kriging produces a ‘goldilocks’ surface.</p>
<p>Finally, simple kriging is ordinary kriging with a known mean value. This is done by specifying a value for the <code>beta =</code> argument. Here you specify the average value over all observed temperatures.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="tuesday-november-29-2022.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">krige</span>(temp <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb39-2"><a href="tuesday-november-29-2022.html#cb39-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">beta =</span> <span class="fu">mean</span>(t.sf<span class="sc">$</span>temp),</span>
<span id="cb39-3"><a href="tuesday-november-29-2022.html#cb39-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">locations =</span> t.sf,</span>
<span id="cb39-4"><a href="tuesday-november-29-2022.html#cb39-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">newdata =</span> grid.sf,</span>
<span id="cb39-5"><a href="tuesday-november-29-2022.html#cb39-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">model =</span> t.vm)</span></code></pre></div>
<pre><code>## [using simple kriging]</code></pre>
<pre><code>## Simple feature collection with 10000 features and 2 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -98.4204 ymin: 38.62435 xmax: -88.5996 ymax: 45.42565
## Geodetic CRS:  WGS 84
## First 10 features:
##    var1.pred  var1.var                  geometry
## 1   55.03658 1.2219584 POINT (-98.4204 38.62435)
## 2   55.42840 0.8890350 POINT (-98.3212 38.62435)
## 3   55.70226 0.7662341  POINT (-98.222 38.62435)
## 4   55.78486 0.9850783 POINT (-98.1228 38.62435)
## 5   55.78267 1.2960863 POINT (-98.0236 38.62435)
## 6   55.75725 1.5646021 POINT (-97.9244 38.62435)
## 7   55.71768 1.7733525 POINT (-97.8252 38.62435)
## 8   55.66063 1.9329095  POINT (-97.726 38.62435)
## 9   55.58293 2.0570339 POINT (-97.6268 38.62435)
## 10  55.48552 2.1558398 POINT (-97.5276 38.62435)</code></pre>
</div>
<div id="evaluating-the-accuracy-of-the-interpolation" class="section level2 unnumbered hasAnchor">
<h2>Evaluating the accuracy of the interpolation<a href="tuesday-november-29-2022.html#evaluating-the-accuracy-of-the-interpolation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>How do you evaluate how good the interpolated surface is? If you use the variogram model to predict at the observation locations, you will get the observed values back when the nugget is zero.</p>
<p>For example, here you interpolate to the observation locations by setting <code>newdata = t.sf</code> instead of <code>grid.sf</code>. You then compute the correlation between the interpolated value and the observed value.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="tuesday-november-29-2022.html#cb42-1" aria-hidden="true" tabindex="-1"></a>t.int2 <span class="ot">&lt;-</span> <span class="fu">krige</span>(temp <span class="sc">~</span> X <span class="sc">+</span> Y,</span>
<span id="cb42-2"><a href="tuesday-november-29-2022.html#cb42-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">locations =</span> t.sf,</span>
<span id="cb42-3"><a href="tuesday-november-29-2022.html#cb42-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">newdata =</span> t.sf,</span>
<span id="cb42-4"><a href="tuesday-november-29-2022.html#cb42-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">model =</span> t.vm)</span></code></pre></div>
<pre><code>## [using universal kriging]</code></pre>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="tuesday-november-29-2022.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(t.int2<span class="sc">$</span>var1.pred, t.sf<span class="sc">$</span>temp)</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>This is not helpful.</p>
<p>Instead you use cross validation. Cross validation in this context is a procedure to assess how well the interpolation does at estimating the values at the observed locations when those values are not used in setting the interpolation procedure.</p>
<p>Cross validation partitions the data into disjoint subsets and the interpolation procedure is set using one subset of the data (training set) and interpolations are made using the procedure on the other subset (testing set).</p>
<p>Leave-one-out cross validation (LOOCV) uses all but one observation for setting the procedure and the left-out observation is used for interpolation. This process is repeated with every observation taking turns being left out.</p>
<p>The <code>krige.cv()</code> function from the {gstat} package is used for cross validating the kriging procedure. Interpolations are made at the observation locations.</p>
<p>The arguments are the same as in <code>krige()</code> except the <code>nfold =</code> argument. Values for the argument range between 2 and the number of observations (here 131). The default is 131 which is LOOCV.</p>
<p>For example with <code>nfold = 3</code> cross validation cuts the set of observations into 3rds (3 folds). Each observation gets put into one of the three folds with the interpolation procedure set using observations from the two folds and interpolations made on the remaining observation. This is repeated three times with each third taking turns being left out.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="tuesday-november-29-2022.html#cb46-1" aria-hidden="true" tabindex="-1"></a>xv3 <span class="ot">&lt;-</span> <span class="fu">krige.cv</span>(temp <span class="sc">~</span> X <span class="sc">+</span> Y,</span>
<span id="cb46-2"><a href="tuesday-november-29-2022.html#cb46-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">locations =</span> t.sf,</span>
<span id="cb46-3"><a href="tuesday-november-29-2022.html#cb46-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">model =</span> t.vm,</span>
<span id="cb46-4"><a href="tuesday-november-29-2022.html#cb46-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">nfold =</span> <span class="dv">3</span>)</span>
<span id="cb46-5"><a href="tuesday-november-29-2022.html#cb46-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-6"><a href="tuesday-november-29-2022.html#cb46-6" aria-hidden="true" tabindex="-1"></a>xv3 <span class="sc">|&gt;</span></span>
<span id="cb46-7"><a href="tuesday-november-29-2022.html#cb46-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>## Simple feature collection with 6 features and 6 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -90.74 ymin: 39.29 xmax: -89.02 ymax: 41.84
## Geodetic CRS:  WGS 84
##   var1.pred var1.var observed   residual      zscore fold             geometry
## 1  51.61631 1.611274     51.6 -0.0163150 -0.01285293    3 POINT (-90.74 41.24)
## 2  54.83830 1.908870     55.9  1.0616962  0.76844375    2 POINT (-89.87 39.29)
## 3  53.45415 2.039303     54.7  1.2458501  0.87241859    2 POINT (-89.02 39.84)
## 4  50.73864 2.293980     51.1  0.3613630  0.23858817    1 POINT (-89.52 41.84)
## 5  51.59009 1.836865     52.2  0.6099053  0.45001172    2 POINT (-90.05 41.17)
## 6  54.17323 1.780450     55.2  1.0267654  0.76949584    2 POINT (-90.74 39.72)</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="tuesday-november-29-2022.html#cb48-1" aria-hidden="true" tabindex="-1"></a>xv3 <span class="sc">|&gt;</span></span>
<span id="cb48-2"><a href="tuesday-november-29-2022.html#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tail</span>()</span></code></pre></div>
<pre><code>## Simple feature collection with 6 features and 6 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -91.16 ymin: 43.04 xmax: -88.55 ymax: 44.97
## Geodetic CRS:  WGS 84
##     var1.pred var1.var observed   residual     zscore fold             geometry
## 126  47.14633 1.894213     46.1 -1.0463308 -0.7602468    2 POINT (-88.55 44.04)
## 127  47.44554 2.315590     49.0  1.5544563  1.0215219    1 POINT (-89.44 43.52)
## 128  47.78241 1.966596     49.4  1.6175947  1.1534853    2 POINT (-91.16 43.04)
## 129  42.88314 2.193358     43.6  0.7168588  0.4840374    3 POINT (-90.94 44.97)
## 130  47.91986 2.265369     46.0 -1.9198561 -1.2755551    1 POINT (-90.92 43.57)
## 131  47.75269 2.591623     48.3  0.5473124  0.3399768    1 POINT (-88.74 43.19)</code></pre>
<p>The output is the same as before but now the data frame has a column indicating the fold (the set of observations that were left out).</p>
<p>Using cross validation you are able to compare the interpolated value against the observed value at the observation locations. Here you use three statistics for comparisons. The correlation (r), the root-mean-squared error (rmse), and the mean absolute error (mae). These statistics are estimates of how skillful universal kriging is in producing the interpolated surface.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="tuesday-november-29-2022.html#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">krige.cv</span>(temp <span class="sc">~</span> X <span class="sc">+</span> Y,</span>
<span id="cb50-2"><a href="tuesday-november-29-2022.html#cb50-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">locations =</span> t.sf,</span>
<span id="cb50-3"><a href="tuesday-november-29-2022.html#cb50-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">model =</span> t.vm,</span>
<span id="cb50-4"><a href="tuesday-november-29-2022.html#cb50-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">nfold =</span> <span class="dv">131</span>) <span class="sc">|&gt;</span></span>
<span id="cb50-5"><a href="tuesday-november-29-2022.html#cb50-5" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span></span>
<span id="cb50-6"><a href="tuesday-november-29-2022.html#cb50-6" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">r =</span> <span class="fu">cor</span>(var1.pred, observed),</span>
<span id="cb50-7"><a href="tuesday-november-29-2022.html#cb50-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">rmse =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((var1.pred <span class="sc">-</span> observed)<span class="sc">^</span><span class="dv">2</span>)),</span>
<span id="cb50-8"><a href="tuesday-november-29-2022.html#cb50-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">mae =</span> <span class="fu">mean</span>(<span class="fu">abs</span>(var1.pred <span class="sc">-</span> observed)))</span></code></pre></div>
<pre><code>##           r     rmse      mae
## 1 0.9438537 1.324621 1.037809</code></pre>
<p>The correlation is .944, the rmse is 1.32°F and the mae is 1.04°F.</p>
<p>How do these skill metrics compare to interpolations from ordinary kriging.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="tuesday-november-29-2022.html#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">krige.cv</span>(temp <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb52-2"><a href="tuesday-november-29-2022.html#cb52-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">locations =</span> t.sf,</span>
<span id="cb52-3"><a href="tuesday-november-29-2022.html#cb52-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">model =</span> t.vm) <span class="sc">|&gt;</span></span>
<span id="cb52-4"><a href="tuesday-november-29-2022.html#cb52-4" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span></span>
<span id="cb52-5"><a href="tuesday-november-29-2022.html#cb52-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">r =</span> <span class="fu">cor</span>(var1.pred, observed),</span>
<span id="cb52-6"><a href="tuesday-november-29-2022.html#cb52-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">rmse =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((var1.pred <span class="sc">-</span> observed)<span class="sc">^</span><span class="dv">2</span>)),</span>
<span id="cb52-7"><a href="tuesday-november-29-2022.html#cb52-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">mae =</span> <span class="fu">mean</span>(<span class="fu">abs</span>(var1.pred <span class="sc">-</span> observed)))</span></code></pre></div>
<pre><code>##           r     rmse      mae
## 1 0.9248236 1.597617 1.195622</code></pre>
<p>With ordinary kriging the skill values are worse. The correlation is lower and the rmse and mae are larger.</p>
<p>How do these skill metrics compare to interpolations from a trend-only interpolation.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="tuesday-november-29-2022.html#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">krige.cv</span>(temp <span class="sc">~</span> X <span class="sc">+</span> Y,</span>
<span id="cb54-2"><a href="tuesday-november-29-2022.html#cb54-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">locations =</span> t.sf) <span class="sc">|&gt;</span></span>
<span id="cb54-3"><a href="tuesday-november-29-2022.html#cb54-3" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span></span>
<span id="cb54-4"><a href="tuesday-november-29-2022.html#cb54-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">r =</span> <span class="fu">cor</span>(var1.pred, observed),</span>
<span id="cb54-5"><a href="tuesday-november-29-2022.html#cb54-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">rmse =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((var1.pred <span class="sc">-</span> observed)<span class="sc">^</span><span class="dv">2</span>)),</span>
<span id="cb54-6"><a href="tuesday-november-29-2022.html#cb54-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">mae =</span> <span class="fu">mean</span>(<span class="fu">abs</span>(var1.pred <span class="sc">-</span> observed)))</span></code></pre></div>
<pre><code>##           r     rmse      mae
## 1 0.9057414 1.698922 1.351733</code></pre>
<p>Even worse. The correlation is lower and the rmse and mae are higher.</p>
<p>What about inverse-distance weighting interpolation?</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="tuesday-november-29-2022.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">krige.cv</span>(temp <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb56-2"><a href="tuesday-november-29-2022.html#cb56-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">locations =</span> t.sf) <span class="sc">|&gt;</span></span>
<span id="cb56-3"><a href="tuesday-november-29-2022.html#cb56-3" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span></span>
<span id="cb56-4"><a href="tuesday-november-29-2022.html#cb56-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">r =</span> <span class="fu">cor</span>(var1.pred, observed),</span>
<span id="cb56-5"><a href="tuesday-november-29-2022.html#cb56-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">rmse =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((var1.pred <span class="sc">-</span> observed)<span class="sc">^</span><span class="dv">2</span>)),</span>
<span id="cb56-6"><a href="tuesday-november-29-2022.html#cb56-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">mae =</span> <span class="fu">mean</span>(<span class="fu">abs</span>(var1.pred <span class="sc">-</span> observed)))</span></code></pre></div>
<pre><code>##           r     rmse      mae
## 1 0.9294513 1.785536 1.346272</code></pre>
<p>Better than the trend-only interpolation but not as good as universal kriging.</p>
<p>All four interpolations result in high correlation between observed and interpolated values that exceed .9 and root-mean-squared errors (RMSE) less than 1.8. But the universal kriging interpolation gives the highest correlation and the lowest RMSE and mean-absolute errors.</p>
<p>For a visual representation of the goodness of fit you plot the observed versus interpolated values from the cross validation procedure.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="tuesday-november-29-2022.html#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">krige.cv</span>(temp <span class="sc">~</span> X <span class="sc">+</span> Y,</span>
<span id="cb58-2"><a href="tuesday-november-29-2022.html#cb58-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">locations =</span> t.sf,</span>
<span id="cb58-3"><a href="tuesday-november-29-2022.html#cb58-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">model =</span> t.vm) <span class="sc">|&gt;</span></span>
<span id="cb58-4"><a href="tuesday-november-29-2022.html#cb58-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">rename</span>(<span class="at">interpolated =</span> var1.pred) <span class="sc">|&gt;</span></span>
<span id="cb58-5"><a href="tuesday-november-29-2022.html#cb58-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> observed, <span class="at">y =</span> interpolated)) <span class="sc">+</span> </span>
<span id="cb58-6"><a href="tuesday-november-29-2022.html#cb58-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb58-7"><a href="tuesday-november-29-2022.html#cb58-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb58-8"><a href="tuesday-november-29-2022.html#cb58-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb58-9"><a href="tuesday-november-29-2022.html#cb58-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Interpolated temperatures (°F)&quot;</span>) <span class="sc">+</span></span>
<span id="cb58-10"><a href="tuesday-november-29-2022.html#cb58-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Observed temperatures (°F)&quot;</span>) <span class="sc">+</span></span>
<span id="cb58-11"><a href="tuesday-november-29-2022.html#cb58-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<p>The black line represents a perfect prediction and the red line is the best fit line when you regress the interpolated temperatures onto the observed temperatures. The fact that the two lines nearly coincide indicates the interpolation is good.</p>
<p>The <code>nfold =</code> argument, which by default is set to the number of observations and does a LOOCV, allows you to divide the data into different size folds (instead of N-1).</p>
<p>These skill metrics are based on a fixed variogram model that uses all the observations when fitting. Thus cross validation using the <code>krige.cv()</code> function is a <em>partial</em> cross validation.</p>
<p>With kriging the data is used in two ways (1) to fit the variogram model, and (2) to interpolate the values. To perform a <em>full</em> LOOCV you need to <em>refit</em> the variogram after removing the observation for which you want the interpolation.</p>
<p>Here is one way to do that using a <code>for()</code> loop.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="tuesday-november-29-2022.html#cb60-1" aria-hidden="true" tabindex="-1"></a>vmi <span class="ot">&lt;-</span> <span class="fu">vgm</span>(<span class="at">model =</span> <span class="st">&quot;Exp&quot;</span>, </span>
<span id="cb60-2"><a href="tuesday-november-29-2022.html#cb60-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">psill =</span> <span class="fl">2.5</span>, </span>
<span id="cb60-3"><a href="tuesday-november-29-2022.html#cb60-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">range =</span> <span class="dv">150</span>, </span>
<span id="cb60-4"><a href="tuesday-november-29-2022.html#cb60-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">nugget =</span> .<span class="dv">5</span>)</span>
<span id="cb60-5"><a href="tuesday-november-29-2022.html#cb60-5" aria-hidden="true" tabindex="-1"></a>int <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb60-6"><a href="tuesday-november-29-2022.html#cb60-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(t.sf)){</span>
<span id="cb60-7"><a href="tuesday-november-29-2022.html#cb60-7" aria-hidden="true" tabindex="-1"></a>  t <span class="ot">&lt;-</span> t.sf[<span class="sc">-</span>i, ]</span>
<span id="cb60-8"><a href="tuesday-november-29-2022.html#cb60-8" aria-hidden="true" tabindex="-1"></a>  v <span class="ot">&lt;-</span> <span class="fu">variogram</span>(temp <span class="sc">~</span> X <span class="sc">+</span> Y, </span>
<span id="cb60-9"><a href="tuesday-november-29-2022.html#cb60-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> t)</span>
<span id="cb60-10"><a href="tuesday-november-29-2022.html#cb60-10" aria-hidden="true" tabindex="-1"></a>  vm <span class="ot">&lt;-</span> <span class="fu">fit.variogram</span>(<span class="at">object =</span> v, </span>
<span id="cb60-11"><a href="tuesday-november-29-2022.html#cb60-11" aria-hidden="true" tabindex="-1"></a>                      <span class="at">model =</span> vmi)</span>
<span id="cb60-12"><a href="tuesday-november-29-2022.html#cb60-12" aria-hidden="true" tabindex="-1"></a>  int[i] <span class="ot">&lt;-</span> <span class="fu">krige</span>(temp <span class="sc">~</span> X <span class="sc">+</span> Y,</span>
<span id="cb60-13"><a href="tuesday-november-29-2022.html#cb60-13" aria-hidden="true" tabindex="-1"></a>                  <span class="at">locations =</span> t,</span>
<span id="cb60-14"><a href="tuesday-november-29-2022.html#cb60-14" aria-hidden="true" tabindex="-1"></a>                  <span class="at">newdata =</span> t.sf[i, ],</span>
<span id="cb60-15"><a href="tuesday-november-29-2022.html#cb60-15" aria-hidden="true" tabindex="-1"></a>                  <span class="at">model =</span> vm)<span class="sc">$</span>var1.pred</span>
<span id="cb60-16"><a href="tuesday-november-29-2022.html#cb60-16" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]</code></pre>
<p>Now compare the observed values with the interpolated values.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="tuesday-november-29-2022.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">interpolated =</span> int,</span>
<span id="cb62-2"><a href="tuesday-november-29-2022.html#cb62-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">observed =</span> t.sf<span class="sc">$</span>temp) <span class="sc">|&gt;</span></span>
<span id="cb62-3"><a href="tuesday-november-29-2022.html#cb62-3" aria-hidden="true" tabindex="-1"></a>   dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">r =</span> <span class="fu">cor</span>(interpolated, observed),</span>
<span id="cb62-4"><a href="tuesday-november-29-2022.html#cb62-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">rmse =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((interpolated <span class="sc">-</span> observed)<span class="sc">^</span><span class="dv">2</span>)),</span>
<span id="cb62-5"><a href="tuesday-november-29-2022.html#cb62-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">mae =</span> <span class="fu">mean</span>(<span class="fu">abs</span>(interpolated <span class="sc">-</span> observed)))</span></code></pre></div>
<pre><code>##           r     rmse      mae
## 1 0.9433904 1.329906 1.041374</code></pre>
<p>These values are slightly worse (r is lower, and rmse and mae are larger). This will always be the case when using full cross validation but these skill estimates represent how well the procedure will perform on a new set of <em>independent</em> observations.</p>
</div>
<div id="block-cross-validation" class="section level2 unnumbered hasAnchor">
<h2>Block cross validation<a href="tuesday-november-29-2022.html#block-cross-validation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Unfortunately, with cross validation in the context of spatial data, the observations are not independent. As such it is better to create spatial areas for training separate from the spatial areas for testing.</p>
<p>The function <code>blockCV::spatialBlock()</code> function creates spatially separated folds based on a pre-specified distance (cell size of the blocks) from raster and vector spatial data objects. It assigns blocks to the training and testing folds with random, checkerboard, or systematic patterns (default is random). The range must be specified in units of meters. The argument <code>k =</code> specifies the number of folds with a default value of 5.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="tuesday-november-29-2022.html#cb64-1" aria-hidden="true" tabindex="-1"></a>sb <span class="ot">&lt;-</span> t.sf <span class="sc">|&gt;</span></span>
<span id="cb64-2"><a href="tuesday-november-29-2022.html#cb64-2" aria-hidden="true" tabindex="-1"></a>  blockCV<span class="sc">::</span><span class="fu">spatialBlock</span>(<span class="at">theRange =</span> <span class="dv">200000</span>)</span></code></pre></div>
<pre><code>## The best folds was in iteration 73:
##   train test
## 1   103   28
## 2   106   25
## 3   105   26
## 4   104   27
## 5   106   25</code></pre>
<pre><code>## Warning in st_point_on_surface.sfc(sf::st_zm(x)): st_point_on_surface may not
## give correct results for longitude/latitude data</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<p>The output shows how many observations are in the training and testing sets for each fold.</p>
<p>The <code>$plot</code> list is a <code>ggplot2</code> object. Render the plot then add the observation locations to see the block assignments.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="tuesday-november-29-2022.html#cb67-1" aria-hidden="true" tabindex="-1"></a>sb<span class="sc">$</span>plots <span class="sc">+</span> </span>
<span id="cb67-2"><a href="tuesday-november-29-2022.html#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> t.sf, </span>
<span id="cb67-3"><a href="tuesday-november-29-2022.html#cb67-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">alpha =</span> .<span class="dv">5</span>)</span></code></pre></div>
<pre><code>## Warning in st_point_on_surface.sfc(sf::st_zm(x)): st_point_on_surface may not
## give correct results for longitude/latitude data</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<p>Now you need to repeat the full cross validation <code>for()</code> loop with some minor changes. First you need to add the fold and observation identification for each observation. Then rearrange the observations by these two indices.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="tuesday-november-29-2022.html#cb69-1" aria-hidden="true" tabindex="-1"></a>t.sf2 <span class="ot">&lt;-</span> t.sf <span class="sc">|&gt;</span></span>
<span id="cb69-2"><a href="tuesday-november-29-2022.html#cb69-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">foldID =</span> sb<span class="sc">$</span>foldID,</span>
<span id="cb69-3"><a href="tuesday-november-29-2022.html#cb69-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">obsID =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(t.sf)) <span class="sc">|&gt;</span></span>
<span id="cb69-4"><a href="tuesday-november-29-2022.html#cb69-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">arrange</span>(foldID, obsID)</span>
<span id="cb69-5"><a href="tuesday-november-29-2022.html#cb69-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-6"><a href="tuesday-november-29-2022.html#cb69-6" aria-hidden="true" tabindex="-1"></a>t.sf2 <span class="sc">|&gt;</span></span>
<span id="cb69-7"><a href="tuesday-november-29-2022.html#cb69-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>## Simple feature collection with 6 features and 5 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -92.79 ymin: 40.59 xmax: -89.97 ymax: 41.82
## Geodetic CRS:  WGS 84
## # A tibble: 6 × 6
##    temp       geometry     X     Y foldID obsID
##   &lt;dbl&gt;    &lt;POINT [°]&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;int&gt; &lt;int&gt;
## 1  51.6 (-90.74 41.24) -90.7  41.2      1     1
## 2  52.2 (-90.05 41.17) -90.0  41.2      1     5
## 3  53.1 (-90.97 40.59) -91.0  40.6      1     9
## 4  51.7 (-90.64 40.92) -90.6  40.9      1    13
## 5  51.9 (-89.97 41.82) -90.0  41.8      1    14
## 6  51.5 (-92.79 41.07) -92.8  41.1      1    23</code></pre>
<p>Now repeat the loop on the new <code>t.sf2</code> spatial data frame. This time subset on <code>foldID</code>. Keep all folds not equal to <code>i</code> for training and then use the ith fold for interpolation.</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="tuesday-november-29-2022.html#cb71-1" aria-hidden="true" tabindex="-1"></a>vmi <span class="ot">&lt;-</span> <span class="fu">vgm</span>(<span class="at">model =</span> <span class="st">&quot;Exp&quot;</span>, </span>
<span id="cb71-2"><a href="tuesday-november-29-2022.html#cb71-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">psill =</span> <span class="fl">2.5</span>, </span>
<span id="cb71-3"><a href="tuesday-november-29-2022.html#cb71-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">range =</span> <span class="dv">150</span>, </span>
<span id="cb71-4"><a href="tuesday-november-29-2022.html#cb71-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">nugget =</span> .<span class="dv">5</span>)</span>
<span id="cb71-5"><a href="tuesday-november-29-2022.html#cb71-5" aria-hidden="true" tabindex="-1"></a>int <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb71-6"><a href="tuesday-november-29-2022.html#cb71-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>){</span>
<span id="cb71-7"><a href="tuesday-november-29-2022.html#cb71-7" aria-hidden="true" tabindex="-1"></a>  t <span class="ot">&lt;-</span> t.sf2[t.sf2<span class="sc">$</span>foldID <span class="sc">!=</span> i, ]</span>
<span id="cb71-8"><a href="tuesday-november-29-2022.html#cb71-8" aria-hidden="true" tabindex="-1"></a>  v <span class="ot">&lt;-</span> <span class="fu">variogram</span>(temp <span class="sc">~</span> X <span class="sc">+</span> Y, </span>
<span id="cb71-9"><a href="tuesday-november-29-2022.html#cb71-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> t)</span>
<span id="cb71-10"><a href="tuesday-november-29-2022.html#cb71-10" aria-hidden="true" tabindex="-1"></a>  vm <span class="ot">&lt;-</span> <span class="fu">fit.variogram</span>(<span class="at">object =</span> v, </span>
<span id="cb71-11"><a href="tuesday-november-29-2022.html#cb71-11" aria-hidden="true" tabindex="-1"></a>                      <span class="at">model =</span> vmi)</span>
<span id="cb71-12"><a href="tuesday-november-29-2022.html#cb71-12" aria-hidden="true" tabindex="-1"></a>  int_i <span class="ot">&lt;-</span> <span class="fu">krige</span>(temp <span class="sc">~</span> X <span class="sc">+</span> Y,</span>
<span id="cb71-13"><a href="tuesday-november-29-2022.html#cb71-13" aria-hidden="true" tabindex="-1"></a>                 <span class="at">locations =</span> t,</span>
<span id="cb71-14"><a href="tuesday-november-29-2022.html#cb71-14" aria-hidden="true" tabindex="-1"></a>                 <span class="at">newdata =</span> t.sf2[t.sf2<span class="sc">$</span>foldID <span class="sc">==</span> i, ],</span>
<span id="cb71-15"><a href="tuesday-november-29-2022.html#cb71-15" aria-hidden="true" tabindex="-1"></a>                 <span class="at">model =</span> vm)<span class="sc">$</span>var1.pred</span>
<span id="cb71-16"><a href="tuesday-november-29-2022.html#cb71-16" aria-hidden="true" tabindex="-1"></a>  int <span class="ot">&lt;-</span> <span class="fu">c</span>(int, int_i)</span>
<span id="cb71-17"><a href="tuesday-november-29-2022.html#cb71-17" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]
## [using universal kriging]</code></pre>
<p>Finally create a data frame and compute the skill metrics.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="tuesday-november-29-2022.html#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">interpolated =</span> int,</span>
<span id="cb73-2"><a href="tuesday-november-29-2022.html#cb73-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">observed =</span> t.sf2<span class="sc">$</span>temp) <span class="sc">|&gt;</span></span>
<span id="cb73-3"><a href="tuesday-november-29-2022.html#cb73-3" aria-hidden="true" tabindex="-1"></a>   dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">r =</span> <span class="fu">cor</span>(interpolated, observed),</span>
<span id="cb73-4"><a href="tuesday-november-29-2022.html#cb73-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">rmse =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((interpolated <span class="sc">-</span> observed)<span class="sc">^</span><span class="dv">2</span>)),</span>
<span id="cb73-5"><a href="tuesday-november-29-2022.html#cb73-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">mae =</span> <span class="fu">mean</span>(<span class="fu">abs</span>(interpolated <span class="sc">-</span> observed)))</span></code></pre></div>
<pre><code>##           r     rmse      mae
## 1 0.9074143 1.723653 1.380181</code></pre>
<p>The skill metrics are worse but more representative of how well the interpolation will work with a different but similarly spatial correlated temperature field.</p>
<p>An introduction to ‘block’ cross validation in the context of species distribution modeling is available here
<a href="https://cran.r-project.org/web/packages/blockCV/vignettes/BlockCV_for_SDM.html" class="uri">https://cran.r-project.org/web/packages/blockCV/vignettes/BlockCV_for_SDM.html</a></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tuesday-november-22-2022.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="thursday-december-1-2022.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
