<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tuesday November 8, 2022 | GIS5122: Applied Spatial Statistics</title>
  <meta name="description" content="Tuesday November 8, 2022 | GIS5122: Applied Spatial Statistics" />
  <meta name="generator" content="bookdown 0.29 and GitBook 2.6.7" />

  <meta property="og:title" content="Tuesday November 8, 2022 | GIS5122: Applied Spatial Statistics" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="jelsner/ASS-2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tuesday November 8, 2022 | GIS5122: Applied Spatial Statistics" />
  
  
  

<meta name="author" content="James B. Elsner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tuesday-november-1-2022.html"/>
<link rel="next" href="thursday-november-10-2022.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied Spatial Statistics</a></li>

<li class="divider"></li>
<li><a href="index.html#section" id="toc-section"></a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i>Syllabus</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#gis5122-applied-spatial-statistics"><i class="fa fa-check"></i>GIS5122: Applied Spatial Statistics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#contact-information"><i class="fa fa-check"></i>Contact information</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#course-description-and-expected-learning-outcomes"><i class="fa fa-check"></i>Course description and expected learning outcomes</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#grades-and-ethics"><i class="fa fa-check"></i>Grades and ethics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#outline-of-topics-and-schedule"><i class="fa fa-check"></i>Outline of topics and schedule</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#reference-materials"><i class="fa fa-check"></i>Reference materials</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#reproducible-research"><i class="fa fa-check"></i>Reproducible research</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html"><i class="fa fa-check"></i>Tuesday, August 23, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#install-r-and-rstudio-on-your-computer"><i class="fa fa-check"></i>Install R and RStudio on your computer</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#download-course-materials"><i class="fa fa-check"></i>Download course materials</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#read-the-syllabus"><i class="fa fa-check"></i>Read the syllabus</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#about-rstudio"><i class="fa fa-check"></i>About RStudio</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#lab-assignments"><i class="fa fa-check"></i>Lab assignments</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#getting-started-with-r"><i class="fa fa-check"></i>Getting started with R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#are-you-completely-new-to-r"><i class="fa fa-check"></i>Are you completely new to R?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html"><i class="fa fa-check"></i>Thursday, August 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-science-workflow-with-r-markdown"><i class="fa fa-check"></i>Data science workflow with R markdown</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#an-introduction-to-using-r"><i class="fa fa-check"></i>An introduction to using R</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-frames"><i class="fa fa-check"></i>Data frames</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html"><i class="fa fa-check"></i>Tuesday August 30, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#working-with-data-frames-using-base-r"><i class="fa fa-check"></i>Working with data frames using base R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#getting-data-into-r"><i class="fa fa-check"></i>Getting data into R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#working-with-data-frames-using-functions-from-dplyr"><i class="fa fa-check"></i>Working with data frames using functions from {dplyr}</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html"><i class="fa fa-check"></i>Thursday September 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#making-graphs"><i class="fa fa-check"></i>Making graphs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html"><i class="fa fa-check"></i>Thursday September 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#introduction-to-simple-features"><i class="fa fa-check"></i>Introduction to simple features</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#geo-computation-on-simple-features"><i class="fa fa-check"></i>Geo-computation on simple features</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html"><i class="fa fa-check"></i>Tuesday September 13, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#spatial-data-subsets-and-joins"><i class="fa fa-check"></i>Spatial data subsets and joins</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#interpolation-using-areal-weights"><i class="fa fa-check"></i>Interpolation using areal weights</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html"><i class="fa fa-check"></i>Thursday September 15, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#s4-spatial-data-objects"><i class="fa fa-check"></i>S4 spatial data objects</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#working-with-raster-data"><i class="fa fa-check"></i>Working with raster data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#working-with-space-time-data"><i class="fa fa-check"></i>Working with space-time data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html"><i class="fa fa-check"></i>Tuesday September 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#mapping-using-functions-from-the-ggplot2-package"><i class="fa fa-check"></i>Mapping using functions from the {ggplot2} package</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#mapping-using-functions-from-the-tmap-package"><i class="fa fa-check"></i>Mapping using functions from the {tmap} package</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#creating-an-interactive-map"><i class="fa fa-check"></i>Creating an interactive map</a></li>
<li class="chapter" data-level="0.1" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#hillshape-and-colors-with-tidyterra"><i class="fa fa-check"></i><b>0.1</b> Hillshape and colors with tidyterra</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#adding-an-inset-map"><i class="fa fa-check"></i>Adding an inset map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html"><i class="fa fa-check"></i>Tuesday October 4, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#defining-spatial-neighborhoods-and-spatial-weights"><i class="fa fa-check"></i>Defining spatial neighborhoods and spatial weights</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#computing-autocorrelation"><i class="fa fa-check"></i>Computing autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#spatial-lag-and-its-relation-to-autocorrelation"><i class="fa fa-check"></i>Spatial lag and its relation to autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#other-neighbor-definitions"><i class="fa fa-check"></i>Other neighbor definitions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html"><i class="fa fa-check"></i>Thursday October 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#assessing-the-statistical-significance-of-autocorrelation"><i class="fa fa-check"></i>Assessing the statistical significance of autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#bivariate-spatial-autocorrelation"><i class="fa fa-check"></i>Bivariate spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#local-indicators-of-spatial-autocorrelation"><i class="fa fa-check"></i>Local indicators of spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#constraining-group-membership-based-on-spatial-autocorrelation"><i class="fa fa-check"></i>Constraining group membership based on spatial autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html"><i class="fa fa-check"></i>Tuesday October 11, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#estimating-spatial-autocorrelation-in-model-residuals"><i class="fa fa-check"></i>Estimating spatial autocorrelation in model residuals</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#choosing-a-spatial-regression-model"><i class="fa fa-check"></i>Choosing a spatial regression model</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#fitting-and-interpreting-spatial-regression-models"><i class="fa fa-check"></i>Fitting and interpreting spatial regression models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html"><i class="fa fa-check"></i>Thursday October 13, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html#fitting-and-interpreting-geographic-regression"><i class="fa fa-check"></i>Fitting and interpreting geographic regression</a></li>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html#mapping-incidence-and-risk-with-a-spatial-regression-model"><i class="fa fa-check"></i>Mapping incidence and risk with a spatial regression model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html"><i class="fa fa-check"></i>Thursday October 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#spatial-data-as-point-patterns"><i class="fa fa-check"></i>Spatial data as point patterns</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#theoretical-framework-for-analyzingmodeling-point-pattern-data"><i class="fa fa-check"></i>Theoretical framework for analyzing/modeling point pattern data</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#working-with-point-pattern-data-using-functions-from-the-spatstat-package"><i class="fa fa-check"></i>Working with point pattern data using functions from the spatstat package</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#quantifying-the-spatial-intensity-of-events"><i class="fa fa-check"></i>Quantifying the spatial intensity of events</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html"><i class="fa fa-check"></i>Tuesday October 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#creating-ppp-and-owin-objects-from-simple-feature-data-frames"><i class="fa fa-check"></i>Creating <code>ppp</code> and <code>owin</code> objects from simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#estimating-spatial-intensity-as-a-function-of-distance"><i class="fa fa-check"></i>Estimating spatial intensity as a function of distance</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#covariate-trend-as-a-possible-confounding-factor"><i class="fa fa-check"></i>Covariate trend as a possible confounding factor</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html"><i class="fa fa-check"></i>Thursday October 27, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#estimating-the-relative-risk"><i class="fa fa-check"></i>Estimating the relative risk</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#estimating-second-moment-properties-of-events"><i class="fa fa-check"></i>Estimating second-moment properties of events</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#examples-of-clustered-events"><i class="fa fa-check"></i>Examples of clustered events</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html"><i class="fa fa-check"></i>Tuesday November 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#removing-duplicate-events-and-defining-the-domain"><i class="fa fa-check"></i>Removing duplicate events and defining the domain</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#determining-statistical-significance-of-clustering"><i class="fa fa-check"></i>Determining statistical significance of clustering</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#estimating-clustering-in-multi-type-event-locations"><i class="fa fa-check"></i>Estimating clustering in multi-type event locations</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#interpolating-output-from-a-distance-function"><i class="fa fa-check"></i>Interpolating output from a distance function</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#limitations-of-the-distance-functions"><i class="fa fa-check"></i>Limitations of the distance functions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html"><i class="fa fa-check"></i>Tuesday November 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#limitations-of-the-distance-functions-1"><i class="fa fa-check"></i>Limitations of the distance functions</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#modeling-point-pattern-data"><i class="fa fa-check"></i>Modeling point pattern data</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#fitting-and-interpreting-an-inhibition-model"><i class="fa fa-check"></i>Fitting and interpreting an inhibition model</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#fitting-and-interpreting-a-cluster-model"><i class="fa fa-check"></i>Fitting and interpreting a cluster model</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#assessing-how-well-the-model-fits"><i class="fa fa-check"></i>Assessing how well the model fits</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html"><i class="fa fa-check"></i>Thursday November 10, 2022</a>
<ul>
<li class="chapter" data-level="0.2" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html#fitting-a-log-gaussian-cox-model"><i class="fa fa-check"></i><b>0.2</b> Fitting a log-Gaussian Cox model</a></li>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html#assessing-how-well-the-model-fits-1"><i class="fa fa-check"></i>Assessing how well the model fits</a></li>
<li class="chapter" data-level="0.3" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html#example-from-my-research"><i class="fa fa-check"></i><b>0.3</b> Example from my research</a></li>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html#spatial-logistic-regression"><i class="fa fa-check"></i>Spatial logistic regression</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-10-2022-1.html"><a href="thursday-november-10-2022-1.html"><i class="fa fa-check"></i>Thursday November 10, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-10-2022-1.html"><a href="thursday-november-10-2022-1.html#spatial-data-interpolation"><i class="fa fa-check"></i>Spatial data interpolation</a></li>
<li class="chapter" data-level="" data-path="thursday-november-10-2022-1.html"><a href="thursday-november-10-2022-1.html#computing-the-sample-variogram"><i class="fa fa-check"></i>Computing the sample variogram</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html"><i class="fa fa-check"></i>Tuesday November 15, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#fitting-a-variogram-model-to-the-sample-variogram"><i class="fa fa-check"></i>Fitting a variogram model to the sample variogram</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#creating-an-interpolated-surface-with-the-method-of-kriging"><i class="fa fa-check"></i>Creating an interpolated surface with the method of kriging</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html"><i class="fa fa-check"></i>Thursday November 17, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#comparing-interpolation-methods"><i class="fa fa-check"></i>Comparing interpolation methods</a></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#evaluating-the-accuracy-of-the-interpolation"><i class="fa fa-check"></i>Evaluating the accuracy of the interpolation</a></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#block-cross-validation"><i class="fa fa-check"></i>Block cross validation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html"><i class="fa fa-check"></i>Thursday November 29, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html#interpolating-to-areal-units-block-kriging"><i class="fa fa-check"></i>Interpolating to areal units (block kriging)</a></li>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html#simulating-spatial-fields"><i class="fa fa-check"></i>Simulating spatial fields</a></li>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html#interpolating-multiple-variables"><i class="fa fa-check"></i>Interpolating multiple variables</a></li>
<li class="chapter" data-level="" data-path="thursday-november-29-2022.html"><a href="thursday-november-29-2022.html#machine-learning-for-spatial-interpolation"><i class="fa fa-check"></i>Machine learning for spatial interpolation</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GIS5122: Applied Spatial Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="tuesday-november-8-2022" class="section level1 unnumbered hasAnchor">
<h1>Tuesday November 8, 2022<a href="tuesday-november-8-2022.html#tuesday-november-8-2022" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>“Weeks of coding can save you hours of planning.”</strong> - Unknown</p>
<p>Today</p>
<ul>
<li>Limitations of distance functions</li>
<li>Modeling point pattern data</li>
<li>Fitting and interpreting an inhibition model</li>
<li>Fitting and interpreting a cluster model</li>
</ul>
<div id="limitations-of-the-distance-functions-1" class="section level2 unnumbered hasAnchor">
<h2>Limitations of the distance functions<a href="tuesday-november-8-2022.html#limitations-of-the-distance-functions-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The distance functions (<span class="math inline">\(G\)</span>, <span class="math inline">\(K\)</span>, etc) used in quantifying clustering are defined and estimated under the assumption that a stationary process produced the events. If this assumption is true then you can treat any sub-region of the domain as an independent and identically distributed (iid) sample from the entire domain.</p>
<p>If the spatial distribution of the locations is influenced by event interaction then the distance curves will deviate from the CSR model curves.</p>
<p>Two points to keep in mind:</p>
<ol style="list-style-type: decimal">
<li><p>A deviation from CSR detected by an distance function does not necessarily imply event interaction. Rather it could be the result of a non-stationary process.</p></li>
<li><p>A distance function characterizes the spatial arrangement of event locations ‘on average’ so variations in an interaction as a function of scale might be interpreted as CSR.</p></li>
</ol>
<p>As an example of this second point, here you generate event locations at random with <em>clustering</em> on a small scale and with <em>regularity</em> on a larger scale. On average the event locations will be indistinguishable from CSR, here as indicated by the <span class="math inline">\(K\)</span> function.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="tuesday-november-8-2022.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spatstat)</span></code></pre></div>
<pre><code>## Loading required package: spatstat.data</code></pre>
<pre><code>## Loading required package: spatstat.geom</code></pre>
<pre><code>## spatstat.geom 2.4-0</code></pre>
<pre><code>## Loading required package: spatstat.random</code></pre>
<pre><code>## spatstat.random 2.2-0</code></pre>
<pre><code>## Loading required package: spatstat.core</code></pre>
<pre><code>## Loading required package: nlme</code></pre>
<pre><code>## Loading required package: rpart</code></pre>
<pre><code>## spatstat.core 2.4-4</code></pre>
<pre><code>## Loading required package: spatstat.linnet</code></pre>
<pre><code>## spatstat.linnet 2.3-2</code></pre>
<pre><code>## 
## spatstat 2.3-4       (nickname: &#39;Watch this space&#39;) 
## For an introduction to spatstat, type &#39;beginner&#39;</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="tuesday-november-8-2022.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">0112</span>)</span>
<span id="cb14-2"><a href="tuesday-november-8-2022.html#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="tuesday-november-8-2022.html#cb14-3" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">rcell</span>(<span class="at">nx =</span> <span class="dv">15</span>)</span>
<span id="cb14-4"><a href="tuesday-november-8-2022.html#cb14-4" aria-hidden="true" tabindex="-1"></a>X <span class="sc">|&gt;</span></span>
<span id="cb14-5"><a href="tuesday-november-8-2022.html#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="at">main =</span> <span class="st">&quot;&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>There are two ‘local’ event clusters one in the north and one in the south. But overall the events appear to be separated from each other more than you might expect by chance.</p>
<p>Based on the <span class="math inline">\(K\)</span> curve you would conclude that the process generating the events is homogeneous Poisson.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="tuesday-november-8-2022.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb15-2"><a href="tuesday-november-8-2022.html#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="tuesday-november-8-2022.html#cb15-3" aria-hidden="true" tabindex="-1"></a>X <span class="sc">|&gt;</span></span>
<span id="cb15-4"><a href="tuesday-november-8-2022.html#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Kest</span>() <span class="sc">|&gt;</span></span>
<span id="cb15-5"><a href="tuesday-november-8-2022.html#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb15-6"><a href="tuesday-november-8-2022.html#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> iso)) <span class="sc">+</span></span>
<span id="cb15-7"><a href="tuesday-november-8-2022.html#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb15-8"><a href="tuesday-november-8-2022.html#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb15-9"><a href="tuesday-november-8-2022.html#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb15-10"><a href="tuesday-november-8-2022.html#cb15-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>The empirical curve (black line) coincides with the theoretical CSR line (red line) indicating CSR.</p>
<p>And the maximum absolute deviation test under the null hypothesis of CSR returns a large <span class="math inline">\(p\)</span>-value so you fail to reject the null.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="tuesday-november-8-2022.html#cb16-1" aria-hidden="true" tabindex="-1"></a>X <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="tuesday-november-8-2022.html#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mad.test</span>(<span class="at">fun =</span> Kest, </span>
<span id="cb16-3"><a href="tuesday-november-8-2022.html#cb16-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">nsim =</span> <span class="dv">99</span>)</span></code></pre></div>
<pre><code>## Generating 99 simulations of CSR  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
## 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,  99.
## 
## Done.</code></pre>
<pre><code>## 
##  Maximum absolute deviation test of CSR
##  Monte Carlo test based on 99 simulations
##  Summary function: K(r)
##  Reference function: theoretical
##  Alternative: two.sided
##  Interval of distance values: [0, 0.25]
##  Test statistic: Maximum absolute deviation
##  Deviation = observed minus theoretical
## 
## data:  X
## mad = 0.0023931, rank = 87, p-value = 0.87</code></pre>
<p>As an example of the first point, here you generate event locations that have no inter-event interactions but instead there is a trend in the spatial intensity.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="tuesday-november-8-2022.html#cb19-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">rpoispp</span>(<span class="cf">function</span>(x, y){ <span class="dv">300</span> <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="dv">3</span> <span class="sc">*</span> x) })</span>
<span id="cb19-2"><a href="tuesday-november-8-2022.html#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="tuesday-november-8-2022.html#cb19-3" aria-hidden="true" tabindex="-1"></a>X <span class="sc">|&gt;</span></span>
<span id="cb19-4"><a href="tuesday-november-8-2022.html#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="at">main =</span> <span class="st">&quot;&quot;</span>) </span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>By design there is a clear trend toward fewer events moving toward the east.</p>
<p>You compute and plot the <span class="math inline">\(K\)</span> function on these event locations.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="tuesday-november-8-2022.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb20-2"><a href="tuesday-november-8-2022.html#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="tuesday-november-8-2022.html#cb20-3" aria-hidden="true" tabindex="-1"></a>X <span class="sc">|&gt;</span></span>
<span id="cb20-4"><a href="tuesday-november-8-2022.html#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Kest</span>() <span class="sc">|&gt;</span></span>
<span id="cb20-5"><a href="tuesday-november-8-2022.html#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb20-6"><a href="tuesday-november-8-2022.html#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> iso)) <span class="sc">+</span></span>
<span id="cb20-7"><a href="tuesday-november-8-2022.html#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb20-8"><a href="tuesday-november-8-2022.html#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb20-9"><a href="tuesday-november-8-2022.html#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb20-10"><a href="tuesday-november-8-2022.html#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>The <span class="math inline">\(K\)</span> function indicates clustering but this is an artifact of the trend in the intensity.</p>
<p>In the case of a known trend in the spatial intensity, you need to use the <code>Kinhom()</code> function. For example, compare the uncertainty envelopes from a homogeneous and inhomogeneous Poisson process.</p>
<p>Start by plotting the output from the <code>envelope()</code> function with <code>fun = Kest</code>. The <code>global = TRUE</code> argument indicates that the envelopes are simultaneous rather than point-wise (<code>global = FALSE</code> which is the default). Point-wise envelopes assume the estimates are independent (not always a good assumption) across the range of distances so the standard errors will be smaller resulting in narrower bands.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="tuesday-november-8-2022.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">envelope</span>(X, </span>
<span id="cb21-2"><a href="tuesday-november-8-2022.html#cb21-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">fun =</span> Kest, </span>
<span id="cb21-3"><a href="tuesday-november-8-2022.html#cb21-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">nsim =</span> <span class="dv">999</span>, </span>
<span id="cb21-4"><a href="tuesday-november-8-2022.html#cb21-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">rank =</span> <span class="dv">1</span>, </span>
<span id="cb21-5"><a href="tuesday-november-8-2022.html#cb21-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">global =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb21-6"><a href="tuesday-november-8-2022.html#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb21-7"><a href="tuesday-november-8-2022.html#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> obs)) <span class="sc">+</span></span>
<span id="cb21-8"><a href="tuesday-november-8-2022.html#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">ymin =</span> lo, <span class="at">ymax =</span> hi), </span>
<span id="cb21-9"><a href="tuesday-november-8-2022.html#cb21-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb21-10"><a href="tuesday-november-8-2022.html#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb21-11"><a href="tuesday-november-8-2022.html#cb21-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">y =</span> theo), </span>
<span id="cb21-12"><a href="tuesday-november-8-2022.html#cb21-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb21-13"><a href="tuesday-november-8-2022.html#cb21-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb21-14"><a href="tuesday-november-8-2022.html#cb21-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## Generating 999 simulations of CSR  ...
## 1, 2, 3, ......10.........20.........30.........40.........50.........60........
## .70.........80.........90.........100.........110.........120.........130......
## ...140.........150.........160.........170.........180.........190.........200....
## .....210.........220.........230.........240.........250.........260.........270..
## .......280.........290.........300.........310.........320.........330.........340
## .........350.........360.........370.........380.........390.........400........
## .410.........420.........430.........440.........450.........460.........470......
## ...480.........490.........500.........510.........520.........530.........540....
## .....550.........560.........570.........580.........590.........600.........610..
## .......620.........630.........640.........650.........660.........670.........680
## .........690.........700.........710.........720.........730.........740........
## .750.........760.........770.........780.........790.........800.........810......
## ...820.........830.........840.........850.........860.........870.........880....
## .....890.........900.........910.........920.........930.........940.........950..
## .......960.........970.........980.........990........ 999.
## 
## Done.</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>After a distance of about .15 units the empirical curve (black line) is outside the uncertainty band indicating the events are more clustered than CSR.</p>
<p>However when you use the <code>fun = Kinhom</code> the empirical curve is completely inside the uncertainty band.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="tuesday-november-8-2022.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">envelope</span>(X, </span>
<span id="cb23-2"><a href="tuesday-november-8-2022.html#cb23-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">fun =</span> Kinhom, </span>
<span id="cb23-3"><a href="tuesday-november-8-2022.html#cb23-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">nsim =</span> <span class="dv">999</span>, </span>
<span id="cb23-4"><a href="tuesday-november-8-2022.html#cb23-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">rank =</span> <span class="dv">1</span>, </span>
<span id="cb23-5"><a href="tuesday-november-8-2022.html#cb23-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">global =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb23-6"><a href="tuesday-november-8-2022.html#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb23-7"><a href="tuesday-november-8-2022.html#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> obs)) <span class="sc">+</span></span>
<span id="cb23-8"><a href="tuesday-november-8-2022.html#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">ymin =</span> lo, <span class="at">ymax =</span> hi), </span>
<span id="cb23-9"><a href="tuesday-november-8-2022.html#cb23-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb23-10"><a href="tuesday-november-8-2022.html#cb23-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb23-11"><a href="tuesday-november-8-2022.html#cb23-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">y =</span> theo), </span>
<span id="cb23-12"><a href="tuesday-november-8-2022.html#cb23-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb23-13"><a href="tuesday-november-8-2022.html#cb23-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb23-14"><a href="tuesday-november-8-2022.html#cb23-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## Generating 999 simulations of CSR  ...
## 1, 2, 3, ......10.........20.........30.........40.........50.........60........
## .70.........80.........90.........100.........110.........120.........130......
## ...140.........150.........160.........170.........180.........190.........200....
## .....210.........220.........230.........240.........250.........260.........270..
## .......280.........290.........300.........310.........320.........330.........340
## .........350.........360.........370.........380.........390.........400........
## .410.........420.........430.........440.........450.........460.........470......
## ...480.........490.........500.........510.........520.........530.........540....
## .....550.........560.........570.........580.........590.........600.........610..
## .......620.........630.........640.........650.........660.........670.........680
## .........690.........700.........710.........720.........730.........740........
## .750.........760.........770.........780.........790.........800.........810......
## ...820.........830.........840.........850.........860.........870.........880....
## .....890.........900.........910.........920.........930.........940.........950..
## .......960.........970.........980.........990........ 999.
## 
## Done.</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>You conclude that the point pattern data are more consistent with an inhomogeneous Poisson process.</p>
<p>Let’s return to the Kansas tornadoes (EF2+). You import the data and create a point pattern object windowed by the state borders.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="tuesday-november-8-2022.html#cb25-1" aria-hidden="true" tabindex="-1"></a>Torn.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="at">dsn =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, </span>
<span id="cb25-2"><a href="tuesday-november-8-2022.html#cb25-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">&quot;1950-2020-torn-initpoint&quot;</span>)) <span class="sc">|&gt;</span></span>
<span id="cb25-3"><a href="tuesday-november-8-2022.html#cb25-3" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3082</span>) <span class="sc">|&gt;</span></span>
<span id="cb25-4"><a href="tuesday-november-8-2022.html#cb25-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(mag <span class="sc">&gt;=</span> <span class="dv">2</span>, yr <span class="sc">&gt;=</span> <span class="dv">1994</span>) <span class="sc">|&gt;</span></span>
<span id="cb25-5"><a href="tuesday-november-8-2022.html#cb25-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">rename</span>(<span class="at">EF =</span> mag) <span class="sc">|&gt;</span></span>
<span id="cb25-6"><a href="tuesday-november-8-2022.html#cb25-6" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(EF)</span></code></pre></div>
<pre><code>## Reading layer `1950-2020-torn-initpoint&#39; from data source 
##   `/Users/jameselsner/Desktop/ClassNotes/ASS-2022/data/1950-2020-torn-initpoint&#39; 
##   using driver `ESRI Shapefile&#39;
## Simple feature collection with 66244 features and 22 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -163.53 ymin: 17.7212 xmax: -64.7151 ymax: 61.02
## Geodetic CRS:  WGS 84</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="tuesday-november-8-2022.html#cb27-1" aria-hidden="true" tabindex="-1"></a>ST.ppp <span class="ot">&lt;-</span> Torn.sf <span class="sc">|&gt;</span></span>
<span id="cb27-2"><a href="tuesday-november-8-2022.html#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.ppp</span>() <span class="sc">|&gt;</span></span>
<span id="cb27-3"><a href="tuesday-november-8-2022.html#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unmark</span>()</span>
<span id="cb27-4"><a href="tuesday-november-8-2022.html#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="tuesday-november-8-2022.html#cb27-5" aria-hidden="true" tabindex="-1"></a>KS.sf <span class="ot">&lt;-</span> USAboundaries<span class="sc">::</span><span class="fu">us_states</span>(<span class="at">states =</span> <span class="st">&quot;Kansas&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb27-6"><a href="tuesday-november-8-2022.html#cb27-6" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_transform</span>(<span class="at">crs =</span> sf<span class="sc">::</span><span class="fu">st_crs</span>(Torn.sf)<span class="sc">$</span>proj4string)</span>
<span id="cb27-7"><a href="tuesday-november-8-2022.html#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="tuesday-november-8-2022.html#cb27-8" aria-hidden="true" tabindex="-1"></a>W <span class="ot">&lt;-</span> KS.sf <span class="sc">|&gt;</span></span>
<span id="cb27-9"><a href="tuesday-november-8-2022.html#cb27-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.owin</span>()</span>
<span id="cb27-10"><a href="tuesday-november-8-2022.html#cb27-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-11"><a href="tuesday-november-8-2022.html#cb27-11" aria-hidden="true" tabindex="-1"></a>ST.ppp <span class="ot">&lt;-</span> ST.ppp[W] <span class="sc">|&gt;</span></span>
<span id="cb27-12"><a href="tuesday-november-8-2022.html#cb27-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rescale</span>(<span class="at">s =</span> <span class="dv">1000</span>, </span>
<span id="cb27-13"><a href="tuesday-november-8-2022.html#cb27-13" aria-hidden="true" tabindex="-1"></a>          <span class="at">unitname =</span> <span class="st">&quot;km&quot;</span>)</span>
<span id="cb27-14"><a href="tuesday-november-8-2022.html#cb27-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-15"><a href="tuesday-november-8-2022.html#cb27-15" aria-hidden="true" tabindex="-1"></a>ST.ppp <span class="sc">|&gt;</span></span>
<span id="cb27-16"><a href="tuesday-november-8-2022.html#cb27-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>There are more tornado reports in the west than in the east, especially across the southern part of the state indicating the process producing the events is not homogeneous. This means there are other factors contributing to local event intensity.</p>
<p>Evidence for clustering must account for this inhomogeneity. Here you do this by computing the envelope around the inhomogeneous Ripley K function using the argument <code>fun = Kinhom</code>.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="tuesday-november-8-2022.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">envelope</span>(ST.ppp,</span>
<span id="cb28-2"><a href="tuesday-november-8-2022.html#cb28-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">fun =</span> Linhom,</span>
<span id="cb28-3"><a href="tuesday-november-8-2022.html#cb28-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">nsim =</span> <span class="dv">99</span>,</span>
<span id="cb28-4"><a href="tuesday-november-8-2022.html#cb28-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">rank =</span> <span class="dv">1</span>,</span>
<span id="cb28-5"><a href="tuesday-november-8-2022.html#cb28-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">global =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb28-6"><a href="tuesday-november-8-2022.html#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb28-7"><a href="tuesday-november-8-2022.html#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> obs)) <span class="sc">+</span></span>
<span id="cb28-8"><a href="tuesday-november-8-2022.html#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">ymin =</span> lo, <span class="at">ymax =</span> hi), </span>
<span id="cb28-9"><a href="tuesday-november-8-2022.html#cb28-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb28-10"><a href="tuesday-november-8-2022.html#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb28-11"><a href="tuesday-november-8-2022.html#cb28-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">y =</span> theo), </span>
<span id="cb28-12"><a href="tuesday-november-8-2022.html#cb28-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb28-13"><a href="tuesday-november-8-2022.html#cb28-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (km)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;K(r)&quot;</span>) <span class="sc">+</span></span>
<span id="cb28-14"><a href="tuesday-november-8-2022.html#cb28-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## Generating 99 simulations of CSR  ...
## 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
## 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
## 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,  99.
## 
## Done.</code></pre>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>The output reveals no evidence of clustering at distances less than about 70 km. At greater distances there is some evidence of regularity indicated by the black line below the red line and just outside the uncertainty ribbon. This is due to the fact that tornado reports are more common near cities and towns and cities and towns tend to be spread out more regular than CSR.</p>
<p>The variance stabilized Ripley <span class="math inline">\(K\)</span> function called the <span class="math inline">\(L\)</span> function is sometimes used instead of <span class="math inline">\(K\)</span>. <span class="math inline">\(L\)</span> is defined as</p>
<p><span class="math display">\[
\hat{L}(r) = \Big( \hat{K}(r)/\pi\Big)^{1/2}.
\]</span></p>
<p>For data that is CSR, the <span class="math inline">\(L\)</span> function has expected value <span class="math inline">\(r\)</span> and its variance is approximately constant in <span class="math inline">\(r\)</span>. A graph of <span class="math inline">\(r - \hat{L}(r)\)</span> against <span class="math inline">\(r\)</span> should follow a diagonal line with constant dispersion if the event locations follow a homogeneous Poisson process.</p>
</div>
<div id="modeling-point-pattern-data" class="section level2 unnumbered hasAnchor">
<h2>Modeling point pattern data<a href="tuesday-november-8-2022.html#modeling-point-pattern-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Models are helpful for trying to understanding the processes leading to the event locations when event interaction is suspected. Event interaction means that an event at one location changes the probability of an event nearby.</p>
<p>Cluster models can be derived by starting with a Poisson model. For example, you begin with a homogeneous Poisson model describing a set of events <span class="math inline">\(Y\)</span>. Then each individual event <span class="math inline">\(y_i\)</span> in <span class="math inline">\(Y\)</span> is considered a ‘parent’ that produces ‘offspring’ events (<span class="math inline">\(x_i\)</span>) according to some mechanism.</p>
<p>The resulting set of offspring forms clustered point pattern data <span class="math inline">\(X\)</span>. Said another way, the model is homogeneous Poisson at an unobserved level <span class="math inline">\(Y\)</span> (latent level) but clustered at the level of the observations (<span class="math inline">\(X\)</span>).</p>
<p>One example of this parent-child process is the Matern cluster model. Parent events come from a homogeneous Poisson process with intensity <span class="math inline">\(\kappa\)</span> and then each parent has a Poisson (<span class="math inline">\(\mu\)</span>) number of offspring that are independent and identically distributed (iid) within a radius <span class="math inline">\(r\)</span> centered on the parent.</p>
<p>For instance here you use the <code>rMatClust()</code> function from the {spatstat} package to produce a clustered <code>ppp</code> object. You use a disc radius of .1 units and an offspring rate equal to 5 (<code>mu = 5</code>).</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="tuesday-november-8-2022.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rMatClust</span>(<span class="at">kappa =</span> <span class="dv">10</span>, </span>
<span id="cb30-2"><a href="tuesday-november-8-2022.html#cb30-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">r =</span> .<span class="dv">1</span>, </span>
<span id="cb30-3"><a href="tuesday-november-8-2022.html#cb30-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">mu =</span> <span class="dv">5</span>) <span class="sc">|&gt;</span></span>
<span id="cb30-4"><a href="tuesday-november-8-2022.html#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="at">main =</span> <span class="st">&quot;&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>The result is a set of event locations and the process that produced them is described as <em>doubly Poisson</em>. You can vary <span class="math inline">\(\kappa\)</span>, <span class="math inline">\(r\)</span>, and <span class="math inline">\(\mu\)</span> to generate more or fewer events.</p>
<p>Other clustered Poisson models include:
- Thomas model: each cluster consists of a Poisson number of random events with each event having an isotropic Gaussian displacement from its parent.<br />
- Gauss-Poisson model: each cluster is either a single event or a pair of events.<br />
- Neyman-Scott model: the cluster mechanism is arbitrary.</p>
<p>A Cox model is a homogeneous Poisson model with a random intensity function. Let <span class="math inline">\(\Lambda(s)\)</span> be a function with non-negative values defined at all locations <span class="math inline">\(s\)</span> inside the domain. Then, conditional on <span class="math inline">\(\Lambda\)</span> let <span class="math inline">\(X\)</span> be a Poisson model with an intensity function <span class="math inline">\(\Lambda\)</span>. Then <span class="math inline">\(X\)</span> will be a sample from a Cox model.</p>
<p>An example of a Cox model is the mixed Poisson process in which a variable <span class="math inline">\(\Lambda\)</span> is generated from some distribution that allow only positive number and then, conditional on <span class="math inline">\(\Lambda\)</span>, a homogeneous point process is generated.</p>
<p>Following are two samples from a Cox point process.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="tuesday-november-8-2022.html#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">3042</span>)</span>
<span id="cb31-2"><a href="tuesday-november-8-2022.html#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb31-3"><a href="tuesday-november-8-2022.html#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>){</span>
<span id="cb31-4"><a href="tuesday-november-8-2022.html#cb31-4" aria-hidden="true" tabindex="-1"></a>  lambda <span class="ot">&lt;-</span> <span class="fu">rexp</span>(<span class="at">n =</span> <span class="dv">1</span>, <span class="at">rate =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">100</span>)</span>
<span id="cb31-5"><a href="tuesday-november-8-2022.html#cb31-5" aria-hidden="true" tabindex="-1"></a>  X <span class="ot">&lt;-</span> <span class="fu">rpoispp</span>(lambda)</span>
<span id="cb31-6"><a href="tuesday-november-8-2022.html#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(X)</span>
<span id="cb31-7"><a href="tuesday-november-8-2022.html#cb31-7" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="tuesday-november-8-2022.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div>
<p>The statistical moments of Cox models are defined in terms of the moments of <span class="math inline">\(\Lambda\)</span>. For instance, the intensity function of <span class="math inline">\(X\)</span> is <span class="math inline">\(\lambda(s)\)</span> = E[<span class="math inline">\(\Lambda(s)\)</span>], where E[] is the expected value.</p>
<p>Cox models are convenient for describing clustered point pattern data. A Cox model is over-dispersed relative to a Poisson model (i.e. the variance of the number of events falling in any region of size A, is greater than the mean number of events in those regions).</p>
<p>The Matern cluster model and the Thomas models are types of Cox models. Another common type of Cox model is the log-Gaussian Cox processes (LGCP) model in which the logarithm of <span class="math inline">\(\Lambda(s)\)</span> is a Gaussian random function.</p>
<p>If you have a way of generating samples from a random function <span class="math inline">\(\Lambda\)</span> of interest, then you can use the <code>rpoispp()</code> function to generate the Cox process. The intensity argument <code>lambda</code> of <code>rpoispp()</code> can be a function of x or y or a pixel image.</p>
<p>Another way to generate clustered point pattern data is by ‘thinning’. Thinning refers to deleting some of the events. With ‘independent thinning’ the fate of each event is independent of the fate of the other events. When independent thinning is applied to a homogeneous Poisson point pattern, the resulting point pattern consisting of the retained events is also Poisson.</p>
<p>An example of this is Matern’s Model I model. Here a homogeneous Poisson model first generates a point pattern <span class="math inline">\(Y\)</span>, then any event in <span class="math inline">\(Y\)</span> that lies closer than a distance <span class="math inline">\(r\)</span> from another event is deleted. This results in point pattern data whereby close neighbor events do not exist.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="tuesday-november-8-2022.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">rMaternI</span>(<span class="at">kappa =</span> <span class="dv">70</span>, </span>
<span id="cb33-2"><a href="tuesday-november-8-2022.html#cb33-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">r =</span> .<span class="dv">05</span>), <span class="at">main =</span> <span class="st">&quot;&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="tuesday-november-8-2022.html#cb34-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">rMaternI</span>(<span class="at">kappa =</span> <span class="dv">70</span>, </span>
<span id="cb34-2"><a href="tuesday-november-8-2022.html#cb34-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">r =</span> .<span class="dv">05</span>)</span>
<span id="cb34-3"><a href="tuesday-november-8-2022.html#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="tuesday-november-8-2022.html#cb34-4" aria-hidden="true" tabindex="-1"></a>X <span class="sc">|&gt;</span></span>
<span id="cb34-5"><a href="tuesday-november-8-2022.html#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Kest</span>() <span class="sc">|&gt;</span></span>
<span id="cb34-6"><a href="tuesday-november-8-2022.html#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-12-2.png" width="672" /></p>
<p>Changing <span class="math inline">\(\kappa\)</span> and <span class="math inline">\(r\)</span> will change the event intensity.</p>
<p>The various spatial models for event locations can be described with math. For instance, expanding on the earlier notation you write that a homogeneous Poisson model with intensity <span class="math inline">\(\lambda &gt; 0\)</span> has intensity</p>
<p><span class="math display">\[\lambda(s, x) = \lambda\]</span> where <span class="math inline">\(s\)</span> is any location in the window W and <span class="math inline">\(x\)</span> is the set of events.</p>
<p>Then the inhomogeneous Poisson model has conditional intensity</p>
<p><span class="math display">\[\lambda(s, x) = \lambda(s)\]</span>.
The intensity <span class="math inline">\(\lambda(s)\)</span> depends on a spatial trend or on an explanatory variable.</p>
<p>There is also a class of ‘Markov’ point process models that allow for clustering (or inhibition) due to event interaction. Markov refers to the fact that the interaction is limited to nearest neighbors. Said another way, a Markov point process generalizes a Poisson process in the case where events are pairwise dependent.</p>
<p>A Markov process with parameters <span class="math inline">\(\beta &gt; 0\)</span> and <span class="math inline">\(0 &lt; \gamma &lt; \infty\)</span> with interaction radius <span class="math inline">\(r &gt; 0\)</span> has conditional intensity <span class="math inline">\(\lambda(s, x)\)</span> given by</p>
<p><span class="math display">\[
\lambda(s, x) = \beta \gamma^{t(s, x)}
\]</span></p>
<p>where <span class="math inline">\(t(s, x)\)</span> is the number of events that lie within a distance <span class="math inline">\(r\)</span> of location <span class="math inline">\(s\)</span>.</p>
<p>Three cases:
- If <span class="math inline">\(\gamma = 1\)</span>, then <span class="math inline">\(\lambda(s, x) = \beta\)</span> No interaction between events, <span class="math inline">\(\beta\)</span> can vary with <span class="math inline">\(s\)</span>.
- If <span class="math inline">\(\gamma &lt; 1\)</span>, then <span class="math inline">\(\lambda(s, x) &lt; \beta\)</span>. Events inhibit nearby events.
- If <span class="math inline">\(\gamma &gt; 1\)</span>, then <span class="math inline">\(\lambda(s, x) &gt; \beta\)</span>. Events encourage nearby events.</p>
<p>Note the distinction between the interaction term <span class="math inline">\(\gamma\)</span> and the trend term <span class="math inline">\(\beta\)</span>. A similar distinction exists between autocorrelation <span class="math inline">\(\rho\)</span> and trend <span class="math inline">\(\beta\)</span> in spatial regression models.</p>
<p>More generally, you write the logarithm of the conditional intensity <span class="math inline">\(\log[\lambda(s, x)]\)</span> as linear expression with two components.</p>
<p><span class="math display">\[
\log\big[\lambda(s, x)\big] = \theta_1 B(s) + \theta_2 C(s, x)
\]</span></p>
<p>where the <span class="math inline">\(\theta\)</span>’s are model parameters that need to be estimated.</p>
<p>The term <span class="math inline">\(B(s)\)</span> depends only on location so it represents trend and explanatory variable (covariate) effects. It is the ‘systematic component’ of the model. The term <span class="math inline">\(C(s, x)\)</span> represents stochastic interactions (dependency) between events.</p>
</div>
<div id="fitting-and-interpreting-an-inhibition-model" class="section level2 unnumbered hasAnchor">
<h2>Fitting and interpreting an inhibition model<a href="tuesday-november-8-2022.html#fitting-and-interpreting-an-inhibition-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The {spatstat} family of packages contains functions for fitting statistical models to point pattern data. Models can include trend, explanatory variables, and event interactions of any order (not restricted to pairwise). Models are fit with the method of maximum likelihood and the method of minimum contrasts.</p>
<p>The method of maximum likelihood estimates the probability of the empirical <span class="math inline">\(K\)</span> curve given the theoretical curve for various parameter values. Parameter values are chosen so as to maximize the likelihood of the empirical curve.</p>
<p>The method of minimum contrasts derives a cost function as the difference between the theoretical and empirical <span class="math inline">\(K\)</span> curves. Parameter values for the theoretical curve are those that minimize this cost function.</p>
<p>The <code>ppm()</code> function from {spatstat} is used to fit a spatial point pattern model. The syntax has the form <code>ppm(X, formula, interaction, ...)</code> where <code>X</code> is the point pattern object of class <code>ppp</code>, <code>formula</code> describes the systematic (trend and covariate) part of the model, and <code>interaction</code> describes the stochastic dependence between events (e.g., Matern process).</p>
<p>Recall a plot the Swedish pine saplings. There was no indication of a trend (no systematic variation in the intensity of saplings).</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="tuesday-november-8-2022.html#cb35-1" aria-hidden="true" tabindex="-1"></a>SP <span class="ot">&lt;-</span> swedishpines</span>
<span id="cb35-2"><a href="tuesday-november-8-2022.html#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="tuesday-november-8-2022.html#cb35-3" aria-hidden="true" tabindex="-1"></a>SP <span class="sc">|&gt;</span></span>
<span id="cb35-4"><a href="tuesday-november-8-2022.html#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="tuesday-november-8-2022.html#cb36-1" aria-hidden="true" tabindex="-1"></a>SP <span class="sc">|&gt;</span></span>
<span id="cb36-2"><a href="tuesday-november-8-2022.html#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">intensity</span>()</span></code></pre></div>
<pre><code>## [1] 0.007395833</code></pre>
<p>There is no obvious spatial trend in the distribution of saplings and the average intensity is .0074 saplings per unit area.</p>
<p>A plot of the Ripley’s <span class="math inline">\(K\)</span> function indicated some regularity relative to CSR for distances between .5 and 1.2 meters.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="tuesday-november-8-2022.html#cb38-1" aria-hidden="true" tabindex="-1"></a>SP <span class="sc">|&gt;</span></span>
<span id="cb38-2"><a href="tuesday-november-8-2022.html#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Kest</span>(<span class="at">correction =</span> <span class="st">&quot;iso&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb38-3"><a href="tuesday-november-8-2022.html#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>The red dashed line is the <span class="math inline">\(K\)</span> curve under CSR. The black line is the empirical curve. At lag distances of between 5 and 15 units the empirical curve is below the CSR curve indicating there are fewer events within other events at those scales than would be expected by chance.</p>
<p>This suggests a process of between-event inhibition. A simple inhibition model is a Strauss process when the inhibition is constant with a fixed radius (r) around each event. The amount of inhibition ranges between zero (100% chance of a nearby event) to complete (0% chance of a nearby event). In the case of no inhibition the process is equivalent to a homogeneous Poisson process.</p>
<p>If you assume the inhibition process is constant across the domain with a fixed interaction radius (r), then you can fit a Strauss model to the data. You use the <code>ppm()</code> function from the {spatstat} package and include the point pattern data as the first argument. You set the trend term to a constant (implying a stationary process) with the argument <code>trend ~ 1</code> and the interaction radius to 10 units with the argument <code>interaction = Strauss(r = 10)</code>. Finally you use a border correction out to a distance of 10 units from the window with the <code>rbord =</code> argument.</p>
<p>Save the output in the object called <code>model.in</code> (inhibition model).</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="tuesday-november-8-2022.html#cb39-1" aria-hidden="true" tabindex="-1"></a>model.in <span class="ot">&lt;-</span> <span class="fu">ppm</span>(SP, </span>
<span id="cb39-2"><a href="tuesday-november-8-2022.html#cb39-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">trend =</span> <span class="sc">~</span> <span class="dv">1</span>, </span>
<span id="cb39-3"><a href="tuesday-november-8-2022.html#cb39-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">interaction =</span> <span class="fu">Strauss</span>(<span class="at">r =</span> <span class="dv">10</span>), </span>
<span id="cb39-4"><a href="tuesday-november-8-2022.html#cb39-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">rbord =</span> <span class="dv">10</span>)</span></code></pre></div>
<p>The value for <code>r</code> in the <code>Strauss()</code> function is based on our visual inspection of the plot of <code>Kest()</code>. A value is chosen to be the distance at which there is the largest departure from a CSR model.</p>
<p>You inspect the model parameters by typing the object name.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="tuesday-november-8-2022.html#cb40-1" aria-hidden="true" tabindex="-1"></a>model.in</span></code></pre></div>
<pre><code>## Stationary Strauss process
## 
## First order term:  beta = 0.07567442
## 
## Interaction distance:    10
## Fitted interaction parameter gamma:  0.2752048
## 
## Relevant coefficients:
## Interaction 
##    -1.29024 
## 
## For standard errors, type coef(summary(x))</code></pre>
<p>The first-order term (<code>beta</code>) has a value of .0757. This is the intensity of the ‘proposal’ events. Beta exceeds the average intensity by a factor of ten.</p>
<p>Recall the intensity of the events is obtained as</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="tuesday-november-8-2022.html#cb42-1" aria-hidden="true" tabindex="-1"></a>SP <span class="sc">|&gt;</span></span>
<span id="cb42-2"><a href="tuesday-november-8-2022.html#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">intensity</span>()</span></code></pre></div>
<pre><code>## [1] 0.007395833</code></pre>
<p>The interaction parameter (<code>gamma</code>) is .275. It is less than one, indicating an inhibition process. The logarithm of gamma, called the interaction coefficient (<code>Interaction</code>), is -1.29. Interaction coefficients less than zero imply inhibition.</p>
<p>A table with the coefficients including the standard errors and uncertainty ranges is obtained with the <code>coef()</code> method.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="tuesday-november-8-2022.html#cb44-1" aria-hidden="true" tabindex="-1"></a>model.in <span class="sc">|&gt;</span></span>
<span id="cb44-2"><a href="tuesday-november-8-2022.html#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>() <span class="sc">|&gt;</span></span>
<span id="cb44-3"><a href="tuesday-november-8-2022.html#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coef</span>()</span></code></pre></div>
<pre><code>##              Estimate      S.E.   CI95.lo    CI95.hi Ztest      Zval
## (Intercept) -2.581315 0.4524077 -3.468018 -1.6946123   *** -5.705728
## Interaction -1.290240 0.2375515 -1.755832 -0.8246475   *** -5.431411</code></pre>
<p>The output includes the <code>Interaction</code> coefficient along with it’s standard error (<code>S.E.</code>) and the associated 95% uncertainty interval. The ratio of the <code>Interaction</code> coefficient to its standard error is the <code>Zval</code>. A large z-value (in absolute magnitude) translates to a low <span class="math inline">\(p\)</span>-value and a rejection of the null hypothesis of no interaction between events.</p>
<p>Output also shows the value for the <code>(Intercept)</code> term. It is the logarithm of the beta value, so exp(-2.58) = .0757 is the intensity of the proposal events.</p>
<p>You interpret the model output as follows. The process producing the spatial pattern of pine saplings is such that you should see .0757 saplings per unit area [unobserved (latent) rate].</p>
<p>But because of event inhibition, where saplings nearby other saplings fail to grow, the number of saplings is reduced to .0074 per unit area. Thus the spatial pattern is suggestive of sibling-sibling interaction. Adults have many offspring, but only some survive due to limited resources.</p>
</div>
<div id="fitting-and-interpreting-a-cluster-model" class="section level2 unnumbered hasAnchor">
<h2>Fitting and interpreting a cluster model<a href="tuesday-november-8-2022.html#fitting-and-interpreting-a-cluster-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s compare this inhibition model with a cluster model for describing the Lansing Woods maple trees (in the <code>ppp</code> object called <code>lansing</code> from the {spatstat} package).</p>
<p>Start by extracting the events marked as <code>maple</code> and putting them in a separate <code>ppp</code> object called <code>MT</code>.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="tuesday-november-8-2022.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(lansing)</span>
<span id="cb46-2"><a href="tuesday-november-8-2022.html#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lansing)</span></code></pre></div>
<pre><code>## Marked planar point pattern:  2251 points
## Average intensity 2251 points per square unit (one unit = 924 feet)
## 
## *Pattern contains duplicated points*
## 
## Coordinates are given to 3 decimal places
## i.e. rounded to the nearest multiple of 0.001 units (one unit = 924 feet)
## 
## Multitype:
##          frequency proportion intensity
## blackoak       135 0.05997335       135
## hickory        703 0.31230560       703
## maple          514 0.22834300       514
## misc           105 0.04664594       105
## redoak         346 0.15370950       346
## whiteoak       448 0.19902270       448
## 
## Window: rectangle = [0, 1] x [0, 1] units
## Window area = 1 square unit
## Unit of length: 924 feet</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="tuesday-november-8-2022.html#cb48-1" aria-hidden="true" tabindex="-1"></a>MT <span class="ot">&lt;-</span> lansing <span class="sc">|&gt;</span></span>
<span id="cb48-2"><a href="tuesday-november-8-2022.html#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">subset</span>(marks <span class="sc">==</span> <span class="st">&quot;maple&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb48-3"><a href="tuesday-november-8-2022.html#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unmark</span>()</span>
<span id="cb48-4"><a href="tuesday-november-8-2022.html#cb48-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-5"><a href="tuesday-november-8-2022.html#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(MT)</span></code></pre></div>
<pre><code>## Planar point pattern:  514 points
## Average intensity 514 points per square unit (one unit = 924 feet)
## 
## Coordinates are given to 3 decimal places
## i.e. rounded to the nearest multiple of 0.001 units (one unit = 924 feet)
## 
## Window: rectangle = [0, 1] x [0, 1] units
## Window area = 1 square unit
## Unit of length: 924 feet</code></pre>
<p>There are 514 maple trees over this square region (924 x 924 square feet).</p>
<p>Plots of tree locations and the local intensity function help you examine the first-order property of these data.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="tuesday-november-8-2022.html#cb50-1" aria-hidden="true" tabindex="-1"></a>MT <span class="sc">|&gt;</span></span>
<span id="cb50-2"><a href="tuesday-november-8-2022.html#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">density</span>() <span class="sc">|&gt;</span></span>
<span id="cb50-3"><a href="tuesday-november-8-2022.html#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span>
<span id="cb50-4"><a href="tuesday-november-8-2022.html#cb50-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-5"><a href="tuesday-november-8-2022.html#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(MT, <span class="at">add =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>There are maple trees across the southern and central parts of the study domain.</p>
<p>A plot of the <span class="math inline">\(G\)</span> function summarizes the second-order properties under the assumption of no trend.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="tuesday-november-8-2022.html#cb51-1" aria-hidden="true" tabindex="-1"></a>G.df <span class="ot">&lt;-</span> MT <span class="sc">|&gt;</span></span>
<span id="cb51-2"><a href="tuesday-november-8-2022.html#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Gest</span>() <span class="sc">|&gt;</span></span>
<span id="cb51-3"><a href="tuesday-november-8-2022.html#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb51-4"><a href="tuesday-november-8-2022.html#cb51-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(r <span class="sc">&lt;</span> .<span class="dv">033</span>) <span class="sc">|&gt;</span></span>
<span id="cb51-5"><a href="tuesday-november-8-2022.html#cb51-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">r =</span> r <span class="sc">*</span> <span class="dv">924</span>)</span>
<span id="cb51-6"><a href="tuesday-november-8-2022.html#cb51-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-7"><a href="tuesday-november-8-2022.html#cb51-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(G.df, <span class="fu">aes</span>(<span class="at">x =</span> r, <span class="at">y =</span> km)) <span class="sc">+</span></span>
<span id="cb51-8"><a href="tuesday-november-8-2022.html#cb51-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb51-9"><a href="tuesday-november-8-2022.html#cb51-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> theo), <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb51-10"><a href="tuesday-november-8-2022.html#cb51-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">18</span>, <span class="at">lty =</span> <span class="st">&#39;dashed&#39;</span>) <span class="sc">+</span></span>
<span id="cb51-11"><a href="tuesday-november-8-2022.html#cb51-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lag distance (ft)&quot;</span>) <span class="sc">+</span> </span>
<span id="cb51-12"><a href="tuesday-november-8-2022.html#cb51-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;G(r): Cumulative % of events within a distance r of another maple&quot;</span>) <span class="sc">+</span></span>
<span id="cb51-13"><a href="tuesday-november-8-2022.html#cb51-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>The plot provides evidence that the maple trees are clustered. The empirical curve is above the theoretical curve. About 74% of the maple trees are within 18 feet of another maple tree (vertical blue line). If the trees were arranged as CSR then only 49% of the trees would be within 18 feet of another maple.</p>
<p>Is the clustering due to interaction or trends (or both)?</p>
<p>You start the modeling process by investigating event interaction using a stationary Strauss model with interaction radius of .019 units (18 ft).</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="tuesday-november-8-2022.html#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ppm</span>(MT, </span>
<span id="cb52-2"><a href="tuesday-november-8-2022.html#cb52-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">trend =</span> <span class="sc">~</span> <span class="dv">1</span>, </span>
<span id="cb52-3"><a href="tuesday-november-8-2022.html#cb52-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">interaction =</span> <span class="fu">Strauss</span>(<span class="at">r =</span> .<span class="dv">019</span>))</span></code></pre></div>
<pre><code>## Stationary Strauss process
## 
## First order term:  beta = 344.625
## 
## Interaction distance:    0.019
## Fitted interaction parameter gamma:  1.7253743
## 
## Relevant coefficients:
## Interaction 
##    0.545444 
## 
## For standard errors, type coef(summary(x))
## 
## *** Model is not valid ***
## *** Interaction parameters are outside valid range ***</code></pre>
<p>Here the first order term beta is 345. It is the ‘latent’ rate (intensity) of maple trees per unit area. This rate is less than the 514 actual maple trees. The fitted interaction parameter (gamma) is 1.72. It is greater than one since the trees are clustered. The logarithm of gamma is positive at .545.</p>
<p>The model is interpreted as follows. The process producing the maple trees is such that you expect to see about 345 maples. Because of clustering where maple trees are more likely in the vicinity of other maple trees, the number of maples increases to the observed 514 per unit area.</p>
<p>Here the physical explanation could be event interaction. But it also could be inhibition with hickory trees. You can model this using a term for cross event type interaction.</p>
<p>The Strauss process is for inhibition models. So although you use it here for diagnostics, you need to fit a cluster model (thus the <code>*** Model is not valid ***</code> warning).</p>
<p>For a cluster model the spatial intensity <span class="math display">\[\lambda(s) = \kappa \mu(s)\]</span> where <span class="math inline">\(\kappa\)</span> is the average number of clusters and where <span class="math inline">\(\mu(s)\)</span> is the spatial varying cluster size (number events per cluster).</p>
<p>Cluster models are fit using the <code>kppm()</code> function from the {spatstat} package. Here you specify the cluster process with <code>clusters = "Thomas"</code>.</p>
<p>That means each cluster consists of a Poisson number of maple trees and where each tree in the cluster is placed randomly about the ‘parent’ tree with intensity that varies inversely with distance from the parent as a Gaussian function.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="tuesday-november-8-2022.html#cb54-1" aria-hidden="true" tabindex="-1"></a>( model.cl <span class="ot">&lt;-</span> <span class="fu">kppm</span>(MT, </span>
<span id="cb54-2"><a href="tuesday-november-8-2022.html#cb54-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">trend =</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb54-3"><a href="tuesday-november-8-2022.html#cb54-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">clusters =</span> <span class="st">&quot;Thomas&quot;</span>) )</span></code></pre></div>
<pre><code>## Stationary cluster point process model
## Fitted to point pattern dataset &#39;MT&#39;
## Fitted by minimum contrast
##  Summary statistic: K-function
## 
## Uniform intensity:   514
## 
## Cluster model: Thomas process
## Fitted cluster parameters:
##       kappa       scale 
## 21.74344366  0.06752959 
## Mean cluster size:  23.63931 points</code></pre>
<p>Here <span class="math inline">\(\kappa\)</span> is 21.75 and <span class="math inline">\(\bar \mu(s)\)</span> (mean cluster size) is 23.6 trees. The product of kappa and the mean cluster size is the number of events. The cluster model describes a parent-child process. The number of parents is about 22. The distribution of the parents can be described as CSR. Each parent produces about 24 offspring distributed randomly about the location of the parent within a characteristic distance. Note: The physical process might be different from the statistical process used to describe it.</p>
<p>The cluster scale parameter indicating the characteristic size (area units) of the clusters is <span class="math inline">\(\sigma^2\)</span>.</p>
<p>A <code>plot()</code> method verifies that the cluster process statistically ‘explains’ the spatial correlation.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="tuesday-november-8-2022.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model.cl, </span>
<span id="cb56-2"><a href="tuesday-november-8-2022.html#cb56-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">what =</span> <span class="st">&quot;statistic&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>The model (black line) is very close to the cluster process line (red dashed line). Also note that it is far from the CSR model (green line).</p>
<p>The spatial scale of the clustering is visualized with the <code>what = "cluster"</code> argument.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="tuesday-november-8-2022.html#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model.cl, </span>
<span id="cb57-2"><a href="tuesday-november-8-2022.html#cb57-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">what =</span> <span class="st">&quot;cluster&quot;</span>)</span></code></pre></div>
<p><img src="ASS-2022_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>The color ramp is the spatial intensity (number of events per unit area) about an arbitrary single event revealing the spatial scale and extent of clustering.</p>
</div>
<div id="assessing-how-well-the-model-fits" class="section level2 unnumbered hasAnchor">
<h2>Assessing how well the model fits<a href="tuesday-november-8-2022.html#assessing-how-well-the-model-fits" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Workflow in fitting spatial event location models</p>
<ul>
<li>Analyze/plot the intensity and nearest neighbor statistics</li>
<li>Select a model including trend, interaction distance, etc informed by the results of step 1</li>
<li>Choose an inhibition or cluster model</li>
<li>Fit the model to the event pattern</li>
<li>Assess how well the model fits the data by generating samples and comparing statistics from the samples with the statistics from the original data</li>
</ul>
<p>The model should be capable of generating samples of event locations that are statistically indistinguishable from the actual event locations.</p>
<p>Note: The development of spatial point process methods has largely been theory driven (not by actual problems/data). More work needs to be done to apply the theory to environmental data with spatial heterogeneity, properties at the individual level (marks), and with time information.</p>
<p>You produce samples of event locations with the <code>simulate()</code> function applied to the model object.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tuesday-november-1-2022.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="thursday-november-10-2022.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
